"""v20.25 — deepen exact-live Transoral Laser Microsurgery for Laryngeal Cancer.

Durable laryngeal anatomy and operative-selection principles are cross-referenced against
the connected Cummings 7e, Pasha 6e and K.J. Lee 12e texts. Current NCI, ELS, FDA,
laser-fire safety and peer-reviewed margin/outcome evidence are recorded separately.
"""
from concept_check_board_repair_v177 import _find_module

QIDS = ("cc-v112-rec-head-neck-oncology-transoral-laser-microsurgery-for-laryngeal-cancer",)
CID = "v6-head-neck-oncology-transoral-laser-microsurgery-for-laryngeal-cancer"
TOPIC = "Transoral Laser Microsurgery for Laryngeal Cancer"

SOURCE_REFS_V225 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive copy id 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t; laryngeal cancer, conservation laryngeal surgery and transoral laser principles; cross-check attempted 2026-09-11. The complete 765 MB PDF exceeds the connector direct-fetch limit, so no page-level quotation is claimed; durable principles were triangulated with the connected Pasha and K.J. Lee texts and current authoritative evidence.","role":"durable laryngeal anatomy/oncologic surgery framework and source provenance; connector-size limitation recorded explicitly"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52; Head and Neck Cancer/Laryngeal Cancer sections, including TLM and partial-laryngectomy contraindication framework; checked 2026-09-11.","role":"durable resident/board anatomy and selection cross-check: endoscopic laser partial laryngectomy, mobility/cartilage/subglottic-extension limitations and Broyles/anterior-commissure concepts"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; Chapter 44 Tumors of the Larynx, TLM pp. 791-792; checked 2026-09-11.","role":"durable operative cross-check: TLM patient selection, negative-margin priority and shift from open partial laryngectomy to endoscopic resection"},
    {"type":"guideline","citation":"National Cancer Institute. Laryngeal Cancer Treatment (PDQ), health-professional version; current web review checked 2026-09-11.","role":"current treatment boundary: surgery and radiation are standard options; selected early glottic cancers may be treated with endoscopic CO2 laser excision, with multidisciplinary selection based on stage, comorbidity and function"},
    {"type":"consensus_statement","citation":"Piazza C, Paderno A, Sjogren EV, et al. Salvage carbon dioxide transoral laser microsurgery for laryngeal cancer after (chemo)radiotherapy: a European Laryngological Society consensus statement. Eur Arch Otorhinolaryngol. 2021;278:4373-4381. PMID: 34226992.","role":"current society boundary: salvage CO2 TOLMS after RT/CRT requires strict selection, workup, exposure and follow-up and is not interchangeable with primary early-stage TLM"},
    {"type":"systematic_review","citation":"De Virgilio A, et al. Prognostic significance of surgical margins in laryngeal cancer treated by transoral laser microsurgery: a systematic review and meta-analysis. Acta Otorhinolaryngol Ital. 2025;45(Suppl 1):S71-S86. PMID: 40400378.","role":"current margin evidence: positive margins worsen disease-free survival while local-control and overall-survival effects remain uncertain; reinforces risk-pattern interpretation rather than a universal cutoff"},
    {"type":"systematic_review","citation":"Positive Margin Rate Following Transoral Surgery in T2-T3 Laryngeal Carcinoma - a Systematic Review and Meta-Analysis. 2026. PMID: 42585753.","role":"current higher-stage evidence: pooled positive-margin burden is substantial and heterogeneous; outcome effect remains uncertain"},
    {"type":"cohort","citation":"Management and Oncologic Outcomes of Close and Positive Margins after Transoral CO2 Laser Microsurgery for Early Glottic Carcinoma. 2023. PMID: 36900281.","role":"margin-pattern application: close/deep and positive/deep margins carry more recurrence risk; re-resection, radiation and surveillance are context-specific options"},
    {"type":"systematic_review","citation":"Long-Term Laryngeal Function and Quality of Life Following Treatment of Early Glottic Cancer: A Meta-Analysis. 2024. PMID: 39403814.","role":"functional evidence boundary: TLM versus RT long-term patient-reported voice/QOL outcomes are broadly comparable with high heterogeneity"},
    {"type":"systematic_review","citation":"Survival Outcomes of Transoral Microsurgery in T3/T4a Laryngeal Tumors: Systematic Review and Meta-Analysis. Laryngoscope. 2025;135:15-26. PMID: 39140205.","role":"advanced-disease boundary: selected advanced cases can be treated transorally in experienced settings, but results are heterogeneous and advanced glottic disease is not a routine default TLM indication"},
    {"type":"fda","citation":"U.S. Food and Drug Administration. Guidance on the Content and Organization of a Premarket Notification for a Medical Laser; includes 21 CFR 874.4500 ENT microsurgical carbon dioxide laser intended for surgical excision of ENT tissue, including lesions/tumors of vocal cords and adjacent areas; checked 2026-09-11.","role":"regulatory distinction: FDA device intended use/labeling governs the laser; it does not substitute for oncologic patient/tumor selection or create a universal TLM cancer indication"},
    {"type":"safety_guidance","citation":"Anesthesia Patient Safety Foundation. OR Fire Safety Video Commentary for the ENT Surgeon; plus APSF 2025 fire-risk update; checked 2026-09-11.","role":"shared-airway laser safety: oxidizer-ignition-fuel triad, laser-resistant airway strategy when intubated, minimize oxidizer exposure, explicit team fire plan and immediate airway-fire rescue"},
]

PROMPT = """A 64-year-old patient with a biopsy-proven glottic squamous cell carcinoma is being considered for transoral laser microsurgery. The lesion approaches the anterior commissure, exposure is borderline on suspension laryngoscopy, and the team wants a single-modality larynx-preservation treatment. As the senior resident, explain how you decide whether TLM is oncologically appropriate, how tumor anatomy and exposure determine the resection, how you manage margins and the neck, what functional tradeoffs must be anticipated, how laser/shared-airway safety changes the setup, and what intraoperative or pathologic finding should make you stop, re-resect, convert, or choose another treatment."""

ANSWER = """Foundation — transoral laser microsurgery (TLM/TOLMS) is an oncologic resection approach, not an indication by itself. The decision starts with tumor extent, laryngeal function, ability to obtain reliable endoscopic exposure, expected margin control, neck disease, patient comorbidity, and the functional tradeoff versus radiation or open surgery. For early glottic cancer, both endoscopic CO2 laser excision and radiation are established single-modality options; the best choice is multidisciplinary and patient-specific. The laser is a cutting/coagulating tool. It does not make a poorly selected tumor resectable and it does not compensate for inadequate exposure.

ANATOMIC FRAMEWORK — map the lesion in three dimensions before touching the laser. For glottic disease, define true-vocal-fold surface and depth, anterior commissure involvement, posterior extension toward the arytenoid/cricoarytenoid unit, subglottic extension, and whether mobility is impaired. Deep spread toward the paraglottic space or cartilage changes the oncologic problem. The anterior commissure deserves special attention because exposure can be difficult and recurrence risk is higher in several series. Broyles' tendon and the relationship of the anterior commissure to thyroid cartilage are durable anatomic concepts, but modern management should not reduce this region to a simplistic automatic-cartilage-invasion rule. For supraglottic lesions, understand pre-epiglottic/paraglottic spread and separately plan the clinically occult or involved neck.

SELECTION — classic high-value TLM candidates are selected Tis/T1 and favorable T2 glottic cancers in which the whole intended resection can be exposed and a functionally acceptable negative-margin operation is realistic. Selected supraglottic tumors can also be managed transorally in experienced hands. More advanced T3/T4a disease has been treated with TLM in specialized series, but current evidence does not justify presenting that as a routine default; advanced glottic tumors in particular have less favorable recurrence outcomes in pooled data. Impaired vocal-fold mobility, major cartilage invasion, substantial subglottic extension, bulky deep-space disease, inability to expose the tumor, or a resection whose functional cost defeats the larynx-preservation goal should push the team toward another strategy.

EXPOSURE IS AN ONCOLOGIC VARIABLE — perform suspension laryngoscopy and obtain a stable line of sight before committing to definitive laser resection. Dental anatomy, mandibular restriction, cervical extension, tongue-base bulk, tumor location and anterior-commissure access can make exposure inadequate. Prospective data associate suboptimal exposure with positive margins. The senior rule is simple: if you cannot see the intended peripheral and deep resection planes, do not solve the exposure problem by taking blind laser bites. Improve exposure, change the laryngoscope or positioning, stage or abort the transoral attempt, or choose radiation/open surgery as appropriate. Poor exposure is an oncologic reason to stop, not a technical inconvenience.

EXTENT OF RESECTION — the European Laryngological Society cordectomy framework is useful language for describing how much vocal-fold tissue is removed; it is not itself a cancer stage. Resection depth should match tumor depth. A superficial lesion should not automatically receive a function-destroying deep cordectomy, while suspected vocalis invasion cannot be treated as a mucosal stripping procedure. As excision becomes deeper and wider, voice morbidity generally increases. Discuss that tradeoff preoperatively rather than calling every larynx-preserving operation function-preserving.

MARGINS — orientation and communication with pathology matter as much as the laser. Label the specimen and/or directed margin biopsies so the team can distinguish superficial from deep risk. Thermal artifact, specimen shrinkage, piecemeal technique and different institutional definitions of close complicate interpretation, so there is no universal millimeter cutoff across every TLM series. Current evidence makes a positive deep margin or multiple concerning margins more worrisome than a trivial superficial/thermal-artifact question. A 2025 meta-analysis of 26 studies and 5,463 patients found positive margins associated with worse disease-free survival, while effects on local control and overall survival remained uncertain. A 2026 meta-analysis of T2-T3 transoral resections found a positive-margin rate around 22% with substantial heterogeneity and uncertain outcome effects. These data reinforce selection and margin discipline rather than a one-number rule.

WHAT TO DO WITH A CLOSE OR POSITIVE MARGIN — first determine what the margin means: superficial versus deep, focal versus multiple, interpretable versus thermally distorted, and whether visible residual tumor remains. Obvious residual disease is not a surveillance problem. When a meaningful deep or multiple positive margin is suspected, options include prompt endoscopic re-resection/enlargement when exposure and function remain acceptable, radiation in selected settings, or conversion to a more definitive surgical strategy. Some early-glottic series support close surveillance for selected superficial or close margins because disease-specific survival and laryngeal preservation can remain high, but other data show worse recurrence-free survival and especially higher recurrence risk with close/deep or positive/deep margins. Therefore positive margin equals automatic total laryngectomy and positive margin equals observe everyone are both wrong.

AIRWAY AND LASER SAFETY — shared-airway planning is part of the operation. Before activation, surgeon and anesthesia team should explicitly agree on airway device/ventilation technique, laser mode, oxidizer strategy, protection of combustible materials, and what will happen if fire occurs. FDA guidance classifies ENT microsurgical CO2 lasers as devices intended for surgical excision of ENT tissue, including lesions/tumors of the vocal cords and adjacent areas; individual devices have manufacturer-specific cleared indications and instructions. Device clearance does not decide which laryngeal cancer should receive TLM. For laser airway work, use the institution's laser-safe airway strategy when an endotracheal tube is present, minimize oxidizer concentration to the lowest level compatible with safe oxygenation, avoid nitrous oxide, protect cuffs/adjacent combustible material according to device and institutional protocols, and keep saline immediately available. APSF fire-prevention guidance emphasizes the oxidizer–ignition–fuel triad and the particular risk of airway laser surgery.

AIRWAY FIRE RESCUE — if an airway fire is suspected, STOP laser energy and the procedure, stop/disconnect oxidizer flow, remove the burning airway device and other burning material from the airway, extinguish with saline/water, then re-establish ventilation with a safe device and assess the airway, typically including bronchoscopy after stabilization. Do not continue lasing while debating whether a flash was really a fire. This must remain consistent with the repository's existing shared-airway fire rescue gate.

BLEEDING AND DEEP-DANGER DECISIONS — laser hemostasis can create false confidence. Know where the lesion sits relative to larger vessels, particularly in supraglottic work, and do not pursue uncontrolled deep bleeding blindly through a narrow laryngoscope. Stop, improve exposure, use appropriate endoscopic hemostatic tools, and escalate the airway or approach when necessary. Thermal injury near cartilage, cricoarytenoid structures and uninvolved mucosa can worsen edema, stenosis, aspiration or functional loss. The senior resident should be able to say when the safest oncologic choice is to stop the transoral operation rather than extend thermal injury into anatomy that cannot be safely controlled.

NECK MANAGEMENT — TLM treats the primary site; it does not erase regional metastatic risk. Early glottic lesions have relatively low occult nodal risk, but supraglottic cancers have richer lymphatic drainage and may require elective or therapeutic neck treatment according to subsite, T/N stage and the overall treatment plan. A technically perfect transoral primary resection with an ignored at-risk neck is not complete regional oncologic care.

FUNCTIONAL COUNSELING — compare the entire treatment package, not just the presence or absence of an external incision. TLM can offer short treatment, repeatability in selected recurrences and laryngeal preservation, but increasing cordectomy extent can worsen voice, supraglottic resection can affect swallow, and positive margins can convert intended single-modality surgery into additional treatment. Contemporary meta-analysis suggests patient-reported long-term voice and quality-of-life outcomes after TLM and radiation for T1-T2 glottic cancer are broadly comparable, with substantial heterogeneity. The right answer is not laser always preserves voice better.

SALVAGE SETTING — prior radiation changes the problem. The European Laryngological Society salvage consensus supports CO2 TOLMS only in carefully selected recurrent laryngeal SCC after radiotherapy/chemoradiotherapy, with strict attention to workup, exposure, extent and follow-up. Radiation fibrosis, impaired healing, submucosal spread and difficult margin interpretation lower the tolerance for casual re-resection. Salvage TLM should not be taught as equivalent to primary early-glottic TLM.

CURRENT TREATMENT BOUNDARY — current National Cancer Institute PDQ lists endoscopic CO2 laser excision among accepted options for selected stage I glottic cancer and laser surgery among stage II glottic options, alongside radiation and partial/total laryngeal operations as anatomically appropriate. This supports a choice framework, not a mandate for TLM. Recent long-term early-glottic data continue to show high laryngeal preservation with careful selection, while T2 disease, anterior-commissure involvement and margin status are recurrent risk factors. Current evidence for selected T3/T4a TLM remains mostly nonrandomized and heterogeneous.

Senior synthesis — use SELECT, EXPOSE, MAP, RESECT, ORIENT, MARGIN, NECK, FUNCTION, RESCUE. SELECT the patient and tumor rather than selecting the laser. EXPOSE the entire intended oncologic field before committing. MAP superficial, deep, anterior-commissure, subglottic, arytenoid and deep-space extent. RESECT only to planes you can see and control. ORIENT tissue so pathology can answer the clinical question. MARGIN interpretation is pattern-specific, especially deep versus superficial/thermal artifact, not a universal millimeter rule. NECK treatment follows subsite and nodal risk. FUNCTION includes voice, swallow, airway and the possibility of multimodality treatment. RESCUE means aborting or converting when exposure, bleeding, airway/fire risk, deep extension or margin control defeats a safe oncologic transoral operation."""

TRAPS = [
    "Treating possession of a CO2 laser as an indication for TLM rather than selecting by tumor extent, exposure, margins, function, and patient factors.",
    "Starting definitive resection before proving that the entire intended peripheral and deep oncologic field can be exposed.",
    "Trying to compensate for poor anterior-commissure exposure with blind or tangential laser cuts.",
    "Assuming every anterior-commissure lesion has thyroid-cartilage invasion or, conversely, treating anterior-commissure involvement as trivial.",
    "Using the ELS cordectomy type as if it were a cancer stage rather than a description of resection extent.",
    "Taking a superficial cordectomy for suspected vocalis/deep invasion because the mucosal lesion looks small.",
    "Taking an unnecessarily deep cordectomy for a superficial lesion without accounting for avoidable voice morbidity.",
    "Calling a thermally distorted superficial margin equivalent to visible residual tumor or a definite positive deep margin.",
    "Teaching one universal millimeter definition of a close TLM margin despite specimen, thermal-artifact, and pathology heterogeneity.",
    "Observing obvious residual disease because some close/positive-margin series report high laryngeal preservation.",
    "Sending every close or positive margin directly to total laryngectomy without distinguishing superficial, deep, focal, multiple, resectable, and salvage contexts.",
    "Forgetting that TLM controls the primary site but does not replace appropriate elective or therapeutic neck treatment.",
    "Claiming TLM always produces better voice than radiation without discussing cordectomy extent and heterogeneous comparative evidence.",
    "Using primary-treatment TLM evidence to justify salvage TLM after radiotherapy without the stricter ELS selection framework.",
    "Allowing high oxidizer concentration, nitrous oxide, combustible airway material, or unclear team roles during laser airway surgery.",
    "Continuing laser activation while troubleshooting a suspected airway fire instead of immediately stopping energy and oxidizer flow and removing burning material.",
    "Chasing deep bleeding or deep tumor extension blindly through a narrow laryngoscope instead of improving exposure, controlling the airway, or changing approach.",
    "Continuing an endoscopic operation after exposure, deep extension, margin control, airway safety, or expected function has made the original transoral objective unsafe.",
]

COHORT = {QIDS[0]: {
    "concept_id": CID,
    "canonical_topic": TOPIC,
    "prompt": PROMPT,
    "answer_text": ANSWER,
    "explanation": "TLM is an exposure- and margin-dependent oncologic approach: select the tumor and patient first, prove exposure, resect to visible oncologic planes, manage the neck separately, and stop or convert when safe margin control or function is no longer achievable.",
    "board_pearl": "The laser is a tool, not the indication. Poor exposure is an oncologic contraindication to continuing the same transoral plan.",
    "depth_layers_v225": {
        "foundation":"Laryngeal compartment anatomy, anterior commissure/Broyles framework, tumor depth, ELS cordectomy language, and the distinction between a surgical tool and an oncologic indication.",
        "application":"Tumor selection, suspension exposure, specimen orientation, deep versus superficial margin interpretation, neck management, and voice/swallow tradeoffs versus radiation or open surgery.",
        "senior_decision":"Shared-airway laser/fire planning, airway-fire rescue, deep bleeding/exposure bailout, and deciding when to re-resect, convert, stop, or choose another oncologic modality.",
    },
    "common_traps_v225": TRAPS,
    "deliberate_review_v225": {
        "why_review":"High-yield laryngeal-oncology OR concept: residents must integrate exposure, margin biology, anterior-commissure/deep-space anatomy, neck risk, function and laser-airway rescue rather than equating laser with minimally invasive safety.",
        "retrieval_prompts":["What tumor and exposure features make primary TLM reasonable or unreasonable?","Why is inadequate exposure an oncologic reason to abort rather than merely a technical inconvenience?","How do deep, superficial, close, positive and thermally distorted margins change next steps?","What neck problem remains after a technically excellent TLM primary resection?","What is the immediate response to an airway fire during laser laryngeal surgery?","When should the senior surgeon stop TLM and choose re-resection, radiation, open partial surgery, or total laryngectomy?"],
        "spacing":"Revisit before microlaryngoscopy/TLM and laryngeal-oncology cases; repeat when a learner treats a laser, a cordectomy type, or one margin number as the treatment decision.",
    },
    "source_refs_v225": SOURCE_REFS_V225,
    "evidence_distinction_v225": "Durable textbook principles are laryngeal anatomy, exposure before commitment, visible oncologic planes, margin-oriented resection, separate neck management and function-aware conservation surgery. Current NCI guidance keeps endoscopic CO2 laser excision as one selected laryngeal-cancer option alongside radiation and other surgery. Current ELS salvage consensus imposes stricter selection after RT/CRT. Current margin meta-analyses show meaningful recurrence/DFS risk from positive and especially deep margins but do not establish one universal millimeter cutoff. FDA guidance regulates ENT microsurgical CO2 lasers and their labeling; device clearance does not determine which cancer should undergo TLM. Current APSF safety guidance treats airway laser surgery as a high-risk fire environment requiring an explicit oxidizer/fuel/ignition prevention and rescue plan.",
    "choices": [],
    "answer": None,
}}

def apply_concept_check_task_alignment_v225(checks, deep_modules, v6_item_id):
    by = {str(q.get("id") or ""): q for q in checks or []}
    repaired, missing, link_mismatch = [], [], []
    for qid, spec in COHORT.items():
        q = by.get(qid)
        if q is None:
            missing.append(qid); continue
        m = _find_module(q, deep_modules, v6_item_id)
        topic = str(m.get("topic") or "") if m else ""
        cid = v6_item_id(q.get("domain"), topic) if m and q.get("domain") else None
        if topic != spec["canonical_topic"] or cid != spec["concept_id"] or q.get("concept_id") != spec["concept_id"]:
            link_mismatch.append(qid); continue
        for key, value in spec.items():
            q[key] = value
        q["task_alignment_v225"] = True
        repaired.append(qid)
    return {"repaired": repaired, "missing": missing, "link_mismatch": link_mismatch}
