"""v19.1 — board/OR-focused live-canonical Concept Check depth cohort.

Selected from the validated V190 untouched backlog after reassessing existing
material. This cohort prioritizes cleft-palate surgical physiology, microtia /
atresia sequencing, congenital-CMV hearing decisions, and stroboscopic lesion
localization. Exact live canonical resolution is required before mutation.
"""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-pediatric-otolaryngology-cleft-lip-palate-ent-surgical-fundamentals":{
"concept_id":"v6-pediatric-otolaryngology-cleft-lip-palate-ent-surgical-fundamentals","canonical_topic":"Cleft Lip / Palate — ENT Surgical Fundamentals",
"prompt":"A 9-month-old with an unrepaired cleft palate has nasal regurgitation, chronic middle-ear effusions, and emerging speech-sound delay but is growing appropriately without obstructive breathing. The family asks what palatoplasty is trying to restore beyond simply closing the visible gap, when ear tubes are considered, and what later findings would suggest velopharyngeal dysfunction or a complication requiring additional treatment. How should you frame the operative anatomy, timing, surveillance, and escalation plan?",
"answer_text":"The functional target of palatoplasty is a mobile, length-appropriate palate with restoration of the levator veli palatini sling, not merely mucosal closure. The abnormal palatal muscles insert along the posterior hard palate rather than forming a transverse sling, contributing to poor velopharyngeal closure and Eustachian-tube dysfunction. Primary repair is commonly performed in late infancy, often around 9–12 months depending on the cleft team, growth, airway, and technique, to support speech development while balancing maxillary-growth considerations. The operation closes nasal and oral layers and reorients the levator mechanism while avoiding excessive tension and neurovascular injury. Persistent bilateral effusion or hearing loss is assessed audiologically; tympanostomy tubes are commonly considered at the time of palate repair or earlier when hearing or infection indications warrant, but the child still needs longitudinal surveillance because otitis media with effusion can persist for years. After repair, monitor feeding, fistula, obstructive symptoms, hearing, resonance, articulation, and speech development. Hypernasality, audible nasal emission, weak pressure consonants, or compensatory articulation after adequate speech development should prompt cleft-speech assessment and instrumental evaluation of velopharyngeal function before secondary surgery. A palatal fistula is repaired when symptoms such as nasal regurgitation, hygiene problems, or speech effects justify the morbidity. The senior principle is to distinguish structural velopharyngeal insufficiency from learned articulation errors: speech therapy treats compensatory mislearning, whereas a true anatomic closure gap may require secondary palatal or pharyngeal surgery after the closure pattern and airway risk are defined.",
"explanation":"Cleft-palate surgery restores a muscular speech and swallowing valve. Hearing surveillance and postoperative speech physiology are part of the operation's longitudinal outcome, not separate problems.",
"board_pearl":"A closed palate can still fail functionally: persistent hypernasality requires localization of the velopharyngeal closure defect before choosing a secondary procedure.",
"depth_layers_v191":{"foundation":"Know the abnormal levator insertion, Eustachian-tube consequences, and why palatoplasty reconstructs a muscular sling rather than simply closing mucosa.","application":"Coordinate age-appropriate palatal repair, audiology/ear-tube decisions, and surveillance for fistula, hearing loss, resonance, and articulation.","senior_decision":"Differentiate compensatory articulation from structural velopharyngeal insufficiency and define closure pattern plus airway risk before secondary speech surgery."},
"common_traps_v191":["Treating palatoplasty as simple hole closure misses the levator reconstruction that drives velopharyngeal competence and ignores the child's prolonged Eustachian-tube and hearing risk.","Sending every hypernasal child directly to pharyngeal surgery without speech evaluation and closure-pattern assessment can operate on learned articulation and can create avoidable obstructive sleep apnea."],
"deliberate_review_v191":"Replaced a generic one-line repair goal with levator-sling anatomy, timing, ear-disease integration, fistula surveillance, velopharyngeal localization, and airway-aware secondary-surgery decisions."},
"cc-v112-rec-pediatric-otolaryngology-microtia-reconstruction":{
"concept_id":"v6-pediatric-otolaryngology-microtia-reconstruction","canonical_topic":"Microtia Reconstruction",
"prompt":"A 7-year-old with unilateral grade III microtia and congenital aural atresia has normal hearing in the opposite ear and wants auricular reconstruction. The family asks whether the ear canal should be opened first, whether autologous rib or porous-polyethylene reconstruction is better, and how hearing rehabilitation fits into the plan. How should you sequence hearing assessment, temporal-bone imaging, atresia candidacy, auricular reconstruction, and long-term complication counseling?",
"answer_text":"Start by separating two parallel goals: hearing rehabilitation and creation of an external ear. Obtain age-appropriate audiology early because bilateral conductive loss requires prompt amplification, while a child with normal contralateral hearing may choose among observation, non-surgical bone-conduction options, implantable hearing devices, or selected atresiaplasty based on functional needs and anatomy. High-resolution temporal-bone CT is generally deferred until the child is old enough that operative candidacy is being considered; it defines the ossicular chain, facial-nerve course, middle-ear space, cochlear/vestibular anatomy, and other features used in atresia-candidacy frameworks such as the Jahrsdoerfer score. Auricular options include observation or prosthesis, osseointegrated prosthesis, autologous costal-cartilage reconstruction once sufficient rib cartilage is available, and porous-polyethylene reconstruction at a younger age in selected centers. The choice depends on age, anatomy, skin/soft-tissue envelope, prior scars, surgeon expertise, tolerance for staged surgery, donor-site morbidity, implant exposure risk, and patient preference; there is no universally superior technique. Sequencing with canal surgery must be planned jointly. Uncoordinated atresiaplasty can scar or consume tissue needed for auricular reconstruction, and temporoparietal fascia is particularly important for alloplastic framework coverage. Many autologous-rib pathways place atresia repair after the framework stages, whereas alloplastic pathways require individualized sequencing so vascularized coverage is not jeopardized. Counsel that atresiaplasty can restenose or develop chronic drainage/cholesteatoma and may not provide stable normal hearing; bone-conduction devices often give more predictable hearing. Autologous frameworks can distort or calcify and have chest donor-site morbidity; alloplastic frameworks avoid rib harvest but carry exposure/infection risk. The senior decision is multidisciplinary sequencing: never choose canal or framework surgery in isolation from the hearing plan and the tissue requirements of the eventual reconstruction.",
"explanation":"Microtia care is a coordinated reconstruction-and-hearing pathway. Canal surgery, implant placement, and auricular framework surgery can compromise one another if sequence and tissue requirements are not planned prospectively.",
"board_pearl":"Before atresiaplasty in a child who wants auricular reconstruction, know which reconstruction will be used and which local vascularized tissues it will need.",
"depth_layers_v191":{"foundation":"Separate auricular form from hearing function and understand why audiology precedes reconstructive decisions.","application":"Use temporal-bone CT when operative candidacy is relevant, compare bone-conduction rehabilitation with atresiaplasty, and counsel autologous versus alloplastic framework tradeoffs.","senior_decision":"Coordinate canal surgery, hearing implants, and auricular reconstruction so scars or tissue harvest do not compromise the definitive framework or its vascularized coverage."},
"common_traps_v191":["Ordering infant temporal-bone CT simply because microtia is visible adds radiation before the anatomy will change management; imaging is most useful when atresia surgery is actually being considered.","Performing canal surgery without the reconstructive team can scar the field or compromise temporoparietal fascia and make the preferred auricular reconstruction more difficult or unsafe."],
"deliberate_review_v191":"Expanded an option list into audiologic triage, CT timing, atresia candidacy, hearing-device tradeoffs, framework choices, complication counseling, and reconstruction-preserving surgical sequencing."},
"cc-v112-rec-pediatric-otolaryngology-congenital-cmv-hearing-loss":{
"concept_id":"v6-pediatric-otolaryngology-congenital-cmv-hearing-loss","canonical_topic":"Congenital CMV Hearing Loss",
"prompt":"A newborn fails the hearing screen and has a positive saliva CMV PCR at 12 days of life. The infant otherwise appears well. The family asks whether this proves congenital CMV, whether antiviral treatment will preserve hearing, and why repeat hearing tests are needed even if the next audiogram is normal. What should be confirmed now, what findings change antiviral discussions, and how should hearing surveillance and rehabilitation proceed?",
"answer_text":"First confirm congenital infection within the diagnostic window. A positive saliva PCR should generally be confirmed with urine PCR because saliva can be contaminated by CMV in breast milk; testing obtained within the first 21 days of life distinguishes congenital from postnatally acquired infection. After that window, retrospective dried-blood-spot testing may sometimes help but a negative result does not reliably exclude congenital CMV because sensitivity is limited. Evaluate the infant for symptomatic disease with the pediatric/infectious-disease team, including neurologic findings, growth, platelet/liver abnormalities, eye disease, and neuroimaging when indicated. Antiviral evidence is strongest for symptomatic congenital CMV, particularly disease with central-nervous-system involvement; valganciclovir-based treatment requires blood-count and hepatic monitoring because neutropenia and other toxicities occur. Treatment of an otherwise asymptomatic infant with isolated sensorineural hearing loss remains an area in which evidence and institutional practice are evolving, so ENT should not promise hearing preservation or start therapy solely from a failed hearing screen without multidisciplinary confirmation of disease category and current protocol. Hearing loss from congenital CMV may be unilateral or bilateral, fluctuate, appear after a normal newborn test, or progress over childhood. Therefore obtain diagnostic ABR/audiology promptly after a failed screen and continue scheduled surveillance even when thresholds normalize. Rehabilitation should follow functional loss without waiting for the disease course to declare itself: optimize hearing aids or bone-conduction options when appropriate, provide early-intervention and speech-language support, and evaluate cochlear-implant candidacy for severe-to-profound loss. The senior pearl is that the 21-day clock is a diagnostic emergency, not necessarily an antiviral-treatment mandate.",
"explanation":"Congenital CMV combines a time-limited diagnostic opportunity with a long, variable hearing trajectory. Confirmation, disease severity, antiviral candidacy, and hearing rehabilitation are related but separate decisions.",
"board_pearl":"CMV testing within 21 days establishes congenital timing; a normal later audiogram does not end surveillance because cCMV hearing loss can be delayed or progressive.",
"depth_layers_v191":{"foundation":"Confirm congenital infection within 21 days and recognize the delayed, fluctuating, or progressive SNHL phenotype.","application":"Classify symptomatic disease with pediatrics/infectious disease, discuss antiviral evidence and toxicity accurately, and institute serial audiology plus early rehabilitation.","senior_decision":"Do not equate isolated failed hearing screening with automatic valganciclovir; separate diagnostic urgency from treatment candidacy while preventing delayed auditory rehabilitation."},
"common_traps_v191":["Accepting an unconfirmed saliva PCR after breast-feeding or waiting beyond 21 days can lose the ability to distinguish congenital infection from postnatal acquisition with routine urine or saliva testing.","Reassuring the family after one normal follow-up audiogram misses the hallmark delayed and progressive hearing risk and can postpone amplification, language intervention, or cochlear-implant evaluation."],
"deliberate_review_v191":"Expanded a 14-word treatment statement into the 21-day diagnostic window, saliva-confirmation nuance, symptomatic-disease antiviral evidence, toxicity monitoring, longitudinal audiology, and timely hearing rehabilitation."},
"cc-v112-rec-laryngology-voice-swallowing-stroboscopy-interpretation":{
"concept_id":"v6-laryngology-voice-swallowing-stroboscopy-interpretation","canonical_topic":"Stroboscopy Interpretation",
"prompt":"A professional singer has persistent dysphonia after an upper-respiratory infection. Flexible examination shows no obvious mass and both vocal folds move, but videostroboscopy demonstrates an hourglass closure pattern, preserved wave over most of both folds, and a focal reduction in mucosal wave at the mid-membranous right vocal fold. How should you interpret closure, symmetry, amplitude, mucosal wave, and periodicity, and which findings would push you toward scar, epithelial lesion, paresis, malignancy workup, or a different imaging technique?",
"answer_text":"Interpret stroboscopy as a set of vibratory observations rather than as a lesion label. First document glottic closure pattern, phase symmetry, periodicity, amplitude of lateral excursion, mucosal-wave propagation, vertical level, and the location of any nonvibrating segment. An hourglass gap commonly accompanies bilateral mid-membranous lesions such as nodules, but closure pattern alone is not diagnostic. Preserved symmetric amplitude and wave argue against a broad stiff infiltrative process. A focal persistent reduction or absence of wave can reflect epithelial tethering, scar, sulcus, cyst, keratosis, or invasive disease and should be correlated with the visible lesion, palpation or microlaryngoscopy when indicated, and oncologic risk factors; stroboscopy cannot exclude cancer. Reduced amplitude and wave on one side with phase asymmetry may also occur with subtle paresis because altered tone and closure change vibration, so integrate vocal-fold position, motion, supraglottic compensation, and laryngeal EMG when the neurologic question remains important. Periodicity matters because conventional stroboscopy samples successive cycles under the assumption that phonation is sufficiently periodic. In markedly aperiodic dysphonia, the apparent slow-motion sequence may be misleading; high-speed videoendoscopy or another non-stroboscopic assessment is preferable when cycle-to-cycle vibration must be seen directly. For this singer, the focal wave abnormality deserves careful lesion localization rather than empiric treatment based only on the hourglass gap. The senior decision is to use strobe to answer whether tissue is pliable and vibrating normally, then choose office observation/voice therapy, operative inspection, biopsy, or neurologic evaluation according to the specific abnormality and clinical risk.",
"explanation":"Stroboscopy is a physiologic sampling tool. Closure pattern suggests mechanisms, while focal stiffness, asymmetry, and loss of wave localize abnormalities that must be interpreted with the visible lesion and clinical context.",
"board_pearl":"A focal absent mucosal wave means focal stiffness until proved otherwise; it does not by itself tell you whether the cause is scar, cyst, dysplasia, or cancer.",
"depth_layers_v191":{"foundation":"Systematically describe closure, symmetry, periodicity, amplitude, mucosal wave, vertical level, and any nonvibratory segment.","application":"Use focal versus diffuse stiffness and phase/amplitude abnormalities to distinguish structural tethering from compensatory or neurogenic mechanisms and choose the next test.","senior_decision":"Recognize when aperiodicity invalidates stroboscopic sampling and escalate suspicious focal stiffness or oncologic features to operative evaluation/biopsy rather than treating a closure pattern as a diagnosis."},
"common_traps_v191":["Calling an hourglass closure pattern 'vocal nodules' without examining the mucosal wave mistakes a descriptive glottic shape for a diagnosis and can miss a unilateral stiff lesion.","Trusting pseudo-slow-motion stroboscopy during severely aperiodic phonation can create an artifactually coherent pattern; high-speed imaging is more appropriate when individual cycles are not periodic."],
"deliberate_review_v191":"Expanded a 14-word technical limitation into a systematic stroboscopic read, lesion-localization physiology, paresis/stiffness differential, cancer escalation, and high-speed-imaging threshold."}
}

def apply_concept_check_task_alignment_v191(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id)
        topic=str(module.get('topic') or '') if module else ''
        cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']:
            link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v191']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
