"""v20.14 — deepen exact live Central Neck Dissection Concept Check."""
from concept_check_board_repair_v177 import _find_module

QID = "cc-v112-rec-thyroid-parathyroid-salivary-central-neck-dissection"
CID = "v6-thyroid-parathyroid-salivary-central-neck-dissection"
TOPIC = "Central Neck Dissection"

SOURCE_REFS_V214 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive Cummings 7e corpus; thyroid-cancer nodal anatomy, central-compartment surgery, recurrent-laryngeal-nerve and parathyroid preservation principles cross-referenced 2026-09-07.","role":"durable operative foundation: compartment-oriented dissection, RLN course/danger zones, parathyroid vascular preservation and revision-plane risk"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy; thyroid malignancy and neck-dissection framework cross-referenced 2026-09-07.","role":"resident/board framework: indications, central compartment anatomy, complications and postoperative calcium/voice assessment"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy; thyroid/neck-dissection material cross-referenced 2026-09-07.","role":"operative cross-check: nodal basin anatomy, RLN/parathyroid protection, hemorrhage and nerve-injury morbidity"},
    {"type":"guideline","citation":"Ringel MD, Sosa JA, et al. 2025 American Thyroid Association Management Guidelines for Adult Patients with Differentiated Thyroid Cancer. Thyroid. 2025;35(8):841-985. PMID: 40844370. DOI: 10.1177/10507256251363120.","role":"current authoritative DTC framework; individualized surgery and selective rather than automatic escalation for clinically node-negative disease"},
    {"type":"consensus","citation":"American Thyroid Association Surgery Working Group, AAES, AAO-HNS, AHNS. Consensus statement on terminology and classification of central neck dissection for thyroid cancer. Thyroid. 2009;19(11):1153-1158. PMID: 19860578. DOI: 10.1089/thy.2009.0159.","role":"durable compartment definition: prelaryngeal, pretracheal and paratracheal basins; therapeutic versus prophylactic terminology; avoid node plucking"},
    {"type":"consensus","citation":"Agrawal N, et al. Indications and extent of central neck dissection for papillary thyroid cancer: American Head and Neck Society Consensus Statement. Head Neck. 2017;39:1269-1279. PMID: 28449244.","role":"specialty-society indication/extent framework and morbidity tradeoffs"},
    {"type":"consensus","citation":"Urken ML, et al. Surgical management of the recurrent laryngeal nerve in thyroidectomy: American Head and Neck Society Consensus Statement. Head Neck. 2018. PMID: 29461666.","role":"RLN preservation versus oncologic sacrifice decision framework when tumor involves the nerve"},
    {"type":"review","citation":"Nguyen C, Karcioglu AS, Scharpf J. 2025 American Thyroid Association Management Guidelines for Adult Patients With Differentiated Thyroid Cancer: What's New for Surgeons? Otolaryngol Head Neck Surg. 2026. PMID: 42560656. DOI: 10.1002/ohn.70367.","role":"2026 surgeon-focused interpretation of the current ATA DTC guideline"},
]

PROMPT = """An adult with papillary thyroid carcinoma has suspicious ipsilateral level VI nodes on ultrasound and a separate patient with a small cN0 intrathyroidal cancer asks whether central neck dissection should be added routinely. How do you distinguish therapeutic from prophylactic central dissection, define the compartment and choose unilateral versus bilateral extent, protect the recurrent laryngeal nerves and parathyroid blood supply, handle tumor adherent to a nerve or scarred revision planes, and rescue bleeding, bilateral nerve dysfunction, or postoperative hypocalcemia/hematoma?"""

ANSWER = """Foundation — start with indication, not with the fact that central nodes commonly contain microscopic disease. A therapeutic central neck dissection is performed for clinically apparent central nodal metastasis identified preoperatively, by imaging, or convincingly intraoperatively. A prophylactic/elective dissection is removal of a clinically negative central compartment. The durable ATA/AAO-HNS/AHNS/AAES terminology statement matters because a central neck dissection is compartment-oriented surgery, not removal of a few visible nodes. The classic nodal groups are prelaryngeal/Delphian, pretracheal, and right and left paratracheal basins, with the inferior central compartment extending into the upper mediastinal level VII territory that is safely accessible from the neck. Record whether the dissection is unilateral or bilateral and why. 'Berry picking' only abnormal nodes leaves the rest of the involved basin behind and is not a substitute for a therapeutic compartment dissection.

Current indication reasoning — clinically involved central nodes are a strong indication for therapeutic dissection when the disease is resectable. The controversial question is cN0 disease. Older teaching and some retrospective series favored routine prophylactic central dissection because occult nodal metastases are common and nodal yield improves pathologic staging. Contemporary practice is more selective. The 2025 ATA DTC guideline emphasizes individualized risk/benefit decisions and broader de-escalation for appropriately low-risk disease; a small intrathyroidal cN0 cancer should not trigger automatic bilateral central dissection merely to discover microscopic N1a disease. Potential benefits of prophylactic dissection—staging information, lower central recurrence in some series, and influence on adjuvant planning—must be weighed against added transient and permanent hypoparathyroidism and RLN morbidity. Advanced primary disease, suspicious lateral nodal disease, tumor biology, need for reliable staging, surgeon experience and whether the information would actually change management can shift that balance. Preserve the disagreement explicitly: therapeutic CND for evident N1a disease is accepted; routine prophylactic CND for every cN0 PTC remains controversial and should not be taught as mandatory.

Anatomic map — before dividing lymphatic tissue, mentally map both recurrent laryngeal nerves, the superior and inferior parathyroid glands with their vascular pedicles, trachea, esophagus, carotid sheath, inferior thyroid artery branches, thymic tongue and thoracic inlet. The right RLN usually approaches the larynx more obliquely and may be hidden by nodal tissue; the left typically ascends in the tracheoesophageal groove. Neither course should be assumed, particularly with large tumors, prior surgery, inflammation, a nonrecurrent nerve variant or distorted anatomy. The nerve is at particular risk where disease or dissection converges near the inferior thyroid artery and Berry ligament. The parathyroid objective is not simply 'identify four glands'; it is to preserve viable glands with intact perfusion. Skeletonizing every gland or devascularizing its terminal vessels in pursuit of a cleaner specimen defeats that goal.

Operative application — expose the central compartment enough to see the structures that define the dissection. In a therapeutic unilateral paratracheal dissection, identify the RLN in a reliable segment and maintain direct awareness of it while nodal tissue is mobilized away from the nerve. Remove the prelaryngeal and pretracheal tissue appropriate to the planned compartment and clear the involved paratracheal basin en bloc when feasible. Avoid traction that tents the nerve into clips or energy. Keep thermal devices away from the nerve even when it is visually intact. On the right, pay attention to tissue posterior to the RLN when oncologically relevant; on either side, the esophageal surface and thoracic inlet become increasingly unforgiving as the dissection deepens.

Parathyroid strategy — preserve arterial inflow and venous drainage whenever possible. If a gland can remain in situ with convincing perfusion, leave it attached to its blood supply rather than stripping it free. If a parathyroid is unavoidably removed or clearly devascularized, confirm tissue when appropriate and autotransplant viable parathyroid tissue according to the operative context. Bilateral central dissection raises the cumulative parathyroid-risk burden, so the indication for crossing to the contralateral side should be explicit rather than reflexive. Postoperative PTH and calcium strategy should anticipate the extent of thyroid and central-compartment surgery; symptoms of hypocalcemia require prompt recognition and treatment rather than waiting for severe tetany or arrhythmia.

Senior oncologic decision — gross tumor involving the RLN changes the problem from routine nerve preservation to oncologic judgment. Do not shave blindly until the anatomy and preoperative nerve function are known. A functioning nerve that is adherent but not clearly invaded may sometimes be preserved with careful dissection depending on disease biology and ability to achieve appropriate control. A nerve with gross invasion may require resection when that is necessary for oncologic clearance, but the decision should integrate preoperative vocal-fold function, contralateral nerve status, expected residual disease, adjuvant options and reconstructive/voice consequences. AHNS consensus principles support deliberate rather than automatic nerve sacrifice. If the contralateral nerve is at risk or its function is uncertain, bilateral paralysis is the catastrophic endpoint to avoid.

Revision central neck — scar removes the normal visual and tactile planes. Do not reproduce a primary operation by force. Use preoperative imaging to localize structural disease, obtain baseline laryngeal examination when indicated, enter through the safest available tissue plane, identify the nerve from an undisturbed segment when possible, and accept that parathyroids and nerve may be densely adherent to scar or tumor. Reoperation should target clinically meaningful structural disease, not biochemical anxiety alone. When a safe plane disappears, stop traction, restore landmarks, use magnification/nerve-monitoring information as adjuncts rather than substitutes for anatomy, and obtain senior help. A small-volume target that would require destructive dissection may justify a different risk-benefit discussion than bulky progressive disease.

Rescue — uncontrolled central-neck bleeding is managed by pressure, suction, exposure and controlled ligation; blind deep clamping beside an incompletely visualized RLN, esophagus or carotid sheath is a dangerous response. Loss of a nerve-monitoring signal is not itself proof of transection: stop, inspect the nerve, correct tube/electrode and anesthetic factors, stimulate proximally/distally and determine whether a true neural event occurred before committing to the opposite side. If the first side has a convincing functional RLN loss during an elective bilateral operation, staged completion may prevent bilateral vocal-fold paralysis unless oncologic circumstances demand otherwise. After surgery, an expanding neck hematoma with pressure, dysphagia, voice change, stridor or respiratory distress is an airway emergency—release a threatening wound and secure oxygenation/airway while arranging immediate definitive hemorrhage control. Symptomatic or biochemical hypocalcemia is treated promptly, and unexpectedly low PTH after extensive bilateral surgery should trigger an active calcium/calcitriol plan.

Senior synthesis — ask six questions. INDICATION: is the central disease clinically positive or am I proposing prophylactic surgery in cN0 disease? COMPARTMENT: am I performing a complete indicated basin rather than node plucking, and is unilateral or bilateral extent justified? NERVE: where is the RLN now, what was preoperative function, and is tumor merely adherent or grossly invasive? PARATHYROID: which glands remain perfused and what action is needed if one is devascularized? CONTRALATERAL COMMITMENT: after first-side nerve trouble, is it safe to proceed? RESCUE: can I immediately control hemorrhage, airway compromise and postoperative hypocalcemia? The major traps are routine bilateral prophylactic dissection in low-risk cN0 disease, berry picking therapeutic nodes, assuming the RLN course, thermal or traction injury, devascularizing parathyroids while 'preserving' them anatomically, sacrificing a functioning nerve without an oncologic plan, forcing scarred revision planes, continuing contralaterally after a true first-side neural injury, blind clamping of central bleeding, and observing a compressive postoperative hematoma."""

TRAPS = [
    "Equating the high prevalence of occult microscopic N1a disease with an indication for routine bilateral prophylactic central dissection in every cN0 papillary cancer.",
    "Removing only palpable or blue-appearing nodes ('berry picking') instead of a compartment-oriented therapeutic dissection when central nodal disease is clinically evident.",
    "Calling a specimen 'central neck dissection' without documenting prelaryngeal/pretracheal/paratracheal extent and whether it was unilateral or bilateral.",
    "Assuming the recurrent laryngeal nerve lies predictably in the groove and placing clips or energy before directly understanding its course.",
    "Preserving a parathyroid anatomically while stripping or cauterizing its vascular pedicle and then overlooking the postoperative hypocalcemia risk.",
    "Crossing automatically to the contralateral central compartment when bilateral dissection adds little oncologic value but substantially increases parathyroid and bilateral-RLN risk.",
    "Shaving or sacrificing a functioning RLN involved by tumor without integrating preoperative vocal-fold function, contralateral nerve status and oncologic consequences.",
    "Treating nerve monitoring as a substitute for anatomic identification or assuming any loss of signal equals transection before checking technical and neural causes.",
    "Proceeding electively to the second side after a convincing first-side RLN functional loss without considering staged completion to avoid bilateral paralysis.",
    "Forcing a primary-operation plane through a scarred revision central neck instead of localizing disease and finding the nerve from safer undisturbed anatomy.",
    "Blindly clamping brisk central-neck bleeding beside the RLN/esophagus/carotid sheath rather than compressing, exposing and obtaining deliberate vascular control.",
    "Observing an expanding postoperative thyroid/central-neck hematoma with airway symptoms instead of immediate decompression/airway rescue and definitive hemorrhage control.",
]

COHORT = {QID: {
    "concept_id": CID, "canonical_topic": TOPIC, "prompt": PROMPT, "answer_text": ANSWER,
    "explanation": "Central neck dissection is an indication- and compartment-driven thyroid cancer operation: treat evident nodal disease comprehensively, use prophylactic dissection selectively, preserve RLN/parathyroid function, and have explicit neural, bleeding, calcium and airway bailouts.",
    "board_pearl": "Therapeutic central dissection means clinically evident N1a disease and should be compartment-oriented; occult microscopic nodes alone do not make routine bilateral prophylactic CND mandatory in a low-risk cN0 patient.",
    "depth_layers_v214": {"foundation":"Define therapeutic versus prophylactic CND, level VI/upper VII basins, RLN and parathyroid vascular anatomy.","application":"Choose unilateral/bilateral extent and execute compartment dissection with direct nerve awareness and perfused-parathyroid preservation.","senior_decision":"Resolve cN0 controversy, gross RLN involvement, revision scar, loss-of-signal contralateral commitment, hemorrhage, hematoma and hypocalcemia rescue."},
    "common_traps_v214": TRAPS,
    "deliberate_review_v214": "Selected from the exact successful v20.13 production backlog (325 canonical topics; zero backlog failures). Central Neck Dissection remained an untouched shallow exact-live Concept Check and was prioritized over lexical leaders because it combines thyroid-cancer board decisions with recurrent-laryngeal-nerve, parathyroid, hemorrhage, bilateral-airway and revision-surgery danger zones.",
    "source_refs_v214": SOURCE_REFS_V214,
}}

def apply_concept_check_task_alignment_v214(checks, deep_modules, v6_item_id):
    by = {str(q.get("id") or ""): q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid, patch in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id); topic=str(module.get("topic") or "") if module else ""
        cid=v6_item_id(q.get("domain"),topic) if module and q.get("domain") else None
        if module is None or topic!=patch["canonical_topic"] or cid!=patch["concept_id"] or q.get("concept_id")!=cid:
            link_mismatch.append(qid); continue
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v214","common_traps_v214","deliberate_review_v214","source_refs_v214"):
            q[field]=patch[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v214"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
