"""v18.3 — live-canonical Concept Check depth cohort.

This cohort was selected from the deterministic v18.3 backlog audit, not from
hand-written aliases. Each payload preserves the useful clinical premise from
the existing reveal, then adds the missing foundation -> application ->
senior-decision layer. These are oral-board/free-response checks, so the
individualized error analysis is stored as common_traps_v183 rather than fake
MCQ distractors.
"""

COHORT = {
    "cc-v112-rec-sleep-surgery-central-events-hypoventilation": {
        "concept_id": "v6-sleep-surgery-central-events-hypoventilation",
        "canonical_topic": "Central Events / Hypoventilation",
        "prompt": "An adult referred to sleep-surgery clinic has persistent sleep-disordered breathing, but the polysomnogram shows a substantial central-event burden and sustained nocturnal hypoventilation rather than a predominantly obstructive pattern. Before offering upper-airway surgery, how do you separate the physiology, what should be treated first, and which findings should trigger multidisciplinary escalation rather than an anatomic operation?",
        "answer_text": "Treat the underlying physiology with sleep/pulmonary/cardiology expertise; do not default to obstructive surgery. First distinguish central apnea from sustained hypoventilation and from true pharyngeal obstruction using the PSG pattern, oxygenation and CO2 data, medication history, neurologic/neuromuscular clues, body habitus and cardiopulmonary disease. Opioids or sedatives, heart failure, neurologic disease, high-altitude exposure and disorders that impair ventilatory drive or mechanics can change treatment completely. Management targets the cause and gas exchange, with the appropriate positive-pressure or ventilatory strategy chosen by sleep/pulmonary specialists when needed. Upper-airway surgery only makes sense if clinically important obstructive collapse remains independently demonstrated. Escalate for severe or sustained hypoxemia/hypercapnia, awake ventilatory failure, major cardiopulmonary disease, progressive neuromuscular weakness, or a central/hypoventilation phenotype that makes the proposed obstructive procedure physiologically mismatched.",
        "explanation": "The key board move is to identify whether the patient has a surgically addressable collapsible upper airway. Central events reflect absent/reduced respiratory effort; hypoventilation reflects inadequate minute ventilation and CO2 clearance. Neither is fixed by enlarging the pharynx unless a separate obstructive component also matters.",
        "board_pearl": "A sleep-surgery referral is not automatically a surgical disease: prove obstruction before treating anatomy.",
        "depth_layers_v183": {"foundation": "Differentiate obstruction, central apnea and sustained hypoventilation by effort and gas-exchange physiology.", "application": "Use PSG/CO2 pattern, medications and cardiopulmonary or neuromuscular context to identify the driver.", "senior_decision": "Do not offer upper-airway surgery for physiology it cannot correct; escalate ventilatory failure and major comorbidity."},
        "common_traps_v183": ["Treating every elevated AHI as obstructive disease ignores respiratory-effort and CO2 physiology.", "Proceeding to DISE or airway surgery before stabilizing hypoventilation can delay treatment of the actual gas-exchange problem."],
        "deliberate_review_v183": "Reused the existing 'treat underlying physiology; do not default to obstructive surgery' core and added physiologic discrimination, workup, mismatch logic and escalation thresholds."
    },
    "cc-v112-rec-rhinology-allergy-skull-base-frontal-recess-frontal-sinus": {
        "concept_id": "v6-rhinology-allergy-skull-base-frontal-recess-frontal-sinus",
        "canonical_topic": "Frontal Recess / Frontal Sinus",
        "prompt": "A patient with unilateral frontal sinus disease is being considered for endoscopic frontal surgery. The coronal and sagittal CT show a narrow frontal drainage pathway with multiple frontal cells near the orbit and anterior skull base. How should you read this anatomy before operating, how do you choose surgical extent, and what findings require urgent escalation rather than routine elective treatment?",
        "answer_text": "Operate only for an appropriate disease burden after the diagnosis and medical strategy are clear; surgical extent should match the pathology and anatomy. Before entering the frontal recess, trace the drainage pathway in more than one CT plane and identify the agger nasi/frontal cells, frontal beak, lamina papyracea, anterior ethmoidal artery region and skull-base contour. The objective is a durable, mucosa-preserving drainage pathway, not indiscriminate superior dissection. Cell partitions are removed according to how they obstruct the true frontal outflow; distorted postoperative anatomy, osteitis, tumor or a very narrow pathway may justify a more extended approach. Stop and re-orient when landmarks are lost. Visual loss, an afferent pupillary defect, orbital hematoma, suspected invasive fungal disease, CSF leak/intracranial complication or uncontrolled hemorrhage changes the problem from routine frontal sinusitis to an urgent rescue pathway.",
        "explanation": "Frontal surgery is a CT-navigation problem before it is an instrument problem. The dangerous error is treating the frontal recess as a vertical tunnel: individual cells redirect drainage and place the orbit, skull base and anterior ethmoidal artery at risk.",
        "board_pearl": "In the frontal recess, define where the sinus drains before deciding what to remove; lost anatomy is a reason to stop, not to dissect faster.",
        "depth_layers_v183": {"foundation": "Understand frontal drainage cells and their relationship to orbit, skull base and anterior ethmoidal artery.", "application": "Use multiplanar CT to map the patient-specific outflow and match the opening to disease burden.", "senior_decision": "Escalate orbital, intracranial, invasive fungal and hemorrhagic complications and stop when landmarks are no longer trustworthy."},
        "common_traps_v183": ["Following a memorized superior direction instead of the patient's CT can drive the dissection into orbit or skull base.", "Making the largest possible frontal opening is not a substitute for removing the cell that actually obstructs the drainage pathway."],
        "deliberate_review_v183": "Preserved the existing extent-matches-pathology principle and added CT localization, mucosal strategy, stop points and orbital/skull-base escalation."
    },
    "cc-v112-mgt-facial-plastics-trauma-facial-soft-tissue-lacerations-burns": {
        "concept_id": "v6-facial-plastics-trauma-facial-soft-tissue-lacerations-burns",
        "canonical_topic": "Facial Soft-Tissue Lacerations / Burns",
        "prompt": "A patient presents after a deep cheek laceration from broken glass with active bleeding and an irregular wound crossing the expected course of the parotid duct and facial nerve branches. What should be assessed before definitive closure, when is bedside exploration insufficient, and which associated findings change disposition or require urgent specialty or operative management?",
        "answer_text": "Irrigate and explore enough to define depth and contamination, while assessing tetanus status, retained foreign body, bite/contamination and associated fracture or specialty-threatening injury. Before cosmetic closure, document facial nerve function by branch, evaluate the parotid duct when the wound crosses its course, inspect for oral communication, identify exposed cartilage or bone and assess tissue viability. Control hemorrhage with direct visualization rather than blind deep clamping. A clean, well-vascularized facial wound often benefits from meticulous layered repair with precise landmark alignment; questionable tissue should be debrided conservatively because facial perfusion is robust. Bedside repair is inappropriate when bleeding cannot be controlled safely, a major nerve/duct/lacrimal injury needs repair, the wound requires complex reconstruction, or the patient cannot tolerate adequate examination. Vision threat, orbital compartment syndrome, unstable airway, CSF leak, major vascular bleeding or extensive burns with inhalational concern require immediate escalation and disposition based on the threatened function, not cosmesis.",
        "explanation": "The diagnostic step is a structure-at-risk examination, not simply CT for every laceration. Facial wounds can look straightforward while transecting the facial nerve or parotid duct; documentation before local anesthetic, swelling and repair is high-value.",
        "board_pearl": "Before closing a cheek laceration, prove that facial movement and salivary drainage are intact—or identify the injury while repair is still straightforward.",
        "depth_layers_v183": {"foundation": "Define contamination, viability and the facial nerve, duct, lacrimal, cartilage and vascular structures at risk.", "application": "Choose bedside layered closure versus operative exploration based on structure injury and safe exposure.", "senior_decision": "Disposition follows airway, vision, hemorrhage and threatened function; cosmetic closure is downstream of those priorities."},
        "common_traps_v183": ["Closing first and checking facial nerve function later can erase the pre-repair neurologic baseline.", "Blind clamping for deep facial bleeding risks iatrogenic facial nerve or parotid-duct injury."],
        "deliberate_review_v183": "Reused irrigation/exploration, tetanus and contamination assessment; added structure-specific examination, repair setting, hemorrhage safety and disposition thresholds."
    },
    "cc-v112-rec-head-neck-oncology-open-partial-conservation-laryngectomy": {
        "concept_id": "v6-head-neck-oncology-open-partial-conservation-laryngectomy",
        "canonical_topic": "Open Partial / Conservation Laryngectomy",
        "prompt": "At tumor board, a patient with resectable laryngeal squamous cell carcinoma asks whether an open partial/conservation laryngectomy can preserve the organ. How do you decide whether conservation surgery is oncologically and functionally appropriate, what must the resection preserve, and which disease or patient factors should move the recommendation toward nonsurgical therapy or total laryngectomy?",
        "answer_text": "Select transoral, open partial, radiation-based or total-laryngectomy strategies by oncologic extent and expected function; functional preservation without a safe airway and swallow is not success. Conservation laryngectomy requires a tumor that can be removed with adequate margins while leaving enough functional laryngeal framework and at least one usable cricoarytenoid unit for airway protection and phonatory/swallow rehabilitation. I would review endoscopy, vocal-fold/arytenoid mobility and cross-sectional imaging for subglottic, pre-epiglottic/paraglottic, cartilage and extralaryngeal extension, then integrate pulmonary reserve, baseline aspiration/swallow function and rehabilitation capacity. Disease that cannot be cleared without sacrificing the functional unit, extensive framework/extralaryngeal involvement, or a patient unlikely to tolerate the expected aspiration burden argues against conservation surgery. The senior decision is not 'can I remove less larynx?' but whether the selected strategy preserves both cancer control and a usable organ.",
        "explanation": "Open conservation surgery is defined by oncologic and physiologic selection. An anatomically preserved larynx that chronically aspirates or cannot provide an adequate airway is organ preservation in name only.",
        "board_pearl": "Conservation laryngectomy preserves function only when the tumor can be cleared and a competent cricoarytenoid-based functional unit remains.",
        "depth_layers_v183": {"foundation": "Know the functional laryngeal unit and the extent data that determine resectability.", "application": "Integrate endoscopy/imaging with swallow, pulmonary reserve and rehabilitation potential.", "senior_decision": "Choose conservation only when oncologic margins and postoperative airway/swallow function are both credible."},
        "common_traps_v183": ["Calling any smaller resection 'organ preservation' ignores whether the remaining larynx can protect the airway.", "Basing eligibility on T category alone misses mobility, cartilage/deep-space extent and patient functional reserve."],
        "deliberate_review_v183": "Preserved the existing oncologic-extent/expected-function comparison and added functional-unit anatomy, selection workup and failure criteria."
    },
    "cc-v112-rec-general-ent-emergencies-common-ent-consult-triage-disposition": {
        "concept_id": "v6-general-ent-emergencies-common-ent-consult-triage-disposition",
        "canonical_topic": "Common ENT Consult Triage / Disposition",
        "prompt": "You are the senior resident receiving simultaneous overnight consults: a stable peritonsillar abscess, new stridor after neck surgery, brisk post-tonsillectomy bleeding, sudden sensorineural hearing loss, and orbital symptoms from sinusitis. How do you triage these calls, what information do you demand before sequencing them, and what findings mandate immediate bedside/OR escalation, transfer, or admission?",
        "answer_text": "Stabilize first, involve the correct services early and decide admission, OR or transfer according to physiologic threat rather than the diagnostic label. I triage by airway, active hemorrhage/hemodynamics, vision/orbit or intracranial threat, rapidly spreading deep-space infection/sepsis, then time-sensitive organ function. New postoperative stridor or expanding neck swelling is an airway emergency; brisk post-tonsillectomy bleeding requires resuscitation, suction-ready airway planning and urgent operative control when ongoing/significant; orbital visual deficit or afferent pupillary abnormality from sinus disease requires urgent ophthalmologic/rhinologic escalation. Sudden sensorineural hearing loss is time-sensitive but usually does not outrank an unstable airway or hemorrhage. For each call I need current vitals, oxygenation, bleeding/airway trajectory, anticoagulation/comorbidity, focused exam and whether the hospital has the necessary airway, anesthesia, imaging, blood bank and operative capability. Stable outpatient decisions require explicit follow-up and return precautions; inability to provide definitive rescue safely is itself a reason to transfer.",
        "explanation": "Consult triage is a threat hierarchy. The chief-level skill is recognizing that a common diagnosis can be unstable and an exotic diagnosis can be stable; disposition also depends on local rescue capability.",
        "board_pearl": "Overnight triage order is airway -> uncontrolled bleeding/shock -> vision/intracranial or rapidly spreading infection -> other time-sensitive function.",
        "depth_layers_v183": {"foundation": "Prioritize physiologic threat over diagnostic name.", "application": "Demand trajectory, focused exam and local rescue capability before sequencing consults.", "senior_decision": "Escalate or transfer whenever definitive airway, hemorrhage, orbital or operative rescue cannot be delivered safely and promptly."},
        "common_traps_v183": ["Seeing consults in callback order rather than threat order can delay an airway or hemorrhage rescue.", "Discharging a clinically stable patient without reliable follow-up, return precautions or local rescue capability is an incomplete disposition decision."],
        "deliberate_review_v183": "Reused the existing stabilize/admit-OR-transfer by physiologic threat core and added an explicit overnight hierarchy, capability assessment and concrete rescue triggers."
    },
    "cc-v112-rec-head-neck-oncology-reconstruction-selection-after-head-neck-ablation": {
        "concept_id": "v6-head-neck-oncology-reconstruction-selection-after-head-neck-ablation",
        "canonical_topic": "Reconstruction Selection After Head & Neck Ablation",
        "prompt": "A patient will undergo composite oral cavity resection with a through-and-through soft-tissue defect and segmental mandibular loss after prior radiation. At the preoperative conference, how do you translate the anticipated defect into reconstructive requirements, choose local/regional versus free tissue, and plan for recipient vessels, airway, nutrition and failure rescue before the ablative operation begins?",
        "answer_text": "Choose the simplest reconstruction that reliably restores function and withstands the oncologic environment. Start with the defect requirements: mucosal lining, external skin, dead-space fill, mandibular continuity, tongue mobility, separation of contaminated spaces and the volume needed for swallowing/speech. Small favorable defects may accept local or regional tissue, but a through-and-through irradiated defect with segmental bone loss generally needs robust vascularized free tissue, often with vascularized bone when mandibular continuity must be restored. Plan the flap around pedicle reach and recipient-vessel availability rather than choosing a donor site in isolation; prior radiation, neck dissection or vessel sacrifice should trigger a recipient-vessel and backup plan. Coordinate tracheostomy/airway strategy, enteral access, anticoagulation/VTE strategy and postoperative flap monitoring. Senior planning includes a second reconstructive option and a salvage pathway for venous congestion, thrombosis or flap loss, because reconstruction begins before the oncologic incision and cannot depend on an idealized defect.",
        "explanation": "Reconstruction is a functional requirements problem. Donor-site familiarity matters, but it comes after defining what tissue components and geometry the defect requires and whether reliable recipient vessels exist.",
        "board_pearl": "Plan the defect, recipient vessels and backup flap before resection; 'we'll see what is left' is not reconstructive planning.",
        "depth_layers_v183": {"foundation": "Translate the ablative defect into lining, skin, bulk, bone and functional requirements.", "application": "Match those needs to local/regional/free tissue while accounting for radiation and recipient-vessel geometry.", "senior_decision": "Pre-plan airway, nutrition, monitoring, backup vessels and a salvage reconstruction before ablation."},
        "common_traps_v183": ["Choosing a favorite flap before defining the defect can leave inadequate lining, bone, reach or bulk.", "Ignoring prior radiation/neck dissection until after flap harvest can turn recipient-vessel scarcity into an avoidable intraoperative crisis."],
        "deliberate_review_v183": "Preserved the simplest-reliable-reconstruction principle and local/regional/free-tissue distinction; added defect-component analysis, vessel planning and flap-failure rescue."
    },
    "cc-v112-rec-general-ent-emergencies-ent-perioperative-anesthesia-difficult-airway-planning": {
        "concept_id": "v6-general-ent-emergencies-ent-perioperative-anesthesia-difficult-airway-planning",
        "canonical_topic": "ENT Perioperative Anesthesia / Difficult Airway Planning",
        "prompt": "A patient with prior radiation, trismus and a bulky supraglottic tumor is scheduled for direct laryngoscopy and biopsy. Flexible examination shows a narrowed but patent airway. How should ENT and anesthesia decide whether to preserve spontaneous ventilation, perform awake airway control or induce conventionally, and what primary, backup and front-of-neck rescue plan must be agreed upon before entering the OR?",
        "answer_text": "Review prior airway records, flexible examination and imaging when relevant, mouth opening/neck mobility, oxygenation/ventilation reserve and the exposure the surgeon needs. The airway plan should be shared before induction and explicitly state the primary technique, backup device or route and front-of-neck rescue. In this patient, trismus, radiation change and a bulky supraglottic lesion raise concern that induction, paralysis or instrumentation could convert a marginal airway into one that cannot be ventilated or intubated. If losing spontaneous ventilation would be dangerous or rescue from above is doubtful, an awake strategy that preserves ventilation—including awake intubation or awake tracheostomy in selected anatomy—should be considered with experienced anesthesia and ENT present. If conventional induction is chosen, define why mask ventilation/intubation is expected to remain feasible, limit repeated traumatic attempts and have rigid endoscopy/surgical-airway equipment immediately available. Bleeding tumor, worsening obstruction, inability to lie flat or rapidly changing symptoms lower the threshold for awake control.",
        "explanation": "The decision is not 'fiberoptic versus video.' It is whether induction removes the patient's last reliable mechanism for oxygenation and whether rescue pathways remain physically possible after that choice.",
        "board_pearl": "Before induction, everyone should be able to say the primary airway plan, the failed-plan trigger and exactly how the neck will be accessed if oxygenation fails.",
        "depth_layers_v183": {"foundation": "Assess difficult ventilation, difficult intubation, aspiration/bleeding and difficult surgical rescue separately.", "application": "Use endoscopy, radiation/trismus and tumor geometry to decide whether spontaneous ventilation must be preserved.", "senior_decision": "Pre-commit to failure triggers and front-of-neck rescue; do not discover the backup plan after repeated attempts."},
        "common_traps_v183": ["A patent airway while awake does not prove that the airway will remain patent after induction and loss of tone.", "Repeated traumatic laryngoscopy in a vascular tumor can create bleeding and edema that destroy previously available rescue options."],
        "deliberate_review_v183": "Reused the existing records/exam/imaging and primary-backup-front-of-neck framework; added induction physiology, spontaneous-ventilation logic and stop triggers."
    },
    "cc-v112-rec-rhinology-allergy-skull-base-sphenoidotomy": {
        "concept_id": "v6-rhinology-allergy-skull-base-sphenoidotomy",
        "canonical_topic": "Sphenoidotomy",
        "prompt": "During endoscopic sphenoidotomy, you are teaching a junior resident who has reached the posterior nasal cavity but is uncertain whether a small opening is the natural sphenoid ostium. How do you localize the ostium safely, which structures define the danger zones once the sinus is entered, and what should make you stop rather than enlarge the opening blindly?",
        "answer_text": "Localize the natural sphenoid ostium using the posterior choana and superior turbinate as reproducible endonasal landmarks, while confirming the trajectory against the preoperative CT rather than relying on a fixed distance. Enter medially and inferiorly enough to stay away from the optic nerve and carotid prominence, then enlarge under direct visualization according to the indication. Once inside, orient to the sellar/skull-base roof, opticocarotid region and lateral recess anatomy; septations can insert on the carotid canal, so they should not be avulsed blindly. A dehiscent or protruding carotid/optic canal, Onodi/posterior ethmoid cell, distorted revision anatomy, extensive pneumatization or tumor can make standard relationships unreliable. Stop when the ostium or posterior landmarks cannot be reconciled with CT/navigation, when brisk arterial bleeding obscures orientation, or when a suspected CSF or orbital/neurovascular injury occurs. The safety principle is patient-specific localization before enlargement, not simply 'go superior and posterior.'",
        "explanation": "The sphenoid is surrounded by high-consequence structures and its pneumatization changes their apparent position. The superior turbinate helps find the ostium, but CT defines the individual optic nerve, carotid, septal and posterior ethmoid relationships.",
        "board_pearl": "Never avulse a sphenoid septation you have not traced on CT; it may terminate on the carotid canal.",
        "depth_layers_v183": {"foundation": "Use choana/superior turbinate to find the ostium and know opticocarotid/skull-base relationships.", "application": "Reconcile endoscopy with CT for posterior ethmoid cells, septations, canal dehiscence and pneumatization.", "senior_decision": "Stop with unreconciled anatomy or obscuring hemorrhage rather than enlarging a presumed ostium."},
        "common_traps_v183": ["Using a memorized distance from the choana ignores variation and revision distortion.", "Blindly fracturing a sphenoid septum risks carotid injury when that septum inserts on the carotid prominence."],
        "deliberate_review_v183": "Preserved the existing superior-turbinate/choana and carotid/optic-nerve core; added CT-based variation, safe enlargement, septation handling and stop criteria."
    },
    "cc-v112-rec-general-ent-emergencies-postoperative-neck-hematoma": {
        "concept_id": "v6-general-ent-emergencies-postoperative-neck-hematoma",
        "canonical_topic": "Postoperative Neck Hematoma",
        "prompt": "Several hours after thyroid surgery, a patient develops rapidly increasing neck pressure, dysphagia, voice change, anxiety and stridor while oxygen saturation is still normal. Explain the physiology of the airway threat, what you do immediately at bedside versus in the OR, and why waiting for CT or a conventional intubation attempt can be dangerous.",
        "answer_text": "Bleeding raises pressure within the relatively noncompliant postoperative neck, producing venous and lymphatic obstruction with progressive pharyngeal/laryngeal edema in addition to direct tracheal compression; that is why the airway may remain difficult even after the clot is released. This is a clinical emergency, not a CT diagnosis. Call for anesthesia/OR help, oxygenate, bring suction and airway/surgical equipment, reverse relevant coagulopathy when feasible without delaying rescue, and rapidly assess whether the airway is deteriorating. With expanding hematoma and respiratory compromise, open the incision and release superficial and deep closure layers immediately at the bedside if necessary; do not wait for transport to an OR. Once decompressed and oxygenation is stabilized, proceed to operative exploration, evacuation, irrigation and definitive hemostasis. Repeated conventional intubation attempts can fail because edema and distorted anatomy worsen quickly. Normal saturation is falsely reassuring because oxygenation can be preserved until late in an evolving obstruction.",
        "explanation": "The high-yield mechanism is not just direct tracheal compression: venous/lymphatic outflow obstruction causes rapidly progressive supraglottic/pharyngeal edema. Decompression therefore precedes source identification when the airway is threatened.",
        "board_pearl": "A deteriorating postoperative neck hematoma gets decompressed where the patient is; CT and transport are luxuries after the airway is safe.",
        "depth_layers_v183": {"foundation": "Understand compression plus venous/lymphatic obstruction and secondary airway edema.", "application": "Recognize pressure, dysphagia, voice change, anxiety and stridor as a clinical diagnosis even with normal saturation.", "senior_decision": "If respiratory compromise is evolving, release the wound immediately, then secure the airway and obtain definitive OR hemostasis."},
        "common_traps_v183": ["Sending a deteriorating patient to CT delays the one treatment that changes the airway trajectory: decompression.", "Waiting for desaturation underestimates obstruction because saturation may remain normal until the airway is critically narrowed."],
        "deliberate_review_v183": "Reused the existing pressure/edema physiology and decompression priority; added bedside-versus-OR sequence, airway strategy and false-reassurance traps."
    },
    "cc-v112-mgt-laryngology-voice-swallowing-posterior-cordotomy-arytenoidectomy": {
        "concept_id": "v6-laryngology-voice-swallowing-posterior-cordotomy-arytenoidectomy",
        "canonical_topic": "Posterior Cordotomy / Arytenoidectomy",
        "prompt": "A patient with chronic bilateral vocal-fold immobility has exertional stridor but a useful voice and only mild baseline dysphagia. Tracheostomy avoidance is a major goal. How do you confirm that posterior glottic enlargement is the right operation, choose cordotomy versus additional arytenoid work, counsel the airway-voice-swallow tradeoff, and decide when urgent airway stabilization must precede definitive surgery?",
        "answer_text": "Endoscopic posterior glottic enlargement is titrated to the airway need, and revision may be required. Before irreversible widening, confirm the cause of bilateral immobility with flexible laryngoscopy and, when fixation versus neuropathy is uncertain, operative palpation and selected laryngeal EMG; posterior glottic stenosis is managed differently from pure bilateral neurogenic paralysis. Posterior cordotomy creates a posterior airway while trying to preserve as much phonatory tissue as possible. Partial arytenoidectomy can add airway when cordotomy alone is inadequate but generally increases the voice and aspiration tradeoff, so I would not remove more tissue than the respiratory goal requires. Counsel that improved airflow commonly means a breathier/weaker voice and that aspiration risk may rise, particularly with baseline dysphagia or poor pulmonary reserve. Progressive stridor at rest, increased work of breathing, hypoxemia, inability to manage secretions or acute bilateral paralysis is an airway problem first: stabilize with intubation or tracheostomy as anatomy and urgency dictate, then plan definitive glottic-widening surgery.",
        "explanation": "Cordotomy/arytenoidectomy is a controlled compromise, not a binary cure. The senior decision is how much posterior glottis to sacrifice for adequate ventilation while preserving voice and airway protection.",
        "board_pearl": "In bilateral immobility, enlarge only as much posterior glottis as the airway requires; every additional millimeter is purchased with voice and sometimes swallow function.",
        "depth_layers_v183": {"foundation": "Differentiate bilateral neuropathy from mechanical fixation/posterior glottic stenosis before irreversible widening.", "application": "Use cordotomy first or add arytenoid reduction according to airway requirement and functional reserve.", "senior_decision": "Acute respiratory compromise gets a safe airway first; definitive widening is titrated after the patient is stabilized."},
        "common_traps_v183": ["Assuming every immobile fold is denervated can lead to the wrong irreversible operation in posterior glottic stenosis or joint fixation.", "Maximizing the airway at the first operation ignores the predictable voice and aspiration cost of excessive posterior glottic widening."],
        "deliberate_review_v183": "Preserved the existing titrated-airway/revision principle and added diagnostic confirmation, cordotomy-versus-arytenoid tradeoffs, counseling and acute-airway thresholds."
    },
}


def apply_concept_check_task_alignment_v183(checks):
    by_id = {str(q.get("id") or ""): q for q in checks or []}
    repaired = []
    missing = []
    link_mismatch = []
    for qid, payload in COHORT.items():
        q = by_id.get(qid)
        if q is None:
            missing.append(qid)
            continue
        if q.get("concept_id") != payload["concept_id"] or q.get("canonical_topic") != payload["canonical_topic"]:
            link_mismatch.append(qid)
            continue
        for key in ("prompt", "answer_text", "explanation", "board_pearl", "depth_layers_v183", "common_traps_v183", "deliberate_review_v183"):
            q[key] = payload[key]
        q["task_alignment_v183"] = True
        q.pop("choices", None)
        q.pop("answer", None)
        q.pop("why_wrong", None)
        repaired.append(qid)
    return {"repaired": repaired, "missing": missing, "link_mismatch": link_mismatch}


__all__ = ["COHORT", "apply_concept_check_task_alignment_v183"]
