"""v20.16 — deepen the exact live Laryngeal Anatomy Concept Check siblings."""
from concept_check_board_repair_v177 import _find_module

QIDS = (
    "cc-v112-mgt-laryngology-voice-swallowing-laryngeal-anatomy",
    "cc-v112-rec-laryngology-voice-swallowing-laryngeal-anatomy",
)
CID = "v6-laryngology-voice-swallowing-laryngeal-anatomy"
TOPIC = "Laryngeal Anatomy"

SOURCE_REFS_V216 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus including Cummings_7e_Part_4_pages_1978-2636.pdf (Drive id 1e6jOBnaay1Msf-aDw-Kf9k2_NtzODQEu) and full Cummings 7e copy (Drive id 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t); laryngeal deep-space, posterior-cricoarytenoid, preepiglottic and conservation-surgery anatomy cross-reference refreshed 2026-09-08.","role":"durable operative/anatomic foundation: laryngeal framework, deep-space spread, PCA/postcricoid relationships and conservation-surgery boundaries"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy (Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52), Laryngeal Anatomy and Physiology / laryngeal oncology material cross-referenced 2026-09-08.","role":"resident/board framework: intrinsic-muscle vector actions, vocal-ligament layers, anterior commissure and fixation mechanisms"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy (Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR), The Larynx anatomy/innervation material cross-referenced 2026-09-08.","role":"operative cross-check: vocal versus muscular arytenoid processes, RLN motor/sensory distribution and PCA as the sole abductor"},
    {"type":"consensus_statement","citation":"Fundakowski CE, et al. Surgical management of the recurrent laryngeal nerve in thyroidectomy: American Head and Neck Society Consensus Statement. Head Neck. 2018;40:663-675. DOI: 10.1002/hed.24928.","role":"major head-and-neck society guidance: deliberate RLN identification/preservation, approach selection and management when tumor involves the nerve"},
    {"type":"guideline_statement","citation":"Barczynski M, et al. External branch of the superior laryngeal nerve monitoring during thyroid and parathyroid surgery: International Neural Monitoring Study Group standards guideline statement. Laryngoscope. 2013;123 Suppl 4:S1-S14. PMID: 23832799. DOI: 10.1002/lary.24301.","role":"EBSLN anatomy/function and standardized neural-monitoring principles; monitoring is an adjunct to anatomic preservation"},
    {"type":"systematic_review","citation":"Surgical anatomy of the recurrent laryngeal nerve: a systematic review and meta-analysis of variants. Langenbecks Arch Surg. 2026. DOI: 10.1007/s00423-026-04097-0.","role":"current evidence reinforcing RLN–inferior-thyroid-artery variability and rare clinically important right-sided nonrecurrent nerve"},
    {"type":"anatomic_study","citation":"Saleh HA, et al. The inside-out surgical anatomy of the paraglottic space: a video-guided endoscopic dissection. Laryngoscope Investig Otolaryngol. 2023;8. DOI: 10.1002/lio2.979.","role":"modern endoscopic/cadaveric description showing paraglottic-space extension across supraglottic, glottic and subglottic levels"},
]

ANSWER = """Foundation — build the larynx as a three-dimensional moving framework rather than a list of labels. The thyroid cartilage forms the anterior and lateral framework, the complete cricoid ring provides the posterior platform, the epiglottis participates in supraglottic protection, and each arytenoid sits on a cricoarytenoid joint that permits rotation, rocking, and translation. The arytenoid vocal process projects anteriorly and anchors the vocal ligament/thyroarytenoid complex; the muscular process projects laterally and is the insertion point for the lateral and posterior cricoarytenoid muscles. This distinction is not trivia: the vector applied to the muscular process determines whether the vocal process swings toward or away from the midline.

Intrinsic-muscle map — posterior cricoarytenoid (PCA) is the only abductor of the true vocal folds and is therefore the critical muscle for inspiratory glottic opening. The lateral cricoarytenoid adducts by rotating the vocal process medially; the interarytenoid closes the posterior glottis; the thyroarytenoid/vocalis shortens, thickens, fine-tunes, and contributes to adduction of the membranous fold. Cricothyroid lengthens and tensions the fold by altering the thyroid-cricoid relationship. A patient with bilateral loss of PCA function can have a deceptively acceptable voice while the airway is critically narrow, because adductor tone can leave both folds near the midline. That is an airway problem first, not simply a dysphonia problem.

Neural map — the recurrent laryngeal nerve (RLN) supplies motor innervation to the intrinsic laryngeal muscles except the cricothyroid and supplies sensation below the true vocal folds. The external branch of the superior laryngeal nerve (EBSLN) is the motor supply to the cricothyroid; injury can produce loss of pitch control, vocal fatigue, and subtle weakness without classic immobility. The internal branch of the superior laryngeal nerve (iSLN) is predominantly sensory above the true vocal folds and enters through the thyrohyoid membrane with the superior laryngeal vessels. Losing supraglottic sensation is therefore not the same lesion as losing vocal-fold motor function; it may impair cough triggering and airway protection. Do not label every postoperative voice complaint an RLN injury.

RLN operative anatomy is variable. The nerve usually approaches the larynx near the cricothyroid joint and Berry-ligament region but its relationship to the inferior thyroid artery varies, and extralaryngeal branching is common. Contemporary systematic review data reinforce that anterior, posterior, and interposed RLN–inferior-thyroid-artery relationships all occur, and a nonrecurrent laryngeal nerve, although rare, is clinically important and overwhelmingly right-sided. The practical rule is systematic visual identification and preservation of every plausible motor branch rather than assuming a single textbook trunk. Neuromonitoring can be a useful adjunct, but it does not replace controlled anatomy.

Cricoarytenoid mechanics and localization — an immobile vocal fold is a sign, not a diagnosis. RLN denervation, cricoarytenoid-joint fixation, posterior glottic stenosis, arytenoid dislocation, and tumor infiltration can all reduce motion. Evaluate resting fold position, arytenoid height/rotation, passive mobility when appropriate, contralateral compensation, mucosal wave, history of intubation or surgery, and imaging for deep-space or joint disease. Laryngeal EMG may help when denervation versus mechanical fixation remains uncertain. In the operating room, passive palpation of the arytenoid/cricoarytenoid joint can be useful, but forceful manipulation is not a substitute for diagnosis and can itself injure the joint.

Vocal-fold microstructure — think epithelium, superficial lamina propria, intermediate lamina propria, deep lamina propria, and thyroarytenoid muscle. The intermediate and deep lamina propria form the vocal ligament; the superficial lamina propria is a key pliable component of the cover. These layers have different mechanical roles, so a superficial scar, an epithelial lesion, and a deep infiltrative process are not equivalent. Microlaryngeal surgery that violates the superficial lamina propria or ligament unnecessarily can convert a removable lesion into permanent stiffness. The clinical target is preservation of the layered vibratory apparatus whenever oncologically safe.

Fibroelastic membranes — the quadrangular membrane forms a supraglottic fibroelastic framework; its inferior free edge contributes to the vestibular ligament. The conus elasticus is the lower fibroelastic framework; its superior free edge forms the vocal ligament, and its anterior midline thickening contributes to the cricothyroid ligament. Confusing these structures leads to incorrect compartment reasoning. They also help orient how tumor can cross from a mucosal site into deeper laryngeal spaces.

Deep spaces — the preepiglottic space lies anterior to the epiglottis and is an important route of supraglottic tumor spread. The paraglottic space lies lateral to the laryngeal lumen and extends alongside supraglottic, glottic, and subglottic levels; it contains fat, vessels, nerves, and portions of intrinsic musculature and communicates with neighboring deep compartments. Modern cadaveric/endoscopic work reinforces that the paraglottic space is not a tiny isolated 'glottic' box. Deep-space invasion can explain impaired mobility even when the mucosal lesion seems limited, and it changes oncologic staging, resectability, and the safety of conservation procedures.

Anterior commissure — the anterior commissure is where the true vocal folds meet anteriorly and where the vocal ligaments attach to the thyroid cartilage through the Broyles ligament region. The anatomy is surgically important because there is little soft-tissue barrier between mucosa/ligament and thyroid cartilage at this attachment. Do not teach the anterior commissure as an automatic pathway guaranteeing cartilage invasion, but do recognize it as a high-stakes area for margin planning, endoscopic exposure, and imaging interpretation. Poor exposure can make an apparently small lesion unsafe for a conservation approach.

Application — localize before treating. A paramedian immobile fold after thyroid or skull-base disease is compatible with RLN dysfunction, but position alone cannot prove the lesion. If cricothyroid function is also impaired, consider a more proximal vagal lesion or separate EBSLN involvement. If the fold is immobile yet the arytenoid is mechanically fixed, passive joint motion is absent and history suggests prolonged intubation, posterior glottic stenosis or cricoarytenoid fixation may be more likely than isolated denervation. If imaging shows paraglottic involvement, cartilage erosion, or cricoarytenoid-joint invasion, tumor-related fixation must move up the differential. The same visible endpoint—'cord does not move'—can therefore arise from very different anatomy and requires different management.

Senior airway decision — bilateral vocal-fold immobility near midline demands an airway assessment before elective voice optimization. Look for stridor, work of breathing, exertional limitation, oxygenation, speed of progression, and the possibility of dynamic deterioration. If the airway is threatened, secure it using the safest controlled strategy for the patient and anatomy; do not persist with prolonged diagnostic manipulation through a critically narrow glottis. Posterior cordotomy, arytenoidectomy, reinnervation, pacing, tracheostomy, or observation are disease- and patient-specific decisions, and none should be chosen until the cause of immobility and likelihood of recovery are understood. A destructive glottic-widening procedure performed for temporary neuropraxia or unrecognized mechanical fixation can create avoidable aspiration or permanent voice loss.

Senior operative nerve protection — during thyroid/parathyroid and open neck surgery, expect RLN branching and EBSLN variability. Identify the nerve in a controlled segment, avoid traction and thermal spread, and do not clamp or divide a structure merely because it is in the 'usual' relationship to the inferior thyroid artery. Near the superior pole, preserve the EBSLN by capsule-oriented vascular control and attention to the cricothyroid muscle entry zone. If there is loss of nerve signal, stop the injuring maneuver, release traction, irrigate/cool as appropriate, reassess the stimulation pathway and electrode setup, and map proximal/distal responses rather than blindly continuing. The bailout is anatomy plus physiology, not more dissection simply to finish the planned operation.

Oncologic senior decision — mobility is a functional staging clue but must be interpreted anatomically. Fixation may reflect deep muscle, cricoarytenoid-joint, paraglottic, or neural invasion. Preepiglottic and paraglottic extension can make a superficially appealing partial procedure oncologically inadequate. Conversely, do not sacrifice cartilage, nerve, or an entire larynx merely because a deep-space boundary is feared; define actual extent with endoscopy, imaging, palpation, and the oncologic operation's accepted selection criteria. Durable textbook anatomy remains the foundation, while contemporary imaging, staging, and conservation techniques determine how that anatomy is used.

Rescue/bailout synthesis — if localization is uncertain, do not create irreversible injury to prove a hypothesis. In bilateral immobility with a marginal airway, prioritize oxygenation and a controlled airway. In suspected RLN injury, document pre/postoperative laryngeal function and use EMG or interval observation when recovery potential matters. In possible joint fixation, verify mechanical mobility rather than treating presumed denervation. In tumor, respect preepiglottic/paraglottic and anterior-commissure pathways and do not let poor exposure drive an inadequate margin. In thyroid surgery, assume branching until anatomy proves otherwise and protect the EBSLN separately. The senior skill is to convert anatomy into a decision tree: identify the moving framework, map the responsible nerve/muscle, decide whether the problem is neurogenic, mechanical, scar-related, or infiltrative, and stop or change strategy before an uncertain localization becomes an airway catastrophe or permanent functional deficit."""

COHORT = {
    QIDS[0]: {
        "concept_id": CID,
        "canonical_topic": TOPIC,
        "prompt": "A 62-year-old patient with progressive dysphonia undergoes flexible laryngoscopy showing one true vocal fold immobile near the paramedian position, while the arytenoid complex appears subtly asymmetric. CT shows no obvious mass. As the resident presenting the case, use laryngeal anatomy to localize the likely lesion and explain what additional findings would distinguish recurrent-laryngeal-nerve denervation from cricoarytenoid joint fixation or infiltrative disease. Include the intrinsic-muscle actions, arytenoid processes, superior-versus-recurrent laryngeal nerve territories, vocal-fold microstructure, and the preepiglottic/paraglottic spaces that matter when interpreting endoscopy, imaging, and operative risk.",
        "answer_text": ANSWER,
        "explanation": "An immobile vocal fold is an anatomic finding, not a diagnosis: localize the moving framework, muscle/nerve territory, joint mechanics, deep spaces and layered vocal fold before selecting treatment.",
        "board_pearl": "PCA is the only abductor; RLN supplies all intrinsic muscles except cricothyroid, EBSLN supplies cricothyroid, and iSLN provides supraglottic sensation. Vocal-fold fixation requires neurogenic, mechanical, scar and infiltrative localization.",
        "depth_layers_v216": {"foundation":"Framework/cartilages, cricoarytenoid mechanics, arytenoid processes, intrinsic muscles, RLN/SLN territories, vocal-fold layers and fibroelastic membranes.","application":"Differentiate denervation from fixation/dislocation/scar/tumor; interpret endoscopy, imaging, EMG and deep-space/anterior-commissure involvement.","senior_decision":"Protect RLN/EBSLN variants, prioritize bilateral-airway risk, preserve vibratory layers and stop irreversible intervention when localization remains uncertain."},
        "common_traps_v216": [
            "Calling any immobile vocal fold an RLN palsy without considering cricoarytenoid fixation, posterior glottic stenosis, arytenoid dislocation, or tumor infiltration.",
            "Forgetting that the posterior cricoarytenoid is the only true vocal-fold abductor and missing the airway significance of bilateral PCA failure.",
            "Assigning cricothyroid motor function to the RLN instead of the external branch of the superior laryngeal nerve.",
            "Confusing internal superior-laryngeal sensory loss with motor vocal-fold paralysis.",
            "Using resting vocal-fold position alone to localize the level or cause of a vagal/RLN lesion.",
            "Confusing the arytenoid vocal process with the muscular process and therefore reversing intrinsic-muscle vector logic.",
            "Treating the superficial, intermediate, and deep lamina propria as one homogeneous layer during microlaryngeal surgery.",
            "Confusing the quadrangular membrane with the conus elasticus and mislocalizing supraglottic versus glottic fibroelastic anatomy.",
            "Ignoring paraglottic or preepiglottic extension because the visible mucosal lesion appears small.",
            "Assuming the anterior commissure/Broyles region guarantees cartilage invasion rather than recognizing it as a high-risk attachment requiring careful staging and margins.",
            "Assuming the RLN is always a single unbranched trunk in a fixed relationship to the inferior thyroid artery.",
            "Missing a proximal vagal or combined nerve lesion when both vocal-fold motion and cricothyroid function are impaired.",
            "Using forceful arytenoid palpation as a substitute for diagnostic localization when mechanical fixation remains uncertain.",
            "Proceeding directly to irreversible glottic-widening surgery before determining whether bilateral immobility could recover.",
        ],
        "deliberate_review_v216": "Selected from the exact successful v20.15 production backlog (325 canonical topics, 618 Concept Checks, 159 untouched candidates, 8 residual candidates, 0 failures). Both exact live Laryngeal Anatomy siblings remained shallow despite high resident/board/OR value, so clinical priority intentionally overrides lexical rank. The management sibling emphasizes localization of immobility and deep-space disease.",
        "source_refs_v216": SOURCE_REFS_V216,
        "evidence_distinction_v216": "Durable anatomy and operative relationships are textbook-grounded; contemporary literature is used to reinforce RLN variability, EBSLN preservation and paraglottic-space geometry rather than to overwrite stable anatomy with transient management fashion.",
    },
    QIDS[1]: {
        "concept_id": CID,
        "canonical_topic": TOPIC,
        "prompt": "During microlaryngoscopy for a patient with bilateral vocal-fold immobility and a prior thyroid operation, the cords sit close to midline and exposure is limited. Before any posterior glottic-widening procedure is considered, the chief asks you to map the anatomy that determines airway, voice, and oncologic safety. Explain the laryngeal framework, cricoarytenoid mechanics, intrinsic muscles, recurrent and superior laryngeal nerve territories, vocal-fold layers, quadrangular membrane and conus elasticus, anterior commissure, and preepiglottic/paraglottic spaces. Then describe the senior decision points and bailouts that prevent an anatomic localization error from becoming an airway or nerve injury.",
        "answer_text": ANSWER,
        "explanation": "Senior laryngeal anatomy means translating framework, joint, nerve, muscle, mucosal-layer and deep-space anatomy into airway, nerve-preservation and oncologic bailout decisions.",
        "board_pearl": "Bilateral near-midline immobility can preserve voice but critically obstruct inspiration because PCA is the sole abductor; establish cause and recovery potential before irreversible posterior glottic-widening surgery.",
        "depth_layers_v216": {"foundation":"Framework/cartilages, CA-joint movement, PCA/adductor vectors, RLN/SLN territories, vocal-fold microstructure, conus/quadrangular membrane and deep spaces.","application":"Map bilateral immobility, prior thyroid-surgery nerve risk, endoscopic orientation, joint fixation versus neuropathy and oncologic spread.","senior_decision":"Secure a threatened airway, troubleshoot loss of signal rather than blindly dissecting, preserve RLN/EBSLN branches and avoid irreversible glottic widening or conservation surgery without anatomic localization."},
        "common_traps_v216": [
            "Treating bilateral near-midline vocal folds as primarily a voice problem instead of recognizing potential critical inspiratory obstruction.",
            "Performing a posterior cordotomy or arytenoidectomy before distinguishing temporary denervation from fixed joint/scar disease.",
            "Forgetting that the PCA is the only abductor and that bilateral loss can preserve voice while severely narrowing the airway.",
            "Confusing the arytenoid vocal process with the muscular process during posterior glottic surgery.",
            "Failing to account for cricoarytenoid-joint rotation and translation when planning a posterior glottic-widening procedure.",
            "Assuming an RLN always enters as one trunk and injuring an extralaryngeal motor branch near the laryngeal entry point.",
            "Protecting the RLN while overlooking the EBSLN at the superior pole and then mislabeling postoperative pitch loss as RLN palsy.",
            "Confusing iSLN sensory territory with EBSLN motor territory and overlooking aspiration risk from sensory loss.",
            "Violating superficial lamina propria or vocal ligament unnecessarily during microlaryngeal exposure and creating permanent stiffness.",
            "Confusing quadrangular membrane and conus elasticus boundaries when reasoning about deep extension.",
            "Underestimating paraglottic/preepiglottic spread and choosing a conservation operation from mucosal appearance alone.",
            "Letting poor anterior-commissure exposure drive an inadequate oncologic margin.",
            "Continuing traction, thermal work, or blind dissection after loss of nerve signal instead of stopping and troubleshooting anatomy/physiology.",
            "Persisting with diagnostic instrumentation through a critically narrow bilateral glottis rather than securing a controlled airway.",
        ],
        "deliberate_review_v216": "Selected from the same exact successful v20.15 production backlog and linked to the same exact live canonical. This recommendation/senior sibling deliberately tests bilateral-airway danger, posterior-glottic operative anatomy, nerve-injury rescue and oncologic bailout rather than duplicating a definitions-only anatomy recall question.",
        "source_refs_v216": SOURCE_REFS_V216,
        "evidence_distinction_v216": "Stable textbook anatomy remains authoritative; current society guidance and modern anatomic studies refine operative risk and variation without converting this foundational concept into a disease-specific management guideline.",
    },
}

def apply_concept_check_task_alignment_v216(checks, deep_modules, v6_item_id):
    by={str(q.get("id") or ""):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get("topic") or "") if m else ""; cid=v6_item_id(q.get("domain"),topic) if m and q.get("domain") else None
        if m is None or topic!=p["canonical_topic"] or cid!=p["concept_id"] or q.get("concept_id")!=cid: link_mismatch.append(qid); continue
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v216","common_traps_v216","deliberate_review_v216","source_refs_v216","evidence_distinction_v216"): q[field]=p[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v216"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
