"""v20.18 — deepen the exact live Cranial Nerve Examination / Skull Base Localization Concept Check."""
from concept_check_board_repair_v177 import _find_module

QIDS = (
    "cc-v112-rec-general-ent-emergencies-cranial-nerve-examination-skull-base-localization",
)
CID = "v6-general-ent-emergencies-cranial-nerve-examination-skull-base-localization"
TOPIC = "Cranial Nerve Examination / Skull Base Localization"

SOURCE_REFS_V218 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus checked 2026-09-08; full/compressed copies and split Parts 1-6 are present (including Drive ids 1qxx-V0VT-K6_6nypNxzgr2cxZAMo_FIj, 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t, and split corpus 1Dl2D7ARIi_uLdG0q7QdE0CEuWrX6LVND through 1fFgAekn6pbtn5jRiO7pSMb8Ui2vdm6lG). Topic-level connector extraction for the oversized/split Cummings corpus was not reliably available in this pass, so no unsupported page-level claim is made.","role":"required core-text cross-check and durable skull-base/cranial-nerve anatomy reference; management assertions are separately updated with current guidance below"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy, Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52, cranial-nerve/skull-base localization material cross-checked 2026-09-08.","role":"resident/board framework for focused cranial-nerve examination, lower-cranial-nerve dysfunction, facial-nerve differential diagnosis, and ENT localization"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy, Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; syndromes/skull-base material cross-checked 2026-09-08. Indexed text specifically identifies Collet-Sicard syndrome as unilateral CN IX-XII palsy and distinguishes it from syndromes with sympathetic involvement.","role":"durable localization cross-check for clustered lower cranial neuropathies and named skull-base syndromes"},
    {"type":"appropriateness_criteria","citation":"American College of Radiology. ACR Appropriateness Criteria: Cranial Neuropathy. Current online narrative reviewed 2026-09-08.","role":"current imaging layer: cranial neuropathy imaging should be targeted to the nerve/pathway and suspected compartment, with contrast-enhanced MRI frequently central and CT/vascular studies selected for osseous or vascular questions"},
    {"type":"society_guidance","citation":"American Academy of Otolaryngology-Head and Neck Surgery. AAO13: Bell's Palsy: Inappropriate Use of MRI or CT Scan+, 2026 measure; reviewed 2026-09-08.","role":"current diagnostic boundary: do not routinely image a classic new Bell palsy, but image earlier when the presentation is atypical, including recurrent/branch-limited paralysis, other cranial-nerve deficits, or other neurologic abnormalities"},
    {"type":"systematic_review","citation":"Kumar LP, et al. Current Evidence in the Management of Central Skull Base Osteomyelitis: A Systematic Review. J Neurol Surg B Skull Base. 2025;86(3):360-369. PMID: 40351881. DOI: 10.1055/a-2297-9474.","role":"current disease-layer reminder that skull-base osteomyelitis can produce cranial neuropathies and requires diagnosis of the underlying infectious skull-base process rather than symptomatic nerve labeling alone"},
    {"type":"peer_reviewed_review","citation":"Supsupin EP Jr, Gonzales NS, Debnam JM. Anatomy and Pathology of the Skull Base: Malignant and Nonmalignant Lesions. Oral Maxillofac Surg Clin North Am. 2023;35(3):413-433. PMID: 37142448. DOI: 10.1016/j.coms.2023.03.001.","role":"modern imaging/anatomic review emphasizing skull-base foramina as routes connecting intracranial and extracranial compartments and pathways for disease spread"},
]

ANSWER = """Foundation — do not treat a cranial-nerve examination as twelve unrelated checkbox maneuvers. In ENT, the high-value question is whether the pattern localizes to a nerve, a skull-base foramen/compartment, the brainstem, the cavernous sinus/orbital apex, the temporal bone/internal auditory canal, the jugular foramen, the hypoglossal canal, or a more diffuse meningeal/inflammatory process. Multiple ipsilateral cranial neuropathies, progressive deficits, or a deficit that does not fit the expected course of a single peripheral nerve should trigger localization before diagnostic labels are assigned. The first senior move is to repeat a complete side-to-side examination yourself, document the time course, and identify which functions are threatened while the etiologic workup proceeds.

Map the major skull-base clusters. CN III, IV, V1, V2, and VI travel in or through the cavernous-sinus region; sympathetic fibers also course with the carotid plexus, so ophthalmoplegia plus facial sensory loss and Horner-type findings can point to this compartment. CN II joins the ophthalmoplegia pattern at the orbital apex, making visual acuity, pupils, color/field complaints, and afferent pupillary function critical discriminators. CN VII and VIII cluster in the cerebellopontine angle/internal auditory canal before the facial nerve continues through the temporal bone. CN IX, X, and XI traverse the jugular foramen; CN XII exits the hypoglossal canal nearby. A unilateral IX-XII pattern is classically described as Collet-Sicard syndrome. If sympathetic dysfunction accompanies a lower-cranial-nerve cluster, the lesion may extend into the parapharyngeal/carotid-space sympathetic chain rather than remaining confined to the jugular-foramen/hypoglossal-canal complex.

Build the focused exam from function. For CN V, compare facial sensation in V1/V2/V3, corneal reflex components when clinically appropriate, and muscles of mastication. For VII, determine whether weakness is upper- and lower-face peripheral pattern or predominantly lower-face central pattern, then look for clues that make an idiopathic Bell palsy diagnosis unsafe: other cranial neuropathies, recurrent same-side paralysis, branch-selective weakness, progressive course, hearing/vestibular symptoms, parotid or temporal-bone findings, trauma, cancer history, or cutaneous vesicles. For VIII, assess hearing and vestibular symptoms rather than writing 'CN VIII intact' without testing. For IX/X, inspect palatal movement and secretion handling, listen for wet/breathy dysphonia, assess cough and swallowing, and perform flexible laryngoscopy when vocal-fold mobility or pharyngeal/laryngeal function is in question. For XI, test trapezius and sternocleidomastoid strength; for XII, inspect tongue bulk/fasciculation and protrusion. Tongue deviation with atrophy/fasciculation supports lower-motor-neuron XII dysfunction rather than simply 'weak tongue.'

Application — once the pattern is established, choose imaging to answer the localization question. MRI with contrast is generally the principal soft-tissue/nerve-pathway study for unexplained progressive or multiple cranial neuropathies, but the protocol and field of view must cover the suspected pathway rather than stopping at a generic noncontrast head MRI. The ACR Cranial Neuropathy criteria are nerve- and scenario-specific: imaging should follow the anatomy. Add high-resolution CT of the temporal bone or skull base when the question is bony erosion, foraminal remodeling, temporal-bone disease, calcification, fracture, or osseous skull-base infection. Add CTA/MRA, and when appropriate venous imaging, when a vascular lesion, carotid-space process, cavernous-sinus thrombosis, aneurysm, dissection, or other vascular complication is plausible. A normal routine head CT does not close a skull-base workup when the clinical localization remains compelling.

Cavernous-sinus/orbital-apex reasoning — painful ophthalmoplegia is a localization, not a diagnosis. Check pupils and vision before assuming an isolated ocular-motor palsy. Cavernous-sinus disease can affect III, IV, V1, V2, VI and sympathetic fibers; orbital-apex disease can add optic-nerve dysfunction. Infection, inflammation, neoplasm, thrombosis, vascular lesions, and invasive sinonasal disease can overlap clinically. New visual loss, an afferent pupillary defect, severe proptosis/orbital signs, rapidly progressive ophthalmoplegia, or systemic toxicity changes the urgency because vision, intracranial spread, or a vascular/infectious catastrophe may be threatened. In that setting, stabilize the patient, obtain the appropriate urgent imaging and specialty help, and treat the underlying emergency rather than waiting for every diagnostic detail to mature.

Jugular-foramen/lower-cranial-nerve reasoning — dysphonia, dysphagia, aspiration, palatal weakness, shoulder weakness, and tongue weakness should not be collapsed into 'lower cranial neuropathy' without functional triage. IX/X dysfunction may threaten airway protection and nutrition now. Flexible laryngoscopy helps document vocal-fold mobility and pharyngeal/laryngeal function; a formal swallow evaluation is appropriate when aspiration risk is uncertain or clinically important. Nutrition and pulmonary consequences may need treatment before the final pathology is known. XI weakness can be subtle early and deserves direct trapezius/SCM testing. XII weakness can impair bolus control and, in bilateral or extensive disease, compound airway/swallow dysfunction. The diagnostic workup then follows the jugular foramen, hypoglossal canal, carotid space, nasopharynx, temporal bone, and central skull base according to the exact pattern.

Skull-base osteomyelitis trap — in an older, diabetic, immunocompromised, or otherwise at-risk patient with severe otalgia/headache, chronic otologic disease, granulation or external-canal findings, and new cranial neuropathies, think beyond 'Bell palsy' or 'stroke ruled out.' Skull-base osteomyelitis may extend centrally and involve multiple cranial nerves. Current literature continues to describe substantial morbidity, difficult microbiologic diagnosis, and the importance of tissue/culture-directed evaluation in selected patients. The durable localization principle is that new VI, VII, IX, X, XI, or XII deficits can be a map of disease extension. Management is directed at the underlying infection with appropriate imaging, microbiology/pathology when needed, antimicrobial planning, glycemic/comorbidity optimization, and multidisciplinary care—not empiric long-term treatment based solely on a cranial-nerve label.

Facial-paralysis boundary — do not over-image every classic Bell palsy, but do not use the Bell-palsy guideline to suppress imaging when the phenotype is atypical. AAO-HNS guidance advises against routine imaging for a typical new-onset Bell palsy; its current 2026 quality measure explicitly lists involvement of other cranial nerves, recurrent paralysis, branch-limited paralysis, and other neurologic abnormalities as reasons imaging may be appropriate sooner. This distinction is important: isolated acute peripheral VII weakness with a classic course is different from VII weakness embedded in a skull-base syndrome. The management error is not merely 'ordering too many MRIs'; it is failing to recognize when the patient no longer meets the clinical construct of uncomplicated Bell palsy.

Oncologic application — progressive unilateral multiple cranial neuropathies, especially with deep pain, trismus, unilateral serous otitis, nasal symptoms, neck/parotid findings, weight loss, or prior malignancy, should raise concern for a skull-base, nasopharyngeal, parotid, perineural-spread, or metastatic process. Perineural tumor spread may track along named nerves and skull-base foramina. Image the full expected nerve course and the suspected primary compartment. If tissue diagnosis is required, identify the safest target after imaging. Do not biopsy a pulsatile, hypervascular, carotid-space, or otherwise potentially vascular lesion before its vascular anatomy is understood.

Senior decision — the bedside examination determines which failures cannot wait. Corneal exposure from VII dysfunction requires eye protection now. Vision-threatening orbital/apical disease requires urgent escalation. IX/X dysfunction with aspiration, secretion failure, bilateral vocal-fold impairment, or progressive airway symptoms requires airway/swallow planning before routine outpatient workup. Severe dysphagia may require temporary nutritional support. New shoulder dysfunction from XI injury deserves early documentation and rehabilitation planning. These functional protections can proceed in parallel with etiologic diagnosis; 'treat the underlying lesion' is incomplete if the patient loses vision, aspirates, develops pneumonia, or suffers preventable corneal injury while the workup is pending.

Vascular and procedural bailout — a skull-base mass is not automatically a biopsy target. Pulsatility, flow voids, carotid-space location, lower-cranial-nerve deficits with sympathetic findings, brisk unexplained bleeding, or imaging suspicion for paraganglioma/vascular pathology should trigger vascular characterization before instrumentation. Similarly, a suspected cavernous-sinus or carotid complication should not be managed by blind transnasal exploration. Stop, localize, obtain the appropriate vascular imaging, and involve the necessary skull-base, neurovascular, radiology, ophthalmology, neurology, or neurosurgical teams according to the threat.

Localization synthesis — use clustered deficits to narrow the compartment: III/IV/V1/V2/VI with or without sympathetic findings suggests cavernous-sinus disease; optic dysfunction added to ophthalmoplegia pushes the localization toward the orbital apex; VII/VIII points toward CPA/IAC/temporal-bone pathways; IX/X/XI points to the jugular foramen; IX-XII is the classic Collet-Sicard lower-skull-base cluster; lower cranial nerves plus sympathetic dysfunction suggests extension beyond the foramina into the carotid/parapharyngeal space. These are organizing patterns, not substitutes for imaging or pathology. Tumor, infection, inflammation, trauma, vascular disease, and treatment injury can occupy the same compartment.

Bailout synthesis — if the deficit pattern does not fit a single named nerve, do not force it into a familiar diagnosis. Repeat the examination, verify that the finding is real, localize the shared anatomic corridor, and image that corridor with the modality needed to answer the question. If the patient has threatened vision, cornea, airway, swallow, or a possible vascular lesion, protect that function before pursuing an elegant diagnostic sequence. The board-level answer is to recognize clustered cranial neuropathies as a localization problem. The resident-level answer is to perform and document the exam that proves the localization and select imaging that covers the entire pathway. The senior-level answer is to know which atypical pattern invalidates a benign label, which function needs rescue immediately, which lesion must not be blindly biopsied, and when uncertainty should trigger broader skull-base/vascular evaluation rather than diagnostic momentum."""

COHORT = {
    QIDS[0]: {
        "concept_id": CID,
        "canonical_topic": TOPIC,
        "prompt": "A 68-year-old patient with diabetes develops progressive deep otalgia and headache followed by dysphonia, aspiration symptoms, ipsilateral shoulder weakness, tongue weakness, and a new peripheral facial paresis. A routine emergency-department head CT is reported as unrevealing. As the ENT resident, localize the deficits before naming a diagnosis, identify the bedside functions that require immediate protection, choose imaging that actually covers the suspected skull-base pathways, and explain what would make a Bell-palsy label unsafe. How would your plan change if the lesion were pulsatile or vascular-appearing, if vision were threatened, or if airway/swallow function deteriorated?",
        "answer_text": ANSWER,
        "explanation": "Multiple or progressive cranial neuropathies are a localization problem before they are a diagnostic label: map the shared skull-base corridor, protect threatened function immediately, image the entire relevant nerve pathway, and do not biopsy or instrument a potentially vascular lesion before characterization.",
        "board_pearl": "A normal routine head CT does not clear the skull base. Clustered IX-XII deficits localize to the lower skull base; additional sympathetic findings imply extension beyond the foramina, and any additional cranial neuropathy makes an uncomplicated Bell-palsy label unsafe.",
        "depth_layers_v218": {"foundation":"Focused CN examination, cavernous-sinus/orbital-apex, CPA/IAC/temporal-bone, jugular-foramen and hypoglossal-canal clustering, including Collet-Sicard localization.","application":"Use the deficit pattern to choose contrast MRI versus high-resolution CT and vascular imaging; distinguish typical Bell palsy from atypical skull-base disease; recognize infection, neoplasm and perineural spread patterns.","senior_decision":"Protect cornea/vision/airway/swallow/nutrition in parallel with diagnosis, avoid blind biopsy of vascular-appearing lesions, and escalate urgent skull-base/vascular workup when the pattern is progressive, multiple, or function-threatening."},
        "common_traps_v218": [
            "Documenting 'cranial nerves intact' without actually testing palate, vocal-fold function, tongue, trapezius/SCM, hearing, pupils, facial sensation, and ocular motility.",
            "Calling progressive facial weakness Bell palsy despite additional cranial neuropathies.",
            "Using a normal routine noncontrast head CT to close a clinically compelling skull-base localization.",
            "Ordering generic brain imaging that does not cover the full extracranial skull-base/nerve pathway suggested by the examination.",
            "Missing threatened corneal protection while waiting for the etiologic diagnosis of facial paralysis.",
            "Ignoring aspiration, secretion failure, or vocal-fold dysfunction while pursuing an outpatient lower-cranial-nerve workup.",
            "Confusing a jugular-foramen IX-XI pattern with the broader IX-XII Collet-Sicard pattern.",
            "Failing to recognize that lower cranial neuropathies plus sympathetic dysfunction can imply carotid/parapharyngeal-space extension.",
            "Treating painful ophthalmoplegia as a diagnosis rather than checking vision/pupils and localizing cavernous sinus versus orbital apex.",
            "Forgetting skull-base osteomyelitis in an at-risk patient with severe otalgia/headache and new multiple cranial neuropathies.",
            "Failing to consider malignancy/perineural spread when unilateral neuropathies are progressive or associated with deep pain, trismus, parotid, nasal, or neck findings.",
            "Biopsying a pulsatile or vascular-appearing skull-base/carotid-space lesion before vascular characterization.",
            "Using navigation or imaging as a substitute for a reproducible bedside cranial-nerve examination and anatomic localization.",
            "Waiting for final pathology before protecting airway, swallow, nutrition, vision, or cornea when those functions are already threatened.",
            "Assuming named skull-base syndromes identify etiology; they localize a compartment but infection, tumor, inflammation, trauma, and vascular disease can share it.",
        ],
        "deliberate_review_v218": "Selected from the exact successful v20.17 production backlog despite lexical rank #6 because the live 22-word answer under-taught a high-yield resident/board/emergency localization skill. Review is deliberately centered on clustered-nerve localization, imaging-by-pathway, atypical Bell-palsy recognition, lower-CN functional rescue, skull-base osteomyelitis/perineural-spread traps, and vascular biopsy bailout.",
        "source_refs_v218": SOURCE_REFS_V218,
        "evidence_distinction_v218": "Durable foraminal anatomy and localization are grounded in the core ENT textbook set: Cummings 7e was explicitly checked in the connected Drive, with Pasha 6e and K.J. Lee 12e used for directly retrievable resident/board cross-checks. Current management is separated from that durable anatomy: ACR Cranial Neuropathy guidance informs pathway-directed imaging; the AAO-HNS 2026 Bell-palsy quality measure preserves the no-routine-imaging rule only for typical Bell palsy and explicitly recognizes other cranial-nerve deficits as an atypical feature; current skull-base osteomyelitis literature reinforces infection as an important multiple-neuropathy cause. No FDA drug/device indication governs this examination/localization concept, so no product indication is represented as an anatomy or imaging rule.",
        "audit_profile_v218": "cranial_nerve_skull_base_localization",
    },
}

def apply_concept_check_task_alignment_v218(checks, deep_modules, v6_item_id):
    by={str(q.get("id") or ""):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get("topic") or "") if m else ""; cid=v6_item_id(q.get("domain"),topic) if m and q.get("domain") else None
        persisted_cid=q.get("concept_id")
        if m is None or topic!=p["canonical_topic"] or cid!=p["concept_id"] or (persisted_cid is not None and persisted_cid!=cid): link_mismatch.append(qid); continue
        q["concept_id"]=cid; q["canonical_topic"]=topic
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v218","common_traps_v218","deliberate_review_v218","source_refs_v218","evidence_distinction_v218","audit_profile_v218"): q[field]=p[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v218"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
