"""Preserved v20.7 Esophageal Foreign Body depth implementation."""
from concept_check_board_repair_v177 import _find_module

SOURCE_REFS_V207 = [
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed., Pediatric Aerodigestive Foreign Bodies chapter; connected Drive corpus.","role":"foundation/operative: symptoms and localization, AP/lateral radiography, coin-versus-button-battery signs, endoscopic retrieval principles, mucosal injury and delayed complications"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022); connected Drive copy.","role":"foundation/operative: cervical esophageal anatomy, rigid endoscopy, foreign-body and food-impaction management"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019); connected Drive copy.","role":"foundation/operative: esophageal anatomy, aerodigestive foreign-body presentation, endoscopic rescue and perforation awareness"},
 {"type":"position_statement","citation":"Ledder O, et al. Foreign body ingestions in children and adolescents: A position paper of the ESPGHAN endoscopy special interest group. J Pediatr Gastroenterol Nutr. 2026; doi:10.1002/jpn3.70485.","role":"current management: object type, anatomic location, symptoms and time since ingestion drive intervention urgency and endoscopic strategy"},
 {"type":"toxicology_guideline","citation":"National Capital Poison Center. Button Battery Ingestion Triage and Treatment Guideline. Current online guideline accessed 2026-09-04.","role":"current button-battery rescue: immediate esophageal removal, honey/sucralfate mitigation without delaying removal, post-removal injury assessment and delayed fistula/vascular surveillance"},
 {"type":"society_guideline","citation":"ASGE. Management of ingested foreign bodies and food impactions.","role":"general endoscopic timing: emergent removal for complete esophageal obstruction and esophageal disk battery; ENT consultation for objects at/above the cricopharyngeus; timely removal of esophageal coins and sharp objects"},
 {"type":"current_society_teaching","citation":"ASGE. The 2 AM Page: A Fellow's Approach to Foreign Body Ingestion and Food Impaction. 2026-08-19.","role":"current practical timing and retrieval teaching: emergent complete obstruction/button battery/sharp esophageal object, urgent remaining esophageal foreign bodies, object-specific retrieval strategy and careful food-bolus technique"},
]
CONCEPT_ID="v6-general-ent-emergencies-esophageal-foreign-body"; TOPIC="Esophageal Foreign Body"
Q_REC="cc-v112-rec-general-ent-emergencies-esophageal-foreign-body"; Q_MGT="cc-v112-mgt-general-ent-emergencies-esophageal-foreign-body"
FOUNDATION_ANSWER="""Foundation — first decide whether this is an airway problem, an esophageal obstruction, or both. Drooling, inability to handle secretions, dysphagia, odynophagia, vomiting, food refusal and chest/neck pain point toward esophageal impaction; stridor, severe respiratory distress or inability to protect the airway changes the first priority to airway stabilization. The classic cervical narrowing is the cricopharyngeus/upper esophageal sphincter, with additional physiologic narrowings distally. Objects at or above the cricopharyngeus sit squarely in ENT territory because rigid endoscopic exposure and airway control may be needed.

Imaging — for a suspected radiopaque object obtain AP and lateral films that include the neck, chest and abdomen when object location is uncertain. Do not call a circular density a coin until a button battery has been excluded. A button battery may show a double-ring/halo sign on AP view and a step-off on lateral view. Orientation also helps distinguish airway from esophageal location: an esophageal coin commonly lies in the coronal plane, while airway foreign bodies more often align sagittally, but location must be confirmed rather than inferred from one sign. Avoid delaying definitive removal in a symptomatic child or a known high-risk object for elaborate imaging.

Object-specific urgency — complete esophageal obstruction with inability to manage secretions is emergent regardless of object type. An esophageal button battery is an immediate-removal emergency because severe alkali injury can develop rapidly. Sharp objects in the esophagus and magnets within endoscopic reach require urgent/emergent specialist removal according to object and physiology. A blunt coin in an asymptomatic child may sometimes be observed briefly for spontaneous passage, but persistent esophageal coins should be removed within the accepted short window rather than left for days.

Button battery nuance — if a child at least 12 months old swallowed a possible lithium coin cell within the prior 12 hours and can swallow, current Poison Center guidance supports honey during transport; after radiographic confirmation of an esophageal battery, sucralfate may also be used before endoscopy. Neither treatment substitutes for removal and neither should delay transport, anesthesia or endoscopy. After removal, inspect the injury and think beyond the mucosa: delayed tracheoesophageal fistula, recurrent laryngeal nerve injury, perforation, mediastinitis and catastrophic vascular fistula can occur after the battery is gone. Injury location relative to the aorta or other major vessels determines surveillance intensity.

Operative principles — secure an airway appropriate to the patient's physiology and object location, then expose the hypopharynx/cervical esophagus under direct vision. Choose rigid versus flexible endoscopy according to location, operator expertise, object shape and need for airway control; proximal/cervical objects are often well suited to rigid esophagoscopy by ENT. Use a retrieval instrument that controls the object rather than allowing it to tumble. Protect sharp points during withdrawal when possible. Stop if resistance suggests the object is embedded or the wall is being injured; forcing extraction can convert a contained impaction into a perforation.

Perforation concern — severe neck/chest pain, crepitus, fever, tachycardia, subcutaneous emphysema, pneumomediastinum or a difficult traumatic extraction should trigger evaluation for esophageal injury. Keep the patient NPO, involve surgery/ENT/GI early, use cross-sectional imaging with a contrast strategy appropriate to the scenario, and treat contamination/source control rather than reflexively performing repeated instrumentation.

Food impaction is not the endpoint — after successful disimpaction, ask why the food stuck. In children and young adults, eosinophilic esophagitis is a major underlying diagnosis; structural narrowing and motility disease also matter. When medically safe, obtain esophageal biopsies during the index evaluation/endoscopy when EoE is suspected rather than treating disimpaction as the complete diagnosis.

Senior synthesis — ask AIRWAY, OBJECT, LOCATION, SYMPTOMS, TIME, then REMOVE without creating a second injury."""
MANAGEMENT_ANSWER="""Application — stabilize airway/breathing and determine whether secretions can be handled. Identify the object and level, distinguish coin from button battery, remove complete obstruction/battery/sharp high-risk objects urgently, choose rigid versus flexible endoscopy according to level and expertise, stop rather than force resistance, inspect for mucosal injury/perforation, surveil significant battery injury for delayed vascular/TE-fistula complications, and evaluate food impaction for EoE/structural disease."""
COHORT={
 Q_REC:{"concept_id":CONCEPT_ID,"canonical_topic":TOPIC,"prompt":"A 3-year-old is brought to the ED after suddenly refusing food and drooling while playing with coins and a remote control. AP imaging shows a round upper-esophageal density, but the lateral film has not yet been reviewed. How should the otolaryngology resident distinguish coin from button battery, determine urgency, choose the removal strategy, and recognize the post-removal injuries that require continued surveillance?","answer_text":FOUNDATION_ANSWER,"explanation":"Esophageal foreign bodies are triaged by airway status, ability to handle secretions, object type, location and time since ingestion.","board_pearl":"Never label a round esophageal object a coin before excluding a button battery.","depth_layers_v207":{"foundation":"Cricopharyngeal anatomy and object recognition.","application":"Urgency and retrieval planning.","senior_decision":"Perforation and delayed injury rescue."}},
 Q_MGT:{"concept_id":CONCEPT_ID,"canonical_topic":TOPIC,"prompt":"A child has a proximal esophageal foreign body with drooling but stable oxygenation. Walk through management from imaging through safe extraction and post-procedure evaluation?","answer_text":MANAGEMENT_ANSWER,"explanation":"Remove the object on the correct timeline without converting impaction into perforation.","board_pearl":"Force against an embedded object is a perforation trap.","depth_layers_v207":{"foundation":"Symptoms, location and object identity define risk.","application":"Select imaging, timing and retrieval method.","senior_decision":"Escalate perforation/vascular injury and evaluate food impaction etiology."}},
}
TRAPS=["Do not miss a button battery.","Do not delay complete obstruction.","Mitigation never substitutes for battery removal.","Do not force an embedded object.","Battery injury can progress after removal.","Use type/location/symptoms/time together.","Recognize perforation after difficult extraction.","Evaluate recurrent food impaction for EoE."]
for _p in COHORT.values():
 _p["common_traps_v207"]=list(TRAPS); _p["deliberate_review_v207"]="High-consequence exact-canonical depth repair."; _p["source_refs_v207"]=SOURCE_REFS_V207

def apply_concept_check_task_alignment_v207(checks, deep_modules, v6_item_id):
 by={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
 for qid,p in COHORT.items():
  q=by.get(qid)
  if q is None: missing.append(qid); continue
  m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get('topic') or '') if m else ''; cid=v6_item_id(q.get('domain'),topic) if m and q.get('domain') else None
  if m is None or topic!=p['canonical_topic'] or cid!=p['concept_id'] or q.get('concept_id')!=cid: link_mismatch.append(qid); continue
  for field in ('prompt','answer_text','explanation','board_pearl','depth_layers_v207','common_traps_v207','deliberate_review_v207','source_refs_v207'): q[field]=p[field]
  q['task_alignment_v207']=True; repaired.append(qid)
 return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
