"""v20.11d focused depth patch for Laser / Energy Safety in Otolaryngology."""
from concept_check_board_repair_v177 import _find_module

QID="cc-v112-mgt-general-ent-emergencies-laser-energy-safety-in-otolaryngology"
CID="v6-general-ent-emergencies-laser-energy-safety-in-otolaryngology"
TOPIC="Laser / Energy Safety in Otolaryngology"

SOURCE_REFS_V211_LASER=[
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected ENT Boards Library; laser surgery, laryngeal/airway instrumentation, electrosurgery and operative-safety sections.","role":"foundation/operative: laser-tissue interaction, airway laser setup, eye/tissue protection, energy-related complications and rescue"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected ENT Boards Library; laser/airway procedure and operative-safety sections.","role":"board framework: airway-fire prevention, laser precautions and perioperative complication response"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected ENT Boards Library; laser surgery and airway/endoscopic operative-safety sections.","role":"board/operative cross-check: wavelength/tissue concepts, ocular protection, airway protection and complication management"},
 {"type":"guideline","citation":"AORN. Key Takeaways: Guideline for Laser Safety. Published 2024-09-09; current online guidance verified 2026-09-05.","role":"current perioperative management: laser time-out, fire-risk assessment and procedural laser-safety controls"},
 {"type":"guideline","citation":"AORN. Guideline for Surgical Smoke Safety and current Management of Surgical Smoke resources; current online guidance verified 2026-09-05.","role":"current plume management: source evacuation/filtration and programmatic smoke-safety controls"},
 {"type":"safety_guidance","citation":"Anesthesia Patient Safety Foundation. OR Fire Safety Video Commentary for the ENT Surgeon; current online resource verified 2026-09-05.","role":"ENT-specific fire prevention/rescue: minimize oxidizer concentration, avoid nitrous oxide during ignition risk, laser-resistant tube limitations, remove burning material and disconnect gas supply"},
]

PROMPT="""A patient is undergoing transoral laryngeal laser surgery near an endotracheal tube. The room is using supplemental oxygen, the surgeon plans repeated laser activation, and smoke plume is accumulating. How should the ENT surgeon choose and use laser/energy safely, protect the patient and team before activation, reduce airway-fire risk during the case, and respond immediately if an airway fire or unintended thermal injury occurs?"""

ANSWER="""Foundation — laser and energy safety is not a checklist detached from the operation; it is the interaction of wavelength, target tissue, power delivery, oxygen, fuel, and anatomy. Before activation, know which device is being used, what wavelength or energy modality it delivers, what tissue effect is intended, how deep or laterally the effect can extend, and which structures cannot tolerate that injury. Use the lowest effective power/energy and shortest effective activation, keep the target directly visible whenever possible, and stop when visualization, tissue identity, or device position is uncertain. A CO2 laser is strongly absorbed by water and is useful for precise superficial cutting/ablation, whereas other wavelengths and energy devices have different absorption and penetration characteristics; the board-level principle is to choose the tool for the desired tissue effect rather than assuming every laser or cautery behaves the same.

Eyes and exposed tissue — eye protection must match the laser wavelength; generic glasses are not interchangeable protection. Everyone in the room needs appropriate eyewear, and the patient's eyes require secure wavelength-appropriate protection appropriate to the procedure. Protect adjacent tissue from stray energy and reflection, keep reflective instruments out of the beam path when possible, use nonreflective/matted instruments when indicated, and place the laser in standby whenever it is not actively being fired. Confirm device settings and protection during a laser-specific time-out before activation.

Plume — laser and electrosurgical plume is an exposure hazard, not merely a visibility nuisance. Use effective smoke evacuation close to the source with appropriate filtration and keep the system functioning throughout plume-generating activation. Standard room ventilation or a routine suction line positioned far from the field is not a substitute for source capture. This is especially important during repeated mucosal ablation and procedures involving potentially infectious tissue.

Airway-fire model — think explicitly in the fire triad: ignition source, oxidizer, and fuel. In airway surgery the laser or electrosurgical device is the ignition source; oxygen and nitrous oxide enrich combustion; an endotracheal tube, cuff, pledget, sponge, drape, secretions or other material can become fuel. Before laser activation, surgeon and anesthesia should agree on the airway device, ventilation strategy, acceptable FiO2, whether an open airway technique is being used, rescue equipment, and the exact fire response. Reduce oxygen to the lowest concentration that safely supports the patient before ignition is introduced; avoid nitrous oxide when a fire-risk energy source is active. Do not activate the laser while oxygen concentration or gas pooling around the operative field is uncertain.

Airway tube protection — when an endotracheal tube is required for airway laser surgery, use a tube specifically designed and labeled as laser resistant for the wavelength/application rather than assuming a conventional tube wrapped improvisedly is safe. Laser-resistant does not mean laser-proof: cuffs and unprotected portions remain vulnerable, and protection is conditional on the device instructions. Saline-filled cuffs, often with visible dye when consistent with local practice/device guidance, and appropriately positioned wet pledgets can reduce consequences of an inadvertent hit; pledgets must remain wet and must be counted/retrieved. Keep the beam directed away from the tube and cuff and use the lowest effective settings.

Open-airway and oxygen trap — tubeless techniques can improve exposure but do not eliminate fire risk. Oxygen can pool in the pharynx or around drapes, and high-flow nasal oxygen can create an oxygen-enriched field near an ignition source. If laser or electrocautery will be used near supplemental oxygen, the team must deliberately control oxygen delivery and concentration rather than treating 'no tube' as 'no fuel/fire problem.' If clinically necessary oxygen cannot be reduced to an acceptably safe level, pause ignition-source use and change the technique rather than proceeding by habit.

Energy-device tissue safety — with monopolar/bipolar electrosurgery, coblation, ultrasonic devices, or laser, identify the structure at risk before activation and anticipate lateral thermal spread, depth of penetration, conductive heating and unintended contact. Activate only on the intended target, avoid prolonged stationary activation, and allow cooling/irrigation when needed. Around nerves, vessels, airway mucosa, implanted hardware, or thin tissue planes, a lower-energy, nonthermal, or alternative technique may be safer. Unexpected tissue charring, deep contraction, loss of anatomic discrimination, device malfunction, or a thermal effect extending beyond the intended target is a reason to stop and reassess—not a reason to simply increase power.

Immediate airway-fire rescue — if flame, flash, unexpected heat, smoke from the tube, or sudden airway-circuit fire is suspected, announce FIRE and act simultaneously. Stop the laser/energy source; stop/disconnect the oxidizing gas flow; remove the burning endotracheal tube and other burning material from the airway; extinguish residual fire with saline or water; then re-establish ventilation with safe gas and secure the airway as needed. Do not waste critical seconds debating whether the tube is truly burning while oxygen continues to feed the fire. After the fire is extinguished and ventilation restored, inspect the airway with bronchoscopy/endoscopy for retained debris and thermal injury and manage edema, inhalation injury, bronchospasm, or distal injury according to severity. Preserve removed material/equipment for investigation when feasible after the patient is safe.

Failure/rescue — after any unexpected laser or energy injury, reassess the actual anatomic consequence. Airway edema or mucosal burn may worsen after an initially stable appearance; eye exposure requires urgent ophthalmologic evaluation; deep thermal injury can evolve beyond the visible surface; and device-related tissue injury near a nerve or vessel may require observation, imaging, exploration, or repair depending on the structure and mechanism. Document the event, energy settings, location, immediate response, and post-event examination.

Senior synthesis — use five decisions. EFFECT: what tissue interaction and depth do I want from this wavelength/device? SHIELD: are eyes, adjacent tissue, personnel and plume controls appropriate before activation? FIRE: where are the ignition source, oxidizer and fuel, and have surgeon/anesthesia reduced avoidable components? CONTROL: can I see the target, use the lowest effective energy and stop immediately if the anatomy or effect becomes uncertain? RESCUE: does every team member know that an airway fire means stop energy and oxidizer, remove burning material/tube, extinguish, re-ventilate and inspect the airway? The dangerous alternatives are treating all lasers as equivalent, wearing non-wavelength-specific eyewear, accepting plume because suction is inconvenient, calling a tube 'laser proof,' using nitrous oxide or unnecessarily high FiO2 around ignition, firing through poor visualization, continuing after unintended thermal spread, and responding to airway fire without immediately removing the fuel and oxidizer."""

COHORT_LASER_V211={QID:{
 "concept_id":CID,"canonical_topic":TOPIC,"prompt":PROMPT,"answer_text":ANSWER,
 "explanation":"Laser/energy safety requires matching device effect to tissue, wavelength-specific eye protection, active plume evacuation, explicit fire-triad control, safe airway-device/oxygen planning, controlled activation and a rehearsed airway-fire rescue sequence.",
 "board_pearl":"Airway laser fire is a fire-triad problem: minimize oxidizer, control fuel and ignition. If fire occurs, stop energy and gas flow, remove the burning tube/material, extinguish, re-establish ventilation, then inspect the airway.",
 "depth_layers_v211":{"foundation":"Match wavelength/energy to intended tissue effect; protect eyes and adjacent tissue and evacuate plume at the source.","application":"Run a laser time-out, minimize oxidizers, use the appropriate laser-resistant airway strategy and activate only under direct target control.","senior_decision":"Recognize when oxygen/airway/device conditions make ignition unsafe, stop unintended thermal spread, execute immediate airway-fire rescue and evaluate downstream injury."},
 "common_traps_v211":[
  "Treating every laser wavelength as interchangeable and choosing settings without considering tissue absorption and penetration.",
  "Using generic protective glasses instead of wavelength-specific laser eye protection for staff and the patient.",
  "Allowing surgical plume to accumulate because it does not obscure the surgeon's view enough to seem urgent.",
  "Calling a laser-resistant endotracheal tube laser-proof and allowing the beam to contact its cuff or unprotected portions.",
  "Using unnecessarily high FiO2 or nitrous oxide while an ignition source is active in or near the airway.",
  "Assuming a tubeless or high-flow nasal oxygen technique eliminates airway-fire risk despite an oxygen-enriched operative field.",
  "Letting saline pledgets dry or failing to count and retrieve them after airway laser surgery.",
  "Firing the laser or electrosurgical device when the target, instrument tip, or adjacent critical anatomy is not clearly visible.",
  "Responding to unexpected deep thermal effect by increasing power or continuing activation instead of stopping and reassessing.",
  "During an airway fire, attempting to ventilate through the burning tube before stopping oxidizer flow, removing the fuel and extinguishing the fire."
 ],
 "deliberate_review_v211":"Expanded after the exact-head v20.11c residual-depth audit ranked Laser / Energy Safety in Otolaryngology first: the live reveal covered generic low-energy use and a brief fire response but omitted wavelength/tissue selection, wavelength-specific eye protection, plume evacuation, fire-triad prevention, laser-resistant tube limitations, oxidizer/nitrous-oxide control, tubeless/HFNO risk, activation discipline and post-fire airway assessment.",
 "source_refs_v211":SOURCE_REFS_V211_LASER,
}}

def apply_laser_energy_safety_v211(checks, deep_modules, v6_item_id):
 by={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
 for qid,p in COHORT_LASER_V211.items():
  q=by.get(qid)
  if q is None: missing.append(qid); continue
  m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get('topic') or '') if m else ''; cid=v6_item_id(q.get('domain'),topic) if m and q.get('domain') else None
  if m is None or topic!=p['canonical_topic'] or cid!=p['concept_id'] or q.get('concept_id')!=cid: link_mismatch.append(qid); continue
  for field in ('prompt','answer_text','explanation','board_pearl','depth_layers_v211','common_traps_v211','deliberate_review_v211','source_refs_v211'): q[field]=p[field]
  q['choices']=[]; q['answer']=None; q['task_alignment_v211']=True; repaired.append(qid)
 return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
