"""v20.11 — deepen exact live Concept Checks that remain shallow after the validated v20.10 production lineage.

Durable anatomy/operative principles are cross-checked against connected Cummings 7e, Pasha 6e,
and K.J. Lee 12e. Management-changing details use current specialty guidance where appropriate.
"""
from concept_check_board_repair_v177 import _find_module

SOURCE_REFS_V211 = [
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), Ch. 19, Facial Trauma: Soft Tissue Lacerations and Burns, pp. 269-285 (connected Drive split Part 1).","role":"foundation/operative: early functional examination, conservative tissue handling, eyelid/canalicular injury, facial nerve and parotid injury, layered landmark repair, facial burns"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), Ch. 10 Head and Neck Trauma, Soft Tissue Trauma and Burns of the Head and Neck, pp. 672-676 (connected Drive copy).","role":"foundation/management: local anesthesia caveats, wound management, special soft-tissue injuries, burn assessment"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), Part 7 Facial Plastic and Reconstructive Surgery, Chs. 54-58, especially craniomaxillofacial trauma and eyelid/lacrimal/auricular repair principles (connected Drive copy).","role":"operative cross-check: anatomic-unit repair, canalicular injury, auricular cartilage/perichondrium, facial trauma reconstruction"},
 {"type":"guideline","citation":"American Burn Association. Burn Patient Referral Guidelines, current online guidance verified 2026-09-04.","role":"current management: immediate consultation/consideration for transfer for deep partial/full-thickness facial burns and suspected inhalation injury; consultation for potentially deep burns"},
 {"type":"review","citation":"Braun TL, Maricevich RS. Management of Traumatic Soft Tissue Injuries of the Face. Semin Plast Surg. 2021;35(4):229-237. PMCID: PMC8604620.","role":"operative review: pre-anesthetic facial nerve examination, irrigation/hemostasis, conservative debridement, layered closure, facial nerve exploration/repair and parotid duct assessment"},
]

QID="cc-v112-rec-facial-plastics-trauma-facial-soft-tissue-lacerations-burns"
CID="v6-facial-plastics-trauma-facial-soft-tissue-lacerations-burns"
TOPIC="Facial Soft-Tissue Lacerations / Burns"
PROMPT="""A patient arrives after a complex cheek-and-lip laceration with possible parotid-region injury, while another patient has a deep facial thermal burn with soot around the mouth. Before focusing on cosmetic closure, how should you evaluate the wound for functional injuries, decide what requires immediate repair versus staged reconstruction, and distinguish a routine facial laceration from a burn that needs airway escalation or burn-center involvement?"""
ANSWER="""Foundation — treat facial soft-tissue trauma as a function-first problem before it is a scar problem. Complete trauma priorities and control hemorrhage, but do not let an apparently cosmetic wound hide an eye, lacrimal, facial nerve, parotid duct, mucosal, cartilage, dental/occlusal, or airway injury. Cummings specifically emphasizes documenting facial nerve function early and before wound exploration, anesthetic application, or repair because those interventions can obscure the original deficit. Test brow elevation, forceful eye closure, smile/oral commissure excursion, and lower-lip depression. Examine the globe and vision when the orbit is involved; inspect eyelid margins and the medial canthus for canalicular injury; examine nasal support/airway, oral mucosa, teeth and occlusion when relevant; and identify exposed auricular or nasal cartilage.

Wound preparation — after the neurologic and functional examination, obtain adequate anesthesia, achieve hemostasis, irrigate thoroughly, remove foreign material, and inspect the wound through its full depth. The face is highly vascular, so debridement should be conservative when viability is uncertain. Do not reflexively discard marginal or partially avulsed tissue that may survive. Crush and avulsion injuries may declare viability over time. The goal is to preserve tissue while avoiding closure over contamination, dead tissue, or an unrecognized deep injury.

Layered repair — rebuild anatomy from deep to superficial. Reapproximate mucosa when violated, restore muscle continuity, eliminate meaningful dead space, restore dermis, and use low-tension skin closure. The first key stitch belongs at the landmark whose mismatch would be most visible or functionally consequential: align the vermilion-cutaneous junction before completing a lip repair, precisely restore eyelid/free margins, and restore the helical rim or nasal margin without notching. Tissue loss is not solved by pulling the remaining face together under excessive tension; graft, local flap, regional flap, or staged reconstruction may be safer when a true defect exists.

Facial nerve — a sharp traumatic transection in a repairable facial nerve branch should be recognized early and repaired primarily when feasible. Early exploration is valuable because distal stimulation becomes unreliable after Wallerian degeneration. If immediate neurorrhaphy cannot be performed, identify/tag nerve ends and make the reconstruction plan rather than allowing them to disappear into scar. Distal midfacial branches have variable redundancy, so management depends on branch level and observed deficit rather than an automatic rule that every tiny distal branch requires exploration. The board and OR trap is documenting facial movement only after local anesthetic or wound manipulation and then being unable to distinguish traumatic from iatrogenic weakness.

Parotid duct/gland — suspect Stensen duct injury when a laceration crosses the parotid-masseter region. The duct papilla is opposite the maxillary second molar and can be cannulated to assess continuity; gland massage may reveal saliva in the wound. A clear repairable transection is generally repaired primarily over a stent. Buccal facial nerve weakness plus a cheek wound should increase suspicion because the nerve branches and duct travel close together. Missed injuries can present with salivary fistula or sialocele and require reassessment rather than repeated superficial drainage alone.

Special structures — medial eyelid/canthal lacerations require deliberate canalicular evaluation; full-thickness eyelid injury requires exact tarsal and margin alignment. Exposed auricular cartilage needs viable soft-tissue/perichondrial coverage and contour restoration. Nasal wounds should restore lining, support, and skin rather than accepting exposed cartilage or free-margin distortion. Through-and-through lip wounds require layered mucosa, orbicularis, and skin repair. These injuries deserve specialist escalation when the required structure cannot be confidently identified or repaired.

Contamination and antibiotics — irrigation, foreign-body removal, and appropriate debridement are more important than reflex antibiotics for every clean facial laceration. Antibiotic decisions should be selective and individualized for bites, gross contamination, oral cavity communication, open fracture/cartilage concerns, immunocompromise, or established infection. Update tetanus prophylaxis when indicated. A delayed presentation is not automatically a reason to leave every facial wound open; judge contamination, infection, tissue viability, and whether safe repair can still be achieved.

Burn distinction — facial burns require a different first decision: airway and burn depth before reconstruction. Stop the burning process, assess burn extent/depth, and look specifically for inhalation injury. Facial flash burns, singed hairs, soot, hoarseness, stridor, respiratory distress, enclosed-space smoke exposure, or progressive edema should raise concern. A currently adequate airway can deteriorate as edema evolves, so early airway escalation is safer than waiting for a difficult late intubation in a high-risk patient. Do not intubate solely because the face is burned, but do not dismiss evolving airway findings because the initial oxygen saturation is normal.

Current-guidance distinction — the textbooks provide durable wound, anatomy, nerve/duct, and reconstruction principles. Disposition should follow current ABA referral guidance rather than older blanket rules: deep partial-thickness or full-thickness burns involving the face warrant immediate burn-center consultation with consideration for transfer, as does suspected inhalation injury; potentially deep burns warrant consultation. Facial location matters because eyelid, lip, nose, and ear injuries are functional/aesthetic units prone to contracture, and airway injury may coexist.

Failure/rescue — worsening pain, erythema, purulence, salivary swelling with meals, new facial weakness, dehiscence, exposed cartilage, ectropion, free-margin notching, or contour distortion should trigger re-examination for a missed deep injury or failed reconstruction rather than cosmetic reassurance. After burns, progressive hoarseness, stridor, respiratory effort, hypoxemia, or rapidly worsening edema demands urgent airway reassessment.

Senior synthesis — use five checks: FUNCTION asks which nerve, eye/lacrimal, salivary, cartilage, mucosal, dental, or airway structures are threatened; CLEAN asks whether contamination and nonviable tissue were addressed without over-debriding viable face; ALIGN asks which landmark must be restored first and which layers remove tension; REPAIR asks which deep structure requires immediate repair or deliberate staged reconstruction before skin closure; BURN asks whether depth, facial location, or inhalation risk changes airway planning and disposition. The dangerous errors are examining facial nerve function only after anesthetic, closing a cheek wound over an unrecognized nerve/duct injury, aggressively discarding potentially viable facial tissue, forcing a true defect closed under tension, and treating a deep facial burn as merely a skin wound while airway edema evolves."""
COHORT={QID:{
 "concept_id":CID,"canonical_topic":TOPIC,"prompt":PROMPT,"answer_text":ANSWER,
 "explanation":"Facial soft-tissue trauma is a functional-anatomy problem before it is a scar problem: document nerve/eye/lacrimal/salivary/cartilage/airway status before anesthetic or closure, preserve viable tissue, restore landmarks with layered low-tension repair, repair deep injuries before skin, and apply current burn-airway/referral guidance.",
 "board_pearl":"Before local anesthetic, document facial nerve function. Before closing a cheek wound, exclude facial nerve and Stensen duct injury. Before treating a facial burn as a wound, decide whether inhalation injury or burn depth changes the airway and disposition.",
 "depth_layers_v211":{"foundation":"Function-first facial examination, conservative tissue preservation, irrigation and precise layered landmark repair.","application":"Recognize and manage facial nerve, parotid duct, eyelid/canalicular, lip, nasal and auricular injuries before superficial closure.","senior_decision":"Choose primary versus staged reconstruction, selectively use antibiotics, recognize failed repair, and escalate deep facial burns/suspected inhalation injury using current burn-center guidance."},
 "common_traps_v211":["Injecting local anesthetic before documenting facial nerve function and losing the baseline neurologic examination.","Closing a cheek laceration without checking the course and function of Stensen duct and nearby facial nerve branches.","Aggressively debriding marginal facial tissue that might survive because of the face's robust vascularity.","Using skin sutures to pull a deep wound together instead of restoring muscle/dermal layers and eliminating tension or dead space.","Missing the vermilion border, eyelid margin, helical rim, or nasal free margin and assuming later scar maturation will correct the distortion.","Closing skin over a recognized nerve, duct, or canalicular transection without repairing it or making an explicit staged plan.","Giving antibiotics to every clean facial laceration while underemphasizing irrigation, foreign-body removal, and selective prophylaxis.","Assuming every facial burn requires prophylactic intubation rather than integrating inhalation-risk findings and evolution.","Waiting for overt airway obstruction despite soot, hoarseness, enclosed-space exposure, or progressive edema.","Treating deep partial/full-thickness facial burns as routine outpatient wounds instead of using current burn-center referral thresholds."],
 "deliberate_review_v211":"Preserved from the stale pre-PTA facial-trauma branch and rehomed onto exact-head-green v20.10 main. The prior live reveal was shallow and omitted pre-anesthetic facial nerve documentation, parotid duct/canalicular injury, landmark-first layered repair, conservative tissue preservation, failed-repair rescue, inhalation-airway reasoning, and current burn-center referral thresholds.","source_refs_v211":SOURCE_REFS_V211,
}}

MICROTIA_QID="cc-v112-mgt-pediatric-otolaryngology-microtia-reconstruction"
MICROTIA_CID="v6-pediatric-otolaryngology-microtia-reconstruction"
MICROTIA_TOPIC="Microtia Reconstruction"
MICROTIA_REFS_V211=[
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), congenital external-ear/microtia and aural-atresia reconstruction sections (connected ENT Boards Library copy).","role":"foundation/operative: auricular development, microtia classification, reconstructive planning, hearing/atresia coordination"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), congenital ear anomalies/microtia and aural-atresia sections (connected ENT Boards Library copy).","role":"board framework: congenital ear evaluation, hearing assessment, reconstruction options and sequencing"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), congenital external-ear deformity/microtia-atresia and auricular reconstruction sections (connected ENT Boards Library copy).","role":"board/operative cross-check: microtia-atresia association, auricular growth, reconstruction timing and anatomy"},
 {"type":"consensus","citation":"Zhang TY et al. International Consensus Recommendations on Microtia, Aural Atresia and Functional Ear Reconstruction. J Int Adv Otol. 2019;15(2):204-208. PMID 31418720.","role":"multidisciplinary management, hearing rehabilitation, reconstruction/atresia sequencing"},
 {"type":"review","citation":"Integrated microtia and aural atresia management. Front Surg. 2022;9:944223.","role":"current integrated timing of hearing diagnostics/rehabilitation, autologous versus porous-polyethylene reconstruction, and atresia repair"},
 {"type":"systematic_review","citation":"Kim YJ, Min K, Kim YS. Auricle reconstruction with autologous costal cartilage versus polyethylene implants in microtia patients: a meta-analysis. Arch Craniofac Surg. 2024;25(4):179-186.","role":"current outcomes/tradeoffs between autologous cartilage and porous polyethylene"},
]
MICROTIA_PROMPT="""A 7-year-old with grade III unilateral microtia and congenital aural atresia has normal hearing in the opposite ear. The family asks whether the child should first undergo canal surgery, rib-cartilage auricular reconstruction, porous-polyethylene reconstruction, or simply wait. How do you build a coordinated microtia plan that addresses hearing first, chooses the reconstructive pathway and timing appropriately, and avoids sequencing one operation in a way that compromises the next?"""
MICROTIA_ANSWER="""Foundation — microtia is not only a cosmetic pinna problem. Begin with a complete craniofacial and otologic assessment: characterize the microtia grade and lobule/skin remnant, examine facial symmetry and syndromic features, document the contralateral ear, and establish hearing status early. Microtia and congenital aural atresia frequently coexist, so every child needs age-appropriate audiologic evaluation rather than assuming unilateral disease is functionally irrelevant. Bilateral conductive loss requires prompt hearing rehabilitation; unilateral atresia still deserves counseling about localization, hearing in noise, classroom function, and options for bone-conduction support.

Hearing comes before the decorative framework — reconstruction of the auricle does not restore hearing. Infants and young children with bilateral atresia generally need early bone-conduction hearing access, initially with a non-surgical band/adhesive system when appropriate. Surgically implanted bone-conduction systems, active transcutaneous systems, or atresiaplasty are later options chosen according to age, anatomy, hearing goals, skin/soft tissue, and the planned auricular reconstruction. In unilateral cases, the urgency is different, but hearing surveillance and functional counseling still belong in the plan.

Define anatomy before promising canal surgery — high-resolution temporal-bone CT is not a newborn screening test for every microtia patient. It is obtained when the child is old enough and when the result will change candidacy/planning for atresia repair or another intervention. Atresiaplasty candidacy depends on favorable middle-ear anatomy, including ossicular and facial-nerve relationships, aeration and overall Jahrsdoerfer-type anatomy; a poor candidate should not be sent for canal surgery simply because an external canal is absent.

Choose the auricular pathway deliberately. Autologous costal-cartilage reconstruction uses the child's own rib to carve a three-dimensional framework. Its advantages are durable living autologous tissue and long-term integration; disadvantages include donor-site morbidity, the need for adequate rib cartilage, technically demanding framework carving, and usually staged surgery. Timing is therefore tied to chest/cartilage development and technique: classic autologous reconstruction is commonly performed in school-age children, often roughly 6-10 years depending on the chosen Brent/Nagata-type technique and surgeon preference rather than a single mandatory birthday.

Porous-polyethylene reconstruction can often be performed younger and avoids rib harvest. It provides a prefabricated framework with strong definition, but it is an alloplastic implant that depends on durable vascularized soft-tissue coverage and carries different failure modes — exposure, infection, trauma vulnerability and possible implant loss. The family should hear those tradeoffs explicitly instead of being told that one material is universally superior. Modern comparative literature does not support reducing the decision to a cosmetic-score contest; complications, number of operations, donor morbidity, soft-tissue quality, age, surgeon expertise and family preference all matter.

Sequence reconstruction with atresia surgery before either surgeon operates. This is a classic board and real-world trap. Canal surgery changes postauricular skin and vascularity and can alter the tissue needed for auricular reconstruction. With autologous costal-cartilage reconstruction, atresiaplasty is generally coordinated after the auricular framework stages so the microtia surgeon can preserve the skin envelope and place the ear correctly. With porous-polyethylene reconstruction, the sequence may differ: experienced integrated teams may perform atresia repair before or concurrently with alloplastic auricular reconstruction because the vascularized fascial coverage and incision planning are different. The exact sequence therefore follows the reconstructive method and the coordinated microtia-atresia team, not a generic rule that canalplasty always comes first.

Plan the ear in three dimensions. Use the normal contralateral auricle when available to guide height, projection, axis and landmark relationships, while accounting for craniofacial asymmetry. Assess whether the vestigial lobule and local skin can be incorporated, whether the hairline is low, and whether scars or prior surgery threaten the skin pocket or temporoparietal fascial blood supply. Autologous reconstruction requires enough healthy skin for a tension-free pocket and enough donor cartilage for framework definition; alloplastic reconstruction requires reliable vascularized coverage. A beautiful framework under ischemic or scarred soft tissue is a setup for exposure.

Senior decision — distinguish four linked decisions rather than collapsing them into one operation. HEARING: what does the child need now to access sound? ANATOMY: is atresiaplasty anatomically reasonable, and when should CT be obtained? AURICLE: autologous cartilage, porous polyethylene, prosthesis, or no reconstruction based on age, tissues, donor site, risk tolerance and goals? SEQUENCE: which operation must occur first so canal work does not compromise the auricular skin/vascular plan? Multidisciplinary planning is especially important in craniofacial microsomia, bilateral disease, prior surgery, low hairline, poor soft tissue or unusual facial-nerve anatomy.

Failure/rescue — early swelling, skin compromise, framework exposure, infection, hematoma or loss of projection requires prompt reconstructive assessment because delayed management can convert a salvageable soft-tissue problem into framework loss. After autologous harvest, monitor donor-site pain, pneumothorax risk and chest-wall contour; contemporary systematic review data reinforce that donor-site deformity is real and technique-dependent, so rib harvest should be meticulous and perichondrial preservation matters. Long-term follow-up should evaluate symmetry, projection, scar, framework integrity and hearing—not appearance alone.

The dangerous alternatives are reconstructing the pinna while ignoring hearing, ordering CT before it will change management, promising atresiaplasty without favorable anatomy, performing canal surgery without coordinating the planned auricular technique, treating porous polyethylene as a complication-free shortcut, or delaying every child until one arbitrary age despite different reconstructive methods and hearing needs."""
COHORT[MICROTIA_QID]={
 "concept_id":MICROTIA_CID,"canonical_topic":MICROTIA_TOPIC,"prompt":MICROTIA_PROMPT,"answer_text":MICROTIA_ANSWER,
 "explanation":"Microtia care is integrated hearing and reconstruction planning: establish hearing needs early, select auricular material/timing by anatomy and goals, and coordinate atresia surgery with the reconstructive method so one operation does not compromise another.",
 "board_pearl":"Microtia reconstruction does not restore hearing. Decide hearing rehabilitation first, then auricular method, then coordinate atresiaplasty timing with that method—especially because canal surgery can compromise tissue needed for later reconstruction.",
 "depth_layers_v211":{"foundation":"Microtia grade, craniofacial/contralateral-ear assessment and early audiology; distinguish auricular reconstruction from hearing rehabilitation.","application":"Compare autologous rib cartilage, porous polyethylene, prosthetic/no reconstruction and atresiaplasty candidacy/timing.","senior_decision":"Coordinate hearing device, CT/atresia decision and auricular reconstruction sequence while protecting skin envelope, vascularized coverage and donor-site safety."},
 "common_traps_v211":["Treating microtia as purely cosmetic and failing to establish hearing status early.","Assuming unilateral atresia needs no functional hearing counseling or surveillance.","Ordering temporal-bone CT in infancy before the result would change management or operative planning.","Offering atresiaplasty without confirming favorable middle-ear and facial-nerve anatomy.","Performing canal surgery first without coordinating how the incision and postauricular scar affect the planned auricular reconstruction.","Teaching one fixed age for all microtia reconstruction despite technique-dependent cartilage and soft-tissue requirements.","Presenting porous polyethylene as a simple rib-free equivalent without discussing exposure, infection and implant-loss risk.","Presenting autologous cartilage as risk-free while ignoring chest donor-site morbidity and staged reconstruction.","Designing framework position without accounting for craniofacial asymmetry, contralateral landmarks, lobule remnant and hairline.","Judging success by pinna appearance alone while neglecting hearing, projection, scar, framework integrity and family goals."],
 "deliberate_review_v211":"Expanded after the validated v20.11 residual-depth audit identified Microtia Reconstruction as the highest-ranked remaining shallow live Concept Check (19-word reveal). The replacement separates hearing rehabilitation from auricular reconstruction, adds atresiaplasty candidacy/sequencing, autologous-versus-alloplastic tradeoffs, donor/soft-tissue risks and multidisciplinary planning.","source_refs_v211":MICROTIA_REFS_V211,
}

TB_QID="cc-v112-rec-laryngology-voice-swallowing-tracheobronchial-endoscopy-principles"
TB_CID="v6-laryngology-voice-swallowing-tracheobronchial-endoscopy-principles"
TB_TOPIC="Tracheobronchial Endoscopy Principles"
TB_REFS_V211=[
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), pediatric airway/anesthesia and tracheobronchial foreign-body sections (connected ENT Boards Library Part 6).","role":"foundation/operative: shared-airway planning, spontaneous-versus-controlled ventilation tradeoffs, foreign-body airway rescue and perioperative complications"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), Ch. 2 Upper Airway Obstruction pp. 84-87 and Ch. 9 pediatric airway foreign body p. 575 (connected ENT Boards Library copy).","role":"board framework: flexible bronchoscopy for diagnosis/location and rigid bronchoscopy for instrumentation/emergency airway management"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), Ch. 50 pp. 910-911 and Ch. 53 pp. 1007-1008 (connected ENT Boards Library copy).","role":"operative cross-check: foreign-body presentation, rigid ventilation bronchoscopy, retrieval technique, sharp-object protection, second-look and complications"},
 {"type":"current_review","citation":"Brown MC et al. Airway Foreign Bodies. Otolaryngol Clin North Am. 2026. PMID: 42135119.","role":"current management: rigid bronchoscopy remains reference treatment for high-suspicion pediatric aspiration while CT can help low/intermediate-suspicion patients"},
 {"type":"systematic_review","citation":"CT Scan in Children Suspected of Foreign Body Aspiration: A Systematic Review and Meta-analysis. Otolaryngol Head Neck Surg. 2023. PMID: 37473440.","role":"current diagnostic update: high CT sensitivity/specificity and role in reducing negative rigid bronchoscopies without replacing bronchoscopy when history/symptoms are convincing"},
 {"type":"systematic_review","citation":"Safia A et al. Flexible versus Rigid Bronchoscopy for Tracheobronchial Foreign Body Removal in Children: A Comparative Systematic Review and Meta-Analysis. J Clin Med. 2024;13(18):5652. PMID: 39337140.","role":"current procedural nuance: selected flexible extraction is feasible, but modality should be chosen by location, stability, operator expertise and rigid rescue capability"},
]
TB_PROMPT="""A toddler has a witnessed choking episode followed by unilateral wheeze and air trapping, while a second stable child has a less convincing history and equivocal radiographs. As the resident preparing for tracheobronchial endoscopy, how do you decide when imaging should stop and bronchoscopy should begin, choose rigid versus flexible instrumentation, coordinate the shared airway and ventilation plan, remove a foreign body without converting partial obstruction into complete obstruction, and rescue hypoxemia, bleeding, migration, or perforation?"""
TB_ANSWER="""Foundation — tracheobronchial endoscopy is not simply “look down the airway.” First define the physiologic threat, the diagnostic probability, and the intervention you may need. A child with a classic choking event plus focal wheeze, asymmetric breath sounds, unilateral air trapping, persistent cough, or unexplained recurrent pneumonia may have an airway foreign body even when the chest radiograph is normal because many aspirated objects are radiolucent. An unstable child or a child with high clinical suspicion should not be sent through serial tests that delay definitive airway control. In contrast, a stable low- or intermediate-suspicion child can sometimes be risk-stratified further before exposing them to general anesthesia and rigid bronchoscopy.

Choose the scope by task, not habit. Flexible bronchoscopy is excellent for diagnostic survey, dynamic airway assessment, distal or segmental bronchi, suction/BAL, and selected foreign-body extraction in experienced hands. Its smaller working channel and limited ability to control a suddenly obstructed central airway are important limitations. Rigid bronchoscopy provides a ventilating airway, a larger working channel, simultaneous telescope and instrument access, stronger graspers, the ability to tamponade some airway bleeding, and immediate access for central foreign-body extraction. For a high-suspicion pediatric central airway foreign body, rigid bronchoscopy remains the reference/default treatment platform. Modern flexible technology, however, means “rigid for every object under every circumstance” is also too absolute: distal objects and selected stable cases may be approached flexibly when an experienced team has appropriate retrieval devices and immediate rigid rescue capability.

Imaging is probability-dependent. A normal chest radiograph does not exclude aspiration. In a child with convincing history and focal findings, bronchoscopy remains appropriate despite a negative film. Do not obtain CT merely to prove what you already need to treat, and never delay bronchoscopy in an unstable airway. The management-changing update from newer evidence is that older blanket caution against CT is now too rigid: in stable low/intermediate-suspicion children, modern low-dose or ultra-low-dose CT can identify an airway foreign body with high diagnostic performance and reduce unnecessary negative rigid bronchoscopies. CT is therefore a selective rule-in/rule-out tool, not a substitute for bronchoscopy in the high-suspicion child.

Shared-airway preparation — before induction, surgeon and anesthesiologist explicitly agree on the likely object and location, rigid and flexible equipment, bronchoscope size, telescope, suction, optical forceps/graspers/baskets, backup airway devices, ventilation strategy, and rescue plan. Spontaneous ventilation versus controlled positive-pressure ventilation is not a universal rule. Cummings emphasizes that this choice is controversial and must reflect the object's position, degree of obstruction, anesthetic conditions, operator needs, and the ability to rescue. Spontaneous ventilation can reduce concern for forcing a mobile object distally, while controlled ventilation may provide more predictable gas exchange and operating conditions in selected patients. The dangerous approach is dogmatically insisting on one mode without a plan for apnea, hypercarbia, hypoxemia, bronchospasm, laryngospasm, or sudden complete obstruction.

Endoscopic survey — protect teeth and lips, expose the larynx, pass the glottis under direct visualization, and know what must be inspected: subglottis, trachea, carina, both main bronchi, and more distal branches as indicated. Describe lesion/foreign-body location, degree of obstruction, mucosal edema, granulation, secretions, bleeding, dynamic collapse, and relationship to the carina or lobar takeoffs. Flexible bronchoscopy is particularly helpful when distal anatomy or dynamic malacia is the question; rigid bronchoscopy becomes more valuable when the goal includes airway control, dilation, removal, or management of a central emergency.

Foreign-body retrieval — keep the object under visualization and choose the instrument for its material and shape. Do not perform a blind sweep and do not repeatedly poke a partially obstructing object distally. Organic material such as nuts can swell, fragment, and inflame the airway; smooth objects need a secure grasp before withdrawal. Sharp objects should be oriented so the sharp edge is protected within or against the bronchoscope rather than dragged exposed across the trachea and vocal folds. When feasible, bring the foreign body securely to the bronchoscope tip and withdraw it under controlled vision; some objects require removal en bloc with the scope because they cannot safely pass through the lumen.

Oxygenation outranks persistence. If saturation falls or ventilation deteriorates during repeated attempts, stop the extraction attempt, restore ventilation and oxygenation, then reassess instrument choice and strategy. A foreign body that becomes lodged at the glottis can create complete obstruction; classic rescue teaching is that it may be necessary to push it back distally temporarily to re-establish ventilation, then regroup for controlled removal. That is a rescue maneuver, not a routine retrieval technique. Large impacted objects rarely require tracheotomy or open/thoracic assistance, and the team should recognize when repeated endoscopic attempts are making the situation less safe.

Second look — successful extraction is not the end of bronchoscopy. Re-inspect the involved bronchus, distal airway when feasible, trachea, and contralateral tree for fragments or a second object; suction purulence and secretions as needed; assess mucosal trauma, bleeding, edema, granulation, or residual obstruction. Failure to perform this second look is how a technically successful extraction becomes persistent postoperative cough, pneumonia, or a missed fragment.

Complications and rescue — anticipate hypoxemia, hypercarbia, laryngospasm, bronchospasm, airway edema/stridor, bleeding, dental or mucosal trauma, foreign-body migration, pneumothorax, pneumomediastinum, and airway perforation. Sudden inability to ventilate means stop instrumentation and restore an airway before continuing. Significant bleeding may require rigid-scope tamponade, suction and controlled visualization rather than blind grasping. New subcutaneous emphysema, unilateral loss of breath sounds, hemodynamic deterioration, or concern for perforation should stop routine endoscopy and trigger evaluation for pneumothorax/pneumomediastinum, chest decompression when clinically indicated, and thoracic/ICU escalation.

Senior synthesis — use four decisions. SUSPICION: is this high enough that imaging would only delay treatment, or low/intermediate enough that low-dose CT can prevent a negative anesthetic/endoscopy? SCOPE: do you need diagnostic distal access or robust central airway control/intervention? SHARED AIRWAY: what ventilation strategy, equipment, and rescue plan have surgeon and anesthesia agreed on before the first pass? SECURE + SECOND LOOK: can you remove the object without pushing it distally or injuring the glottis, then prove no fragment, second object, bleeding, edema, or perforation remains? The dangerous alternatives are trusting a normal radiograph, obtaining CT in a high-suspicion unstable child, treating flexible and rigid scopes as interchangeable, enforcing spontaneous ventilation as dogma, blindly pushing an object distally, dragging a sharp object exposed across the vocal folds, persisting through hypoxemia, and ending the case without re-inspection."""
COHORT[TB_QID]={
 "concept_id":TB_CID,"canonical_topic":TB_TOPIC,"prompt":TB_PROMPT,"answer_text":TB_ANSWER,
 "explanation":"Tracheobronchial endoscopy requires probability-based diagnostic escalation, task-based scope selection, explicit shared-airway planning, controlled foreign-body retrieval, and a mandatory second look with immediate rescue of hypoxemia, migration, bleeding or perforation.",
 "board_pearl":"A normal chest radiograph does not exclude aspiration. High suspicion goes to bronchoscopy; stable low/intermediate suspicion may benefit from low-dose CT. Rigid is the reference platform for central pediatric foreign-body control, but flexible bronchoscopy has an important diagnostic/distal and selected therapeutic role.",
 "depth_layers_v211":{"foundation":"Match clinical suspicion and airway stability to imaging versus bronchoscopy; distinguish rigid airway-control advantages from flexible distal diagnostic access.","application":"Plan the shared airway, select scope/instruments by object and location, retrieve under vision, protect sharp edges and complete a second-look bronchoscopy.","senior_decision":"Individualize ventilation, stop attempts to restore oxygenation, manage migration/bleeding, and escalate pneumothorax, perforation or failed endoscopic retrieval rather than persisting blindly."},
 "common_traps_v211":["Treating a normal chest radiograph as proof that no airway foreign body is present.","Sending an unstable or high-suspicion child to CT when bronchoscopy is already indicated.","Treating flexible and rigid bronchoscopy as interchangeable despite different airway-control and working-channel capabilities.","Teaching rigid bronchoscopy as the only legitimate modern tool and ignoring selected distal flexible diagnosis/extraction in experienced teams with rigid rescue available.","Mandating spontaneous ventilation for every case instead of making an explicit shared-airway plan with anesthesia.","Blindly sweeping or repeatedly probing a partially obstructing object and pushing it farther distally.","Dragging a sharp foreign body exposed across the trachea or vocal folds instead of shielding/orienting the sharp edge.","Continuing repeated retrieval attempts while the child is desaturating instead of stopping to restore ventilation and oxygenation.","Ending the case immediately after extraction without a second look for fragments, a second object, bleeding, edema or distal disease.","Ignoring new loss of breath sounds, subcutaneous emphysema or hemodynamic change that may represent pneumothorax or airway perforation."],
 "deliberate_review_v211":"Expanded after the validated v20.11b residual-depth audit identified Tracheobronchial Endoscopy Principles as the highest-priority remaining exact-live Concept Check (19-word reveal). The replacement adds probability-based CT-versus-OR decisions, rigid-versus-flexible distinctions, shared-airway/ventilation reasoning, retrieval choreography, second-look requirements and complication rescue.",
 "source_refs_v211":TB_REFS_V211,
}


def apply_concept_check_task_alignment_v211(checks, deep_modules, v6_item_id):
 by={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
 for qid,p in COHORT.items():
  q=by.get(qid)
  if q is None: missing.append(qid); continue
  m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get('topic') or '') if m else ''; cid=v6_item_id(q.get('domain'),topic) if m and q.get('domain') else None
  if m is None or topic!=p['canonical_topic'] or cid!=p['concept_id'] or q.get('concept_id')!=cid: link_mismatch.append(qid); continue
  for field in ('prompt','answer_text','explanation','board_pearl','depth_layers_v211','common_traps_v211','deliberate_review_v211','source_refs_v211'): q[field]=p[field]
  q['choices']=[]; q['answer']=None; q['task_alignment_v211']=True; repaired.append(qid)
 return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
