"""v18.7 — next highest-priority live-canonical Concept Check depth cohort.

Selected deterministically from the validated V186 backlog. Exact canonical
resolution is required before mutation. This cohort focuses on sleep-surgery
selection and high-risk laryngology/oncology decisions rather than recall.
"""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-sleep-surgery-oral-appliance-therapy":{
"concept_id":"v6-sleep-surgery-oral-appliance-therapy","canonical_topic":"Oral Appliance Therapy",
"prompt":"A 52-year-old with symptomatic mild-to-moderate obstructive sleep apnea cannot tolerate PAP despite optimization and asks for a mandibular advancement device. He has adequate dentition, no major TMJ limitation, and no known central apnea or hypoventilation. How should you select and titrate oral-appliance therapy, verify efficacy, and decide when residual disease requires a different strategy rather than more protrusion?",
"answer_text":"Oral-appliance therapy is most appropriate when the phenotype is obstructive and the patient has anatomy and dentition that can tolerate mandibular advancement. I would use a custom titratable mandibular advancement device, establish baseline dental/TMJ status, and advance gradually to balance airway benefit with comfort. Counsel about jaw discomfort, salivation or dry mouth, tooth movement, occlusal change, and TMJ symptoms. Symptoms alone are not enough to prove control; obtain objective follow-up sleep testing after titration because residual AHI, oxygen burden, or positional disease may persist despite subjective improvement. If clinically important OSA remains despite maximal tolerable advancement, do not keep increasing protrusion indefinitely. Reassess adherence, weight, nasal obstruction, sleep position, and the original sleep-study phenotype, then compare PAP re-engagement, positional therapy, hypoglossal-nerve stimulation, soft-tissue surgery, skeletal surgery, or combination therapy as appropriate. Severe hypoxemia, substantial central apnea, hypoventilation, or major cardiopulmonary disease should trigger broader sleep-medicine evaluation rather than assuming a dental device alone addresses the physiology.",
"explanation":"The key decision is not simply whether a device can be prescribed, but whether it meaningfully controls obstructive physiology without unacceptable dental or TMJ morbidity.",
"board_pearl":"A mandibular advancement device is a titratable treatment that still requires objective efficacy testing; comfort and cure are not synonyms.",
"depth_layers_v187":{"foundation":"Know candidacy, mechanism, and major dental/TMJ adverse effects.","application":"Titrate a custom device and verify response with objective sleep testing.","senior_decision":"Abandon endless protrusion when residual disease persists and re-phenotype the patient for a different or combined therapy."},
"common_traps_v187":["Calling treatment successful because snoring improved can miss persistent desaturation and residual OSA.","Escalating mandibular advancement past tolerability treats the number rather than the patient and can create durable dental or TMJ morbidity."],
"deliberate_review_v187":"Expanded a short treatment summary into candidacy, titration, objective verification, adverse-effect surveillance, and failure-pathway decision making."},
"cc-v112-rec-head-neck-oncology-laryngeal-preservation-decision":{
"concept_id":"v6-head-neck-oncology-laryngeal-preservation-decision","canonical_topic":"Laryngeal Preservation Decision",
"prompt":"A 64-year-old with advanced laryngeal squamous cell carcinoma has a technically resectable tumor but severe pretreatment aspiration, poor pulmonary reserve, weight loss, and a largely nonfunctional larynx. How should you decide between nonsurgical organ preservation and total laryngectomy, and which pretreatment findings should outweigh the desire to preserve the anatomic larynx?",
"answer_text":"Laryngeal preservation should mean preservation of useful laryngeal function, not simply avoidance of laryngectomy. I would define tumor extent with endoscopy and contrast imaging, assess vocal-fold mobility, cartilage and extralaryngeal invasion, and obtain tissue diagnosis and appropriate chest/distant staging. Just as important, document baseline airway, swallowing and aspiration, pulmonary reserve, nutrition, performance status, renal function and hearing if cisplatin is being considered, and the patient's ability to complete radiation and systemic therapy. A patient can be anatomically eligible for organ-preservation therapy yet be a poor functional candidate if the larynx is already severely dysfunctional, aspiration is clinically important, airway protection is poor, pulmonary reserve is limited, or treatment completion is doubtful. Major cartilage destruction or extensive extralaryngeal disease may also favor surgery depending on stage and resectability. Total laryngectomy can provide superior functional separation of airway and alimentary tract in selected patients with a nonfunctional larynx. Conversely, a functional larynx with appropriate disease burden and adequate reserve may justify nonsurgical preservation. The senior decision explicitly weighs oncologic control, baseline function, treatment toxicity, salvage options, and patient priorities rather than treating 'organ preservation' as an automatic endpoint.",
"explanation":"Keeping the larynx anatomically is not a victory if the patient is left with unsafe swallowing, repeated aspiration, airway compromise, or poor oncologic control.",
"board_pearl":"The correct preservation question is: can this patient keep a functional larynx with acceptable cancer control?",
"depth_layers_v187":{"foundation":"Separate anatomic preservation from functional preservation.","application":"Integrate staging with baseline airway, swallow, pulmonary, nutritional, renal, hearing, and performance status.","senior_decision":"Favor laryngectomy when pretreatment laryngeal function is already poor or preservation therapy is unlikely to yield a safe, functional organ."},
"common_traps_v187":["Equating any anatomically intact larynx with treatment success ignores aspiration, tracheostomy dependence, and severe dysphagia.","Using tumor stage alone to choose chemoradiation misses patients whose baseline function and reserve make preservation a poor physiologic strategy."],
"deliberate_review_v187":"Converted a staging-heavy answer into a functional organ-preservation decision framework with explicit pretreatment failure signals."},
"cc-v112-mgt-laryngology-voice-swallowing-subglottic-tracheal-stenosis":{
"concept_id":"v6-laryngology-voice-swallowing-subglottic-tracheal-stenosis","canonical_topic":"Subglottic / Tracheal Stenosis",
"prompt":"A 41-year-old with progressive exertional dyspnea and biphasic noise has a short-segment subglottic stenosis after prior intubation. She has already undergone several endoscopic dilations with progressively shorter benefit. How should you define the stenosis, evaluate etiology, and decide whether another endoscopic procedure still makes sense versus definitive open reconstruction?",
"answer_text":"First characterize both anatomy and cause. Flexible laryngoscopy assesses the glottis and proximal subglottis; operative laryngoscopy and bronchoscopy define exact level, length, diameter, maturity of scar, circumferential involvement, and cartilage integrity. CT with airway reconstruction is helpful when length, external framework, or operative planning is uncertain. Etiology matters: review prior intubation or tracheostomy, autoimmune symptoms, prior surgery or radiation, and biopsy atypical, ulcerative, or mass-like disease before calling a stenosis idiopathic. Endoscopic dilation, radial incision, and selected adjuncts are reasonable for favorable short, soft, limited stenoses, especially when morbidity of open reconstruction is disproportionate. But repeated procedures with progressively shorter intervals suggest diminishing durability. Dense mature circumferential scar, longer stenosis, cartilage collapse, high-grade obstruction, or recurrent disease despite technically adequate endoscopic treatment should trigger discussion of definitive reconstruction such as cricotracheal or tracheal resection in an appropriate patient. The airway plan always comes first if stridor, work of breathing, or rapidly progressive symptoms suggest instability. The senior decision is to recognize when another technically easy dilation merely postpones a more durable solution.",
"explanation":"Endoscopic treatment is not a failure simply because recurrence occurs, but shortening benefit and unfavorable framework disease should change the strategy.",
"board_pearl":"Serial dilation is a treatment pathway, not an obligation; diminishing durability is information.",
"depth_layers_v187":{"foundation":"Define stenosis level, length, grade, scar quality, cartilage, and etiology.","application":"Use endoscopic therapy for favorable disease and investigate atypical or systemic causes.","senior_decision":"Escalate to definitive reconstruction when recurrence accelerates or framework disease makes repeated endoscopy predictably nondurable."},
"common_traps_v187":["Labeling unexplained stenosis idiopathic without considering GPA, prior injury, infection, or neoplasm can miss a treatable systemic or malignant cause.","Repeating dilation simply because it is feasible can expose the patient to repeated anesthesia while the interval of benefit steadily collapses."],
"deliberate_review_v187":"Expanded diagnostic staging into a recurrence-pattern and durability decision that distinguishes appropriate endoscopy from definitive reconstruction."},
"cc-v112-rec-sleep-surgery-dise":{
"concept_id":"v6-sleep-surgery-dise","canonical_topic":"DISE",
"prompt":"A 49-year-old with moderate obstructive sleep apnea cannot tolerate PAP and is considering surgery. Office examination does not clearly identify the dominant obstruction. How should drug-induced sleep endoscopy be used, what does it add beyond polysomnography, and which collapse patterns should materially change selection of palate surgery, tongue-base treatment, epiglottic treatment, or hypoglossal-nerve stimulation?",
"answer_text":"DISE is a dynamic upper-airway localization study, not a diagnostic test for OSA. Polysomnography establishes disease severity and physiology; DISE is used selectively when the treatment decision depends on the pattern, level, and direction of collapse. During a standardized sedated examination, describe the velum, oropharyngeal lateral walls, tongue base, and epiglottis, including degree and direction of collapse, and note how jaw or tongue advancement changes the airway when relevant. Large tonsils or dominant palatal collapse may support palate-directed treatment, tongue-base obstruction may support tongue-base or skeletal strategies, and independent epiglottic collapse may require epiglottis-specific planning rather than assuming palate surgery will solve it. Multilevel collapse often requires combined therapy. Complete concentric collapse at the velum is an important unfavorable phenotype for conventional unilateral hypoglossal-nerve stimulation candidacy, whereas other patterns may be compatible depending on the full eligibility profile. DISE must be interpreted alongside BMI, AHI, central-apnea burden, craniofacial anatomy, prior surgery, and patient goals. Persistent OSA after prior surgery should be re-localized rather than reflexively repeating the same operation. The senior use of DISE is to change a management decision, not merely generate a descriptive report.",
"explanation":"DISE is useful when dynamic collapse phenotype will alter treatment selection; it should not replace PSG or be ordered as an automatic ritual before every OSA intervention.",
"board_pearl":"PSG tells you how bad the sleep-disordered breathing is; DISE can help show how the airway fails and whether that should change the operation.",
"depth_layers_v187":{"foundation":"Know that DISE localizes dynamic collapse but does not diagnose OSA.","application":"Map collapse level, direction, degree, and response to maneuvers to procedure selection.","senior_decision":"Use incompatible collapse phenotypes to reject or redirect a proposed operation and re-localize persistent disease after prior surgery."},
"common_traps_v187":["Treating DISE as a substitute for polysomnography confuses anatomy with disease severity and physiology.","Repeating the same palate operation after failure without re-localizing multilevel or epiglottic collapse can reproduce the original treatment mismatch."],
"deliberate_review_v187":"Expanded a generic localization answer into procedure-specific interpretation, HNS candidacy logic, and salvage re-localization after failed surgery."}
}

def apply_concept_check_task_alignment_v187(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id)
        topic=str(module.get('topic') or '') if module else ''
        cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']:
            link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v187']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
