"""v20.16 extension — deepen the exact live Nasopharyngeal Carcinoma Concept Check."""

NPC_QID = "cc-v112-rec-head-neck-oncology-nasopharyngeal-carcinoma"
NPC_CID = "v6-head-neck-oncology-nasopharyngeal-carcinoma"
NPC_TOPIC = "Nasopharyngeal Carcinoma"

NPC_SOURCE_REFS_V216 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus; full compressed 7e copy identified at Drive id 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t. Durable nasopharyngeal anatomy, skull-base spread, nodal pathways, pathology and radiation-first management framework cross-referenced against the connected core-text corpus on 2026-09-08.","role":"durable anatomic/oncologic foundation: pharyngeal recess, Eustachian-tube relationship, skull-base/cranial-nerve spread, retropharyngeal and bilateral cervical drainage, radiation sensitivity and salvage principles"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52; Nasopharyngeal Cancer section cross-referenced 2026-09-08, including neck mass, serous otitis from Eustachian-tube obstruction, nasal symptoms and cranial-neuropathy presentation.","role":"resident/board presentation, staging-workup and treatment framework"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; Head and Neck tumor, TNM, chemotherapy, radiation and skull-base chapters cross-referenced 2026-09-08.","role":"operative/oncology cross-check for pharyngeal malignancy, skull-base extension, systemic therapy, radiation and salvage decision-making"},
    {"type":"staging_consensus","citation":"Pan JJ, et al. Ninth Version of the AJCC and UICC Nasopharyngeal Cancer TNM Staging Classification. JAMA Oncol. 2024;10(12):1627-1635. PMID: 39388190. DOI: 10.1001/jamaoncol.2024.4354. Global application launched January 2025.","role":"current anatomic staging: advanced radiologic extranodal extension as N3, nonmetastatic regrouping, and M1a versus M1b metastatic burden"},
    {"type":"guideline","citation":"SEOM–TTCC Clinical Guideline for Nasopharyngeal Carcinoma, update 2025; published 2026. Current guideline used for definitive chemoradiation, induction-systemic-therapy selection, recurrent/metastatic treatment, salvage neck dissection/nasopharyngectomy and re-irradiation selection.","role":"current multidisciplinary management and salvage guidance"},
    {"type":"review_guidance","citation":"Chua MLK, et al. Updates on Treatments and Management of Nasopharyngeal Carcinoma. American Society of Clinical Oncology Educational Book. 2025;45:e472460. DOI: 10.1200/EDBK-25-472460.","role":"current treatment synthesis: induction chemotherapy preference in locoregionally advanced disease, plasma EBV-DNA risk stratification and immunotherapy-era recurrent/metastatic management"},
    {"type":"fda_indication","citation":"U.S. FDA. FDA approves toripalimab-tpzi (LOQTORZI) for nasopharyngeal carcinoma. October 27, 2023: with cisplatin/gemcitabine first-line for adults with metastatic or recurrent locally advanced NPC; single-agent for recurrent unresectable or metastatic NPC progressing on or after platinum chemotherapy.","role":"current U.S. regulatory indication; prevents treating checkpoint therapy as merely investigational in recurrent/metastatic NPC"},
    {"type":"fda_indication","citation":"U.S. FDA. FDA approves penpulimab-kcqx for non-keratinizing nasopharyngeal carcinoma. April 23, 2025: with cisplatin or carboplatin plus gemcitabine first-line for adults with recurrent/metastatic non-keratinizing NPC; single-agent after platinum and at least one additional prior line in metastatic non-keratinizing NPC.","role":"current U.S. regulatory indication and histology-specific immunotherapy nuance"},
]

NPC_ANSWER = """Foundation — nasopharyngeal carcinoma (NPC) is not managed like a routine mucosal head-and-neck squamous cell carcinoma. Start with the anatomy. The primary commonly arises in the lateral nasopharynx around the pharyngeal recess/fossa of Rosenmüller, immediately adjacent to the Eustachian-tube cushion. That relationship explains why an adult with a new persistent unilateral serous middle-ear effusion, especially with a neck mass, nasal obstruction, epistaxis, headache, or cranial neuropathy, needs visualization of the nasopharynx rather than repeated treatment for isolated otitis media. The nasopharynx also has rich retropharyngeal and bilateral cervical lymphatic drainage, so nodal disease can be the first obvious manifestation and can be bilateral even when the mucosal primary is small.

Pathology and biology — distinguish keratinizing squamous carcinoma from non-keratinizing NPC. Endemic non-keratinizing NPC is strongly associated with Epstein-Barr virus (EBV), whereas nonendemic biology is more heterogeneous and a subset can be HPV-associated. Plasma EBV DNA is a highly useful biomarker in EBV-associated disease for prognosis, baseline risk assessment, response assessment and surveillance, but it is not a substitute for histologic diagnosis, endoscopy, or imaging. Assay platforms and treatment-adaptation thresholds are not perfectly interchangeable across centers, so a detectable or rising result should trigger clinical evaluation rather than an automatic treatment change without localization of disease.

Diagnostic workup — perform complete head-and-neck examination, flexible nasopharyngoscopy and biopsy of the primary when feasible. Image the nasopharynx and skull base with contrast-enhanced MRI because deep parapharyngeal extension, skull-base invasion, cavernous-sinus involvement and perineural/cranial-nerve spread may be underappreciated by surface examination alone. PET/CT or appropriate whole-body staging is important for nodal and distant disease. Document cranial nerves carefully; abducens dysfunction, trigeminal sensory changes, lower-cranial-neuropathy findings or Horner syndrome can localize advanced skull-base/parapharyngeal disease. A cervical node can be sampled when needed, but finding a metastatic node should not end the search for the nasopharyngeal primary.

Current staging — use the current AJCC/UICC ninth-version NPC framework rather than reflexively applying older stage-group memory. TNM-9 entered global use in January 2025. Important changes include advanced radiologic extranodal extension as an N3 feature, regrouping of nonmetastatic disease into stages I-III, and subdivision of metastatic disease into M1a/IVA for three or fewer metastatic lesions versus M1b/IVB for more than three lesions. The resident-level principle is not merely memorizing labels: stage must reflect the primary's skull-base/deep extension, bilateral/retropharyngeal nodal burden and metastatic burden because those features change systemic-therapy and radiation decisions.

Definitive treatment — NPC is predominantly a radiation-treated disease. Modern intensity-modulated radiation therapy (IMRT) is central because the primary sits near the brainstem, temporal lobes, optic apparatus, cochleae, salivary glands and cranial nerves while the at-risk retropharyngeal and cervical nodal basins often require treatment. Surgery is not the routine primary treatment for newly diagnosed conventional NPC. For genuinely early disease, radiation alone can be appropriate in selected low-risk presentations. As locoregional risk rises, concurrent cisplatin-based chemoradiation becomes central, and modern evidence strongly supports induction chemotherapy before chemoradiation for many patients with locoregionally advanced/high-risk disease.

Induction-chemotherapy nuance — do not convert the modern preference for induction therapy into the false rule that every NPC patient receives identical induction chemotherapy. Contemporary guideline and ASCO syntheses favor induction chemotherapy, commonly gemcitabine plus cisplatin in evidence-based regimens, followed by concurrent chemoradiotherapy for many locoregionally advanced patients. However, exact thresholds vary with the staging version, nodal burden, EBV-DNA risk, endemic versus nonendemic evidence base, comorbidity and institutional protocol. Some lower-risk stage groups can be managed without induction, and the value/tolerability of adjuvant chemotherapy after definitive chemoradiation is not interchangeable with the evidence supporting induction. Teach the direction of evidence and the reasons for selection, not a one-line universal sequence.

EBV-DNA application — obtain a pretreatment plasma EBV-DNA level when an appropriate validated assay is available in EBV-associated NPC. A high baseline level, slow clearance during induction, or persistent post-treatment detectability is prognostically adverse and may identify patients who deserve intensified evaluation. Yet biomarker-directed changes in the exact number of induction cycles or post-treatment therapy remain an evolving precision-oncology area. Do not cancel curative local therapy because the number falls quickly, and do not start salvage therapy from an isolated low-level result without confirming disease.

Response and surveillance — after treatment, assess the nasopharynx and neck clinically and endoscopically and use imaging at an appropriate interval; contemporary guidance commonly places the first major response assessment around three months. MRI is particularly useful for the nasopharynx and skull base; PET can help distinguish viable tumor from post-radiation change in the correct time window. Follow cranial-nerve function, hearing, swallowing, endocrine and other late-radiation effects. Persistent unilateral symptoms, a new neck mass, progressive neuropathy, recurrent epistaxis or rising EBV DNA deserves directed workup rather than attribution to radiation alone.

Senior recurrent/metastatic decision — separate potentially salvageable locoregional recurrence from disseminated disease. Selected small local recurrences can be treated with salvage nasopharyngectomy at experienced centers; contemporary guideline evidence includes a randomized comparison in carefully selected small local recurrences showing an endoscopic nasopharyngectomy advantage over re-irradiation. Carotid or intracranial invasion can make nasopharyngectomy inappropriate. Persistent or recurrent nodal disease can require selective or radical neck dissection depending on extent. Re-irradiation can control selected disease but carries major risks including temporal-lobe injury, cranial neuropathy, osteoradionecrosis and catastrophic carotid hemorrhage; prior dose, recurrence volume, disease-free interval, carotid involvement and performance status must be reviewed before committing.

Recurrent/metastatic systemic therapy — checkpoint inhibition is no longer merely experimental in the United States. FDA approved toripalimab-tpzi with cisplatin and gemcitabine in October 2023 for first-line adults with metastatic or recurrent locally advanced NPC, and toripalimab monotherapy after platinum progression in recurrent unresectable/metastatic disease. In April 2025 FDA also approved penpulimab-kcqx with cisplatin or carboplatin plus gemcitabine first-line for recurrent/metastatic non-keratinizing NPC, with a later-line monotherapy indication after platinum and at least one additional line. Those approvals do not mean PD-1 therapy should be inserted automatically into every curative localized case; integration of immunotherapy into definitive locoregionally advanced therapy continues to evolve and should follow current disease-setting evidence, regulatory labeling and multidisciplinary guidance.

OR/salvage danger zones — salvage surgery after radiation is not a routine primary-nasopharynx dissection. Expect scarred planes, altered vascularity and proximity to the parapharyngeal/internal carotid artery and skull base. Before nasopharyngectomy, define carotid relationship and intracranial extension and ensure that an endoscopic approach can achieve exposure and oncologic margins. Before neck dissection for irradiated nodal recurrence, anticipate fibrosis around the carotid sheath, cranial nerves and prior treatment fields. Do not pursue a deep margin blindly when the carotid is not controlled or the skull-base plane is uncertain; stop, reorient, obtain vascular/skull-base help when necessary, and change the salvage plan rather than converting uncertainty into exsanguination or cranial-nerve injury.

Bleeding rescue — recurrent epistaxis in an irradiated NPC patient is not always benign mucosal bleeding. A sentinel hemorrhage can precede carotid blowout, particularly after re-irradiation, skull-base necrosis or recurrent tumor near the carotid. Prioritize airway and hemodynamic resuscitation, avoid uncontrolled blind instrumentation, obtain urgent vascular imaging/interventional support when carotid injury is plausible, and coordinate endovascular or operative control according to anatomy. The senior bailout is to recognize when 'epistaxis' has become a vascular emergency.

Synthesis — the board and OR framework is: suspect NPC from the presentation; visualize and biopsy; map skull base, cranial nerves, retropharyngeal/bilateral nodes and distant disease; stage with the current TNM system; use radiation-based definitive therapy with stage/risk-appropriate systemic treatment; use EBV DNA as a powerful adjunct rather than an oracle; reserve surgery for selected salvage and neck disease; and in the recurrent irradiated patient respect carotid, skull-base and re-irradiation danger. Durable textbook anatomy remains stable, while systemic therapy, staging and biomarker use must be updated to contemporary evidence."""

NPC_COHORT = {
    NPC_QID: {
        "concept_id": NPC_CID,
        "canonical_topic": NPC_TOPIC,
        "prompt": "A 46-year-old adult presents with a painless level II neck mass, persistent unilateral middle-ear effusion, intermittent epistaxis, and new diplopia. Nasopharyngoscopy shows a lateral nasopharyngeal mass and biopsy confirms non-keratinizing nasopharyngeal carcinoma. As the senior resident, build the case from anatomy and EBV biology through current AJCC/UICC staging, imaging, definitive radiation/systemic therapy, plasma EBV-DNA interpretation, and surveillance. Then explain when induction chemotherapy is favored but not universal, what current FDA-approved immunotherapy applies in recurrent/metastatic disease, when salvage nasopharyngectomy or neck dissection is reasonable, and what carotid/re-irradiation danger zones should make you stop or change the salvage plan.",
        "answer_text": NPC_ANSWER,
        "explanation": "NPC is a radiation-centered, EBV-linked and skull-base-sensitive disease in which current staging, systemic-therapy evidence, biomarker interpretation and selected salvage must be layered onto durable nasopharyngeal anatomy.",
        "board_pearl": "Adult unilateral effusion plus a neck mass is a nasopharynx-until-proven-otherwise pattern; stage with TNM-9, use IMRT with risk-appropriate systemic therapy, treat EBV DNA as an adjunct, and reserve surgery mainly for selected salvage/neck disease.",
        "depth_layers_v216": {"foundation":"Pharyngeal recess/Eustachian-tube anatomy, bilateral retropharyngeal/cervical drainage, EBV-associated non-keratinizing biology, skull-base and cranial-nerve spread.","application":"Endoscopy/biopsy, MRI plus systemic staging, TNM-9, IMRT-centered definitive care, induction-versus-concurrent therapy selection, EBV-DNA interpretation and surveillance.","senior_decision":"Select salvage nasopharyngectomy/neck dissection versus re-irradiation/systemic therapy, use current FDA immunotherapy indications correctly, and bail out when carotid or skull-base control is unsafe."},
        "common_traps_v216": [
            "Treating a new persistent unilateral adult serous effusion with repeated tubes or antibiotics without examining the nasopharynx.",
            "Stopping the workup after finding a metastatic cervical node instead of identifying and staging the nasopharyngeal primary.",
            "Assuming all NPC is biologically identical and ignoring the strong EBV association of endemic non-keratinizing disease.",
            "Using plasma EBV DNA as a substitute for biopsy, endoscopy, MRI, or anatomic staging.",
            "Using an older NPC stage-group memory without recognizing the January 2025 TNM-9 changes.",
            "Missing skull-base or cranial-nerve spread because the mucosal primary looks small on office endoscopy.",
            "Planning routine primary nasopharyngectomy for a newly diagnosed conventional NPC instead of radiation-centered definitive therapy.",
            "Giving the same induction-chemotherapy sequence to every stage and risk group rather than individualizing by stage, nodal burden, EBV risk and fitness.",
            "Treating adjuvant chemotherapy and induction chemotherapy as evidence-equivalent interchangeable strategies.",
            "Assuming a rapidly falling EBV-DNA value eliminates the need for definitive local therapy.",
            "Starting salvage treatment from an isolated biomarker rise without localizing recurrent disease.",
            "Calling PD-1 therapy investigational in all NPC despite current U.S. FDA toripalimab and penpulimab indications in recurrent/metastatic disease.",
            "Conversely, adding checkpoint therapy automatically to every curative localized case despite evolving rather than universal definitive-setting evidence.",
            "Choosing re-irradiation without accounting for prior dose, recurrence volume, skull-base necrosis and carotid-blowout risk.",
            "Attempting salvage nasopharyngectomy with carotid or intracranial invasion that makes safe oncologic resection inappropriate.",
            "Performing blind deep dissection in the irradiated parapharyngeal/skull-base plane when carotid control is uncertain.",
            "Dismissing recurrent epistaxis after radiation as routine mucosal bleeding when it may be a sentinel carotid hemorrhage.",
        ],
        "deliberate_review_v216": "Selected from the exact successful v20.16 production backlog: 325 canonical topics, 618 Concept Checks, 157 untouched shallow checks, 8 residual candidates and 0 failures. Although lexical rank was fourth, the exact-live NPC answer was only 15 words and the topic carries substantially higher resident/board/oncologic/salvage value than the generic rank leaders; clinical priority therefore intentionally overrides lexical rank.",
        "source_refs_v216": NPC_SOURCE_REFS_V216,
        "evidence_distinction_v216": "Durable nasopharyngeal/skull-base anatomy and radiation-first disease principles remain textbook-grounded. Management is updated to TNM-9, contemporary induction-chemotherapy evidence, current EBV-DNA risk-stratification limits, 2023/2025 U.S. FDA checkpoint-inhibitor indications and modern salvage evidence. Guideline differences in exactly which nonmetastatic risk groups require induction chemotherapy are presented as a selection issue rather than falsely collapsed into one universal regimen.",
        "audit_profile_v216": "nasopharyngeal_carcinoma",
    }
}
