"""v19.5 — live-canonical adverse pathology and adjuvant therapy depth cohort."""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-head-neck-oncology-adverse-pathology-and-adjuvant-therapy":{
"concept_id":"v6-head-neck-oncology-adverse-pathology-and-adjuvant-therapy",
"canonical_topic":"Adverse Pathology and Adjuvant Therapy",
"prompt":"A 61-year-old undergoes curative-intent resection of an oral cavity squamous cell carcinoma with neck dissection. Final pathology shows a negative but close primary margin, pT3 disease, perineural invasion, three metastatic cervical nodes, and extranodal extension in one node. How should the tumor board translate the operative and pathologic findings into postoperative observation versus radiation versus concurrent chemoradiation, which findings carry the strongest evidence for adding concurrent systemic therapy, and what patient or treatment factors can change the plan?",
"answer_text":"Postoperative treatment is driven by the recurrence risk demonstrated by the resection specimen, not simply by the preoperative clinical stage. First separate the classic high-risk features from intermediate-risk features. A microscopically positive surgical margin means invasive tumor remains at the cut edge, and extranodal extension (ENE) means metastatic tumor has extended beyond the lymph-node capsule into surrounding soft tissue. In a patient with resected mucosal head-and-neck squamous cell carcinoma who can tolerate treatment, either finding classically supports postoperative radiation with concurrent cisplatin-based systemic therapy rather than radiation alone. Before accepting a positive margin as immutable, the surgeon and tumor board should determine whether a clearly oriented, oncologically meaningful re-resection can safely clear it; a vague additional specimen or an anatomically impossible re-resection should not create false reassurance. Intermediate adverse features—including pT3-4 primary disease, multiple involved nodes or greater nodal burden, perineural invasion, lymphovascular invasion, and a close but negative margin—commonly support postoperative radiation according to site-specific risk. They do not automatically carry the same evidence-based indication for concurrent chemotherapy as positive margin or ENE, so avoid adding chemotherapy merely because several intermediate features are present without considering the disease site, guideline context, and patient fitness. Margin interpretation must remain site- and specimen-specific: orientation, the exact involved surface, separately submitted margins, bone versus soft-tissue involvement, and whether the 'close' distance is meaningful for that anatomic site can change the discussion. The tumor board should also review HPV/p16 status when relevant, pathologic T/N stage, number and laterality of nodes, ENE extent, PNI/LVI, prior radiation, wound healing, nutrition, performance status, renal function, baseline hearing and neuropathy before selecting concurrent cisplatin. If cisplatin is contraindicated, do not casually substitute another radiosensitizer as though it has identical postoperative evidence; radiation alone or an alternative regimen requires multidisciplinary, disease-specific judgment. Finally, adjuvant therapy is time-sensitive: healing and dental/nutritional preparation should be coordinated so postoperative radiation is not unnecessarily delayed, with initiation within roughly six weeks after surgery used as an important quality target when feasible. The senior decision is therefore not 'bad pathology equals more treatment'; it is to identify which pathologic feature changes modality, confirm that the pathology actually represents residual or extracapsular disease, and balance oncologic benefit against treatment toxicity without losing the postoperative treatment window.",
"explanation":"Positive margin and ENE are the classic postoperative high-risk findings that most directly change modality from radiation alone to concurrent chemoradiation in an appropriate patient. Other adverse features often justify postoperative radiation but require site- and patient-specific judgment before systemic therapy is added.",
"board_pearl":"Do not lump every adverse pathologic feature together: positive margin and ENE are the classic high-risk triggers for postoperative concurrent chemoradiation, whereas PNI, LVI, pT3-4 disease, nodal burden, and close negative margins more often define postoperative-radiation risk.",
"depth_layers_v195":{"foundation":"Distinguish a truly positive surgical margin and extranodal extension from intermediate adverse features such as PNI, LVI, pT3-4 disease, nodal burden, and a close but negative margin.","application":"Use the final pathology, specimen orientation, disease site, and patient fitness to choose observation, postoperative radiation, or concurrent cisplatin-based chemoradiation rather than escalating all adverse pathology identically.","senior_decision":"Decide whether a positive margin is safely re-resectable, avoid unsupported chemotherapy substitutions or automatic escalation for intermediate features, and coordinate healing, nutrition, dental care, and radiation planning so adjuvant therapy is not unnecessarily delayed."},
"common_traps_v195":["Treating a close but negative margin as identical to a microscopically positive margin can trigger unnecessary trimodality toxicity; confirm the oriented specimen, involved surface, separately submitted margins, and site-specific significance before changing modality.","Adding concurrent chemotherapy for PNI, LVI, pT3-4 disease, or multiple nodes simply because several adverse features coexist ignores that the strongest classic postoperative chemoradiation evidence centers on positive margin and ENE; patient fitness and disease-specific guidance still matter."],
"deliberate_review_v195":"Replaced the 62-word anatomic definition with a tumor-board decision framework separating high-risk from intermediate-risk pathology, re-resection judgment, cisplatin fitness, postoperative timing, and modality-changing evidence."
}
}

def apply_concept_check_task_alignment_v195(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id); topic=str(module.get('topic') or '') if module else ''; cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']: link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v195']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
