"""v20.19 — deepen the exact-live Parathyroid Carcinoma Concept Check on validated v20.18 production."""
from concept_check_board_repair_v177 import _find_module

QIDS = (
    "cc-v112-rec-thyroid-parathyroid-salivary-parathyroid-carcinoma",
)
CID = "v6-thyroid-parathyroid-salivary-parathyroid-carcinoma"
TOPIC = "Parathyroid Carcinoma"

SOURCE_REFS_V219 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus, full copy Drive id 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t plus connected split-volume set; thyroid/parathyroid operative anatomy and oncologic principles cross-referenced 2026-09-08.","role":"durable operative foundation: parathyroid/thyroid relationships, recurrent laryngeal nerve, tracheoesophageal and carotid-sheath danger zones, intact oncologic resection"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52; Parathyroids section and endocrine surgery framework cross-referenced 2026-09-08.","role":"resident/board framework: hyperparathyroidism, localization, operative anatomy, calcium/PTH management"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; Chapter 38 Thyroid and Parathyroid Glands cross-referenced 2026-09-08.","role":"operative cross-check: endocrine neck anatomy, recurrent laryngeal nerve and parathyroid surgical decision-making"},
    {"type":"guideline","citation":"Wilhelm SM, et al. The American Association of Endocrine Surgeons Guidelines for Definitive Management of Primary Hyperparathyroidism. JAMA Surg. 2016;151:959-968. PMID: 27532368.","role":"AAES carcinoma boundary: suspect with severe biochemical disease; complete resection avoiding capsular disruption; no prophylactic central/lateral neck dissection; long-term calcium/PTH surveillance"},
    {"type":"consensus","citation":"Makay O, et al. Consensus statement of the European Society of Endocrine Surgeons on advanced parathyroid cancer: definitions and management. Br J Surg. 2024;111(5):znae108. PMID: 38713608.","role":"current advanced-surgery consensus: specialized-center care, en-bloc resection without capsular rupture, locally advanced structure/RLN tradeoffs and recurrent-disease strategy"},
    {"type":"guideline","citation":"Hadoux J, et al. Neuroendocrine neoplasms of head and neck, genitourinary and gynaecological systems, unknown primaries, parathyroid carcinomas and intrathyroid thymic neoplasms: ESMO Clinical Practice Guideline. ESMO Open. 2024;9(10):103664. PMID: 39461777.","role":"current rare-endocrine oncology guidance: diagnosis, staging, recurrent/metastatic management, molecular profiling and follow-up"},
    {"type":"current_review","citation":"Management of aggressive forms of primary HPT: Parathyroid carcinoma and atypical parathyroid tumor. Ann Endocrinol (Paris). 2026. PMID: 42580893.","role":"2026 evidence update: CDC73/parafibromin, severe-hypercalcemia control, oncologic surgery, debated adjuvant RT, recurrence and targeted-therapy boundaries"},
]

PROMPT = """A 46-year-old patient has calcium 14.6 mg/dL, markedly elevated PTH, nephrolithiasis, bone pain, a 3.5-cm firm inferior parathyroid-region mass and new hoarseness. As the senior resident planning surgery, explain how suspicion for parathyroid carcinoma changes preoperative workup, biopsy decisions, exposure and first-pass resection; how you handle an adherent or invaded recurrent laryngeal nerve, thyroid, trachea or esophagus; what intraoperative findings make you stop a routine parathyroidectomy; and how calcium/PTH kinetics, pathology, CDC73/parafibromin, recurrence and metastatic disease change postoperative management. Include explicit rescue and bailout decisions that prevent capsular rupture, uncontrolled nerve injury or incomplete oncologic surgery."""

ANSWER = """Foundation — parathyroid carcinoma is rare, but missing the diagnosis before or during the first operation can convert a potentially curable operation into a lifelong recurrence problem. Suspect carcinoma when primary hyperparathyroidism is unusually severe: marked hypercalcemia, very high PTH, renal and skeletal complications together, a palpable neck mass, hoarseness or other evidence of local invasion, or a large firm gland on imaging. None of these findings alone proves malignancy. The key resident move is to recognize a high-risk phenotype early enough to plan an oncologic operation rather than treating the lesion as a routine adenoma.

Preoperative localization and staging — confirm PTH-dependent hypercalcemia and stabilize dangerous hypercalcemia before elective surgery. Assess creatinine, phosphate, magnesium, vitamin D, ECG and volume status; severe symptomatic hypercalcemia may require IV isotonic fluid, antiresorptive therapy and calcimimetic treatment in addition to definitive tumor control. Ultrasound can show a large irregular hypoechoic lesion, loss of tissue planes or adjacent thyroid involvement. Multiphase CT or other cross-sectional imaging helps define tracheoesophageal, thyroid, vascular and nodal relationships; imaging is for operative planning and staging, not for histologic proof. Obtain a baseline laryngeal examination when voice is abnormal, prior surgery exists, or invasive disease approaches the recurrent laryngeal nerve. In a patient with suspected carcinoma, avoid percutaneous FNA or core biopsy of the parathyroid mass because cytology is unreliable for distinguishing adenoma from carcinoma and needle disruption risks fibrosis, diagnostic confusion and possible seeding.

Pathology and genetics — the diagnosis cannot be made from cellular atypia alone. Unequivocal invasive behavior such as vascular invasion, lymphatic invasion, perineural invasion, direct invasion into adjacent structures, nodal disease or metastasis establishes malignancy; parafibromin loss and CDC73 abnormalities can support the diagnosis and identify a hereditary cancer-predisposition pathway. Ask about family history of hyperparathyroidism, jaw tumors, renal or uterine tumors and young age. Germline CDC73 evaluation is particularly important when carcinoma is confirmed or strongly suspected. The durable distinction for boards is that a suspicious gland is managed by operative oncologic behavior before final pathology is available; definitive histologic classification follows the intact specimen.

First-operation anatomy — know the tracheoesophageal groove, recurrent laryngeal nerve, inferior thyroid artery, thyroid capsule, strap muscles, esophageal muscular wall, trachea and carotid sheath before committing to tumor mobilization. Carcinoma may feel gray-white, hard, fibrotic and adherent rather than the soft, reddish-brown, easily dissected appearance of a typical adenoma. The operation should proceed from normal tissue toward tumor so that planes are defined before the mass is manipulated. Do not grasp the tumor capsule, shell it out through an adhesive plane or rupture it to gain exposure. Capsular disruption and tumor spillage are major avoidable errors because local recurrence may be difficult to eradicate.

Primary surgery — when carcinoma is suspected and resection is feasible, the objective is an R0 en-bloc resection without capsular rupture. This commonly means removal of the involved parathyroid tumor with the ipsilateral thyroid lobe and any directly invaded soft tissue as one specimen rather than piecemeal parathyroidectomy. Adjacent strap muscle, esophageal muscularis or other structures are resected only when actually required for a clear gross margin; the operation is not a ritualized radical neck dissection. Current AAES guidance specifically discourages prophylactic central or lateral neck dissection in the absence of evidence of nodal disease, while contemporary ESES guidance emphasizes complete initial resection and individualized management of advanced local invasion. Therapeutic nodal dissection is appropriate for clinically or radiographically involved nodes.

Recurrent laryngeal nerve decision — this is a senior judgment point, not a memorized automatic sacrifice. If the nerve is grossly invaded and an R0 resection is otherwise achievable only by nerve sacrifice, oncologic clearance may require resection, with preoperative counseling about voice, aspiration and reconstruction options. If the nerve is merely adherent or entrapped yet functioning, the evidence is weak and expert consensus acknowledges a real tradeoff between R0 clearance and functional preservation. Identify the nerve in normal tissue, use monitoring as an adjunct when appropriate, avoid traction through tumor, and make the decision deliberately rather than tearing tumor off the nerve or sacrificing a functional nerve reflexively.

Rescue and bailout — if the presumed adenoma is unexpectedly rock-hard, densely adherent, invasive or inseparable from thyroid, stop the routine focused-parathyroidectomy script. Do not keep peeling until the capsule tears. Widen exposure, confirm anatomy, assess whether an oncologic en-bloc resection can be completed safely, and call an experienced endocrine/head-and-neck surgeon if needed. If gross invasion of trachea, esophagus, carotid or a functioning recurrent laryngeal nerve creates a morbidity decision that was not consented or cannot be managed safely, it is better to preserve the specimen and defer a planned multidisciplinary operation than to perform uncontrolled piecemeal debulking. Catastrophic bleeding is managed by compression, exposure and vascular control, not blind clamping around the recurrent laryngeal nerve or carotid sheath.

Intraoperative PTH and postoperative calcium — intraoperative PTH can document removal of functioning tissue, but a biochemical fall does not prove oncologic adequacy. Conversely, renal dysfunction can slow PTH clearance and blunt the expected kinetic drop, so failure to achieve a textbook percentage decline should be interpreted with renal function and the operative picture rather than prompting indiscriminate exploration. After removal of a highly functional carcinoma, anticipate profound hypocalcemia and hungry-bone physiology, especially in patients with severe bone disease. Monitor calcium, magnesium and phosphate, replace calcium and active vitamin D as needed, and distinguish expected postoperative hypocalcemia from persistent hypercalcemia suggesting residual functional disease.

Adjuvant therapy boundary — complete surgery is the only established curative modality. Routine adjuvant external-beam radiation after an R0 resection is not supported by strong evidence; older AAES guidance advises against routine use, whereas newer expert discussions allow individualized consideration after unresectable or grossly incomplete local disease because recurrence risk is high and data are sparse. This disagreement should be taught explicitly rather than flattened into a single rule. Cytotoxic chemotherapy has no established standard curative role. In recurrent or metastatic disease, the immediate threat is often uncontrolled PTH-mediated hypercalcemia rather than tumor volume itself.

Recurrent/metastatic disease — confirm biochemical recurrence with calcium and PTH trends and localize disease with neck and systemic imaging. Resectable locoregional or oligometastatic disease can merit repeat surgery when meaningful biochemical or disease control is achievable, but reoperations carry greater recurrent-nerve, hypoparathyroidism, esophageal, tracheal and vascular risk. Control hypercalcemia aggressively with hydration when appropriate, calcimimetics such as cinacalcet, antiresorptive therapy and other endocrine support. For progressive unresectable disease, contemporary ESMO guidance and recent reviews support molecular profiling and individualized systemic therapy in expert centers; antiangiogenic multikinase inhibitors have reported activity, but there is no universal FDA-approved parathyroid-carcinoma drug regimen that should be memorized as standard.

Surveillance — a patient is not “cured” because the calcium normalized at the postoperative visit. Parathyroid carcinoma can recur years later. Follow calcium and PTH long term, reassess the neck and distant sites when biochemistry or symptoms change, and integrate pathology features such as invasion and parafibromin/CDC73 findings. Rising PTH may precede major hypercalcemia and should trigger deliberate evaluation rather than reassurance.

Senior synthesis — before incision, answer four questions: Do the biochemical and imaging features make carcinoma plausible? Can the tumor be removed intact with a meaningful margin? Which adjacent structures, especially the recurrent laryngeal nerve, trachea, esophagus and carotid sheath, could force a morbidity tradeoff? What will make you stop rather than rupture the tumor? During surgery, the most dangerous cognitive error is continuing a routine adenoma operation after the anatomy tells you the diagnosis may be different. The oncologic priority is intact first-pass resection when safely achievable; the safety priority is controlled exposure and a planned bailout when achieving that margin would require an unconsented or technically uncontrolled sacrifice."""

TRAPS = [
    "Treating severe primary hyperparathyroidism with a large firm mass as routine adenoma until the capsule tears.",
    "Using FNA or core biopsy to prove parathyroid carcinoma despite unreliable cytologic distinction and avoidable disruption/seeding risk.",
    "Beginning tumor mobilization before defining the recurrent laryngeal nerve, thyroid, tracheoesophageal groove and carotid-sheath relationships.",
    "Shelling a hard adherent tumor out of the thyroid instead of preserving an intact en-bloc oncologic specimen.",
    "Performing prophylactic central or lateral neck dissection when there is no clinical or radiographic nodal disease.",
    "Sacrificing a functioning recurrent laryngeal nerve reflexively without recognizing the evidence-poor R0-versus-function tradeoff.",
    "Tearing gross tumor from an invaded nerve simply to preserve motion and leaving an uncontrolled margin without acknowledging it.",
    "Continuing a focused parathyroidectomy after unexpected dense invasion rather than widening exposure or staging a safer oncologic operation.",
    "Interpreting a >50% intraoperative PTH drop as proof that the cancer operation was oncologically complete.",
    "Forgetting that renal dysfunction can slow PTH clearance and make intraoperative kinetics less textbook-like.",
    "Missing hungry-bone physiology after resection of a highly functional tumor and under-monitoring calcium, magnesium and phosphate.",
    "Calling postoperative normocalcemia a cure and stopping long-term calcium/PTH surveillance.",
    "Giving routine adjuvant radiation after every R0 resection despite sparse evidence and guideline disagreement.",
    "Focusing on tumor size in recurrent disease while undertreating the immediate metabolic danger of severe PTH-mediated hypercalcemia.",
    "Presenting a multikinase inhibitor or other systemic agent as a universal FDA-approved parathyroid-carcinoma standard when evidence remains limited and individualized.",
]

COHORT = {QIDS[0]: {
    "concept_id": CID,
    "canonical_topic": TOPIC,
    "prompt": PROMPT,
    "answer_text": ANSWER,
    "explanation": "Parathyroid carcinoma is a first-operation diagnosis problem: recognize the high-risk phenotype, avoid biopsy/capsular disruption, obtain intact oncologic resection when safely feasible, and deliberately manage RLN/adjacent-organ tradeoffs, severe hypercalcemia and lifelong recurrence risk.",
    "board_pearl": "The board-saving move is suspicion before rupture: severe calcium/PTH plus a large firm invasive gland should trigger intact en-bloc oncologic thinking, not a routine focused parathyroidectomy or FNA.",
    "depth_layers_v219": {
        "foundation":"Severe PTH-dependent hypercalcemia phenotype; parathyroid/thyroid/RLN/tracheoesophageal anatomy; invasive pathology and CDC73/parafibromin framework.",
        "application":"No-FNA boundary, staging, intact en-bloc resection, selective adjacent-structure resection, therapeutic-not-prophylactic nodal surgery, calcium/PTH and recurrence management.",
        "senior_decision":"Stop routine adenoma dissection before capsular rupture; explicitly decide R0-versus-function when RLN/airway/esophagus is involved; stage or escalate expertise rather than perform uncontrolled piecemeal surgery."
    },
    "common_traps_v219": TRAPS,
    "deliberate_review_v219": "Selected from the exact successful v20.18 production backlog, where only seven residual candidates remained. Although lexical rank was fourth, Parathyroid Carcinoma was promoted because the first-operation diagnosis, capsule-rupture avoidance, RLN/adjacent-organ margin decisions, severe hypercalcemia and recurrence biology are disproportionately high-yield for boards and the OR.",
    "source_refs_v219": SOURCE_REFS_V219,
    "evidence_distinction_v219": "Durable Cummings/Pasha/K.J. Lee endocrine-neck anatomy and intact oncologic operative principles are preserved. AAES 2016 remains useful for the no-capsular-disruption/no-prophylactic-neck-dissection framework; ESES 2024 adds advanced-local-disease and RLN tradeoff consensus; ESMO 2024 and a 2026 review update recurrence, molecular profiling and systemic options. Adjuvant RT and functioning-RLN sacrifice are explicitly presented as evidence-limited individualized decisions rather than false absolutes, and no universal FDA-approved systemic regimen is implied.",
    "audit_profile_v219": "parathyroid_carcinoma",
}}

def apply_concept_check_task_alignment_v219(checks, deep_modules, v6_item_id):
    by={str(q.get("id") or ""):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get("topic") or "") if m else ""; cid=v6_item_id(q.get("domain"),topic) if m and q.get("domain") else None
        persisted=q.get("concept_id")
        if m is None or topic!=p["canonical_topic"] or cid!=p["concept_id"] or (persisted is not None and persisted!=cid): link_mismatch.append(qid); continue
        q["concept_id"]=cid; q["canonical_topic"]=topic
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v219","common_traps_v219","deliberate_review_v219","source_refs_v219","evidence_distinction_v219","audit_profile_v219"): q[field]=p[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v219"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
