"""v18.4 — next deterministic live-canonical Concept Check depth cohort.

Selected from V183_DEPTH_BACKLOG_AUDIT.json after v18.0-v18.3 exclusions.
Each item preserves its exact live canonical concept_id and adds only missing
foundation -> application -> senior-decision content. Because these are oral-board
free-response checks, individualized error analysis is stored as common_traps_v184.
"""

from concept_check_board_repair_v177 import _find_module

COHORT = {
    "cc-v112-rec-facial-plastics-trauma-facial-synkinesis-static-dynamic-rehabilitation": {
        "concept_id": "v6-facial-plastics-trauma-facial-synkinesis-static-dynamic-rehabilitation",
        "canonical_topic": "Facial Synkinesis / Static-Dynamic Rehabilitation",
        "prompt": "A patient one year after facial nerve injury has involuntary eye closure with smiling, oral commissure movement with blinking, facial tightness, and asymmetric resting tone. How do you distinguish synkinetic reinnervation from persistent flaccid denervation, what is first-line rehabilitation, and when should static or dynamic surgery enter the plan?",
        "answer_text": "First define the phenotype rather than treating all facial weakness alike. Synkinesis implies recovered but misdirected motor activity with coupled movements and hypertonicity; persistent flaccid paralysis implies inadequate reinnervation and different reconstructive options. Document branch-specific excursion, smile symmetry, ocular protection, oral competence, resting tone and the patient's highest-priority functional complaint. Neuromuscular retraining is foundational, and targeted botulinum toxin can reduce maladaptive co-contraction while preserving useful movement. Static procedures are appropriate when protection, symmetry or oral competence cannot be achieved with motor retraining alone. Dynamic nerve or muscle-transfer strategies depend on duration of denervation, viable motor endplates, proximal nerve availability and donor function. Escalate ocular exposure urgently, and do not perform an irreversible weakening or transfer procedure until the residual motor pattern and reconstructive target are clear.",
        "explanation": "Synkinesis is aberrant reinnervation, not simply residual paralysis. The senior decision is whether the problem is excessive coupled activation, absent motor input, loss of protection, or loss of dynamic excursion because each requires a different rehabilitation strategy.",
        "board_pearl": "Before choosing a facial reanimation operation, decide whether the face is flaccid, synkinetic, or mixed; the same weakness score can hide very different physiology.",
        "depth_layers_v184": {"foundation": "Differentiate synkinetic reinnervation from persistent denervation.", "application": "Map branch-specific function and use retraining plus targeted chemodenervation according to the abnormal movement pattern.", "senior_decision": "Choose static versus dynamic reconstruction from ocular/oral needs, denervation duration, viable motor units and donor options."},
        "common_traps_v184": ["Treating synkinesis as simple weakness can worsen useful movement with indiscriminate weakening.", "Choosing a dynamic transfer without considering denervation duration and viable motor endplates can produce a technically successful but functionally poor reconstruction."],
        "deliberate_review_v184": "Reused the existing retraining/botulinum/static-dynamic framework and added physiologic discrimination, examination targets, ocular urgency and reconstruction-selection thresholds."
    },
    "cc-v112-rec-general-ent-emergencies-wound-healing-scar-biology-in-head-neck-surgery": {
        "concept_id": "v6-general-ent-emergencies-wound-healing-scar-biology-in-head-neck-surgery",
        "canonical_topic": "Wound Healing / Scar Biology in Head & Neck Surgery",
        "prompt": "A previously irradiated neck incision begins separating on postoperative day 8 with erythema, salivary-appearing drainage, and exposed hardware. How do you determine why the wound is failing, what must be controlled before revision, and when should repeated local closure be abandoned for vascularized tissue?",
        "answer_text": "Treat wound failure as a cause-and-host problem before calling it a scar problem. Examine for infection, hematoma or seroma, salivary or pharyngocutaneous fistula, exposed hardware, ischemia, recurrent tumor, excessive tension and radiation injury; assess nutrition, diabetes, smoking and other healing modifiers. Obtain cultures or imaging selectively when a deep collection, fistula tract or recurrent disease is suspected, but do not delay drainage or source control in a clinically infected wound. Correct contamination, nutrition, dead space and mechanical tension before definitive closure. Irradiated tissue has impaired vascularity and fibroatrophic change, so repeated tight closure of ischemic edges predictably fails. When the bed is hostile, hardware or major structures are exposed, a fistula persists, or viable local tissue cannot achieve tension-free coverage, import well-vascularized regional or free tissue. Reserve elective scar revision for a stable healed wound after remodeling and after the original failure mechanism has been addressed.",
        "explanation": "Inflammation, perfusion, contamination and tension determine whether a head-and-neck wound can heal. In irradiated or fistulized beds, vascularized tissue is often a source-control and biology decision rather than a cosmetic escalation.",
        "board_pearl": "Do not revise the scar until you know why the wound failed; in a hostile irradiated bed, vascularity is often the missing treatment.",
        "depth_layers_v184": {"foundation": "Recognize inflammatory, proliferative and remodeling biology plus ischemia, contamination and tension as failure drivers.", "application": "Identify infection, fistula, hardware, nutrition and radiation injury before revision.", "senior_decision": "Escalate from local closure to vascularized tissue when source control, perfusion or durable coverage cannot be achieved locally."},
        "common_traps_v184": ["Repeatedly closing a salivary-contaminated or irradiated wound under tension treats the dehiscence but not the mechanism.", "Calling every late wound change 'radiation' can miss recurrent tumor, deep infection or exposed hardware."],
        "deliberate_review_v184": "Reused the existing tension/ischemia/infection/radiation framework and added source control, fistula/hardware assessment, host optimization and vascularized-tissue thresholds."
    },
    "cc-v112-mgt-facial-plastics-trauma-forehead-flap-nasal-reconstruction": {
        "concept_id": "v6-facial-plastics-trauma-forehead-flap-nasal-reconstruction",
        "canonical_topic": "Forehead Flap / Nasal Reconstruction",
        "prompt": "After Mohs resection, a patient has a full-thickness distal nasal defect involving skin, missing alar cartilage, and absent internal lining. How do you analyze the defect, sequence lining/support/cover reconstruction, and what technical or postoperative findings threaten a paramedian forehead flap enough to require urgent intervention?",
        "answer_text": "Reconstruct the nose in layers and by subunit rather than treating the defect as missing skin alone. Define external skin loss, lining loss, cartilage or bony support loss, alar-rim position and the functional risk of valve collapse. Restore stable internal lining first or simultaneously, then rebuild structural support with cartilage when the alar rim, sidewall or tip framework is missing, and finally provide external cover. A paramedian forehead flap is useful for larger distal nasal defects because it supplies robust, color-matched vascularized skin based on the supratrochlear system, but it cannot substitute for absent lining or framework. Design pedicle width and arc to avoid kinking, avoid excessive tension, and stage thinning/division deliberately. Postoperatively, venous congestion, rapidly progressive duskiness, hematoma, pedicle compression or loss of Doppler/clinical perfusion requires immediate assessment and correction of mechanical causes; do not wait for established necrosis. Long-term success also requires maintaining airway patency and alar support, not merely skin survival.",
        "explanation": "Forehead-flap nasal reconstruction is a three-layer functional reconstruction. A healthy skin paddle can still yield obstruction and retraction if lining and structural support are not restored.",
        "board_pearl": "For a full-thickness nasal defect, say lining, support, and cover in that order before naming the flap.",
        "depth_layers_v184": {"foundation": "Analyze nasal subunit plus lining, support and cover requirements.", "application": "Use forehead skin for cover while independently restoring lining and cartilage framework.", "senior_decision": "Recognize pedicle kinking, hematoma and venous compromise early and rescue perfusion before necrosis develops."},
        "common_traps_v184": ["Using a forehead flap as a skin-only solution without rebuilding alar support can create late valve collapse and retraction.", "Ignoring early venous congestion because the flap is 'robust' can convert a reversible pedicle problem into flap loss."],
        "deliberate_review_v184": "Reused the existing lining/support/cover principle and added subunit analysis, supratrochlear pedicle planning, airway goals and flap-compromise rescue."
    },
    "cc-v112-mgt-facial-plastics-trauma-le-fort-panfacial-trauma": {
        "concept_id": "v6-facial-plastics-trauma-le-fort-panfacial-trauma",
        "canonical_topic": "Le Fort / Panfacial Trauma",
        "prompt": "A patient with panfacial fractures has malocclusion, increased facial width, midface retrusion, bilateral orbital fractures, and no single obviously intact central facial reference. How do you establish the operative sequence, which stable reference points matter, and what associated findings must be controlled before definitive fixation?",
        "answer_text": "Begin with trauma priorities: secure the airway, control hemorrhage and address vision, intracranial injury and cervical-spine issues before definitive facial reconstruction. Thin-cut CT defines the fracture map, but ocular examination, dental occlusion and preinjury facial form determine the functional targets. Panfacial repair restores three-dimensional width, height, projection, orbital volume and occlusion from reliable reference points; it is not a collection of independent fracture repairs. Establish mandibular/maxillary occlusion when it is trustworthy, then rebuild stable vertical and horizontal buttresses using a bottom-up, top-down or combined sequence chosen from the intact skeleton. When the mandible or cranial frame is comminuted, select another reliable reference rather than forcing a memorized sequence. Restore zygomatic projection and orbital boundaries while repeatedly checking width and occlusion before locking fixation. Active orbital compartment syndrome, uncontrolled bleeding, CSF leak, unstable neurologic status or an unsecured airway takes priority over plating, and postoperative vision or occlusal change demands immediate reassessment.",
        "explanation": "The sequence is reference-point dependent. The chief-level task is to decide which part of the facial framework is reliable enough to rebuild the rest while preventing a small early error from propagating across the entire face.",
        "board_pearl": "In panfacial trauma, choose a stable reference and rebuild a three-dimensional framework; do not let a memorized top-down or bottom-up slogan replace anatomy.",
        "depth_layers_v184": {"foundation": "Restore occlusion, width, height, projection and orbital volume from facial buttresses.", "application": "Choose top-down versus bottom-up sequencing from the most reliable intact reference points.", "senior_decision": "Defer fixation for airway, hemorrhage, vision, CSF or neurologic emergencies and reassess any postoperative vision/occlusion change immediately."},
        "common_traps_v184": ["Rigidly using bottom-up repair when the mandible is an unreliable reference can propagate malposition through the midface.", "Achieving plate-to-plate reduction without repeated occlusal and width checks can leave a technically fixed but functionally deformed face."],
        "deliberate_review_v184": "Reused the existing width/height/projection/occlusion and buttress framework, adding trauma priorities, reference-point selection and failure checks."
    },
    "cc-v112-mgt-pediatric-otolaryngology-ankyloglossia-maxillary-frenulum": {
        "concept_id": "v6-pediatric-otolaryngology-ankyloglossia-maxillary-frenulum",
        "canonical_topic": "Ankyloglossia / Maxillary Frenulum",
        "prompt": "A thriving infant is referred for a prominent lingual frenulum after breastfeeding pain and latch difficulty, while an older child is referred for a visible maxillary frenulum without feeding, speech, or dental symptoms. How do you decide who needs intervention, what functional assessment matters, and what should prevent anatomy-only surgery?",
        "answer_text": "Treat demonstrated functional impairment, not the appearance of a frenulum. For the infant, obtain a skilled feeding and lactation assessment that examines latch, milk transfer, maternal pain, weight trajectory and whether positioning or other feeding mechanics explain the problem. Tongue mobility should be interpreted in that functional context; an anatomy score alone should not dictate frenotomy. When clinically significant breastfeeding dysfunction persists despite appropriate support and restriction is plausibly causal, frenotomy can be considered after shared decision-making about expected benefit, bleeding, pain and the possibility that symptoms may not fully resolve. In older children, speech concerns require appropriate speech assessment and dental/orthodontic concerns should be defined before surgery. An asymptomatic maxillary frenulum is not an operative indication simply because it is visually prominent. If a procedure is chosen, protect adjacent salivary ducts and tongue musculature and select simple release versus formal frenuloplasty according to age, scar/restriction and functional goal.",
        "explanation": "The evidence-sensitive distinction is anatomy versus function. Feeding, speech and dental problems have different evaluators and different thresholds, so a visible frenulum cannot serve as a universal surgical diagnosis.",
        "board_pearl": "A frenulum is anatomy; an indication requires a functional problem that the proposed release can plausibly improve.",
        "depth_layers_v184": {"foundation": "Separate visible restriction from clinically meaningful feeding, speech or dental dysfunction.", "application": "Use lactation, speech or dental assessment appropriate to the complaint before surgery.", "senior_decision": "Operate selectively after supportive measures and shared decision-making; avoid prophylactic anatomy-only release."},
        "common_traps_v184": ["Using an anatomy score as the sole indication for frenotomy ignores feeding mechanics and expected benefit.", "Treating an asymptomatic maxillary frenulum prophylactically creates procedural risk without a defined functional target."],
        "deliberate_review_v184": "Reused the existing function-not-photograph principle and added age-specific evaluation, shared decision-making and operative anatomy."
    },
    "cc-v112-rec-facial-plastics-trauma-structured-facial-trauma-examination": {
        "concept_id": "v6-facial-plastics-trauma-structured-facial-trauma-examination",
        "canonical_topic": "Structured Facial Trauma Examination",
        "prompt": "A polytrauma patient has extensive facial swelling and a dramatic CT fracture pattern. Before deciding which fractures to repair, what structured bedside examination must be completed, which functional findings outrank the fracture labels, and what changes require immediate escalation?",
        "answer_text": "Start with airway, hemorrhage and neurologic stabilization, then document vision before swelling and interventions obscure the baseline. Assess visual acuity, pupils and afferent defect, extraocular movement, globe position and pain; an acute visual deficit with proptosis, tense orbit or afferent pupillary defect is an orbital-compartment emergency. Examine occlusion and dental stability, trismus, facial width and zygomatic projection, nasal/NOE mobility and canthal position, facial sensation and facial nerve function. Look for malocclusion, mandibular instability, telecanthus, CSF rhinorrhea/otorrhea and soft-tissue injuries involving lids, lacrimal system, parotid duct or facial nerve. Thin-cut CT then answers anatomic questions raised by the functional examination rather than replacing it. Repair is prioritized by threatened function and meaningful structural deformity. New vision loss, uncontrolled hemorrhage, worsening airway, CSF leak with intracranial concern or an unstable globe/brain injury requires urgent specialty escalation before routine fracture sequencing.",
        "explanation": "A structured examination prevents dramatic imaging from eclipsing time-sensitive functional emergencies. Vision and occlusion are particularly high-value baselines because both can change during treatment.",
        "board_pearl": "In facial trauma, read the patient before the CT: vision, airway and occlusion can change management faster than a fracture name.",
        "depth_layers_v184": {"foundation": "Examine vision, airway, occlusion, canthi, facial form, sensation, nerve function and CSF signs systematically.", "application": "Use CT to localize abnormalities identified by the functional examination.", "senior_decision": "Escalate orbital-compartment, hemorrhagic, airway, intracranial and globe emergencies before routine fixation."},
        "common_traps_v184": ["Skipping a documented preoperative visual exam makes postoperative visual deterioration harder to detect and defend.", "Letting a complex CT dominate attention can delay treatment of a simple but time-critical orbital-compartment syndrome."],
        "deliberate_review_v184": "Reused the existing vision/airway/occlusion framework and added a reproducible bedside sequence, CT role and emergency thresholds."
    },
    "cc-v112-mgt-facial-plastics-trauma-cervicofacial-flap": {
        "concept_id": "v6-facial-plastics-trauma-cervicofacial-flap",
        "canonical_topic": "Cervicofacial Flap",
        "prompt": "After oncologic resection, a patient has a large lateral cheek defect approaching the lower eyelid with intact deep structures and adequate adjacent cervical skin laxity. How do you decide whether a cervicofacial flap is appropriate, design the tension vectors, and recognize when local tissue is no longer the safest reconstructive choice?",
        "answer_text": "First define defect size, depth, exposed structures, prior radiation or surgery, lower-eyelid involvement and the amount/quality of adjacent lax tissue. A cervicofacial advancement-rotation flap is useful when broad cheek and cervical skin can be recruited to provide good color and texture match without excessive tension at a free margin. Design a wide flap and mobilize enough tissue so closure tension is distributed over the flap rather than concentrated at the defect. The critical vector near the lower eyelid should be lateral or superiorly supported rather than inferior, because downward tension promotes ectropion. Elevate in a plane that preserves reliable vascularity and add deep suspension when needed to unload the lid. Prior radiation, very deep composite loss, exposed critical structures, insufficient laxity or a defect that would require dangerous tension should move reconstruction toward regional or free tissue rather than heroic local advancement. Postoperative progressive duskiness, hematoma, venous congestion or new ectropion requires early evaluation of perfusion and tension.",
        "explanation": "Cervicofacial flaps succeed by distributing tension through a broad recruitment field. The most common conceptual error is focusing on skin match while ignoring free-margin vector and tissue quality.",
        "board_pearl": "For a cheek flap near the eye, the reconstruction is only successful if the eyelid remains where it started.",
        "depth_layers_v184": {"foundation": "Match broad adjacent cheek/cervical skin to appropriate lateral facial defects.", "application": "Design vascularity-preserving mobilization and tension vectors that protect the lower eyelid.", "senior_decision": "Escalate to regional/free tissue when radiation, depth, exposed structures or required tension make local recruitment unreliable."},
        "common_traps_v184": ["Closing a cheek defect under an inferior eyelid vector can create ectropion despite complete wound closure.", "Persisting with local tissue in an irradiated or deep composite defect can trade a simpler operation for predictable wound failure."],
        "deliberate_review_v184": "Reused the existing broad tissue recruitment concept and added free-margin vector, tissue-quality selection and postoperative perfusion/tension rescue."
    },
    "cc-v112-rec-facial-plastics-trauma-septal-perforation": {
        "concept_id": "v6-facial-plastics-trauma-septal-perforation",
        "canonical_topic": "Septal Perforation",
        "prompt": "A patient presents with crusting, intermittent epistaxis, whistling and obstruction from an anterior septal perforation, but the surrounding mucosa looks irregular and the patient denies prior septal surgery. What evaluation is required before offering repair, which etiologies must be excluded, and what determines observation, button placement, or operative closure?",
        "answer_text": "Document perforation size, anterior-posterior location, residual L-strut/support, crusting, bleeding and the quality of surrounding mucosa. The absence of a clear iatrogenic history should trigger an etiologic evaluation rather than an assumption of trauma: ask about intranasal drug or spray injury, autoimmune/granulomatous disease, infection and neoplasm, and pursue targeted laboratory testing, imaging or biopsy when the history or mucosal appearance is atypical. Stabilize destructive inflammatory or infectious disease before considering closure. Asymptomatic stable perforations may need no intervention; symptomatic patients usually begin with humidification, saline, emollient care and avoidance of manipulation. A septal button is reasonable for selected symptomatic patients who do not want or are poor candidates for repair. Operative closure depends on symptoms, size, tissue quality, etiology and availability of tension-free vascularized mucosa, usually with an interposition graft while preserving support. Active destructive disease, poor mucosa or excessive closure tension predicts failure and should defer surgery.",
        "explanation": "Septal perforation is a diagnosis plus an etiology. Surgery treats a stable defect; it does not treat active vasculitis, infection, neoplasm or ongoing chemical injury.",
        "board_pearl": "Before repairing a septal hole, prove that the disease creating the hole has stopped.",
        "depth_layers_v184": {"foundation": "Understand airflow symptoms, size/location and support implications.", "application": "Investigate autoimmune, infectious, neoplastic, drug-related and iatrogenic causes when history is atypical.", "senior_decision": "Choose observation, prosthesis or tension-free vascularized repair only after the underlying process is controlled."},
        "common_traps_v184": ["Automatically labeling a perforation iatrogenic can miss GPA, infection or malignancy.", "Attempting closure in actively inflamed or poorly vascularized mucosa produces failure regardless of graft choice."],
        "deliberate_review_v184": "Reused the existing size/location and etiologic workup core, adding destructive-disease exclusion, nonsurgical options and repair-selection criteria."
    },
    "cc-v112-rec-head-neck-oncology-base-of-tongue-scc": {
        "concept_id": "v6-head-neck-oncology-base-of-tongue-scc",
        "canonical_topic": "Base of Tongue SCC",
        "prompt": "A patient presents with an HPV-associated level II neck node and subtle asymmetry of the lingual tonsil/base of tongue without an obvious oral cavity primary. How do you establish and stage the primary, choose between transoral surgery and radiation-based treatment, and what anatomic or functional findings should change the plan?",
        "answer_text": "Treat this as an oropharyngeal cancer problem, not as an isolated neck mass. Complete flexible endoscopic examination and contrast cross-sectional imaging, obtain tissue diagnosis with appropriate HPV/p16 characterization, and evaluate nodal and distant disease according to stage and risk. If the primary remains occult, directed examination under anesthesia with tonsillar and lingual-tonsil evaluation may localize a small tumor. Treatment selection depends on tumor extent, nodal burden, exposure, anticipated margins and expected swallowing toxicity. Transoral resection is reasonable only when exposure permits an oncologically complete resection with acceptable functional cost; the surgeon must understand the relationship of the deep tongue-base resection to the lingual artery and neurovascular structures. Extensive deep invasion, poor exposure, inability to obtain adequate margins without major morbidity, or a disease pattern better served by definitive radiation/chemoradiation should redirect treatment. Neck management and adjuvant therapy are determined by pathology and stage rather than by the technical success of removing the primary alone.",
        "explanation": "Base-of-tongue SCC commonly presents through nodal disease, and modern treatment is a comparison of equivalent oncologic strategies with different functional and adjuvant consequences. Exposure and margin feasibility are central to surgical selection.",
        "board_pearl": "A transoral base-of-tongue operation is attractive only if it can achieve margins without converting the patient into trimodality therapy for no functional gain.",
        "depth_layers_v184": {"foundation": "Localize BOT SCC as oropharyngeal disease and recognize HPV-associated nodal presentation.", "application": "Stage with endoscopy/imaging/tissue and determine transoral exposure, margin feasibility and swallow consequences.", "senior_decision": "Choose surgery versus radiation-based therapy by total oncologic and functional burden, including the likelihood of adjuvant treatment."},
        "common_traps_v184": ["Treating the metastatic neck node without completing primary-site localization and staging misses the actual oropharyngeal disease plan.", "Choosing transoral surgery solely because the tumor is technically reachable can create unnecessary trimodality toxicity if adverse pathology is predictable."],
        "deliberate_review_v184": "Reused the existing exposure/stage/swallow principle and added HPV-associated presentation, occult-primary workup, lingual-artery risk and multimodality tradeoffs."
    },
    "cc-v112-rec-laryngology-voice-swallowing-injection-laryngoplasty": {
        "concept_id": "v6-laryngology-voice-swallowing-injection-laryngoplasty",
        "canonical_topic": "Injection Laryngoplasty",
        "prompt": "A patient develops unilateral vocal-fold paralysis after thyroid surgery with breathy dysphonia, a glottic gap and aspiration symptoms, but meaningful neural recovery remains possible. How do you decide whether to inject, select material and route, place the injectate safely, and recognize technical failures or airway complications?",
        "answer_text": "Confirm the side and mechanism of immobility, characterize the glottic gap and vertical level, assess swallowing/aspiration and estimate recovery potential before choosing augmentation. Injection laryngoplasty improves closure but does not restore nerve movement, so a temporary material is attractive when recovery is plausible while a more durable strategy may be reasonable when prognosis and goals justify it. Choose office versus operating-room injection according to patient tolerance, airway, visualization and need for concurrent procedures. Place the material in the appropriate lateral/paraglottic target to medialize the membranous fold while avoiding superficial injection into the vibratory cover; titrate rather than overcorrect blindly. Reassess voice, closure and swallowing after injection. Superficial material, marked overinjection, worsening stridor, significant edema, hematoma or respiratory distress requires prompt evaluation; airway compromise is an emergency. Persistent posterior gap or vertical mismatch despite adequate bulk should trigger reconsideration of framework surgery, arytenoid adduction or reinnervation rather than repeated indiscriminate injection.",
        "explanation": "Injection is a geometry-and-prognosis procedure. The useful question is not simply whether a fold is weak, but whether temporary medialization can close the actual gap while preserving future definitive options.",
        "board_pearl": "Injection adds bulk; it does not correct every posterior gap, vertical mismatch or denervation problem.",
        "depth_layers_v184": {"foundation": "Understand temporary versus durable augmentation and paraglottic medialization.", "application": "Match material and office/OR route to recovery prognosis, gap geometry, aspiration and tolerance.", "senior_decision": "Recognize superficial/overinjection and airway complications, and escalate persistent posterior or vertical mismatch to a different operation."},
        "common_traps_v184": ["Repeatedly adding volume to a posterior gap or vertical mismatch can worsen stiffness without correcting the geometry.", "Superficial injection into the vibratory cover can create dysphonia even when medialization appears adequate."],
        "deliberate_review_v184": "Reused the existing side/gap/prognosis/material/route framework and added aspiration goals, paraglottic target, complication rescue and escalation to framework/reinnervation options."
    },
}


def apply_concept_check_task_alignment_v184(checks, deep_modules, v6_item_id):
    by_id = {str(q.get("id") or ""): q for q in checks or []}
    repaired, missing, link_mismatch = [], [], []
    for qid, payload in COHORT.items():
        q = by_id.get(qid)
        if q is None:
            missing.append(qid)
            continue
        module = _find_module(q, deep_modules, v6_item_id)
        domain = str(q.get("domain") or "")
        resolved_topic = str(module.get("topic") or "") if module else ""
        resolved_cid = v6_item_id(domain, resolved_topic) if module and domain else None
        if not module or resolved_topic != payload["canonical_topic"] or resolved_cid != payload["concept_id"] or q.get("concept_id") != resolved_cid:
            link_mismatch.append(qid)
            continue
        q["prompt"] = payload["prompt"]
        q["answer_text"] = payload["answer_text"]
        q["explanation"] = payload["explanation"]
        q["board_pearl"] = payload["board_pearl"]
        q["depth_layers_v184"] = payload["depth_layers_v184"]
        q["common_traps_v184"] = payload["common_traps_v184"]
        q["deliberate_review_v184"] = payload["deliberate_review_v184"]
        q["task_alignment_v184"] = True
        q.pop("choices", None); q.pop("answer", None); q.pop("why_wrong", None)
        repaired.append(qid)
    return {"repaired": repaired, "missing": missing, "link_mismatch": link_mismatch}

__all__ = ["COHORT", "apply_concept_check_task_alignment_v184"]
