"""v20.18 — deepen the exact-live Sinonasal Malignancy Concept Check on the validated v20.17 lineage."""
from concept_check_board_repair_v177 import _find_module

QIDS = (
    "cc-v112-rec-rhinology-allergy-skull-base-sinonasal-malignancy",
)
CID = "v6-rhinology-allergy-skull-base-sinonasal-malignancy"
TOPIC = "Sinonasal Malignancy"

SOURCE_REFS_V218 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus; split Part 2 copy Drive id 1_PCclrEVhvetv14xawyW2LBlLeqKMLW- plus the connected split-volume set cross-referenced 2026-09-08 for sinonasal oncology, anterior skull-base, orbital, pterygopalatine/infratemporal and endoscopic/open operative anatomy.","role":"durable operative foundation: compartmental sinonasal anatomy, skull-base/orbital barriers, neurovascular danger zones, margin-oriented resection and reconstruction"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52; sinonasal neoplasm and skull-base oncology framework cross-referenced 2026-09-08.","role":"resident/board framework: presentation, imaging/biopsy, histology, staging, surgical and adjuvant treatment principles"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; nasal/paranasal tumor and skull-base operative principles cross-referenced 2026-09-08.","role":"operative cross-check: sinonasal tumor extent, orbit/skull-base relationships, cranial neuropathy and surgical morbidity"},
    {"type":"guideline","citation":"Resteghini C, et al. Sinonasal malignancy: ESMO–EURACAN Clinical Practice Guideline for diagnosis, treatment and follow-up. ESMO Open. 2025;10(2):104121. PMID: 39986703.","role":"current rare-cancer guideline: histology-aware surgery/RT/systemic treatment, selective neoadjuvant chemotherapy for potentially chemosensitive high-grade locally advanced tumors when local therapy would carry very high morbidity, recurrence/metastatic algorithms and surveillance"},
    {"type":"systematic_review","citation":"Survival, efficacy and organ preservation outcomes of induction chemotherapy in sinonasal squamous cell carcinoma: a systematic review and meta-analysis. Acta Otolaryngol. 2025. PMID: 40611588.","role":"current SNSCC evidence: pooled partial response 57%, 2-year OS 78%, orbital preservation 83%; supports response-adapted consideration while explicitly acknowledging need for higher-quality standardized trials"},
    {"type":"systematic_review","citation":"Tang A, et al. The role of induction chemotherapy for orbital invasion in sinonasal malignancies: a systematic review. Int Forum Allergy Rhinol. 2024;14(7):1226-1239. PMID: 38829173.","role":"orbital-preservation evidence boundary: selected responders may avoid exenteration, but evidence is heterogeneous and histology-dependent"},
    {"type":"fda_boundary","citation":"U.S. FDA. June 12, 2025 pembrolizumab perioperative approval for adults with resectable locally advanced HNSCC and PD-L1 CPS >=1 based on KEYNOTE-689. This is recorded as a regulatory boundary, not as a sinonasal-specific standard; rare sinonasal histologies and site eligibility/evidence must be verified before extrapolation.","role":"prevents overgeneralizing a contemporary generic HNSCC FDA indication to every sinonasal malignancy"},
]

PROMPT = """A 58-year-old patient presents with progressive unilateral nasal obstruction, recurrent epistaxis, facial pressure and new diplopia. Nasal endoscopy shows a friable superior nasal-cavity mass; MRI demonstrates ethmoid/superior nasal-cavity disease abutting the anterior skull base with focal periorbital involvement, while CT is being reviewed for bone destruction. As the senior resident planning biopsy and definitive management, explain how you would work up and localize a suspected sinonasal malignancy, identify the orbit/skull-base/carotid and hemorrhage danger zones, decide whether an endoscopic, open, combined, radiation-based or induction-response-adapted strategy is appropriate, and show how histology changes treatment. Include explicit rescue/bailout decisions when the orbit, dura, optic apparatus, cavernous/skull-base region or major vessels make the planned operation unsafe."""

ANSWER = """Foundation — treat “sinonasal malignancy” as an anatomic problem plus a histologic family, not as one generic cancer. Persistent unilateral obstruction, epistaxis, facial numbness or pain, diplopia, proptosis, cranial neuropathy, a unilateral middle-meatal mass, or unilateral sinus opacification with destructive or infiltrative features should lower the threshold for neoplasm. Endoscopy defines the mucosal epicenter and supplies tissue, but cross-sectional imaging defines dangerous deep extent. Contrast-enhanced MRI is particularly important for orbit, dura, brain, perineural spread, cavernous/skull-base soft tissue and marrow; thin-cut CT complements MRI for bone remodeling or destruction, lamina papyracea, cribriform/fovea, frontal recess and pterygoid/maxillary architecture. Image the neck and chest/systemic sites according to histology and stage. Biopsy should be planned, not reflexive: review vascularity and skull-base relationships first, correct reversible bleeding risk, choose a site that will not create an avoidable CSF leak or orbital injury, and obtain enough tissue for expert classification and molecular testing when indicated.

Anatomic map — the roof is not a flat plate. The cribriform plate, lateral lamella and fovea ethmoidalis create a variable anterior skull-base boundary; the lateral lamella can be exceptionally thin. Superior/posterior disease can involve dura, olfactory bulbs, planum or sphenoid and intracranial structures. The medial orbital boundary includes lamina papyracea and periorbita, but oncologic orbital assessment must distinguish bone or periorbita contact from invasion of extraconal fat, extraocular muscles, globe, intraconal contents, optic nerve or apex. Posterior disease can enter the pterygopalatine and infratemporal fossae, follow V2 and other nerves, reach the vidian region or foramen rotundum, and approach the cavernous sinus and petrous/paraclival internal carotid artery. The sphenopalatine/internal-maxillary arterial system can generate major hemorrhage. These compartments determine both oncologic margins and whether the next millimeter of dissection is routine, reconstructive, vascular, neuro-ophthalmic or potentially catastrophic.

Workup and histology — first establish histology because sinonasal squamous cell carcinoma (SNSCC), intestinal and nonintestinal adenocarcinoma, olfactory neuroblastoma (ONB), sinonasal undifferentiated carcinoma (SNUC), neuroendocrine carcinoma, adenoid cystic carcinoma, NUT carcinoma, SWI/SNF-deficient tumors and other entities do not share one treatment algorithm. Ask about occupational wood/leather-dust exposure where relevant, smoking, speed of progression, cranial neuropathy and prior radiation. Expert pathology review matters because poorly differentiated sinonasal tumors can be difficult to classify and classification changes systemic options and expected chemosensitivity. Stage with the disease-appropriate system and multidisciplinary review; do not let shorthand such as “T4” substitute for describing exactly which orbit, skull base, cranial nerve, skin, palate, pterygoid, brain or vascular structures are involved.

Margin-oriented surgery — the operative question is not “Can I reach it endoscopically?” but “Can I achieve oncologically sound resection with controlled margins and acceptable morbidity?” Endoscopic endonasal resection is appropriate for many selected tumors, including anterior skull-base resections, when the tumor can be compartmentally exposed, critical margins can be assessed, vascular control is available and reconstruction is reliable. Open craniofacial, maxillectomy, transfacial or combined approaches remain appropriate when lateral/anterior extension, skin or soft tissue, extensive orbital involvement, vascular encasement, brain involvement or margin geometry cannot be safely controlled endoscopically. Planned compartmental endoscopic disassembly can preserve orientation and margins; blind intratumoral debulking to discover boundaries does not.

Orbit decision — reject the binary “any orbital involvement equals exenteration.” Bone or limited periorbital involvement does not automatically require removal of a functional eye. Define whether disease stops at bone/periorbita or enters extraconal fat, extraocular muscles, globe, intraconal contents, optic nerve or apex; integrate vision and whether a negative or otherwise oncologically controlled margin is achievable. Selected orbit-invading, potentially chemosensitive tumors may be candidates for neoadjuvant treatment and response-adapted organ preservation in an experienced multidisciplinary program. Contemporary systematic reviews report substantial response and orbital-preservation rates in selected cohorts, but the evidence is heterogeneous and largely nonrandomized; induction chemotherapy is therefore selective, not a universal substitute for resection. If preservation leaves gross disease on the optic nerve or apex or destroys oncologic control, preservation is not success.

Skull base and dura — tumor at the cribriform or fovea requires deliberate superior-margin planning. Dural involvement can require margin-directed dural resection with neurosurgical collaboration and multilayer skull-base reconstruction. A controlled CSF leak created as part of planned oncologic resection is fundamentally different from an unrecognized tear during blind superior dissection. Once the skull-base plane is no longer identified, stop curettage, reorient with fixed anatomy and navigation when useful, obtain appropriate exposure, and convert to a combined or staged strategy if safe margins cannot be obtained. Intracranial extension, optic-chiasm proximity and carotid or cavernous involvement may shift treatment toward chemoradiation, advanced RT including proton techniques when appropriate, induction-response assessment or unresectable-disease pathways rather than heroic surgery with unacceptable neurologic morbidity.

Hemorrhage and carotid bailout — posterior tumor can obscure the sphenopalatine/internal-maxillary system and, at the deepest skull base, approach the petrous/paraclival internal carotid. Preoperative imaging should identify vessel displacement, narrowing, encasement and prior-treatment effects. Major bleeding is not managed by blind clamping in a tumor-filled pterygopalatine or sphenoid field. Pack or compress to regain control and visualization when appropriate, call vascular/interventional support early, maintain resuscitation and convert exposure if needed. If carotid injury is suspected, prioritize immediate hemorrhage control and cerebral perfusion; do not repeatedly probe the defect. A tumor that cannot be separated safely from a critical carotid should trigger a planned resectability or vascular strategy before uncontrolled injury.

Histology-specific application — for resectable SNSCC, surgery followed by risk-adapted radiotherapy with or without systemic therapy remains a common framework. Induction chemotherapy can be considered in selected locally advanced SNSCC when response may guide organ preservation or avoid extremely morbid local therapy. High-grade poorly differentiated tumors such as SNUC can be chemosensitive, and response to induction has been used in experienced centers to select definitive chemoradiation versus surgery, but that is not the same evidence base as routine SNSCC management. ONB management integrates grade and stage, surgery when resectable and radiotherapy for appropriate disease; neck management depends on nodal status, stage/grade and institutional strategy rather than copying SCC rules. Adenocarcinoma, adenoid cystic carcinoma, NUT and molecularly defined tumors require their own pathology-driven discussions. Current ESMO–EURACAN guidance supports considering neoadjuvant chemotherapy in potentially chemosensitive high-grade or poorly differentiated locally advanced tumors when surgery or radiotherapy would carry very high morbidity, including significant orbital invasion or proximity to the chiasm. That recommendation is selective and evidence-graded, not an instruction to induce every advanced sinonasal cancer.

Neck, adjuvant and regulatory boundaries — clinically involved neck disease should be treated according to histology and definitive modality. Elective neck treatment is not identical across all sinonasal tumors; risk varies with primary site, T category, histology and grade. Postoperative RT is common for many advanced or high-risk resected cancers, while concurrent chemotherapy is added selectively based on histology and risk rather than because “head and neck cancer gets cisplatin.” Rare sinonasal tumors are underrepresented in randomized trials that define generic mucosal HNSCC standards. The June 12, 2025 FDA approval of perioperative pembrolizumab for selected PD-L1-positive resectable locally advanced HNSCC should therefore not be memorized as a sinonasal-specific mandate; verify site, histology and evidence applicability, and use tissue-agnostic indications only when their exact criteria are met.

Senior decision — before committing to resection, write down the intended margin surfaces: skull base or dura, orbit, posterior pterygopalatine/infratemporal boundary, maxillary/palatal or frontal boundary, and every neurovascular interface. If one margin cannot be made safe or meaningful, change the plan before incision. If the tumor is highly chemosensitive and an up-front operation would require exenteration, optic sacrifice, extremely morbid skull-base resection or impossible posterior margins, multidisciplinary induction therapy with early imaging response assessment may preserve function in responders while identifying nonresponders who need a different definitive strategy. A dramatic response does not erase the pretreatment disease map; definitive local therapy must still address original extent according to histology and protocol.

Rescue and bailout synthesis — orbit: stop blind periorbital dissection when anatomy is lost; define the compartment and involve ophthalmology when globe or optic structures are threatened. Skull base: if the superior plane is uncertain, stop curettage, reorient and obtain controlled dural exposure rather than converting occult tumor or a thin lateral lamella into uncontrolled intracranial injury. CSF leak: recognize it, protect neural tissue and perform planned multilayer repair rather than hiding the defect under packing. Hemorrhage: regain control with compression, packing and exposure; never chase a posterior vessel blindly. Carotid or cavernous region: stop when safe separation is not demonstrable and move to a planned vascular/oncologic alternative. Optic apparatus: preservation is worthwhile only when oncologically and functionally meaningful. The senior skill is not maximal technical aggression; it is knowing when anatomy, histology, response and margin feasibility support surgery, when combined expertise changes the risk, and when a controlled change in strategy prevents permanent blindness, stroke, catastrophic hemorrhage, CSF catastrophe or a knowingly inadequate cancer operation."""

TRAPS = [
    "Treating all sinonasal malignancies as one SCC-like disease instead of establishing histology before choosing surgery, radiation, systemic therapy and neck management.",
    "Biopsying a vascular or skull-base-adjacent mass before reviewing imaging and creating an avoidable hemorrhage or CSF-leak problem.",
    "Assuming CT alone excludes dural, perineural, orbital-apex or cavernous/skull-base soft-tissue extension when MRI is needed.",
    "Calling any contact with the lamina papyracea or periorbita an indication for orbital exenteration.",
    "Preserving an eye when gross disease remains at the optic nerve or apex and mistaking organ preservation for oncologic success.",
    "Using induction chemotherapy for every advanced sinonasal cancer instead of selecting potentially chemosensitive, high-morbidity cases and reassessing response early.",
    "Interpreting retrospective or highly selected orbital-preservation series as randomized proof that induction therapy is superior to surgery.",
    "Choosing an endoscopic approach because the tumor is technically reachable even when posterior, lateral or vascular margins cannot be controlled.",
    "Equating planned compartmental endoscopic disassembly with uncontrolled intratumoral debulking and losing margin orientation.",
    "Blindly curetting superior ethmoid or skull-base tumor when the cribriform, lateral lamella or dura is no longer identified.",
    "Blindly clamping posterior tumor-bed hemorrhage in the pterygopalatine, infratemporal or sphenoid region without identifying vessel and carotid relationships.",
    "Continuing dissection against suspected carotid or cavernous involvement because the original plan called for resection instead of changing strategy.",
    "Applying elective-neck treatment uniformly across SNSCC, ONB, SNUC, adenocarcinoma and other rare histologies despite different nodal risks.",
    "Applying a generic HNSCC FDA immunotherapy approval automatically to every sinonasal histology without verifying trial/site applicability or a tumor-agnostic indication.",
    "Forgetting that a major induction response does not erase pretreatment extent when planning definitive local therapy.",
]

COHORT = {QIDS[0]: {
    "concept_id": CID,
    "canonical_topic": TOPIC,
    "prompt": PROMPT,
    "answer_text": ANSWER,
    "explanation": "Sinonasal malignancy decisions require histology plus a three-dimensional margin map: define orbit, skull base/dura, posterior neurovascular and carotid interfaces; select endoscopic/open/RT/induction strategies by controllable margins and morbidity; and stop before uncertain anatomy becomes blindness, stroke, hemorrhage or an inadequate cancer operation.",
    "board_pearl": "Do not equate orbital contact with exenteration or advanced stage with automatic induction chemotherapy. Histology, precise compartment invasion, response potential and whether a safe oncologic margin is achievable determine the plan.",
    "depth_layers_v218": {
        "foundation":"Histology-specific sinonasal cancer framework; MRI/CT roles; orbit, cribriform/fovea/dura, pterygopalatine/infratemporal, cavernous and carotid anatomy.",
        "application":"Biopsy planning, endoscopic versus open marginability, orbital-compartment assessment, histology-specific surgery/RT/systemic and neck decisions, selective induction-response strategy.",
        "senior_decision":"Predeclare critical margins, use combined skull-base/ophthalmic/vascular expertise when needed, and bail out of blind orbit/skull-base/posterior dissection before blindness, CSF injury, stroke or catastrophic hemorrhage."
    },
    "common_traps_v218": TRAPS,
    "deliberate_review_v218": "Promoted from the stale v20.17 Sinonasal Malignancy branch onto the newly validated v20.17 production lineage after concurrent Endoscopic Maxillary Antrostomy work occupied v20.17. This exact-live canonical is retained because it concentrates high-yield resident/board decisions and immediate OR danger zones: orbit preservation versus exenteration, anterior skull-base/dural control, posterior hemorrhage/carotid risk, margin-driven approach selection and histology-dependent induction/systemic therapy.",
    "source_refs_v218": SOURCE_REFS_V218,
    "evidence_distinction_v218": "Durable Cummings/Pasha/K.J. Lee anatomy and margin-oriented operative principles are preserved. Current ESMO–EURACAN 2025 guidance supports selective neoadjuvant chemotherapy for potentially chemosensitive high-grade locally advanced disease when local therapy would be highly morbid; 2024-2025 systematic reviews suggest meaningful response/orbit preservation in selected cohorts but remain heterogeneous and nonrandomized. Generic HNSCC FDA immunotherapy approvals are explicitly not treated as sinonasal-specific mandates.",
    "audit_profile_v218": "sinonasal_malignancy",
}}

def apply_concept_check_task_alignment_v218(checks, deep_modules, v6_item_id):
    by={str(q.get("id") or ""):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get("topic") or "") if m else ""; cid=v6_item_id(q.get("domain"),topic) if m and q.get("domain") else None
        persisted=q.get("concept_id")
        if m is None or topic!=p["canonical_topic"] or cid!=p["concept_id"] or (persisted is not None and persisted!=cid): link_mismatch.append(qid); continue
        q["concept_id"]=cid; q["canonical_topic"]=topic
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v218","common_traps_v218","deliberate_review_v218","source_refs_v218","evidence_distinction_v218","audit_profile_v218"): q[field]=p[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v218"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
