"""v18.8 — next high-priority live-canonical Concept Check depth cohort.

Selected from the validated V186 ranking after excluding the already-completed
v18.7 cohort. Exact canonical resolution is required before mutation. This pass
prioritizes unilateral/bilateral laryngeal immobility, posterior glottic fixation,
and skeletal OSA surgery with explicit physiology, operative tradeoffs, rescue,
and escalation thresholds.
"""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-laryngology-voice-swallowing-unilateral-vocal-fold-paralysis":{
"concept_id":"v6-laryngology-voice-swallowing-unilateral-vocal-fold-paralysis","canonical_topic":"Unilateral Vocal Fold Paralysis",
"prompt":"A 58-year-old develops a breathy weak voice and coughing with thin liquids after thyroid surgery. Flexible laryngoscopy shows a unilateral immobile vocal fold, but the operative note does not document nerve transection. How should you localize the lesion, evaluate swallowing and recovery potential, and choose observation, temporary injection, durable framework surgery, or reinnervation without committing too early to an irreversible strategy?",
"answer_text":"First confirm that the problem is truly neurogenic immobility rather than fixation and define the functional consequences. Document fold position, glottic gap, vertical level, contralateral motion, cough strength, airway symptoms, and signs of aspiration; obtain FEES or modified barium swallow when swallowing safety is uncertain or pulmonary consequences are present. The history should localize the likely nerve segment, but unexplained paralysis outside an obvious surgical injury requires imaging along the vagus and recurrent laryngeal nerve course according to laterality and clinical context. Laryngeal EMG can be useful selectively when prognosis or denervation status would materially change timing of treatment. If recovery remains plausible but dysphonia or aspiration is clinically important, temporary injection augmentation can restore glottic competence while preserving future options. Once paralysis is established and recovery is unlikely, durable treatment should match the geometry: medialization thyroplasty addresses glottic insufficiency, arytenoid adduction is valuable for persistent posterior gap or vertical height mismatch, and reinnervation can restore long-term tone and bulk in selected patients but develops over months and does not reliably restore normal purposeful motion. Progressive aspiration, recurrent pneumonia, inability to maintain nutrition, or severe occupational voice disability should accelerate treatment rather than forcing prolonged observation simply because spontaneous recovery is theoretically possible.",
"explanation":"The senior decision is to separate immediate glottic-closure needs from uncertain neural recovery and from the long-term mechanical or biologic deficit that remains once prognosis is clear.",
"board_pearl":"Temporary injection buys function while prognosis declares itself; permanent framework surgery should match the residual glottic geometry, not just the diagnosis label.",
"depth_layers_v188":{"foundation":"Confirm neurogenic immobility, localize the nerve, and assess voice/swallow consequences.","application":"Use temporary augmentation when recovery is uncertain but glottic insufficiency is clinically important.","senior_decision":"Choose durable thyroplasty, arytenoid adduction, and/or reinnervation according to posterior gap, height mismatch, timing, aspiration, and recovery probability."},
"common_traps_v188":["Calling every immobile fold an RLN paralysis without considering cricoarytenoid fixation can send the patient down the wrong treatment pathway.","Waiting many months for theoretical recovery despite recurrent aspiration pneumonia can convert a reversible glottic-competence problem into preventable pulmonary morbidity."],
"deliberate_review_v188":"Expanded a short UVFP summary into lesion localization, swallowing risk, prognostic timing, reversible bridging, and durable procedure selection based on glottic geometry."},
"cc-v112-rec-sleep-surgery-maxillomandibular-advancement":{
"concept_id":"v6-sleep-surgery-maxillomandibular-advancement","canonical_topic":"Maxillomandibular Advancement",
"prompt":"A 43-year-old with severe obstructive sleep apnea cannot tolerate PAP and has multilevel retropalatal and retroglossal collapse with maxillomandibular retrusion. He asks whether maxillomandibular advancement is simply a cosmetic jaw operation. How should you explain the airway mechanism, select an appropriate candidate, plan the skeletal movement, and counsel about the perioperative and long-term tradeoffs compared with soft-tissue or hypoglossal-nerve approaches?",
"answer_text":"Maxillomandibular advancement is a skeletal airway-enlarging operation, not merely an aesthetic procedure. Advancing the maxilla and mandible tensions and displaces the attached soft-tissue envelope—including tongue base, palate-related musculature, and lateral pharyngeal structures—anteriorly, which can enlarge the retropalatal and retroglossal airway simultaneously. Candidate assessment should integrate PSG severity and central-apnea burden, craniofacial anatomy, occlusion, dental health, nasal obstruction, prior surgery, BMI and medical risk, and the patient's tolerance for a major facial-skeletal procedure. Preoperative planning requires coordinated orthodontic/occlusal analysis and virtual or model-based skeletal planning so the airway goal does not create an unacceptable bite or facial imbalance. The operation generally offers powerful multilevel treatment, especially when skeletal deficiency is present or prior soft-tissue surgery has failed, but carries risks such as facial edema, temporary or persistent V2/V3 sensory change, malocclusion, infection, hardware problems, bleeding, relapse, TMJ symptoms, and airway issues during the immediate postoperative period. The senior decision compares durability and multilevel efficacy against invasiveness. A patient with anatomy well suited to a less invasive targeted therapy may reasonably choose that first, whereas severe multilevel collapse with craniofacial restriction may make MMA the more comprehensive strategy. Objective postoperative sleep testing is still required because a technically successful advancement does not guarantee physiologic cure.",
"explanation":"MMA treats the skeletal framework that constrains several pharyngeal levels at once, so its value is greatest when the patient's collapse pattern and craniofacial anatomy match that mechanism.",
"board_pearl":"Think of MMA as multilevel airway framework surgery: the occlusion and facial skeleton are part of the airway plan, not collateral details.",
"depth_layers_v188":{"foundation":"Understand how maxillary and mandibular advancement enlarges retropalatal and retroglossal airway dimensions.","application":"Select patients using PSG, collapse pattern, craniofacial anatomy, occlusion, and prior-treatment history and plan the movement with dental/skeletal precision.","senior_decision":"Balance high multilevel efficacy against major-surgery morbidity and choose MMA when the skeletal framework is a dominant, durable treatment target."},
"common_traps_v188":["Choosing MMA solely from AHI without evaluating occlusion, craniofacial anatomy, central events, and collapse pattern turns a physiologic operation into a generic escalation step.","Assuming a large skeletal advancement guarantees cure can miss residual positional, weight-related, or nonobstructive disease that still requires objective postoperative testing."],
"deliberate_review_v188":"Expanded a skeletal-advancement description into airway mechanism, candidate selection, occlusal planning, complication counseling, and procedure-selection tradeoffs."},
"cc-v112-rec-laryngology-voice-swallowing-bilateral-vocal-fold-immobility":{
"concept_id":"v6-laryngology-voice-swallowing-bilateral-vocal-fold-immobility","canonical_topic":"Bilateral Vocal Fold Immobility",
"prompt":"A 67-year-old has progressive inspiratory stridor after a prolonged intubation. Both vocal folds remain near the midline on flexible laryngoscopy. How should you distinguish bilateral neurogenic paralysis from posterior glottic scar or cricoarytenoid fixation, stabilize the airway, and decide among observation, tracheostomy, posterior cordotomy, arytenoidectomy, or other reconstruction while protecting voice and swallowing?",
"answer_text":"Bilateral immobility is a physical finding, not an etiologic diagnosis. First assess airway stability—work of breathing, stridor at rest, oxygenation, secretion handling, trajectory, and ability to lie flat. A deteriorating airway requires controlled escalation rather than waiting for the diagnostic workup to finish. History helps separate postsurgical neural injury from post-intubation posterior glottic stenosis, but office motion alone may not distinguish denervation from mechanical fixation. Direct laryngoscopy with arytenoid palpation is important when fixation is plausible, and laryngeal EMG can add prognostic or localization information selectively for suspected neurogenic disease. If recent bilateral neural injury may recover and the airway is safe, observation or temporary airway support may preserve future function. Tracheostomy provides a reversible airway when immediate protection is needed or when recovery remains uncertain. Posterior cordotomy and partial arytenoidectomy enlarge the posterior glottis but deliberately trade voice quality and some glottic competence for airway; they are most appropriate when a durable larger airway is needed and the patient accepts that tradeoff. Mechanical posterior glottic stenosis may instead require scar release, dilation, flap/graft reconstruction, or other fixation-directed treatment. The senior decision is to identify the mechanism before sacrificing tissue and to choose the least irreversible intervention that reliably solves the airway problem for the expected recovery timeline.",
"explanation":"Neurogenic paralysis and mechanical fixation can look identical on flexible examination, yet the correct operation and the likelihood of recovery are very different.",
"board_pearl":"Before widening a bilaterally immobile glottis, decide whether the arytenoids cannot move because the nerves are weak or because the joints are physically fixed.",
"depth_layers_v188":{"foundation":"Recognize bilateral immobility as an airway problem with neurogenic and mechanical causes.","application":"Use history, direct palpation, and selective EMG to distinguish paralysis from fixation while securing an unstable airway.","senior_decision":"Choose reversible airway support versus irreversible glottic-widening or scar-reconstruction procedures according to mechanism, recovery probability, and voice/swallow priorities."},
"common_traps_v188":["Assuming postoperative bilateral immobility is automatically bilateral RLN paralysis can miss posterior glottic stenosis and lead to the wrong destructive airway procedure.","Performing cordotomy before clarifying a potentially recoverable neural injury may create permanent voice and swallowing morbidity for a temporary airway problem."],
"deliberate_review_v188":"Expanded recognition of bilateral immobility into airway triage, paralysis-versus-fixation localization, recovery timing, and explicit airway/voice/swallow procedure tradeoffs."},
"cc-v112-rec-laryngology-voice-swallowing-posterior-glottic-stenosis-arytenoid-fixation":{
"concept_id":"v6-laryngology-voice-swallowing-posterior-glottic-stenosis-arytenoid-fixation","canonical_topic":"Posterior Glottic Stenosis / Arytenoid Fixation",
"prompt":"A patient has persistent dyspnea and bilateral vocal-fold immobility after prolonged intubation. Office laryngoscopy cannot determine whether this is neural paralysis or posterior glottic fixation. What operative findings establish posterior glottic stenosis, how should severity and cricoarytenoid mobility change treatment, and when should you escalate beyond dilation or simple scar division to flap, graft, or airway-widening reconstruction?",
"answer_text":"Posterior glottic stenosis results from interarytenoid/posterior commissure scarring that may progress from a mucosal scar bridge to fixation of one or both cricoarytenoid joints. The key diagnostic step when office examination is equivocal is direct laryngoscopy with careful visualization of the posterior commissure and palpation of each arytenoid. Preserved passive joint motion with a limited mucosal scar is fundamentally different from dense scar with cricoarytenoid ankylosis. Treatment should match the level of disease. Thin or limited scar may respond to precise scar division with adjunctive dilation and meticulous postoperative management. More advanced disease often needs strategies that prevent raw posterior surfaces from re-adhering, such as mucosal flap reconstruction, and severe fixation or framework loss may require grafting, staged reconstruction, posterior cricoid expansion, or selected glottic-widening procedures. Repeated endoscopic treatment that produces progressively shorter benefit is evidence that the scar biology or joint fixation is not being durably corrected. The surgeon must also account for the airway/voice/swallow triangle: aggressive posterior widening improves airflow but can worsen phonation and aspiration, whereas overly conservative scar release may leave a tracheostomy-dependent airway. The senior decision is to identify whether the limiting lesion is mucosal scar, joint fixation, or both and choose a reconstruction that creates durable separation and mobility rather than simply making the lumen look larger at the end of the case.",
"explanation":"Posterior glottic stenosis is a spectrum from scar bridge to joint fixation, and the operation should be driven by passive arytenoid mobility and the durability of prior treatments.",
"board_pearl":"Arytenoid palpation converts 'both folds do not move' into the clinically decisive question: is this a nerve problem, a scar problem, or an ankylosed-joint problem?",
"depth_layers_v188":{"foundation":"Recognize posterior commissure scar and distinguish it from neurogenic bilateral paralysis.","application":"Use direct visualization and arytenoid palpation to grade mucosal scar versus cricoarytenoid fixation and select scar-directed treatment.","senior_decision":"Escalate to flap, graft, framework expansion, or airway-widening reconstruction when fixation or recurrent scar makes simple division predictably nondurable."},
"common_traps_v188":["Treating an ankylosed cricoarytenoid joint with repeated mucosal scar division alone can produce technically successful cases with no durable functional airway gain.","Maximizing posterior glottic width without counseling about voice and aspiration can solve the spirometry problem while creating a new swallowing problem."],
"deliberate_review_v188":"Expanded a short fixation concept into operative diagnosis by arytenoid palpation, scar-versus-joint staging, durability thresholds, and reconstruction tradeoffs."}
}

def apply_concept_check_task_alignment_v188(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id)
        topic=str(module.get('topic') or '') if module else ''
        cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']:
            link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v188']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
