"""v20.17 — deepen the exact-live Sinonasal Malignancy Concept Check."""
from concept_check_board_repair_v177 import _find_module

QID = "cc-v112-rec-rhinology-allergy-skull-base-sinonasal-malignancy"
CID = "v6-rhinology-allergy-skull-base-sinonasal-malignancy"
TOPIC = "Sinonasal Malignancy"

SOURCE_REFS_V217 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus; compressed full 7e copy Drive id 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t and split volumes cross-referenced 2026-09-08 for sinonasal oncology, anterior skull-base, orbital, pterygopalatine/infratemporal and endoscopic/open operative anatomy.","role":"durable operative foundation: compartmental sinonasal anatomy, skull-base/orbital barriers, neurovascular danger zones, margin-oriented resection and reconstruction"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52; sinonasal neoplasm and skull-base oncology framework cross-referenced 2026-09-08.","role":"resident/board framework: presentation, imaging/biopsy, histology, staging, surgical and adjuvant treatment principles"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; nasal/paranasal tumor and skull-base operative principles cross-referenced 2026-09-08.","role":"operative cross-check: sinonasal tumor extent, orbit/skull-base relationships, cranial neuropathy and surgical morbidity"},
    {"type":"guideline","citation":"Sinonasal malignancy: ESMO–EURACAN Clinical Practice Guideline for diagnosis, treatment and follow-up. Ann Oncol. 2025. PMID: 39986703.","role":"current rare-cancer guideline: histology-aware surgery/RT/systemic treatment, selective neoadjuvant chemotherapy for potentially chemosensitive high-grade locally advanced tumors when local therapy would carry very high morbidity, recurrence/metastatic algorithms and surveillance"},
    {"type":"systematic_review","citation":"Survival, efficacy and organ preservation outcomes of induction chemotherapy in sinonasal squamous cell carcinoma: a systematic review and meta-analysis. 2025. PMID: 40611588.","role":"current SNSCC evidence: pooled partial response 57%, 2-year OS 78%, orbital preservation 83%; supports response-adapted consideration while explicitly acknowledging need for higher-quality standardized trials"},
    {"type":"systematic_review","citation":"The role of induction chemotherapy for orbital invasion in sinonasal malignancies: a systematic review. 2024. PMID: 38829173.","role":"orbital-preservation evidence boundary: high induction response and selected conversion from planned exenteration to preservation, but heterogeneous retrospective evidence and histology-dependent response"},
    {"type":"fda_boundary","citation":"U.S. FDA. June 12, 2025 pembrolizumab perioperative approval for resectable locally advanced HNSCC with PD-L1 CPS >=1, based on KEYNOTE-689. This is recorded as a regulatory boundary, not as a sinonasal-specific standard; rare sinonasal histologies and site eligibility/evidence must be verified before extrapolation.","role":"prevents overgeneralizing a contemporary HNSCC FDA indication to every sinonasal malignancy"},
]

PROMPT = """A 58-year-old patient presents with progressive unilateral nasal obstruction, recurrent epistaxis, facial pressure and new diplopia. Nasal endoscopy shows a friable superior nasal-cavity mass; MRI demonstrates ethmoid/superior nasal-cavity disease abutting the anterior skull base with focal periorbital involvement, while CT is being reviewed for bone destruction. As the senior resident planning biopsy and definitive management, explain how you would work up and localize a suspected sinonasal malignancy, identify the orbit/skull-base/carotid and hemorrhage danger zones, decide whether an endoscopic, open, combined, radiation-based or induction-response-adapted strategy is appropriate, and show how histology changes treatment. Include explicit rescue/bailout decisions when the orbit, dura, optic apparatus, cavernous/skull-base region or major vessels make the planned operation unsafe."""

ANSWER = """Foundation — treat “sinonasal malignancy” as an anatomic problem plus a histologic family, not as one generic cancer. Persistent unilateral obstruction, epistaxis, facial numbness/pain, diplopia, proptosis, cranial neuropathy, a unilateral middle-meatal mass, or unilateral sinus opacification with destructive or infiltrative features should lower the threshold for neoplasm. Endoscopy defines the mucosal epicenter and supplies tissue, but cross-sectional imaging defines the dangerous deep extent. Contrast-enhanced MRI is particularly important for orbit, dura, brain, perineural spread, cavernous/skull-base soft tissue and marrow; thin-cut CT complements MRI for bone remodeling/destruction, lamina papyracea, cribriform/fovea, frontal recess and pterygoid/maxillary architecture. Image the neck and chest/systemic sites according to histology and stage. Biopsy should be planned, not reflexive: control anticoagulation/coagulopathy when possible, review vascularity and skull-base relationships first, choose a site that will not create an avoidable CSF leak or orbital injury, and obtain enough tissue for modern pathologic classification and molecular testing when indicated.

Anatomic map — the roof is not a flat plate. The cribriform plate, lateral lamella and fovea ethmoidalis create a variable anterior skull-base boundary; the lateral lamella can be exceptionally thin. Superior/posterior disease can involve dura, olfactory bulbs, planum/sphenoid and intracranial structures. The medial orbital boundary includes lamina papyracea/periorbita, but oncologic orbital assessment must distinguish bone/periorbita contact from invasion of orbital fat, extraocular muscles, globe, optic nerve or apex. Posterior disease can enter the pterygopalatine and infratemporal fossae, follow V2/other nerves, reach the vidian region, foramen rotundum, cavernous sinus and petrous/paraclival internal carotid artery. The sphenopalatine/internal-maxillary system can generate major hemorrhage. These compartments determine both oncologic margins and whether the next millimeter of dissection is routine, reconstructive, vascular, neuro-ophthalmic or potentially catastrophic.

Workup — first establish histology because sinonasal squamous cell carcinoma (SNSCC), intestinal/nonintestinal adenocarcinoma, olfactory neuroblastoma (ONB), sinonasal undifferentiated carcinoma (SNUC), neuroendocrine carcinoma, mucosal melanoma, adenoid cystic carcinoma, NUT carcinoma and SWI/SNF-deficient tumors do not share one treatment algorithm. Ask about occupational wood/leather-dust exposure where relevant, smoking, rapidity, cranial neuropathy and prior radiation. Pathology review at an experienced center matters because poorly differentiated sinonasal tumors can be difficult to classify and classification now changes systemic options and expected chemosensitivity. Stage with the disease-appropriate TNM system and multidisciplinary review; do not let the shorthand “T4” substitute for describing exactly which orbit, skull-base, cranial-nerve, skin, palate, pterygoid or intracranial structures are involved.

Margin-oriented surgery — the operative question is not “Can I reach it endoscopically?” but “Can I achieve oncologically sound resection with controlled margins and acceptable morbidity?” Endoscopic endonasal resection is appropriate for many selected tumors, including anterior skull-base resections, when the tumor can be compartmentally exposed, critical margins can be assessed, vascular control is available and reconstruction is reliable. Open craniofacial, maxillectomy, transfacial or combined approaches remain appropriate when lateral/anterior extension, skin/soft tissue, extensive orbital involvement, vascular encasement, brain involvement or margin geometry cannot be safely controlled endoscopically. Piecemeal endoscopic removal is not the same as oncologic tumor violation: planned compartmental disassembly can be acceptable when orientation and margins are preserved, while blindly debulking through tumor to discover its boundaries is not.

Orbit decision — reject the obsolete binary “any orbital involvement equals exenteration.” Bone or limited periorbital involvement does not automatically require removal of a functional eye. Define whether disease stops at bone/periorbita or enters extraconal fat, extraocular muscles, globe, optic nerve/apex or extensive intraconal contents; integrate visual function and whether a negative/controlled margin is achievable. Selected orbit-invading, potentially chemosensitive tumors may be candidates for neoadjuvant treatment and response-adapted organ preservation in an experienced multidisciplinary program. Contemporary systematic reviews show high response/orbital-preservation rates in selected cohorts, but the evidence is heterogeneous and largely nonrandomized; induction chemotherapy is therefore a selective strategy, not a universal substitute for resection. If preservation leaves gross disease on the optic nerve/apex or destroys oncologic control, preservation is not success.

Skull-base and dura — tumor at the cribriform/fovea requires deliberate superior-margin planning. Dural involvement can require en bloc or margin-directed dural resection with neurosurgical collaboration and multilayer skull-base reconstruction. A controlled CSF leak created as part of planned oncologic resection is fundamentally different from an unrecognized tear during blind superior dissection. Once the surgeon cannot identify the skull-base plane, do not continue curetting superiorly toward the brain. Stop, orient with navigation/anatomic landmarks, obtain appropriate exposure, and convert to a combined approach or staged plan if safe margins cannot be obtained. Intracranial extension, optic-chiasm proximity and carotid/cavernous involvement may shift treatment toward chemoradiation, proton/advanced RT, induction-response assessment or unresectable-disease pathways rather than heroic margin-negative surgery with unacceptable neurologic morbidity.

Hemorrhage and carotid bailout — posterior tumor can obscure the sphenopalatine/internal-maxillary system and, at the deepest skull base, approach the petrous/paraclival internal carotid. Preoperative imaging must identify vessel displacement, narrowing/encasement and prior treatment effects. Major bleeding is not managed by blind clamping in a tumor-filled pterygopalatine or sphenoid field. Pack/compress to regain visualization when appropriate, call for vascular/interventional support early, maintain resuscitation and convert exposure if needed. If carotid injury is suspected, prioritize immediate hemorrhage control and cerebral perfusion; do not repeatedly probe the defect. A tumor that cannot be separated from a critical carotid safely should trigger a resectability/vascular strategy discussion before uncontrolled injury, not intraoperative improvisation.

Histology-specific application — for resectable SNSCC, surgery followed by risk-adapted radiotherapy with or without systemic therapy remains a common framework; induction chemotherapy can be considered in selected locally advanced disease, especially when response may guide organ preservation or avoid extremely morbid local therapy. High-grade poorly differentiated tumors such as SNUC can be highly chemosensitive, and response to induction has been used in experienced centers to choose definitive chemoradiation versus surgery, but this is not the same evidence base as routine SNSCC management. ONB management integrates grade/stage, surgery when resectable and radiotherapy for appropriate disease; neck management depends on nodal status, stage/grade and institutional strategy rather than copying SCC rules. Adenocarcinoma, adenoid cystic carcinoma, mucosal melanoma, NUT and molecularly defined tumors require their own pathology-driven discussions. The ESMO–EURACAN guideline specifically supports considering neoadjuvant chemotherapy in potentially chemosensitive, high-grade/poorly differentiated, locally advanced tumors when surgery or radiotherapy would carry very high morbidity, including significant orbital invasion or proximity to the chiasm. That recommendation is selective and evidence-graded, not an instruction to induce every advanced sinonasal cancer.

Neck and adjuvant decisions — clinically involved neck disease should be treated according to histology and definitive modality. Elective neck treatment is not identical across all sinonasal tumors; risk varies with primary site, T category, histology and grade. Likewise, postoperative RT is common for many advanced/high-risk resected cancers, while concurrent chemotherapy is added selectively based on histology and risk rather than because “head and neck cancer gets cisplatin.” Rare sinonasal tumors are underrepresented in the randomized trials that define generic mucosal HNSCC standards. Current FDA approval of perioperative pembrolizumab for selected PD-L1-positive resectable locally advanced HNSCC should therefore not be memorized as a sinonasal-specific mandate; verify that the patient’s site/histology and evidence base actually support extrapolation, and use molecular/tissue-agnostic indications only when their specific criteria are met.

Senior decision — before committing to resection, write down the intended negative-margin surfaces: skull base/dura, orbit, posterior pterygopalatine/infratemporal boundary, maxillary/palatal or frontal boundary, and any neurovascular interface. If one of those margins cannot be made safe or meaningful, change the plan before incision. If the tumor is highly chemosensitive and an up-front operation would require exenteration, optic sacrifice, extremely morbid skull-base resection or impossible posterior margins, multidisciplinary induction therapy with early imaging response assessment may preserve function in responders while identifying nonresponders who need a different definitive strategy. Conversely, a dramatic response does not erase the original disease map; definitive local therapy must still address the pretreatment extent according to the protocol and histology.

Rescue/bailout synthesis — orbit: stop blind periorbital dissection when anatomy is lost; define the compartment and bring ophthalmology when globe/optic structures are threatened. Skull base: if the superior plane is uncertain, stop curettage, reorient and obtain controlled dural exposure rather than converting occult tumor or a thin lateral lamella into an uncontrolled intracranial injury. CSF leak: recognize it, protect neural tissue and perform planned multilayer repair rather than hiding the defect under packing. Hemorrhage: regain control with compression/packing and exposure; never chase a posterior vessel blindly. Carotid/cavernous region: stop when safe separation is not demonstrable and move to a planned vascular/oncologic alternative. Optic apparatus: preservation is worthwhile only when oncologically and functionally meaningful. The senior skill is not maximal technical aggression; it is knowing when anatomy, histology, response and margin feasibility support surgery, when combined expertise changes the risk, and when a controlled change in strategy prevents permanent blindness, stroke, catastrophic hemorrhage, CSF catastrophe or a knowingly inadequate cancer operation."""

TRAPS = [
    "Treating all sinonasal malignancies as one SCC-like disease instead of establishing histology before choosing surgery, radiation, systemic therapy and neck management.",
    "Biopsying a vascular or skull-base-adjacent mass before reviewing imaging and creating an avoidable hemorrhage or CSF-leak problem.",
    "Assuming CT alone excludes dural, perineural, orbital-apex or cavernous/skull-base soft-tissue extension when MRI is needed.",
    "Calling any contact with the lamina papyracea or periorbita an indication for orbital exenteration.",
    "Preserving an eye when gross disease remains at the optic nerve/apex and mistaking organ preservation for oncologic success.",
    "Using induction chemotherapy for every advanced sinonasal cancer instead of selecting potentially chemosensitive, high-morbidity cases and reassessing response early.",
    "Interpreting retrospective/highly selected orbital-preservation series as randomized proof that induction therapy is superior to surgery.",
    "Choosing an endoscopic approach because the tumor is technically reachable even when posterior/lateral/vascular margins cannot be controlled.",
    "Equating planned compartmental endoscopic disassembly with uncontrolled intratumoral debulking and losing margin orientation.",
    "Blindly curetting superior ethmoid/skull-base tumor when the cribriform, lateral lamella or dura is no longer identified.",
    "Blindly clamping posterior tumor-bed hemorrhage in the pterygopalatine/infratemporal or sphenoid region without identifying the vessel and carotid relationship.",
    "Continuing dissection against suspected carotid or cavernous involvement because the original plan called for resection instead of changing the resectability/vascular strategy.",
    "Applying elective-neck treatment uniformly across SNSCC, ONB, SNUC, adenocarcinoma and other rare histologies despite different nodal risks.",
    "Applying a generic HNSCC FDA immunotherapy approval automatically to every sinonasal histology without verifying trial/site applicability or a tumor-agnostic indication.",
    "Forgetting that a major induction response does not erase pretreatment extent when planning definitive local therapy.",
]

COHORT = {QID: {
    "concept_id": CID,
    "canonical_topic": TOPIC,
    "prompt": PROMPT,
    "answer_text": ANSWER,
    "explanation": "Sinonasal malignancy decisions require histology plus a three-dimensional margin map: define orbit, skull base/dura, posterior neurovascular and carotid interfaces; select endoscopic/open/RT/induction strategies by controllable margins and morbidity; and stop before uncertain anatomy becomes blindness, stroke, hemorrhage or an inadequate cancer operation.",
    "board_pearl": "Do not equate orbital contact with exenteration or advanced stage with automatic induction chemotherapy. Histology, precise compartment invasion, response potential and whether a safe oncologic margin is achievable determine the plan.",
    "depth_layers_v217": {
        "foundation":"Histology-specific sinonasal cancer framework; MRI/CT roles; orbit, cribriform/fovea/dura, pterygopalatine/infratemporal, cavernous and carotid anatomy.",
        "application":"Biopsy planning, endoscopic versus open marginability, orbital-compartment assessment, histology-specific surgery/RT/systemic and neck decisions, selective induction-response strategy.",
        "senior_decision":"Predeclare critical margins, use combined skull-base/ophthalmic/vascular expertise when needed, and bail out of blind orbit/skull-base/posterior dissection before blindness, CSF injury, stroke or catastrophic hemorrhage."
    },
    "common_traps_v217": TRAPS,
    "deliberate_review_v217": "Selected from the newest validated v20.16 exact-live canonical backlog after exact production CI succeeded. Sinonasal Malignancy was prioritized over noisier lexical ranks because it concentrates resident/board decisions and immediate OR danger zones: orbit preservation versus exenteration, anterior skull-base/dural control, posterior hemorrhage/carotid risk, margin-driven approach selection and histology-dependent induction/systemic therapy.",
    "source_refs_v217": SOURCE_REFS_V217,
    "evidence_distinction_v217": "Durable Cummings/Pasha/K.J. Lee anatomy and margin-oriented operative principles are preserved. Current ESMO–EURACAN 2025 guidance supports selective neoadjuvant chemotherapy for potentially chemosensitive high-grade locally advanced disease when local therapy would be highly morbid; 2024-2025 systematic reviews suggest meaningful response/orbit-preservation in selected cohorts but remain heterogeneous/nonrandomized. Generic HNSCC FDA immunotherapy approvals are explicitly not treated as sinonasal-specific mandates."
}}

def apply_concept_check_task_alignment_v217(checks, deep_modules, v6_item_id):
    by={str(q.get("id") or ""):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get("topic") or "") if m else ""; cid=v6_item_id(q.get("domain"),topic) if m and q.get("domain") else None
        persisted=q.get("concept_id")
        if m is None or topic!=p["canonical_topic"] or cid!=p["concept_id"] or (persisted is not None and persisted!=cid): link_mismatch.append(qid); continue
        q["concept_id"]=cid; q["canonical_topic"]=topic
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v217","common_traps_v217","deliberate_review_v217","source_refs_v217","evidence_distinction_v217"): q[field]=p[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v217"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
