"""v19.3 — live-canonical endocrine, voice, rhinology, and swallow depth cohort."""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-thyroid-parathyroid-salivary-graves-disease-toxic-goiter":{
"concept_id":"v6-thyroid-parathyroid-salivary-graves-disease-toxic-goiter","canonical_topic":"Graves Disease / Toxic Goiter",
"prompt":"A 37-year-old with Graves disease has a large hypervascular goiter, compressive symptoms, and active medical treatment with methimazole. She is referred for thyroidectomy because of poor durable control and gland size. What must be optimized before surgery, when is preoperative iodide useful, how do the hypervascular gland and distorted anatomy change operative risk, and what should you do if the patient cannot be rendered conventionally euthyroid or develops concern for thyroid storm?",
"answer_text":"Thyroidectomy for Graves disease or toxic goiter begins with control of thyrotoxicosis and a clear reason surgery is favored over continued medical therapy or radioactive iodine. Coordinate with endocrinology to achieve euthyroidism when feasible using a thionamide such as methimazole, add beta blockade for adrenergic symptoms and heart-rate control, and correct major comorbidity or volume/electrolyte problems. Short-course inorganic iodide can be used immediately before Graves thyroidectomy after antithyroid therapy has blocked new hormone synthesis; it decreases hormone release and can reduce gland vascularity. Do not give iodide as unopposed long-term therapy because iodine can provide substrate for new hormone synthesis after escape from the acute inhibitory effect. A large Graves gland is hypervascular and friable, so anticipate greater bleeding and difficult capsular-plane work. Marked enlargement, inflammation, substernal extension, or prior treatment can distort the recurrent laryngeal nerve and parathyroid relationships; meticulous capsular dissection, deliberate RLN identification/monitoring strategy, and preservation of parathyroid blood supply are essential. Obtain preoperative laryngeal examination when voice symptoms, prior neck surgery, invasive disease concern, or other risk makes baseline function important. If urgent surgery is required before conventional euthyroidism can be achieved, use multidisciplinary rapid preparation with beta blockade, thionamide when possible, iodide only after synthesis blockade, glucocorticoid, supportive therapy, and selected adjuncts such as cholestyramine according to severity and endocrine/anesthesia guidance. Thyroid storm is a clinical emergency marked by severe thyrotoxicosis with systemic decompensation such as hyperthermia, marked tachycardia/arrhythmia, CNS dysfunction, heart failure, or GI/hepatic manifestations; treat immediately with supportive resuscitation, beta blockade when hemodynamically appropriate, thionamide, then iodide after thionamide, glucocorticoid, and treatment of the precipitant. The senior principle is that surgical anatomy and endocrine physiology are inseparable: a technically excellent thyroidectomy is unsafe if uncontrolled hormone physiology is ignored, while indefinite delay may also be unsafe in a compressive or otherwise urgent gland.",
"explanation":"Graves thyroidectomy combines endocrine stabilization with a hypervascular, anatomically distorted operation. The sequence of thionamide before iodide and recognition/treatment of thyroid storm are core safety physiology.",
"board_pearl":"For rapid preoperative preparation, block new hormone synthesis before giving iodide; in thyroid storm, do not delay treatment while waiting for laboratory confirmation of severity.",
"depth_layers_v193":{"foundation":"Understand why Graves glands are hypervascular and why uncontrolled thyroid hormone physiology increases perioperative risk.","application":"Use thionamide, beta blockade, short-course iodide in the correct sequence, and plan capsular/RLN/parathyroid dissection for a large vascular gland.","senior_decision":"Coordinate accelerated preparation when surgery cannot wait, recognize thyroid storm clinically, and balance physiologic stabilization against urgency from compression or other surgical indications."},
"common_traps_v193":["Giving iodide before blocking hormone synthesis can supply substrate to a still-active thyroid and ignores the sequencing that makes short-course preoperative iodide useful.","Treating Graves thyroidectomy like an ordinary small euthyroid nodule underestimates vascularity, friability, distorted nerve/parathyroid relationships, and the catastrophic perioperative risk of uncontrolled thyrotoxicosis."],
"deliberate_review_v193":"Reused the existing hypervascular/distorted-anatomy principle and added endocrine preparation, iodide sequencing, accelerated preparation, thyroid-storm recognition/rescue, and RLN/parathyroid operative strategy."},
"cc-v112-rec-laryngology-voice-swallowing-medialization-thyroplasty":{
"concept_id":"v6-laryngology-voice-swallowing-medialization-thyroplasty","canonical_topic":"Medialization Thyroplasty",
"prompt":"A 61-year-old with stable unilateral vocal-fold paralysis 14 months after vagal injury has persistent breathy dysphonia and cough with thin liquids despite voice therapy. Stroboscopy shows a large posterior-predominant glottic gap. How do you decide between injection augmentation, type I medialization thyroplasty, arytenoid adduction, reinnervation, or observation, and what intraoperative anatomy and postoperative complications should guide a permanent framework operation?",
"answer_text":"Permanent framework medialization is most useful when symptomatic glottic insufficiency is durable and recovery is unlikely or the patient accepts permanent treatment after counseling. First define the mechanism with laryngoscopy/stroboscopy and voice/swallow assessment: quantify the gap, vocal-process position, vertical-level mismatch, tissue atrophy, contralateral compensation, and aspiration burden, and establish the cause and expected nerve-recovery trajectory. Injection augmentation is attractive when recovery remains possible, when a temporary diagnostic/therapeutic trial is useful, or when the patient is a poor candidate for framework surgery. Type I medialization thyroplasty provides durable static medialization and is commonly performed under local anesthesia with monitored sedation so phonation can help titrate implant position, although anesthetic approach varies by patient and surgeon. The thyroid-cartilage window must preserve structural support and be positioned so the implant medializes the membranous fold at the desired level without entering the laryngeal lumen. Overmedialization can produce strained voice or airway narrowing; under-medialization leaves the gap. A large posterior gap, malpositioned vocal process, or substantial vertical mismatch may not be corrected by an anterior/mid-membranous implant alone and can justify adding arytenoid adduction, which rotates the vocal process medially but adds operative time, edema, and airway risk. Reinnervation can improve tone and bulk without providing immediate static closure and is particularly attractive in selected younger patients with denervation when timing and expected recovery make it appropriate; it can be combined with temporary augmentation while waiting for reinnervation effect. Postoperatively watch for neck hematoma, airway compromise from edema or overmedialization, implant displacement/extrusion or infection, dysphagia/aspiration trajectory, and suboptimal voice requiring revision. New stridor, rapidly expanding neck swelling, hypoxemia, or respiratory distress demands immediate airway/hematoma evaluation. The senior decision is to match the operation to the geometry and time course of insufficiency rather than treating every unilateral paralysis with the same implant.",
"explanation":"Medialization thyroplasty treats glottic geometry, not the nerve lesion itself. Gap location, posterior vocal-process position, vertical mismatch, recovery timing, and aspiration burden determine whether static medialization alone is enough.",
"board_pearl":"A large posterior gap or vertical-level mismatch should make you consider arytenoid adduction in addition to type I thyroplasty; an implant alone may not correct vocal-process malposition.",
"depth_layers_v193":{"foundation":"Define the glottic gap, vocal-process position, vertical level, aspiration burden, and recovery trajectory before choosing permanent medialization.","application":"Choose temporary injection versus durable thyroplasty, recognize when arytenoid adduction or reinnervation adds value, and titrate implant position while preserving airway and cartilage support.","senior_decision":"Anticipate hematoma/airway rescue, over- versus under-medialization, implant complications, and revision when the chosen framework does not match posterior or vertical glottic geometry."},
"common_traps_v193":["Scheduling permanent thyroplasty early in a potentially recovering nerve injury can commit the patient to a durable framework operation when temporary injection would bridge the recovery window.","Trying to close a major posterior gap solely by pushing the membranous fold medially can leave the vocal process malpositioned or force overmedialization that worsens airway and voice quality."],
"deliberate_review_v193":"Reused the existing stroboscopy/recovery assessment and temporary-injection principle, then added framework-window goals, posterior-gap/vertical-level decision making, arytenoid adduction, reinnervation, and airway/hematoma rescue."},
"cc-v112-rec-rhinology-allergy-skull-base-fungal-ball":{
"concept_id":"v6-rhinology-allergy-skull-base-fungal-ball","canonical_topic":"Fungal Ball",
"prompt":"A 68-year-old immunocompetent patient has months of unilateral maxillary pressure and foul drainage. CT shows unilateral sinus opacification with internal hyperdense/calcific material and surrounding bony sclerosis but no extrasinus invasion. What features support a fungal ball rather than AFRS or invasive fungal rhinosinusitis, what is the definitive treatment, when are antifungals unnecessary, and which clinical or operative findings should trigger biopsy and urgent escalation for invasive disease?",
"answer_text":"A fungal ball is a noninvasive accumulation of dense fungal hyphae and debris, usually in a single sinus of an immunocompetent patient, with no tissue invasion. Unilateral opacification containing hyperdense or calcific foci and chronic bony remodeling/sclerosis supports the diagnosis, but unilateral disease still requires evaluation for alternative pathology. Distinguish it from allergic fungal rhinosinusitis, which is an inflammatory type-2/eosinophilic disease often associated with polyposis, allergic mucin, sinus expansion, and broader sinonasal involvement, and from acute invasive fungal rhinosinusitis, in which organisms invade mucosa, vessels, bone, orbit, or intracranial structures and the host is often immunocompromised or metabolically vulnerable. Definitive treatment for a simple fungal ball is endoscopic opening of the involved sinus, complete removal/irrigation of fungal debris, restoration of drainage and ventilation, and inspection of the mucosa; routine systemic antifungal therapy is not indicated after complete clearance of noninvasive disease. Send material for pathology when diagnosis is uncertain and biopsy suspicious mucosa rather than assuming all dark debris is benign fungus. Escalate urgently when there is severe rapidly progressive pain, fever/systemic toxicity, cranial neuropathy, facial numbness, vision change, afferent pupillary defect, ophthalmoplegia, palatal or turbinate necrosis, extrasinus soft-tissue infiltration, orbital/intracranial involvement, or operative evidence of devitalized/invasive tissue. In suspected invasive disease, management changes completely to urgent tissue diagnosis, reversal of immunometabolic risk when possible, aggressive surgical debridement of involved devitalized tissue, and prompt systemic antifungal therapy selected for the organism/clinical syndrome with infectious-disease support. The senior principle is that radiographic 'fungus' does not determine invasiveness; host risk, tempo, extrasinus findings, and histopathologic tissue invasion do.",
"explanation":"The treatment split is invasion. A fungal ball is surgically cleared without routine systemic antifungal therapy, whereas invasive fungal rhinosinusitis is an emergency requiring tissue diagnosis, debridement, and systemic therapy.",
"board_pearl":"Hyperdense unilateral sinus debris in an immunocompetent patient can be a fungal ball, but cranial neuropathy, necrosis, vision findings, or extrasinus infiltration should make you prove or exclude tissue invasion urgently.",
"depth_layers_v193":{"foundation":"Differentiate noninvasive fungal ball from AFRS and tissue-invasive fungal disease using host, tempo, imaging, mucosa, and pathology.","application":"Perform endoscopic sinus opening and complete debris clearance for a fungal ball without routine systemic antifungal therapy.","senior_decision":"Biopsy suspicious/devitalized mucosa and escalate immediately to invasive-fungal debridement/systemic therapy when neuro-ophthalmic, necrotic, extrasinus, or high-risk-host findings appear."},
"common_traps_v193":["Prescribing systemic antifungal medication for an uncomplicated fungal ball adds toxicity without treating the key problem, which is retained noninvasive debris in a poorly ventilated sinus.","Assuming unilateral hyperdense debris is always benign fungal ball can delay life-saving biopsy and debridement when necrosis, cranial neuropathy, orbital findings, extrasinus infiltration, or immunocompromise signals invasive disease."],
"deliberate_review_v193":"Reused the existing surgical-clearance/no-routine-antifungal principle and added imaging/pathology distinction from AFRS and invasive disease, tissue-biopsy thresholds, neuro-ophthalmic danger signs, and invasive-fungal rescue."},
"cc-v112-rec-laryngology-voice-swallowing-cricopharyngeal-dysfunction":{
"concept_id":"v6-laryngology-voice-swallowing-cricopharyngeal-dysfunction","canonical_topic":"Cricopharyngeal Dysfunction",
"prompt":"A 74-year-old has cervical dysphagia, repeated post-swallow residue at the upper esophageal sphincter on modified barium swallow, and intermittent aspiration. Pharyngeal constriction is reduced but a prominent cricopharyngeal bar is also present. How do you determine whether the upper esophageal sphincter is the primary outflow problem, and how should the relative roles of dilation, botulinum toxin, endoscopic/open myotomy, swallowing therapy, and further esophageal evaluation be chosen?",
"answer_text":"A cricopharyngeal bar or incomplete upper-esophageal-sphincter opening is a radiographic observation, not automatically the cause of dysphagia. Start with a physiologic swallow study such as MBS/VFSS to determine bolus propulsion, hyolaryngeal excursion, UES opening, residue, penetration/aspiration, and whether obstruction is focal or reflects globally weak pharyngeal driving pressure. FEES complements airway-protection and residue assessment but does not directly show UES opening. Endoscopy or esophagram evaluates structural lesions and distal esophageal disease when symptoms or study findings suggest them; high-resolution pharyngeal/esophageal manometry can clarify pressure and relaxation questions in selected complex cases. Treat the dominant physiology. Swallow therapy and management of the underlying neurologic, muscular, reflux, or structural disorder are appropriate when poor propulsion or coordination is central. Dilation can provide a relatively low-morbidity therapeutic trial for a focal restrictive UES and may be repeated if benefit is meaningful. Botulinum toxin can temporarily reduce cricopharyngeal tone and may be diagnostically useful when hypertonicity or impaired relaxation is suspected, but its temporary effect and risk of worsened reflux/aspiration must be considered. Cricopharyngeal myotomy—endoscopic when exposure/anatomy permit or open in selected situations—offers more durable division of the sphincter for well-selected patients with true UES outflow obstruction and adequate upstream propulsion. Cutting the sphincter in a patient whose main limitation is severe pharyngeal weakness may not improve clearance and can worsen regurgitation or aspiration because the propulsion needed to move the bolus remains absent. Zenker diverticulum, malignancy, distal stricture, achalasia or other esophageal dysmotility, and cervical osteophyte/extrinsic problems require disease-specific evaluation rather than isolated CP treatment. The senior decision is to use a reversible intervention such as dilation or botulinum toxin when diagnostic uncertainty is meaningful, and reserve durable myotomy for physiology that demonstrates a correctable outflow resistance with sufficient swallowing reserve.",
"explanation":"Cricopharyngeal treatment succeeds when the UES is truly the bottleneck. The same bar can be causal, compensatory, or incidental depending on pharyngeal propulsion and downstream esophageal physiology.",
"board_pearl":"Do not myotomize a cricopharyngeal bar just because it is visible; prove that UES outflow resistance—not severe pharyngeal weakness—is the dominant correctable lesion.",
"depth_layers_v193":{"foundation":"Interpret UES opening together with pharyngeal propulsion, hyolaryngeal excursion, residue, and aspiration rather than treating a CP bar as a diagnosis.","application":"Choose therapy, dilation, temporary botulinum toxin, or endoscopic/open myotomy according to the dominant physiology and diagnostic certainty.","senior_decision":"Use reversible treatment when uncertainty is high, avoid durable sphincter division in profound propulsion failure, and investigate Zenker, malignancy, distal obstruction, or dysmotility when the pattern is not isolated CP dysfunction."},
"common_traps_v193":["Myotomizing every prominent cricopharyngeal bar mistakes a fluoroscopic sign for causality and can worsen aspiration or regurgitation in a patient with severely weak pharyngeal propulsion.","Treating only the UES when dysphagia actually reflects Zenker diverticulum, distal stricture, malignancy, achalasia, or generalized neuromuscular disease delays the intervention that addresses the true bottleneck."],
"deliberate_review_v193":"Reused the existing MBS/manometry and 'do not cut weak propulsion' principle, then added physiology-based selection among therapy, dilation, botulinum toxin, myotomy, and broader esophageal evaluation."}
}

def apply_concept_check_task_alignment_v193(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id); topic=str(module.get('topic') or '') if module else ''; cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']: link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v193']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
