"""v19.4 — live-canonical esophageal diagnostic and escalation depth cohort."""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-laryngology-voice-swallowing-transnasal-esophagoscopy":{
"concept_id":"v6-laryngology-voice-swallowing-transnasal-esophagoscopy","canonical_topic":"Transnasal Esophagoscopy",
"prompt":"A 67-year-old with progressive solid-food dysphagia, intermittent regurgitation, and a remote history of head-and-neck radiation is referred for office transnasal esophagoscopy (TNE). Flexible laryngoscopy shows no obstructing pharyngeal lesion and the patient can tolerate topical nasal anesthesia. When is unsedated TNE an appropriate diagnostic or surveillance tool, when should you instead choose conventional sedated EGD or another study, what findings require biopsy or urgent escalation, and what procedural complications or limitations must you anticipate?",
"answer_text":"Transnasal esophagoscopy is an office-based, typically unsedated way to inspect the hypopharynx and esophagus in selected patients when the clinical question is mucosal or structural and the patient can tolerate transnasal passage. It can be useful for selected dysphagia evaluation, surveillance after head-and-neck cancer treatment, assessment of suspected esophagitis or visible stenosis, and targeted biopsy when the lesion is accessible and the office setting is appropriate. It is not a universal substitute for conventional EGD. Choose sedated GI endoscopy when extensive therapeutic intervention, larger or multiple biopsies, significant dilation, control of bleeding, full gastric/duodenal examination, or patient tolerance and airway considerations make the conventional platform safer or more complete. Choose MBS/FEES when the dominant question is oropharyngeal swallow physiology and airway protection; choose esophagram when contour, diverticulum, stricture length, or dynamic transit needs radiographic mapping; and pursue manometry when motility disease is suspected after structural obstruction has been addressed. During TNE, inspect systematically rather than stopping at the first benign-appearing abnormality. Ulceration, irregular mass, friable mucosa, unexplained focal narrowing, progressive dysphagia, weight loss, bleeding, or a suspicious post-radiation change should trigger tissue diagnosis and appropriate oncologic/GI escalation. A tight stenosis should not be forced: inability to pass safely is itself useful information and may require radiographic definition or controlled dilation in a setting equipped for rescue. Complications are uncommon but include epistaxis, vasovagal symptoms, laryngospasm, aspiration, mucosal injury, and rare perforation. New severe neck/chest pain, subcutaneous emphysema, dyspnea, fever, tachycardia, or toxicity after instrumentation raises concern for perforation and warrants immediate cessation, NPO status, urgent imaging/surgical evaluation, and supportive management. The senior decision is to match the platform to the question and rescue needs rather than treating office convenience as proof that TNE is adequate for every esophageal problem.",
"explanation":"TNE is valuable when a targeted mucosal/structural question can be answered safely in the office, but the diagnostic platform must change when physiology, extensive therapy, deep sedation, or perforation-rescue capability is needed.",
"board_pearl":"Do not force a transnasal scope across a tight or suspicious stenosis; inability to traverse safely should trigger a different diagnostic/therapeutic plan, not increasingly traumatic office instrumentation.",
"depth_layers_v194":{"foundation":"Know what TNE directly visualizes and distinguish a mucosal/structural esophageal question from oropharyngeal physiology or motility disease.","application":"Select TNE versus EGD, MBS/FEES, esophagram, or manometry according to the diagnostic question, tolerance, biopsy/therapy needs, and airway considerations.","senior_decision":"Recognize suspicious mucosa or nontraversable stenosis, avoid forcing instrumentation, and escalate immediately when post-procedure findings suggest perforation or another complication requiring rescue."},
"common_traps_v194":["Using office TNE as a universal dysphagia test can miss the actual physiology when the problem is aspiration, pharyngeal weakness, diverticular anatomy, distal disease, or motility dysfunction that requires another modality.","Forcing the scope through a tight stenosis converts useful diagnostic information into preventable mucosal injury or perforation; stop, redefine the anatomy, and move dilation or further endoscopy to an appropriately controlled setting."],
"deliberate_review_v194":"Replaced the generic 18-word selection answer with a platform-selection framework, targeted biopsy thresholds, nontraversable-stenosis decision making, and explicit perforation recognition/rescue."},
"cc-v112-rec-laryngology-voice-swallowing-esophageal-disease-for-the-otolaryngologist":{
"concept_id":"v6-laryngology-voice-swallowing-esophageal-disease-for-the-otolaryngologist","canonical_topic":"Esophageal Disease for the Otolaryngologist",
"prompt":"A 72-year-old reports coughing immediately with liquids, a sensation of food sticking in the lower neck several seconds after swallowing, nocturnal regurgitation, and 6 kg of unintentional weight loss. Laryngoscopy is unrevealing. How should an otolaryngologist separate oropharyngeal dysphagia from cervical or distal esophageal structural disease and motility disorders, choose among FEES/MBS, esophagram, endoscopy, and manometry, and identify findings that require expedited malignancy or aspiration-risk evaluation?",
"answer_text":"Start by localizing the symptom physiologically rather than accepting the patient's perceived level of sticking as the lesion location. Difficulty initiating a swallow, coughing or choking during the swallow, wet voice, nasal regurgitation, and recurrent aspiration pneumonia favor an oropharyngeal problem; FEES and MBS/VFSS are the principal tools for airway protection, residue, bolus flow, and compensatory-strategy assessment, with MBS also showing upper-esophageal opening. Food sticking seconds after initiation, especially for solids, regurgitation, or retrosternal symptoms raises a structural or esophageal process. A barium esophagram is useful for rings, strictures, diverticula, gross transit, and contour; endoscopy directly evaluates mucosa, permits biopsy, and enables selected therapy. Progressive solid-food dysphagia, weight loss, anemia or bleeding, odynophagia, a new focal stricture, or a suspicious mucosal lesion requires expedited endoscopic tissue diagnosis rather than empiric reflux treatment alone. Dysphagia to both solids and liquids from the outset, prominent regurgitation, or unexplained stasis after structural disease is excluded should raise concern for motility disease; high-resolution manometry is the definitive physiologic study for disorders such as achalasia and other major motility abnormalities. Zenker diverticulum and cricopharyngeal dysfunction sit at the pharyngoesophageal junction and require correlation of anatomy with propulsion rather than reflexively labeling all cervical symptoms as reflux. Simultaneously assess pulmonary consequence: recurrent pneumonia, weight loss/dehydration, inability to handle secretions, or significant aspiration may require diet modification, swallowing therapy, temporary alternative nutrition, or inpatient evaluation while the cause is worked up. Acute complete food bolus obstruction with inability to manage secretions is an endoscopic urgency. The senior principle is to sequence tests so each answers a specific question—airway protection and pharyngeal physiology, structural anatomy and mucosa, then motility—while red-flag cancer or aspiration findings accelerate the pathway.",
"explanation":"Dysphagia workup is a localization problem. Symptoms, swallow physiology, structural imaging/endoscopy, and manometry answer different questions and should be sequenced rather than ordered interchangeably.",
"board_pearl":"The perceived level of food sticking is unreliable; progressive solid dysphagia with weight loss needs structural evaluation and tissue diagnosis even when the patient points to the neck.",
"depth_layers_v194":{"foundation":"Differentiate swallow-initiation and airway-protection symptoms from delayed esophageal transit, structural obstruction, and motility-pattern symptoms.","application":"Choose FEES/MBS, esophagram, endoscopy, and manometry in a question-driven sequence and use endoscopy for suspicious mucosal disease or therapeutic structural problems.","senior_decision":"Accelerate malignancy workup, protect nutrition and lungs when aspiration has consequence, and treat inability to handle secretions from an obstructing food bolus as an urgent endoscopic problem."},
"common_traps_v194":["Assuming that a patient who points to the lower neck has a cervical lesion can mislocalize distal esophageal obstruction; symptom timing and targeted structural testing matter more than the finger-point location.","Calling mixed dysphagia 'reflux' without testing can delay cancer diagnosis, achalasia evaluation, or aspiration mitigation when weight loss, progressive symptoms, regurgitation, pneumonia, or secretion intolerance are already warning signs."],
"deliberate_review_v194":"Replaced the generic 19-word modality list with symptom localization, test sequencing, cancer red flags, food-bolus urgency, aspiration/nutrition consequences, and motility escalation."}
}

def apply_concept_check_task_alignment_v194(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id); topic=str(module.get('topic') or '') if module else ''; cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']: link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v194']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
