"""v19.2 — live-canonical pediatric-airway and endocrine decision depth cohort."""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-pediatric-otolaryngology-supraglottoplasty":{
"concept_id":"v6-pediatric-otolaryngology-supraglottoplasty","canonical_topic":"Supraglottoplasty",
"prompt":"A 3-month-old with inspiratory stridor has flexible laryngoscopy showing shortened aryepiglottic folds and redundant arytenoid mucosa prolapsing into the glottis. The infant now has poor weight gain, feeding-associated desaturations, and increasing work of breathing despite conservative reflux/feeding optimization. Which findings make this laryngomalacia severe enough for supraglottoplasty, what anatomy should be treated or preserved, when should you look for synchronous airway disease, and which postoperative problems require escalation?",
"answer_text":"Most laryngomalacia is observed because symptoms peak in infancy and improve with maturation, but supraglottoplasty is considered when dynamic supraglottic collapse produces clinically important obstruction or functional consequences such as failure to thrive, recurrent cyanosis or hypoxemia, significant retractions, severe obstructive sleep apnea, pulmonary hypertension, or feeding/aspiration morbidity attributable to the collapse. Flexible awake laryngoscopy establishes the dynamic diagnosis; direct laryngoscopy and bronchoscopy are appropriate when the presentation is atypical, the severity is disproportionate, intubation history or other findings suggest a second lesion, or the child is proceeding to surgery and the team needs a complete airway assessment. Operatively, tailor treatment to the collapsing structure: divide pathologically shortened aryepiglottic folds and selectively reduce redundant supra-arytenoid/arytenoid mucosa while preserving enough mucosa and supraglottic tissue for sensation, swallowing protection, and scar-free healing. Avoid indiscriminate bilateral deep resection because opposing raw surfaces can produce supraglottic stenosis; also respect the interarytenoid region and neurovascular structures. Postoperatively monitor airway edema/obstruction, oxygen requirement, stridor trajectory, feeding and aspiration, pain/hydration, and need for respiratory support. Children with neurologic disease, significant cardiopulmonary comorbidity, synchronous airway lesions, severe preoperative OSA/hypoxemia, or very young age may need higher-acuity observation and have higher revision or persistent-symptom risk. Failure to improve should trigger reassessment for residual collapse, synchronous lesions, aspiration, neurologic tone abnormalities, or another airway level rather than reflexively repeating the same resection. The senior principle is anatomy-directed reduction of the obstructing tissue while preserving protective supraglottic function; the operation treats severe physiology, not stridor volume alone.",
"explanation":"Supraglottoplasty is a severity- and anatomy-directed airway operation. The decision is driven by obstructive physiology, growth, gas exchange, sleep, and feeding consequences, while the technique must avoid creating scar or swallowing dysfunction.",
"board_pearl":"Loud stridor is not itself an operative indication; failure to thrive, hypoxemia/cyanosis, severe OSA, cardiopulmonary consequence, or important feeding/aspiration morbidity are the escalation signals.",
"depth_layers_v192":{"foundation":"Recognize dynamic laryngomalacia anatomy and distinguish common self-limited stridor from severe obstructive physiology.","application":"Select supraglottoplasty for growth, gas-exchange, sleep, cardiopulmonary, or feeding consequences and tailor division/reduction to the actual collapsing structures.","senior_decision":"Preserve protective tissue, avoid opposing raw surfaces and supraglottic stenosis, identify synchronous lesions, and investigate another mechanism when symptoms persist after surgery."},
"common_traps_v192":["Operating because the stridor sounds dramatic can expose a thriving infant without hypoxemia, sleep, or feeding consequences to unnecessary airway and aspiration risk.","Aggressive symmetric tissue removal may improve the immediate view yet create opposing raw surfaces, supraglottic scar, stenosis, or swallowing dysfunction that is harder to rescue than the original laryngomalacia."],
"deliberate_review_v192":"Reused the existing selective aryepiglottic-fold/redundant-tissue principle and added severity indications, complete-airway assessment thresholds, tissue-preservation anatomy, postoperative monitoring, high-risk phenotypes, and failure analysis."},
"cc-v112-rec-pediatric-otolaryngology-pediatric-tracheostomy-decannulation":{
"concept_id":"v6-pediatric-otolaryngology-pediatric-tracheostomy-decannulation","canonical_topic":"Pediatric Tracheostomy / Decannulation",
"prompt":"A 4-year-old with a tracheostomy placed for prolonged ventilation is now off the ventilator, tolerates a speaking valve while awake, handles secretions, and has improving swallow function. The family asks whether the next step is simply downsizing and capping until the tube can be removed. What physiologic readiness must be demonstrated, what airway evaluation is required before decannulation, when is polysomnography useful, and what findings should stop or reverse a decannulation pathway?",
"answer_text":"Decannulation is the end point of resolution of the original tracheostomy indication plus adequate upper-airway patency, ventilatory reserve, secretion clearance, cough, and swallow/aspiration control; it is not achieved by tube downsizing alone. First confirm that the child no longer needs the tracheostomy for ventilation or airway protection and can manage secretions without frequent suctioning or recurrent aspiration-related pulmonary decompensation. Progression through speaking-valve use, downsizing, and capping can test tolerance, but protocols vary and each step should be interpreted in the context of work of breathing, oxygenation, sleep, and pulmonary reserve. A complete endoscopic airway examination before decannulation is a core safety step: evaluate the supraglottis/glottis, subglottis, trachea, and stoma for granulation, suprastomal collapse, tracheomalacia, stenosis, vocal-fold immobility, or another lesion that could be masked by the tracheostomy. Current pediatric tracheostomy guidance supports bronchoscopy before decannulation and supports polysomnography when objective sleep assessment is needed; PSG is particularly useful when there is significant sleep-disordered breathing risk, marginal capping tolerance, complex airway or neuromuscular disease, or uncertainty that awake performance predicts sleep ventilation. A capped study must be interpreted carefully because a small tracheostomy tube itself can add airway resistance. Stop or reverse the pathway for persistent oxygen desaturation, hypercapnia, increased work of breathing, inability to clear secretions, recurrent aspiration/pneumonia, severe obstructive events, or a fixed/dynamic airway lesion that has not been corrected. After tube removal, observe for early respiratory failure and ensure a rescue plan; persistent tracheocutaneous fistula is addressed later if it fails to close and is clinically important. The senior principle is to prove airway and respiratory independence across wake, secretion burden, and sleep rather than using a successful brief cap trial as a surrogate for the entire physiology.",
"explanation":"Pediatric decannulation is a multidisciplinary physiologic test. Endoscopic airway patency, pulmonary reserve, secretion/swallow safety, and sleep stability each answer a different failure mode.",
"board_pearl":"Before pediatric decannulation, inspect the airway endoscopically for a lesion hidden by the tracheostomy; a good daytime cap trial does not exclude sleep-related obstruction or hypoventilation.",
"depth_layers_v192":{"foundation":"Define decannulation readiness as resolution of the original indication plus airway, ventilation, secretion, cough, and swallow competence.","application":"Use valve/downsize/cap progression as physiologic testing, perform complete airway endoscopy, and add PSG when sleep stability is uncertain or risk is high.","senior_decision":"Abort decannulation for gas-exchange failure, excessive work, secretion/aspiration failure, severe sleep events, or unresolved fixed/dynamic airway obstruction and plan rescue/observation after removal."},
"common_traps_v192":["Treating downsizing as the goal can hide the real question: whether the child can ventilate, protect the airway, and clear secretions without any tracheostomy support.","Removing the tube after a reassuring awake cap trial without airway endoscopy can miss suprastomal collapse, granulation, stenosis, malacia, or vocal-fold dysfunction that becomes clinically important only after decannulation."],
"deliberate_review_v192":"Reused the existing speaking-valve/capping and contributor-treatment framework and added bronchoscopy, sleep physiology, secretion/swallow thresholds, failure criteria, and post-removal rescue planning."},
"cc-v112-rec-thyroid-parathyroid-salivary-indeterminate-thyroid-cytology-molecular-testing":{
"concept_id":"v6-thyroid-parathyroid-salivary-indeterminate-thyroid-cytology-molecular-testing","canonical_topic":"Indeterminate Thyroid Cytology / Molecular Testing",
"prompt":"A 42-year-old has a 2.1-cm thyroid nodule with Bethesda III cytology, no suspicious cervical nodes, and intermediate ultrasound features. She wants to avoid unnecessary surgery but also asks whether a positive molecular panel means she should automatically have a total thyroidectomy. How should you integrate Bethesda category, ultrasound and clinical pretest risk, repeat sampling, molecular test performance, and patient preference into surveillance versus diagnostic lobectomy or a larger initial operation?",
"answer_text":"Indeterminate cytology is a risk category, not a cancer diagnosis. Start by confirming the Bethesda category and integrating it with ultrasound pattern, nodule size and growth, cervical-node findings, radiation/family history, compressive symptoms, contralateral disease, and the local malignancy prevalence that determines the patient's pretest probability. For Bethesda III, repeat ultrasound-guided FNA is often reasonable because some nodules are reclassified; molecular testing or diagnostic surgery are alternatives when uncertainty remains. Bethesda IV more often proceeds to molecular risk stratification or diagnostic lobectomy because cytology cannot demonstrate capsular or vascular invasion required to diagnose follicular carcinoma. Molecular testing is useful only when its result is likely to change management. A high-sensitivity/high-negative-predictive-value 'rule-out' result can support surveillance in an appropriately selected low/intermediate-pretest-risk nodule, whereas a 'rule-in' result raises malignancy probability and, depending on the alteration, may provide biologic information. Predictive values are not fixed properties: they change with disease prevalence and pretest risk, so a negative test should not override worrisome nodes or invasive ultrasound findings, and a positive result is not synonymous with a mandate for total thyroidectomy. If surgery is chosen for an isolated indeterminate nodule without independent indication for total thyroidectomy, diagnostic lobectomy frequently provides diagnosis and treatment with less hypoparathyroidism and bilateral recurrent-laryngeal-nerve risk. The extent can increase when established cancer risk, tumor size/extent, suspicious nodes, contralateral disease, high-risk molecular features that truly alter the oncologic plan, or patient preference create an independent reason. Counsel about the possibility of completion thyroidectomy if final pathology reveals features requiring it. The senior question before ordering a molecular panel is: 'What will I do if it is negative, and what will I do if it is positive?' If neither answer changes, the test adds cost and ambiguity rather than decision value.",
"explanation":"Molecular tests modify an existing probability; they do not replace ultrasound, nodal staging, cytology, or patient goals. Their clinical value comes from changing a real surveillance-versus-surgery decision.",
"board_pearl":"For an indeterminate nodule, know the pretest risk before interpreting molecular predictive values; a positive panel is not automatically an indication for total thyroidectomy.",
"depth_layers_v192":{"foundation":"Know why Bethesda III/IV are probabilistic and why follicular carcinoma cannot be diagnosed by cytology without invasion.","application":"Combine ultrasound, clinical risk, repeat FNA, molecular rule-out/rule-in performance, and patient preference to choose surveillance versus diagnostic lobectomy.","senior_decision":"Order molecular testing only when both possible results map to different management; do not let a panel replace nodal imaging or create an unsupported total-thyroidectomy indication."},
"common_traps_v192":["Reading a molecular result without pretest risk treats predictive value as universal and can falsely reassure a clinically high-risk nodule or overcall a low-risk one.","Equating any positive mutation panel with mandatory total thyroidectomy ignores tumor extent, nodal status, contralateral disease, the specific alteration, and the morbidity advantage of lobectomy when it is otherwise oncologically adequate."],
"deliberate_review_v192":"Expanded the existing combined-risk principle into Bethesda-specific next steps, repeat FNA, pretest-dependent predictive values, rule-out/rule-in use, lobectomy tradeoffs, and a decision-value test for ordering molecular studies."},
"cc-v112-mgt-thyroid-parathyroid-salivary-parathyroid-carcinoma":{
"concept_id":"v6-thyroid-parathyroid-salivary-parathyroid-carcinoma","canonical_topic":"Parathyroid Carcinoma",
"prompt":"A 55-year-old with calcium 14.8 mg/dL and markedly elevated PTH has a firm 3.5-cm parathyroid-region mass that appears tethered to the ipsilateral thyroid and strap muscle. There is no proven nodal disease. What features should make you suspect parathyroid carcinoma before incision, what should you avoid diagnostically, how should the first operation differ from routine parathyroidectomy, and how do you manage hypercalcemia and recurrent or metastatic disease?",
"answer_text":"Suspect parathyroid carcinoma when primary hyperparathyroidism is unusually severe—particularly marked hypercalcemia with very high PTH—when there is a large firm mass, local invasion/adherence, recurrent laryngeal nerve dysfunction, or recurrent disease after a prior suspicious lesion. No single calcium or PTH cutoff is diagnostic, and benign adenomas can be large, so the operative phenotype matters. Avoid percutaneous FNA of a suspected parathyroid carcinoma because cytology cannot reliably distinguish adenoma from carcinoma and needle/capsule violation can complicate the field or seed parathyroid tissue. The first operation offers the best chance for durable control. Resect the suspicious gland en bloc with its capsule intact and remove directly invaded/adherent adjacent tissue as required for a negative oncologic margin; an ipsilateral thyroid lobectomy or involved strap muscle may therefore be part of the specimen, but routine sacrifice of uninvolved structures is not the goal. Do not rupture or shell out the tumor. Assess the recurrent laryngeal nerve carefully and obtain preoperative laryngeal examination when voice symptoms, invasive imaging, prior neck surgery, or other risk makes baseline function important. Therapeutic compartment-oriented nodal dissection is appropriate for clinically involved nodes; routine prophylactic lateral neck dissection without evidence of nodal disease does not improve the operation. Severe hypercalcemia is itself an urgent management problem: restore volume, use calcitonin for rapid temporary effect when needed, antiresorptive therapy as appropriate, and cinacalcet for ongoing PTH-mediated calcium control, while definitive resection is planned. Pathologic diagnosis depends on unequivocal invasive/metastatic features rather than atypia alone. Recurrent or metastatic disease is managed multidisciplinary; reoperation/metastasectomy can be valuable when resectable because controlling functional tumor burden may substantially improve hypercalcemia even when cure is unlikely. Consider CDC73-related disease and genetic counseling/testing when age, family history, jaw/renal/uterine findings, pathology, or clinical context suggests a hereditary syndrome. The senior principle is intact first-pass oncologic resection plus aggressive calcium control: capsule violation converts a potentially local problem into a difficult recurrent one.",
"explanation":"Parathyroid carcinoma is both an oncologic and endocrine emergency. The surgical priority is an intact en-bloc first resection when suspicion exists, while hypercalcemia often drives immediate morbidity and recurrent-disease treatment.",
"board_pearl":"Do not FNA or shell out a suspected parathyroid carcinoma. Preserve the capsule and take invaded adjacent tissue en bloc; the first operation is the best opportunity for durable local control.",
"depth_layers_v192":{"foundation":"Recognize the severe biochemical/invasive phenotype and understand why FNA and capsule violation are dangerous and diagnostically weak.","application":"Plan intact en-bloc resection with invaded adjacent tissue, baseline nerve assessment when indicated, therapeutic rather than routine prophylactic nodal surgery, and urgent calcium control.","senior_decision":"Balance margin clearance against unnecessary sacrifice, use reoperation/metastasectomy for resectable functional recurrence, and evaluate CDC73/hereditary context when appropriate."},
"common_traps_v192":["Biopsying a suspicious parathyroid mass because the diagnosis is uncertain does not reliably separate adenoma from carcinoma and can violate the capsule before the definitive oncologic operation.","Shelling a tethered gland away from thyroid or strap muscle like a routine adenoma risks tumor rupture and positive margins; conversely, performing prophylactic extensive neck dissection without clinically involved nodes adds morbidity without a clear oncologic benefit."],
"deliberate_review_v192":"Reused the existing en-bloc/capsule-preservation principle and added preoperative suspicion, no-FNA reasoning, margin-directed adjacent resection, RLN and nodal decisions, hypercalcemia rescue, recurrence strategy, and CDC73 considerations."}
}

def apply_concept_check_task_alignment_v192(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id); topic=str(module.get('topic') or '') if module else ''; cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']: link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v192']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
