"""v18.5 — high-risk live-canonical Concept Check depth cohort.

Selected from the validated V184 backlog. These items had unusually short reveals
but high board/call/OR consequence. Exact production canonical linkage is required
before mutation. Oral-board error analysis is stored as individualized common traps.
"""

from concept_check_board_repair_v177 import _find_module

COHORT = {
    "cc-v112-rec-head-neck-oncology-head-neck-radiation-toxicity-survivorship": {
        "concept_id": "v6-head-neck-oncology-head-neck-radiation-toxicity-survivorship",
        "canonical_topic": "Head & Neck Radiation Toxicity / Survivorship",
        "prompt": "A long-term head-and-neck cancer survivor develops progressive dysphagia, xerostomia, neck fibrosis, dental deterioration and new mandibular pain years after chemoradiation. How do you separate expected late toxicity from recurrence or osteoradionecrosis, what surveillance and rehabilitation are required, and which findings need urgent escalation?",
        "answer_text": "Late radiation effects are longitudinal syndromes, but new focal or progressive symptoms still require evaluation for recurrence. I would assess weight and nutrition, aspiration/pneumonia history, cranial nerve and mucosal examination, dental status, thyroid function, neck mobility and the tempo/localization of pain or dysphagia. Instrumental swallowing assessment guides rehabilitation when aspiration or pharyngeal dysfunction is suspected; dental prevention, fluoride, saliva strategies, jaw range-of-motion work and thyroid surveillance should be built into survivorship rather than added after complications occur. New exposed mandibular bone, fistula, pathologic fracture, progressive focal pain or imaging concern requires evaluation for osteoradionecrosis and recurrent tumor, with biopsy when oncologically appropriate. New neurologic deficit, threatened airway, significant bleeding, severe aspiration-related pulmonary compromise or suspected carotid/major-vessel complication requires urgent escalation. Management should distinguish reversible focal problems from diffuse fibrosis and use multidisciplinary swallowing, dental, nutrition, endocrine, rehabilitation and oncologic follow-up.",
        "explanation": "The board-level distinction is chronic treatment toxicity versus a new disease process. Survivorship requires active prevention and functional surveillance, while focal progression can represent recurrence, osteoradionecrosis or vascular injury.",
        "board_pearl": "Do not let a history of radiation explain away a new focal symptom; late toxicity and recurrent cancer can coexist.",
        "depth_layers_v185": {"foundation": "Know xerostomia, dysphagia, fibrosis, dental injury, hypothyroidism, vascular disease and osteoradionecrosis as late effects.", "application": "Use longitudinal swallow, dental, nutrition, thyroid and oncologic surveillance to distinguish functional decline from new focal disease.", "senior_decision": "Escalate exposed bone/fistula/fracture, recurrent-tumor concern, airway/aspiration compromise, neurologic deficit or major-vessel warning signs."},
        "common_traps_v185": ["Attributing every new symptom to radiation can delay diagnosis of recurrent cancer or osteoradionecrosis.", "Waiting for aspiration pneumonia before arranging instrumental swallowing assessment misses an opportunity for earlier rehabilitation and risk reduction."],
        "deliberate_review_v185": "Expanded a 13-word prevention statement into recurrence discrimination, longitudinal surveillance, rehabilitation and late-complication escalation."
    },
    "cc-v112-rec-head-neck-oncology-carotid-body-paraganglioma": {
        "concept_id": "v6-head-neck-oncology-carotid-body-paraganglioma",
        "canonical_topic": "Carotid Body Paraganglioma",
        "prompt": "A healthy adult has a slowly enlarging pulsatile carotid-bifurcation mass that splays the internal and external carotid arteries on imaging. How do you confirm the diagnosis without creating bleeding risk, assess hereditary/multifocal disease, and choose observation, radiation or surgery while counseling about vascular and cranial-nerve morbidity?",
        "answer_text": "A classic hypervascular carotid-bifurcation lesion should be characterized radiographically rather than routinely biopsied. MRI/MRA or CTA defines vascularity, carotid displacement/encasement, skull-base extension and surgical complexity; functional imaging can be useful for multifocal/metastatic evaluation in selected patients. History should address catecholamine symptoms and family history, and biochemical testing plus genetic counseling/testing should be considered according to paraganglioma phenotype, age, multiplicity and contemporary hereditary-risk practice. Treatment is individualized by age, growth, symptoms, cranial neuropathy, tumor size/complexity, comorbidity and patient priorities. Observation with serial imaging is reasonable for selected indolent tumors; radiation can provide durable control when operative morbidity is unattractive; surgery offers removal but carries increasing carotid and lower-cranial-nerve risk with larger/encasing lesions. Operative planning must anticipate proximal/distal vascular control, vagal/hypoglossal/sympathetic injury and possible vascular-reconstruction needs. Rapid growth, new cranial neuropathy, concerning secretory symptoms or threatened vascular/skull-base structures changes urgency and workup.",
        "explanation": "The key management tradeoff is tumor control versus treatment morbidity. A small asymptomatic tumor in an older patient is different from a growing symptomatic lesion in a young patient with hereditary disease.",
        "board_pearl": "A classic carotid body paraganglioma is an imaging-and-risk-stratification diagnosis; sticking a needle into it is usually not the next step.",
        "depth_layers_v185": {"foundation": "Recognize a hypervascular carotid-bifurcation paraganglioma and its cranial-nerve/vascular relationships.", "application": "Use vascular imaging, hereditary evaluation and growth/symptom assessment to choose observation, radiation or surgery.", "senior_decision": "Counsel explicitly about lower-cranial-nerve and carotid morbidity and plan vascular control/reconstruction when surgery is selected."},
        "common_traps_v185": ["Routine biopsy of a classic hypervascular paraganglioma adds bleeding risk without usually adding needed diagnostic information.", "Choosing surgery from tumor size alone ignores age, growth, hereditary context and the functional cost of lower-cranial-nerve injury."],
        "deliberate_review_v185": "Expanded the existing observation/radiation/surgery sentence into imaging, hereditary assessment, Shamblin-type vascular complexity and morbidity-based decision-making."
    },
    "cc-v112-rec-pediatric-otolaryngology-subglottic-hemangioma": {
        "concept_id": "v6-pediatric-otolaryngology-subglottic-hemangioma",
        "canonical_topic": "Subglottic Hemangioma",
        "prompt": "An infant has recurrent 'croup' with progressively persistent biphasic stridor and increased work of breathing between viral illnesses. How do you confirm a subglottic hemangioma, stabilize the airway, use beta-blocker therapy safely, and decide when endoscopic or open airway intervention is required?",
        "answer_text": "The changing pattern—progressive or persistent biphasic stridor rather than episodic uncomplicated croup—should trigger airway evaluation. Flexible laryngoscopy can assess the supraglottis and vocal folds, but direct laryngoscopy/bronchoscopy may be needed to define subglottic location, degree of obstruction and alternative lesions; imaging is selective when extent or diagnosis remains uncertain. In a stable infant with a typical infantile hemangioma, systemic propranolol is foundational therapy after appropriate cardiovascular/feeding safety assessment and with dosing/monitoring coordinated to age and comorbidity. The airway plan comes first in a child with significant distress: minimize agitation, maintain oxygenation and involve pediatric anesthesia/airway expertise early rather than forcing an examination that precipitates obstruction. Failure to improve on appropriate medical therapy, severe fixed obstruction, recurrent life-threatening events or inability to maintain a safe airway can require endoscopic debulking or other airway intervention, with tracheostomy/open reconstruction reserved for selected refractory situations. Feeding intolerance, hypoglycemia risk during illness and associated cutaneous/distribution clues should also inform management.",
        "explanation": "The important discrimination is persistent/progressive subglottic obstruction versus routine viral croup. Modern treatment is primarily medical, but severe airway physiology still dictates immediate stabilization and rescue planning.",
        "board_pearl": "Repeated croup that never fully goes away deserves an airway diagnosis, not another reflexive croup treatment.",
        "depth_layers_v185": {"foundation": "Recognize progressive biphasic stridor and a subglottic vascular lesion phenotype.", "application": "Define obstruction endoscopically and use propranolol with age-appropriate cardiovascular/feeding safety.", "senior_decision": "Prioritize airway stabilization and escalate refractory or severe obstruction to procedural airway management."},
        "common_traps_v185": ["Repeatedly treating persistent biphasic stridor as viral croup delays diagnosis of a fixed or evolving airway lesion.", "Focusing on propranolol dosing while an infant is tiring or obstructing reverses the correct priority: airway physiology comes first."],
        "deliberate_review_v185": "Expanded a 15-word beta-blocker statement into diagnostic endoscopy, medication safety, airway stabilization and refractory-disease escalation."
    },
    "cc-v112-mgt-general-ent-emergencies-airway-foreign-body": {
        "concept_id": "v6-general-ent-emergencies-airway-foreign-body",
        "canonical_topic": "Airway Foreign Body",
        "prompt": "A toddler has a witnessed choking episode followed by persistent unilateral wheeze; chest radiographs are normal and the child is currently oxygenating. What findings justify bronchoscopy despite normal imaging, how should the OR and airway rescue plan be organized, and how does management change if complete obstruction develops?",
        "answer_text": "A convincing aspiration history with persistent focal respiratory findings can justify bronchoscopy even when plain films are normal because many foreign bodies are radiolucent and imaging sensitivity is imperfect. Keep the child calm and avoid unnecessary agitation while assessing work of breathing, oxygenation, air entry and evidence of a ball-valve or fixed obstruction. For a stable but high-suspicion case, coordinate rigid bronchoscopy with an experienced pediatric airway/anesthesia team, appropriate ventilating bronchoscopes, optical forceps/baskets, suction and a range of instrument sizes. Discuss ventilation strategy and the possibility that induction or manipulation can convert partial obstruction into complete obstruction. Remove the object under direct visualization, inspect the involved and contralateral bronchi, manage granulation/secretions and reassess for retained fragments or airway injury. If complete obstruction develops, perform immediate age-appropriate choking rescue; if the object remains inaccessible and oxygenation fails, transition rapidly to the established emergency airway/bronchoscopic rescue plan. Do not delay definitive bronchoscopy solely to obtain increasingly elaborate imaging when clinical suspicion is high.",
        "explanation": "Airway foreign-body management is driven by history and physiology, not by a requirement for an abnormal x-ray. The anesthetic and extraction plan must anticipate migration and total obstruction.",
        "board_pearl": "Normal chest imaging does not clear a classic aspiration event with persistent focal findings.",
        "depth_layers_v185": {"foundation": "Recognize sudden choking and focal wheeze as a possible radiolucent airway foreign body.", "application": "Use clinical suspicion to select rigid bronchoscopy and prepare extraction/ventilation equipment deliberately.", "senior_decision": "Plan for conversion from partial to complete obstruction and execute age-appropriate immediate rescue when oxygenation fails."},
        "common_traps_v185": ["Using a normal radiograph to cancel bronchoscopy can leave a radiolucent foreign body in place.", "Entering the OR without an explicit shared ventilation and total-obstruction rescue plan makes a predictable airway transition dangerous."],
        "deliberate_review_v185": "Expanded the existing rigid-bronchoscopy recommendation into imaging limitations, OR setup, extraction inspection and complete-obstruction rescue."
    },
    "cc-v112-rec-otology-neurotology-temporal-bone-anatomy": {
        "concept_id": "v6-otology-neurotology-temporal-bone-anatomy",
        "canonical_topic": "Temporal Bone Anatomy",
        "prompt": "During a cortical mastoidectomy, the resident becomes disoriented after opening the antrum and asks which boundaries should be re-established before further drilling. How do you organize temporal-bone anatomy spatially, which landmarks protect the facial nerve/labyrinth/dura/sigmoid, and what findings should make you stop and reassess?",
        "answer_text": "Re-establish known boundaries rather than drilling toward a memorized depth. Think from the external auditory canal and tympanic membrane into the epitympanum/antrum and mastoid while continuously identifying the tegmen superiorly, sigmoid sinus posteriorly, posterior canal wall and facial recess region anteriorly, and labyrinthine structures medially. The lateral semicircular canal is a key antral landmark; the facial nerve's tympanic and mastoid segments, second genu, digastric ridge and short process of the incus help orient deeper work. CT should be reviewed preoperatively for tegmen height, sigmoid position, mastoid aeration, labyrinth, facial-nerve anomalies and carotid/jugular variants. If anatomy is no longer trustworthy, stop drilling, irrigate, improve exposure and re-identify multiple fixed landmarks before proceeding. Unexpected facial stimulation/weakness, blue-lined labyrinth, CSF leak, brisk venous bleeding or suspected carotid injury requires complication-specific rescue rather than blind packing or continued drilling. The safe mastoidectomy is a boundary-based three-dimensional operation.",
        "explanation": "Temporal-bone surgery is spatial localization. Safe drilling depends on maintaining several simultaneously verified boundaries; one assumed landmark is not enough when anatomy is distorted.",
        "board_pearl": "When lost in the mastoid, stop and find boundaries—do not drill until the anatomy looks familiar again.",
        "depth_layers_v185": {"foundation": "Map EAC/middle ear/mastoid/otic capsule and the facial nerve, tegmen, sigmoid, carotid and jugular relationships.", "application": "Use CT and operative landmarks to maintain a multi-boundary orientation during mastoid drilling.", "senior_decision": "Stop when landmarks are lost and initiate specific rescue for facial-nerve, labyrinthine, dural, venous or arterial injury."},
        "common_traps_v185": ["Drilling toward a remembered depth instead of maintaining tegmen, sigmoid, canal-wall and labyrinth boundaries invites injury when anatomy varies.", "Blindly packing brisk deep bleeding before identifying whether it is venous or arterial can obscure a major vascular complication."],
        "deliberate_review_v185": "Expanded a 16-word anatomy-dependent management statement into operative boundary mapping, CT review, stop points and complication rescue."
    },
    "cc-v112-rec-rhinology-allergy-skull-base-juvenile-nasopharyngeal-angiofibroma": {
        "concept_id": "v6-rhinology-allergy-skull-base-juvenile-nasopharyngeal-angiofibroma",
        "canonical_topic": "Juvenile Nasopharyngeal Angiofibroma",
        "prompt": "An adolescent boy has recurrent brisk epistaxis and unilateral obstruction; MRI/CTA show a markedly enhancing nasopharyngeal mass extending through the sphenopalatine foramen toward the pterygopalatine fossa. How do you establish the diagnosis safely, stage vascular/skull-base extension, and plan embolization and resection without creating avoidable hemorrhage?",
        "answer_text": "A classic juvenile nasopharyngeal angiofibroma is primarily an imaging diagnosis; routine office biopsy should be avoided because the tumor is highly vascular. Contrast CT/MRI defines the nasopharyngeal origin, bony remodeling and skull-base/intracranial extension, while angiographic evaluation clarifies dominant arterial supply and dangerous anastomoses when embolization is planned. Stage and map extension into the pterygopalatine/infratemporal fossae, sphenoid and skull base because these relationships determine exposure and control. Preoperative embolization can reduce blood loss in appropriately selected cases, but timing, embolic agent and vascular anatomy require experienced interventional planning, particularly when supply approaches ophthalmic or intracranial circulations. Endoscopic resection is feasible for many tumors; more extensive disease may require combined/open strategies or selected nonsurgical management. The OR plan should include large-bore access, blood availability, proximal vascular-control strategy and clear stop/escalation points for uncontrolled hemorrhage. Acute hemodynamic instability from epistaxis is treated as hemorrhage first, before definitive tumor surgery.",
        "explanation": "JNA is a vascular-anatomy problem before it is a biopsy problem. Imaging establishes diagnosis and extension while angiography/embolization planning must respect dangerous vascular connections.",
        "board_pearl": "An adolescent male with classic hypervascular nasopharyngeal imaging should not get a casual office biopsy.",
        "depth_layers_v185": {"foundation": "Recognize the classic adolescent male, epistaxis and hypervascular nasopharyngeal phenotype.", "application": "Use CT/MRI and vascular imaging to stage skull-base extension and arterial supply without biopsy.", "senior_decision": "Plan embolization/resection around dangerous anastomoses, blood-loss rescue and extension-driven surgical exposure."},
        "common_traps_v185": ["Biopsying a classic JNA in clinic creates avoidable hemorrhage risk when imaging is already diagnostic.", "Treating embolization as automatic rather than mapping ophthalmic/intracranial anastomoses can exchange surgical blood loss for ischemic catastrophe."],
        "deliberate_review_v185": "Expanded a 17-word embolization/resection statement into safe diagnosis, extension mapping, vascular planning and hemorrhage rescue."
    },
    "cc-v112-rec-laryngology-voice-swallowing-aspiration-prevention-surgery": {
        "concept_id": "v6-laryngology-voice-swallowing-aspiration-prevention-surgery",
        "canonical_topic": "Aspiration-Prevention Surgery",
        "prompt": "A previously irradiated patient has recurrent aspiration pneumonias despite maximal swallowing therapy, feeding modification and prior focal procedures; instrumental testing shows profound global pharyngeal failure and an unsafe nonfunctional larynx. How do you decide when irreversible aspiration-prevention surgery is justified, choose among separation/diversion/laryngectomy strategies, and counsel about voice, stoma and wound consequences?",
        "answer_text": "First confirm that aspiration is clinically consequential, refractory and unlikely to be corrected by a reversible focal intervention. Review instrumental swallowing findings, pulmonary events, nutrition, cognition/goals, laryngeal sensation and closure, pharyngeal propulsion, upper-esophageal function and current cancer status; exclude recurrent tumor or another correctable obstructive lesion. Continue rehabilitation, diet/feeding strategies and targeted procedures when they can plausibly restore safe swallowing. When repeated pulmonary injury persists because the native larynx cannot protect the airway, definitive separation becomes a quality-of-life and survival decision. Laryngotracheal separation or diversion can protect the lungs while retaining the larynx anatomically; functional or total laryngectomy may be appropriate for a profoundly nonfunctional irradiated larynx, particularly when other laryngeal pathology coexists. Counseling must explicitly address permanent separation of breathing from the upper aerodigestive tract, loss/change of natural voice, alaryngeal communication options, permanent stoma care and elevated fistula/wound risk after radiation. The endpoint is preventing pulmonary injury, not merely improving a swallow-study score.",
        "explanation": "These operations intentionally trade native laryngeal airflow/voice for pulmonary protection. The irreversible step is justified only when aspiration is severe, refractory and driven by a larynx/pharynx that cannot be rehabilitated adequately.",
        "board_pearl": "For life-threatening chronic aspiration, the senior decision is when preserving the larynx is more dangerous than separating it from the lungs.",
        "depth_layers_v185": {"foundation": "Localize aspiration to glottic incompetence, sensory loss, global pharyngeal failure or a nonfunctional larynx.", "application": "Exhaust plausible reversible rehabilitation/targeted options and quantify pulmonary/nutritional consequence.", "senior_decision": "Choose irreversible separation/diversion/laryngectomy only with explicit counseling about stoma, voice rehabilitation and irradiated wound risk."},
        "common_traps_v185": ["Choosing irreversible airway separation from a single abnormal swallow study ignores reversibility, goals and actual pulmonary consequence.", "Calling an irradiated larynx 'preserved' despite recurrent aspiration pneumonia can prioritize anatomy over patient function and survival."],
        "deliberate_review_v185": "Replaced a reveal that merely repeated the recognition sentence with candidacy, operation-selection and irreversible-consequence counseling."
    },
    "cc-v112-rec-general-ent-emergencies-post-tonsillectomy-hemorrhage": {
        "concept_id": "v6-general-ent-emergencies-post-tonsillectomy-hemorrhage",
        "canonical_topic": "Post-Tonsillectomy Hemorrhage",
        "prompt": "A child presents one week after tonsillectomy after a large episode of hematemesis; bleeding has stopped, but there is a clot in the tonsillar fossa and the child is tachycardic. How do you resuscitate and risk-stratify this sentinel bleed, prepare the shared airway, and decide observation versus urgent operative control?",
        "answer_text": "Treat the history and clot burden seriously even when active bleeding has stopped. Assess airway, mental status, perfusion and hemodynamics; place IV access, send CBC and type-and-screen/crossmatch according to severity, correct relevant coagulopathy and begin balanced resuscitation when blood loss is significant. Keep suction available, avoid repeated traumatic manipulation of an uncooperative child and involve anesthesia/OR early because swallowed blood creates a full-stomach airway and rebleeding can be abrupt. Active bleeding, recurrent significant bleeding, hemodynamic abnormality, a concerning fossa clot or inability to observe safely lowers the threshold for operative control. Temporary antifibrinolytic/local measures may be used according to protocol while definitive care is organized, but should not delay source control in an unstable patient. In the OR, use a hemorrhage/full-stomach induction plan, evacuate clot, identify and cauterize/ligate the source, inspect both fossae and account for airway/stomach blood before emergence. Disposition after a minor self-limited event still requires an observation plan and explicit return precautions because a sentinel bleed can precede a brisk recurrence.",
        "explanation": "Post-tonsillectomy hemorrhage is both a blood-loss and shared-airway emergency. A temporarily dry oropharynx does not erase the significance of a convincing bleed, tachycardia or retained clot.",
        "board_pearl": "The child who stopped bleeding before you arrived can still be the child who exsanguinates on the next episode—treat the history, physiology and clot seriously.",
        "depth_layers_v185": {"foundation": "Recognize secondary hemorrhage, sentinel bleeding and aspiration/full-stomach airway risk.", "application": "Resuscitate, obtain blood access/labs and involve anesthesia/OR based on history, clot and hemodynamics.", "senior_decision": "Choose urgent operative control for active/recurrent/concerning bleeding and execute a shared hemorrhage-airway plan."},
        "common_traps_v185": ["Discharging solely because the child is not actively bleeding can miss a sentinel event with retained clot and ongoing rebleed risk.", "Repeated bedside probing of an anxious child can restart hemorrhage and worsen airway contamination without providing durable source control."],
        "deliberate_review_v185": "Expanded a 28-word workup answer into sentinel-bleed risk, resuscitation, shared-airway planning, operative thresholds and disposition."
    },
}


def apply_concept_check_task_alignment_v185(checks, deep_modules, v6_item_id):
    by_id = {str(q.get("id") or ""): q for q in checks or []}
    repaired, missing, link_mismatch = [], [], []
    for qid, payload in COHORT.items():
        q = by_id.get(qid)
        if q is None:
            missing.append(qid); continue
        module = _find_module(q, deep_modules, v6_item_id)
        domain = str(q.get("domain") or "")
        resolved_topic = str(module.get("topic") or "") if module else ""
        resolved_cid = v6_item_id(domain, resolved_topic) if module and domain else None
        if not module or resolved_topic != payload["canonical_topic"] or resolved_cid != payload["concept_id"] or q.get("concept_id") != resolved_cid:
            link_mismatch.append(qid); continue
        for key in ("prompt", "answer_text", "explanation", "board_pearl", "depth_layers_v185", "common_traps_v185", "deliberate_review_v185"):
            q[key] = payload[key]
        q["task_alignment_v185"] = True
        q.pop("choices", None); q.pop("answer", None); q.pop("why_wrong", None)
        repaired.append(qid)
    return {"repaired": repaired, "missing": missing, "link_mismatch": link_mismatch}

__all__ = ["COHORT", "apply_concept_check_task_alignment_v185"]
