"""v18.9 — high-yield post-completion Concept Check depth cohort.

Selected from the validated V188 live-canonical backlog. This pass favors
clinically consequential facial-trauma/functional-nasal topics plus chronic
aspiration and deep-neck infection over lower-yield cosmetic material. Exact
canonical resolution is required before mutation.
"""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-facial-plastics-trauma-alar-retraction-nasal-vestibular-stenosis":{
"concept_id":"v6-facial-plastics-trauma-alar-retraction-nasal-vestibular-stenosis","canonical_topic":"Alar Retraction / Nasal Vestibular Stenosis",
"prompt":"A 41-year-old has progressive unilateral nasal obstruction and visible alar retraction after prior Mohs reconstruction and scar revision. Examination shows fixed vestibular narrowing with external-valve collapse that does not resolve with decongestion. How should you distinguish dynamic collapse from fixed stenosis, identify the missing lining versus structural support, and choose scar release, lining reconstruction, cartilage grafting, stenting, or staged reconstruction while avoiding restenosis?",
"answer_text":"Start by defining whether the obstruction is primarily dynamic lateral-wall collapse, fixed scar contracture, loss of vestibular lining, loss of alar structural support, or a combination. Decongestion, modified Cottle-type support, inspection of the nostril sill/alar rim/vestibule, and comparison with the contralateral side help localize the limiting segment. Purely dynamic collapse may improve with support or targeted structural grafting, but fixed vestibular stenosis generally requires release of cicatricial bands and restoration of both lining and framework when either is deficient. Small lining deficits may be managed with local mucosal or skin rearrangement; larger deficits may require composite or staged reconstructive solutions. Cartilage support such as alar batten or rim grafting is useful when the external valve lacks rigidity, but grafting alone will fail if dense scar remains tethered. Postoperative stenting can help maintain the newly created lumen while re-epithelialization and scar remodeling occur. The senior decision is to reconstruct the specific missing layer and to minimize opposing raw surfaces, because simple dilation or isolated scar division in a lining-deficient vestibule predictably restenoses.",
"explanation":"Vestibular stenosis is a lining-and-support problem, not merely a small nostril. Durable repair depends on identifying fixed scar, missing lining, and weak alar framework separately.",
"board_pearl":"Release without lining replacement and support invites restenosis; rebuild the layer that is actually missing.",
"depth_layers_v189":{"foundation":"Differentiate fixed vestibular stenosis from dynamic external-valve collapse and identify scar, lining loss, and support deficiency.","application":"Match scar release, lining reconstruction, cartilage grafting, and postoperative stenting to the anatomic deficit.","senior_decision":"Use staged or composite reconstruction when opposing raw surfaces or major lining loss make simple release predictably nondurable."},
"common_traps_v189":["Using a batten graft to treat a densely scarred fixed vestibule may stiffen the wall without actually enlarging the cicatricial lumen.","Performing aggressive scar release without replacing deficient lining creates opposing raw surfaces that can contract back into restenosis."],
"deliberate_review_v189":"Expanded a brief support-versus-scar statement into layered diagnosis, reconstructive planning, restenosis prevention, and staged decision-making."},
"cc-v112-rec-facial-plastics-trauma-functional-septorhinoplasty":{
"concept_id":"v6-facial-plastics-trauma-functional-septorhinoplasty","canonical_topic":"Functional Septorhinoplasty",
"prompt":"A 35-year-old has persistent nasal obstruction despite optimized rhinitis therapy and prior septoplasty. Examination shows a narrow internal nasal valve, weak lateral wall with inspiration, caudal septal deviation, and asymmetric tip support. How should you determine which structural abnormalities actually cause obstruction and plan septal correction, spreader grafting, lateral-wall support, osteotomies, or tip-support maneuvers without creating new cosmetic or airway problems?",
"answer_text":"Functional septorhinoplasty begins with mechanism-based localization rather than repeating septoplasty by default. Confirm that reversible mucosal disease has been optimized, then document septal deviation, internal-valve angle, dynamic lateral-wall collapse, external-valve weakness, turbinate contribution, dorsal width, caudal septal support, and tip position. A modified Cottle maneuver can suggest where support helps but is not by itself a diagnosis. Spreader grafts or equivalent middle-vault reconstruction can widen or stabilize a narrowed internal valve; batten or lateral-crural support addresses dynamic sidewall collapse; caudal septal reconstruction treats anterior septal deformity and loss of tip support; osteotomies are selected when bony vault position or width contributes to functional narrowing. Because these maneuvers change the nasal framework, consent must include visible contour change, asymmetry, graft visibility/warping, persistent obstruction, and revision risk. The senior operation should correct the smallest set of structural causes that explains the patient's obstruction while preserving or restoring the support relationships that keep the valve open during inspiration.",
"explanation":"Persistent obstruction after prior septoplasty often reflects uncorrected valve or support pathology. Functional rhinoplasty should be driven by the exact site and mechanism of collapse.",
"board_pearl":"Do not repeat a septoplasty for a valve problem; localize the obstruction before choosing the graft or osteotomy.",
"depth_layers_v189":{"foundation":"Separate mucosal obstruction, septal deviation, internal-valve narrowing, and dynamic external-valve collapse.","application":"Match spreader, batten/lateral-crural, caudal-septal, osteotomy, and tip-support maneuvers to the responsible structural deficit.","senior_decision":"Correct the minimum necessary framework while counseling about aesthetic change, graft complications, persistent obstruction, and revision."},
"common_traps_v189":["Treating every postoperative obstruction as residual septal deviation can miss internal-valve narrowing or lateral-wall insufficiency that a second septoplasty will not fix.","Over-widening or over-stiffening the nose without understanding the collapse vector can trade obstruction for an unnatural contour or a different valve problem."],
"deliberate_review_v189":"Expanded a brief fixed-obstruction statement into mechanism-based valve localization, structural maneuver selection, and functional-aesthetic tradeoffs."},
"cc-v112-rec-facial-plastics-trauma-nasal-fracture":{
"concept_id":"v6-facial-plastics-trauma-nasal-fracture","canonical_topic":"Nasal Fracture",
"prompt":"A 22-year-old presents six hours after an altercation with nasal deformity, obstruction, epistaxis, and marked swelling. He has no visual symptoms or malocclusion. How should you evaluate for septal hematoma and associated midface/skull-base injury, decide whether imaging is needed, time closed reduction, and recognize when delayed reassessment is appropriate versus when immediate intervention is mandatory?",
"answer_text":"The immediate priorities are airway, bleeding control, ocular and midface screening, and direct intranasal examination for septal hematoma. A septal hematoma is a boggy or fluctuant collection lifting the mucoperichondrium from the septal cartilage and requires urgent drainage with appropriate follow-up because cartilage depends on perichondrial blood supply; delay risks infection, necrosis, and saddle deformity. Isolated uncomplicated nasal fractures are usually diagnosed clinically and do not require routine CT. Imaging is appropriate when the mechanism or examination suggests NOE injury, orbital fracture, significant maxillary or frontal injury, CSF leak, or other complex facial trauma. If edema prevents reliable assessment of deformity and there is no emergency, reassessment after swelling improves is reasonable. Closed reduction is generally performed after the deformity can be assessed but before fracture healing makes manipulation difficult; timing is individualized by age, edema, displacement, and local practice. Open injuries, uncontrolled epistaxis, septal hematoma/abscess, CSF rhinorrhea, ocular emergency, or major associated facial instability require immediate escalation rather than routine delayed fracture follow-up.",
"explanation":"Nasal fracture management is mostly clinical, but the septal hematoma is the time-sensitive exception and complex injury signs determine when CT and broader trauma management are needed.",
"board_pearl":"Swelling can wait; a septal hematoma cannot.",
"depth_layers_v189":{"foundation":"Perform a complete nasal, septal, ocular, and midface examination and recognize septal hematoma as an emergency.","application":"Use CT selectively for suspected complex facial/skull-base injury and time reduction after edema improves but before fixation.","senior_decision":"Escalate immediately for hematoma/abscess, uncontrolled hemorrhage, CSF leak, ocular compromise, open injury, or unstable associated facial trauma."},
"common_traps_v189":["Ordering CT for every isolated nasal fracture adds little when the diagnosis and treatment plan are already clinical and no complex-injury signs are present.","Deferring all intranasal examination until swelling resolves can miss a septal hematoma during the window when cartilage injury is still preventable."],
"deliberate_review_v189":"Expanded a basic imaging answer into emergency septal assessment, selective CT indications, reduction timing, and associated-injury escalation."},
"cc-v112-rec-head-neck-oncology-nonfunctional-larynx-chronic-aspiration-after-cancer-therapy":{
"concept_id":"v6-head-neck-oncology-nonfunctional-larynx-chronic-aspiration-after-cancer-therapy","canonical_topic":"Nonfunctional Larynx / Chronic Aspiration After Cancer Therapy",
"prompt":"A disease-free head-and-neck cancer survivor has severe radiation fibrosis, silent aspiration of secretions and oral intake, three pneumonias in a year, feeding-tube dependence, and profound dysphagia despite expert rehabilitation. How should you determine whether additional rehabilitation or targeted endoscopic treatment is still worthwhile and when to discuss aspiration-prevention surgery or functional total laryngectomy despite the absence of recurrent cancer?",
"answer_text":"First confirm that the larynx is oncologically disease-free and define why it is functionally failing. Instrumental swallowing evaluation should characterize secretion burden, timing and volume of aspiration, pharyngeal propulsion, residue, airway sensation, UES opening, and whether compensatory strategies meaningfully reduce risk. Treat reversible contributors when present—stenosis, focal UES dysfunction, poor dentition, xerostomia-related bolus problems, or a discrete structural lesion—but recognize when global fibrosis, neuropathy, and sensory loss make further local procedures unlikely to restore safe swallowing. Feeding-tube dependence does not eliminate aspiration of saliva or refluxate. Recurrent aspiration pneumonia, inability to handle secretions, progressive pulmonary injury, major quality-of-life loss, and failure of high-quality rehabilitation justify discussion of aspiration-prevention procedures. Options can include laryngotracheal separation or, in selected cancer survivors, functional total laryngectomy; these sacrifice normal laryngeal airflow and natural voice but can provide durable separation of the airway and alimentary tract. The senior decision is goals-based: compare the burden of irreversible loss of laryngeal function with the ongoing morbidity of a larynx that is anatomically preserved but no longer safely functional.",
"explanation":"An anatomically preserved larynx can become functionally dangerous after cancer therapy. Recurrent pulmonary morbidity despite optimized rehabilitation is a legitimate indication to discuss definitive aspiration control.",
"board_pearl":"Organ preservation is not the same as function preservation when the preserved larynx repeatedly injures the lungs.",
"depth_layers_v189":{"foundation":"Characterize aspiration mechanism, secretion burden, sensation, pharyngeal strength, and reversible structural contributors after cancer therapy.","application":"Exhaust meaningful rehabilitation and targeted reversible treatments while recognizing that tube feeding does not stop secretion aspiration.","senior_decision":"Discuss irreversible aspiration-prevention surgery or functional laryngectomy when recurrent pneumonia and pulmonary risk outweigh preservation of natural laryngeal function."},
"common_traps_v189":["Assuming a gastrostomy solves aspiration can miss ongoing silent aspiration of secretions and refluxate that continues to damage the lungs.","Repeating focal dilation or therapy despite diffuse radiation fibrosis and absent airway sensation can delay a needed goals-of-care discussion about definitive aspiration control."],
"deliberate_review_v189":"Expanded a short rehabilitation statement into mechanism-based swallowing assessment, treatment limits, pulmonary escalation thresholds, and irreversible aspiration-control tradeoffs."},
"cc-v112-rec-general-ent-emergencies-deep-neck-space-infection":{
"concept_id":"v6-general-ent-emergencies-deep-neck-space-infection","canonical_topic":"Deep Neck Space Infection",
"prompt":"A 54-year-old with diabetes has worsening neck swelling, trismus, muffled voice, fever, and CT showing a multiloculated parapharyngeal collection extending toward the carotid sheath with early superior mediastinal inflammatory change. How should you prioritize airway control, antibiotics, source control, surgical approach, and escalation for vascular or descending mediastinal complications?",
"answer_text":"Treat this as an airway-and-sepsis problem first. Assess work of breathing, stridor, secretion handling, mouth opening, floor-of-mouth displacement, and the predicted difficulty of induction. Significant distortion or progressive symptoms warrant a controlled airway plan with anesthesia and ENT, often preserving spontaneous ventilation until the airway is secured and with surgical-airway backup available. Start broad intravenous antimicrobial therapy appropriate to oral flora, staphylococci, gram-negative risk, and the patient's immune status, then narrow to cultures. Imaging defines the involved spaces, vascular relationship, gas, thrombosis, and inferior extension. Drainage is indicated for a mature or sizable abscess, airway compromise, sepsis, progression despite medical therapy, or anatomy unlikely to resolve with antibiotics alone. Medial accessible collections may permit transoral drainage, whereas lateral, carotid-space, multiloculated, or low-neck disease often requires transcervical exposure with drainage of all communicating spaces. Carotid sheath involvement raises concern for vascular erosion or septic thrombosis, and descending necrotizing mediastinitis requires urgent thoracic collaboration because cervical drainage alone may be inadequate. Persistent shock or clinical worsening after drainage should trigger a search for missed compartments, mediastinal spread, vascular complication, or inadequate source control rather than simple antibiotic escalation alone.",
"explanation":"Deep-neck infection can deteriorate from airway distortion, sepsis, vascular catastrophe, or descending mediastinitis. Airway planning and anatomic source control must proceed in parallel.",
"board_pearl":"In deep-neck infection, a secure airway and complete source control matter more than simply choosing a broader antibiotic.",
"depth_layers_v189":{"foundation":"Recognize airway-threat and sepsis features and map the involved deep-neck spaces on imaging.","application":"Coordinate controlled airway management, broad IV therapy, and transoral versus transcervical drainage according to collection anatomy.","senior_decision":"Escalate for carotid-space vascular complications, persistent sepsis, missed compartments, or descending mediastinitis with thoracic involvement."},
"common_traps_v189":["Paralyzing a patient with severe trismus and distorted pharyngeal anatomy before a shared rescue plan can convert a threatened airway into a cannot-intubate emergency.","Draining only the most obvious cervical pocket while ignoring communicating spaces or mediastinal extension can leave the true septic source uncontrolled."],
"deliberate_review_v189":"Expanded a short drainage answer into airway strategy, antibiotic/source-control sequencing, approach selection, vascular risk, and mediastinal escalation."}
}

def apply_concept_check_task_alignment_v189(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id)
        topic=str(module.get('topic') or '') if module else ''
        cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']:
            link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v189']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
