"""v20.22 — deepen exact-live Ankyloglossia / Maxillary Frenulum after validated v20.21 production."""
from concept_check_board_repair_v177 import _find_module

QIDS = ("cc-v112-rec-pediatric-otolaryngology-ankyloglossia-maxillary-frenulum",)
CID = "v6-pediatric-otolaryngology-ankyloglossia-maxillary-frenulum"
TOPIC = "Ankyloglossia / Maxillary Frenulum"

SOURCE_REFS_V222 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive corpus, Drive id 18QGOAaZhvH-kEUJxtwDWXn1ho86PRY-t; pediatric oral cavity/floor-of-mouth and congenital pediatric ENT framework cross-referenced 2026-09-09. The connected compressed PDF could not be text-fetched reliably for a specific current tongue-tie indication statement, so current indications are not attributed to Cummings alone.","role":"durable foundation: pediatric oral/floor-of-mouth anatomy and congenital ENT framework; explicit provenance boundary avoids inventing a management statement not recoverable from the connected text"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy Drive id 14E4Iy4XCjGPSyMT5n7uyURGtIDnhi-52; Chapter 9 Pediatric Otolaryngology and general oral/floor-of-mouth material cross-referenced 2026-09-09. The connected text did not provide a sufficiently specific current ankyloglossia indication rule, so it is used as contextual rather than sole management authority.","role":"resident framework and anatomy/context cross-check; current candidacy is deliberately governed by newer specialty guidance"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy Drive id 112c9y0fb1z_7OLP4aLlAG2z-r8weuXvR; pediatric ankyloglossia and oral-cavity anatomy cross-referenced 2026-09-09. The text describes the frenulum as attaching the anterior-inferior tongue to the floor of mouth/gingiva with Wharton ducts on either side and recognizes that congenital shortening can reduce mobility and interfere with feeding or speech.","role":"durable anatomy and traditional clinical phenotype: tongue mobility, feeding/speech relationship, floor-of-mouth/Wharton duct danger anatomy"},
    {"type":"guideline","citation":"Thomas J, et al. Identification and Management of Ankyloglossia and Its Effect on Breastfeeding in Infants: Clinical Report. Pediatrics. 2024;154(2):e2024067605. doi:10.1542/peds.2024-067605. Published 2024-07-29; reviewed 2026-09-09.","role":"current pediatric guidance: symptomatic functional definition, full breastfeeding assessment, no prophylactic treatment, posterior-tie caution, no breastfeeding indication for labial/buccal frenula, no laser superiority, no routine postoperative stretching"},
    {"type":"consensus","citation":"Messner AH, et al. Clinical Consensus Statement: Ankyloglossia in Children. Otolaryngol Head Neck Surg. 2020;162(5):597-611. PMID: 32283998. doi:10.1177/0194599820915457.","role":"AAO-HNS expert consensus and explicit disagreement/knowledge-gap framework across breastfeeding infants, older children, frenotomy, maxillary labial frenulum, buccal tie and sleep-apnea claims"},
    {"type":"society_guidance","citation":"LeFort Y, et al. Academy of Breastfeeding Medicine Position Statement on Ankyloglossia in Breastfeeding Dyads. Breastfeed Med. 2021;16(4):278-281. PMID: 33852342. doi:10.1089/bfm.2021.29179.ylf.","role":"breastfeeding-medicine perspective: functional dyad assessment, conservative optimization and individualized shared decision-making amid limited high-quality evidence"},
    {"type":"society_guidance","citation":"American Academy of Pediatric Dentistry. Policy on Management of the Frenulum in Pediatric Patients. Revised 2022; current Reference Manual of Pediatric Dentistry 2026-2027 page reviewed 2026-09-09.","role":"current dental boundary: alternative causes of breastfeeding difficulty are more common, not every ankyloglossia needs surgery, team-based planning, uncertainty about long-term indications and outcomes"},
    {"type":"current_review","citation":"Zyzynska K, Tretiakow D, Skorek A. Lingual frenotomy for breastfeeding difficulties: indications, surgical techniques and multidisciplinary care in infants and young children. Eur Arch Otorhinolaryngol. 2026 Aug 3. PMID: 42543437. doi:10.1007/s00405-026-10474-8.","role":"current peer-reviewed synthesis: selective short-term benefit after persistent documented breastfeeding dysfunction despite skilled support; weak evidence for nonspecific speech/reflux/distress indications; multidisciplinary care reduces misdiagnosis and avoidable procedures"},
]

PROMPT = """An otherwise healthy 3-week-old is referred for a visible 'tongue-tie' and prominent maxillary labial frenulum because breastfeeding is painful and inefficient. Weight gain is borderline, but the family has not yet had an observed feed with an experienced lactation clinician and asks for laser release of the tongue and upper-lip 'tie' today to prevent later speech, dental and sleep problems. As the senior ENT resident, how do you decide whether this infant has symptomatic ankyloglossia, what must be assessed and treated before surgery, when is lingual frenotomy reasonable, what claims or procedures should you decline, what anatomy and complications matter during release, and how would your reasoning change for an older child referred primarily for speech or a maxillary diastema? Explicitly distinguish durable anatomy from current areas of evidence, consensus and disagreement."""

ANSWER = """Foundation — ankyloglossia is a functional diagnosis, not a photograph. A visible lingual frenulum is normal anatomy, and morphology alone does not establish disease. K.J. Lee's durable anatomy remains useful: the lingual frenulum joins the anterior-inferior tongue to the floor of mouth/gingiva, Wharton duct papillae lie on either side, and congenital restriction can reduce tongue mobility. The modern question is whether that restriction is actually causing an important function problem in this child. Current AAP terminology is especially useful in infants: symptomatic ankyloglossia is a restrictive lingual frenulum causing breastfeeding difficulty that has not improved with appropriate lactation support. An infant who feeds normally needs no intervention merely because a frenulum looks short.

Start with the dyad, not the procedure — painful or ineffective breastfeeding has a broad differential. Before offering release, obtain a feeding history, trajectory of weight and hydration, maternal nipple pain/trauma, milk supply, feeding frequency and duration, bottle use if relevant, and prior interventions. Examine oral cavity, palate, craniofacial anatomy and tongue movement, but then observe a feed with a clinician experienced in breastfeeding assessment whenever feasible. Look at latch, seal, maternal pain, audible swallowing, sustained transfer and the infant's ability to maintain feeding. Consider maternal positioning, supply, nipple anatomy, infant prematurity, nasal obstruction, neurologic/oral-motor dysfunction, retrognathia or other craniofacial factors, and general illness. A scoring tool can structure observation, but no single tongue-tie scale should replace the clinical demonstration that restricted mobility is the causal problem.

Conservative first step — optimize positioning and latch, provide skilled lactation support, address milk-supply and maternal factors, and ensure close weight follow-up. If feeding becomes effective and growth/pain improve, do not operate. This is not therapeutic delay; it is diagnostic work. The 2024 AAP report specifically defines symptomatic disease by persistence despite lactation support and emphasizes complete breastfeeding assessment before treatment. The AAPD similarly notes that causes other than ankyloglossia are more common causes of breastfeeding difficulty and that not every infant with ankyloglossia requires surgery.

When frenotomy is reasonable — after alternative causes have been evaluated and modifiable feeding problems treated, a lingual frenotomy can be offered when a clearly restrictive lingual frenulum continues to cause substantial functional breastfeeding impairment. Shared decision-making should state the evidence accurately: the most consistent demonstrated benefit is short-term reduction in maternal nipple pain, while evidence for durable improvement in every breastfeeding outcome is less certain. The 2026 review reaches a similar practical boundary: carefully selected dyads with persistent, well-documented difficulty despite high-quality support may benefit, but frenotomy is not a universal answer to feeding, speech, reflux-like behavior or nonspecific distress.

What not to call an indication — do not operate on an asymptomatic frenulum to prevent hypothetical future articulation problems or obstructive sleep apnea. The AAP says these prophylactic indications are not evidence based. 'Posterior tongue-tie' is poorly defined and should not itself be the reason to operate on an infant. A prominent maxillary labial frenulum and buccal frena are normal oral structures; current AAP guidance states they are unrelated to breastfeeding mechanics and do not require release to improve breastfeeding. The family's request for simultaneous upper-lip release therefore does not become appropriate simply because the tissue is visible or because a package procedure is offered elsewhere.

Laser versus scissors — there is no evidence that laser is superior to conventional frenotomy techniques for infant ankyloglossia. Device branding should never substitute for indication. Choose a technique the appropriately trained operator can perform safely and efficiently. Consent should cover expected benefit and uncertainty, pain, bleeding, infection, scarring/restriction, oral aversion or feeding worsening, injury to nearby floor-of-mouth/salivary structures, and the possibility that symptoms persist because the original causal diagnosis was wrong. Confirm the newborn received vitamin K or otherwise address bleeding risk before an elective release. The procedure is generally low risk when properly selected and performed, but 'minor' is not synonymous with consequence-free.

Operative anatomy and restraint — expose the lingual frenulum clearly and distinguish the intended restrictive band from deeper floor-of-mouth tissue. Wharton duct openings sit adjacent to the frenulum, and unnecessarily deep or broad dissection increases the chance of salivary-duct/floor-of-mouth injury and bleeding without proving additional functional benefit. The objective is functional release, not creation of the largest wound. Maintain control of the tongue, suction and airway, obtain hemostasis, and reassess mobility. Persistent brisk bleeding, expanding floor-of-mouth swelling, respiratory change, poor secretion control or inability to feed after the procedure requires immediate reassessment and escalation rather than routine discharge.

Aftercare — verify that the functional target actually improved. Reassess feeding, maternal pain and weight rather than declaring success from a more dramatic tongue excursion alone. Continue lactation support because release does not teach a feeding pattern by itself. Current AAP guidance does not recommend routinely opening the wound or prescribing repetitive postoperative stretching intended to prevent reattachment; that practice lacks supportive evidence and can cause pain. If symptoms persist, reconsider the differential before proposing a deeper repeat release or a different device.

Older child with speech concern — the evidence boundary changes. First establish that there is a real speech or mechanical function problem plausibly related to restricted tongue mobility. Obtain speech-language evaluation when articulation is the complaint; many speech errors have causes unrelated to the frenulum, and a visible tie does not prove causation. Assess protrusion, elevation and task-specific mobility, the actual phonemes or oral functions affected, developmental expectations, prior therapy, dentition and oral-motor status. AAO-HNS consensus work is valuable precisely because not every proposed relationship reached agreement. Selected older children with clear mechanical restriction and a function-limiting symptom may be considered for frenotomy/frenuloplasty after shared decision-making, but prophylactic surgery to guarantee normal future speech is not evidence based.

Maxillary frenulum and dental referral — a prominent maxillary labial frenulum in an infant is not a breastfeeding indication. In an older child referred for a diastema or periodontal concern, coordinate with pediatric dentistry/orthodontics and interpret the frenulum in the context of dental development, eruption and the planned orthodontic sequence. A midline gap is not by itself proof that early frenectomy is needed. The dental literature and AAPD policy emphasize individualized, team-based planning and acknowledge important uncertainty regarding causal associations and long-term outcomes. ENT should not convert an appearance-based dental referral into automatic early surgery.

Disagreement and evidence hierarchy — durable textbook anatomy tells us what tissue is present, what structures are nearby and what functions restriction can plausibly affect. It does not settle the current threshold for infant surgery. AAO-HNS's 2020 consensus statement reached consensus on many issues but also left numerous statements at near-consensus or no consensus, signaling genuine evidence gaps rather than permission to fill them with certainty. The Academy of Breastfeeding Medicine emphasizes functional breastfeeding-dyad assessment and individualized care. The 2024 AAP report is more explicit about avoiding overdiagnosis, posterior-tie labeling, lip/buccal releases for breastfeeding, prophylactic future indications and routine stretching. Those modern management boundaries should supersede older morphology-driven habits while anatomy and safe operative technique remain durable.

FDA boundary — candidacy for frenotomy is not determined by an FDA disease indication or a particular branded laser. This is a clinical procedural decision based on functional impairment, evidence, professional guidance, informed consent and operator competence. A device being marketed or cleared for soft-tissue use does not create an indication to release a normal or noncausal frenulum.

Senior bailout — if the history sounds severe but an observed feed is effective, growth is appropriate and tongue mobility is adequate, stop and reassess rather than operating to satisfy the label. If feeding is poor but the frenulum does not convincingly explain it, broaden the diagnostic workup and feeding-team involvement. If skilled support has not yet occurred, provide it and follow closely. If the infant has persistent documented dysfunction clearly linked to restricted mobility despite support, frenotomy becomes a reasonable option. If a prior release failed, do not assume the answer is a deeper second release: reconsider latch, milk supply, neurologic/oral-motor factors, craniofacial anatomy and the original diagnosis.

Senior synthesis — before agreeing to a release, answer five questions aloud: What function is impaired? Have I directly demonstrated that restricted tongue mobility plausibly causes it? What competing causes have been assessed and treated? What outcome am I promising, and how strong is that evidence? What nearby anatomy and procedural risks change my technique or disposition? The high-value resident skill is resisting both extremes: do not dismiss a genuinely function-limiting ankyloglossia that persists despite skilled support, but do not transform normal frenula, uncertain labels or hoped-for future benefits into surgical disease."""

TRAPS = [
    "Calling a visible or short-appearing frenulum symptomatic ankyloglossia without demonstrating impaired function.",
    "Offering infant frenotomy before an observed breastfeeding assessment and skilled lactation optimization.",
    "Attributing every painful latch or poor weight trajectory to tongue-tie instead of considering maternal, supply, oral-motor, nasal, neurologic and craniofacial causes.",
    "Using the poorly defined label 'posterior tongue-tie' as a stand-alone surgical indication.",
    "Releasing a maxillary labial or buccal frenulum to improve breastfeeding simply because it is prominent.",
    "Promising prophylactic frenotomy will prevent future speech articulation problems or obstructive sleep apnea.",
    "Selling laser as clinically superior to scissors despite lack of evidence for superiority.",
    "Skipping vitamin-K/bleeding-risk review because infant frenotomy is considered a minor procedure.",
    "Dissecting unnecessarily deep into the floor of mouth and placing Wharton duct/salivary structures or hemostasis at avoidable risk.",
    "Judging procedural success only by greater tongue excursion rather than feeding function, pain and weight trajectory.",
    "Prescribing routine wound-opening or stretching exercises as evidence-based prevention of reattachment despite current AAP guidance against the practice.",
    "Responding to persistent symptoms after release with an automatic deeper repeat release instead of reconsidering the causal diagnosis.",
    "Operating on an older child for 'speech' without defining the articulation problem and involving speech-language evaluation when appropriate.",
    "Treating an older child's maxillary diastema as an automatic early-frenectomy indication without dental development and orthodontic planning.",
    "Presenting disputed associations as settled science instead of distinguishing textbook anatomy, consensus, current guidance and unresolved evidence gaps.",
]

COHORT = {QIDS[0]: {
    "concept_id": CID,
    "canonical_topic": TOPIC,
    "prompt": PROMPT,
    "answer_text": ANSWER,
    "explanation": "Ankyloglossia requires demonstrated functional restriction, not a visible frenulum. In infants, complete breastfeeding assessment and skilled support come first; selective lingual frenotomy may be reasonable for persistent causal dysfunction, while posterior-tie labeling, prophylactic future indications and labial/buccal release for breastfeeding should not drive surgery.",
    "board_pearl": "Treat function, not frenulum appearance: observe the feed, optimize lactation, prove causal tongue restriction, and decline prophylactic or lip/buccal releases unsupported by current evidence.",
    "depth_layers_v222": {
        "foundation":"Lingual-frenulum/floor-of-mouth anatomy, Wharton duct relationship, mobility phenotype and the distinction between normal anatomy and symptomatic functional restriction.",
        "application":"Observed-feed assessment, differential diagnosis, lactation optimization, selective frenotomy candidacy, technique/consent/aftercare and older-child speech/dental pathways.",
        "senior_decision":"Resist morphology-driven overtreatment, distinguish society disagreements and evidence strength, stop when causality is unproven, and reconsider the diagnosis rather than escalating automatically after treatment failure."
    },
    "common_traps_v222": TRAPS,
    "deliberate_review_v222": "Selected from the exact successful v20.21 production backlog. It ranked third lexically, but its prior 15-word answer left a high-frequency pediatric ENT counseling gap: functional diagnosis, breastfeeding differential, overdiagnosis, lip/buccal tie claims, posterior-tie controversy, procedural risk, older-child speech/dental boundaries and current evidence disagreement.",
    "source_refs_v222": SOURCE_REFS_V222,
    "evidence_distinction_v222": "Durable K.J. Lee/Cummings/Pasha oral and pediatric anatomy is preserved, with explicit provenance limits where a specific current indication statement could not be recovered from a connected text. Current management follows AAP 2024, AAO-HNS consensus, Academy of Breastfeeding Medicine, AAPD policy and 2026 peer-reviewed synthesis: symptomatic function after skilled support drives infant lingual frenotomy; morphology, poorly defined posterior-tie labels, prophylactic future speech/OSA claims, and maxillary/buccal frenula for breastfeeding do not. No FDA device status creates a clinical indication, and no laser technique has proven superiority.",
    "audit_profile_v222": "ankyloglossia_maxillary_frenulum",
}}

def apply_concept_check_task_alignment_v222(checks, deep_modules, v6_item_id):
    by_id = {str(q.get("id") or ""): q for q in checks or []}
    repaired, missing, link_mismatch = [], [], []
    for qid, payload in COHORT.items():
        q = by_id.get(qid)
        if q is None:
            missing.append(qid)
            continue
        module = _find_module(q, deep_modules, v6_item_id)
        topic = str(module.get("topic") or "") if module else ""
        cid = v6_item_id(q.get("domain"), topic) if module and q.get("domain") else None
        if topic != payload["canonical_topic"] or cid != payload["concept_id"]:
            link_mismatch.append(qid)
            continue
        for key, value in payload.items():
            q[key] = value
        q["concept_id"] = payload["concept_id"]
        q["choices"] = []
        q["answer"] = None
        q["task_alignment_v222"] = True
        repaired.append(qid)
    return {"repaired": repaired, "missing": missing, "link_mismatch": link_mismatch}
