"""v19.0 — high-yield post-completion Concept Check depth cohort.

Selected from the validated V189 live-canonical backlog. Prioritizes call-risk,
airway, aspiration, reoperative endocrine surgery, and goals-of-care decisions.
Exact canonical resolution is required before mutation.
"""
from concept_check_board_repair_v177 import _find_module

COHORT={
"cc-v112-rec-head-neck-oncology-palliative-goals-of-care-decision-making-in-head-neck-cancer":{
"concept_id":"v6-head-neck-oncology-palliative-goals-of-care-decision-making-in-head-neck-cancer","canonical_topic":"Palliative / Goals-of-Care Decision-Making in Head & Neck Cancer",
"prompt":"A 67-year-old with unresectable recurrent oropharyngeal SCC has progressive dysphagia, fungating neck disease with intermittent bleeding, severe pain, increasing secretion burden, and a narrowing but currently stable airway. He values time at home and wants to avoid prolonged hospitalization. How should you prioritize symptom targets, discuss tracheostomy, feeding access, hemostatic or debulking procedures, and decide when a technically feasible intervention is more burdensome than beneficial?",
"answer_text":"Start by defining the patient's goals and the specific symptom each proposed intervention is intended to relieve. Palliative care should run in parallel with disease-directed treatment and should address pain, dyspnea, bleeding risk, dysphagia, nutrition, secretions, communication, psychosocial distress, and caregiver burden. A tracheostomy may prevent catastrophic airway obstruction but can increase secretion-management needs, hospitalization, caregiver burden, and the possibility of surviving with a tube-dependent airway; it should therefore be discussed before a crisis when possible. Feeding access can support nutrition but does not necessarily prevent aspiration or improve quality of life in every patient. Focal bleeding may be addressed with packing, endovascular therapy, radiation, or selected surgery depending on source and expected durability. Debulking can be reasonable when a discrete obstructive or symptomatic target can be relieved with acceptable recovery, but major salvage surgery without realistic oncologic or functional benefit may consume much of the patient's remaining time. The senior decision is proportionality: choose interventions with a clear, patient-valued endpoint and avoid procedures whose recovery burden, complication risk, or loss of independence outweighs the symptom benefit the patient actually wants.",
"explanation":"Palliative head-and-neck surgery is symptom-directed, not procedure-directed. Technical feasibility does not establish that an intervention is goal-concordant or proportionate.",
"board_pearl":"Before offering a palliative procedure, be able to name the symptom it is meant to improve and the recovery burden the patient accepts to gain that benefit.",
"depth_layers_v190":{"foundation":"Identify dominant symptom burden and establish goals, prognosis, and acceptable tradeoffs before procedural planning.","application":"Match airway, feeding, bleeding, pain, secretion, and wound interventions to specific patient-valued targets.","senior_decision":"Decline or de-escalate technically feasible interventions when recovery burden or loss of independence exceeds realistic symptom benefit."},
"common_traps_v190":["Waiting until complete airway obstruction to discuss tracheostomy forces a crisis decision without allowing the patient to weigh long-term tube burden and goals.","Equating technical resectability with palliative benefit can lead to a major operation that consumes remaining life without meaningfully improving symptoms or function."],
"deliberate_review_v190":"Expanded a 64-word procedural statement into prospective airway planning, symptom-targeted intervention, burden-benefit proportionality, and goal-concordant escalation."},
"cc-v112-rec-pediatric-otolaryngology-pediatric-deep-neck-infection":{
"concept_id":"v6-pediatric-otolaryngology-pediatric-deep-neck-infection","canonical_topic":"Pediatric Deep Neck Infection",
"prompt":"A 4-year-old has fever, torticollis, drooling, muffled voice, and worsening oral intake. CT shows a 2.8-cm retropharyngeal collection with rim enhancement and mild airway displacement but no mediastinal extension. The child is tachycardic but oxygenating comfortably. How should you decide monitored IV therapy versus drainage, secure the airway if the child deteriorates, and recognize vascular, neurologic, or mediastinal complications that mandate urgent escalation?",
"answer_text":"Begin with airway and sepsis assessment rather than the CT size alone. Evaluate work of breathing, stridor, secretion handling, neck position, trismus, hydration, neurologic findings, and the trajectory over hours. Start broad IV antibiotics covering expected aerobic and anaerobic upper-airway flora and provide fluids and analgesia. Selected clinically stable children without airway compromise, septic shock, neurologic or vascular complication, or rapidly progressive disease can undergo a closely monitored trial of medical therapy even when imaging shows a collection, particularly if operative anesthesia itself carries meaningful airway risk. Drainage is favored for airway compromise, large organized or accessible abscess with mass effect, sepsis, progression, complication, or failure to improve after an appropriate medical trial. If respiratory status worsens, coordinate ENT and anesthesia early, preserve spontaneous ventilation when loss of the airway is a concern, and have rigid endoscopy and surgical-airway rescue capability available. Internal-jugular thrombosis, carotid involvement, cranial neuropathy, epidural/intracranial spread, or descending mediastinitis changes the case from routine abscess management to urgent multidisciplinary source control.",
"explanation":"Pediatric deep-neck infection management depends on clinical trajectory and complication risk, not a single diameter threshold. Airway strategy and source control must be individualized.",
"board_pearl":"A stable child may earn a monitored antibiotic trial; a worsening airway, sepsis, or complication removes that option quickly.",
"depth_layers_v190":{"foundation":"Recognize retropharyngeal/deep-neck infection and assess airway, hydration, sepsis, and complication signs.","application":"Use monitored IV therapy selectively and drain organized disease when clinical severity, mass effect, or failure of medical therapy warrants source control.","senior_decision":"Escalate with a controlled pediatric airway plan and multidisciplinary drainage for vascular, neurologic, intracranial, or mediastinal extension."},
"common_traps_v190":["Treating CT diameter as an automatic operation rule ignores that clinical stability, organization, accessibility, and trajectory determine whether a monitored antibiotic trial is reasonable.","Inducing anesthesia without a shared airway-rescue plan in a child with progressive retropharyngeal swelling can convert partial obstruction into a cannot-ventilate emergency."],
"deliberate_review_v190":"Expanded a 70-word antibiotic-versus-drainage answer into pediatric airway planning, medical-trial selection, source-control thresholds, and complication escalation."},
"cc-v112-rec-general-ent-emergencies-angioedema":{
"concept_id":"v6-general-ent-emergencies-angioedema","canonical_topic":"Angioedema",
"prompt":"A 61-year-old taking lisinopril develops rapidly progressive tongue and floor-of-mouth swelling without urticaria or wheezing. Flexible scope shows increasing base-of-tongue edema but the glottis remains visible. How should you distinguish histamine-mediated from bradykinin-mediated angioedema, choose pharmacologic treatment, decide whether to secure the airway early, and plan rescue if oral or nasal intubation becomes unsafe?",
"answer_text":"Treat the airway trajectory first while simultaneously identifying the likely mediator. Histamine-mediated angioedema often accompanies urticaria, pruritus, bronchospasm, or anaphylaxis and should receive intramuscular epinephrine when anaphylaxis is suspected, plus antihistamines and corticosteroids as adjuncts. ACE-inhibitor and hereditary/acquired C1-inhibitor angioedema are bradykinin-mediated, commonly lack urticaria, and do not reliably respond to epinephrine, antihistamines, or steroids; stop the offending ACE inhibitor and use institutionally available bradykinin-directed therapy when appropriate. Serial airway examination is important because tongue, floor-of-mouth, and laryngeal progression can be rapid. Increasing edema, voice change, drooling, dyspnea, inability to handle secretions, or worsening endoscopic findings should lower the threshold for controlled early intubation by the most experienced team, often using an awake technique while spontaneous ventilation is preserved. Repeated traumatic attempts worsen edema. If upper-airway instrumentation is predicted to fail or deterioration outpaces safe intubation, cricothyrotomy or tracheostomy rescue must be immediately available. The senior mistake is waiting for complete obstruction before acting simply because oxygen saturation is still normal.",
"explanation":"Angioedema is both an airway problem and a mediator-identification problem. Pharmacologic response differs substantially between histamine and bradykinin pathways, but airway progression overrides diagnostic elegance.",
"board_pearl":"Normal oxygen saturation does not reassure you in a progressively narrowing upper airway; secure the airway before anatomy becomes impossible.",
"depth_layers_v190":{"foundation":"Differentiate histamine-mediated and bradykinin-mediated angioedema by phenotype and expected medication response.","application":"Use epinephrine for anaphylaxis, appropriate adjuncts or bradykinin-directed therapy, and serial airway examination.","senior_decision":"Intubate early with a controlled technique when progression threatens access and maintain immediate surgical-airway rescue rather than waiting for complete obstruction."},
"common_traps_v190":["Repeating antihistamines and steroids while ACE-inhibitor angioedema continues to progress can delay the airway intervention that actually determines survival.","Multiple traumatic laryngoscopy attempts in a swollen floor of mouth can worsen edema and eliminate an airway that could have been secured earlier with a controlled technique."],
"deliberate_review_v190":"Expanded a 72-word airway statement into mediator-specific therapy, serial endoscopic assessment, early-intubation thresholds, and surgical rescue planning."},
"cc-v112-rec-pediatric-otolaryngology-pediatric-aspiration":{
"concept_id":"v6-pediatric-otolaryngology-pediatric-aspiration","canonical_topic":"Pediatric Aspiration",
"prompt":"A 14-month-old with recurrent pneumonias coughs with thin liquids and has poor weight gain. Flexible laryngoscopy shows mobile vocal folds without an obvious mass. How should you localize aspiration physiology, choose FEES versus modified barium swallow, decide when direct laryngoscopy/bronchoscopy is needed for a laryngeal cleft or other structural lesion, and determine whether feeding modification, injection, cleft repair, or enteral support is appropriate?",
"answer_text":"First separate oropharyngeal discoordination from a structural airway-protection problem. History should address consistency-specific coughing, wet voice or breathing, recurrent pneumonia, neurologic disease, prior cardiothoracic surgery, prematurity, and growth. An instrumental swallow study is usually required when pulmonary or nutritional consequences are meaningful. Modified barium swallow is useful for oral and pharyngeal timing, bolus flow, aspiration timing, and testing compensatory strategies; FEES is valuable for secretion burden, laryngeal sensation, residue, and repeated bedside assessment, although the actual moment of the swallow is obscured by white-out. Persistent aspiration despite appropriate therapy, unexplained aspiration with suggestive symptoms, or concern for laryngeal cleft, tracheoesophageal fistula, subglottic disease, or occult airway lesion warrants direct airway evaluation, often including palpation of the interarytenoid region because a subtle cleft can be missed on office examination. Management should match mechanism: thicken or alter flow/position when strategies demonstrably improve safety, treat neurologic or inflammatory contributors, consider temporary injection for selected glottic or interarytenoid insufficiency, repair a clinically important structural cleft when conservative therapy fails, and use enteral support when nutrition cannot be maintained safely. A feeding tube supports nutrition but does not eliminate secretion or reflux-related aspiration.",
"explanation":"Pediatric aspiration is a physiology-localization problem. Treatment depends on whether aspiration arises from timing, sensation, glottic closure, structural cleft, or broader neurologic disease.",
"board_pearl":"Do not label aspiration as reflux or dyscoordination until you have asked whether a subtle structural airway lesion is being missed.",
"depth_layers_v190":{"foundation":"Recognize pulmonary/nutritional consequences and distinguish neurologic discoordination, sensory impairment, glottic insufficiency, and structural lesions.","application":"Choose FEES, MBS, and operative airway evaluation according to the unresolved physiologic or anatomic question and test compensatory strategies.","senior_decision":"Escalate from feeding modification to injection, structural repair, or enteral support based on mechanism, recurrent pulmonary injury, growth, and failure of conservative therapy."},
"common_traps_v190":["Attributing recurrent aspiration to reflux without instrumental localization can delay diagnosis of a laryngeal cleft or other surgically correctable airway lesion.","Placing a gastrostomy and assuming aspiration is solved ignores continued aspiration of secretions or refluxate and does not treat an unsafe structural airway."],
"deliberate_review_v190":"Expanded a 15-word differential into test selection, operative localization, mechanism-specific treatment, and escalation for pulmonary/nutritional harm."},
"cc-v112-rec-thyroid-parathyroid-salivary-reoperative-thyroid-surgery":{
"concept_id":"v6-thyroid-parathyroid-salivary-reoperative-thyroid-surgery","canonical_topic":"Reoperative Thyroid Surgery",
"prompt":"A patient previously treated with total thyroidectomy now has biopsy-proven nodal recurrent papillary thyroid carcinoma in the central neck. Preoperative laryngoscopy shows one mobile and one mildly paretic vocal fold, and imaging suggests the target abuts the tracheoesophageal groove. How should you confirm the indication and exact target, plan recurrent-laryngeal-nerve and parathyroid protection, decide when nerve sacrifice is oncologically justified, and prepare for bilateral nerve or calcium complications?",
"answer_text":"Reoperation should begin with proof that the expected oncologic benefit exceeds the substantially higher morbidity of scarred central-neck surgery. Confirm the structural target with high-quality ultrasound and cross-sectional imaging when needed, correlate suspicious nodes with cytology and thyroglobulin washout when appropriate, and map every compartment that will require treatment so the operation is not an exploratory reentry. Document baseline vocal-fold mobility because an unrecognized preexisting paresis dramatically changes the consequence of injury to the contralateral nerve. Review prior operative and pathology reports and anticipate distorted parathyroid blood supply. Intraoperatively, identify the recurrent laryngeal nerve using an approach through the least scarred expected segment, often inferiorly or near its laryngeal entry point, and use nerve monitoring as an adjunct rather than a substitute for anatomic identification. Preserve functioning parathyroid tissue and vascularity when possible and plan postoperative calcium/PTH surveillance. A functioning nerve should generally be preserved when disease can be completely dissected off it; deliberate sacrifice is reserved for direct gross invasion when oncologic control requires it and should trigger immediate counseling/reconstruction planning. If the contralateral fold is already weak, the threshold for staged or modified surgery rises because bilateral dysfunction can create an airway emergency.",
"explanation":"Reoperative thyroid surgery is target-defined, anatomy-intensive surgery. Baseline vocal-fold function and the exact relationship of recurrent disease to the RLN determine how much risk is acceptable.",
"board_pearl":"Before reentering a scarred central neck, know exactly what you are removing and exactly how much recurrent-laryngeal-nerve function the patient can afford to lose.",
"depth_layers_v190":{"foundation":"Confirm structural recurrence, map the target, review prior surgery, and document baseline vocal-fold function before reentry.","application":"Use least-scarred nerve-identification strategies, protect parathyroid vascularity, and monitor postoperative calcium and vocal-fold function.","senior_decision":"Preserve a functioning RLN when gross disease can be separated; sacrifice only for true oncologic invasion when necessary and modify/stage surgery when contralateral function is compromised."},
"common_traps_v190":["Entering the central neck for a vaguely suspicious biochemical recurrence without a mapped structural target exposes the RLN and parathyroids to high morbidity without a defined surgical endpoint.","Assuming both vocal folds move normally without preoperative laryngoscopy can turn an otherwise tolerated unilateral nerve injury into catastrophic bilateral dysfunction in a patient with occult paresis."],
"deliberate_review_v190":"Expanded a 15-word risk statement into target confirmation, preoperative laryngeal assessment, scar-plane nerve strategy, parathyroid protection, and oncologic nerve-sacrifice thresholds."}
}

def apply_concept_check_task_alignment_v190(checks, deep_modules, v6_item_id):
    by_id={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid,p in COHORT.items():
        q=by_id.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id)
        topic=str(module.get('topic') or '') if module else ''
        cid=v6_item_id(q.get('domain'),topic) if module and q.get('domain') else None
        if topic!=p['canonical_topic'] or cid!=p['concept_id']:
            link_mismatch.append(qid); continue
        for k,v in p.items():
            if k not in {'concept_id','canonical_topic'}: q[k]=v
        q['concept_id']=cid; q['task_alignment_v190']=True
        q.pop('choices',None); q.pop('answer',None); q.pop('correct_answer',None)
        repaired.append(qid)
    return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
