"""v20.11f focused depth patch for Four-Gland Parathyroid Exploration."""
from concept_check_board_repair_v177 import _find_module

CID="v6-thyroid-parathyroid-salivary-four-gland-parathyroid-exploration"
TOPIC="Four-Gland Parathyroid Exploration"
QID="cc-v112-mgt-thyroid-parathyroid-salivary-four-gland-parathyroid-exploration"

SOURCE_REFS_V211_PARATHYROID=[
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive split Part 4; parathyroid localization/anatomic exploration material reviewed 2026-09-05. Superior glands usually lie posterior to the recurrent-laryngeal-nerve plane, inferior glands anterior; ectopic superior glands track paraesophageal/retroesophageal while inferior glands may descend with thymic migration.","role":"foundation/operative: embryologic migration, RLN relationship, ectopic-gland search strategy, multigland localization pitfalls"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), Chapter 3 Endocrinology, parathyroidectomy section; connected Google Drive copy reviewed 2026-09-05.","role":"board/operative framework: four-gland exploration when localization is negative or multigland disease is suspected, autotransplantation concepts, persistent disease reasoning"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), Chapter 38 Thyroid and Parathyroid; connected Google Drive copy reviewed 2026-09-05.","role":"operative cross-check: single adenoma versus four-gland hyperplasia, intraoperative PTH kinetics, subtotal versus total parathyroidectomy with autotransplantation, recurrence causes"},
 {"type":"guideline","citation":"Wilhelm SM, et al. The American Association of Endocrine Surgeons Guidelines for Definitive Management of Primary Hyperparathyroidism. JAMA Surg. 2016;151(10):959-968. PMID 27532368.","role":"major society guidance: consider multigland disease routinely; focused surgery and bilateral exploration both achieve high cure rates; convert to bilateral exploration for discovered multigland disease, failure to identify the abnormal gland, or inadequate intraoperative PTH response"},
 {"type":"international_guideline","citation":"Bilezikian JP, et al. Evaluation and Management of Primary Hyperparathyroidism: Summary Statement and Guidelines from the Fifth International Workshop. J Bone Miner Res. 2022;37(11):2293-2314. DOI 10.1002/jbmr.4677.","role":"current management: imaging localizes disease only after the decision for surgery; selective parathyroidectomy is appropriate with successful localization, while multigland disease requires a different operative strategy"},
 {"type":"consensus_review","citation":"Perrier ND, et al. Surgical Aspects of Primary Hyperparathyroidism. J Bone Miner Res. 2022;37(11):2373-2390. DOI 10.1002/jbmr.4689.","role":"current operative terminology: bilateral/four-gland exploration is recommended for negative localization and known or suspected multigland disease including hereditary, lithium-associated, and sporadic multigland PHPT"},
]

PROMPT="""A patient with biochemically confirmed primary hyperparathyroidism has discordant/nonlocalizing localization studies and concern for multigland disease. During bilateral exploration, how should the surgeon systematically identify all four parathyroid glands, use embryology and the recurrent laryngeal nerve to search for ectopic glands, decide what to resect when multiple glands are enlarged, interpret an inadequate intraoperative PTH fall, and avoid trading persistent hyperparathyroidism for permanent hypoparathyroidism or recurrent-laryngeal-nerve injury?"""

ANSWER="""Foundation — four-gland exploration is an anatomy-driven operation, not a hunt for the first brown nodule. Confirm that the patient truly has a surgical parathyroid disorder before entering the neck; localization studies are for operative planning, not for making the biochemical diagnosis. Modern PHPT care does not require bilateral exploration for every patient. A well-localized apparent single adenoma can be treated selectively in experienced hands, but known or suspected multigland disease, hereditary disease, lithium-associated disease, negative/nonlocalizing studies, discovery of multiple abnormal glands, inability to find the expected abnormal gland, or an inadequate intraoperative PTH response should lower the threshold for bilateral/four-gland exploration.

Build a reproducible map. Expose one side sufficiently to identify the thyroid lobe, tracheoesophageal groove, recurrent laryngeal nerve region, carotid sheath and thymic/thyrothymic tissue without devascularizing normal glands. Search expected superior and inferior positions systematically rather than repeatedly dissecting the same scar plane. The most durable anatomic rule from Cummings is the relationship to the recurrent laryngeal nerve: superior glands usually lie posterior/dorsal to the RLN plane, whereas inferior glands are usually anterior/ventral. This relationship is often more useful than asking whether a gland looks physically “high” or “low.”

Superior-gland search — the superior parathyroid develops from the fourth pouch and migrates less, so it is commonly found near the posterior upper/mid thyroid, around the cricothyroid junction or posterior to the recurrent nerve. When ectopic, follow its predictable posterior migration possibilities: paraesophageal, retroesophageal, paratracheal and occasionally retropharyngeal locations. A descended superior gland can sit deceptively low but typically remains posterior to the RLN plane; mistaking it for an inferior gland can leave the true inferior gland undiscovered.

Inferior-gland search — the inferior parathyroid develops with the thymus from the third pouch and has a wider migration path. Search the lower thyroid pole, thyrothymic ligament, thymic tongue and upper mediastinal trajectory. An apparently “missing” inferior gland may be intrathymic or descend toward the anterior superior mediastinum. Do not perform progressively dangerous blind central-neck dissection without first using embryology, prior imaging and the glands already identified to decide where the missing gland should be.

Identify normal before sacrificing normal. During true bilateral exploration, compare size, shape, color, texture and vascularity across glands. Fat, lymph nodes, thyroid nodules and brown fat can mimic parathyroid tissue, and a single enlarged gland does not prove single-gland disease when the preoperative picture suggests hyperplasia. Conversely, mildly asymmetric normal glands should not all be removed merely because they are visible. The goal is biochemical cure while preserving enough well-perfused parathyroid tissue to avoid permanent hypoparathyroidism.

Single adenoma versus multigland disease — if one clearly enlarged gland is found and the remaining explored glands are convincingly normal, remove the pathologic gland and use the entire clinical picture, exploration findings and intraoperative PTH protocol to decide whether exploration is complete. If multiple glands are enlarged, think hyperplasia or double adenoma rather than repeatedly labeling each new gland an incidental finding. Known four-gland hyperplasia is not treated by removing only the largest gland. Common operative strategies include subtotal parathyroidectomy, leaving a deliberately sized well-vascularized remnant of the most normal-appearing gland, or total parathyroidectomy with autotransplantation in selected settings. The exact strategy depends on sporadic versus hereditary disease, renal disease context, recurrence risk and surgeon/endocrine-surgery plan.

Protect perfusion and the RLN. Parathyroid viability depends on a delicate end-arterial supply. When preserving a remnant, avoid skeletonizing or crushing its vascular pedicle; if normal parathyroid tissue is inadvertently devascularized and clearly nonviable, current AAES guidance supports autotransplantation. At the same time, do not convert a search for a gland into a recurrent-laryngeal-nerve injury. Identify the nerve when the dissection requires it, stay oriented to the nerve/gland plane, and stop blind traction, cautery or deep clamping when anatomy is uncertain.

Intraoperative PTH is a physiologic adjunct, not a substitute for anatomy. PTH has a short half-life, and many protocols use an appropriate fall after excision to support biochemical success. If the level does not fall adequately, first verify timing, sampling and the assay protocol; then assume residual hyperfunctioning tissue until proved otherwise. During a focused operation, failure of an appropriate PTH decrease is a classic reason to convert to bilateral exploration. During an already bilateral exploration, reconsider whether one of the “identified” structures was actually parathyroid, whether a second adenoma or hyperplastic gland remains, or whether a fifth/supernumerary or ectopic gland is present.

Important nuance — a slow or incomplete intraoperative PTH fall is not interpreted in a vacuum. Renal dysfunction can alter PTH clearance and baseline elevation, so the trend must be interpreted with the assay protocol and the patient's physiology rather than forcing resection solely to make one number cross a threshold. The dangerous alternative is removing progressively normal-appearing glands because the curve is slower than expected without reconciling renal function, timing and operative findings.

Missing-gland algorithm — stop and account for what you know. Confirm which glands are truly identified and which side/embryologic class is missing. Re-review imaging if available. For an inferior gland, inspect thyrothymic ligament/thymic tissue and the anterior mediastinal path. For a superior gland, inspect posterior/paraesophageal/retroesophageal locations. Consider an intrathyroidal gland only after more common locations are excluded; thyroid resection solely as an undirected “search maneuver” is poor strategy. A supernumerary fifth gland becomes more plausible in persistent multigland disease after four credible glands have been addressed.

Hereditary/multigland context changes the endpoint. MEN1 and other hereditary syndromes have a different recurrence biology than a sporadic solitary adenoma, so the operation may require planned subtotal resection or total parathyroidectomy/autotransplantation and, in selected hereditary settings, cervical thymectomy. The senior mistake is applying a focused-adenoma mindset to a patient whose disease is biologically multiglandular.

Postoperative rescue — watch for neck hematoma, voice change, symptomatic hypocalcemia and hungry-bone physiology. Perioral numbness, paresthesias, carpopedal spasm or QT prolongation demand calcium assessment and treatment. Patients with marked preoperative bone disease may have substantial calcium uptake after cure and need proactive calcium/vitamin-D management. A new breathy voice or aspiration symptoms require laryngeal assessment rather than being dismissed as routine postoperative discomfort. Cure is not declared because the wound looks good; long-term biochemical follow-up confirms eucalcemia and detects persistence or recurrence.

Senior synthesis — use five questions. INDICATION: why is this a four-gland operation rather than a focused one? MAP: which glands are identified, and are they anterior or posterior to the RLN plane as expected? BIOLOGY: does the pattern fit single adenoma, double adenoma, sporadic hyperplasia, lithium-associated disease or hereditary multigland disease? PHYSIOLOGY: does intraoperative PTH support cure, and if not, have timing, renal clearance, ectopic/supernumerary tissue and missed multigland disease been considered? PRESERVATION: can you cure the patient while leaving a viable, perfused parathyroid remnant and an intact recurrent laryngeal nerve? The dangerous errors are stopping after the first enlarged gland in a multigland patient, searching randomly for a missing gland, mistaking a descended superior gland for an inferior gland, sacrificing the remnant's blood supply, chasing a slow PTH curve by removing normal tissue, and ending the case without a plan for hypocalcemia, hematoma, voice change or biochemical persistence."""

COMMON_TRAPS=[
 "Using localization imaging to diagnose PHPT rather than to plan an operation after biochemical diagnosis is established.",
 "Assuming every PHPT patient needs four-gland exploration despite concordant single-gland localization and an appropriate selective-surgery pathway.",
 "Stopping after the first enlarged gland even when hereditary disease, lithium exposure, negative imaging or operative findings suggest multigland disease.",
 "Searching for superior versus inferior glands by absolute neck height rather than using their relationship to the recurrent-laryngeal-nerve plane and embryologic migration.",
 "Calling a descended superior gland an inferior gland and therefore leaving the true inferior gland unexplored.",
 "Performing blind deep or mediastinal dissection for a missing gland without first following predictable paraesophageal, thyrothymic and thymic migration pathways.",
 "Removing progressively normal-looking glands solely because intraoperative PTH falls slowly without checking timing, assay protocol and renal clearance.",
 "Skeletonizing the vascular pedicle of the intended parathyroid remnant and converting subtotal parathyroidectomy into permanent hypoparathyroidism.",
 "Treating identification of four glands as permission to ignore a supernumerary fifth gland when PTH and disease biology still indicate residual hyperfunctioning tissue.",
 "Ending the case without explicit postoperative surveillance for hematoma, recurrent-laryngeal-nerve dysfunction, symptomatic hypocalcemia/hungry bone and long-term biochemical cure.",
]

COHORT_PARATHYROID_V211={QID:{
 "concept_id":CID,"canonical_topic":TOPIC,"prompt":PROMPT,"answer_text":ANSWER,
 "explanation":"Four-gland exploration is a systematic anatomy-and-biology operation: use the RLN plane and embryologic migration to identify glands, recognize multigland disease, interpret ioPTH in physiologic context, preserve a vascularized remnant and execute a deliberate missing-gland/rescue plan.",
 "board_pearl":"Superior glands are usually posterior to the RLN plane; inferior glands are usually anterior and follow thymic migration. Known/suspected multigland disease or failed focused exploration/ioPTH response should prompt bilateral exploration—not random additional gland excision.",
 "depth_layers_v211":{"foundation":"Map superior/inferior gland embryology, RLN relationship, expected and ectopic locations, and distinguish imaging for localization from biochemical diagnosis.","application":"Perform a systematic bilateral exploration, compare all glands, recognize multigland hyperplasia, choose subtotal versus selected total/autotransplant strategy and use ioPTH appropriately.","senior_decision":"Convert from focused to bilateral exploration when indicated, reconcile inadequate ioPTH with renal physiology and missed/ectopic/supernumerary disease, preserve remnant perfusion/RLN function and rescue postoperative hypocalcemia or persistent disease."},
 "common_traps_v211":COMMON_TRAPS,
 "deliberate_review_v211":"Expanded from the exact-head v20.11e live backlog, where Four-Gland Parathyroid Exploration remained an exact canonical primary candidate with a 20-word reveal. Clinical priority was intentionally favored over higher lexical ranks because this is a resident/board/OR-critical operation with important anatomy, conversion, ioPTH, remnant-perfusion and missing-gland rescue decisions absent from the prior reveal.",
 "source_refs_v211":SOURCE_REFS_V211_PARATHYROID,
}}

def apply_four_gland_parathyroid_v211(checks, deep_modules, v6_item_id):
 by={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
 for qid,p in COHORT_PARATHYROID_V211.items():
  q=by.get(qid)
  if q is None: missing.append(qid); continue
  m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get('topic') or '') if m else ''; cid=v6_item_id(q.get('domain'),topic) if m and q.get('domain') else None
  if m is None or topic!=p['canonical_topic'] or cid!=p['concept_id'] or q.get('concept_id')!=cid: link_mismatch.append(qid); continue
  for field in ('prompt','answer_text','explanation','board_pearl','depth_layers_v211','common_traps_v211','deliberate_review_v211','source_refs_v211'): q[field]=p[field]
  q['choices']=[]; q['answer']=None; q['task_alignment_v211']=True; repaired.append(qid)
 return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
