"""Focused v20.11 depth patch for the exact-live Tracheomalacia / Bronchomalacia Concept Check.

Durable pediatric airway principles are grounded in connected Cummings 7e, Pasha 6e,
and K.J. Lee 12e. Current evidence adds free-breathing dynamic assessment and
anatomy-directed tracheopexy/bronchopexy while preserving oxygenation-first rescue.
"""
from concept_check_board_repair_v177 import _find_module

CID="v6-airway-bronchoscopy-tracheomalacia-bronchomalacia"
TOPIC="Tracheomalacia / Bronchomalacia"
QIDS=("cc-v112-rec-airway-bronchoscopy-tracheomalacia-bronchomalacia",)

SOURCE_REFS_V211_TRACHEOMALACIA=[
 {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive split copy; pediatric tracheomalacia/airway material reviewed 2026-09-06.","role":"foundation/operative: dynamic expiratory airway collapse, associated vascular/foregut anatomy, bronchoscopy, growth/support, positive pressure, and classic aortopexy principles"},
 {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy; pediatric airway/tracheomalacia material reviewed 2026-09-06.","role":"resident framework: bronchoscopy-based diagnosis, observation/support for milder disease, positive pressure, and selected surgical stabilization"},
 {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy; pediatric airway/tracheomalacia material reviewed 2026-09-06.","role":"operative cross-check: dynamic collapse, CPAP/positive-pressure splinting, vascular compression, aortopexy, and historical tracheostomy role"},
 {"type":"society_statement","citation":"Wallis C, et al. ERS statement on tracheomalacia and bronchomalacia in children. Eur Respir J. 2019;54(3):1900382. DOI 10.1183/13993003.00382-2019.","role":"authoritative pediatric statement: symptoms, free-breathing flexible bronchoscopy, dynamic imaging adjuncts, limited evidence base, CPAP and severe-disease surgical options including aortopexy/posterior tracheopexy"},
 {"type":"current_outcomes","citation":"Tracheopexy for Severe Tracheobronchomalacia in Children with Bronchopulmonary Dysplasia: A Two-Center Study of Patient Characteristics and Outcomes. 2026. PMID 42628598.","role":"current anatomy-directed surgery evidence: highly selected severe BPD/TBM cohort, frequent posterior tracheopexy/bronchopexy, lower postoperative PEEP and fewer severe respiratory events; retrospective evidence, not universal superiority"},
]

PROMPT="""An infant with a prior esophageal-atresia/tracheoesophageal-fistula repair has a brassy cough, recurrent respiratory infections, episodic cyanosis, and difficulty weaning positive pressure. Static airway imaging shows no fixed stenosis. How should you recognize and confirm tracheomalacia/bronchomalacia, distinguish intrinsic malacia from extrinsic compression, conduct dynamic airway assessment without letting the diagnostic maneuver create an unsafe airway, and choose observation/positive-pressure support versus anatomy-directed surgical stabilization?"""

ANSWER="""Foundation — tracheomalacia and bronchomalacia are dynamic central-airway problems, not simply small fixed airways. During expiration, inadequate cartilaginous support, excessive posterior membranous intrusion, or both can narrow the tracheal or bronchial lumen enough to produce clinically important flow limitation. The geometry matters because an airway dominated by anterior compression is a different operative problem from one dominated by posterior membranous prolapse or mainstem bronchomalacia. Do not reduce the diagnosis to a single percentage-collapse threshold: the ERS statement emphasizes that severity classification is not universally standardized, so symptoms, physiology, location, morphology and associated disease must be interpreted together.

Recognize the phenotype. Clues include an early brassy/barking cough, monophonic or fixed wheeze that does not behave like asthma, stridor/noisy breathing, recurrent lower-respiratory infections, secretion-retention problems, cyanotic or near-death spells, exercise limitation in an older child, and difficulty weaning PEEP or ventilation. Association with repaired esophageal atresia/tracheoesophageal fistula should sharply increase suspicion, as should congenital vascular anomalies, bronchopulmonary dysplasia, prolonged airway instrumentation, or prior cardiothoracic surgery. A child repeatedly labeled as having asthma despite atypical fixed noise or poor bronchodilator response deserves reconsideration of a dynamic central-airway diagnosis.

Diagnosis — dynamic flexible bronchoscopy in a spontaneously/free-breathing child is the key reference examination in current pediatric guidance because it shows where and when the airway collapses. Map the entire trachea and both mainstem bronchi rather than stopping once one abnormal segment is found. Describe location, longitudinal extent, anterior versus posterior contribution, bronchial extension, secretion burden and any pulsatile/extrinsic compression. Dynamic CT or other dynamic imaging is a valuable adjunct when defining vascular/compressive anatomy or distal airways and surgical planning, but a static inspiratory CT cannot reliably exclude dynamic malacia.

Diagnostic safety is part of the skill. Positive pressure can pneumatically splint a malacic airway and make collapse look less dramatic, so when clinically safe the exam should preserve spontaneous/free breathing and assess dynamic expiration. But never sacrifice oxygenation or ventilation to obtain a 'pure' diagnostic collapse. If the child desaturates, becomes hypercarbic, develops severe obstruction or cannot ventilate around the bronchoscope, stop the provocative maneuver, withdraw/reposition the scope as needed, restore effective ventilation and add PEEP/CPAP. The fact that collapse improves with positive pressure is useful physiology; it is not evidence that the disease is absent.

Application — separate primary/intrinsic malacia from secondary mechanics. Ask whether the airway wall is intrinsically weak, whether an anterior vessel or other structure compresses it, whether posterior membranous intrusion dominates, and whether a repaired foregut anomaly has distorted the posterior tracheal relationship. Evaluate aspiration/swallow dysfunction, recurrent infection and secretion clearance because they can amplify symptoms even when the airway geometry itself is unchanged. A vascular ring/sling or other causal compression must be defined rather than treating the airway in isolation.

Management should follow clinical burden, not bronchoscopy appearance alone. Many infants with milder congenital malacia improve as airway cartilage and caliber mature. Supportive treatment may include airway-clearance strategies, treatment of bacterial infection when present, management of aspiration/reflux or other associated disease when clinically relevant, nutrition/growth support and avoidance of unnecessary therapies aimed at an incorrect asthma diagnosis. The ERS statement notes that evidence for many commonly used medications and chest physiotherapy is limited, so do not present them as disease-modifying cures.

Positive airway pressure acts as a pneumatic stent. CPAP/PEEP can reduce expiratory collapse and may bridge a child through growth, illness, or ventilator weaning. A meaningful response supports the physiology but does not by itself determine whether surgery is needed. Conversely, needing progressively high pressure, recurrent severe events despite optimized support, or inability to wean respiratory support signals greater physiologic burden.

Senior decision — consider operative stabilization when severe symptoms persist despite optimized multidisciplinary care: recurrent cyanotic/apneic or life-threatening events, recurrent pneumonias with ineffective clearance, failure to thrive attributable to respiratory work, inability to liberate from substantial PEEP/ventilation, or other major functional compromise. The operation must match the collapse geometry and causal anatomy. Classic textbooks appropriately emphasize aortopexy for anterior vascular-related compression/collapse. Contemporary airway centers also use anterior tracheopexy when the anterior wall requires fixation, posterior tracheopexy when excessive posterior membranous intrusion is the dominant mechanism, and bronchopexy when mainstem bronchomalacia materially contributes. Complex patients may require combinations plus correction of a vascular anomaly or other compressive lesion.

Textbook-versus-current-evidence distinction — the durable textbook principles remain correct: diagnose dynamically, understand associated vascular/foregut anatomy, use positive pressure as an airway splint, and reserve major surgery for important physiology. What has evolved is the operative menu. Aortopexy or tracheostomy should not be taught as automatic endpoints for every severe child. Modern specialty-center series support anatomy-directed anterior/posterior tracheopexy and bronchopexy in selected patients. A 2026 two-center retrospective BPD/TBM cohort reported decreased PEEP and fewer severe respiratory events after predominantly posterior tracheopexy/bronchopexy, but this is observational evidence from highly selected patients and does not establish universal superiority over other operations.

Tracheostomy requires nuanced reasoning. It can provide a stable airway interface and a route for positive pressure, but it does not magically bypass distal tracheomalacia or mainstem bronchomalacia; the tube tip may still sit proximal to important collapse. Before choosing it as the mechanical solution, map the distal airway and define what problem the tracheostomy will actually solve. Internal or external stents likewise belong to carefully selected multidisciplinary/salvage situations rather than routine first-line management because device-related and airway-growth issues are substantial.

OR/danger-zone reasoning — before bronchoscopy or reconstruction, explicitly plan how ventilation will be rescued if dynamic collapse becomes critical. During bronchoscopy, loss of effective ventilation, progressive desaturation, hypercarbia or inability to pass gas around the scope means diagnostic completeness has lost priority: withdraw or reposition the scope, restore ventilation, apply positive pressure/PEEP and escalate the airway plan. During surgical planning, do not operate from a single still image or one tracheal segment. Missing bronchial extension can produce a technically successful tracheal procedure with persistent physiology. Likewise, fixing posterior collapse while leaving major anterior vascular compression—or vice versa—can leave the causal mechanism untreated.

Senior synthesis — use five questions. PHYSIOLOGY: are the symptoms truly produced by dynamic central-airway collapse? MAP: where is the collapse and does it extend into either mainstem bronchus? GEOMETRY: is the dominant problem weak cartilage, posterior membrane intrusion, anterior/extrinsic compression, or a combination? BURDEN: can the child safely grow with airway clearance and pneumatic splinting, or are there recurrent life-threatening events, infections, growth failure or ventilator dependence? MATCH: which intervention actually addresses that geometry—continued support, correction of compressive anatomy, anterior/aortic suspension, posterior tracheopexy, bronchopexy, or a combined strategy? The dangerous errors are calling every wheeze asthma, relying on static imaging, forcing a bronchoscopy through deteriorating oxygenation, choosing surgery from a percentage-collapse number alone, and treating 'tracheomalacia' as one anatomy with one operation."""

COMMON_TRAPS=[
 "Calling a brassy cough or fixed monophonic wheeze 'asthma' repeatedly without considering dynamic central-airway collapse when the phenotype or treatment response is atypical.",
 "Using a normal static inspiratory CT to exclude tracheomalacia/bronchomalacia instead of obtaining appropriate dynamic airway assessment.",
 "Assigning surgery from a percentage-collapse threshold alone without integrating symptoms, physiology, location, morphology and associated disease.",
 "Continuing free-breathing/provocative bronchoscopy despite desaturation or failing ventilation just to document maximal collapse instead of restoring oxygenation and positive-pressure ventilation.",
 "Concluding malacia is absent because positive pressure splints the lumen open during anesthesia; the ventilation strategy can mask the dynamic abnormality.",
 "Choosing aortopexy reflexively before defining whether the dominant mechanism is anterior vascular compression, posterior membranous intrusion, bronchomalacia or mixed disease.",
 "Planning an isolated tracheal operation after seeing tracheal collapse but failing to map both mainstem bronchi for clinically important bronchomalacia.",
 "Assuming a tracheostomy bypasses the disease even when significant distal tracheal or mainstem bronchial collapse lies beyond the tube tip.",
 "Using airway stenting as routine first-line pediatric therapy rather than a carefully selected multidisciplinary/salvage strategy with device and growth risks.",
 "Ignoring associated TEF/EA anatomy, vascular compression, aspiration, infection and secretion-clearance problems that may drive symptoms and alter the definitive operation.",
]

COHORT_TRACHEOMALACIA_V211={qid:{
 "concept_id":CID,"canonical_topic":TOPIC,"prompt":PROMPT,"answer_text":ANSWER,
 "explanation":"Tracheobronchomalacia is a dynamic, geometry-specific central-airway disorder. Diagnose it dynamically, map tracheal and bronchial extent plus compressive anatomy, preserve oxygenation during assessment, use positive pressure as a bridge when appropriate, and match severe-disease surgery to anterior, posterior, bronchial or mixed collapse.",
 "board_pearl":"Do not choose an operation from a collapse percentage alone. Free-breathing dynamic bronchoscopy defines physiology, but oxygenation outranks diagnostic purity; severe disease requires anatomy-directed stabilization rather than reflex aortopexy or tracheostomy.",
 "depth_layers_v211":{"foundation":"Dynamic expiratory collapse, clinical phenotype, associated TEF/EA/vascular disease, and free-breathing bronchoscopy with dynamic imaging adjuncts.","application":"Map tracheal/bronchial extent and collapse geometry, treat associated disease, use CPAP/PEEP as a pneumatic stent, and distinguish malacia from fixed stenosis or isolated extrinsic compression.","senior_decision":"Use physiologic severity rather than percentage collapse alone, preserve oxygenation during diagnostic maneuvers, and match anterior/aortic suspension, posterior tracheopexy, bronchopexy or combined repair to exact anatomy while recognizing limits of tracheostomy/stents."},
 "common_traps_v211":COMMON_TRAPS,
 "deliberate_review_v211":"Selected from the exact live 529a0e7b production backlog because the single exact Tracheomalacia / Bronchomalacia Concept Check remained a 16-word reveal despite high pediatric-airway, board and OR value. Durable Cummings/Pasha/K.J. Lee principles were retained, while management was updated to ERS guidance and contemporary anatomy-directed tracheopexy/bronchopexy evidence without overstating retrospective specialty-center outcomes.",
 "source_refs_v211":SOURCE_REFS_V211_TRACHEOMALACIA,
} for qid in QIDS}


def apply_tracheomalacia_bronchomalacia_v211(checks, deep_modules, v6_item_id):
 by={str(q.get('id') or ''):q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
 for qid,p in COHORT_TRACHEOMALACIA_V211.items():
  q=by.get(qid)
  if q is None: missing.append(qid); continue
  m=_find_module(q,deep_modules,v6_item_id); topic=str(m.get('topic') or '') if m else ''; cid=v6_item_id(q.get('domain'),topic) if m and q.get('domain') else None
  if m is None or topic!=p['canonical_topic'] or cid!=p['concept_id'] or q.get('concept_id')!=cid: link_mismatch.append(qid); continue
  for field in ('prompt','answer_text','explanation','board_pearl','depth_layers_v211','common_traps_v211','deliberate_review_v211','source_refs_v211'): q[field]=p[field]
  q['choices']=[]; q['answer']=None; q['task_alignment_v211']=True; repaired.append(qid)
 return {'repaired':repaired,'missing':missing,'link_mismatch':link_mismatch}
