"""v18.6 — next high-yield live-canonical Concept Check depth cohort.

Selected from the validated V185 backlog. Exact canonical resolution is required
before mutation. These eight topics prioritize call risk, perioperative judgment,
oncology surveillance, frailty, stewardship, and complication rescue.
"""

from concept_check_board_repair_v177 import _find_module

COHORT = {
    "cc-v112-rec-general-ent-emergencies-geriatric-otolaryngology-frailty": {
        "concept_id": "v6-general-ent-emergencies-geriatric-otolaryngology-frailty",
        "canonical_topic": "Geriatric Otolaryngology / Frailty",
        "prompt": "An 84-year-old with mild cognitive impairment, recent falls, weight loss and limited reserve is referred for a technically resectable head-and-neck operation. How should frailty change preoperative assessment, consent and postoperative planning, and which findings should make you reconsider an otherwise anatomically feasible operation?",
        "answer_text": "Chronologic age alone should not determine candidacy; assess physiologic reserve and vulnerability. I would document functional status, gait/falls, cognition and delirium risk, nutrition/weight loss, polypharmacy, hearing/vision, cardiopulmonary reserve, social support and the patient's baseline independence and goals. Frailty screening should trigger targeted optimization rather than serve as an automatic exclusion label. Prehabilitation, nutrition, medication review, hearing/communication support and advance planning can reduce preventable postoperative decline. Consent should compare oncologic or functional benefit with the realistic risks of delirium, loss of independence, prolonged rehabilitation, dysphagia, aspiration and non-home discharge. Severe frailty, progressive cognitive decline, inability to tolerate the expected airway/nutrition course, or a mismatch between treatment burden and the patient's goals should prompt multidisciplinary reconsideration, modification or nonsurgical treatment even when anatomy is operable. Postoperatively use delirium prevention, early mobility, multimodal analgesia, orientation, sleep preservation and aggressive nutrition/swallow support rather than waiting for deconditioning to occur.",
        "explanation": "Frailty predicts tolerance of treatment better than age alone. The senior decision is whether the expected benefit remains worthwhile after accounting for reserve, cognition, recovery trajectory and the patient's priorities.",
        "board_pearl": "Operable anatomy does not equal an operable patient; frailty is a recovery-risk phenotype, not a birthday.",
        "depth_layers_v186": {"foundation": "Separate frailty and physiologic reserve from chronologic age.", "application": "Assess function, cognition, nutrition, falls, polypharmacy, support and delirium risk and optimize modifiable vulnerabilities.", "senior_decision": "Modify or defer treatment when expected recovery burden, loss of independence or airway/nutrition needs conflict with reserve or goals."},
        "common_traps_v186": ["Using age alone to deny treatment misses robust older adults who may tolerate surgery well.", "Ignoring cognition and baseline independence can produce an oncologically successful operation followed by preventable delirium and permanent functional decline."],
        "deliberate_review_v186": "Expanded an 18-word frailty statement into preoperative phenotype assessment, optimization, consent, postoperative delirium prevention and treatment-burden tradeoffs."
    },
    "cc-v112-rec-general-ent-emergencies-immunocompromised-host-in-otolaryngology": {
        "concept_id": "v6-general-ent-emergencies-immunocompromised-host-in-otolaryngology",
        "canonical_topic": "Immunocompromised Host in Otolaryngology",
        "prompt": "A neutropenic patient receiving chemotherapy develops rapidly progressive facial pain, fever and unilateral necrotic nasal mucosa despite broad-spectrum antibiotics. How should immunosuppression alter the differential, diagnostic tempo, antimicrobial strategy and threshold for operative source control?",
        "answer_text": "In an immunocompromised host, muted examination findings do not imply mild disease and pathogen breadth changes substantially. Rapid facial pain with necrotic mucosa should raise immediate concern for invasive fungal rhinosinusitis while also considering resistant bacterial infection and other opportunistic processes. Obtain urgent nasal endoscopy with biopsy for frozen/permanent pathology and fungal studies when feasible, cross-sectional imaging to define orbital/skull-base/intracranial extension, and involve infectious disease, oncology and anesthesia early. Start empiric therapy appropriate to the suspected invasive pathogen and immune defect without waiting for every test when the clinical syndrome is dangerous; then narrow therapy when cultures/pathology allow. In suspected invasive fungal disease, systemic antifungal treatment and prompt surgical debridement of devitalized tissue are complementary forms of source control, not competing alternatives. Persistent fever or progression despite therapy should trigger re-phenotyping: wrong pathogen, inadequate drug exposure, persistent neutropenia, undrained compartment, vascular invasion or noninfectious mimic. Orbital signs, cranial neuropathy, altered mental status, palate necrosis or vascular/intracranial extension require urgent escalation.",
        "explanation": "Immunosuppression changes both pathogen probability and the reliability of classic inflammatory signs. Worsening despite broad therapy should provoke diagnostic re-phenotyping and source-control review rather than reflexive antibiotic broadening alone.",
        "board_pearl": "In the immunocompromised patient, necrosis is a clock: biopsy, treat and control the source in parallel.",
        "depth_layers_v186": {"foundation": "Recognize opportunistic pathogens and blunted inflammatory presentations.", "application": "Pair urgent tissue diagnosis and extension imaging with immune-defect-appropriate empiric therapy.", "senior_decision": "Escalate early to debridement/source control and re-phenotype treatment failure instead of simply broadening antimicrobials."},
        "common_traps_v186": ["Waiting for culture finalization before treating a classic invasive fungal syndrome can allow vascular and intracranial progression.", "Escalating to ever-broader antibiotics without checking for devitalized tissue, fungal disease or an undrained compartment treats uncertainty rather than the patient."],
        "deliberate_review_v186": "Expanded a 22-word warning into pathogen/immune-defect reasoning, urgent biopsy, antifungal/debridement parallel treatment and treatment-failure re-phenotyping."
    },
    "cc-v112-rec-head-neck-oncology-head-neck-cancer-surveillance-second-primaries": {
        "concept_id": "v6-head-neck-oncology-head-neck-cancer-surveillance-second-primaries",
        "canonical_topic": "Head & Neck Cancer Surveillance / Second Primaries",
        "prompt": "A tobacco-exposed survivor of treated oral cavity SCC returns two years later with new unilateral otalgia and weight loss but a normal routine oral examination. How should surveillance distinguish recurrence, treatment toxicity and a second primary, and what symptoms should trigger targeted imaging or endoscopic evaluation rather than routine follow-up?",
        "answer_text": "Surveillance combines symptom-driven examination with risk-based follow-up rather than repetitive imaging by habit. Review the original site, stage, treatment and recurrence pattern; perform complete head-and-neck examination including flexible endoscopy when appropriate, assess neck nodes and treatment-related function, and address tobacco/alcohol cessation, dental care, nutrition, swallowing, thyroid or other treatment-specific late effects. New focal pain, referred otalgia, unexplained weight loss, bleeding, dysphagia, new mass, cranial neuropathy or progressive voice/airway change requires targeted investigation even when the routine surface examination is unrevealing. Choose CT, MRI, PET/CT or directed endoscopy/biopsy according to the suspected site and clinical question rather than ordering every modality. Tobacco-exposed patients remain at risk for second primaries in the upper aerodigestive tract and lung, so a new symptom is not automatically local recurrence. Surveillance should also detect functional morbidity that is treatable. The key is to establish a new diagnosis promptly while avoiding low-yield indefinite imaging in an asymptomatic stable survivor.",
        "explanation": "Post-treatment symptoms can represent recurrence, a second primary or late toxicity. The surveillance plan should be risk- and symptom-directed and must not let a normal cursory examination overrule persistent focal warning symptoms.",
        "board_pearl": "A cancer survivor with a new focal symptom earns a new diagnostic question, not the reassurance of yesterday's surveillance plan.",
        "depth_layers_v186": {"foundation": "Know recurrence patterns, field-cancerization/second-primary risk and late-treatment toxicity.", "application": "Use complete examination plus symptom-directed imaging/endoscopy and survivorship assessment.", "senior_decision": "Escalate persistent focal symptoms despite a normal routine examination and avoid indiscriminate indefinite imaging in asymptomatic survivors."},
        "common_traps_v186": ["Assuming every new symptom is radiation toxicity can delay diagnosis of recurrence or a second primary.", "Ordering serial whole-body imaging without a clinical question can create false positives while missing the need for directed endoscopy or biopsy."],
        "deliberate_review_v186": "Expanded a 23-word surveillance answer into symptom triggers, second-primary risk, modality selection and survivorship-function assessment."
    },
    "cc-v112-rec-head-neck-oncology-tracheal-malignancy": {
        "concept_id": "v6-head-neck-oncology-tracheal-malignancy",
        "canonical_topic": "Tracheal Malignancy",
        "prompt": "An adult with months of progressive wheeze unresponsive to asthma therapy is found to have a proximal tracheal mass causing critical fixed narrowing. How do you secure the airway without converting partial obstruction into complete obstruction, stage resectability and decide endoscopic temporization versus definitive tracheal resection or nonsurgical therapy?",
        "answer_text": "First treat the airway physiology. A critically narrowed fixed trachea can collapse with sedation, paralysis or poorly planned instrumentation, so define the level and severity from awake examination/imaging and coordinate an airway strategy with anesthesia and thoracic/head-and-neck expertise before induction. CT of the neck/chest characterizes length, extraluminal invasion, nodal/distant disease and relationship to major vessels/esophagus; bronchoscopy provides tissue and precise endoluminal mapping when it can be performed safely. Endoscopic debulking, dilation or stenting can restore lumen or obtain tissue in selected unstable/obstructed patients, but it is temporizing when an oncologic resection is feasible and can also complicate later surgery. Definitive segmental tracheal resection depends on histology, tumor length, margin feasibility, laryngeal/cricoid involvement, mediastinal mobility and whether a tension-free anastomosis is possible. Unresectable or medically inoperable disease may require radiation/systemic therapy according to histology. Stridor, increasing work of breathing, inability to lie flat or rapidly worsening obstruction mandates urgent controlled-airway planning rather than routine elective bronchoscopy.",
        "explanation": "Tracheal cancer is simultaneously an airway and oncologic-resectability problem. The dangerous error is inducing anesthesia before deciding how oxygenation will be maintained across the obstructing segment.",
        "board_pearl": "With critical tracheal narrowing, the airway plan comes before the biopsy plan.",
        "depth_layers_v186": {"foundation": "Recognize fixed central-airway obstruction masquerading as asthma and localize the lesion.", "application": "Stage length/invasion and obtain bronchoscopic tissue only within a safe airway strategy.", "senior_decision": "Use endoscopic rescue selectively and choose resection based on margins and tension-free reconstruction; avoid routine induction in critical obstruction."},
        "common_traps_v186": ["Treating progressive fixed wheeze as asthma delays diagnosis until the airway is dangerously narrow.", "Inducing general anesthesia for a routine biopsy without a cross-obstruction oxygenation plan can convert a stable partial obstruction into a cannot-ventilate emergency."],
        "deliberate_review_v186": "Expanded a 27-word statement into critical-airway physiology, staging, endoscopic temporization, resection constraints and nonsurgical options."
    },
    "cc-v112-rec-general-ent-emergencies-laser-energy-safety-in-otolaryngology": {
        "concept_id": "v6-general-ent-emergencies-laser-energy-safety-in-otolaryngology",
        "canonical_topic": "Laser / Energy Safety in Otolaryngology",
        "prompt": "During transoral laser surgery the team plans high inspired oxygen, a standard PVC tube and wet pledgets but has not discussed airway-fire rescue. What must be changed before activation, how do laser wavelength and tissue interaction alter eye/airway precautions, and what is the immediate response to an airway fire?",
        "answer_text": "Do not activate the laser until a shared fire-prevention plan is explicit. Use the lowest inspired oxygen concentration compatible with safe oxygenation, avoid nitrous oxide, use a laser-resistant airway tube or appropriate tubeless technique when indicated, protect exposed combustible material with wet pledgets and account for them, and ensure wavelength-appropriate eye protection for the patient and room personnel. The laser safety officer/team should confirm warning signage, plume evacuation, equipment readiness and clear verbal communication before activation. Different wavelengths have different absorption and penetration profiles, so tissue effect, protective eyewear and reflected-beam risk are device specific; power and exposure should be the minimum needed for the target. If an airway fire occurs, stop the laser, disconnect/stop oxidizer flow, remove the burning tube or material promptly, extinguish with saline/water, re-establish ventilation with room air when possible and assess the airway by bronchoscopy for thermal injury and retained debris. An unsafe fire triangle is a reason to stop the case setup, not merely document concern.",
        "explanation": "Laser safety is prevention plus rehearsed rescue. Fuel, oxidizer and ignition source must all be controlled, and airway-fire management must be immediate and coordinated.",
        "board_pearl": "If the team cannot state the airway-fire rescue sequence before the laser fires, the laser is not ready to fire.",
        "depth_layers_v186": {"foundation": "Understand fuel-oxidizer-ignition fire-triangle and wavelength-specific tissue/eye hazards.", "application": "Reduce oxidizer, use appropriate tube/pledgets/eye protection, plume control and explicit activation communication.", "senior_decision": "Stop an unsafe setup and execute immediate tube removal, extinguishment, reoxygenation and bronchoscopic injury assessment after fire."},
        "common_traps_v186": ["Relying on a laser-resistant tube while using unnecessarily high oxygen leaves the fire triangle intact.", "Continuing the operation after extinguishing a fire without bronchoscopic assessment can miss distal thermal injury or retained burned material."],
        "deliberate_review_v186": "Expanded a 28-word generic safety answer into fire-triangle prevention, wavelength-specific precautions and exact airway-fire rescue."
    },
    "cc-v112-rec-pediatric-otolaryngology-pediatric-vocal-fold-immobility": {
        "concept_id": "v6-pediatric-otolaryngology-pediatric-vocal-fold-immobility",
        "canonical_topic": "Pediatric Vocal Fold Immobility",
        "prompt": "An infant has persistent stridor and feeding difficulty after cardiac surgery; flexible laryngoscopy shows one vocal fold immobile near the paramedian position. How do you distinguish neurogenic paralysis from fixation, evaluate aspiration and recovery potential, and decide observation, injection, reinnervation or airway-widening intervention?",
        "answer_text": "Confirm laterality, resting position, contralateral motion and the relationship of symptoms to airway and swallowing. The history of cardiothoracic surgery raises recurrent laryngeal nerve injury, but persistent immobility may also reflect cricoarytenoid fixation, posterior glottic scar or central neurologic disease, so direct laryngoscopy with palpation is useful when fixation is plausible or management depends on the distinction. Assess feeding and aspiration clinically and with instrumental swallowing evaluation when symptoms or pulmonary consequence warrant it. Many unilateral injuries may recover, so recovery timing, etiology and symptom severity guide observation versus temporary medialization. Injection can improve glottic closure and swallowing in selected symptomatic unilateral cases while recovery remains possible; reinnervation offers longer-term tone in appropriate persistent paralysis. Bilateral immobility or severe airway compromise requires a separate airway strategy, balancing tracheostomy or airway-widening procedures against voice and aspiration consequences. Progressive respiratory distress, recurrent aspiration pneumonia, failure to thrive or inability to maintain a safe airway should accelerate intervention rather than waiting solely for nerve recovery.",
        "explanation": "Pediatric vocal-fold immobility is not synonymous with nerve paralysis. The management hinges on airway versus swallow physiology, fixation versus denervation and the likelihood of spontaneous recovery.",
        "board_pearl": "Before treating an immobile fold as a dead nerve, decide whether the arytenoid can actually move.",
        "depth_layers_v186": {"foundation": "Differentiate unilateral/bilateral immobility and neurogenic paralysis from mechanical fixation.", "application": "Assess aspiration, pulmonary/feeding consequence and recovery potential and use temporary augmentation selectively.", "senior_decision": "Escalate airway-compromising bilateral disease or persistent symptomatic paralysis to reinnervation/airway surgery while balancing voice and aspiration."},
        "common_traps_v186": ["Assuming every postoperative immobile fold is neurogenic can miss posterior glottic scar or cricoarytenoid fixation.", "Waiting for spontaneous recovery despite recurrent aspiration pneumonia or worsening respiratory distress allows preventable morbidity."],
        "deliberate_review_v186": "Expanded a 29-word evaluation answer into fixation-versus-paralysis localization, swallowing workup, recovery timing and procedure tradeoffs."
    },
    "cc-v112-rec-general-ent-emergencies-antimicrobial-stewardship-in-otolaryngology": {
        "concept_id": "v6-general-ent-emergencies-antimicrobial-stewardship-in-otolaryngology",
        "canonical_topic": "Antimicrobial Stewardship in Otolaryngology",
        "prompt": "A stable postoperative neck patient remains febrile on broad vancomycin plus piperacillin-tazobactam despite negative blood cultures; CT shows a new rim-enhancing collection. How should stewardship change the next step, when should therapy be broadened versus narrowed, and what does persistent fever actually mean?",
        "answer_text": "Persistent fever on broad antibiotics is not proof that the drug spectrum is too narrow. Reassess the diagnosis, source and host: examine the wound and airway, review cultures and prior antibiotics, identify hardware or salivary contamination, and ask whether imaging shows a drainable compartment. A rim-enhancing postoperative collection with ongoing sepsis usually makes source control the next priority; obtain cultures at drainage when possible and then tailor therapy to the actual organisms and clinical trajectory. Empiric coverage should reflect syndrome, severity, local resistance and host factors, with MRSA, anaerobic, gram-negative or fungal coverage added only when the phenotype supports it. De-escalate once cultures and source control permit, use the narrowest effective agent, appropriate route and shortest evidence-based duration, and avoid duplicate anaerobic or antipseudomonal coverage. If the patient worsens despite apparently adequate therapy, reconsider undrained infection, resistant or unexpected pathogen, drug exposure, immune defect and noninfectious fever rather than reflexively stacking antibiotics. Stewardship is diagnostic precision plus source control, not simply using fewer drugs.",
        "explanation": "Broadening therapy cannot sterilize an undrained abscess. Stewardship protects efficacy by matching spectrum and duration to the actual syndrome while repeatedly reassessing source control and diagnosis.",
        "board_pearl": "When broad antibiotics are 'failing,' ask first whether the infection is trapped somewhere the antibiotic cannot fix.",
        "depth_layers_v186": {"foundation": "Match empiric spectrum to syndrome, severity, host and local resistance.", "application": "Obtain source cultures and de-escalate after drainage/clinical data using the narrowest effective regimen and duration.", "senior_decision": "Treat persistent fever as a diagnostic/source-control problem before reflexive broadening and investigate unexpected pathogens or noninfectious mimics when trajectory worsens."},
        "common_traps_v186": ["Adding a third broad agent to an undrained abscess increases toxicity without correcting the source-control failure.", "Continuing maximal empiric coverage after cultures and source control define a narrower pathogen wastes spectrum and obscures later diagnostic interpretation."],
        "deliberate_review_v186": "Expanded a 33-word stewardship answer into source-control reasoning, phenotype-based broadening, de-escalation and treatment-failure re-evaluation."
    },
    "cc-v112-rec-rhinology-allergy-skull-base-intracranial-complications-of-sinusitis": {
        "concept_id": "v6-rhinology-allergy-skull-base-intracranial-complications-of-sinusitis",
        "canonical_topic": "Intracranial Complications of Sinusitis",
        "prompt": "A teenager with frontal sinusitis develops severe headache, vomiting, fever and subtle confusion despite oral antibiotics. How do you evaluate for epidural/subdural empyema or brain abscess, coordinate sinus and intracranial source control, and identify findings that demand immediate escalation?",
        "answer_text": "Neurologic symptoms in bacterial sinusitis are an emergency until intracranial spread is excluded. Perform a focused neurologic examination, assess mental status and signs of meningismus or raised intracranial pressure, obtain urgent contrast-enhanced MRI when available for sensitive intracranial evaluation and CT to define the paranasal sinus/bony anatomy when useful for operative planning. Begin IV antimicrobial therapy with appropriate intracranial penetration and coverage for expected sinus pathogens while obtaining blood or operative cultures; do not delay treatment for a lumbar puncture when mass effect or focal intracranial infection is possible. Involve neurosurgery and rhinology/ENT early. Drain the infected sinus source endoscopically when indicated and coordinate neurosurgical drainage for subdural empyema, sizable/loculated abscess, mass effect or neurologic deterioration; antibiotics alone are insufficient when a drainable intracranial collection is driving disease. Worsening mental status, focal neurologic deficit, seizure, papilledema, persistent bacteremia or radiographic mass effect requires immediate escalation and monitored care. Repeat imaging is driven by clinical trajectory and adequacy of source control.",
        "explanation": "Intracranial sinus complications require parallel antimicrobial treatment and anatomic source control. The dangerous mistake is treating a neurologic presentation as uncomplicated sinusitis or performing lumbar puncture before excluding mass effect.",
        "board_pearl": "Sinusitis plus a new neurologic symptom is no longer routine sinusitis—image the brain and assemble the source-control team early.",
        "depth_layers_v186": {"foundation": "Recognize epidural/subdural empyema, brain abscess and meningitic/intracranial warning symptoms.", "application": "Use urgent contrast MRI/CT, IV intracranial-penetrating antibiotics and early ENT/neurosurgical consultation.", "senior_decision": "Coordinate sinus and neurosurgical drainage for collections/mass effect and avoid lumbar puncture when focal infection or raised pressure is possible."},
        "common_traps_v186": ["Escalating oral sinus antibiotics without intracranial imaging in a confused patient delays diagnosis of empyema or abscess.", "Performing lumbar puncture before excluding mass effect can be dangerous and does not substitute for imaging a focal intracranial complication."],
        "deliberate_review_v186": "Expanded a 19-word imaging statement into neurologic triage, imaging modality selection, antimicrobial penetration and coordinated ENT-neurosurgical source control."
    },
}


def apply_concept_check_task_alignment_v186(checks, deep_modules, v6_item_id):
    by_id = {str(q.get("id") or ""): q for q in checks or []}
    repaired, missing, link_mismatch = [], [], []
    for qid, payload in COHORT.items():
        q = by_id.get(qid)
        if q is None:
            missing.append(qid); continue
        module = _find_module(q, deep_modules, v6_item_id)
        domain = str(q.get("domain") or "")
        topic = str(module.get("topic") or "") if module else ""
        cid = v6_item_id(domain, topic) if module and domain else None
        if not module or topic != payload["canonical_topic"] or cid != payload["concept_id"] or q.get("concept_id") != cid:
            link_mismatch.append(qid); continue
        for key in ("prompt", "answer_text", "explanation", "board_pearl", "depth_layers_v186", "common_traps_v186", "deliberate_review_v186"):
            q[key] = payload[key]
        q["task_alignment_v186"] = True
        q.pop("choices", None); q.pop("answer", None); q.pop("why_wrong", None)
        repaired.append(qid)
    return {"repaired": repaired, "missing": missing, "link_mismatch": link_mismatch}

__all__ = ["COHORT", "apply_concept_check_task_alignment_v186"]
