"""v20.13 — deepen exact live Submandibular Gland Excision Concept Check."""
from concept_check_board_repair_v177 import _find_module

QID = "cc-v112-rec-thyroid-parathyroid-salivary-submandibular-gland-excision"
CID = "v6-thyroid-parathyroid-salivary-submandibular-gland-excision"
TOPIC = "Submandibular Gland Excision"

SOURCE_REFS_V213 = [
    {"type":"textbook","citation":"Cummings Otolaryngology: Head and Neck Surgery, 7th ed. (2021), connected Google Drive Cummings 7e corpus, salivary-gland anatomy, obstructive disease, neoplasm, and operative-management sections reviewed/cross-referenced 2026-09-07.","role":"durable anatomy/operative foundation: submandibular space, facial vessels, marginal mandibular branch, lingual and hypoglossal nerves, Wharton duct, inflammatory versus oncologic dissection"},
    {"type":"textbook","citation":"Pasha R, Golub JS. Otolaryngology-Head and Neck Surgery: Clinical Reference Guide, 6th ed. (2022), connected Google Drive copy, salivary-gland disease and surgery material cross-referenced 2026-09-07.","role":"board framework: obstructive/inflammatory indications, salivary neoplasm evaluation, operative complications and nerve protection"},
    {"type":"textbook","citation":"K.J. Lee's Essential Otolaryngology: Head & Neck Surgery, 12th ed. (2019), connected Google Drive copy, salivary-gland anatomy and submandibular disease/surgery material cross-referenced 2026-09-07.","role":"operative cross-check: transcervical excision anatomy, facial-vessel relationships, lingual/hypoglossal nerve danger zones and postoperative morbidity"},
    {"type":"operative_text","citation":"Myers Neck Dissection.pdf, connected Google Drive operative neck-dissection reference, identified in source search 2026-09-07.","role":"supplemental neck-plane and cranial-nerve orientation cross-check"},
    {"type":"guideline","citation":"Geiger JL, et al. Management of Salivary Gland Malignancy: ASCO Guideline. J Clin Oncol. 2021;39(17):1909-1941. PMID: 33900808. DOI: 10.1200/JCO.21.00449.","role":"authoritative malignant-salivary framework: pathologic diagnosis, imaging/staging, complete resection when feasible, neck/adjuvant decisions based on disease biology and stage"},
    {"type":"systematic_review","citation":"Success rate of sialendoscopy: a systematic review and meta-analysis. Oral Dis. 2023. PMID: 37486613.","role":"current obstructive-disease evidence: gland-preserving sialendoscopy is effective and generally safe, with pooled submandibular success about 88% in the included literature"},
    {"type":"systematic_review","citation":"Lee YC, et al. Gland-preserving surgery versus total gland excision for benign submandibular tumors: A systematic review and meta-analysis. Surg Oncol. 2026;66:102433. PMID: 42001628.","role":"evolving benign-tumor evidence: selected gland-preserving surgery may improve salivary/cosmetic outcomes and reduce marginal-mandibular injury, but evidence is limited to four studies/318 patients and does not replace oncologic principles"},
]

PROMPT = """An adult has recurrent painful left submandibular swelling despite appropriate gland-preserving treatment, but imaging also shows a discrete intraglandular mass that requires oncologic exclusion. How should you decide whether whole-gland excision is appropriate, plan a safe transcervical operation around the marginal mandibular, lingual, and hypoglossal nerves, control the facial vessels and Wharton duct, change the dissection if tumor biology or scar makes the usual plane unsafe, and rescue bleeding or postoperative airway compromise?"""

ANSWER = """Foundation — first decide why the gland is being removed. Submandibular gland excision is not the default treatment for every stone or episode of sialadenitis. Modern obstructive-salivary practice favors gland preservation when feasible: sialendoscopy, transoral stone removal, or a combined approach can treat many stones and stenoses while retaining gland function. Whole-gland excision remains appropriate for refractory obstructive/inflammatory disease when conservative and gland-preserving options have failed or are unsuitable, and for selected neoplasms when removal of the gland is part of an oncologically sound operation. A discrete mass changes the preoperative mindset: do not enter the neck assuming chronic sialadenitis when salivary malignancy remains possible. Obtain appropriate imaging and tissue diagnosis when indicated, stage suspected malignancy, and plan the operation around histology, extent, nerve involvement and neck-management needs rather than using a benign stone operation as the template.

Anatomic map — the submandibular gland has superficial and deep components that wrap around the posterior free edge of the mylohyoid. The superficial gland fills much of the submandibular triangle. The facial vein and facial artery are closely related to the gland and may need deliberate ligation or preservation depending on the operation. The marginal mandibular branch of the facial nerve is vulnerable in the superior flap near the mandibular border and facial vessels. Deep to the gland, the lingual nerve, submandibular ganglion, Wharton duct and hypoglossal nerve are the major structures that turn a routine dissection into a nerve-injury operation. The lingual nerve is intimately related to the duct in the floor of mouth; the hypoglossal nerve lies deeper and inferior/posterior to the operative field. Never treat a white cord as 'the duct' until the nerve-duct relationship is understood.

Exposure and marginal-mandibular protection — place the transcervical incision sufficiently below the mandibular border and raise the superior flap in a controlled plane. There are several accepted ways to protect the marginal mandibular nerve, including deliberate identification in selected cases or maintaining a protective fascial plane and manipulating the facial vessels/gland inferiorly. No single maneuver should be taught as universally mandatory; the durable rule is to know where the nerve is at risk, avoid blind superior traction and energy use, and keep the nerve with the protected flap rather than dissecting toward it unintentionally. A scarred inflammatory neck deserves slower layer-by-layer exposure because inflammation can erase the clean tissue planes described in textbooks.

Gland mobilization and vessel control — develop the inferior and posterior gland surfaces under direct vision. The facial vein may be encountered superficially and the facial artery may groove or traverse the posterior gland. Control vessels deliberately with adequate proximal/distal purchase rather than avulsing them from the gland. If brisk bleeding obscures the field, apply pressure, improve exposure and obtain controlled vascular ligation; blind clamping in the deep submandibular space risks the lingual or hypoglossal nerve. Hemostasis should improve the anatomy, not make it less visible.

Deep dissection — as the gland is mobilized, identify the posterior mylohyoid edge and understand when the deep lobe, duct and lingual-nerve complex come into view. Retracting the mylohyoid and gland can expose the floor-of-mouth relationships. Identify the lingual nerve before dividing structures attached to the gland. The submandibular ganglion/parasympathetic connections can be divided from the gland under direct vision while preserving the lingual nerve. Trace Wharton duct far enough to distinguish it confidently from neural tissue, then ligate/divide the duct without incorporating the lingual nerve. Protect the hypoglossal nerve during inferior/deep mobilization; avoid aggressive traction, blind clips and thermal spread in its expected plane. Remove the gland without unnecessary violation of adjacent floor-of-mouth structures.

Benign inflammation versus tumor — chronic sialadenitis may make the gland densely adherent, but fibrosis is not permission to sacrifice a nerve for an elective benign endpoint. When the expected plane disappears, stop, re-establish landmarks from a safer direction, obtain assistance if needed, and decide whether the benefit of completing elective excision justifies escalating nerve risk. Conversely, a suspected neoplasm should not be 'shelled out' through the gland. Preserve the tumor capsule when possible and avoid piecemeal violation. If an unexpected infiltrative process is encountered, reassess the oncologic plan rather than forcing completion of a benign dissection. For resectable salivary malignancy, contemporary ASCO guidance supports complete surgical resection when appropriate; neck management and adjuvant therapy depend on stage, grade, histology, margins, perineural disease and other risk features. The senior distinction is that nerve preservation is the default in benign disease, whereas proven gross malignant nerve invasion can change the oncologic balance and requires an explicit resection/reconstruction discussion.

Gland preservation is also evolving for selected benign tumors. A 2026 meta-analysis of four studies and 318 patients found better unstimulated salivary flow, cosmetic outcomes and a lower marginal-mandibular injury rate with gland-preserving surgery, without a detected recurrence penalty. That is promising but not a universal new standard: the evidence base is small and vulnerable to selection bias, and it applies to appropriately selected benign tumors, not lesions of uncertain or malignant biology. Preserve this disagreement explicitly: durable textbook total-gland excision remains a standard operation, while carefully selected benign disease may increasingly be managed with gland-preserving techniques at experienced centers.

Completion and postoperative plan — inspect the field with attention to the facial-vessel pedicles, floor of mouth and nerve courses before closing. A drain is selective rather than a substitute for hemostasis. Counsel about transient or permanent marginal mandibular weakness, tongue numbness/taste disturbance from lingual-nerve injury, tongue weakness from hypoglossal injury, scar/contour change and xerostomia. Unexpected tongue deviation, lower-lip asymmetry or sensory loss deserves an anatomic diagnosis rather than being dismissed as routine swelling.

Rescue — an expanding neck or floor-of-mouth hematoma with dysphagia, voice change, tongue elevation, stridor or respiratory distress is an airway emergency. Prioritize oxygenation and airway control, release a threatening wound when necessary, and return urgently for definitive hemorrhage control. For uncontrolled intraoperative facial-artery/vein bleeding, pressure and deliberate vascular exposure are safer than blind deep clamping. If the lingual nerve versus duct anatomy cannot be distinguished, stop before ligation and improve exposure. If dense benign scarring makes preservation of the lingual or hypoglossal nerve impossible to assure, the bailout is reorientation, senior help, or aborting an elective benign excision—not knowingly converting a quality-of-life operation into a permanent cranial-nerve deficit.

Senior synthesis — ask five questions. INDICATION: is this refractory benign disease, a clearly benign tumor, or possible malignancy, and have gland-preserving options been considered? MAP: where are the marginal mandibular, lingual and hypoglossal nerves relative to the current plane? CONTROL: are the facial vessels and duct being divided under direct identification rather than traction or assumption? BIOLOGY: does tumor behavior require intact oncologic resection and a neck/adjuvant plan rather than a benign shell-out? BAILOUT: if bleeding, scar or uncertainty destroys the safe plane, can you restore exposure and control before continuing? The dangerous errors are removing glands unnecessarily for treatable obstruction, treating an unexplained mass like inflammation, injuring the marginal mandibular nerve in the superior flap, blindly clamping facial-vessel bleeding, dividing the duct before identifying the lingual nerve, traction injury to the hypoglossal nerve, violating a tumor capsule, and persisting through unsafe scar or postoperative airway compromise."""

TRAPS = [
    "Using total submandibular-gland excision as first-line therapy for every stone instead of considering sialendoscopy/transoral or combined gland-preserving treatment.",
    "Treating a discrete submandibular mass as chronic inflammation without an oncologic workup appropriate to a salivary neoplasm.",
    "Raising the superior flap or using energy close to the mandibular border without an explicit marginal-mandibular nerve protection strategy.",
    "Avulsing or blindly clamping facial vessels when bleeding obscures the field instead of compressing, exposing and obtaining controlled vascular ligation.",
    "Assuming a white cord is Wharton duct and dividing it before proving the lingual-nerve/duct relationship.",
    "Injuring the lingual nerve while separating the submandibular ganglion or deep gland because the nerve was never directly recognized.",
    "Using aggressive inferior/deep traction or thermal energy and injuring the hypoglossal nerve.",
    "Shelling out or violating a tumor capsule when malignancy has not been excluded.",
    "Applying a benign inflammatory dissection endpoint to proven gross malignant nerve invasion without an explicit oncologic resection/reconstruction plan.",
    "Persisting through obliterated inflammatory scar planes in an elective benign case rather than reorienting, obtaining senior help, or aborting when nerve safety cannot be assured.",
    "Teaching 2026 gland-preserving benign-tumor data as proof that total excision is obsolete despite only four comparative studies and strong selection limitations.",
    "Observing an expanding postoperative neck/floor-of-mouth hematoma despite tongue elevation, voice change or respiratory symptoms instead of treating it as an airway-and-hemorrhage emergency.",
]

COHORT = {QID: {
    "concept_id": CID, "canonical_topic": TOPIC, "prompt": PROMPT, "answer_text": ANSWER,
    "explanation": "Submandibular-gland excision is an indication-, anatomy-, and biology-driven operation: preserve glands when appropriate, protect marginal mandibular/lingual/hypoglossal nerves, control vessels and duct under direct vision, and change the plan for malignancy, scar, bleeding, or airway danger.",
    "board_pearl": "The dangerous deep step is not simply 'ligate the duct': identify the lingual nerve and Wharton duct relationship first, protect hypoglossal deep/inferiorly, and never let facial-vessel bleeding trigger blind clamping.",
    "depth_layers_v213": {"foundation":"Define indications and map gland/mylohyoid, facial vessels, marginal mandibular, lingual/hypoglossal nerves and Wharton duct.","application":"Perform a safe transcervical dissection with deliberate superior-flap, vessel, deep-lobe, ganglion and duct control while distinguishing inflammation from tumor.","senior_decision":"Choose gland preservation versus total excision, preserve oncologic principles for malignancy, and execute bleeding, scar and postoperative-airway bailouts."},
    "common_traps_v213": TRAPS,
    "deliberate_review_v213": "Selected from the exact successful v20.12 production backlog where the exact live Submandibular Gland Excision Concept Check remained a 12-word shallow candidate. It was prioritized over a higher lexical Four-Gland Parathyroid residual because a separate exact Four-Gland management check is already deeply protected, whereas this operation still lacked core nerve/vessel/duct danger-zone and rescue reasoning.",
    "source_refs_v213": SOURCE_REFS_V213,
}}

def apply_concept_check_task_alignment_v213(checks, deep_modules, v6_item_id):
    by = {str(q.get("id") or ""): q for q in checks or []}; repaired=[]; missing=[]; link_mismatch=[]
    for qid, patch in COHORT.items():
        q=by.get(qid)
        if q is None: missing.append(qid); continue
        module=_find_module(q,deep_modules,v6_item_id); topic=str(module.get("topic") or "") if module else ""
        cid=v6_item_id(q.get("domain"),topic) if module and q.get("domain") else None
        if module is None or topic!=patch["canonical_topic"] or cid!=patch["concept_id"] or q.get("concept_id")!=cid:
            link_mismatch.append(qid); continue
        for field in ("prompt","answer_text","explanation","board_pearl","depth_layers_v213","common_traps_v213","deliberate_review_v213","source_refs_v213"):
            q[field]=patch[field]
        q["choices"]=[]; q["answer"]=None; q["task_alignment_v213"]=True; repaired.append(qid)
    return {"repaired":repaired,"missing":missing,"link_mismatch":link_mismatch}
