ORIGINAL_V11_CURVEBALLS_V123 = {
'v11_oto_02':'CT shows lateral semicircular canal fistula and the patient has serviceable hearing. How does that change your operative counseling and hearing-preservation strategy?',
'v11_oto_03':'The patient also reports autophony and sound-induced vertigo. What alternative diagnosis should you reconsider before offering stapes surgery, and what testing distinguishes it?',
'v11_oto_04':'The Dix-Hallpike is negative but a supine roll test produces horizontal geotropic nystagmus. Which canal is involved and how does the repositioning maneuver change?',
'v11_oto_05':'The facial weakness is progressing despite antimicrobial therapy. What imaging, microbiologic, and source-control questions become urgent?',
'v11_oto_06':'MRI shows a 1.2-cm intracanalicular tumor with excellent hearing. What factors drive observation, radiation, versus hearing-preservation surgery?',
'v11_rhi_01':'The child develops an afferent pupillary defect and worsening vision after initial IV antibiotics. What does that do to your threshold for urgent drainage?',
'v11_rhi_02':'Frozen section is positive at the middle turbinate and disease approaches the orbit. How do you decide the extent and frequency of serial debridement?',
'v11_rhi_03':'Beta-2 transferrin confirms CSF, but routine CT does not localize the defect. What is your next localization strategy and what raises concern for elevated intracranial pressure?',
'v11_rhi_04':'The patient has recurrent polyps despite surgery and topical therapy. Where do aspirin desensitization and biologic therapy fit in the longitudinal plan?',
'v11_rhi_05':'Endoscopic control of the SPA fails and bleeding remains brisk. What alternative arterial sources and escalation options should you consider?',
'v11_rhi_06':'Pathology confirms inverted papilloma with focal carcinoma. How does that change margin strategy, staging workup, and surveillance?',
'v11_hn_01':'Imaging now shows thyroid cartilage invasion beyond the inner cortex. How does that change T classification and the organ-preservation versus surgical discussion?',
'v11_hn_02':'FNA is p16-positive SCC and PET/CT shows no primary. What operative mucosal evaluation would you perform next to identify the occult site?',
'v11_hn_03':'Depth of invasion is greater than expected on final pathology. How does that change the elective neck discussion and what other adverse features influence adjuvant therapy?',
'v11_hn_04':'Directed biopsies are negative. What role do palatine tonsillectomy and lingual tonsillectomy/TORS play in finding the primary and potentially reducing radiation fields?',
'v11_hn_05':'The parotid metastasis is accompanied by clinically suspicious level II nodes. How does that change the extent of neck management?',
'v11_hn_06':'The patient develops pathologic fracture and a draining fistula. What findings push you from conservative management toward segmental resection and vascularized reconstruction?',
'v11_end_01':'FNA returns Bethesda III. What additional clinical, ultrasound, molecular, and patient-preference factors determine surveillance versus diagnostic surgery?',
'v11_end_02':'Urine calcium is low and family history is suggestive. What mimic must you exclude before offering parathyroid surgery?',
'v11_end_03':'RET testing is positive and plasma metanephrines are elevated. Which disease must be treated first, and why does the order matter?',
'v11_end_04':'The stone is now 12 mm and hilar/intraparenchymal. How does location change the feasibility of sialendoscopy, combined approaches, or gland excision?',
'v11_end_05':'The patient has preoperative facial paralysis and imaging suggests skull-base extension. How does that affect facial-nerve planning and reconstruction counseling?',
'v11_end_06':"The nerve is visually intact but loses signal after traction near Berry's ligament. What immediate troubleshooting steps help distinguish equipment failure from true nerve injury?",
'v11_ped_01':'The same child returns with recurrent AOM and now has bilateral effusions at candidacy assessment. How does that change the tube discussion?',
'v11_ped_02':'The child is obese with severe OSA and persistent symptoms after adenotonsillectomy. What should the next evaluation focus on before choosing additional therapy?',
'v11_ped_03':'Bronchoscopy finds a peanut tightly lodged in the right mainstem with mucosal edema. What extraction and postoperative airway considerations matter?',
'v11_ped_04':'The infant begins losing weight and has cyanotic spells. What findings now make supraglottoplasty appropriate?',
'v11_ped_05':'Ultrasound shows no normal thyroid tissue in the neck. What must you establish before excising the presumed thyroglossal duct cyst?',
'v11_ped_06':'The stenosis is high-grade and the child remains tracheostomy-dependent. What factors determine endoscopic treatment versus laryngotracheal reconstruction?',
'v11_lar_01':'The paralysis is idiopathic with no surgical explanation. What imaging field should be evaluated along the vagus/RLN course, and how does expected recovery affect timing of augmentation?',
'v11_lar_02':'The patient is stable but cannot be extubated because the glottic airway is critically narrow. What temporary versus irreversible airway-widening options would you consider?',
'v11_lar_03':'The patient also has a rhythmic tremor at rest and across multiple speech tasks. What competing voice disorder should you consider before injecting botulinum toxin?',
'v11_lar_04':'The diverticulum is very small with poor neck extension. How do pouch size and exposure affect endoscopic versus open treatment selection?',
'v11_lar_05':'Under anesthesia the arytenoids are fixed on palpation. How does that confirm a mechanical cause and change the operative strategy versus bilateral RLN palsy?',
'v11_lar_06':'The lesion is a cyst with markedly reduced mucosal wave. Why does that change surgical technique and counseling compared with a soft polyp?',
'v11_fprs_01':'Drainage is delayed and the child now has fever and septal necrosis. What complications are you trying to prevent and what additional management is needed?',
'v11_fprs_02':"This is a child with minimal bruising but severe nausea, bradycardia, and restricted upgaze. Why is this a more urgent 'trapdoor' injury than many dramatic adult fractures?",
'v11_fprs_03':'The fracture is comminuted and occlusion cannot be reproduced because of missing teeth. What alternative reference points help restore mandibular form and function?',
'v11_fprs_04':'The medial canthal tendon is avulsed from a comminuted central fragment. How does that alter fixation and canthal reconstruction?',
'v11_fprs_05':'The modified Cottle improves breathing, but the septum is also deviated and the lateral wall collapses dynamically. How do you avoid attributing all obstruction to a single site?',
'v11_fprs_06':'The laceration also transects Stensen duct. How would you identify, repair, and stent the duct while planning facial-nerve repair?',
'v11_sleep_01':'The patient cannot tolerate CPAP despite optimization. What phenotype and anatomic information do you need before discussing oral appliance, HNS, or skeletal/soft-tissue surgery?',
'v11_sleep_02':'DISE instead shows anteroposterior palatal collapse without complete concentric collapse. What other candidacy factors still need to be checked before implantation?',
'v11_sleep_03':'Jaw thrust improves the tongue-base collapse but worsens epiglottic obstruction. How does that complicate a one-level surgical interpretation?',
'v11_sleep_04':'The patient has positional OSA but cannot reliably avoid supine sleep. What treatment options can combine positional therapy with other modalities?',
'v11_sleep_05':'Central events emerge only after CPAP eliminates obstruction. What syndrome does this suggest and why is upper-airway surgery not the primary answer?',
'v11_sleep_06':'The patient has severe TMJ dysfunction and poor dentition. How does that change oral-appliance candidacy and what alternatives should be considered?',
'v11_gen_01':'The floor of mouth is rapidly worsening and the patient cannot lie flat. What airway approach is safer than routine induction with direct laryngoscopy?',
'v11_gen_02':'The patient is toxic with neck swelling extending below the angle of the mandible. What alternative deep-neck diagnosis should you consider and when is CT needed?',
'v11_gen_03':'The patient becomes stridulous before transport to the OR. What bedside action should not be delayed while a definitive airway is organized?',
'v11_gen_04':'There is no urticaria and the patient is taking an ACE inhibitor. Why might standard histamine-directed therapy be insufficient, and what remains the overriding priority?',
'v11_gen_05':'The oropharynx looks nearly normal. Why does that not reassure you about esophageal or gastric injury, and what determines timing of endoscopic evaluation?',
'v11_gen_06':'Packing slows the bleeding but the patient remains hypotensive with ongoing transfusion needs. When should you escalate to operative arterial control or embolization?'
}
