"""Ninth-order Daily Curriculum answer-depth and decision-fit repairs.

This layer continues the exact-production review of cards whose questions are
clinically coherent but whose inherited answers are too short to resolve the
decision being asked. It also replaces the next group of parent-topic curveball
fallbacks with direct answers to the displayed counterfactual.
"""


DAILY_OVERRIDES = {
    ("Le Fort / Panfacial Trauma", "teach"): (
        "How would you teach panfacial-fracture reconstruction from initial threats and reliable reference points through framework sequencing, occlusion, orbital checks, and postoperative rescue?",
        "Stabilize airway, hemorrhage, brain and globe threats before definitive reconstruction, then document vision, occlusion, facial width, height and projection. Identify which unit remains reliable: the cranial bar may support top-down reconstruction, whereas a stable mandible and reproducible dentition can support bottom-up sequencing. Rebuild outer facial buttresses and orbital volume while repeatedly checking occlusion, intercanthal distance, globe position and facial symmetry. Comminuted mandible, unreliable teeth, skull-base instability or major soft-tissue loss changes the sequence. Postoperative visual decline, malocclusion, expanding hematoma or airway compromise requires immediate reassessment rather than attribution to swelling.",
    ),
    ("Branchial Cleft Anomalies", "manage"): (
        "Once a branchial cleft anomaly is identified, how do infection, tract anatomy, age, symptoms, and malignancy risk determine observation, drainage, or definitive excision?",
        "Control acute cellulitis or abscess first with antibiotics and drainage when indicated; avoid attempting complete tract excision through acutely inflamed planes unless the airway or uncontrolled sepsis requires it. After inflammation settles, offer definitive excision for recurrent infection, drainage, growth, discomfort or diagnostic uncertainty, using the predicted embryologic course to protect facial, hypoglossal, glossopharyngeal and vagal structures. Selected asymptomatic lesions may be observed after counseling. A new lateral cystic mass in an adult must not be assumed congenital: evaluate for metastatic oropharyngeal carcinoma before performing an open excision.",
    ),
    ("Pediatric Aspiration", "teach"): (
        "How would you teach pediatric aspiration from clinical suspicion and swallow physiology through feeding safety, cause-directed treatment, and escalation for persistent pulmonary injury?",
        "Begin with the consequence—coughing, desaturation, wet breathing, recurrent pneumonia, poor growth or silent aspiration in an at-risk child—then define when and why material enters the airway using clinical feeding assessment plus FEES or MBS as appropriate. Separate oral-motor, pharyngeal, sensory, structural, neurologic and esophageal contributors rather than labeling every event reflux. Use tested changes in flow, position, texture and pacing, therapy, and nutrition support to protect the lungs while treating the cause. Persistent silent aspiration, secretion failure, respiratory decline or inability to meet hydration and growth goals requires multidisciplinary aerodigestive escalation and sometimes temporary nonoral support or aspiration-prevention intervention.",
    ),
    ("Subglottic Hemangioma", "localize"): (
        "In an infant with recurrent croup-like symptoms, which age, sound, airway pattern, and vascular findings localize the problem to a subglottic hemangioma rather than routine croup or another stridor lesion?",
        "Subglottic hemangioma typically becomes symptomatic during early infancy as proliferative vascular tissue narrows the subglottis, producing progressive or recurrent biphasic stridor, barky cough, retractions and poor response or atypical recurrence after standard croup therapy. Flexible examination may suggest subglottic narrowing, while controlled airway endoscopy defines location and extent. Cutaneous beard-distribution or large segmental cervicofacial hemangioma strengthens suspicion but is not required. Abrupt onset suggests foreign body, prominent feeding-related symptoms suggest aspiration or cleft, and predominantly inspiratory dynamic collapse suggests supraglottic disease.",
    ),
    ("Subglottic Hemangioma", "teach"): (
        "How would you teach subglottic hemangioma from the recurrent-croup presentation through airway confirmation, propranolol safety, syndromic evaluation, and rescue?",
        "Recognize progressive or repeatedly atypical croup during infancy as a reason to inspect the airway. Define the lesion and degree of obstruction endoscopically when symptoms warrant it, and evaluate a large segmental facial hemangioma for PHACE-associated disease before selected systemic treatment. Propranolol is first-line for most symptomatic lesions after appropriate cardiovascular and feeding-risk assessment, with dosing and monitoring coordinated by an experienced team. Respiratory distress, marked narrowing or feeding compromise requires urgent airway planning; endoscopic, open or tracheostomy rescue is reserved for severe, refractory or immediately threatening disease.",
    ),
    ("Reoperative Thyroid Surgery", "workup"): (
        "Before reoperative thyroid or central-neck surgery, what must be established about indication, disease localization, vocal-fold function, calcium risk, prior operative planes, and possible need for nerve or aerodigestive sacrifice?",
        "Confirm the pathology and that reoperation offers meaningful benefit, then localize disease with high-quality ultrasound and compartment-appropriate cross-sectional or functional imaging rather than relying on exploration. Review the prior operative note, pathology, complications and radioactive-iodine history. Document bilateral vocal-fold motion, calcium and parathyroid status, and counsel about scar-distorted recurrent and external superior laryngeal nerves, hypoparathyroidism, tracheal or esophageal injury, chyle leak and bleeding. Invasive disease, preexisting contralateral paralysis, nonlocalized biochemical disease or morbidity disproportionate to expected control may change extent, require multidisciplinary planning or favor surveillance or nonsurgical therapy.",
    ),
    ("Reoperative Thyroid Surgery", "teach"): (
        "How would you teach reoperative thyroid surgery as an indication-and-localization problem followed by scar-aware exposure, nerve strategy, and postoperative airway or calcium rescue?",
        "Start by proving that a defined target justifies the added morbidity; excellent localization is safer than indiscriminate searching. Enter through the least scarred useful plane, gain proximal or distal landmarks before dissecting the target, and use nerve monitoring as an adjunct to visual identification rather than a substitute. Anticipate altered parathyroid blood supply, adherent trachea or esophagus, thoracic duct risk and the possibility that tumor cannot be separated safely from the nerve. A loss of signal, recognized aerodigestive injury, unexpected bilateral nerve risk, hematoma or symptomatic hypocalcemia activates a preplanned stop, repair or airway-and-calcium rescue pathway.",
    ),
    ("Open Rhinoplasty Fundamentals", "workup"): (
        "Before open rhinoplasty, how should functional examination, structural analysis, photographs, skin-envelope assessment, and patient goals be translated into a support-preserving operative plan?",
        "Clarify functional and aesthetic priorities and screen for unrealistic expectations or body-dysmorphic concern. Examine the septum, turbinates and internal and external valves at rest and with inspiration, then analyze dorsal lines, deviation, projection, rotation, tip shape, alar support, base relationships, chin balance, skin thickness and prior scars. Standardized photographs document asymmetry that surgery cannot erase. Inventory septal, auricular or costal cartilage needs and decide which maneuvers preserve or restore dorsal, caudal, lateral-wall and tip support. Active inflammation, cocaine injury, unstable obstruction or goals unsupported by the anatomy should delay or redirect surgery.",
    ),
    ("Systemic Therapy Foundations in Head & Neck Cancer", "teach"): (
        "How would you teach systemic therapy in head-and-neck cancer by intent, biomarker, treatment setting, organ function, toxicity, response, and failure rather than by memorizing drug names?",
        "First name the intent and setting: radiosensitization for definitive or postoperative cure, induction in selected circumstances, or treatment of recurrent or metastatic disease. Then integrate histology, primary site, HPV or EBV context, PD-L1 and other actionable molecular findings with performance status, prior treatment, renal function, hearing, neuropathy, marrow reserve and autoimmune or transplant history. Explain the distinct roles and toxicities of platinum therapy, cetuximab, immunotherapy and targeted agents. Monitor both tumor response and organ toxicity, and define progression, intolerance and goals-of-care transitions before treatment rather than continuing a regimen simply because it is familiar.",
    ),
    ("TEP and Alaryngeal Speech", "localize"): (
        "After total laryngectomy, which anatomy and airflow pathway produces electrolaryngeal, esophageal, and tracheoesophageal speech, and which failure site explains a poor TEP voice or leak?",
        "An electrolarynx supplies an external vibratory source shaped by the mouth. Esophageal speech releases insufflated air through the pharyngoesophageal segment, whereas TEP speech diverts pulmonary air through a one-way prosthesis into that segment while the permanent stoma remains the only respiratory airway. Poor voice may reflect inadequate pulmonary seal, prosthesis obstruction, tract position, pharyngoesophageal spasm or stenosis, or impaired oral articulation. Leakage through the prosthesis suggests valve failure or debris; leakage around it suggests tract enlargement, sizing or tissue problems. Airway distress is managed through the stoma, never through the mouth or nose.",
    ),
    ("TEP and Alaryngeal Speech", "manage"): (
        "How should alaryngeal communication be selected and followed, and what voice, leakage, tract, or airway problem requires urgent escalation?",
        "Begin preoperative counseling with electrolarynx access and discuss esophageal speech and primary versus secondary TEP according to reconstruction, radiation, dexterity, cognition, pulmonary function, support and patient preference. After puncture, fit and resize the prosthesis, teach cleaning and stoma/HME care, and reassess pharyngoesophageal function when voice is strained or absent. Manage leakage through the device with cleaning or replacement and leakage around it with cause-directed tract care. A missing prosthesis raises aspiration and tract-closure risk; respiratory distress, significant bleeding, cellulitis, mediastinal concern or inability to maintain the tract requires prompt specialist evaluation.",
    ),
    ("Arytenoid Adduction / Reinnervation", "manage"): (
        "Where do arytenoid adduction and laryngeal reinnervation fit among voice therapy, injection, and thyroplasty for unilateral vocal-fold paralysis, and what anatomy chooses among them?",
        "Define symptoms, aspiration, expected neural recovery, glottic gap, posterior gap, vertical level and vocal demand. Voice therapy and temporary injection are useful early or while recovery remains plausible; type I thyroplasty provides immediate durable medialization for a stable deficit. Arytenoid adduction is particularly useful for a large posterior gap or vertical height mismatch, often combined with thyroplasty. Reinnervation restores tone and bulk over months without immediate motion and is attractive in younger patients with a suitable donor and viable muscle. Severe scar, joint fixation, poor pulmonary reserve or a different dominant vibratory lesion may redirect the plan.",
    ),
    ("Microlaryngoscopy", "manage"): (
        "When is suspension microlaryngoscopy appropriate, what office or nonsurgical alternatives should be considered, and what exposure or airway finding should make the surgeon change course?",
        "Use microlaryngoscopy when magnified palpation, biopsy or precise treatment of a laryngeal lesion will change care and cannot be accomplished adequately in the office. Observation, voice therapy, office biopsy or laser, flexible endoscopic procedures and imaging may be better for selected lesions or patients. Match ventilation and laryngoscope strategy to the airway and target, protect teeth and mucosa, and preserve the vocal-fold epithelium and superficial lamina propria during phonomicrosurgery. Unsafe cervical positioning, unstable dentition, inadequate line of sight or inability to ventilate is a reason to change instruments, use a different approach, stage the procedure or stop—not to add suspension force.",
    ),
    ("Muscle Tension Dysphonia", "manage"): (
        "Once muscle-tension dysphonia is suspected, how should treatment address both the maladaptive phonatory pattern and any lesion, paresis, reflux, respiratory, or workload driver?",
        "Confirm the diagnosis with laryngoscopy or stroboscopy and perceptual examination, looking specifically for glottic insufficiency, mucosal lesion, tremor, dystonia, inflammation and respiratory or neurologic disease that could provoke compensation. Voice therapy is the primary treatment for the tension pattern and should include efficient breath-voice coordination, unloading and task-specific practice. Modify harmful vocal load and treat a demonstrated contributor rather than empirically assigning reflux. Failure to improve should prompt review of the diagnosis, adherence and occupational demands; a hidden lesion or paresis may require procedural treatment while therapy continues.",
    ),
    ("Muscle Tension Dysphonia", "teach"): (
        "How would you teach muscle-tension dysphonia from perceptual pattern and stroboscopy through primary-versus-compensatory diagnosis, therapy, and reconsideration when treatment fails?",
        "Teach supraglottic squeeze as a finding, not a diagnosis. Listen across connected speech and demanding tasks, then examine true-fold vibration and closure before deciding whether excess tension is primary or compensation for a lesion, atrophy, paresis, tremor, dystonia or respiratory limitation. A stimulability trial with a voice-specialized clinician can support the behavioral component. Treat the underlying driver and retrain efficient phonation, monitoring function rather than appearance alone. Persistent pain, progressive dysphonia, impaired motion, weight loss, hemoptysis or failure of expert therapy requires renewed structural and neurologic evaluation.",
    ),
    ("Stroboscopy Interpretation", "manage"): (
        "How should closure, wave, amplitude, symmetry, periodicity, motion, and lesion findings on stroboscopy change observation, therapy, further testing, or surgery?",
        "Interpret the entire examination with the voice complaint. Preserved wave and a small symmetric phonotraumatic pattern may support behavioral treatment, while focal absent wave, irregular mass, suspicious vascularity or progressive unilateral disease can require microlaryngoscopic evaluation and tissue diagnosis. Bowing with insufficiency may lead to therapy or augmentation; asymmetric motion may prompt paresis workup; severe aperiodicity makes the strobe reconstruction unreliable and may require high-speed imaging or real-time assessment. Do not operate on a closure pattern alone: treatment follows the cause, functional burden and expected effect on vibration.",
    ),
    ("Vocal Fold Nodules", "manage"): (
        "How should classic vocal-fold nodules be treated, and what atypical feature or failed response should reopen the diagnosis or justify procedural intervention?",
        "Confirm bilateral symmetric mid-membranous lesions with compatible phonotraumatic history and preserved or predictably altered vibration. Voice therapy, vocal-load modification, hydration and treatment of specific contributing inflammation or glottic insufficiency are first-line; occupational accommodations may be essential. Reassess symptoms and stroboscopy rather than promising that every visible lesion must disappear. Unilateral stiffness, irregular vascularity, progressive growth, impaired motion or an inconsistent history should reopen the differential for cyst, polyp, scar, dysplasia or another lesion. Surgery is uncommon but can be considered for persistent, function-limiting disease after optimized expert therapy and diagnostic certainty.",
    ),
    ("Vocal Fold Nodules", "teach"): (
        "How would you teach vocal-fold nodules from collision mechanics and the hourglass pattern through behavioral treatment, reassessment, and the uncommon surgical indication?",
        "Repeated high-impact contact at the mid-membranous folds produces paired phonotraumatic lesions and often hourglass closure. The visible nodules are therefore part of a load-and-technique problem rather than isolated tissue to remove. Confirm the symmetric pattern with stroboscopy, identify workload and compensatory behavior, and use voice therapy to improve efficiency while adjusting exposure. Reassess both function and morphology. Atypical asymmetry or stiffness demands a different diagnosis; precise surgery is reserved for persistent disabling lesions after adequate therapy because excision without changing the causal mechanics invites recurrence or scar.",
    ),
    ("Vocal Tremor", "localize"): (
        "How do task pattern and distribution across palate, pharynx, tongue base, vertical larynx, and true folds distinguish vocal tremor from spasmodic dysphonia and compensatory tension?",
        "Vocal tremor produces rhythmic oscillation that may appear across multiple upper-airway subsites during sustained phonation and sometimes quiet breathing. Examine vowels, connected speech, voiceless and voiced tasks, pitch change and respiration while noting horizontal glottic, vertical laryngeal and supraglottic components. Spasmodic dysphonia causes irregular task-specific breaks rather than a regular oscillation, and muscle tension is often variable and compensatory. Tremor involving palate, pharynx or limbs suggests a broader neurologic syndrome; isolated irregular fold motion or unilateral weakness should redirect evaluation toward another motor disorder or paresis.",
    ),
    ("Vocal Tremor", "workup"): (
        "What perceptual, laryngoscopic, task-specific, neurologic, and functional assessment confirms vocal tremor and identifies the muscle groups most likely to benefit from treatment?",
        "Characterize regularity, frequency, severity and disability during sustained vowels, reading, conversation and the patient's most demanding task. Flexible laryngoscopy should survey palate, pharynx, tongue base, supraglottis, vertical laryngeal movement and true folds during phonation and breathing. Look for limb, head or palatal tremor, dystonia, parkinsonism and medication effects; obtain neurologic input when disease is generalized, progressive or atypical. Acoustic measures can document change but do not replace the examination. Distribution matters because horizontal glottic, vertical and pharyngeal tremor respond differently to botulinum toxin and systemic therapy.",
    ),
    ("Vocal Tremor", "manage"): (
        "How should vocal tremor be treated by distribution and functional burden, and what response or adverse effect should trigger adjustment or another strategy?",
        "Begin with education, communication strategies and selected voice therapy for breath support and compensation, recognizing that therapy does not eliminate the oscillatory generator. Coordinate systemic essential-tremor treatment with neurology when tremor extends beyond the larynx. Site-directed botulinum toxin can reduce disabling horizontal glottic or selected vertical tremor, using conservative dosing and staged adjustment. Counsel about transient breathiness, weak cough and dysphagia, especially with bilateral or strap-muscle treatment. Poor response should prompt confirmation of injection target, tremor distribution and competing spasmodic dysphonia or tension rather than automatic dose escalation.",
    ),
    ("Laryngotracheal Cleft", "teach"): (
        "How would you teach laryngotracheal cleft from aspiration phenotype and instrumental swallow findings through endoscopic classification, conservative care, repair, and postoperative reassessment?",
        "Suspect a cleft in an infant or child with choking, cyanosis, recurrent pneumonia, wet breathing or persistent aspiration, while remembering that symptoms and swallow studies demonstrate the consequence but not the complete anatomy. Stabilize breathing and nutrition, optimize flow, position, texture and comorbid airway or reflux contributors, then use rigid endoscopy with interarytenoid palpation to define depth and associated lesions. Limited defects may improve with conservative care or selected injection augmentation; persistent clinically important aspiration or deeper clefts require endoscopic or open repair. Postoperative swallow reassessment guides safe diet advancement because anatomic closure does not guarantee immediate physiologic recovery.",
    ),
    ("Laryngotracheal Reconstruction", "workup"): (
        "Before pediatric laryngotracheal reconstruction, what airway map, pulmonary and swallowing assessment, tracheostomy information, comorbidity review, and family readiness determine candidacy or staging?",
        "Define stenosis grade, length, subsites, framework quality, vocal-fold motion, posterior glottis, tracheomalacia and distal airway with controlled endoscopy; review prior reconstructions and tracheostomy position. Assess pulmonary reserve, secretion burden, aspiration and swallowing, reflux when clinically relevant, nutrition, infection, neurologic status and need for other airway procedures. Determine whether cricoid split, grafting, resection, single-stage or double-stage reconstruction matches the anatomy and physiology. Active lower-airway disease, uncontrolled aspiration, poor wound conditions, severe multilevel collapse or inadequate caregiver capacity may require optimization, a staged plan or continued tracheostomy rather than immediate decannulation-focused surgery.",
    ),
    ("Laryngotracheal Reconstruction", "teach"): (
        "How would you teach laryngotracheal reconstruction from stenosis mapping and procedure selection through graft stability, stenting, extubation or decannulation, and failure analysis?",
        "Start with a complete three-dimensional airway diagnosis: grade alone does not describe length, posterior involvement, framework collapse, vocal-fold function or distal disease. Match expansion grafting, cricotracheal resection or another approach and single- versus double-stage timing to the child’s airway, pulmonary and swallowing physiology. During reconstruction create stable vascularized framework expansion without mucosal trauma, size graft and stent deliberately, and protect the recurrent nerves. Postoperative success requires safe ventilation, secretion control, healing and functional swallowing. Granulation, graft prolapse, restenosis, collapse, aspiration or failed decannulation should be localized before repeating the same operation.",
    ),
    ("Lymphatic Malformation", "teach"): (
        "How would you teach lymphatic malformation from macrocystic or microcystic phenotype and airway extent through observation, sclerotherapy, surgery, systemic therapy, and acute rescue?",
        "Describe the lesion by cyst phenotype, symptoms and trans-spatial extent rather than by size alone. Ultrasound helps with superficial cysts and procedures, while MRI maps tongue, floor-of-mouth, pharyngeal, orbital or mediastinal involvement. Observe stable asymptomatic disease; macrocystic compartments often respond well to image-guided sclerotherapy, whereas diffuse microcystic or mucosal disease may need staged multimodal treatment because complete excision risks nerves and function. Surgery addresses accessible symptomatic residual disease, and selected complex PIK3CA-related disease may merit targeted systemic therapy. Infection, hemorrhage or sudden swelling can rapidly threaten the airway and requires immediate reassessment.",
    ),
    ("Nonobstructive Pediatric Sleep Disorders", "teach"): (
        "How would you teach a child with poor sleep or daytime dysfunction to separate insomnia, circadian, movement, parasomnia, hypersomnolence, and medical causes from obstructive sleep apnea?",
        "Begin with timing, opportunity and pattern: bedtime resistance or conditioned wakefulness suggests insomnia; a stable but shifted schedule suggests circadian misalignment; uncomfortable legs or rhythmic movements suggest movement disorder; stereotyped partial arousals suggest parasomnia; persistent sleepiness despite adequate sleep raises central or medical causes. Ask separately about snoring, witnessed obstruction, gasping and risk anatomy. Use sleep logs or actigraphy for timing, targeted iron or medical evaluation when indicated, and PSG when respiratory, movement or unusual-event characterization will change care. Adenotonsillectomy treats demonstrated obstruction, not every child whose sleep is poor.",
    ),
    ("Frontal Sinusotomy / Draf Procedures", "teach"): (
        "How would you teach frontal sinusotomy from disease indication and CT pathway reconstruction through Draf selection, safe drilling, postoperative patency, and failure rescue?",
        "Confirm clinically important frontal disease and reconstruct each drainage pathway on multiplanar CT before choosing extent. A Draf IIa opens the frontal recess between lamina and middle turbinate; IIb extends medially toward the septum; III creates a common bilateral neo-ostium by removing superior septum and frontal beak. Preserve orbit and skull base, control the anterior ethmoid artery risk and avoid blind drilling. The narrowest durable opening that treats the pathology is preferable to escalation for its own sake. Postoperative irrigation, topical access, surveillance and selective debridement limit stenosis; recurrent narrowing requires analysis of retained cells, osteitis, scarring and inflammatory control.",
    ),
    ("Inferior Turbinate Hypertrophy", "teach"): (
        "How would you teach inferior-turbinate hypertrophy from reversible mucosal congestion and fixed enlargement through medical treatment, tissue-preserving reduction, and recognition of overresection?",
        "First prove that the turbinate contributes to the symptomatic bottleneck by examining before and after decongestion while assessing septum and nasal valves. Reversible mucosal disease should receive cause-directed rhinitis therapy; persistent fixed soft-tissue or bony enlargement despite adequate treatment may benefit from submucosal reduction, outfracture or another tissue-preserving technique. The goal is improved airflow with intact mucosal humidification and sensation, not maximal removal. Persistent obstruction suggests another missed site, whereas paradoxical obstruction, excessive dryness, crusting and widened cavities after aggressive resection raise concern for dysfunctional airflow or empty-nose physiology.",
    ),
    ("MEN2 / RET", "workup"): (
        "After MEN2 or a pathogenic RET variant is suspected, which genetic, biochemical, imaging, and family evaluation confirms the syndrome and safely sequences treatment?",
        "Confirm the familial variant or obtain germline RET testing with genetic counseling when medullary thyroid carcinoma, pheochromocytoma, hyperparathyroidism or family history raises concern. Measure calcitonin and CEA and assess the thyroid and neck according to age and disease status. Screen for pheochromocytoma with metanephrine testing before thyroid or parathyroid intervention and localize a positive result appropriately; assess calcium and PTH for hyperparathyroidism. Genotype defines risk and surveillance timing, while biomarkers and imaging define established disease. Offer targeted testing to at-risk relatives, including children when the result changes the timing of surveillance or prophylactic thyroidectomy.",
    ),
    ("Deep Neck Abscess Drainage", "manage"): (
        "How do airway status, involved space, abscess maturity, source, vascular risk, and response to antibiotics determine observation, aspiration, transoral, or transcervical drainage?",
        "Secure a threatened airway before sending an unstable patient for imaging. In a stable patient, contrast CT maps cellulitis versus drainable collection, odontogenic or tonsillar source, mediastinal extension, carotid or jugular complications and the safest corridor. Small phlegmonous disease in a reliable patient may respond to IV antibiotics and close serial examination; a mature collection, sepsis, airway symptoms, vascular complication, mediastinal spread or failure to improve requires source control. Use transoral drainage for selected medially accessible collections and transcervical or combined drainage for lateral, multiloculated, vascular-adjacent or descending disease, obtaining cultures and addressing the dental or other source.",
    ),
    ("Esophageal Foreign Body", "teach"): (
        "How would you teach esophageal foreign-body management from airway and object identification through timing of removal, mucosal assessment, and perforation or battery rescue?",
        "First assess airway, secretion handling and hemodynamic stability, then identify object, location and time using history and appropriate two-view imaging without delaying treatment for a clear emergency. An esophageal button battery requires immediate removal; complete obstruction, sharp or long objects and significant respiratory symptoms are also emergent, while other retained esophageal objects require urgent removal. Protect the airway, inspect the mucosa and avoid blind advancement. After extraction, severe pain, fever, crepitus, bleeding, instability, mediastinal air or deep battery injury triggers NPO status, antibiotics, cross-sectional or vascular imaging and immediate multidisciplinary complication management.",
    ),
    ("Ludwig Angina", "teach"): (
        "How would you teach Ludwig angina from floor-of-mouth physiology and airway warning signs through controlled airway management, antibiotics, source control, and descending-infection rescue?",
        "Recognize rapidly progressive bilateral submandibular and sublingual cellulitis by woody induration, tongue elevation, dysphagia, drooling, muffled voice and increasing work of breathing, often from an odontogenic source. Keep the patient upright and avoid agitation or supine imaging when the airway is unstable; assemble awake or controlled advanced airway and surgical-airway backup before decompensation. Begin broad aerobic and anaerobic antibiotics and obtain contrast imaging only when stable enough. Drain a collection or progressive infection and treat the dental source. Chest pain, sepsis, crepitus or mediastinal extension requires combined cervical and thoracic source-control planning.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v142_lar_04": "Stroboscopy constructs an apparent slow-motion cycle from successive flashes, so it assumes sufficiently periodic vibration. Severe aperiodicity prevents reliable synchronization and can create false impressions of wave, symmetry or immobility. Use real-time flexible examination for gross motion and high-speed videoendoscopy or videokymography when true cycle-to-cycle vibration will change diagnosis or treatment. A technologically detailed image is not more valid if the periodicity assumption has failed.",
    "v144_oto_12": "Acute vertigo with new hearing loss is not typical isolated vestibular neuritis. Consider viral or inflammatory labyrinthitis, bacterial spread from otitis media, mastoiditis or meningitis, cholesteatoma with labyrinthine fistula, sudden sensorineural hearing loss with vestibular symptoms, Ménière disease and ototoxicity. Central and vascular causes include AICA-territory ischemia and other posterior-circulation lesions, particularly with neurologic signs or vascular risk. Examine the ear, obtain urgent audiometry when feasible and choose MRI or infection-directed imaging without delaying time-sensitive treatment.",
    "v256_lar_esoph_fnd": "Difficulty with solids and liquids from symptom onset suggests disordered propulsion or lower-esophageal-sphincter relaxation, such as achalasia or another motility disorder, rather than a simple fixed mechanical narrowing that usually begins with solids. Clarify initiation difficulty, regurgitation, weight loss and aspiration. Endoscopy and esophagram assess mucosal and structural disease, while high-resolution manometry defines motility and outflow obstruction. Oropharyngeal coughing or inability to initiate the swallow still redirects evaluation toward FEES or MBS.",
    "v260_fpt_obstruction_fnd": "Static internal-valve narrowing is a fixed small angle or middle-vault constriction between septum and upper lateral cartilage that is present without inspiratory collapse. Dynamic lateral-wall collapse is inward movement during inspiration because the sidewall lacks support; it may affect internal or external valve zones. Observe quiet and forced inspiration and use targeted support at the suspected segment. A broad Cottle pull can improve almost any narrow nose and therefore does not localize the abnormality by itself.",
    "v139_ped_10": "Atresiaplasty can alter or scar the tissue envelope needed for auricular reconstruction and its incision or vascular territory may conflict with a future autologous framework. Coordinate the sequence before either operation: autologous rib reconstruction is commonly planned before or in a deliberate relationship to canal surgery, whereas alloplastic or prosthetic strategies have different requirements. The child still needs early hearing access; delaying CT or atresia surgery planning does not mean delaying amplification or communication support.",
    "v139_ped_19": "Treat acute infection first with appropriate antibiotics and drainage if an abscess is present, while protecting the airway and confirming the diagnosis. Inflamed planes increase rupture, bleeding, incomplete tract removal and wound-complication risk, so definitive Sistrunk surgery is generally delayed until infection has resolved. Recurrent infections strengthen the indication for definitive excision but do not justify forcing tract dissection through uncontrolled inflammation. A persistent solid component or suspicious node should prompt carcinoma-directed evaluation rather than routine timing alone.",
    "v143_tps_02": "A high-risk driver associated with malignancy raises the estimated cancer probability and may support definitive surgery and a broader initial extent when integrated with ultrasound, cytology, patient factors and the specific mutation. A benign-pattern classifier lowers but does not eliminate risk and is most useful when it changes a genuine diagnostic-lobectomy decision. Explain test performance in that nodule's pretest-risk setting. Molecular data should not override highly suspicious imaging, compressive progression, metastatic nodes or a result whose uncertainty would not alter management.",
    "v143_tps_04": "Preoperative vocal-fold paralysis suggests invasive local disease and increases concern that the recurrent laryngeal nerve is already involved. Document bilateral motion, map tumor-tracheoesophageal relationships and counsel that en-bloc oncologic resection may require sacrificing a nonfunctional invaded nerve, while a functioning nerve should be preserved when a sound plane exists and oncologic control is not compromised. Contralateral dysfunction radically increases airway risk and may change extent, staging, reconstruction and postoperative airway planning.",
    "v145_lar_10": "Support the diagnosis by reproducing the occupational complaint during perceptual examination and stroboscopy. Look for task-specific mucosal-wave loss, subtle lesion, glottic gap, asymmetric motion or fatigability, tremor, dystonic breaks, respiratory limitation and compensatory supraglottic tension. Laryngeal EMG is selective when paresis, neuropathy or dystonia remains uncertain; it is not routine for every professional voice complaint. Normal conversational phonation does not exclude loss of range, endurance, dynamic control or reliable high-demand function.",
    "v146_ped_08": "Atresiaplasty is less favorable when CT shows poorly developed middle-ear space, absent or severely malformed ossicles, unfavorable facial-nerve course, oval-window or stapes abnormality, significant inner-ear dysplasia, poor mastoid pneumatization or anatomy that prevents a safe canal and tympanic reconstruction. Use a validated candidacy framework such as Jahrsdoerfer scoring as one input, not a guarantee. The scan should be obtained when the child is near an actual surgical decision because radiation and anatomy alone do not determine family goals or hearing strategy.",
    "v146_ped_18": "During acute infection, prioritize airway, antibiotics, analgesia and drainage of a true abscess; do not attempt routine definitive tract excision through inflamed tissue. Ultrasound can confirm a cystic lesion and evaluate the thyroid when the diagnosis is uncertain. Plan Sistrunk excision after inflammation resolves because edema and scar obscure the tract and raise incomplete-removal and wound risks. Recurrent infection, rapid growth, a solid component or suspicious nodes should broaden evaluation and may accelerate specialist planning.",
    "v170_oto_csf_app": "A spontaneous temporal-bone leak, multiple tegmen defects, contralateral thinning, empty or partially empty sella, optic-nerve-sheath enlargement, arachnoid pits or other skull-base defects should raise concern for elevated intracranial-pressure physiology, especially with obesity, pulsatile tinnitus, headache or papilledema. Absence of classic symptoms does not exclude it because an active leak may decompress pressure. Coordinate ophthalmologic and neurologic evaluation and address pressure drivers after closure to reduce recurrence rather than treating the bony hole as an isolated event.",
    "v222_hn_lym_fnd": "Image-guided core biopsy can be adequate when it yields enough viable tissue for morphology, immunohistochemistry, flow cytometry and molecular studies and when the suspected subtype is routinely classifiable from core material. Excisional biopsy is preferred when prior FNA or core is nondiagnostic, architecture is essential, transformation is suspected, or an accessible node can be removed safely without delaying care. Coordinate with pathology before sampling; steroid exposure and unplanned open biopsy can destroy diagnostic information or complicate definitive treatment.",
    "v222_hn_lym_snr": "Anesthesia is hazardous when lymphoma creates stridor, orthopnea, positional dyspnea, inability to lie flat, tracheal compression, bulky tongue-base or pharyngeal disease, mediastinal mass effect, great-vessel compression, pericardial effusion or superior vena cava physiology. Review cross-sectional imaging and symptoms before sedation. Loss of spontaneous tone can convert partial compression to complete obstruction or cardiovascular collapse, so obtain tissue by the least destabilizing route under a multidisciplinary airway plan rather than defaulting to general anesthesia.",
    "v228_hn_tlm_fnd": "Difficult transoral laser exposure is predicted by limited mouth opening, prominent or fragile teeth, retrognathia, macroglossia, mandibular tori, short thyromental distance, obesity, restricted cervical extension, prior radiation or surgery and an anterior, subglottic or deeply infiltrative tumor. Perform preoperative endoscopic and airway assessment and be willing to abandon TLM when the entire oncologic target and margins cannot be visualized. A technically reachable fragment is not the same as an adequately exposed cancer operation.",
    "v235_tps_indet_snr": "A benign molecular classifier reduces risk but does not erase a highly suspicious ultrasound phenotype. Reconfirm imaging quality, cytology category, sample identity and whether the test is validated in that setting; consider repeat expert ultrasound or sampling. Marked growth, extrathyroidal extension, suspicious nodes, compressive symptoms or a high-risk clinical history can justify diagnostic surgery despite a reassuring result. Counsel using post-test probability rather than calling the nodule benign, and choose surveillance only when the residual risk and follow-up plan are acceptable.",
    "v241_ped_tgdc_fnd": "If ultrasound shows no thyroid in the normal pretracheal location, do not assume the midline cyst is expendable. It may represent the patient's only functioning ectopic thyroid tissue. Confirm thyroid anatomy and function with specialist-directed imaging or laboratory assessment before excision. Removing the sole thyroid source creates permanent hypothyroidism, whereas a typical thyroglossal duct cyst with clearly orthotopic thyroid can proceed through the usual infection-control and Sistrunk pathway.",
    "v241_ped_tgdc_snr": "A solid mural nodule, calcification, rapid growth, fixation or suspicious cervical nodes should trigger dedicated thyroid and neck ultrasound, needle sampling of the solid component or node when appropriate, and evaluation of the orthotopic thyroid. The operation still generally includes a complete Sistrunk procedure, but confirmed carcinoma may add thyroidectomy or neck treatment according to tumor size, invasion, nodal disease, thyroid findings and patient risk. Avoid treating every incidental microscopic focus with automatic total thyroidectomy.",
    "v243_ped_tm_snr": "Tracheopexy can correct a dominant focal tracheal collapse but will not resolve extensive distal bronchomalacia, intrinsic small-airway disease or compression driven by complex cardiovascular anatomy. Dynamic bronchoscopy and cardiovascular imaging must define every level and mechanism. The plan may require bronchopexy, aortopexy, vascular reconstruction, positive-pressure support or staged combined surgery. Counsel that improving the central trachea may reduce events without eliminating wheeze, secretion retention or ventilatory dependence from distal disease.",
    "v245_ped_micro_app": "Temporal-bone CT is usually deferred until the child is old enough and the family is actively considering atresiaplasty or another anatomy-dependent operation. Earlier imaging adds radiation while middle-ear anatomy is not yet being used for a decision and may become outdated relative to the operative plan. Obtain it sooner only for a separate indication such as cholesteatoma concern or atypical complications. Early diagnostic audiology, amplification and communication support proceed without waiting for CT.",
    "v245_ped_micro_fnd": "Look for facial asymmetry, mandibular hypoplasia, epibulbar dermoid, facial tags, vertebral or rib anomalies, cleft palate, renal or cardiac abnormalities and facial-nerve dysfunction suggesting craniofacial microsomia, Goldenhar spectrum, Treacher Collins, branchio-oto-renal or another syndrome. Bilateral microtia, severe canal atresia, developmental delay or family history also lowers the threshold for genetics and organ-specific evaluation. The workup should be phenotype-directed rather than a uniform battery for every isolated ear anomaly.",
    "v247_ped_cleft_snr": "A secondary pharyngeal flap or sphincter procedure can worsen obstruction, so severe baseline OSA requires multidisciplinary review of airway anatomy, PSG and the exact velopharyngeal gap before narrowing the port. Consider whether speech surgery can be modified, staged or replaced by a less obstructive option, and optimize tonsillar, nasal or other obstruction first when appropriate. Postoperative monitored care and repeat PSG may be needed. Improving resonance is not a success if the child develops unsafe sleep-disordered breathing.",
    "v247_ped_microtia_fnd": "Autologous rib-cartilage reconstruction needs an intact, well-vascularized soft-tissue envelope and carefully positioned framework; prior canal surgery can scar or compromise that field. Alloplastic frameworks and prosthetic reconstruction use different incisions and tissue requirements, so their relationship to atresiaplasty differs. Decide the auricular method first and coordinate both surgeons before operating. Regardless of sequence, provide early hearing access through nonsurgical bone conduction or another appropriate option during language development.",
    "v251_lar_strobe_app": "Bilateral symmetric mid-membranous lesions with hourglass closure and compatible phonotrauma strongly favor vocal-fold nodules. Confirm that wave reduction is symmetric and that neither side contains a deeper focal stiff lesion suggesting cyst, scar or another mass. Initial treatment is voice therapy and load modification rather than excision. Persistent asymmetry, focal absent wave, irregular vascularity or failure to improve should reopen the diagnosis instead of labeling every paired lesion a nodule.",
    "v253_lar_fees_app": "A feeding tube removes food and liquid from the oral route but does not stop aspiration of saliva, colonized secretions or refluxate. Severe silent secretion aspiration therefore signals impaired sensation, clearance and airway protection that may continue despite NPO status. Pair nutrition support with secretion management, oral hygiene, pulmonary surveillance, positioning and treatment of the neurologic or structural cause. Recurrent pneumonia or inability to protect the airway may require more definitive aspiration-prevention discussion rather than simply changing tube type.",
    "v253_lar_fees_fnd": "During the pharyngeal swallow, apposition of the tongue base and pharyngeal walls around the endoscope briefly obscures the image—the white-out. FEES therefore infers events during that instant from material position immediately before and after it; it does not directly show laryngeal vestibule closure or upper-esophageal opening during the obscured frame. This limitation is why timing questions or oral and esophageal phase problems may require MBS or another complementary study.",
    "v260_fpt_tip_snr": "Thick skin and soft tissue can obscure subtle cartilage definition, prolong edema and require stronger but still smooth structural support; final tip refinement may take well beyond a year. Thin skin reveals contour and graft edges more readily, so small asymmetries, sharp graft transitions and suture irregularities demand meticulous camouflage. Counsel both groups differently: thick skin limits how sharply the framework will show, while thin skin makes overengineering visible. Neither phenotype is corrected safely by indiscriminate cartilage resection.",
    "v266_sleep_positional_snr": "Use in-laboratory PSG when the decision depends on sleep stage, arousals, reliable body position, central versus obstructive classification, hypoventilation or gas exchange—especially with neuromuscular disease, significant cardiopulmonary disease, opioid use or suspected obesity hypoventilation. Home testing generally cannot characterize CO2 and may underestimate disease when sleep time is unknown. A positional AHI from limited recording is insufficient if the apparent residual events could instead be REM-predominant, central or hypoventilatory.",
    "v271_gen_epi_snr": "Embolization is particularly hazardous when angiography shows internal-carotid or ophthalmic anastomoses, an ethmoidal source, dangerous collateral flow, carotid stenosis or dissection, pseudoaneurysm, prior vascular graft or an external-carotid branch supplying retina or brain. Prior skull-base surgery, radiation and tumor can distort pathways. Review neurologic and visual risk with interventional specialists; particles or liquid agent entering an unrecognized collateral can cause blindness or stroke, so some anatomy favors surgical control or a different endovascular strategy.",
}


def apply_daily_curriculum_quality_v377(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if not override:
            continue
        prompt, answer = override
        item["daily_prompt"] = prompt
        item["prompt"] = prompt
        item["answer"] = answer
        changed += 1
    return changed


def install_daily_curriculum_quality_v377(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v377():
        items = original_get_items()
        apply_daily_curriculum_quality_v377(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v377

    def adaptive_question_v377(item):
        return item.get("daily_prompt") or item.get("prompt") or ""

    app_module._adaptive_question = adaptive_question_v377

    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1

    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119

    return {
        "daily_pairs_repaired": len(DAILY_OVERRIDES),
        "curveball_answers_repaired": repaired,
    }
