"""Eleventh-order Daily Curriculum pathway and curveball repairs."""


DAILY_OVERRIDES = {
    ("Carotid Body Paraganglioma", "teach"): (
        "How would you teach carotid body paraganglioma from vascular diagnosis through genetic and biochemical evaluation, treatment selection, and cranial-nerve counseling?",
        "Recognize a slowly growing hypervascular carotid-bifurcation mass that splays the internal and external carotids, then avoid routine biopsy because imaging is usually diagnostic and sampling can hemorrhage. Document vagal, hypoglossal and sympathetic function, define carotid encasement and skull-base extent, and assess catecholamine secretion and hereditary risk when appropriate. Observation may fit an indolent asymptomatic tumor; radiation can provide growth control when surgery is disproportionately morbid; resection offers definitive control but carries increasing vascular and lower-cranial-nerve risk with larger Shamblin anatomy. Embolization is selective, not automatic.",
    ),
    ("Esophageal Disease for the Otolaryngologist", "teach"): (
        "How would you teach an otolaryngologist to localize dysphagia before choosing FEES, MBS, esophagram, endoscopy, manometry, or urgent operative evaluation?",
        "Start with timing: difficulty initiating a swallow, coughing, nasal regurgitation, wet voice, or aspiration localizes toward oral-pharyngeal physiology; delayed sticking, regurgitation, chest discomfort, or food impaction suggests esophageal structural or motility disease. FEES assesses pharyngeal secretion and airway protection, MBS shows dynamic bolus transit, esophagram defines selected structural relationships, endoscopy evaluates mucosa and permits biopsy or therapy, and manometry tests motility. Progressive symptoms, weight loss, bleeding, complete obstruction, sharp foreign body, perforation signs, or recurrent impaction require expedited evaluation rather than empiric reflux treatment.",
    ),
    ("Esophageal Disease for the Otolaryngologist", "manage"): (
        "Which pharyngoesophageal disorders can an otolaryngologist manage directly, and which findings require coordinated gastroenterology, thoracic, oncology, or emergency care?",
        "Manage selected Zenker diverticulum, cricopharyngeal dysfunction, cervical stenosis, and airway-protection consequences when the anatomy and physiology are defined and appropriate expertise is available. Coordinate distal strictures, eosinophilic or reflux esophagitis, achalasia and other motility disorders, Barrett disease, and suspected malignancy with gastroenterology or thoracic teams. Food impaction, button battery, sharp object, complete secretion intolerance, subcutaneous emphysema, systemic toxicity, or severe chest pain changes the problem to urgent extraction or perforation control. Treatment should follow localization; persistent dysphagia is not adequately managed by indefinite acid suppression alone.",
    ),
    ("Ototoxic / Noise-Induced Hearing Loss", "localize"): (
        "How do exposure timing, audiometric pattern, speech testing, tinnitus, vestibular symptoms, and asymmetry distinguish noise or drug toxicity from age-related, genetic, retrocochlear, or middle-ear disease?",
        "Build a dose-and-timeline history for occupational and impulse noise, chemotherapy, aminoglycosides, loop diuretics, and other relevant agents, including renal function and concurrent exposures. Noise injury often produces a high-frequency notch that may broaden, whereas many ototoxins begin bilaterally at the highest frequencies and progress with cumulative dose; either can cause tinnitus before perceived disability. Confirm sensorineural physiology and serial change with audiometry. Marked asymmetry, disproportionate speech loss, unilateral tinnitus, fluctuating hearing, conductive findings, or focal neurologic signs should redirect evaluation rather than being attributed reflexively to exposure.",
    ),
    ("Submandibular Gland Excision", "manage"): (
        "How should indication, infection, stone location, malignancy risk, nerve anatomy, duct control, and postoperative findings guide submandibular-gland excision and rescue?",
        "Confirm that excision is needed rather than transoral stone removal, sialendoscopy, observation, or cancer-directed resection, and control acute infection before elective surgery when possible. Plan around the marginal mandibular, lingual and hypoglossal nerves, facial artery and vein, mylohyoid, and Wharton duct; protect the lingual nerve where it loops around the duct and avoid leaving an obstructed distal remnant. A suspicious tumor may require oncologic margins and neck management rather than routine extracapsular removal. Postoperative tongue weakness, floor-of-mouth swelling, expanding hematoma, salivary collection, infection, or lower-lip weakness demands documented reassessment and cause-specific care.",
    ),
    ("Airway Foreign Body", "localize"): (
        "Which history, examination, sound, laterality, and imaging pattern localize a suspected airway foreign body, and why can a normal chest radiograph be falsely reassuring?",
        "A witnessed choking episode followed by persistent cough, unilateral wheeze, asymmetric breath sounds, stridor, recurrent focal pneumonia, or unexplained respiratory symptoms should raise suspicion. Laryngeal or tracheal objects may cause stridor or biphasic noise; a mainstem object more often causes unilateral air trapping, atelectasis, or diminished ventilation. Many organic and plastic objects are radiolucent, and early films can be normal; inspiratory-expiratory or decubitus views may show indirect obstruction. High clinical suspicion after a convincing event warrants controlled bronchoscopy despite nondiagnostic imaging.",
    ),
    ("Airway Foreign Body", "workup"): (
        "How should a suspected airway foreign body be evaluated without delaying definitive bronchoscopy or destabilizing a partially obstructed child?",
        "Assess airway stability, timing and type of choking event, current work of breathing, voice, oxygenation, breath-sound asymmetry, and prior pneumonia. Avoid agitating a child with severe obstruction and mobilize anesthesia and bronchoscopic expertise early. Radiographs can identify a radiopaque object or indirect air trapping; CT is selective when suspicion is intermediate and the patient is stable, not a prerequisite after a classic event. Flexible bronchoscopy can answer selected diagnostic questions, but rigid bronchoscopy remains the controlled therapeutic standard for many pediatric objects because it provides ventilation, exposure, and extraction capability.",
    ),
    ("Airway Foreign Body", "manage"): (
        "What is the management sequence for partial versus complete airway foreign-body obstruction, and what must be checked after extraction before the case is finished?",
        "For effective cough and partial obstruction, preserve spontaneous ventilation and avoid blind finger sweeps while arranging controlled removal. Complete obstruction requires immediate age-appropriate choking maneuvers and, if unsuccessful, direct airway intervention. In the operating room, coordinate ventilation with rigid bronchoscopy, choose forceps that control rather than fragment the object, and anticipate edema, bleeding, migration, fire risk, and inability to pass the glottis. After extraction, reinspect both bronchi and the injured segment for fragments, a second object, granulation, perforation, pneumothorax, or retained secretions before extubation planning.",
    ),
    ("Deep Neck Abscess Drainage", "localize"): (
        "How do symptoms, examination, fascial-space anatomy, and imaging localize a deep-neck infection and predict airway, vascular, mediastinal, or intracranial danger?",
        "Trismus and tonsillar displacement suggest peritonsillar or masticator involvement; floor-of-mouth elevation suggests sublingual or submandibular disease; torticollis and posterior pharyngeal bulge suggest retropharyngeal infection; neck swelling along the carotid space raises jugular or vascular complications. Contrast CT in a stable patient maps drainable collection, source, gas, vessel relationships, and spread toward the mediastinum. Stridor, drooling, tripod positioning, rapidly progressive swelling, cranial neuropathy, septic emboli, chest symptoms, or neurologic change demands simultaneous airway and complication planning rather than routine imaging-first sequencing.",
    ),
    ("Deep Neck Abscess Drainage", "workup"): (
        "What workup distinguishes cellulitis or phlegmon from a drainable deep-neck abscess while identifying the source and complications that change source control?",
        "Assess airway and sepsis before testing, then examine teeth, tonsils, salivary glands, floor of mouth, neck mobility, cranial nerves, and chest symptoms. Obtain contrast-enhanced CT when stable to define rim enhancement, central low attenuation, gas, mass effect, involved spaces, odontogenic or tonsillar source, internal-jugular thrombosis, carotid injury, skull-base extension, and mediastinal spread. Ultrasound can guide superficial pediatric questions; MRI is selective for skull base, spine, or intracranial concern. Send blood and operative cultures when indicated, but do not let equivocal imaging delay drainage of a clinically deteriorating patient.",
    ),
    ("Deep Neck Abscess Drainage", "teach"): (
        "How would you teach deep-neck abscess drainage as airway protection plus anatomy-specific source control rather than simply opening the largest fluid pocket?",
        "First secure a plan for an airway that may worsen with supine positioning or induction. Then identify the infected compartment, primary source, dependent extent, and relationship to carotid sheath, cranial nerves, salivary ducts, skull base, and mediastinum. Choose transoral, transcervical, image-guided, or combined access that reaches every clinically important loculation without crossing avoidable neurovascular structures. Drainage fails when the dental, tonsillar, salivary, foreign-body, or necrotic source persists. Continue culture-directed antimicrobials and reassess trajectory; ongoing fever, swelling, chest pain, neurologic change, or sepsis should trigger repeat imaging and additional source control.",
    ),
    ("Chyle Leak", "workup"): (
        "How should a suspected cervical chyle leak be confirmed and quantified, and which physiologic consequences or anatomy predict failure of conservative care?",
        "Track drain volume and appearance in relation to feeding; milky output is suggestive but fasting chyle may be clear. When uncertain, test drain triglycerides relative to serum or demonstrate chylomicrons, while excluding purulence and enteral-feed contamination. Follow fluid balance, weight, albumin or nutritional status, electrolytes, lymphocyte loss, wound integrity, and respiratory effects. Review the operation and side, recognizing variable and multiple lymphatic terminations. Rising or persistently high output, metabolic depletion, skin compromise, mediastinal or pleural accumulation, and failure to fall with an adequate initial strategy should accelerate lymphatic imaging or definitive control.",
    ),
    ("Chyle Leak", "teach"): (
        "How would you teach cervical chyle leak from recognition through nutritional physiology, output-based escalation, and operative or interventional rescue?",
        "Explain that lymph loss is not merely inconvenient drainage: it depletes volume, protein, electrolytes, fat-soluble nutrients, and lymphocytes while impairing wound healing and immunity. Confirm the diagnosis, quantify the trajectory, maintain effective drainage, and reduce intestinal lymph flow with an appropriate low-fat medium-chain-triglyceride or temporary nutrition strategy while replacing losses. Adjunctive medication and local measures are center- and patient-specific. Persistent high output or physiologic decline should shorten the path to re-exploration, thoracic-duct ligation, or image-guided lymphatic embolization rather than extending unsuccessful conservative care indefinitely.",
    ),
    ("Head & Neck Radiation Toxicity / Survivorship", "localize"): (
        "How do treatment field, dose, time course, symptoms, and examination localize late head-and-neck radiation toxicity without missing recurrence or a second primary?",
        "Map each complaint to irradiated structures and latency: salivary injury causes xerostomia and dental risk; pharyngeal fibrosis and neuropathy impair swallow; laryngeal edema or chondroradionecrosis affects airway and voice; mandibular or temporal-bone injury causes exposed bone and infection; thyroid, carotid, hearing, shoulder, and cranial-nerve effects may emerge years later. New pain, progressive ulceration, bleeding, weight loss, focal mass, worsening trismus, or new neuropathy cannot be labeled radiation change by history alone. Endoscopy, imaging, dental assessment, swallow testing, and biopsy are selected to separate toxicity from recurrent disease.",
    ),
    ("Head & Neck Radiation Toxicity / Survivorship", "workup"): (
        "What longitudinal surveillance should a head-and-neck radiation survivor receive for recurrence, swallowing, dental, endocrine, auditory, vascular, nutritional, and psychosocial complications?",
        "Use site- and stage-appropriate cancer surveillance with symptom-directed endoscopy and imaging, while tracking weight, nutrition, aspiration and swallowing function, oral opening, neck and shoulder mobility, dental health, salivary function, thyroid function, hearing when exposed, and tobacco or alcohol risk. Review pain, sleep, mood, return to work, cognition, sexuality, and caregiver burden rather than reducing survivorship to tumor scans. Carotid or other vascular assessment is risk based. A new focal deficit, progressive dysphagia, aspiration pneumonia, exposed bone, nonhealing ulcer, or unexplained pain requires targeted evaluation for both late toxicity and recurrence.",
    ),
    ("Head & Neck Radiation Toxicity / Survivorship", "manage"): (
        "How should late radiation toxicity be prevented, rehabilitated, and escalated when conservative care no longer protects swallowing, airway, dentition, bone, or quality of life?",
        "Begin dental prevention, fluoride, nutrition, smoking cessation, range-of-motion work, and swallow preservation before or during treatment when feasible. After treatment, use saliva and dental support, targeted swallowing and voice therapy, fibrosis and lymphedema rehabilitation, thyroid replacement when indicated, hearing rehabilitation, pain care, and psychosocial support. Treat aspiration, stenosis, soft-tissue or bone infection, and exposed necrotic tissue according to the demonstrated mechanism; selected patients need dilation, debridement, vascularized reconstruction, airway intervention, or aspiration-prevention surgery. Refractory symptoms should trigger renewed recurrence evaluation rather than endless empiric antibiotics or analgesics.",
    ),
    ("Pediatric Hearing Loss Workup", "localize"): (
        "How do behavioral thresholds, tympanometry, OAEs, ABR, speech measures, laterality, and developmental history localize pediatric hearing loss and determine how urgently hearing access is needed?",
        "Separate conductive loss from middle-ear or canal disease, cochlear sensorineural loss, mixed loss, and auditory-neural dysfunction using age-appropriate behavioral testing with objective cross-checks. Tympanometry assesses middle-ear mechanics, OAEs reflect outer-hair-cell function, and ABR estimates neural pathway responses when behavioral reliability is limited; no single test should stand alone. Define severity, frequency pattern, laterality, progression, and functional speech access. Because auditory and language development is time sensitive, provide amplification and communication support while etiologic genetics, imaging, congenital-infection, ophthalmologic, or neurologic evaluation proceeds rather than waiting for every cause to be known.",
    ),
    ("Anaplastic Thyroid Cancer", "teach"): (
        "How would you teach anaplastic thyroid cancer as a simultaneous airway, tissue-diagnosis, staging, molecular, and goals-of-care emergency?",
        "Rapidly enlarging thyroid or neck disease with dyspnea, dysphagia, pain, vocal-fold paralysis, or skin fixation requires urgent airway assessment and contrast imaging of local and distant extent. Obtain tissue promptly by the safest high-yield route and send molecular testing early because an actionable alteration can change systemic treatment. Resectability must be decided by an experienced multidisciplinary team; incomplete morbid surgery is not automatically beneficial. Coordinate radiation and systemic options, nutrition, symptom control, and honest goals-of-care discussion from the start. Tracheostomy can be technically difficult and should follow a deliberate plan rather than reflexive bedside escalation.",
    ),
    ("Choanal Atresia", "manage"): (
        "How should unilateral versus bilateral choanal atresia be stabilized, evaluated, repaired, and followed, and what associated disease changes the plan?",
        "Bilateral disease in a cyanotic newborn is an airway emergency: restore temporary oral airflow with positioning, an oral airway or intubation while arranging definitive care. Confirm anatomy with nasal examination and CT after decongestion, and assess feeding, aspiration, cardiac and syndromic disease including CHARGE features. Unilateral atresia often permits elective repair when symptoms and anatomy justify it. Endoscopic repair removes the obstructing plate and creates a durable choana while limiting injury to skull base, sphenopalatine region, septum, and palate. Postoperative surveillance addresses restenosis, granulation, feeding, and nasal care; routine stenting is individualized.",
    ),
    ("Choanal Atresia", "teach"): (
        "How would you teach the physiology and presentation of choanal atresia so a learner recognizes bilateral neonatal crisis and unilateral delayed disease?",
        "Newborns strongly prefer nasal breathing, so bilateral obstruction produces cyclic cyanosis and respiratory distress that may improve with crying when the mouth opens; inability to pass a catheter is a clue but not definitive proof. Unilateral atresia can present later with chronic one-sided obstruction or discharge. Stabilize airflow before pursuing imaging, then distinguish bony, membranous, or mixed obstruction and look for associated craniofacial and CHARGE features. The operation is not merely puncturing a plate: it must create and maintain an adequately sized posterior nasal airway without injuring adjacent skull-base, palatal, or vascular structures.",
    ),
    ("Four-Gland Parathyroid Exploration", "workup"): (
        "Before four-gland exploration, how should diagnosis, renal function, familial disease, imaging, vocal-fold status, prior surgery, and intraoperative PTH kinetics shape the plan?",
        "Confirm the biochemical diagnosis and distinguish primary from secondary or tertiary hyperparathyroidism, reviewing calcium, albumin or ionized calcium, PTH, renal function, vitamin D, phosphate, medications, and urinary calcium when relevant. Assess MEN or familial risk and prior neck operations, document vocal-fold motion when indicated, and use imaging for operative planning rather than to decide whether biochemical disease exists. Anticipate multigland anatomy, supernumerary or ectopic glands, thymic descent, and autotransplant or cryopreservation needs. Interpret intraoperative PTH in context because delayed clearance with renal dysfunction can complicate rigid timing thresholds.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v146_ped_03": "A palatal fistula can permit nasal escape of food and liquid, impair pressure generation for speech, and cause compensatory articulation or hypernasality depending on its size and location. Determine whether symptoms arise from the fistula itself, persistent velopharyngeal dysfunction, or learned speech patterns. Small asymptomatic fistulas may be observed; symptomatic repair should wait for healthy tissue and use a tension-free multilayer plan, with speech therapy addressing errors that closure alone will not erase.",
    "v247_ped_cleft_app": "Excess tension compromises flap perfusion and concentrates force along the closure, promoting ischemia, dehiscence, and an oronasal fistula. A technically closed palate is not a successful repair if the tissues cannot survive or the reconstructed levator cannot function. Reassess mobilization, relaxing incisions, tissue availability, and whether a staged or alternative flap is safer. Preserve vascular pedicles and achieve multilayer separation without forcing short tissue to span an uncorrected gap.",
    "v147_fp_08": "Strip harvest removes an ellipse and closes a linear donor scar, often yielding many grafts while preserving follicular units under magnification; scar width depends on tension, healing, and repeated harvest. FUE extracts individual units, leaving numerous small circular scars and permitting short hairstyles, but overharvesting can create diffuse moth-eaten thinning and reduces future donor flexibility. Neither creates new follicles: donor density, caliber, curl, scalp laxity, hairstyle, future loss, and prior scars determine the choice.",
    "v262_fpt_hair_app": "Stabilizing androgenetic loss with appropriate medical therapy clarifies the true progression rate, may improve miniaturized native hair, and reduces the chance that transplanted islands remain while surrounding hair disappears. Reassess after an adequate treatment interval before committing finite donor supply. Graft number should follow a long-term density and framing plan, not the maximum that fits today. Rapid ongoing loss, young age, weak donor reserve, or unrealistic density goals favors delay or conservative staging.",
    "v128_lar_09": "A simple polyp is a discrete lesion that can often be removed while preserving normal layered tissue. Scar and sulcus alter the vibratory cover, lamina propria depth, and sometimes epithelial adherence across a broader or poorly bounded area. Excision cannot recreate normal viscoelastic architecture, and manipulation can add fibrosis. Treatment must balance closure against stiffness; voice therapy, augmentation, scar-directed procedures, and staged reassessment may improve function, but normal wave restoration is less predictable.",
    "v136_oto_08": "An adult who developed language normally retains established auditory-linguistic networks, so later hearing loss does not carry the same developmental deprivation risk as congenital deafness. Prognosis still depends on duration and completeness of auditory deprivation, cochlear or neural pathology, cognitive health, device use, and rehabilitation. Earlier restoration generally reduces maladaptive deprivation, but counseling should distinguish recovery of access and speech understanding from a child's time-sensitive acquisition of language in the first place.",
    "v144_oto_08": "Early childhood is a sensitive period for auditory-language development, and prolonged deprivation can reorganize central pathways and reduce the efficiency with which later cochlear input is used. Implant timing therefore matters alongside anatomy, cause, residual hearing, consistent hearing-aid use, communication access, and family goals. Do not promise a uniform outcome based on age alone; provide rich language exposure and habilitation immediately, without postponing communication while implant candidacy is being completed.",
    "v173_oto_plastic_snr": "Prior meaningful spoken-language development indicates that auditory-linguistic pathways were established before hearing loss, which generally improves the ability to interpret a restored signal compared with congenital or prelingual long-term deprivation. Prognosis still varies with duration of deafness, residual neural integrity, cognition, cause, consistency of device use, and rehabilitation. Document what communication was achieved and when access was lost rather than treating chronological age or an imaging finding as the sole predictor.",
    "v138_hn_22": "Cisplatin is renally cleared and can cause cumulative nephrotoxicity, electrolyte wasting, neuropathy, and often irreversible high-frequency sensorineural hearing loss. Baseline creatinine clearance, magnesium, audiometry, tinnitus, hearing needs, neuropathy, performance status, and interacting drugs therefore influence eligibility, dose, hydration, monitoring, and whether an alternative radiosensitizer is safer. A patient who cannot hear communication-critical frequencies or clear the drug adequately may suffer disproportionate permanent harm even if the tumor indication is otherwise strong.",
    "v138_lar_02": "Ansa-to-recurrent-laryngeal-nerve reinnervation is especially attractive in a younger patient with a stable unilateral neural injury, viable laryngeal muscle, meaningful long-term voice needs, and no expectation that immediate motion will return. It restores tone and bulk over months rather than purposeful abduction, so temporary injection may bridge the delay. Large posterior gap or vertical mismatch may still require arytenoid adduction or framework surgery, and longstanding denervation, joint fixation, scar, or poor donor nerve changes the expected benefit.",
    "v145_lar_02": "Favor reinnervation when the injury is recent but judged durable, the patient is young, the thyroarytenoid remains viable, and long-term restoration of tone is preferable to an implant alone. Counsel that improvement takes months and does not restore normal movement; temporary injection can support voice or swallowing during regeneration. If recovery remains genuinely possible, prognosis is unclear, or immediate closure is the dominant need, observation, LEMG-informed timing, injection, or framework surgery may be more appropriate.",
    "v145_lar_12": "Stop office TNE for severe pain, unexpected resistance, inability to maintain the lumen, bleeding that obscures the view, respiratory distress, syncope, suspected perforation, or anatomy that prevents safe passage. A tight stricture, large diverticulum, sharp foreign body, obstructing tumor, unstable cervical spine, significant aspiration risk, or need for controlled dilation or hemostasis belongs in a setting with anesthesia and rescue capability. Never push through unexplained resistance merely to complete the examination.",
    "v146_ped_15": "Urgent imaging and neurologic evaluation are warranted for focal weakness or sensory loss, diplopia, dysarthria, new severe headache, altered mental status, papilledema, direction-changing or vertical nystagmus, ocular dysmetria, marked truncal ataxia, inability to walk, seizures, progressive symptoms, or an examination not fitting a peripheral disorder. In a child, persistent morning vomiting, developmental regression, and symptoms triggered by Valsalva also matter. Migraine is common, but it should not be used to explain objective central findings.",
    "v248_ped_vest_snr": "These findings convert a routine dizziness evaluation into urgent central neurologic assessment. Stabilize the child, document timing and ocular-motor findings, obtain emergent neuroimaging appropriate to suspected posterior-fossa, vascular, infectious, or pressure pathology, and involve neurology or emergency teams. Do not rely on a normal ear examination or label the presentation vestibular migraine. Direction-changing nystagmus, severe gait failure, focal deficits, or thunderclap headache can signal stroke, tumor, demyelination, cerebellitis, hemorrhage, or raised intracranial pressure.",
    "v147_fp_17": "Even without cooperation, inspect pupil size and reactivity, relative afferent defect when testable, globe position, proptosis, chemosis, corneal exposure, anterior chamber, wounds, and resistance to retropulsion; palpate orbital tension and review pre-intubation vision documentation. Thin-cut CT helps identify retrobulbar hemorrhage, globe contour change, optic-canal injury, muscle entrapment, and orbital fractures. A tense orbit with concerning pupillary or globe findings warrants immediate ophthalmologic and decompression action rather than waiting for formal acuity testing.",
    "v148_lar_01": "After difficult extraction, sudden desaturation, rising airway pressures, unilateral breath-sound loss, subcutaneous emphysema, chest asymmetry, hypotension, or unexpected difficulty ventilating should raise concern for pneumothorax or airway perforation. Pause, maintain oxygenation, inspect the tracheobronchial tree, and obtain immediate bedside ultrasound or radiography if the patient is stable. Tension physiology requires decompression without waiting for imaging. Also look for retained fragments, mucosal laceration, mediastinal air, bleeding, and contralateral obstruction.",
    "v170_oto_mast_snr": "Actively evaluate sigmoid or transverse sinus thrombosis, internal-jugular extension, epidural or subdural empyema, meningitis, cerebritis or brain abscess, cavernous-sinus involvement when anatomy fits, and petrous-apex complications affecting abducens or trigeminal function. New headache, papilledema, focal deficit, seizure, altered mental status, persistent bacteremia, or multiple pulmonary embolic lesions changes imaging and urgency. Obtain contrast venous and intracranial imaging as indicated while coordinating antimicrobial therapy and surgical source control.",
    "v228_hn_rt_fnd": "Radiation works through cumulative biologic dose delivered on a planned schedule. Unplanned gaps permit accelerated repopulation of surviving tumor clonogens, so completing the same nominal dose later may not fully preserve control, especially in rapidly proliferating squamous cancers. Prevent avoidable breaks with proactive dental, nutrition, skin, pain, airway, and social support. When interruption occurs, the radiation oncologist determines whether and how to compensate; patients should not improvise missed fractions or continue through unsafe toxicity without assessment.",
    "v243_ped_sgh_fnd": "A large segmental cervicofacial hemangioma, particularly in a beard or frontotemporal distribution, should prompt evaluation for PHACE-spectrum disease: posterior-fossa anomalies, arterial cerebrovascular abnormalities, cardiac or aortic-arch defects, eye abnormalities, and ventral developmental defects. The phenotype guides MRI/MRA, cardiac, ophthalmologic, and other testing before systemic therapy. Airway symptoms still require direct airway assessment; a skin distribution raises risk but neither proves nor excludes subglottic involvement.",
    "v247_ped_frenulum_fnd": "Document latch quality, maternal nipple pain or trauma, milk transfer, audible swallowing, fatigue, duration and frequency of feeds, weight trajectory, supplementation, prior lactation support, bottle function, and respiratory or craniofacial issues. Examine tongue elevation, protrusion, cupping and lateralization during function, frenulum attachment and elasticity, palate, jaw, neuromuscular tone, and coordinated suck-swallow-breathe pattern. Appearance or a scoring tool alone should not determine frenotomy; demonstrate a plausible functional restriction after other feeding mechanics are addressed.",
    "v252_lar_presby_app": "Reopen the diagnosis for progressive or painful dysphonia, odynophagia, hemoptysis, weight loss, unilateral otalgia, aspiration, stridor, neck mass, focal leukoplakia or irregular vascularity, unilateral stiffness, impaired motion, marked asymmetry, or a gap inconsistent with simple bilateral atrophy. Presbyphonia is a diagnosis made after visualizing the larynx and considering paresis, malignancy, scar, tremor, dystonia, inflammatory disease, and systemic frailty. Age does not make a unilateral or progressive finding benign.",
    "v260_fpt_open_fnd": "Dissection can weaken the scroll region between upper and lower lateral cartilages, lateral-crural attachments, interdomal and transdomal support, medial-crural footplates, septal attachments, and the major tip-support relationship between the medial crura and caudal septum. Excessive cephalic trim, division without reconstruction, overresection of caudal septum, or destabilizing the lateral wall can cause loss of projection, pinching, alar retraction, or valve collapse. Identify which support is being altered and reconstruct it deliberately.",
    "v260_fpt_open_snr": "Internal nasal-valve collapse may require spreader grafts or flaps, dorsal or septal reconstruction, or lateral-wall support depending on the narrow segment. External valve or alar collapse may need lateral-crural strut, alar batten, rim, articulated rim, or composite graft support matched to the deficient subunit. Caudal septal or tip instability may need a septal-extension or columellar-strut strategy. Choose the smallest construct that corrects the demonstrated dynamic or static failure without narrowing another valve.",
    "v262_fpt_analysis_app": "Morphing can confirm that surgeon and patient are discussing the same directional changes, reveal competing goals, and show how one maneuver affects whole-face balance. Present it as a communication simulation, not a predicted photograph: healing, skin thickness, asymmetry, scar, animation, and intraoperative anatomy limit precision. Use multiple views, preserve features the patient values, and document that exact pixels are not guaranteed. A patient fixated on imperceptible discrepancies despite careful counseling may need expectations reassessed before surgery.",
    "v267_sleep_narc_snr": "Cataplexy is a brief, emotion-triggered loss of muscle tone—often with laughter, surprise, or anger—while consciousness and recall are preserved. It may affect jaw, neck, knees, speech, or the whole body and resolves without a postictal state. Syncope usually involves loss of consciousness and autonomic prodrome; seizures may produce positive motor activity, impaired awareness, injury, or confusion; fixed weakness persists outside triggers. Ask about timing, emotion, awareness, recovery, medications, and witness descriptions.",
    "v274_gen_frail_snr": "Persistent or worsening delirium needs broader evaluation when it is unexplained after correcting common triggers, is accompanied by focal neurologic deficit, head trauma, seizure, severe headache, fever or meningismus, anticoagulation, markedly reduced consciousness, or concern for stroke, hemorrhage, infection, mass, or nonconvulsive status. Review baseline cognition, medications, oxygenation, glucose, electrolytes, infection, retention, pain, and withdrawal. Neuroimaging and neurology consultation should answer a specific red-flag question, not substitute for a complete delirium workup.",
}


def apply_daily_curriculum_quality_v379(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if override:
            prompt, answer = override
            item["daily_prompt"] = prompt
            item["prompt"] = prompt
            item["answer"] = answer
            changed += 1
    return changed


def install_daily_curriculum_quality_v379(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v379():
        items = original_get_items()
        apply_daily_curriculum_quality_v379(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v379
    app_module._adaptive_question = lambda item: item.get("daily_prompt") or item.get("prompt") or ""
    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1
    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119
    return {"daily_pairs_repaired": len(DAILY_OVERRIDES), "curveball_answers_repaired": repaired}
