"""Seventh-order Daily Curriculum question/answer alignment repairs.

This layer targets prompts that had already been made clinically specific but
still revealed a short inherited topic pearl rather than answering the actual
question.  It also replaces curveball answers that described the parent topic
without resolving the counterfactual posed to the learner.
"""


DAILY_OVERRIDES = {
    ("Open Rhinoplasty Fundamentals", "teach"): (
        "How would you teach open rhinoplasty as a support-preserving operation, using correction of a bulbous tip to show why diagnosis must precede cartilage removal?",
        "Begin by separating skin-envelope thickness, lower-lateral-cartilage shape and orientation, tip-support relationships, and valve function. A bulbous tip caused by broad or convex lateral crura is not treated by indiscriminate cephalic trim: use measured sutures, conservative reshaping or support grafting while preserving an adequate lateral-crural strip and the scroll, septal and ligamentous supports. Recheck projection, rotation, symmetry and external-valve stability before closure. The durable lesson is that structural diagnosis guides modification and that over-resection can create pinching, alar retraction or collapse that is harder to repair than the original deformity.",
    ),
    ("Le Fort / Panfacial Trauma", "workup"): (
        "In panfacial trauma, which bedside findings and CT relationships establish the fracture pattern, and which ocular, neurologic, dental, or skull-base finding must redirect the sequence of repair?",
        "Stabilize the trauma patient first, then document vision, pupils, motility, globe position, facial sensation and movement, occlusion, mandibular mobility, midface mobility, telecanthus, nasal support and CSF leak. Thin-cut maxillofacial CT with multiplanar and three-dimensional review maps buttresses, frontal sinus, NOE complex, orbital walls, zygomas and mandible. Globe injury or orbital compartment syndrome, intracranial injury or unstable skull base, threatened airway, uncontrolled hemorrhage, contaminated open fractures and an unreliable dentition each change urgency or the reference framework. Definitive sequencing begins from reproducibly stable cranial or mandibular landmarks rather than assuming every case is repaired bottom-up.",
    ),
    ("Leukoplakia / Laryngeal Dysplasia", "manage"): (
        "Once vocal-fold leukoplakia is identified, how do endoscopic risk, voice needs, and pathology determine observation, office treatment, or operative biopsy, and what should trigger escalation?",
        "First address tobacco and other irritants and document the lesion with flexible examination and stroboscopy when phonation permits. Smooth, homogeneous, low-risk lesions may undergo close photo-documented surveillance in a reliable patient; irregular, thick, ulcerated, vascular, enlarging or wave-impairing lesions generally warrant tissue diagnosis with function-preserving microlaryngoscopy. Treatment then follows pathology and recurrence pattern, ranging from surveillance or limited ablation to repeat excision and oncologic management. Escalate for airway symptoms, rapid change, impaired mobility, suspicious vascularity, invasive carcinoma, worsening dysplasia or recurrence that cannot be safely monitored without better sampling.",
    ),
    ("Microlaryngoscopy", "workup"): (
        "Before suspension microlaryngoscopy, which airway, dental, cervical, lesion, and voice findings determine whether the target can be exposed safely or whether the plan should change?",
        "Define the indication and target with office laryngoscopy or stroboscopy, document baseline voice and fold mobility, and review prior exposure notes. Assess mouth opening, dentition, mandibular anatomy, tongue size, neck extension, cervical instability or fusion, obesity, trismus and prior radiation; identify anticoagulation and cardiopulmonary or difficult-airway risks. Imaging is selective for submucosal, deep or oncologic disease rather than routine benign lesions. A nonnegotiable cervical restriction, unstable teeth, impossible line of sight or airway plan that cannot support shared ventilation should prompt alternative laryngoscopes, angled or flexible techniques, nonsuspension biopsy, staged airway control or deferral rather than greater suspension force.",
    ),
    ("Mohs Defect Reconstruction", "workup"): (
        "Before reconstructing a Mohs defect, what must be assessed about oncologic clearance, depth, subunit anatomy, function, tissue laxity, and vascularity, and which finding should delay or change reconstruction?",
        "Confirm margin clearance and inspect the true defect after hemostasis. Record involved aesthetic subunits, depth and exposed cartilage, bone, tendon or nerve; test eyelid, alar, lip and brow function; and assess adjacent color, thickness, laxity, scars, radiation and flap vascularity. Small rim or canthal defects may be more functionally demanding than larger convex-surface defects because contraction can cause notching, ectropion or valve collapse. Uncertain margins, active infection, questionable tissue viability, an inadequately assessed lacrimal or facial-nerve injury, or a defect requiring multidisciplinary oncologic resection should delay definitive closure or redirect it toward staged reconstruction.",
    ),
    ("Vocal Tremor", "teach"): (
        "How would you teach vocal tremor from perceptual pattern and distribution through confirmation, differentiation, and treatment escalation?",
        "Start by listening for rhythmic oscillation during sustained vowels, connected speech and quiet breathing, then examine the palate, pharynx, tongue base, vertical larynx and true folds across tasks. Tremor is usually regular and may occur across several subsites, whereas spasmodic dysphonia is task-specific and produces irregular phonatory breaks; muscle-tension compensation and essential tremor elsewhere should also be sought. Confirm the functional impact and obtain neurologic assessment when tremor is generalized or atypical. Begin with education and selected voice strategies, consider systemic tremor therapy with appropriate specialists, and use site-directed botulinum toxin for disabling laryngeal tremor while counseling about transient breathiness or dysphagia.",
    ),
    ("Ankyloglossia / Maxillary Frenulum", "teach"): (
        "How would you teach ankyloglossia as a function-first algorithm with a decisive examination, conservative step, procedural threshold, and post-procedure safety stop?",
        "First define the functional complaint—ineffective milk transfer with maternal pain, later mechanical limitation, or a speech concern—rather than grading a frenulum photograph alone. Observe feeding with skilled lactation support, examine tongue mobility and rule out more common causes of poor intake or pain; speech concerns require age-appropriate speech-language assessment. Optimize positioning and feeding support before offering frenotomy. Consider release when a restrictive lingual frenulum clearly causes persistent dysfunction despite conservative help and the expected benefit outweighs bleeding, pain, oral aversion and reattachment risk. Active bleeding, floor-of-mouth swelling, respiratory change, fever, dehydration or worse feeding after the procedure requires urgent reassessment.",
    ),
    ("Choanal Atresia", "workup"): (
        "How is suspected choanal atresia confirmed after the airway is stabilized, and which endoscopic or CT finding changes urgency or operative planning?",
        "Failure to pass an appropriately sized catheter, absent posterior nasal airflow and neonatal cyanosis relieved by crying raise suspicion, but mucus, edema and pyriform aperture stenosis must be excluded. After suction and decongestion, flexible endoscopy confirms the posterior obstruction. Thin-cut CT obtained after clearing secretions defines unilateral versus bilateral disease, bony versus mixed anatomy, vomer thickness and adjacent skull-base or craniofacial anomalies. Bilateral obstruction is an immediate neonatal airway problem; associated CHARGE features, a very thick bony plate, skull-base abnormality or additional airway disease changes timing, equipment and multidisciplinary planning.",
    ),
    ("Esophageal Foreign Body", "manage"): (
        "Once an esophageal foreign body is identified, how do object type, obstruction, symptoms, and time determine emergent versus urgent removal, and what finding requires complication-directed escalation?",
        "Protect the airway, stop oral intake and determine the object, location, ingestion time and ability to handle secretions. An esophageal button battery requires immediate removal; complete obstruction, a sharp or long object, significant respiratory symptoms or clinical instability also demands emergent endoscopy. Other coins or blunt objects lodged in the esophagus should be removed urgently rather than observed indefinitely. Fever, crepitus, severe neck or chest pain, hematemesis, shock, mediastinal air or extravasation suggests perforation or vascular injury and requires broad-spectrum antibiotics, cross-sectional imaging when stable, and immediate surgical consultation rather than routine extraction alone.",
    ),
    ("Laryngeal Anatomy", "workup"): (
        "Which examination and imaging modalities best answer questions about laryngeal motion, vibration, submucosal spaces, cartilage, and tumor spread, and what normal asymmetry should not be overcalled?",
        "Flexible laryngoscopy defines supraglottic and vocal-fold motion, airway caliber, pooling and gross mucosal disease; stroboscopy adds vibratory amplitude, wave, closure, periodicity and vertical-level information when phonation is sufficiently periodic. Direct laryngoscopy permits palpation and biopsy. Contrast CT is useful for cartilage, airway and deep extension, while MRI better resolves selected soft-tissue, marrow and perineural questions. Interpret mild arytenoid height or rotation differences, ventricular asymmetry and phase asymmetry in clinical context: none alone proves paralysis or invasive disease. The test should be chosen for the compartment and management decision rather than used as interchangeable anatomy pictures.",
    ),
    ("Lymphatic Malformation", "workup"): (
        "What clinical and imaging findings confirm a lymphatic malformation, define its macrocystic or microcystic extent, and change the urgency or treatment choice?",
        "A soft, compressible, often trans-spatial lesion that enlarges with infection or hemorrhage suggests the diagnosis. Ultrasound distinguishes cystic from solid superficial disease and can guide aspiration, while contrast MRI best maps trans-spatial extent, fluid-fluid levels and involvement of tongue, floor of mouth, pharynx, orbit or mediastinum. CT is reserved for selected acute or bony questions. Airway compromise, dysphagia, rapid painful enlargement, hemorrhage or infection changes urgency. Macrocystic pockets are often favorable for sclerotherapy; diffuse microcystic mucosal or infiltrative disease may require multimodal therapy because complete surgical excision can carry unacceptable nerve and functional morbidity.",
    ),
    ("MEN2 / RET", "manage"): (
        "After a pathogenic RET variant is confirmed, how should pheochromocytoma screening, thyroidectomy timing, calcium surveillance, and family testing be sequenced?",
        "Coordinate care with endocrinology, genetics and an experienced thyroid team. Test for pheochromocytoma before thyroid surgery and treat a catecholamine-secreting tumor first to avoid perioperative crisis. Time prophylactic or therapeutic thyroidectomy according to RET risk category, calcitonin trend, ultrasound findings, age and established medullary carcinoma rather than using one age for every genotype. Screen for hyperparathyroidism and plan calcium/PTH follow-up. Offer targeted testing and counseling to at-risk relatives, including age-appropriate testing of children when results change surveillance or surgery. Rising calcitonin, a structural lesion or symptoms of hormone excess should accelerate disease-specific evaluation.",
    ),
    ("Nasopharyngeal Carcinoma", "workup"): (
        "How should nasopharyngeal carcinoma be confirmed and staged, including primary-site biopsy, skull-base and nodal imaging, distant staging, and EBV-related testing?",
        "Perform complete head-and-neck examination with nasopharyngoscopy and obtain endoscopic biopsy of the primary when feasible; a neck mass alone should not substitute for assessment of the nasopharynx. Contrast MRI best maps parapharyngeal, skull-base, intracranial and perineural extension, while CT complements bone assessment and treatment planning. Image the entire neck and obtain guideline-appropriate distant staging, commonly with PET/CT for locoregionally advanced disease. Pathology establishes histology and relevant viral association; plasma EBV DNA can support prognosis and surveillance in appropriate endemic or EBV-associated disease but does not replace biopsy or imaging. Cranial neuropathy, skull-base invasion or bulky nodal disease materially changes stage and treatment planning.",
    ),
    ("Otoplasty", "workup"): (
        "Before otoplasty, which deformity components, asymmetries, tissue qualities, and patient factors determine the technique or make surgery inappropriate?",
        "Analyze each ear separately for antihelical underfolding, conchal excess, conchomastoid angle, lobular prominence, helical shape, cartilage stiffness, skin quality and superior/middle/inferior asymmetry. Measure projection at reproducible levels and photograph both ears, then discuss that perfect symmetry is unrealistic. Determine whether suture reshaping, conchal setback, limited cartilage modification or a combined approach addresses the actual mechanics. Defer for active infection, unstable scarring, unrealistic expectations or inability to participate in postoperative protection. Prior surgery, very stiff cartilage, congenital framework deficiency or major size discrepancy requires a reconstructive rather than routine setback plan.",
    ),
    ("Pediatric Vocal Fold Immobility", "teach"): (
        "How would you teach pediatric vocal-fold immobility from airway presentation and cause through motion confirmation, swallowing assessment, observation, and irreversible intervention?",
        "Begin by separating unilateral disease, which often presents with weak cry and aspiration, from bilateral immobility, which can cause neonatal stridor and airway failure. Flexible laryngoscopy documents position and apparent motion, but direct examination, palpation and selected laryngeal EMG or imaging may be needed to distinguish neuropathy from cricoarytenoid fixation and to investigate central, birth-trauma, cardiac or iatrogenic causes. Assess feeding and aspiration, not just breathing. Stabilize the airway and support nutrition while allowing recovery when safe. Before cordotomy, arytenoidectomy or another irreversible widening procedure, establish mechanism, recovery potential and the expected trade among airway, voice and swallowing.",
    ),
    ("Recurrent Acute Rhinosinusitis", "teach"): (
        "How would you teach recurrent acute rhinosinusitis as an episode-based pathway that distinguishes true bacterial recurrences from chronic sinusitis, migraine, and repeated viral illness?",
        "Require discrete acute episodes with return to baseline between them and document whether each episode actually meets bacterial features such as persistence without improvement, severe onset or double worsening. Symptoms that never clear suggest chronic rhinosinusitis; short nonspecific colds, facial pain without objective sinonasal disease and migraine should not be relabeled as recurrent bacterial infection. Review allergy, immune risk, dental disease and anatomic obstruction, using endoscopy or appropriately timed CT when results will change management. Treat individual bacterial episodes judiciously, optimize contributing inflammation and reserve surgery for well-documented recurrences with a correctable disease pattern after medical evaluation.",
    ),
    ("Septal Deviation", "teach"): (
        "How would you teach septal deviation from symptom localization through examination, medical trial, septoplasty selection, and prevention of structural complications?",
        "Confirm that obstruction corresponds to the septal deformity and assess turbinates, mucosal disease and static or dynamic nasal-valve dysfunction; decongestion can reveal reversible congestion but does not straighten cartilage. Treat inflammatory contributors first when present. Offer septoplasty when a structurally important deviation remains functionally limiting and counseling includes the possibility of residual valve or turbinate obstruction. During surgery preserve adequate dorsal and caudal support, maintain mucosal vascularity and avoid opposing bilateral tears. Persistent obstruction, saddle change, tip ptosis, perforation, hematoma or worsening valve collapse indicates that support or another obstructive site was missed or injured.",
    ),
    ("Subglottic Hemangioma", "workup"): (
        "In an infant with recurrent or atypical croup, how is subglottic hemangioma confirmed, and which airway or associated finding changes the next step?",
        "Progressive biphasic stridor, barky cough outside the usual croup pattern, poor response to standard therapy and cutaneous segmental hemangioma raise concern. Flexible laryngoscopy may show the lesion below the cords, but controlled direct laryngoscopy and bronchoscopy define airway caliber, circumferential extent and additional lesions when symptoms are significant or diagnosis remains uncertain. MRI is selective for extensive, atypical or syndromic disease rather than required in every classic case. Respiratory distress, feeding compromise, marked subglottic narrowing or rapid progression requires urgent airway planning and treatment; a large segmental facial hemangioma should trigger evaluation for PHACE-associated abnormalities before selected systemic therapy.",
    ),
    ("Submandibular Gland Excision", "localize"): (
        "Before submandibular-gland excision, map the gland, duct, facial vessels, and marginal mandibular, lingual, and hypoglossal nerves; which relationships change the dissection?",
        "The gland wraps around the posterior free edge of mylohyoid into superficial and deep components. The marginal mandibular nerve is vulnerable above the lower mandibular border during flap elevation; facial vein and artery cross the gland and may be divided or used to protect the nerve. The lingual nerve lies superior to the deep lobe and loops around Wharton duct, while the hypoglossal nerve runs deeper on hyoglossus. Proximal duct stones, deep-lobe tumor, inflammation or scar can tether these relationships and increase nerve risk. Follow the capsule and duct under direct vision rather than treating the operation as simple removal of a superficial mass.",
    ),
    ("Supraglottoplasty", "workup"): (
        "Before supraglottoplasty, what airway, sleep, feeding, neurologic, pulmonary, and endoscopic findings establish candidacy or predict that surgery alone will not solve the problem?",
        "Confirm dynamic supraglottic collapse and define shortened aryepiglottic folds, redundant arytenoid mucosa and epiglottic prolapse on awake flexible laryngoscopy. Grade respiratory effort, growth, cyanotic events and sleep symptoms, and assess swallowing or aspiration when indicated. Look for synchronous airway lesions with direct endoscopy in severe, atypical or operative cases. Neurologic hypotonia, significant cardiopulmonary disease, craniofacial abnormality, vocal-fold immobility, subglottic disease or severe aspiration predicts persistent symptoms and changes postoperative monitoring. Mild disease without hypoxemia or growth failure usually receives observation and feeding support; surgery is reserved for clinically consequential obstruction after comorbid drivers are addressed.",
    ),
    ("Tongue Base Surgery", "localize"): (
        "Before tongue-base surgery for obstructive sleep apnea, which collapse pattern, neurovascular anatomy, exposure limits, and multilevel findings determine the target and approach?",
        "Use examination and often drug-induced sleep endoscopy to distinguish lingual-tonsil hypertrophy, posterior muscular tongue collapse and epiglottic or lateral-wall contributions; a large awake tongue is not itself a surgical target. The lingual arteries run deep and lateral within tongue musculature, the hypoglossal nerves enter laterally, and vallecular and epiglottic relationships shape transoral exposure. Prior radiation, trismus, mandibular anatomy, bleeding risk and poor visualization may preclude safe resection. Concentric palatal or multilevel collapse, severe obesity and inadequate skeletal support reduce the likelihood that isolated tongue-base reduction will succeed and should redirect counseling or combined treatment.",
    ),
    ("Tracheobronchial Endoscopy Principles", "teach"): (
        "How would you teach rigid tracheobronchial endoscopy as a shared ventilation procedure, from indication and airway plan through systematic examination, foreign-body rescue, and complication recognition?",
        "Define the suspected level and urgency before induction, review imaging without allowing a normal film to overrule high clinical suspicion, and agree with anesthesia on spontaneous versus controlled ventilation and the rescue plan. Choose age-appropriate telescopes, bronchoscopes and forceps and confirm that suction, optical forceps and emergency airway equipment are present. Examine the larynx, trachea, carina and both bronchial trees systematically while continuously coordinating oxygenation and instrument passage. During extraction maintain control of the object and withdraw it with the bronchoscope when needed, then reinspect for a second object, trauma or residual obstruction. Desaturation, bleeding, pneumothorax, airway edema or loss of the object requires an announced stop and the rehearsed rescue pathway.",
    ),
    ("Central Events / Hypoventilation", "teach"): (
        "How would you teach central apnea and sleep-related hypoventilation from polysomnographic pattern through cause, confirmatory data, treatment selection, and a ventilation safety stop?",
        "First separate absent respiratory effort during scored central apneas from sustained or sleep-stage-related CO2 elevation due to inadequate ventilation; the total AHI alone hides that distinction. Review central-apnea index, event timing, oxygen and CO2 tracings, sleep stage and periodic breathing, then integrate opioids, altitude, heart failure, neurologic disease, pulmonary restriction and neuromuscular weakness. Confirm daytime gas exchange, pulmonary function or cardiac status when indicated and correct the cause before selecting oxygen, PAP or noninvasive ventilation. Avoid adaptive servo-ventilation in patients with symptomatic heart failure and reduced ejection fraction when contraindicated, and escalate urgently for awake hypercapnia, progressive weakness or inability to maintain ventilation.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v139_gen_03": "Begin with output, duration, wound status and systemic losses. Low-output leaks often respond to drainage, pressure used cautiously, a low-fat medium-chain-triglyceride or enteral strategy, electrolyte and protein replacement, and sometimes octreotide. Persistent high-output leakage, skin-flap compromise, infection, respiratory effects or nutritional decline should trigger early lymphangiography with embolization or operative exploration and ligation rather than serial dietary changes. The operative plan should account for the variable thoracic-duct arch and protect the nearby phrenic nerve, carotid sheath and pleura.",
    "v146_ped_12": "Do not wait for conventional pure-tone responses if development or behavior makes them unreliable. Combine tympanometry, OAEs and frequency-specific ABR or ASSR—using natural sleep or appropriately planned sedation—to estimate ear-specific thresholds and distinguish conductive, cochlear and auditory-neural patterns. Fit amplification or provide hearing access from the best defensible physiologic estimate, then repeat behavioral testing as the child matures. Etiologic imaging, congenital-infection testing and genetics are selected from the hearing phenotype; they should not delay language access and early-intervention referral.",
    "v136_rhi_16": "Persistent obstruction after turbinate reduction should prompt a new valve examination rather than more turbinate removal. Observe the lateral wall during quiet and deep inspiration, localize internal versus external collapse, and compare improvement with modified Cottle or targeted sidewall support while inspecting the septum and mucosa. Dynamic inspiratory narrowing identifies a structural sidewall problem that turbinate surgery cannot correct and may make more apparent by changing airflow. Treatment should restore valve support with a lesion-specific maneuver rather than create additional dryness or empty-nose symptoms through repeat reduction.",
    "v138_hn_03": "A young patient, bilateral or multifocal paragangliomas, family history of paraganglioma or pheochromocytoma, prior tumors, or a secretory phenotype should prompt genetic counseling and germline testing, particularly for SDHx-associated disease. Ask specifically about head-and-neck, adrenal and thoracoabdominal tumors in relatives, not merely 'thyroid cancer.' The result can expand whole-body biochemical and imaging surveillance, identify renal or other syndrome-associated risks, alter the threshold for observation versus intervention, and trigger cascade testing of relatives.",
    "v139_ped_09": "Bilateral atresia creates bilateral conductive deprivation during a critical language period, so bone-conduction hearing access should be provided in infancy rather than waiting for auricular reconstruction or atresiaplasty. Confirm cochlear reserve, fit and verify a softband or adhesive device, monitor wear time and speech-language development, and involve early-intervention services. Definitive implant or canal surgery is a later candidacy decision based on anatomy, age and reconstructive sequencing; it should not postpone early auditory stimulation.",
    "v141_oto_06": "A small, isolated tegmen defect without large encephalocele may be repaired transmastoid, especially when mastoid disease also needs treatment. Multiple, medial, broad tegmen defects, limited transmastoid access or a substantial encephalocele favor a middle-fossa approach for broad extradural exposure and multilayer repair; combined approaches help when both mastoid source control and superior access are needed. Hearing status, ossicles, prior surgery, intracranial-pressure physiology and surgeon expertise also matter. The route should permit safe reduction of nonviable tissue and durable multilayer closure without avoidable temporal-lobe or labyrinthine injury.",
    "v144_rh_10": "Treating turbinate tissue alone will not correct a fixed septal bottleneck. Map whether the deviation is caudal, dorsal, high, posterior or associated with an internal-valve problem, and plan septoplasty or septorhinoplasty that preserves dorsal and caudal support while addressing the turbinate only to the extent it independently contributes. A severe caudal deviation may require batten grafting, repositioning or extracorporeal reconstruction rather than simple submucous excision. Counsel that unrecognized valve collapse can leave obstruction despite technically adequate septal and turbinate work.",
    "v174_oto_sbtumor_app": "Angiography is useful when imaging suggests a highly vascular skull-base tumor, carotid encasement, uncertain vessel of origin, planned arterial sacrifice or a need to define collateral circulation. Preoperative embolization is considered when accessible feeding vessels can be treated safely and reduced blood loss will materially improve resection; it is not routine for every lateral skull-base tumor. The decision must account for dangerous external-to-internal carotid anastomoses and risks of stroke, cranial-neuropathy ischemia, dissection and nontarget embolization. Balloon-occlusion testing or reconstruction planning may be needed when carotid sacrifice is plausible.",
    "v175_oto_tmperf_app": "A conductive loss larger than expected for the perforation, marked ossicular discontinuity pattern, vertigo, sensorineural loss, facial weakness or temporal-bone fracture raises concern beyond a simple tympanic-membrane defect. Bedside tuning forks and complete audiometry help separate conductive and cochlear injury; CT is reserved for suspected fracture, ossicular disruption, foreign body or other structural complication. Sudden sensorineural loss or persistent vertigo requires urgent inner-ear assessment, while delayed tympanoplasty planning should include possible ossicular exploration rather than promising that membrane closure alone will normalize hearing.",
    "v222_hn_cbp_fnd": "Ask about early age at presentation; bilateral, multifocal or recurrent paragangliomas; pheochromocytoma; and relatives with head-and-neck, adrenal, thoracic or abdominal paragangliomas. These features increase concern for SDHx or another hereditary syndrome and warrant genetic counseling and germline testing. Symptoms of catecholamine excess should prompt biochemical testing before intervention even though most carotid-body tumors are nonsecretory. A pathogenic result changes surveillance beyond the neck and supports cascade testing of relatives.",
    "v244_ped_bca_app": "Acute infection replaces delicate tract planes with edema, friable tissue, abscess and adherence to adjacent nerves and vessels, so the epithelial tract may be impossible to distinguish safely. Drain an abscess and treat infection first; defer definitive excision until inflammation resolves unless uncontrolled sepsis or airway compromise requires immediate source control. Recurrent incision and drainage can add scar and make later dissection harder. At definitive surgery use the expected embryologic course and any skin or pharyngeal opening to guide complete removal while protecting the facial, hypoglossal, glossopharyngeal and recurrent laryngeal nerves as appropriate to anomaly type.",
    "v245_ped_micro_snr": "Poor atresiaplasty anatomy—unfavorable middle-ear space, ossicles, facial-nerve course or pneumatization—lowers the chance of durable canal patency and useful hearing while increasing facial-nerve, restenosis and chronic-cavity risk. Counseling should shift toward verified nonsurgical bone-conduction access and, when age and anatomy permit, an implantable bone-conduction system. Coordinate device position and timing with microtia reconstruction so an implant incision or fixture does not consume skin or vascular territory needed for the auricular framework.",
    "v247_ped_cleft_fnd": "The greater palatine neurovascular bundle exits the greater palatine foramen and supplies commonly elevated hard-palate mucoperiosteal flaps. Preserve the pedicle during incision, elevation and mobilization; tension, cautery or tearing can ischemically compromise the flap and promote fistula. Its position also limits medial advancement until the bundle is mobilized safely. Nasopalatine contribution anteriorly and the levator and tensor relationships posteriorly remain relevant, but the greater palatine bundle is the principal pedicle at risk in standard two-flap palatoplasty.",
    "v248_ped_sleep_snr": "Chronic insufficient sleep and untreated OSA can both shorten sleep latency and produce sleep-onset REM, creating a false narcolepsy-like MSLT. Document adequate, regular sleep with diary and preferably actigraphy for the preceding period, stabilize the circadian schedule, treat clinically important sleep-disordered breathing, and review REM-modulating or sedating medications before testing. The MSLT must follow an adequate attended polysomnogram. If these prerequisites are not met, correct them and repeat or defer the study rather than interpreting a short latency as primary hypersomnolence.",
    "v261_fpt_scar_app": "Z-plasty is useful when a mature linear scar is contracted, maloriented across relaxed skin-tension lines, tethering a free margin or producing a web; it lengthens and redirects the central limb. Geometric broken-line closure can camouflage a conspicuous long straight scar on an appropriate broad surface. Neither is needed for an immature, flat, well-oriented scar likely to improve with time, and both add incision length and flap-tip ischemia risk. Correct hypertrophy, keloid biology, infection and tension first rather than using rearrangement as a universal scar treatment.",
    "v266_sleep_central_events_fnd": "A mixed apnea begins with absent airflow and absent inspiratory effort, then respiratory effort resumes while airflow remains obstructed before the event ends. That sequence demonstrates both unstable ventilatory drive and collapsible upper airway. The central-apnea index counts central apneas, not the central portion of every mixed event, so review raw effort channels and the laboratory's scoring rather than inferring mechanism from AHI alone. Numerous mixed events may influence PAP titration and follow-up but do not automatically establish primary central sleep apnea.",
    "v266_sleep_central_events_app": "Review awake or morning blood gas or bicarbonate for chronic CO2 retention, spirometry and lung volumes for obstructive or restrictive disease, respiratory-muscle strength when neuromuscular weakness is possible, medication and opioid exposure, and relevant cardiac or neurologic findings. Sustained nocturnal CO2 elevation or awake hypercapnia favors ventilatory support rather than treating only scored apneas. Correct reversible depressants and pulmonary disease, and select CPAP, bilevel support with an appropriate backup strategy, oxygen or another modality from the mechanism; progressive weakness or daytime ventilatory failure warrants urgent pulmonary support.",
    "v136_oto_16": "Risk rises with another ototoxin—especially loop diuretics, additional aminoglycosides or platinum chemotherapy—and with renal dysfunction, high cumulative dose, prolonged exposure, sepsis, prior cochlear injury and intense noise. Review the complete medication and exposure list rather than the named drug alone, obtain risk-appropriate baseline audiometry and monitor high frequencies or OAEs when feasible. A threshold shift should prompt rapid discussion of dose, interval or alternative therapy while preserving the antimicrobial or oncologic objective.",
    "v137_tps_07": "RET genotype defines risk category and expected tempo of medullary thyroid carcinoma, so prophylactic thyroidectomy timing is variant-specific rather than uniform. Highest-risk variants generally require surgery in early childhood or infancy, while moderate-risk variants can often be timed using age, basal or stimulated calcitonin, ultrasound and family phenotype. Screen for pheochromocytoma first whenever age and genotype make it plausible and address it before thyroid surgery. The operative extent and node evaluation depend on biochemical or structural evidence of established disease, not genotype alone.",
    "v138_lar_16": "Stroboscopy reconstructs an apparent slow-motion cycle by sampling successive periods; it therefore requires sufficiently regular fundamental frequency. With severe aperiodicity, the flashes cannot synchronize reliably and the displayed wave, symmetry or apparent immobility may be an artifact rather than true cycle-to-cycle behavior. Use real-time flexible examination for gross motion and consider high-speed videoendoscopy or videokymography when detailed vibration matters. Do not make a lesion-specific or paresis diagnosis from an unstable strobe pattern alone.",
    "v139_ped_15": "Flexible nasoendoscopy directly shows the velopharyngeal closure pattern during connected speech: coronal, sagittal, circular or circular with Passavant ridge. It estimates gap size and location, lateral-wall contribution and whether a fistula or adenoid pad affects closure, allowing the team to match a procedure to the physiologic deficit. Interpretation requires representative speech with a speech-language pathologist and must be integrated with perceptual resonance and articulation assessment; compensatory articulation can make an anatomically useful study misleading.",
    "v141_slp_05": "Desired HNS recruitment is comfortable forward protrusion or stiffening that enlarges the retrolingual airway. Retraction, strong lateral deviation, tongue curling, floor-of-mouth pulling, painful contraction or minimal visible movement despite rising amplitude suggests poor electrode recruitment or an unfavorable configuration. Reprogram electrode configuration, pulse width, rate or amplitude and reassess comfort and airway effect rather than simply increasing voltage. Persistent abnormal motion should also prompt evaluation of lead integrity, nerve function and device position.",
    "v143_fpt_03": "When the mandible and occlusion are comminuted or unreliable, they cannot serve as the sole bottom-up template. Establish a stable cranial reference first—often the frontal bar and lateral orbital or zygomatic framework—then reconstruct facial width, projection and vertical height toward the central midface while rebuilding the mandibular arch from reproducible posterior and basal segments when possible. Dental models, virtual planning and temporary external references may help. The sequence must be individualized to whichever facial unit remains stable rather than forcing teeth into a false preinjury relationship.",
    "v145_lar_08": "Underlying paresis is suggested by true-fold bowing or shortened tone, incomplete closure, phase or amplitude asymmetry, reduced mucosal-wave excursion, arytenoid height or rotation differences, and compensatory supraglottic squeeze that is asymmetric or task-dependent. No single stroboscopic sign proves neuropathy. Correlate with perceptual weakness, swallowing symptoms and motion across tasks; use laryngeal EMG or imaging when etiology, prognosis or treatment would change. Treating the visible tension alone can fail if it is compensation for glottic insufficiency.",
    "v146_ped_16": "Infants with unilateral immobility may present less with a recognizable hoarse speaking voice and more with weak or breathy cry, coughing or desaturation during feeds, recurrent pneumonia, poor weight gain or subtle stridor. Flexible laryngoscopy establishes side and position, while an instrumental swallow assessment is often needed because aspiration may be silent. Review birth, cardiac surgery and neurologic history and image along the nerve course selectively. Management prioritizes safe feeding and growth while monitoring recovery; injection augmentation is considered when glottic insufficiency causes consequential aspiration or voice impairment.",
    "v175_oto_ototox_app": "Renal dysfunction reduces drug clearance and raises exposure; cumulative and repeated aminoglycoside dosing increases cochlear and vestibular injury, especially with concurrent loop diuretics, platinum therapy, prior hearing loss or critical illness. Verify renal-adjusted dosing and serum levels when applicable, review all ototoxins and obtain baseline and serial high-frequency audiometry or OAEs. New oscillopsia, imbalance or threshold shift should trigger prompt medication reassessment and vestibular or hearing rehabilitation—not reassurance based on a normal low-frequency screening test.",
    "v176_oto_vr_app": "New brief vertigo triggered by rolling, lying back or looking up, with a canal-specific positional nystagmus on Dix-Hallpike or supine-roll testing, suggests secondary BPPV superimposed on the original vestibular loss. Treat the involved canal with a repositioning maneuver before escalating generic habituation. Direction-changing gaze-evoked nystagmus, new neurologic deficits, inability to walk or a pattern inconsistent with canal physiology is not BPPV and should redirect evaluation toward central disease.",
    "v243_ped_vfi_fnd": "Ask about prematurity and traumatic or difficult delivery; PDA ligation and other cardiothoracic surgery; prolonged or difficult intubation; neck, esophageal or airway surgery; and known cranial neuropathy. Neurologic causes include Chiari malformation, hydrocephalus, brainstem or neuromuscular disease, especially with bilateral immobility. Also review feeding, aspiration and congenital syndromic features. The history guides imaging from brainstem through the vagal and recurrent-laryngeal-nerve course rather than ordering the same study for every child.",
    "v253_lar_mbs_fnd": "An MBS may include a brief screening view of cervical or thoracic esophageal transit, but it is optimized for oral and pharyngeal swallowing under time and radiation constraints. It does not provide the full column distention, multiple projections, prolonged observation, mucosal assessment or standardized maneuvers of a diagnostic esophagram. A normal screen therefore does not exclude a distal ring, stricture, diverticulum, reflux-related problem or motility disorder; persistent esophageal symptoms require dedicated GI or radiographic evaluation.",
    "v253_lar_mbs_app": "If symptoms localize to distal sticking, regurgitation or obstruction despite a pharyngeal abnormality on MBS, obtain a dedicated barium esophagram—often including a tablet when safe—and refer for endoscopy to assess mucosal or structural disease. High-resolution manometry is added when motility or outflow obstruction remains likely, with reflux testing selected by phenotype. Do not assume that treating pharyngeal residue explains simultaneous distal symptoms or that the limited MBS esophageal screen excludes a second lesion.",
    "v253_lar_mbs_snr": "Continued oral intake is unsafe when aspiration remains frequent or large despite tested strategies, aspiration is silent with poor clearance, secretion control is profoundly impaired, oxygenation or respiratory status deteriorates, or the patient cannot follow the only effective maneuver. Recurrent aspiration pneumonia, severe fatigue, inadequate nutrition or hydration and absent protective cough further lower the threshold for temporary nonoral support. A feeding tube does not eliminate salivary or reflux aspiration, so pair the decision with secretion, airway and rehabilitation planning and repeat assessment when physiology changes.",
}


def apply_daily_curriculum_quality_v375(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if not override:
            continue
        prompt, answer = override
        item["daily_prompt"] = prompt
        item["prompt"] = prompt
        item["answer"] = answer
        changed += 1
    return changed


def install_daily_curriculum_quality_v375(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v375():
        items = original_get_items()
        apply_daily_curriculum_quality_v375(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v375

    def adaptive_question_v375(item):
        return item.get("daily_prompt") or item.get("prompt") or ""

    app_module._adaptive_question = adaptive_question_v375

    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1

    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119

    return {
        "daily_pairs_repaired": len(DAILY_OVERRIDES),
        "curveball_answers_repaired": repaired,
    }
