"""Thirteenth-order Daily Curriculum residual safety-boundary repairs."""


DAILY_OVERRIDES = {
    ("Acute / Chronic Laryngopharyngitis", "localize"): (
        "How do duration, distribution, fold motion, focal lesions, systemic symptoms, and exposure history localize laryngopharyngeal inflammation without mistaking malignancy, paresis, or another disorder for laryngitis?",
        "Acute diffuse erythema and edema after viral symptoms or heavy voice use usually localizes to a self-limited inflammatory process, but appearance alone is nonspecific. Document tobacco and inhalational exposure, medication use, immune status, voice demand, swallowing, reflux symptoms and time course, then examine fold motion and the entire mucosal surface. A focal ulcer, leukoplakia, mass, unilateral stiffness, impaired motion, neck node, hemoptysis, weight loss, progressive dysphagia or persistent dysphonia should redirect evaluation toward tissue diagnosis, imaging, neurologic disease or another cause rather than a chronic laryngitis label.",
    ),
    ("Acute / Chronic Laryngopharyngitis", "operate"): (
        "When does suspected laryngopharyngitis require operative examination or biopsy, and how should tissue be obtained without causing unnecessary vibratory scar?",
        "Uncomplicated diffuse inflammation is treated by removing the demonstrated cause, supportive care and follow-up, not routine microlaryngoscopy. Operative examination is appropriate for a persistent or progressive focal lesion, suspicious vascularity, ulceration, leukoplakia, focal stiffness, unexplained impaired motion, airway concern, or inadequate office visualization when pathology will change management. Map the lesion, obtain representative depth from the suspicious region, orient and label specimens, and preserve uninvolved epithelium and superficial lamina propria when oncologically safe. A nondiagnostic superficial sample should not falsely reassure a clinically concerning lesion.",
    ),
    ("Acute / Chronic Laryngopharyngitis", "teach"): (
        "How would you teach laryngopharyngitis as a descriptive inflammatory phenotype rather than a diagnosis that automatically justifies antibiotics, steroids, or reflux therapy?",
        "Begin with cause and time course: viral infection, phonotrauma, smoke or chemical exposure, inhaled medication, candidiasis, allergy, bacterial disease, immune dysfunction and specific reflux-mediated injury require different evidence and treatment. Erythema and edema are common, observer-dependent findings and do not prove reflux or bacterial infection. Use symptoms, exposure history, motion, stroboscopy and response over time to narrow the mechanism. Persistent dysphonia or a focal, unilateral, stiff, ulcerated or progressive abnormality must reopen the differential for neoplasm, paresis, scar or systemic disease rather than accumulating empiric medications.",
    ),
    ("Branchial Cleft Anomalies", "workup"): (
        "How should age, location, infection, tract opening, imaging, and adult malignancy risk shape the workup of a suspected branchial cleft anomaly?",
        "Map the lesion relative to parotid, sternocleidomastoid, carotid sheath, pharynx, thyroid and external or internal openings, using ultrasound for selected superficial pediatric masses and contrast CT or MRI for deep, infected, recurrent or surgically complex disease. First-cleft lesions require attention to parotid and facial-nerve relationships; second-cleft tracts may pass between carotids toward the tonsillar fossa; recurrent low-neck infection may indicate a pyriform sinus tract. In an adult, do not accept a lateral cystic-mass label until metastatic HPV-associated or other head-and-neck carcinoma has been deliberately excluded.",
    ),
    ("Branchial Cleft Anomalies", "teach"): (
        "How would you teach branchial cleft anomalies by embryologic tract and operative danger rather than memorizing cyst positions?",
        "Link each lesion to its expected course. First-cleft anomalies involve the external auditory canal or parotid region and may cross the facial nerve; second-cleft tracts travel from the lateral neck between carotid branches toward the tonsillar fossa; third- and fourth-pouch lesions can present as recurrent lower-neck or thyroid infection with a pyriform sinus opening and recurrent-laryngeal-nerve or mediastinal relationships. Treat acute infection first when safe, define the internal source, and excise or obliterate the complete pathway. In adults, cystic nodal metastasis remains a competing diagnosis until proven otherwise.",
    ),
    ("Endoscopic Maxillary Antrostomy", "localize"): (
        "Which uncinate, natural ostium, orbit, lacrimal, accessory-ostium, and dental relationships must be localized before a maxillary antrostomy?",
        "Identify the uncinate attachment and infundibulum, then find the true natural maxillary ostium rather than entering through a fontanelle accessory opening. The lamina papyracea and orbital floor define the lateral-superior danger, while the nasolacrimal duct lies anteriorly and dental roots and alveolar recess are inferior. Disease may extend into prelacrimal, lateral or odontogenic compartments not reached by a routine middle-meatal opening. Preoperative CT should also reveal hypoplastic sinus, silent-sinus remodeling, Haller cells, prior surgery and anatomic asymmetry that change orientation and access.",
    ),
    ("Endoscopic Maxillary Antrostomy", "manage"): (
        "How should pathology and anatomy determine the size and position of a maxillary antrostomy while preventing recirculation, orbital injury, and unnecessary mucosal loss?",
        "Open the natural ostium and connect any accessory opening into one common physiologic drainage pathway; leaving separated openings can create mucus recirculation. Enlarge only as needed for ventilation, topical access, fungal debris, tumor, odontogenic source or instrument reach, while preserving healthy mucosa and protecting orbit and nasolacrimal duct. Address the dental, foreign-body or neoplastic source rather than treating the sinus opening as definitive therapy. Persistent symptoms after surgery should prompt review for missed natural ostium, scar, odontogenic disease, recirculation or a lateral recess that the chosen corridor cannot adequately reach.",
    ),
    ("Ethmoidectomy", "workup"): (
        "What must be reconstructed from preoperative CT before ethmoidectomy to anticipate skull-base, orbital, vascular, optic-nerve, and frontal-recess hazards?",
        "Review each side independently for skull-base height and slope, Keros depth, asymmetry, dehiscence, lamina papyracea integrity, orbital prolapse, anterior ethmoid artery course, supraorbital ethmoid cells, frontal cells, Onodi cells and sphenoid-optic or carotid relationships. Identify prior surgery, osteitis, tumor, fungal disease and distorted middle-turbinate landmarks. Trace the natural drainage pathways rather than counting cells. A low or dehiscent roof, suspended artery, medially displaced orbit or posterior cell around the optic nerve should change instrument direction, dissection extent and whether image guidance or a different approach is warranted.",
    ),
    ("Inferior Turbinate Hypertrophy", "localize"): (
        "How do decongestion response, bony contour, mucosal disease, nasal-valve behavior, septal anatomy, and side-to-side symptoms identify whether the inferior turbinate is actually the dominant obstruction?",
        "Examine the airway before and after topical decongestion. A large reversible change supports mucosal congestion from rhinitis, while persistent bulk may reflect bone, fibrosis or compensatory hypertrophy. Observe the internal and external valves during inspiration, septal deviation, head position, nasal cycle, polyps and posterior choana with endoscopy when indicated. A turbinate can look large because the opposite septum displaces airflow, and a small-appearing cavity can still fail dynamically at the valve. Treatment should target the symptomatic bottleneck rather than reducing every radiographically or visually prominent turbinate.",
    ),
    ("Inferior Turbinate Hypertrophy", "workup"): (
        "What history and examination distinguish inflammatory turbinate congestion from fixed hypertrophy, valve collapse, septal obstruction, medication injury, or another nasal process?",
        "Clarify laterality, variability, allergens, irritants, exercise, sleep, prior surgery, trauma and use of topical decongestants, cocaine or intranasal medication. Perform anterior examination and dynamic valve assessment before and after decongestion, documenting mucosal color, edema, crusting, septum and airflow response. Endoscopy evaluates posterior hypertrophy, polyps, purulence, masses and nasopharynx. Allergy testing or CT is selective when it changes treatment; routine imaging is unnecessary for isolated straightforward obstruction. Unilateral bleeding, pain, progressive obstruction or a mass requires a different workup than presumed rhinitis.",
    ),
    ("Inferior Turbinate Hypertrophy", "manage"): (
        "How should medical response, tissue composition, coexisting septal or valve disease, and empty-nose risk determine whether and how the inferior turbinate is reduced?",
        "Treat the demonstrated inflammatory driver first with saline, appropriate intranasal therapy, allergen or irritant control and withdrawal of rebound-producing decongestants. Offer reduction for persistent function-limiting hypertrophy after the turbinate is shown to contribute meaningfully to obstruction. Choose a mucosa-preserving submucosal, radiofrequency, microdebrider, outfracture or limited bony technique matched to tissue and anatomy, and correct significant septal or valve disease when it is part of the bottleneck. Avoid aggressive resection that sacrifices sensation, humidification and airflow regulation and can create chronic crusting or empty-nose symptoms.",
    ),
    ("Microtia / Aural Atresia", "manage"): (
        "How should hearing access, canal anatomy, cholesteatoma risk, auricular reconstruction, age, and family communication goals be coordinated for microtia with aural atresia?",
        "Confirm hearing in both ears early and provide nonsurgical bone-conduction access or another appropriate device during language development without waiting for cosmetic reconstruction. Evaluate syndromic and craniofacial findings and monitor a stenotic canal for cholesteatoma. Obtain temporal-bone CT when an anatomy-dependent surgical decision is approaching, then assess atresiaplasty candidacy, bone-conduction implantation and expected maintenance. Choose prosthetic, autologous cartilage or alloplastic auricular reconstruction with the family first because incision, vascularized tissue and timing interact with canal surgery. Coordinate otology, facial plastics, audiology and communication support longitudinally.",
    ),
    ("Petrous Apex Lesions", "teach"): (
        "How would you teach petrous-apex lesions by imaging behavior, symptoms, natural history, and available drainage or resection corridors?",
        "Start with CT density and bone behavior, then MRI T1, T2, enhancement and diffusion. Cholesterol granuloma is typically expansile and T1/T2 bright; cholesteatoma restricts diffusion; trapped fluid follows fluid signal without aggressive expansion; tumor, infection and inflammatory disease have different enhancement and erosion patterns. Relate findings to hearing, vestibular symptoms, headache and cranial neuropathies. Stable incidental lesions may be observed. When treatment is necessary, choose a durable aerated drainage route or resection corridor based on diagnosis, carotid and cochlear anatomy, hearing status and access—not simply the shortest line to the lesion.",
    ),
    ("Petrous Apex Lesions", "manage"): (
        "When should a petrous-apex lesion be observed, drained, biopsied, or resected, and how do hearing and corridor anatomy choose the approach?",
        "Observe a confidently characterized, stable, asymptomatic lesion with serial symptom and imaging follow-up. Drain an expanding symptomatic cholesterol granuloma through a durable transsphenoidal, infracochlear, infralabyrinthine or other aerated corridor when anatomy permits; diffusion-restricting cholesteatoma generally requires epithelial eradication rather than simple drainage. Biopsy or resect an indeterminate, growing, enhancing or neurologically progressive lesion when tissue will change care. Preserve hearing and cranial nerves when feasible, but carotid position, cochlear reserve, prior surgery and skull-base extension may require a different corridor. New diplopia, facial weakness or lower-cranial neuropathy accelerates evaluation.",
    ),
    ("Supraglottoplasty", "localize"): (
        "Which dynamic supraglottic structure is collapsing in laryngomalacia, and what alternative airway level or comorbidity would make supraglottoplasty insufficient?",
        "Flexible laryngoscopy should identify inspiratory prolapse of shortened aryepiglottic folds, redundant arytenoid mucosa, posterior epiglottic collapse or a combination, while documenting vocal-fold motion, secretion control and synchronous lesions. Supraglottoplasty targets only the obstructing supraglottic tissue. Subglottic stenosis, vocal-fold immobility, tracheomalacia, vascular compression, neurologic hypotonia, aspiration and significant pulmonary or cardiac disease can produce persistent symptoms despite technically adequate surgery. Operate for severe obstruction, feeding compromise, hypoxemia or growth failure after defining the dominant physiology, and preserve protective mucosa to limit aspiration and scar.",
    ),
    ("Tracheomalacia / Bronchomalacia", "workup"): (
        "How should dynamic bronchoscopy, respiratory phase, cardiovascular imaging, pulmonary disease, and symptoms define the level and mechanism of tracheobronchomalacia?",
        "Characterize barking cough, recurrent infections, cyanotic spells, extubation failure, secretion retention and positional or feeding triggers, then assess every airway level during spontaneous breathing with dynamic bronchoscopy when feasible. Record anterior vascular compression, posterior membranous intrusion, focal versus diffuse collapse, bronchial involvement and response to positive pressure. Dynamic CT or MRI and echocardiographic or vascular imaging define rings, slings and postoperative cardiovascular relationships. Evaluate aspiration, reflux only when demonstrated, small-airway disease, neuromuscular weakness and infection. A percentage collapse without symptoms or standardized conditions should not alone dictate surgery.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v260_fpt_tip_app": "Deprojection can be achieved by reducing an overlong caudal septum or anterior septal angle, setting back or repositioning the medial crura, modifying domal or lateral-crural geometry, or using controlled tongue-in-groove and septal-extension maneuvers. Each change also affects rotation, columellar show, nasolabial angle and valve support. Preserve or rebuild a stable tripod and avoid simple cartilage excision that weakens the tip. Plan deprojection from profile and base relationships rather than chasing one measurement.",
    "v262_fpt_hair_fnd": "FUE removes individual follicular units through many small punches, avoiding a linear scar but risking diffuse donor thinning and transection if overharvested. FUT removes a strip that is dissected microscopically into grafts, often producing a large yield while leaving a linear scar whose width depends on laxity, tension and healing. Donor density, curl, caliber, hairstyle, prior scars and anticipated future procedures matter more than calling either technique scarless. Both redistribute a finite donor supply.",
    "v262_fpt_hair_snr": "Beard or body hair may supplement scalp donor supply when scalp reserve is inadequate, prior harvest is extensive, and the alternate hair has useful caliber, curl, growth length and survival characteristics. It is usually better for density behind a natural scalp-hair hairline than for the leading edge. Growth cycle, texture, color, extraction difficulty and cosmetic behavior differ from scalp hair, so test harvesting and conservative expectations are essential; it cannot be counted as interchangeable graft inventory.",
    "v267_sleep_circ_app": "Rotating shifts repeatedly move the required sleep window, so the same patient may alternate between circadian misalignment, acute sleep restriction and recovery sleep. A single weekend history or PSG may therefore misrepresent the usual problem. Map work and sleep across several weeks with logs or actigraphy, light exposure, caffeine and naps. Treatment must match the actual rotation and may include anchored sleep, timed light or darkness and occupational modification rather than one fixed bedtime prescription.",
    "v267_sleep_narc_app": "REM-suppressing antidepressants, stimulants, wake-promoting agents and some sedatives alter sleep latency or suppress sleep-onset REM; abrupt withdrawal can cause REM rebound and a false-positive MSLT. Antihistamines, cannabis and other substances also affect sleepiness. Review every prescription and nonprescription agent with the sleep clinician and plan a safe, sufficiently long washout based on half-life and psychiatric risk. Never stop essential medication solely to satisfy a test protocol without prescriber coordination.",
    "v116-oto-03": "Concern for posterior-circulation ischemia rises with direction-changing gaze-evoked nystagmus, skew, a normal head impulse in continuous acute vestibular syndrome, severe truncal ataxia, new focal deficit, headache or neck pain, vascular risk, or acute hearing loss suggesting AICA involvement. Early posterior-fossa MRI can be falsely negative, so a compelling bedside syndrome warrants urgent stroke evaluation and repeat or vascular imaging as appropriate. Classic labyrinthitis should have cochlear symptoms but not central ocular-motor or focal neurologic signs.",
    "v11_ped_05": "Establish whether the midline mass is the child's only functioning ectopic thyroid before excision. Confirm orthotopic thyroid anatomy with expert ultrasound and assess thyroid function; radionuclide imaging or additional evaluation is used when anatomy remains uncertain. Removing the sole thyroid tissue creates permanent hypothyroidism. Once normal thyroid is clearly present, the usual Sistrunk pathway can proceed after infection control, with separate evaluation of any solid component or suspicious node.",
    "v245_ped_neck_fnd": "Do not excise until you know whether the presumed thyroglossal lesion represents the patient's only thyroid tissue. Confirm an orthotopic gland with high-quality ultrasound, check thyroid function, and use radionuclide or specialist-directed imaging when the normal gland is absent or equivocal. Ectopic thyroid can mimic a cyst and may be the sole functioning source. If orthotopic thyroid is confirmed, proceed according to infection status and standard Sistrunk principles rather than simple cyst removal.",
    "v136_oto_14": "Rapidly progressive or fluctuating bilateral sensorineural loss over days to months, asymmetric change, vestibular symptoms, systemic autoimmune features and steroid responsiveness can raise AIED concern. Routine presbycusis is slowly progressive, symmetric and high-frequency predominant without inflammatory fluctuation. Red flags for another cause include unilateral tinnitus, retrocochlear signs, ototoxic exposure, infection, conductive findings or focal neurologic deficits. Document serial audiograms and targeted systemic evaluation before exposing an older patient to prolonged immunosuppression.",
    "v138_hn_19": "The classic high-risk postoperative findings supporting concurrent chemoradiation are positive surgical margins and extranodal extension, assuming the patient can tolerate systemic therapy. Other adverse features—multiple nodes, pT3-4 disease, perineural or lymphovascular invasion, close margins and selected subsite factors—commonly support postoperative radiation but do not automatically carry the same evidence for added chemotherapy. Review pathology in a multidisciplinary setting because re-resection, performance status, renal and hearing function and treatment timing affect the final plan.",
    "v138_hn_23": "Leakage through the prosthesis usually reflects valve failure, debris, biofilm or an incorrectly functioning device and often improves with cleaning or replacement. Leakage around the prosthesis suggests an enlarged tract, poor sizing, tissue atrophy, infection, reflux-related inflammation or high pharyngoesophageal pressure and requires cause-directed tract management. A missing prosthesis raises aspiration and tract-closure risk. Distinguish these patterns before upsizing or removing the device, because the same visible leak has different treatment.",
    "v139_gen_07": "In severe malnutrition, give thiamine before and during feeding, correct major phosphate, potassium and magnesium deficits, and start calories cautiously with close fluid, glucose, electrolyte and cardiopulmonary monitoring. Advance in a controlled stepwise fashion rather than immediately delivering full estimated needs. Edema, arrhythmia, weakness, respiratory decline or falling phosphate signals refeeding physiology and should slow escalation while deficits are treated. Coordinate nutrition expertise; avoiding nutrition entirely also carries harm, so the solution is monitored restoration, not prolonged starvation.",
    "v139_ped_17": "Modifying factors can favor tonsillectomy below classic episode counts when infections are unusually severe or poorly tolerated, documentation is incomplete but disease burden is compelling, multiple antibiotic allergy or intolerance limits treatment, PFAPA is present, or more than one peritonsillar abscess has occurred. Shared decision-making should still consider natural improvement, missed school, family burden and operative risk. Snoring or tonsil size alone does not convert an infection indication into an obstructive one without separate assessment.",
    "v140_hn_10": "A segmental mandibulectomy creates a load-bearing bony defect, so reconstruction usually requires vascularized bone with enough length, height and skin or soft tissue for oral lining and external coverage. Fibula is versatile for long segments and implants; scapular system offers flexible bone and soft-tissue components; iliac crest provides height and contour in selected defects. Choose by defect location, condyle involvement, dentition, radiation, vessel status and donor function—not by a universal favorite flap.",
    "v144_oto_16": "Relapsing polychondritis can cause painful auricular chondritis that classically spares the lobule, external-canal narrowing, conductive loss and sometimes inner-ear dysfunction. Cogan syndrome combines inflammatory ocular disease, often interstitial keratitis, with rapidly progressive audiovestibular loss that can resemble Ménière disease. Either can threaten hearing and systemic organs. Examine the eye and cartilage pattern, document audiovestibular change and coordinate rheumatologic evaluation rather than treating recurrent ear inflammation as routine otitis externa.",
    "v144_rh_12": "Favor a combined or external route when the mucocele is far lateral or superior beyond safe endoscopic reach, separated by complex postoperative anatomy, associated with extensive bone or skin involvement, has an inaccessible thick wall or suspected neoplasm, or cannot be marsupialized into a durable nasal drainage pathway. Thin-cut CT and MRI when needed should define orbit and skull base. The goal remains safe complete drainage and surveillance, not external surgery solely because the lesion appears large.",
    "v145_hn_15": "Before radiation, complete dental evaluation and extract hopeless teeth with adequate healing time when oncologically feasible, initiate fluoride and oral-hygiene prevention, document baseline swallow and nutrition, and identify mandibular regions likely to receive high dose. Reconstruction should use well-vascularized tissue, achieve durable mucosal closure and position hardware away from tenuous irradiated coverage. Anticipated radiation also affects implant timing, salivary counseling and trismus prevention. Do not delay urgent cancer therapy for elective dental perfection; coordinate priorities explicitly.",
    "v145_lar_05": "Zenker diverticulum typically causes progressive dysphagia, regurgitation of undigested food, halitosis, gurgling, cough, aspiration and weight loss. Treatment divides the common wall and cricopharyngeal muscle through rigid or flexible endoscopic septotomy when exposure and pouch anatomy permit, or open diverticulectomy/diverticulopexy with myotomy when the pouch, neck mobility, dental exposure or recurrence favors it. Very small pouches can be difficult to expose endoscopically; frailty and pulmonary consequences matter as much as pouch size.",
    "v145_lar_11": "If the object fragments while obstructing a mainstem bronchus, maintain ventilation through the rigid bronchoscope, prevent distal migration, remove controlled pieces with appropriate forceps or basket, and repeatedly clear blood and secretions. Reinspect the obstructed side, distal bronchi and contralateral tree for retained fragments or a second object. Sudden inability to ventilate may require withdrawing the object and scope together, re-establishing the airway, or emergent thoracic assistance; evaluate afterward for perforation, pneumothorax and edema.",
    "v146_ped_10": "Narcolepsy is suggested by irresistible daily sleep attacks despite adequate opportunity for sleep, cataplexy triggered by emotion, sleep paralysis, hypnagogic or hypnopompic hallucinations, fragmented nighttime sleep and automatic behavior. In children it may present as irritability, hyperactivity or abrupt weight gain rather than a classic complaint of sleepiness. Confirm adequate sleep and treat OSA before PSG/MSLT interpretation, and distinguish cataplexy from syncope, seizure and ordinary weakness using awareness, trigger and recovery history.",
    "v146_ped_14": "Compensatory articulation, phonologic errors, childhood apraxia, dysarthria, language disorder and hearing-related speech delay will not resolve simply by narrowing the velopharyngeal port. VPI surgery addresses obligatory hypernasality, nasal emission and pressure-consonant weakness caused by inadequate closure; learned glottal stops or pharyngeal substitutions still require speech therapy. Define resonance, articulation, motor planning, hearing and closure pattern with the speech team before operating, because the wrong target can add OSA without improving intelligibility.",
}


def apply_daily_curriculum_quality_v381(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if override:
            prompt, answer = override
            item["daily_prompt"] = prompt
            item["prompt"] = prompt
            item["answer"] = answer
            changed += 1
    return changed


def install_daily_curriculum_quality_v381(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v381():
        items = original_get_items()
        apply_daily_curriculum_quality_v381(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v381
    app_module._adaptive_question = lambda item: item.get("daily_prompt") or item.get("prompt") or ""
    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1
    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119
    return {"daily_pairs_repaired": len(DAILY_OVERRIDES), "curveball_answers_repaired": repaired}
