"""Eighth-order Daily Curriculum answer-depth and curveball-fit repairs.

The prior semantic passes removed diagnosis-revealing and category-literal stems.
This layer targets the remaining cards where a broad, clinically useful question
still revealed only a short inherited pearl, plus curveballs whose fallback answer
described the parent topic rather than resolving the question on screen.
"""


DAILY_OVERRIDES = {
    ("Hearing Aids and Bone-Conduction Devices", "workup"): (
        "Before selecting a hearing device, which audiologic, anatomic, communication, and real-world performance data distinguish conventional amplification, CROS/BiCROS, bone-conduction, and implantable options?",
        "Obtain ear-specific air and bone thresholds, speech reception and word recognition, tympanometry when indicated, and unaided versus aided speech testing in conditions that resemble the patient's listening demands. Confirm whether the loss is conductive, sensorineural, mixed, or single-sided and whether an ear can physically and consistently use an air-conduction aid. Examine canal and middle-ear anatomy, review chronic drainage or prior surgery, and clarify communication goals, dexterity, cognition, occupation, and trial experience. Conventional aids require an aidable pathway; CROS routes sound without restoring binaural hearing; bone-conduction options bypass an unusable canal or middle ear; cochlear implantation is considered when appropriately fit amplification provides inadequate speech access.",
    ),
    ("Hearing Aids and Bone-Conduction Devices", "manage"): (
        "After a hearing device is fitted, how should benefit, comfort, adherence, and communication function be monitored, and what pattern should trigger refitting or a different technology?",
        "Verify the fitting objectively with real-ear or appropriate device measures and assess aided speech performance, comfort, retention, skin condition, daily use, and patient-reported communication benefit. Pair the device with communication strategies and auditory rehabilitation rather than judging success by gain alone. Troubleshoot occlusion, feedback, poor earmold fit, drainage, pressure injury, connectivity, and unrealistic expectations. Refit or change the pathway when optimized amplification remains intolerable or produces inadequate speech understanding, when anatomy prevents safe use, or when progressive loss moves the patient toward cochlear-implant or another implantable-device evaluation.",
    ),
    ("Ototoxic / Noise-Induced Hearing Loss", "workup"): (
        "In a patient exposed to an ototoxic drug or hazardous noise, what baseline and serial assessment detects injury early, and which change requires immediate coordination with the treating team?",
        "Document the agent or noise dose, duration, timing, renal function, concurrent ototoxins, prior hearing loss, tinnitus and vestibular symptoms. Obtain baseline conventional and extended high-frequency audiometry when feasible, with speech testing, OAEs or other protocol-specific measures for patients who cannot provide reliable thresholds. Compare serial results to the same baseline rather than waiting for symptomatic disability. A reproducible threshold shift, new tinnitus, oscillopsia or imbalance should prompt rapid confirmation and discussion of dose, interval, hearing protection or a less-toxic alternative while preserving the antimicrobial or oncologic objective.",
    ),
    ("Ototoxic / Noise-Induced Hearing Loss", "manage"): (
        "When early ototoxic or noise-related injury is detected, how do you reduce further damage without abandoning necessary treatment, and when should hearing or vestibular rehabilitation begin?",
        "Remove avoidable noise exposure, strengthen correctly fitted hearing protection, and review every ototoxic medication and renal-dose adjustment. For essential antimicrobial or oncologic therapy, communicate the documented change promptly so the prescribing team can weigh dose, schedule, serum monitoring, route, or an effective alternative; the ENT clinician should not stop lifesaving therapy unilaterally. Treat remediable conductive contributors, counsel about tinnitus and communication strategies, and introduce hearing aids, cochlear-implant evaluation, vestibular therapy, or fall-prevention support as soon as functional deficits emerge rather than waiting for the exposure course to end.",
    ),
    ("Ototoxic / Noise-Induced Hearing Loss", "teach"): (
        "How would you teach prevention and surveillance of ototoxic or noise-induced hearing loss from risk identification through an actionable threshold shift and long-term rehabilitation?",
        "Start by defining the hazard and the patient's susceptibility: cumulative dose or sound level, renal function, age, prior cochlear injury and simultaneous ototoxins all matter. Establish a reproducible baseline, monitor the frequencies and functions most likely to change first, and ask about tinnitus and vestibular symptoms. When a confirmed shift appears, communicate it while treatment can still be modified and balance hearing preservation against the indication for the exposure. Prevention, serial comparison, counseling and early rehabilitation form one pathway; a normal conversational-frequency screen does not exclude early injury.",
    ),
    ("Autoimmune Inner Ear Disease", "workup"): (
        "A patient has rapidly progressive or fluctuating sensorineural hearing loss: how do you evaluate possible autoimmune inner-ear disease without treating a nonspecific laboratory result as diagnostic?",
        "Define the tempo, laterality, fluctuation, vestibular symptoms and systemic inflammatory features, and document serial ear-specific audiograms. Exclude common and dangerous alternatives with examination and targeted testing, including sudden idiopathic loss, medication or noise toxicity, infection, Ménière phenotype, retrocochlear disease and other systemic causes. Laboratory studies should be selected from the history and rheumatologic phenotype because no single blood test confirms isolated autoimmune inner-ear disease. Treatment response may support but does not prove the diagnosis; atypical asymmetry, neurologic findings, poor response or continued decline should reopen the differential rather than reinforce the label.",
    ),
    ("Autoimmune Inner Ear Disease", "manage"): (
        "How should suspected autoimmune inner-ear disease be treated and monitored, and what should trigger a change in diagnosis, immunologic strategy, or hearing rehabilitation?",
        "Coordinate otology and, when systemic disease is plausible, rheumatology care. After documenting active decline and excluding major mimics, a time-limited corticosteroid trial may be considered with explicit medical-risk review and repeat audiometry using predefined response criteria. Avoid indefinite empiric steroids without objective benefit. Recurrent steroid-responsive loss may prompt specialist discussion of steroid-sparing therapy, but evidence and toxicity must be individualized. Continued decline, marked unilateral or retrocochlear features, or absent objective response should redirect the workup. Fit amplification early and refer for cochlear-implant evaluation when speech access remains poor despite optimized aids.",
    ),
    ("Autoimmune Inner Ear Disease", "teach"): (
        "How would you teach autoimmune inner-ear disease as a syndrome-of-exclusion pathway from hearing trajectory through treatment trial, objective reassessment, and rehabilitation?",
        "Teach the trajectory before the label: usually progressive or fluctuating sensorineural loss over days to months, often bilateral but asymmetric, with possible vestibular symptoms or systemic autoimmune clues. Confirm change with serial audiometry and investigate mimics according to the phenotype; do not use a positive inflammatory marker as a stand-alone diagnosis. If a medically appropriate treatment trial is used, define the audiometric endpoint and stop rule in advance. Objective nonresponse should weaken the hypothesis, while persistent disability should activate hearing-aid or cochlear-implant rehabilitation regardless of etiology.",
    ),
    ("CSF Otorrhea / Temporal Encephalocele", "manage"): (
        "Once temporal-bone CSF leakage or encephalocele is confirmed, how do defect anatomy, infection risk, hearing status, and intracranial-pressure physiology determine repair and follow-up?",
        "Treat meningitis or an acutely contaminated ear urgently and avoid routine tympanostomy for an unrecognized CSF effusion. Map the tegmen defect or defects with high-resolution CT and MRI, document hearing, and assess spontaneous-leak features associated with elevated intracranial pressure. A transmastoid approach may suit selected accessible defects; a middle-fossa or combined approach provides broader access for multiple, anterior, large, or encephalocele-associated defects. Use multilayer closure and preserve hearing when feasible. Confirm leak resolution and follow for recurrent effusion, meningitis, hearing change, repair failure, and untreated pressure physiology that can drive recurrence.",
    ),
    ("CSF Otorrhea / Temporal Encephalocele", "teach"): (
        "How would you teach temporal-bone CSF leak from the misleading middle-ear presentation through confirmation, anatomic repair selection, and recurrence prevention?",
        "Begin with the trap: persistent unilateral clear effusion, clear drainage after a tube, conductive loss or recurrent meningitis may be CSF rather than routine otitis media. Confirm suspicious fluid with a specific CSF marker when available, and pair temporal-bone CT with MRI to distinguish bony defects from encephalocele. Choose transmastoid, middle-fossa or combined repair from defect location, multiplicity, size, hearing and prior surgery. In spontaneous disease, investigate the elevated-intracranial-pressure phenotype because closing the visible hole without addressing the driving physiology leaves recurrence risk.",
    ),
    ("Vestibular Rehabilitation", "teach"): (
        "How would you teach vestibular rehabilitation as deficit-specific neuroplastic training, including exercise selection, expected symptom provocation, progression, and reasons to stop or reassess?",
        "First identify the treatable deficit: gaze instability calls for adaptation or substitution exercises, motion sensitivity for graded habituation, impaired stance or gait for balance and locomotor training, and canalithiasis for a repositioning maneuver rather than generic exercise. Set functional goals and prescribe a tolerable home dose that briefly provokes symptoms without causing prolonged decompensation or unsafe falls. Progress speed, visual complexity, head movement and surface demands as performance improves. New focal neurologic findings, direction-changing positional patterns, syncope, acute hearing change, severe headache or failure to progress should trigger diagnostic reassessment rather than simply increasing exercises.",
    ),
    ("Frontal Recess / Frontal Sinus", "workup"): (
        "Before frontal-sinus surgery, how should multiplanar CT be reconstructed to identify the drainage pathway, and which anatomic or disease feature changes the planned extent?",
        "Review thin-cut CT in sagittal, coronal and axial planes and trace the frontal drainage pathway around the agger nasi region, frontal cells, uncinate attachment, bulla, frontal beak, orbit and skull base. Compare sides and identify low or asymmetric skull base, dehiscence, osteitis, prior surgical distortion, retained cells and neo-osteogenesis. Confirm that symptoms correspond to objective frontal disease and that appropriate medical treatment has failed. A narrow pathway, extensive osteitis, mucocele, tumor, lateral disease, prior restenosis or distorted landmarks may require a wider or alternative approach; anatomy alone is not an indication for surgery.",
    ),
    ("Nasal Anatomy for Endoscopy", "workup"): (
        "During endoscopy and CT review, how do you confirm orientation in the middle meatus and sphenoethmoidal recess, and which variants must be recognized before instrumentation?",
        "Correlate the septum, floor, inferior and middle turbinates, uncinate, ethmoid bulla, basal lamella, superior turbinate, choana and sphenoethmoidal recess directly with multiplanar CT. Define the lamina papyracea laterally and skull base superiorly at every depth. Identify concha bullosa, paradoxical middle turbinate, uncinate attachment, Haller or Onodi cells, low or asymmetric fovea, dehiscent lamina, anterior ethmoid artery position and sphenoid septations near the carotid or optic canal. If the visual field and CT map do not agree, stop and reorient rather than assigning a normal variant to pathology.",
    ),
    ("Endoscopic Maxillary Antrostomy", "workup"): (
        "Before maxillary antrostomy, what must CT and endoscopy establish about the natural ostium, uncinate, orbit, dentition, and disease cause, and what finding should redirect the operation?",
        "Confirm an appropriate maxillary disease indication after medical therapy and review endoscopy for middle-meatal inflammation, purulence, scarring or tumor. On CT, define uncinate attachment and atelectasis, the natural ostium and infundibulum, Haller cells, orbital floor, nasolacrimal duct, accessory ostia, dental roots and odontogenic disease. A unilateral mass, bone erosion, silent-sinus anatomy, oroantral fistula, foreign material or dental source requires cause-specific planning rather than a routine antrostomy alone. Prior surgery that separated natural and accessory openings should prompt creation of one common drainage pathway to prevent mucus recirculation.",
    ),
    ("Endoscopic Maxillary Antrostomy", "teach"): (
        "How would you teach maxillary antrostomy from indication and natural-ostium identification through safe enlargement, recirculation prevention, and postoperative failure analysis?",
        "Start with the purpose: restore access and drainage for documented maxillary disease, not create the largest possible opening. Mobilize or remove the uncinate under direct control, identify the natural ostium rather than assuming an accessory opening is native, and enlarge it while protecting orbit, nasolacrimal duct and healthy mucosa. Join a clinically relevant accessory ostium to the natural opening so mucus does not cycle between them. At follow-up, persistent disease should prompt inspection for retained uncinate, missed natural ostium, recirculation, stenosis, dental source, foreign body or a diagnosis that antrostomy alone cannot treat.",
    ),
    ("Ethmoidectomy", "teach"): (
        "How would you teach ethmoidectomy as an orientation-dependent operation, including fixed boundaries, the basal-lamella transition, and immediate response to orbital or skull-base injury?",
        "Establish the lamina papyracea laterally, skull base superiorly and middle turbinate medially, then remove cells in a controlled sequence rather than following apparent cavities blindly. The basal lamella marks transition from anterior to posterior ethmoid, where sphenoid and Onodi relationships become relevant; CT predicts skull-base height, asymmetry and anterior ethmoid artery risk. Preserve landmarks and mucosa appropriate to the disease. Orbital fat, unexpected brisk bleeding or CSF requires an immediate stop, removal of traction or suction from the injury, reorientation, assessment of vision or intracranial risk, and deliberate repair or escalation.",
    ),
    ("Total Laryngectomy", "localize"): (
        "Before total laryngectomy, which tumor, pharyngeal, thyroid, tracheal, neurovascular, and reconstructive relationships determine resectability and the required extent?",
        "Map the primary across laryngeal subsites, pre-epiglottic and paraglottic spaces, cartilage and extralaryngeal soft tissue, and determine involvement of base of tongue, hypopharynx, cervical esophagus, thyroid, trachea, carotid space and prevertebral fascia. Define nodal disease and prior-treatment effects and assess how much pharyngeal mucosa will remain for closure. Subglottic or thyroid invasion, circumferential hypopharyngeal extension, carotid encasement, prevertebral fixation or a large irradiated mucosal deficit can change resection, neck treatment, thyroidectomy, tracheal length, reconstruction or candidacy. The permanent stoma separates pulmonary from upper aerodigestive anatomy.",
    ),
    ("Total Laryngectomy", "workup"): (
        "What preoperative oncologic, airway, swallowing, pulmonary, nutritional, thyroid, and communication assessment is required before total laryngectomy, and which finding changes the plan?",
        "Confirm pathology and stage with endoscopy and appropriate cross-sectional and distant imaging, documenting tumor extent, nodal disease and prior radiation. Record laryngeal function, swallowing and aspiration burden, pulmonary reserve, nutrition, dentition, thyroid status, vascular access and wound risk. Speech-language pathology should counsel about electrolarynx, esophageal speech and primary versus secondary tracheoesophageal puncture, and the team should mark and teach stoma care. Severe malnutrition, active infection, unresectable carotid or prevertebral disease, inadequate pulmonary reserve, major pharyngeal extension or poor irradiated tissue may require optimization, altered resection, vascularized reconstruction or a nonoperative plan.",
    ),
    ("Total Laryngectomy", "manage"): (
        "Where does total laryngectomy fit among organ-preservation, salvage, aspiration-prevention, and palliative options, and how are reconstruction and rehabilitation integrated?",
        "Offer total laryngectomy for selected resectable advanced or recurrent laryngeal cancer when oncologic control cannot be achieved with an acceptable functional larynx, and for carefully selected end-stage dysfunctional larynges with intractable aspiration after shared decision-making. Compare it with radiation-based organ preservation, partial laryngeal surgery, nonsurgical aspiration strategies and palliation according to tumor, prior therapy, physiology and goals. Plan neck treatment and pharyngeal closure with vascularized tissue when defect or irradiated-field risk warrants it. Nutrition, pulmonary toileting, smell rehabilitation, thyroid surveillance and alaryngeal communication begin before surgery and continue longitudinally.",
    ),
    ("Total Laryngectomy", "teach"): (
        "How would you teach total laryngectomy as one pathway from indication and extirpation through permanent-airway safety, fistula prevention, swallowing recovery, and speech rehabilitation?",
        "Begin with the irreversible physiologic change: the trachea is matured to the neck and no longer connects to mouth or nose, so all oxygenation, suction and intubation occur through the stoma. The operation removes the larynx with tumor-appropriate adjacent structures, treats the neck when indicated and closes or reconstructs the pharynx without tension. Monitor for hematoma, stoma compromise, salivary leak, fistula, wound infection, stricture, hypocalcemia and hypothyroidism. Restore nutrition and swallowing deliberately, and establish communication with electrolarynx, esophageal speech or tracheoesophageal prosthesis rather than treating rehabilitation as an afterthought.",
    ),
    ("Professional Voice", "teach"): (
        "How would you teach evaluation of a professional voice user when ordinary conversation sounds normal but occupational endurance, range, control, or reliability has fallen?",
        "Define the actual vocal task—pitch range, loudness, style, duration, schedule, amplification, recovery time and performance environment—and reproduce it during perceptual and stroboscopic assessment when safe. Examine mucosal vibration, closure, motion, motor control, respiratory support, resonance and compensatory tension; a normal conversational sample can miss task-specific injury or technique failure. Quantify occupational impact and coordinate with a voice-specialized speech-language pathologist or singing-voice professional. Treat inflammation, lesion, paresis or systemic contributor while modifying load, and use return-to-performance criteria based on the real task rather than a normal speaking voice alone.",
    ),
    ("Scar Management", "recognize"): (
        "A postoperative scar is raised, widened, depressed, contracted, pigmented, painful, or function-limiting: which phenotype is present, and which finding suggests recurrent disease or wound failure instead?",
        "Describe timing, color, height, thickness, pliability, symptoms, extension beyond the original wound and distortion of nearby free margins or joints. Hypertrophic scars remain within the wound; keloids grow beyond it; widened scars suggest tension or weak support; depressed or tethered scars reflect volume loss or adhesion; contracture limits movement. Early erythema may be normal maturation. Drainage, fluctuance, dehiscence, exposed hardware, progressive ulceration, fixation, cranial neuropathy or a new mass requires evaluation for infection, fistula, ischemia, foreign body or tumor recurrence rather than cosmetic scar treatment.",
    ),
    ("Scar Management", "localize"): (
        "Which biologic and mechanical processes drive hypertrophic, keloid, widened, depressed, and contracted scars, and how does that mechanism choose the intervention?",
        "Excess collagen deposition and prolonged inflammation produce hypertrophic or keloid elevation; persistent tension and poor deep support widen a scar; tethering or volume loss depresses it; directional shortening across a mobile boundary creates contracture. Pigment and vascularity may be separate targets from contour. Reduce inflammation or collagen activity with silicone, pressure, corticosteroid or selected adjuncts; address vascularity or pigment with appropriate energy-based treatment; restore support, release tethering, reorient tension with Z-plasty, or add tissue when the structural mechanism demands it. Treat active infection or ischemia before remodeling the scar.",
    ),
    ("Scar Management", "workup"): (
        "Before treating a problematic scar, what history, examination, photographs, and risk assessment define the phenotype, maturity, functional effect, and safe baseline?",
        "Record the original operation or injury, healing complications, radiation, prior treatments, growth pattern, symptoms, skin type, keloid history, nicotine use, diabetes and immunosuppression. Examine the scar at rest and with movement for boundaries, color, thickness, pliability, tethering, tension vectors, sensory change and distortion of eyelid, lip, nostril, neck or joint. Standardized photographs and patient-reported function provide a baseline. Biopsy or imaging is selective when recurrence, foreign body, infection or another lesion is plausible. An immature scar usually merits observation and conservative care unless contracture or functional distortion demands earlier action.",
    ),
    ("Scar Management", "manage"): (
        "How should scar therapy be sequenced by maturity and phenotype, and which response or complication should prompt revision or a different modality?",
        "Begin with wound optimization, sun protection, moisturization and massage when appropriate; add silicone or pressure for susceptible raised scars. Intralesional corticosteroid, often with selected adjuncts, treats symptomatic hypertrophic or keloid biology; vascular, pigment or texture targets may use phenotype-appropriate laser therapy. Delay elective surgical revision until maturation when possible, then correct the actual problem with excision and layered closure, tension redistribution, Z-plasty, local tissue transfer, grafting or volume restoration. Escalate for progressive contracture, functional distortion, refractory pain or pruritus, recurrent keloid, ulceration, infection, pigment injury or evidence that the lesion is not a benign scar.",
    ),
    ("Scar Management", "teach"): (
        "How would you teach scar management as a time- and phenotype-based pathway from wound optimization through conservative therapy, procedural treatment, and revision?",
        "First decide whether the wound is still failing, the scar is maturing normally, or a defined abnormal phenotype is present. Correct infection, ischemia, tension and systemic healing risks before treating appearance. During maturation, use protection and selected silicone, pressure, injection or laser therapy for the target that is actually active. Reserve revision for a stable scar or earlier functional necessity, and redesign support and tension so the same mechanics do not recreate the defect. Counsel that improvement is iterative, recurrence risk varies by biology and site, and no intervention makes a scar disappear.",
    ),
    ("Otoplasty", "recognize"): (
        "Which specific auricular deformity components make an ear prominent, and how does identifying the dominant component determine whether otoplasty is appropriate?",
        "Analyze antihelical fold definition, conchal depth and height, conchomastoid angle, lobular projection, helical shape, cartilage stiffness and asymmetry at upper, middle and lower thirds. Prominence most often reflects antihelical underfolding, conchal excess or both, but macrotia, constricted ear, cryptotia, framework deficiency and isolated lobular prominence require different reconstructive logic. Otoplasty is appropriate when the patient seeks correction of a defined framework relationship with realistic expectations; it is not a uniform ear-pinning operation and cannot promise exact bilateral symmetry.",
    ),
    ("Otoplasty", "localize"): (
        "Before otoplasty, map the antihelix, concha, conchomastoid angle, lobule, vascularized skin envelope, and danger zones; which relationship changes the maneuver?",
        "The antihelix must be recreated at the site of underfolding without producing a sharp or tubular ridge. Conchal excess and an increased conchomastoid angle may require concha-mastoid setback or selective cartilage management while preserving the external canal. The lobule is assessed separately because upper-ear correction may expose residual lower-pole prominence. Protect the thin anterior skin, posterior vascularity and perichondrium, avoid narrowing the postauricular sulcus, and bury permanent sutures away from skin. Stiff adult cartilage may need controlled scoring, whereas soft pediatric cartilage may respond to sutures alone.",
    ),
    ("Otoplasty", "manage"): (
        "How do you match suture reshaping, conchal setback, cartilage modification, or observation to the deformity, and what should trigger urgent postoperative reassessment?",
        "Use antihelical mattress sutures for true fold deficiency, concha-mastoid fixation for excessive angle or conchal contribution, and limited cartilage weakening or reduction only when stiffness or excess requires it. Treat lobular prominence separately and avoid overcorrection, canal narrowing and loss of the postauricular sulcus. Minor asymmetry may be preferable to escalating maneuvers that threaten contour or skin. Sudden severe pain, tense swelling, bruising or contour expansion suggests hematoma and requires prompt dressing removal and evacuation; ischemic skin, infection, exposed suture, chondritis or recurrent deformity also demands early review.",
    ),
    ("Otoplasty", "teach"): (
        "How would you teach otoplasty as deformity-specific cartilage mechanics followed by symmetry checks and early hematoma or skin-compromise rescue?",
        "Start by naming the component—antihelical underfolding, conchal excess, excessive conchomastoid angle, lobular prominence or a more complex framework anomaly—then select the least destructive maneuver that corrects it. Mark and compare both ears before and during surgery, build smooth curves, preserve the sulcus and canal, and bury sutures under healthy coverage. Reassess projection from multiple views before closure because one correction can unmask another. Postoperatively, disproportionate pain or tense swelling is a hematoma until proven otherwise; rapid evacuation protects cartilage from necrosis and deformity.",
    ),
    ("Narcolepsy / Central Hypersomnolence Recognition", "localize"): (
        "How do narcolepsy and other central hypersomnolence disorders differ physiologically from insufficient sleep, circadian misalignment, sedating medication, depression, and untreated sleep apnea?",
        "Central hypersomnolence reflects abnormal regulation of wakefulness and REM sleep rather than upper-airway collapse alone. Narcolepsy type 1 is associated with orexin deficiency and cataplexy, while type 2 lacks cataplexy and has no established orexin deficiency; idiopathic hypersomnia produces persistent sleepiness with a different sleep and awakening phenotype. Before specialized testing, document adequate sleep opportunity and regular timing, review drugs and mood, and treat clinically important sleep-disordered breathing. PSG followed by a valid MSLT supports classification only when sleep deprivation, circadian misalignment and medication effects have been controlled.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v143_tps_03": "RET genotype sets the expected tempo of medullary thyroid carcinoma and therefore the earliest safe window for prophylactic thyroidectomy; age is interpreted within that variant-specific risk category rather than used alone. Highest-risk variants generally require surgery in infancy or early childhood, whereas moderate-risk variants may permit timing informed by calcitonin, ultrasound, family phenotype and access to expert follow-up. Screen for pheochromocytoma when genotype and age make it relevant, and treat a catecholamine-secreting tumor before thyroid surgery.",
    "v245_ped_hl_fnd": "Use the early-hearing-detection pathway as a practical benchmark: complete screening by 1 month, diagnostic audiologic confirmation by 3 months, and enrollment in appropriate early intervention by 6 months, with programs increasingly pursuing a 1-2-3 timeline when feasible. These are maximum targets, not reasons to wait. Any failed screen, risk factor, parental concern or developmental delay should trigger timely ear-specific testing and communication support while the cause is evaluated.",
    "v256_lar_esoph_app": "Dilation enlarges the narrowed lumen but does not control the eosinophil-driven inflammation that continues remodeling the esophagus. In fibrostenotic EoE, use dilation for clinically important fixed narrowing while gastroenterology directs anti-inflammatory treatment and objective follow-up; either component alone is incomplete. Repeated dilation without disease control invites recurrent stricture and additional procedures, whereas medication or diet alone may not immediately correct an established tight caliber. New severe pain, crepitus, fever or instability after dilation requires perforation evaluation.",
    "v128_lar_05": "Injection augmentation is reasonable when documented glottic insufficiency from vocal-fold atrophy causes meaningful breathiness, vocal fatigue, weak cough or selected swallowing symptoms despite an appropriate voice-therapy trial, or when a temporary diagnostic trial will clarify likely benefit from durable medialization. Choose material and setting from desired duration, gap, health and goals. Reconsider isolated injection when stiffness, tremor, severe supraglottic compensation, a large posterior gap or an untreated lesion is the dominant problem.",
    "v138_lar_13": "Recent bilateral paresis with plausible neural recovery favors securing the airway while avoiding unnecessarily irreversible bilateral tissue removal. If observation is safe, follow motion and cause; when an airway is required, tracheostomy or a deliberately limited unilateral endoscopic enlargement may preserve future voice and swallowing options. Laryngeal EMG can sometimes inform prognosis but does not replace the clinical airway decision. Progressive distress still requires immediate airway control—the possibility of recovery cannot justify unsafe delay.",
    "v145_lar_06": "The conus elasticus is the fibroelastic subglottic membrane extending from the superior cricoid toward the vocal ligaments. It can initially constrain superficial spread across the glottic-subglottic boundary, but tumor may track along or penetrate it into the paraglottic space and cricothyroid region. Once those deeper compartments or cartilage are involved, apparent mucosal extent understates disease and both staging and conservation-surgery feasibility change. Imaging and direct examination must therefore assess deep spread, not just the visible inferior tumor edge.",
    "v145_lar_09": "Coexisting unilateral paresis changes presbyphonia from symmetric age-related atrophy to an asymmetric motor and closure problem. Confirm motion, level difference, gap geometry, aspiration risk and nerve etiology before treatment. Voice therapy remains useful, but targeted temporary injection can protect function while recovery is assessed; persistent denervation may favor durable thyroplasty, arytenoid adduction for posterior gap or height mismatch, or selected reinnervation. Bilateral symmetric augmentation without addressing the paretic side can undercorrect the true deficit.",
    "v241_ped_tgdc_app": "Follow the tract with the central hyoid specimen toward the tongue base and foramen cecum while maintaining a midline suprahyoid dissection. Nearby structures include the hyoid body, strap and suprahyoid muscles, thyrohyoid membrane, lingual musculature and, laterally, the hypoglossal nerves and lingual arteries. Remove a core of tissue rather than chasing an invisible duct blindly. Entering pharyngeal mucosa, uncontrolled lateral dissection or failure to remove the central hyoid increases morbidity or recurrence risk.",
    "v251_lar_strobe_snr": "Routine stroboscopy becomes unreliable when cycle-to-cycle periodicity is too poor for synchronization, as in severe dysphonia from irregular mass lesions, advanced scarring, marked edema, spasmodic or tremulous phonation, and some neurologic or inflammatory disorders. The displayed wave can then be a sampling artifact. Use real-time laryngoscopy for gross motion and consider high-speed videoendoscopy or videokymography when the actual vibratory pattern will change diagnosis or treatment.",
    "v255_lar_cordotomy_app": "A staged unilateral cordotomy or arytenoid procedure widens the airway incrementally while preserving as much contralateral glottic tissue as possible for voice, cough and swallowing. Healing, edema and scar can alter the final airway, so the response to the first side informs whether more surgery is truly needed. Aggressive bilateral removal creates a larger irreversible aspiration and dysphonia burden and can still restenose. Immediate bilateral intervention is reserved for exceptional airway needs after explicit functional tradeoff counseling.",
    "v269_gen_afb_fnd": "A ball-valve bronchial obstruction traps air distal to the object: the affected lung or lobe stays hyperlucent and expanded on expiration rather than becoming smaller and denser like the opposite side. Bilateral inspiratory/expiratory films can show asymmetric air trapping; in a young child unable to cooperate, lateral decubitus views may show failure of the dependent affected lung to deflate. Normal films do not exclude a foreign body, and strong history or focal findings still justify bronchoscopy.",
    "v270_gen_eso_snr": "Stop oral intake and assess airway, sepsis and hemodynamics. Obtain prompt contrast-enhanced cross-sectional imaging, often with a water-soluble oral-contrast strategy tailored with radiology, when perforation is suspected; do not perform a routine blind swallow study in an unstable patient. Start broad aerobic and anaerobic coverage, provide IV support and involve ENT/thoracic or general surgery early. Small contained injuries may be managed selectively, but free leak, mediastinal contamination, necrosis, retained object or clinical deterioration requires drainage and repair or diversion planning.",
    "v136_oto_10": "Implantable bone-conduction options are considered when the conductive or mixed loss, chronic drainage, canal atresia or single-sided deafness phenotype is likely to benefit and conventional air-conduction or nonsurgical routing is inadequate or impractical. Selection depends on bone thresholds, speech goals, age and skull thickness, skin and soft tissue, prior surgery, MRI needs, retention and ability to maintain the site. A headband or adhesive trial helps estimate benefit. Surgery is not justified merely because an implant exists if a nonsurgical device meets the goal.",
    "v138_hn_16": "After supracricoid partial laryngectomy, at least one functional cricoarytenoid unit is needed to open the reconstructed airway and close it sufficiently for swallowing and phonation. Arytenoid fixation, denervation or oncologic sacrifice can therefore convert an anatomically feasible resection into a functionally unsafe one with persistent aspiration or airway dependence. Preoperative motion assessment and intraoperative preservation of the selected unit matter; postoperative rehabilitation cannot compensate for absent essential arytenoid function.",
    "v138_lar_05": "Dysphagia to solids and liquids from the outset suggests impaired propulsion or lower-esophageal sphincter relaxation rather than a simple fixed narrowing, which usually begins with solids and later affects liquids. Ask about regurgitation, weight loss, aspiration and intermittent versus progressive symptoms. A dedicated esophagram and upper endoscopy evaluate structure and mucosa, while high-resolution manometry defines motility or outflow obstruction. Oropharyngeal coughing or failure to initiate swallowing still redirects evaluation toward FEES or MBS.",
    "v139_ped_01": "Frenotomy becomes more reasonable when a restrictive lingual frenulum produces observed ineffective latch or milk transfer and persistent maternal nipple pain despite skilled lactation support, with tongue mobility findings that fit the dysfunction. The decision should integrate weight trajectory and alternative feeding causes rather than a visual grade alone. Poor intake from prematurity, hypotonia, craniofacial disease or uncorrected positioning will not be cured by release. Discuss bleeding, pain, oral aversion, reattachment and the possibility of no improvement.",
    "v204_oto_lab_snr": "Purulent middle-ear disease, acute mastoiditis, cholesteatoma, a labyrinthine fistula, coalescent change, subperiosteal collection, facial weakness or intracranial complication lowers the threshold for operative source control. Tympanostomy can drain an infected middle ear and obtain culture; mastoidectomy is considered when mastoid or cholesteatomatous disease cannot be controlled medically or complications are present. Sudden hearing and vestibular loss without an otologic source should instead broaden evaluation toward viral, vascular, autoimmune and central causes rather than prompt empiric ear surgery.",
    "v247_ped_frenulum_app": "Persistent bleeding despite direct pressure, expanding floor-of-mouth or tongue swelling, respiratory noise or distress, pallor or lethargy, fever, dehydration, worsening feeding, uncontrolled pain or concern for infection requires urgent reassessment. Airway change or an expanding hematoma is an emergency. Minor spotting and transient feeding adjustment may be expected, but the infant should still demonstrate safe intake and urine output. Routine stretching should not delay evaluation of a complication and should follow the treating team's evidence-informed protocol.",
    "v260_fpt_obstruction_app": "Internal-valve narrowing is localized near the junction of septum and upper lateral cartilage and appears as a narrow angle or static middle-vault pinch; support of that segment improves airflow. External-valve collapse involves the alar rim, lateral crus or nostril and is seen as inspiratory inward movement at the nostril margin. Dynamic lateral-wall collapse may span both zones. Examine at rest and with inspiration, use targeted support maneuvers rather than a nonspecific global Cottle pull, and assess septum, turbinates and mucosa simultaneously.",
    "v267_sleep_circ_snr": "Improved sleep onset, wake time, alertness and daytime function when the patient follows a consistent schedule aligned to the suspected circadian phase supports the interpretation. A sleep log or actigraphy should show the timing shift rather than only a subjective good night. Persistent sleepiness despite adequate, regular sleep opportunity should reopen the differential for sleep apnea, medication effect, mood disorder or central hypersomnolence. Relapse when the schedule again conflicts with the internal phase is common and does not by itself disprove the diagnosis.",
    "v270_gen_eso_fnd": "An esophageal button battery completes an electrical circuit across moist tissue, generating hydroxide and rapid liquefactive necrosis; serious injury can begin within hours and may progress even after removal. A coin causes pressure obstruction but lacks the same electrochemical injury. Therefore an esophageal battery requires immediate removal and post-removal injury assessment, while a stable child with a coin follows an urgent but less minute-to-minute pathway. Review two-view imaging carefully for the battery's double-rim or step-off sign.",
    "v271_gen_epi_app": "Posterior packing can worsen hypoxemia, obstruct the airway, provoke aspiration or vagal events, and conceal ongoing hemorrhage. Admit patients with posterior packs for monitored care, especially those who are older, frail, significantly anemic, actively bleeding, anticoagulated, cardiopulmonary-compromised, affected by OSA, or requiring substantial analgesia or sedation. Ensure airway access, serial hemodynamic and hemoglobin assessment, and a defined plan for pack duration and definitive SPA or endovascular control if bleeding continues; packing is a bridge, not proof of hemostasis.",
    "v136_rhi_13": "Draf III creates a large common frontal neo-ostium but exposes raw bone and remains vulnerable to fibrin, crusting, granulation, infection and progressive cicatricial stenosis. Saline irrigation, topical anti-inflammatory access, endoscopic surveillance and selective debridement keep the cavity patent while mucosa heals; retained partitions or osteitic bone can accelerate restenosis. Worsening frontal pain, fever, orbital symptoms, purulence or early narrowing requires prompt examination rather than waiting for complete closure.",
    "v137_fpt_11": "Preserve an adequate lateral-crural strip and avoid violating the scroll and ligamentous support indiscriminately. After conservative cephalic trim, restore shape and strength with transdomal or interdomal sutures, lateral-crural steal or repositioning, turn-in flap, spanning or lateral-crural strut graft, alar rim graft, or columellar/septal support as the diagnosed deformity requires. Recheck external-valve stability, alar contour, projection and rotation before closure; additional cartilage removal is not the default correction for residual bulbosity.",
    "v138_hn_27": "The anterior commissure has little intervening soft tissue over the thyroid cartilage and complex three-dimensional attachment around Broyles ligament, making depth and cartilage involvement difficult to judge endoscopically. Exposure can be limited and piecemeal orientation can obscure the true deep margin. Involvement therefore raises the risk of an inadequate margin and local recurrence and may shift treatment toward a wider endoscopic resection, open partial approach or radiation according to stage, exposure, cartilage suspicion and expected function.",
    "v138_lar_06": "Pooling secretions without awareness, absent response when the scope contacts supraglottic structures, and penetration or aspiration without an effective cough suggest impaired laryngopharyngeal sensation and reduced airway protection. FEES can add a formal sensory stimulus in appropriate settings, but clinical interpretation also includes spontaneous swallow frequency and secretion severity. Silent aspiration should lower confidence in symptom reporting and may require stricter diet, supervision, pulmonary monitoring or temporary nonoral support while the cause and recovery potential are addressed.",
}


def apply_daily_curriculum_quality_v376(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if not override:
            continue
        prompt, answer = override
        item["daily_prompt"] = prompt
        item["prompt"] = prompt
        item["answer"] = answer
        changed += 1
    return changed


def install_daily_curriculum_quality_v376(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v376():
        items = original_get_items()
        apply_daily_curriculum_quality_v376(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v376

    def adaptive_question_v376(item):
        return item.get("daily_prompt") or item.get("prompt") or ""

    app_module._adaptive_question = adaptive_question_v376

    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1

    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119

    return {
        "daily_pairs_repaired": len(DAILY_OVERRIDES),
        "curveball_answers_repaired": repaired,
    }
