"""Tenth-order Daily Curriculum question/answer and curveball repairs."""


DAILY_OVERRIDES = {
    ("Aesthetic Facial Analysis", "teach"): (
        "How would you teach aesthetic facial analysis so that measurements inform a patient-specific plan without turning population averages into rigid ideals?",
        "Begin with the patient's functional concerns, identity, priorities, and features they do not want changed. Use standardized photographs and a reproducible sequence—facial thirds and fifths, symmetry, profile, chin and nasal projection, orbital and perioral relationships, skin and dynamic expression—to describe anatomy rather than assign beauty. Separate correctable structural relationships from lighting, posture, animation, and normal asymmetry. Measurements are communication tools, not universal targets; the final plan should preserve ethnic and individual characteristics, state realistic tradeoffs, and screen for goals that surgery cannot safely meet.",
    ),
    ("Carotid Body Paraganglioma", "manage"): (
        "How should age, growth, symptoms, catecholamine activity, cranial-nerve function, anatomy, genetics, and competing morbidity guide observation, radiation, embolization, or resection of a carotid body paraganglioma?",
        "Confirm vascular anatomy and skull-base extent, document lower cranial-nerve function, assess secretory symptoms with appropriate biochemical testing, and consider germline evaluation, especially with young age, multifocality, family history, or metastatic disease. Observation with interval imaging is reasonable for selected small, indolent, asymptomatic tumors or patients with high treatment morbidity. Surgery offers definitive local control but nerve and vascular risk rises with carotid encasement. Radiation is an alternative when growth control matters and surgery is disproportionately morbid. Embolization is selective and must be weighed against stroke and cranial-nerve risk.",
    ),
    ("Hypopharyngeal Cancer", "localize"): (
        "Which symptoms, endoscopic subsites, deep-space relationships, and nodal patterns localize a hypopharyngeal cancer and determine whether larynx-preserving treatment remains feasible?",
        "Map the piriform sinus, posterior pharyngeal wall, and postcricoid region with flexible examination and cross-sectional imaging, noting apex extension, esophageal inlet involvement, prevertebral fascia, thyroid or cartilage invasion, vocal-fold mobility, airway caliber, and retropharyngeal or cervical nodes. Referred otalgia, dysphagia, aspiration, weight loss, and a neck mass often reflect advanced disease despite a subtle mucosal primary. Fixation, extensive cartilage or soft-tissue invasion, poor baseline swallow, or a nonfunctional larynx can make nominal organ preservation clinically unsound even when nonsurgical therapy is technically available.",
    ),
    ("Neck Lymphoma", "teach"): (
        "How would you teach a neck-lymphoma pathway from safe tissue acquisition through classification, staging, airway risk, and avoidance of operations that delay systemic treatment?",
        "Suspect lymphoma when adenopathy is persistent, bulky, generalized, associated with B symptoms, or discordant with a routine mucosal primary. Choose tissue that preserves architecture and supports flow cytometry, immunophenotyping, cytogenetics, and molecular studies; coordinate handling with pathology before biopsy. Core biopsy may suffice, while excision is needed when architecture or transformation remains uncertain. Avoid empiric steroids before tissue unless airway or other organ threat demands them. Assess positional dyspnea, stridor, mediastinal compression, and vascular compromise before sedation, then stage and treat by subtype rather than performing therapeutic neck dissection.",
    ),
    ("Parapharyngeal Space Tumor", "localize"): (
        "How do prestyloid-versus-poststyloid displacement, vessel relationships, cranial-nerve findings, and skull-base extension narrow the differential and determine the safest route to a parapharyngeal-space tumor?",
        "Use contrast MRI or CT to identify the compartment and displacement pattern. Prestyloid lesions commonly arise from salivary or fat-containing tissue and displace the carotid space posteromedially; poststyloid lesions include neurogenic and paraganglionic tumors and alter the carotid-jugular relationship according to their nerve of origin. Horner syndrome, vocal-fold paresis, tongue weakness, pulsatility, flow voids, or foraminal extension refines localization. Define vascularity before biopsy, because a paraganglioma should not undergo casual transoral sampling. Size, superior extent, carotid encasement, malignancy risk, and need for vascular control determine transcervical, transparotid, mandibulotomy, or selected observation strategies.",
    ),
    ("Tonsil SCC", "manage"): (
        "How do HPV status, primary and nodal burden, smoking history, resectability, swallowing function, and expected treatment morbidity determine surgery versus radiation-based treatment for tonsil squamous cell carcinoma?",
        "Confirm pathology, p16 status, complete mucosal and nodal staging, and evaluate contralateral tonsil or base-of-tongue risk when the primary is uncertain. Early accessible tumors may be treated with transoral resection plus risk-adapted neck management or definitive radiation, while larger, poorly exposed, or functionally costly resections often favor radiation-based therapy. Positive margins or extranodal extension can add concurrent systemic therapy after surgery, so avoid an operation likely to produce trimodality treatment without benefit. Discuss smoking, dental care, nutrition, aspiration risk, speech and swallowing, and surveillance as part of the initial choice.",
    ),
    ("FEES", "manage"): (
        "How should FEES or MBS findings be translated into a feeding plan, and which result requires broader airway, neurologic, esophageal, or nutrition evaluation rather than a texture recommendation alone?",
        "Identify the impaired phase and mechanism, not merely aspiration: bolus control, timing, laryngeal closure, sensation, pharyngeal drive, upper-esophageal opening, residue, fatigue, and response to tested strategies. Recommend only maneuvers, postures, flow changes, or consistencies that improved safety or efficiency during the study, while balancing hydration, nutrition, development, and quality of life. Silent secretion aspiration, progressive weakness, structural obstruction, marked weight loss, recurrent pneumonia, or findings unexplained by the known diagnosis requires multidisciplinary escalation. A tube may support nutrition but does not prevent aspiration of saliva or refluxate.",
    ),
    ("Injection Laryngoplasty", "localize"): (
        "Before injection laryngoplasty, how do the location and cause of the glottic gap determine target, material, approach, and whether injection is the wrong operation?",
        "Define whether insufficiency comes from unilateral paralysis, bowing or atrophy, scar, sulcus, tissue loss, or a posterior gap, and document vertical height, arytenoid position, mucosal wave, airway, and aspiration. Lateral thyroarytenoid augmentation can medialize a mobile edge, but injection alone may not correct a large posterior gap, major vertical mismatch, joint fixation, or an obstructing mass. Choose temporary material while recovery is plausible and durable material for a stable deficit after counseling. Target depth and volume should restore closure without placing stiff material superficially or overmedializing the airway.",
    ),
    ("Injection Laryngoplasty", "workup"): (
        "What evaluation is required before injection laryngoplasty, and which uncertainty should delay augmentation or redirect the patient to imaging, LEMG, swallow testing, or operative examination?",
        "Confirm the complaint and fold motion with flexible laryngoscopy or stroboscopy, characterize the gap and vibratory edge, and assess airway, cough, swallowing, vocal demand, onset, and likelihood of neural recovery. Unexplained unilateral paralysis requires evaluation along the vagal-recurrent laryngeal course; uncertain prognosis may justify LEMG in a decision-relevant window. Significant aspiration may require instrumental swallow assessment and urgent temporary augmentation. A mucosal lesion, cricoarytenoid fixation, progressive neurologic syndrome, airway narrowing, or an unclear diagnosis should be resolved before treating the visible gap as the whole problem.",
    ),
    ("Laryngeal Anatomy", "manage"): (
        "How should laryngeal compartment anatomy change airway, oncologic, phonatory, and swallowing decisions rather than remain a list of named structures?",
        "Translate anatomy into function and routes of spread. The membranous fold and superficial lamina propria require tissue-sparing technique for vibration; the posterior glottis and cricoarytenoid joints govern airway opening and closure. Paraglottic and pre-epiglottic spaces permit submucosal tumor extension and influence staging and resection. Superior laryngeal sensation and vagal motor function shape aspiration risk, while the recurrent nerve course affects thyroid and mediastinal evaluation. Management should therefore protect the vibratory cover, preserve at least one functional cricoarytenoid unit when appropriate, anticipate hidden deep-space disease, and plan rescue around the patient's actual airway and swallow.",
    ),
    ("Leukoplakia / Laryngeal Dysplasia", "workup"): (
        "How should a vocal-fold leukoplakic lesion be evaluated so that observation, office treatment, and biopsy reflect cancer risk without sacrificing voice unnecessarily?",
        "Document tobacco and alcohol exposure, prior dysplasia, immune status, symptom trajectory, fold motion, lesion laterality, surface morphology, vascular pattern, thickness, and stroboscopic wave. Smooth, flat, homogeneous lesions with preserved wave may permit close surveillance in a reliable patient, whereas irregular, exophytic, ulcerated, erythroplakic, vascular, enlarging, or stiff lesions favor prompt tissue diagnosis. Examine the entire upper aerodigestive tract and neck for synchronous disease. When sampling, obtain representative depth while preserving uninvolved epithelium and ligament; pathology grade, margins, recurrence, and field risk determine subsequent surveillance or treatment.",
    ),
    ("Vocal Fold Polyp / Cyst", "localize"): (
        "Which history and stroboscopic findings distinguish a vocal-fold polyp from an intracordal cyst, reactive contralateral change, scar, or dysplasia, and why does that distinction matter surgically?",
        "A polyp is usually a unilateral superficial phonotraumatic lesion that may be hemorrhagic or gelatinous and often retains some wave around it. A cyst is a deeper, well-circumscribed intracordal lesion with focal wave loss and a higher risk of adherent epithelium or ligament; the opposite fold may show a reactive contact lesion rather than a second primary lesion. Irregular vascularity, leukoplakia, progressive stiffness, or impaired motion broadens concern for dysplasia or another mass. The distinction guides counseling, voice therapy, microflap depth, tissue preservation, and the risk that complete cyst-wall removal may trade recurrence for scar.",
    ),
    ("Vocal Fold Polyp / Cyst", "manage"): (
        "How should voice demand, lesion type, hemorrhage, mucosal wave, diagnostic certainty, and response to therapy determine observation, voice therapy, office treatment, or phonomicrosurgery for a polyp or cyst?",
        "Reduce injurious load and use voice therapy to address inefficient mechanics; selected small polyps can regress, while a true cyst rarely disappears but symptoms may improve. Persistent functional limitation, recurrent hemorrhage, diagnostic uncertainty, or a lesion unlikely to respond behaviorally supports procedural treatment. Office laser or excision is appropriate only for suitable exposure, lesion, and patient tolerance. During phonomicrosurgery preserve epithelium and superficial lamina propria, evacuate or dissect the lesion through the smallest useful microflap, and avoid aggressive stripping. Postoperative rehabilitation and realistic scar-risk counseling are part of the operation.",
    ),
    ("Congenital Neck Masses", "manage"): (
        "Once a congenital neck mass is suspected, how do age, location, infection, airway risk, imaging, thyroid anatomy, and a possible adult malignancy mimic determine immediate and definitive management?",
        "Stabilize airway or sepsis first, then use location and ultrasound or cross-sectional imaging to distinguish thyroglossal, branchial, dermoid, vascular, lymphatic, thymic, or foregut lesions and define relation to vessels, nerves, airway, and thyroid. Treat acute infection before planned excision when safe; drain a true abscess but avoid incomplete elective surgery through inflamed planes. Confirm orthotopic thyroid before Sistrunk surgery. Recurrent lesions require review of the entire tract and prior operative field. In an adult, a lateral cystic mass is metastatic squamous carcinoma until a deliberate mucosal and nodal evaluation proves otherwise.",
    ),
    ("Congenital Neck Masses", "operate"): (
        "What operative principles reduce recurrence and neurovascular injury when excising common congenital neck masses, and when should the planned operation be postponed or expanded?",
        "Operate after acute inflammation resolves unless airway or uncontrolled infection dictates otherwise, using imaging and embryologic anatomy to remove the complete tract or involved central hyoid segment rather than shelling out only the visible cyst. Identify the relationship to carotid sheath structures, hypoglossal and facial nerves, pharynx, thyroid, and mediastinum before division. Sclerotherapy may be preferable for suitable lymphatic malformations, and observation may suit an asymptomatic low-risk lesion. Postpone when the diagnosis or normal thyroid anatomy is uncertain; expand oncologic evaluation when solid components, fixation, suspicious nodes, or adult cystic presentation suggest malignancy.",
    ),
    ("Pediatric Hearing Loss Workup", "manage"): (
        "After pediatric hearing loss is confirmed, how should severity, laterality, conductive-versus-sensorineural mechanism, developmental timing, anatomy, family goals, and comorbidity shape intervention?",
        "Do not wait for etiologic testing to provide hearing access. Treat reversible middle-ear disease when it meaningfully contributes, fit air- or bone-conduction technology according to anatomy, and refer early for cochlear-implant evaluation when appropriately fitted hearing aids do not provide sufficient speech access. Pair audiologic treatment with communication and educational support chosen with the family, monitoring language rather than thresholds alone. Unilateral and mild losses still affect localization, fatigue, and classroom function. Progressive loss, vestibular symptoms, syndromic findings, congenital infection, or anatomic abnormality requires coordinated genetics, imaging, ophthalmology, and specialty follow-up without delaying habilitation.",
    ),
    ("Pediatric Reflux / Eosinophilic Esophagitis", "localize"): (
        "Which symptom pattern localizes a child's feeding or airway complaint toward reflux, eosinophilic esophagitis, oropharyngeal dysphagia, structural disease, or a behavioral feeding disorder?",
        "Reflux may produce regurgitation, pain, feeding refusal, or esophagitis but nonspecific cough and hoarseness alone do not establish it. Eosinophilic esophagitis is suggested by atopy, dysphagia, prolonged meals, texture avoidance, food impaction, or compensatory drinking, with age-dependent feeding symptoms. Coughing during the swallow, wet breathing, recurrent pneumonia, or poor secretion control points toward oropharyngeal dysfunction; focal obstruction, weight loss, bleeding, or progressive symptoms demands structural evaluation. History must separate timing before, during, and after swallowing, because empiric acid suppression cannot diagnose every aerodigestive complaint.",
    ),
    ("Pediatric Reflux / Eosinophilic Esophagitis", "manage"): (
        "How should pediatric reflux or suspected eosinophilic esophagitis be managed while protecting nutrition, avoiding indefinite empiric therapy, and recognizing when endoscopy or dilation is needed?",
        "Use age-appropriate feeding measures and treat proven acid-mediated disease for a defined indication and interval, then reassess rather than continuing medication solely for nonspecific airway symptoms. Suspected EoE requires gastroenterology evaluation and endoscopic biopsies; treatment may include proton-pump inhibitor, swallowed topical steroid, or structured dietary elimination with nutritional oversight and repeat assessment of histologic response. Dilation treats a clinically important stricture but not the underlying inflammation, so it should accompany anti-inflammatory therapy. Food impaction, dehydration, growth failure, bleeding, severe pain, or respiratory compromise requires urgent escalation.",
    ),
    ("Parathyroid Carcinoma", "workup"): (
        "Which biochemical, imaging, vocal-fold, nodal, and operative-history findings raise concern for parathyroid carcinoma, and what should be avoided before an oncologic operation?",
        "Marked hypercalcemia and parathyroid-hormone elevation, a firm or invasive neck mass, vocal-fold paralysis, suspicious nodes, or recurrent disease after prior parathyroid surgery should raise concern, although no single value proves carcinoma. Stabilize dangerous hypercalcemia, localize with ultrasound and complementary imaging, document vocal-fold motion, and assess renal and skeletal effects. Avoid percutaneous biopsy of a suspected primary because cytology is unreliable and tract seeding or capsule violation can compromise definitive surgery. Plan en-bloc resection of adherent involved tissue at the first operation rather than piecemeal excision; pathology and long-term biochemical surveillance establish behavior.",
    ),
    ("Functional Nasal Obstruction", "workup"): (
        "How should history, decongestion, dynamic examination, endoscopy, airflow testing, and prior surgery distinguish septal, turbinate, valve, inflammatory, and sensory causes of nasal obstruction?",
        "Clarify laterality, variability, triggers, sleep and exercise effects, trauma, medication use, prior surgery, and the patient's response to decongestants or external dilators. Examine the septum, turbinates, internal and external valves at rest and inspiration, tip and lateral-wall support, mucosa, polyps, masses, and nasopharynx with endoscopy when indicated. A modified support maneuver may identify valve contribution but is not a stand-alone diagnosis. Objective airflow testing can document physiology in selected cases. Treat inflammatory disease first and match surgery to demonstrated structural collapse; dryness, empty-nose symptoms, neuralgia, or unrealistic goals require a different plan than simply enlarging the airway.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v136_oto_21": "New brief, position-triggered spinning—especially with rolling in bed, lying back, or looking up—plus a characteristic positional nystagmus pattern suggests superimposed BPPV rather than simple failure of vestibular compensation. Repeat positional testing for the involved canal and side instead of merely intensifying gaze-stability exercises. Treat the canalithiasis with the appropriate repositioning maneuver, then resume rehabilitation for any remaining hypofunction or balance deficit.",
    "v137_slp_04": "Painful pulling, tongue abrasion, jaw or neck activation, speech or swallowing interference, uncomfortable stimulation, absent useful protrusion, excessive retrusion, or persistent residual obstruction suggests that amplitude, pulse settings, timing, or electrode configuration needs adjustment. Examine the awake recruitment pattern and correlate it with sleep efficacy. More amplitude is not automatically better; reprogram toward effective forward stiffening with tolerable sensation, and reconsider anatomy or candidacy when no configuration produces useful motion.",
    "v140_gen_08": "The thoracic duct is usually sought in the left lower neck near the venous angle, where it arches anteriorly to enter the junction of the internal jugular and subclavian veins. Its termination is variable and may be multiple, so expose deliberately around the carotid sheath, phrenic nerve, and subclavian vessels rather than relying on one textbook point. Trendelenburg positioning or controlled increases in intrathoracic pressure may help identify active leakage while protecting adjacent nerves and vessels.",
    "v141_rhi_06": "Preoperative embolization is considered for a large or highly vascular JNA when angiography can define feeders and safely reduce operative blood loss, commonly within a short planned interval before resection. Benefit depends on access and vascular anatomy, not size alone. Dangerous internal-carotid, ophthalmic, or intracranial anastomoses increase stroke, blindness, and cranial-nerve risk and may preclude embolization or alter the agent and route. It complements, rather than replaces, an exposure and transfusion plan.",
    "v143_slp_01": "Review opioids, sedative-hypnotics, alcohol, respiratory depressants, and high-altitude exposure, then look for heart failure, recent stroke, renal failure, obesity hypoventilation, COPD overlap, neuromuscular weakness, chest-wall restriction, and metabolic or endocrine contributors. Device downloads alone cannot distinguish every mechanism. Confirm whether events are central, obstructive, treatment-emergent, or part of sustained hypoventilation with appropriate PSG and gas-exchange assessment, then remove reversible drivers before escalating ventilatory technology.",
    "v144_oto_11": "Consider misophonia: a disproportionate emotional and autonomic response—often anger, disgust, or panic—to specific patterned sounds such as chewing or breathing, rather than discomfort determined primarily by sound intensity. Ask about trigger specificity, context, avoidance, functional impairment, and psychiatric or sensory comorbidity. It can coexist with hyperacusis, but simply lowering loudness does not define or treat it; management usually requires education, sound-tolerance strategies, and appropriately experienced behavioral or mental-health support.",
    "v144_oto_26": "Bilateral vestibular loss shifts rehabilitation toward substitution and safety because there is no intact side to drive ordinary vestibular compensation. Emphasize gaze-stability exercises within retinal-slip tolerance, visual and somatosensory substitution, balance under reduced-light and uneven-surface conditions, gait and fall prevention, and assistive or environmental strategies. Oscillopsia and darkness-related imbalance may persist despite good adherence. Review ototoxic exposure and neuropathy, and avoid vestibular suppressants that further impair the limited compensation available.",
    "v171_oto_aied_snr": "Abandon an autoimmune label when the course is sudden rather than fluctuating or progressive, strictly unilateral without systemic clues, explained by noise or ototoxic exposure, accompanied by a retrocochlear sign, driven by middle-ear disease, or associated with infection, genetic disease, migraine, vascular events, or structural inner-ear findings. Lack of steroid response is supportive but not decisive. Recheck serial audiograms, history, medication exposure, imaging, and targeted laboratory testing rather than extending immunosuppression for an unverified diagnosis.",
    "v174_oto_hyper_app": "Hyperacusis is reduced tolerance to ordinary sound intensity across many sources, often described as discomfort or pain at levels others tolerate. Misophonia is a selective emotional reaction to particular patterned sounds regardless of loudness. Loudness recruitment occurs with cochlear hearing loss: perceived loudness grows abnormally rapidly above an elevated threshold, narrowing dynamic range. History, audiometry, loudness-discomfort testing used cautiously, and trigger pattern separate them; they may coexist, so a single low tolerance value is not the diagnosis.",
    "v174_oto_hyper_snr": "For suspected superior canal dehiscence, seek a compatible physiologic syndrome—sound- or pressure-induced vertigo or oscillopsia, autophony, pulsatile tinnitus, low-frequency air-bone gaps with normal middle-ear mechanics, and abnormally low cervical or elevated ocular VEMP thresholds or amplitudes. Confirm with thin-section high-resolution CT reformatted in the canal plane. Radiographic thinning or apparent dehiscence without matching symptoms and physiology is common enough that CT alone should not trigger surgery.",
    "v176_oto_vr_snr": "Direction-changing gaze-evoked nystagmus, pure vertical or torsional nystagmus not fitting a canal, impaired smooth pursuit, dysmetric saccades, internuclear ophthalmoplegia, ocular skew, and failure of fixation suppression strongly suggest central disease. A unilateral peripheral loss more often produces direction-fixed horizontal-torsional nystagmus suppressed by fixation with an abnormal head impulse toward the affected side. Context still matters: acute central lesions can mimic peripheral patterns, so severe truncal ataxia, focal neurologic findings, or an atypical course warrants urgent neurologic evaluation.",
    "v206_rhi_eth_app": "A low-hanging or dehiscent anterior ethmoid artery is suspended below the skull base and can be avulsed during ethmoid dissection. The injured vessel may retract into the orbit, causing a rapidly expanding orbital hematoma and vision threat, while superior injury risks CSF leak or intracranial entry. Identify its canal and the skull-base slope on preoperative imaging, keep dissection oriented to known lamellae, and control bleeding without blind lateral cautery or traction near the orbit.",
    "v213_rhi_jna_found": "Routine office biopsy is avoided because JNA is a markedly vascular tumor in a characteristic adolescent clinical and imaging setting; unplanned sampling can cause severe hemorrhage without adding necessary diagnostic value. Contrast imaging defines the nasopharyngeal origin, pterygopalatine extension, bone remodeling, and vascularity, with angiography when embolization or feeder mapping is contemplated. Biopsy is reserved for genuinely atypical cases under controlled conditions with airway, hemostatic, and alternative-diagnosis planning.",
    "v228_hn_cons_fnd": "A conservation laryngectomy requires at least one cricoarytenoid unit that is oncologically clear, mobile or functionally preservable, and capable of supporting airway protection and reconstruction. Tumor fixation from joint invasion, bilateral arytenoid involvement, extensive posterior commissure or subglottic disease, and severe preexisting aspiration undermine candidacy. Distinguish neurogenic immobility from mechanical invasion when possible. Preserving cartilage without a functional sensate unit does not preserve a useful larynx and may leave chronic aspiration or airway failure.",
    "v244_ped_lm_app": "Common agents include doxycycline, bleomycin, sodium tetradecyl sulfate, ethanol in selected expert hands, and other center-specific sclerosants; choice depends on cyst type, location, age, and toxicity profile. Expect pain, fever, inflammation, and temporary swelling as part of the treatment response. Airway-adjacent, tongue, floor-of-mouth, or mediastinal disease may swell dangerously, so plan steroids, analgesia, monitored observation, staged dosing, and a rescue airway before injection rather than reacting after obstruction develops.",
    "v244_ped_lm_fnd": "Macrocystic lymphatic malformations contain drainable spaces and generally respond better to image-guided sclerotherapy. Microcystic disease infiltrates tissue planes, tongue, or mucosa and responds less predictably because there is no single cavity to empty; repeated sclerotherapy, systemic targeted therapy, laser, limited surgery, or combination care may be needed. Mixed lesions require component-specific planning. The goal is durable symptom and functional improvement, not necessarily complete radiographic eradication at the cost of nerve, airway, or swallowing injury.",
    "v245_ped_neck_app": "Recurrent left lower-neck suppuration with a tract opening at the piriform sinus suggests a third- or fourth-pouch anomaly, often managed as a pyriform sinus tract rather than a generic branchial cyst. Control acute infection first, define the internal opening endoscopically, and assess its relationship to thyroid, recurrent laryngeal nerve, and mediastinum. Definitive treatment may combine endoscopic cauterization or closure with selective external tract excision; repeated drainage alone leaves the internal source and invites recurrence.",
    "v252_lar_reinke_app": "Biopsy when one region is irregular, ulcerated, exophytic, leukoplakic or erythroplakic, unusually vascular, focally stiff, progressively enlarging, or associated with impaired fold motion or a neck node. Bilateral diffuse polypoid edema in a smoker does not immunize the patient against synchronous dysplasia or carcinoma. Target the suspicious focus separately, orient and label specimens clearly, and preserve as much uninvolved vibratory cover as oncologically safe rather than stripping both folds indiscriminately.",
    "v252_lar_reinke_snr": "Treat the irregular leukoplakic focus as a distinct oncologic specimen, not as ordinary edema discarded with bulk reduction. Photograph and map the site, obtain adequate depth without crushing tissue, label laterality and lesion separately, and communicate the clinical concern to pathology. Avoid bilateral aggressive stripping that creates opposing raw surfaces and scar. Definitive extent and surveillance should follow histology, margins, motion, nodal findings, and field-cancerization risk rather than assuming smoking-related polypoid change is uniformly benign.",
    "v254_lar_leuko_fnd": "Irregular or rough surface, nonhomogeneous thickness, erythroplakia, ulceration, exophytic growth, abnormal perpendicular or stippled vascularity, focal stiffness or absent mucosal wave, rapid progression, impaired motion, and suspicious cervical nodes favor prompt biopsy. Smooth, flat, homogeneous disease with preserved wave may permit close observation in a reliable patient, but appearance cannot grade dysplasia with certainty. Integrate tobacco exposure, prior dysplasia, immune status, symptoms, and change over time when setting urgency.",
    "v257_fpt_exam_snr": "Immediately re-examine new visual loss, reduced color vision, afferent pupillary defect, tense proptosis, severe orbital pain, ophthalmoplegia, rapidly expanding swelling, airway change, malocclusion, uncontrolled bleeding, CSF rhinorrhea, or a new focal cranial-nerve or limb deficit. These are not routine edema until dangerous causes are excluded. Check the operation-specific baseline, dressings and drains, and obtain urgent surgical, ophthalmologic, airway, or neurologic intervention rather than waiting for morning rounds or imaging when decompression is time critical.",
    "v259_fpt_mohs_fnd": "The alar rim and eyelid are free margins where millimeters of scar contraction can cause notching, valve collapse, ectropion, exposure, or lacrimal dysfunction. Their defects often involve multiple thin lamellae—lining, support, and skin—and cross aesthetic subunits with limited local tissue. A larger convex cheek defect may accept broad undermining or a graft without distorting a critical margin. Reconstruct function first, replace missing support and lining, and orient tension away from the rim or lid.",
    "v263_sleep_hnsprog_app": "Electrode configuration changes which contacts act as cathodes and anodes and therefore the shape and depth of the stimulation field. At a similar amplitude, one configuration may recruit protrusor branches and produce useful tongue-base opening, while another spreads to retrusor muscles, causes twisting, discomfort, or little airway benefit. Programming should inspect awake tongue motion and comfort, then correlate with sleep testing; amplitude alone cannot correct an unfavorable recruitment vector.",
    "v266_sleep_central_events_snr": "Obesity hypoventilation requires sustained ventilatory support and weight-directed care, not treatment of event count alone; CPAP may suffice when severe obstructive apnea predominates, while bilevel support is needed when hypoventilation persists. COPD overlap requires attention to oxygenation, CO2 retention, expiratory time, and excessive pressure. Neuromuscular weakness often needs bilevel ventilation with a backup rate and cough or secretion support. Confirm daytime and nocturnal gas exchange and avoid oxygen alone when it can mask or worsen untreated hypoventilation.",
    "v267_sleep_rls_app": "Common aggravators include sedating antihistamines, dopamine-blocking antiemetics and antipsychotics, many serotonergic or noradrenergic antidepressants, and sometimes lithium. Caffeine, alcohol, sleep deprivation, and untreated sleep disorders can also worsen symptoms. Review timing and indication before stopping an essential drug, correct iron deficiency, and coordinate substitutions with the prescriber. Dopamine agonists themselves can eventually cause augmentation—earlier onset, greater intensity, and spread—so apparent progression may be treatment induced rather than undertreatment.",
    "v270_gen_chyle_fnd": "Although the thoracic duct usually terminates at the left venous angle, lymphatic anatomy is variable: terminal branches can cross, duplicate, or enter more centrally, and the right lymphatic duct may also be injured. Large resections can disrupt communicating channels, while prior surgery or thoracic disease can reroute flow. Diagnose by drainage character, triglycerides or chylomicrons, timing, and operative anatomy rather than excluding chyle solely because the leak is right-sided.",
    "v270_gen_chyle_snr": "Bilateral neck dissection, prior thoracic surgery, central venous thrombosis, radiation, or previous leak repair can alter normal lymphatic routes and produce more than one injury site. Review both operative fields and thoracic anatomy, localize with lymphangiography when output persists or re-exploration would be blind, and plan access to cervical as well as image-guided or thoracic control options. During rescue, search systematically rather than assuming every high-output leak arises from the usual left venous-angle termination.",
}


def apply_daily_curriculum_quality_v378(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if override:
            prompt, answer = override
            item["daily_prompt"] = prompt
            item["prompt"] = prompt
            item["answer"] = answer
            changed += 1
    return changed


def install_daily_curriculum_quality_v378(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v378():
        items = original_get_items()
        apply_daily_curriculum_quality_v378(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v378
    app_module._adaptive_question = lambda item: item.get("daily_prompt") or item.get("prompt") or ""

    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1
    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119
    return {"daily_pairs_repaired": len(DAILY_OVERRIDES), "curveball_answers_repaired": repaired}
