"""Twelfth-order Daily Curriculum localization and curveball repairs."""


DAILY_OVERRIDES = {
    ("Vocal Fold Nodules", "localize"): (
        "Which history, lesion symmetry, vibratory location, closure pattern, and mucosal-wave findings localize classic vocal-fold nodules rather than a cyst, polyp, scar, or suspicious mass?",
        "Classic nodules are paired, symmetric lesions at the junction of the anterior and middle thirds of the membranous folds, where collision stress is greatest. The history usually reflects repetitive high-impact voice use, and stroboscopy often shows hourglass closure with relatively symmetric vibration. A unilateral deeper lesion with focal wave loss suggests cyst; a unilateral gelatinous or hemorrhagic lesion suggests polyp. Irregular vascularity, progressive growth, marked stiffness, impaired motion, or asymmetry should reopen the diagnosis rather than being dismissed as atypical nodules.",
    ),
    ("Central Vestibular Disorders", "localize"): (
        "How do timing, triggers, ocular-motor findings, gait, hearing, and focal neurologic signs localize dizziness to central pathways rather than a peripheral vestibular lesion?",
        "First define an acute continuous syndrome, episodic spontaneous attacks, or triggered positional symptoms; HINTS applies only to an appropriate acute vestibular syndrome with spontaneous nystagmus. Central clues include direction-changing gaze-evoked, vertical, or unusual torsional nystagmus, skew deviation, impaired smooth pursuit or saccades, severe truncal ataxia, focal deficits, and a pattern inconsistent with one labyrinth. New unilateral hearing loss can accompany AICA-territory ischemia. A normal early MRI does not erase a compelling posterior-circulation examination, while a positive positional test should still fit a canal-specific pattern.",
    ),
    ("Central Vestibular Disorders", "teach"): (
        "How would you teach central-versus-peripheral dizziness without turning HINTS, MRI, or the word vertigo into a stand-alone diagnosis?",
        "Teach syndrome selection before test interpretation. In continuous acute vestibular syndrome, integrate spontaneous nystagmus, head impulse, skew, gait and neurologic examination; in brief triggered episodes, use positional testing; in recurrent spontaneous attacks, build a migraine, inner-ear, cardiac and neurologic differential. HINTS is not valid for intermittent symptoms or a patient without spontaneous nystagmus, and early posterior-fossa MRI can miss ischemia. The patient's label of spinning does not localize disease—eye movements, time course, hearing, gait and focal findings do.",
    ),
    ("Four-Gland Parathyroid Exploration", "localize"): (
        "During bilateral exploration, how do embryology and reproducible relationships guide identification of normal, ectopic, supernumerary, or previously disturbed parathyroid glands?",
        "Superior glands arise from the fourth pouch and are usually posterior near the cricothyroid junction and recurrent laryngeal nerve, but may descend into retroesophageal or posterior mediastinal positions. Inferior glands travel with the thymus from the third pouch and vary widely from the lower thyroid pole through the thyrothymic ligament into the mediastinum. Explore systematically rather than chasing imaging alone, using the recurrent nerve, inferior thyroid artery, carotid sheath, esophagus, thymus and thyroid capsule as landmarks. A missing gland may be intrathyroidal or supernumerary, particularly in renal or familial multigland disease.",
    ),
    ("Four-Gland Parathyroid Exploration", "teach"): (
        "How would you teach four-gland exploration from biochemical disease and embryologic search through extent of resection, viable-tissue preservation, and interpretation of incomplete intraoperative PTH decline?",
        "Start by confirming whether disease is primary, secondary, tertiary, familial, or reoperative, because that determines the expected number of abnormal glands and the resection strategy. Identify glands in a fixed sequence using superior and inferior embryologic paths, search ectopic and thymic sites deliberately, and preserve or autotransplant viable tissue according to the disease context. Mark remaining tissue and ensure hemostasis. Interpret intraoperative PTH by baseline, timing, renal clearance, and manipulation; an incomplete 50% fall may reflect missed hyperfunctioning tissue, but delayed clearance in renal dysfunction can make a rigid early cutoff misleading.",
    ),
    ("Hyperacusis / Decreased Sound Tolerance", "teach"): (
        "How would you teach decreased sound tolerance as a phenotype problem that separates hyperacusis, misophonia, phonophobia, recruitment, migraine, and third-window physiology?",
        "Ask whether the trigger is sound intensity across many sources, a specific patterned sound with anger or disgust, fear of sound, rapid loudness growth above a hearing-loss threshold, migraine-associated sensory amplification, or sound- and pressure-induced vestibular symptoms. Hyperacusis is broad loudness discomfort; misophonia is trigger-specific emotional reactivity; recruitment accompanies cochlear loss; phonophobia emphasizes fear. Audiometry, middle-ear testing, cautious loudness measures, and targeted vestibular testing support—not replace—the history. Avoid blanket earplug use that can reinforce avoidance, and treat the demonstrated hearing, migraine, vestibular, or behavioral mechanism.",
    ),
    ("Microlaryngoscopy", "localize"): (
        "How do lesion surface, vibratory-layer depth, anterior-versus-posterior location, exposure, and airway requirements determine whether suspension microlaryngoscopy is the right approach?",
        "Map the lesion on office laryngoscopy or stroboscopy: epithelial and superficial lamina propria disease requires cover-preserving technique, deeper ligament or muscle involvement changes prognosis and oncologic concern, and anterior commissure or subglottic targets may be difficult to expose. Evaluate dentition, jaw opening, neck extension and prior radiation before promising transoral access. Choose ventilation and instrumentation around the airway and target. Observation, voice therapy, office biopsy or laser, flexible endoscopic treatment, imaging, or an open approach may be safer when suspension adds risk without improving diagnosis or control.",
    ),
    ("Microlaryngoscopy", "teach"): (
        "How would you teach safe suspension microlaryngoscopy from exposure and ventilation planning through tissue handling, hemostasis, and the decision to stop?",
        "Define the diagnostic or therapeutic goal and review airway, cervical spine, jaw opening, dentition, anticoagulation and lesion location with anesthesia. Protect teeth and lips, obtain a stable line of sight with the least force, and coordinate ventilation before instruments share the airway. During phonomicrosurgery preserve epithelium, superficial lamina propria and uninvolved ligament; orient specimens and control bleeding without indiscriminate thermal injury. If ventilation is unstable, the target cannot be fully visualized, or exposure requires destructive force, change the scope, technique or setting, stage the case, or stop.",
    ),
    ("Nonobstructive Pediatric Sleep Disorders", "localize"): (
        "How should timing, schedule, movements, parasomnias, daytime sleepiness, medications, development, and breathing symptoms localize a child's sleep complaint before PSG or surgery is considered?",
        "Separate difficulty initiating or maintaining sleep from circadian delay, insufficient sleep, restless legs or periodic movements, parasomnia, nocturnal seizure, central hypersomnolence, medication effect, behavioral insomnia and obstructive breathing. Ask when the child sleeps normally, weekday-weekend differences, naps, screens, caffeine, witnessed events, recall, injury, irresistible sleep, cataplexy, snoring and gasping. Sleep logs and actigraphy clarify schedule; iron studies, PSG, EEG or MSLT answer selected questions. Tonsil size does not explain a complaint whose dominant physiology is circadian, movement related, neurologic or behavioral.",
    ),
    ("Nonobstructive Pediatric Sleep Disorders", "operate"): (
        "When is surgery inappropriate for a pediatric sleep complaint, and what evidence would be required before an ENT procedure becomes reasonable?",
        "Do not operate for insomnia, delayed sleep phase, insufficient sleep, restless legs, typical parasomnias, narcolepsy, medication-related sleepiness, or central events without a demonstrated surgically correctable obstruction. First characterize the phenotype and treat schedule, behavioral, iron, neurologic, pulmonary or medication drivers. An ENT procedure becomes reasonable only when examination, PSG and sometimes DISE identify obstructive anatomy whose expected benefit exceeds speech, swallowing and airway risk. Coexisting OSA can still require treatment, but improvement in snoring does not prove that the child's separate nonobstructive complaint will resolve.",
    ),
    ("Pediatric Vocal Fold Immobility", "localize"): (
        "How do voice, cry, aspiration, stridor, fold position, laterality, and associated neurologic or cardiothoracic findings localize pediatric vocal-fold immobility and its urgency?",
        "Unilateral immobility commonly produces weak cry, dysphonia and feeding-related aspiration, while bilateral folds near midline can cause neonatal or post-extubation stridor and critical airway narrowing. Bilateral lateralized dysfunction produces poor closure and aspiration rather than obstruction. Flexible laryngoscopy documents motion and position but may not distinguish neural paralysis from cricoarytenoid fixation, posterior glottic scar or mechanical tethering. Birth, cardiac, mediastinal, skull-base, brainstem, intubation and surgical history guide localization along the vagal-recurrent pathway. Respiratory distress, cyanosis or inability to protect the airway changes evaluation to urgent stabilization.",
    ),
    ("Pediatric Vocal Fold Immobility", "workup"): (
        "What evaluation distinguishes pediatric neurogenic paralysis from fixation or posterior glottic stenosis while defining airway, swallowing, and recovery potential?",
        "Begin with awake flexible laryngoscopy, comparing fold position, arytenoid movement, posterior scar, secretion control and dynamic airway. Review onset, intubation, cardiac or neck surgery, neurologic symptoms and birth history; evaluate the vagal-recurrent pathway with targeted brain, skull-base, neck or chest imaging when the cause is unexplained. Instrumental swallowing assessment defines silent aspiration and tested strategies. Direct laryngoscopy with palpation distinguishes fixation, stenosis and anatomic lesions when uncertain. Laryngeal EMG is selective and age- or center-dependent; serial examinations and time course help estimate recovery before irreversible airway-widening surgery.",
    ),
    ("Posterior Cordotomy / Arytenoidectomy", "localize"): (
        "Which glottic level and mechanism must be localized before posterior cordotomy or arytenoidectomy, and what diagnosis will not be corrected by simply enlarging the posterior airway?",
        "Confirm that the bottleneck is glottic and results from bilateral neurogenic immobility or a defined posterior restriction, then distinguish paralysis from cricoarytenoid fixation, interarytenoid scar, subglottic stenosis, supraglottic collapse, tracheomalacia and poor pulmonary reserve. Assess fold position, posterior gap, joint mobility, prior airway surgery, voice, aspiration and expected neural recovery. A cordotomy creates a posterior membranous opening; arytenoidectomy enlarges the cartilaginous posterior glottis. Neither treats obstruction below the glottis or a dynamic distal airway, and both trade closure for airflow.",
    ),
    ("Posterior Cordotomy / Arytenoidectomy", "manage"): (
        "How should airway severity, voice and swallow priorities, recovery potential, scar, and revision risk determine the extent and timing of posterior cordotomy or arytenoidectomy?",
        "Secure urgent airway when necessary, but delay irreversible enlargement when meaningful neural recovery remains plausible and tracheostomy or temporary strategies are acceptable. Choose the smallest unilateral posterior opening that meets respiratory needs, preserving contralateral tissue and arytenoid function when possible. Counsel that breathiness, weak cough, aspiration, granulation, restenosis and revision are expected tradeoffs, and prior radiation or posterior scar increases unpredictability. Reassess pulmonary disease and other airway levels before enlarging further. Bilateral aggressive resection may create more dysphagia and poor voice without correcting a distal cause of dyspnea.",
    ),
    ("Stroboscopy Interpretation", "workup"): (
        "What recording quality, phonatory tasks, and complementary tests are required before interpreting mucosal wave, closure, periodicity, and motion on stroboscopy?",
        "Confirm adequate visualization, focus, light synchronization and a sufficiently periodic signal; severe aperiodicity produces an apparent reconstructed cycle that may not represent real vibration. Record comfortable and high or low pitch, intensity change, connected speech and the task that triggers symptoms when possible. Interpret wave, amplitude, phase, symmetry, closure and motion with perceptual findings. High-speed imaging or real-time endoscopy may better assess irregular vibration; acoustic or aerodynamic measures quantify function; LEMG, imaging, microlaryngoscopy and swallow testing answer different questions. A technical limitation should be reported, not converted into pathology.",
    ),
    ("Stroboscopy Interpretation", "teach"): (
        "How would you teach a learner to convert stroboscopic findings into differential diagnosis without treating absent wave, supraglottic squeeze, or closure pattern as a diagnosis?",
        "Start with whether the recording is valid and the vibration periodic enough for strobe. Then describe motion, edge, closure, amplitude, wave, phase and symmetry before naming disease. Focal absent wave indicates stiffness but may reflect cyst, scar, dysplasia, inflammation or technical limitation; supraglottic compression may be primary or compensation; bowing and a gap may arise from atrophy or paresis. Integrate lesion morphology, task response and voice complaint. Findings should direct observation, therapy, imaging, LEMG, biopsy or phonomicrosurgery according to cause, not trigger treatment by pattern alone.",
    ),
    ("Vestibular Rehabilitation", "localize"): (
        "How do gaze instability, motion sensitivity, positional vertigo, imbalance, gait dysfunction, visual dependence, and autonomic symptoms map to different vestibular-rehabilitation targets?",
        "Oscillopsia and an abnormal head impulse suggest impaired vestibulo-ocular reflex requiring gaze-stability adaptation or substitution. Brief position-triggered vertigo with canal-specific nystagmus requires repositioning rather than generic habituation. Motion or visual sensitivity may benefit from graded habituation; static and dynamic imbalance requires sensory integration, gait and fall training. Bilateral loss emphasizes visual and somatosensory substitution, especially in darkness. Orthostatic symptoms, neuropathy, cerebellar signs, active migraine and functional dizziness can limit or redirect therapy. Rehabilitation should treat the measured deficit, not simply prescribe the same exercises for every dizzy patient.",
    ),
    ("Vestibular Rehabilitation", "workup"): (
        "What baseline assessment is needed before vestibular rehabilitation, and which finding should redirect the patient for repositioning, neurologic evaluation, hearing workup, or medical stabilization?",
        "Define diagnosis, onset, falls, oscillopsia, triggers, medication use, migraine, hearing symptoms, vision, neuropathy and functional goals. Examine ocular motor function, head impulse, dynamic visual acuity, positional nystagmus, sensory balance, gait and fall risk, using laboratory vestibular testing when it changes the plan. Canal-specific BPPV should be repositioned; new hearing loss needs audiologic and otologic evaluation; central ocular-motor signs or severe truncal ataxia require neurologic assessment; orthostasis or unstable cardiopulmonary disease needs medical treatment. Establish measurable goals so lack of progress reopens the diagnosis rather than extending ineffective exercises.",
    ),
    ("Vestibular Test Battery", "teach"): (
        "How would you teach a vestibular test battery by organ, frequency, compensation, and clinical question rather than calling any abnormal result an abnormal VNG?",
        "Tie each test to physiology: video head impulse samples high-frequency canal function, calorics emphasize low-frequency horizontal-canal asymmetry, rotary chair assesses bilateral function and compensation across selected frequencies, cervical and ocular VEMPs probe otolith pathways, positional testing identifies canalithiasis, and ocular-motor tasks screen central pathways. Audiometry adds cochlear localization. Results can disagree because they interrogate different frequencies and organs, and compensation, age, vision, attention and technique alter performance. Interpret a pattern against the syndrome; no isolated weakness percentage or VEMP proves a complete clinical diagnosis.",
    ),
}


CURVEBALL_OVERRIDES = {
    "v139_ped_16": "Fluctuating unilateral or asymmetric low-frequency sensorineural loss, new aural fullness, tinnitus, or documented hearing change temporally linked to recurrent vertigo shifts concern toward an inner-ear hydrops or Ménière-like process rather than isolated vestibular migraine. Repeat age-appropriate audiometry during or after attacks and review congenital, autoimmune and structural causes. The label is uncommon in children and should require objective cochlear change rather than vertigo plus nonspecific ear pressure alone.",
    "v248_ped_vest_fnd": "Delayed independent walking, poor head control, inability to see clearly while moving, frequent falls in darkness or on uneven ground, avoidance of climbing, and failure to develop age-appropriate balance skills suggest bilateral vestibular hypofunction. Ask about congenital hearing loss, meningitis, ototoxic exposure, inner-ear malformations and cochlear implantation. Developmental delay is nonspecific, so combine history with dynamic visual acuity, head impulse and age-appropriate vestibular testing rather than attributing every motor delay to the labyrinth.",
    "v261_fpt_periocular_fnd": "The anterior lamella consists of eyelid skin and orbicularis muscle. The posterior lamella consists principally of tarsus and palpebral conjunctiva, with retractors contributing functionally. Reconstruction must also preserve the gray line, lash margin, canthal tendons, levator or lower-lid retractors and lacrimal drainage when involved. At least one reconstructed lamella should have a reliable vascular supply; replacing both with free grafts risks ischemia, contraction, malposition and exposure.",
    "v113-fprs-05": "A malpositioned or weak lateral crus can be stabilized with a lateral-crural strut graft, repositioning, turnover or replacement technique depending on cartilage quality and vector. Alar batten grafts support dynamic lateral-wall collapse, while rim or articulated rim grafts reinforce the free alar margin and correct retraction. A composite graft may replace lining and rim tissue in selected defects. Match the graft to the failing structure; indiscriminate bulk can narrow the valve or make contours visible.",
    "v113-hn-01": "Skull-base extension can produce abducens palsy with diplopia, trigeminal V2 or V3 numbness or pain, lower cranial neuropathies, Horner syndrome, or multiple sequential deficits through the cavernous sinus and foramina. Unilateral serous otitis reflects Eustachian-tube obstruction but is not itself a cranial neuropathy. Document the complete cranial-nerve examination and obtain skull-base-focused contrast MRI when symptoms suggest perineural, foraminal or intracranial spread.",
    "v128_hn_10": "Where validated, plasma EBV DNA is a tumor-associated biomarker that can complement staging, prognostic assessment, response monitoring and surveillance in nonkeratinizing EBV-associated nasopharyngeal carcinoma. A persistently detectable or rising level after therapy can prompt closer evaluation, but assay methods and thresholds vary and a negative test does not exclude disease. Use it alongside endoscopy and imaging, not as a substitute for tissue diagnosis or an explanation for every post-treatment symptom.",
    "v136_oto_12": "A salt-and-pepper, intensely enhancing lateral skull-base lesion raises a paraganglioma such as glomus jugulare or vagale. Localize it by epicenter, bone change and vessel displacement, then document pulsatile tinnitus, hearing, facial and lower-cranial-nerve function. Ask about multifocal or hereditary disease and catecholamine symptoms, obtain vascular imaging when intervention is considered, and avoid casual biopsy. Schwannoma and meningioma can enhance but usually have different flow-void, foraminal and displacement patterns.",
    "v144_oto_13": "Before treating a hypervascular paraganglioma, ask whether it is functional, multifocal or hereditary; document hearing, swallowing, voice, shoulder, tongue and sympathetic function; and define carotid, jugular, intracranial and lower-cranial-nerve relationships. Age, growth, symptoms, bilateral disease and baseline deficits affect observation, radiation and surgery. If resection is contemplated, assess embolization anatomy, vascular sacrifice risk and rehabilitation needs. Imaging diagnosis generally makes routine biopsy unnecessary and potentially hazardous.",
    "v136_oto_20": "A dry perforation persisting at four months can be observed if hearing, water exposure and infections are acceptable, but discuss office patching or fat-plug repair for selected small defects and formal tympanoplasty when the defect is larger, symptomatic, infection prone or limiting activity. Evaluate ossicles, Eustachian-tube status and contralateral ear before choosing underlay, cartilage or other technique. The goal is a safe dry ear and useful hearing, not closure at any cost.",
    "v137_fpt_05": "A defect near the lower lid increases the risk that flap weight and contraction will pull the lid inferiorly. Design broad mobilization, anchor the flap or deep tissues to stable periosteum or lateral orbital structures, and direct vectors horizontally or superiorly rather than relying on skin closure. Assess baseline laxity and consider canthal support when needed. A flap that closes the cheek but creates ectropion, scleral show or exposure has failed functionally.",
    "v137_slp_07": "Insufficient sleep and untreated OSA shorten sleep latency and can produce sleep-onset REM, creating a false-positive narcolepsy pattern on MSLT. Document adequate sleep with logs or actigraphy, stabilize the schedule, and treat clinically important OSA before testing when feasible. Review REM-suppressing or sedating medications and withdrawal timing. The MSLT should follow an appropriate overnight PSG; it cannot distinguish central hypersomnolence reliably when chronic sleep deprivation or uncontrolled respiratory fragmentation remains active.",
    "v146_slp_03": "Chronic sleep restriction and untreated OSA can both cause pathologic sleepiness, short mean sleep latency and occasionally sleep-onset REM periods, confounding MSLT interpretation. Verify adequate habitual sleep with logs or actigraphy, optimize respiratory disease, and review circadian schedule, substances and REM-altering medications before testing. Perform an overnight PSG immediately before the MSLT under protocol. A positive result without these conditions being controlled may diagnose test preparation rather than narcolepsy.",
    "v138_lar_14": "A recent hemorrhagic polyp before a performance calls for risk counseling, not a promise that medication will make forceful singing safe. Assess active hemorrhage, lesion size, wave, anticoagulants and vocal demands; recommend relative voice rest, amplification and cancellation or modification when further bleeding or scar risk is meaningful. Steroids may reduce surrounding edema in selected circumstances but do not remove the lesion or prevent rebleeding. Definitive therapy and return-to-performance planning should follow repeat examination and voice-specialist input.",
    "v139_ped_11": "Habitual snoring, witnessed pauses or gasping, labored breathing, paradoxical effort, restless sleep, unusual sleep positions, enuresis, morning headache, impaired growth, and daytime hyperactivity or inattention increase concern for pediatric OSA. Tonsil size supports anatomy but does not establish severity, and quiet sleep does not exclude obstruction. Obtain PSG when diagnosis or severity is uncertain, comorbidity raises perioperative risk, or symptoms and examination disagree. Separate coexisting insomnia, circadian and movement complaints rather than attributing all sleep dysfunction to tonsils.",
    "v139_ped_22": "Pre-existing OSA makes a pharyngeal flap or sphincter procedure potentially hazardous because narrowing the velopharyngeal port can worsen obstruction. Define baseline severity with sleep history and PSG, characterize the closure gap and lateral-wall motion, and consider less obstructive or adjustable alternatives, staged adenotonsillar treatment, or modified port size. Counsel that resonance improvement is not a success if sleep becomes unsafe. Plan postoperative observation and repeat PSG when symptoms or baseline risk justify it.",
    "v144_rh_07": "A lateral frontal mucocele suggests that the diseased compartment remains isolated from the created drainage pathway or cannot be reached adequately through the prior corridor. Reconstruct the postoperative frontal anatomy on thin-cut CT, identify retained cells, neo-osteogenesis, scarring and orbital or skull-base relationships, and choose an extended endoscopic, combined trephine, or external route that permits complete marsupialization and durable surveillance. Repeatedly opening only the medial frontal recess will not drain a separated lateral cavity.",
    "v146_ped_02": "Children with cleft palate often have prolonged Eustachian-tube dysfunction, so tube strategy should be longitudinal rather than a one-time response. Use hearing, effusion duration, speech-language access, tympanic-membrane status and infection burden to decide observation versus repeat tubes. Balance reliable hearing during language development against otorrhea, persistent perforation, tympanosclerosis and cholesteatoma risk from repeated long-term ventilation. Continue audiologic surveillance even after palate repair because muscular reconstruction does not guarantee normal tube function.",
    "v147_fp_05": "Alar retraction commonly follows excessive downward or medial tension from an undersized primary lobe, poor pivot placement, inadequate undermining, or failure to account for the secondary-lobe donor vector. Designing the flap too close to the rim and closing under tension pulls the margin superiorly. Use measured lobe sizing, broad vascular undermining, thoughtful standing-cone placement and tension distribution away from the ala. If the defect itself compromises rim support, add structural support rather than expecting skin rearrangement to resist contraction.",
    "v170_oto_vn_snr": "Do not apply HINTS to brief episodic or position-triggered dizziness, a patient without spontaneous nystagmus, a resolved syndrome, intoxication or inability to cooperate, or symptoms explained by syncope or another nonvestibular process. It is designed for continuous acute vestibular syndrome in an appropriately examined patient and depends on examiner expertise. In the wrong population, a normal head impulse or absent skew is not reassuring and can create false confidence instead of guiding stroke evaluation.",
    "v175_oto_petrous_app": "Petrous-apex cholesteatoma typically shows expansile erosive bone change on CT, low or intermediate T1 signal, high T2 signal, and marked diffusion restriction on non-echo-planar diffusion-weighted MRI without the intrinsic T1 hyperintensity of cholesterol granuloma. Enhancement should be absent or limited to a rim unless infected. Correlate with prior surgery, chronic ear disease and cranial neuropathies. Diffusion technique and lesion size matter, so one nonspecific bright sequence should not determine the diagnosis.",
    "v243_ped_cleft_app": "Type I is limited to the interarytenoid region above the cricoid. Type II extends into but not completely through the posterior cricoid plate; type III traverses the cricoid into the cervical trachea; type IV extends farther down the thoracic trachea and may approach a carina or main bronchus in the most extensive variants. Increasing depth changes aspiration severity, airway strategy and whether endoscopic closure is feasible versus open reconstruction with cardiothoracic support.",
    "v243_ped_cleft_fnd": "A shallow type I cleft can hide beneath apposed interarytenoid mucosa and may not gape during awake flexible laryngoscopy. Secretions, motion, limited angle and lack of palpation obscure the posterior defect. Persistent aspiration with otherwise unrevealing flexible examination therefore warrants controlled suspension laryngoscopy and rigid palpation of the interarytenoid region when clinical suspicion remains. Not every deep interarytenoid notch is symptomatic, so correlate the finding with swallow physiology and competing neurologic or airway causes.",
    "v248_ped_reflux_eoe_app": "Escalate beyond empiric acid suppression for food impaction, progressive solid-food dysphagia, weight loss or growth failure, bleeding, persistent vomiting, severe pain, dehydration, recurrent pneumonia, coughing or wet breathing during feeds, neurologic regression, focal weakness, or symptoms unexplained by reflux physiology. Atopy, prolonged meals and texture avoidance raise EoE concern and require GI endoscopy with biopsies. Aspiration symptoms need swallow assessment, while respiratory or neurologic red flags require their own targeted evaluation.",
    "v251_lar_thyro_app": "A high vagal injury impairs both motor closure and supraglottic sensation, so medialization may improve the glottic gap yet leave silent aspiration from sensory loss, pharyngeal weakness and poor coordination. Counsel that voice improvement does not guarantee a safe swallow. Obtain instrumental swallow assessment, use therapy and diet strategies, and consider temporary augmentation early. Severe persistent aspiration may require additional framework, arytenoid, reinnervation or aspiration-prevention strategies depending on pulmonary consequences and recovery potential.",
    "v256_lar_esoph_snr": "A sharp bone, subcutaneous emphysema, severe neck or chest pain, fever, tachycardia or crepitus raises perforation risk and changes the case to urgent NPO resuscitation, antibiotics when contamination is suspected, cross-sectional imaging with appropriate contrast strategy, and specialist source-control planning. Do not perform blind office extraction or force an endoscope through resistance. Stable contained cervical injuries may be managed selectively, but free leak, sepsis, mediastinal contamination or unstable physiology requires drainage, repair or operative intervention.",
}


def apply_daily_curriculum_quality_v380(items):
    changed = 0
    for item in items:
        override = DAILY_OVERRIDES.get((item.get("topic"), item.get("stage")))
        if override:
            prompt, answer = override
            item["daily_prompt"] = prompt
            item["prompt"] = prompt
            item["answer"] = answer
            changed += 1
    return changed


def install_daily_curriculum_quality_v380(data_module, app_module):
    original_get_items = data_module.get_adaptive_items_v120

    def get_adaptive_items_v380():
        items = original_get_items()
        apply_daily_curriculum_quality_v380(items)
        return items

    data_module.get_adaptive_items_v120 = get_adaptive_items_v380
    app_module._adaptive_question = lambda item: item.get("daily_prompt") or item.get("prompt") or ""
    repaired = 0
    for challenge in data_module.CLINICAL_CHALLENGES_V119:
        answer = CURVEBALL_OVERRIDES.get(challenge.get("id"))
        if answer:
            challenge["curveball_answer"] = answer
            repaired += 1
    data_module.CLINICAL_CHALLENGE_BY_ID_V119 = {
        q["id"]: q for q in data_module.CLINICAL_CHALLENGES_V119 if q.get("id")
    }
    app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    app_module.CLINICAL_CHALLENGE_BY_ID_V119 = data_module.CLINICAL_CHALLENGE_BY_ID_V119
    return {"daily_pairs_repaired": len(DAILY_OVERRIDES), "curveball_answers_repaired": repaired}
