"""v16.1 — Cross-domain Deep Curriculum enrichment, pass 2.

One additional decision-heavy concept in each non-Otology domain. Like v16.0,
these are in-place enrichments only: no new canonical topics, no concept-ID
changes, and unmatched title variants are reported rather than allowed to take
down production.
"""


def _entry(candidates, recognize, localize, workup, manage, operate, teach, tags, sources=None):
    return {
        "candidates": tuple(candidates),
        "fields": {
            "recognize": recognize,
            "localize": localize,
            "workup": workup,
            "manage": manage,
            "operate": operate,
            "teach": teach,
            "tags": list(tags),
            **({"source_basis": list(sources)} if sources else {}),
        },
    }


PATCHES_V161 = {
    "Rhinology / Allergy / Skull Base": [
        _entry(
            ["CSF Rhinorrhea / Skull Base Defect", "CSF Rhinorrhea", "CSF Leak", "Cerebrospinal Fluid Leak"],
            "Suspect CSF rhinorrhea when clear unilateral watery drainage is positional, salty/metallic, increases with straining, follows skull-base trauma/surgery, or occurs with recurrent meningitis. Spontaneous leaks are strongly associated with elevated intracranial pressure phenotypes, particularly obesity/IIH, and may coexist with empty sella or multiple skull-base defects. Do not diagnose a leak from 'clear drainage' alone: allergic/nonallergic rhinorrhea is far more common.",
            "Common anterior-skull-base sites include cribriform plate/olfactory cleft, fovea ethmoidalis/ethmoid roof, sphenoid sinus (including lateral recess), and frontal sinus/posterior table pathways. The defect is the bony/dural failure; the meningocele/meningoencephalocele is herniated intracranial tissue through that failure. Lateral sphenoid recess leaks often relate to pneumatization and arachnoid-pit/IIH physiology and require a different surgical corridor than a medial cribriform defect.",
            "Confirm suspicious nasal fluid with beta-2 transferrin or beta-trace protein when available; glucose testing is unreliable. Thin-cut CT defines bony defects and pneumatization, while MRI/MR cisternographic sequences characterize meningoencephalocele and soft-tissue relationships. When multiple candidate defects exist or an intermittent leak cannot be localized, selected intrathecal fluorescein/cisternographic strategies may be used by experienced teams with informed risk discussion. In spontaneous leak, evaluate the elevated-ICP phenotype rather than treating the hole as an isolated accident.",
            "Acute traumatic leaks can sometimes close with conservative measures when there is no urgent complication, but persistent, recurrent, spontaneous, iatrogenic, or meningitis-associated leaks generally require definitive repair. Treat meningitis promptly when present. Long-term success in spontaneous leaks requires attention to intracranial-pressure drivers—weight management, neuro-ophthalmologic evaluation, acetazolamide and/or CSF-diversion strategies in selected patients—because technically perfect closure can recur if the pressure problem is ignored.",
            "Endoscopic endonasal repair is first-line for most accessible anterior-skull-base defects. Choose exposure according to site, remove mucosa around the true defect, reduce/ablate nonfunctional herniated tissue when appropriate, and create a durable multilayer closure using free graft, fascia, cartilage/bone and/or vascularized flap according to defect size/flow and prior treatment. High-flow defects, large dural openings, irradiated fields and recurrent leaks increase the value of vascularized reconstruction. Lumbar drainage is selective rather than mandatory for every leak. Preserve olfaction and avoid unnecessary bilateral skull-base dissection when a unilateral site is well localized.",
            "Boards/chief framework: prove it is CSF, localize the defect, then ask why the defect occurred. Beta-2 transferrin confirms fluid identity; CT is best for bone and MRI for herniated soft tissue. Spontaneous CSF leak is often an intracranial-pressure disease presenting through the nose, so closure without pressure assessment invites recurrence. Repair strategy follows defect location/flow, not a one-graft-fits-all recipe.",
            ["CSF rhinorrhea", "beta-2 transferrin", "skull base defect", "meningoencephalocele", "IIH", "endoscopic repair", "vascularized flap"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Head & Neck Oncology": [
        _entry(
            ["Adverse Pathology and Adjuvant Therapy", "Adjuvant Therapy After Head and Neck Cancer Surgery"],
            "After curative-intent head-and-neck cancer surgery, adjuvant treatment is driven by pathologic recurrence risk rather than by the preoperative stage alone. The highest-consequence findings are positive surgical margins and extranodal extension, which classically support postoperative radiation with concurrent systemic therapy in an appropriate patient. Other adverse features—pT3/4 disease, multiple positive nodes, close margins, perineural invasion, lymphovascular invasion and selected nodal/subsite risks—often support postoperative radiation without automatically requiring chemotherapy.",
            "Risk is anatomic and biologic. A positive margin means tumor remains at the resection boundary; extranodal extension means metastatic tumor has breached the nodal capsule into surrounding tissue. Perineural invasion, lymphovascular invasion and nodal burden describe additional routes/volume of spread. The operative report must therefore allow pathology to orient margins and specimens accurately; a vague specimen is a future adjuvant-therapy problem.",
            "Review final pathology systematically: primary site/subsite, tumor size/depth or relevant T features, margin status and distance, PNI/LVI, nodal number/levels, size, ENE, and HPV/EBV biology when relevant. Reconcile pathology with the operative map before tumor board. Confirm whether a 'positive margin' can be meaningfully re-resected; do not assume adjuvant therapy is an automatic substitute for an easily correctable residual focus. Assess performance status, renal/hearing function, nutrition and wound healing before recommending concurrent cisplatin-based therapy.",
            "Observation is reserved for appropriately low-risk resected disease. Postoperative radiation treats intermediate-risk microscopic recurrence pathways. Concurrent postoperative chemoradiation is reserved for the highest-risk pathologic features in patients able to tolerate systemic therapy, especially positive margins and ENE. When feasible, re-resection to a true negative margin may alter the risk discussion, but a separately submitted negative fragment does not always erase the biology/geometry of a compromised primary specimen; multidisciplinary pathology/surgical review matters.",
            "The best adjuvant plan starts in the OR: orient specimens, mark concerning margins, communicate close structures and send targeted frozen sections when results will actually change resection. Do not sacrifice a critical structure merely to obtain an arbitrary margin if the morbidity is disproportionate; instead define the true oncologic boundary and discuss adjuvant implications. Conversely, do not leave readily resectable gross disease assuming postoperative radiation will compensate. Neck-dissection quality and accurate nodal-level labeling determine whether ENE/nodal burden can be interpreted properly.",
            "Boards/chief framework: positive margin and ENE are the classic postoperative chemoradiation triggers; PNI/LVI, multiple nodes and advanced local disease generally drive radiation-risk discussions. Adjuvant therapy is not chosen by memorizing a list alone—the question is what microscopic disease may remain, where it can recur, and whether systemic radiosensitization adds benefit worth its toxicity.",
            ["adjuvant therapy", "positive margin", "extranodal extension", "ENE", "PNI", "LVI", "postoperative radiation", "chemoradiation"],
            ["NCCN Head & Neck v2.2026", "Pasha 6e"],
        ),
    ],
    "Thyroid / Parathyroid / Salivary": [
        _entry(
            ["Salivary Gland Malignancy", "Parotid Malignancy"],
            "Salivary malignancy should be suspected with rapid growth, pain, skin fixation, trismus, facial weakness, deep-lobe/parapharyngeal extension or cervical adenopathy, but low-grade tumors can be painless and mobile. Histology matters enormously: mucoepidermoid, acinic, adenoid cystic, salivary duct carcinoma, carcinoma ex pleomorphic adenoma and other entities differ in nodal propensity, perineural spread and distant-metastatic behavior. Facial paralysis in a parotid mass is a major malignant warning sign.",
            "Parotid tumors are organized around the facial nerve, which is a surgical plane rather than a true fascial division of superficial/deep lobes. Deep-lobe disease can extend through the stylomandibular tunnel into parapharyngeal space. Adenoid cystic carcinoma is particularly associated with perineural spread; MRI is valuable when pain, weakness or skull-base neural extension is suspected. Nodal levels II/III are common drainage basins, with additional levels dictated by site/burden.",
            "Ultrasound-guided FNA or core biopsy establishes a preoperative diagnosis in most accessible lesions; avoid routine open biopsy of a parotid mass. MRI is favored for deep-lobe, skull-base and perineural assessment; CT complements bony/chest/staging questions. Examine and document every facial-nerve division before surgery. Stage the neck and chest when high-grade or advanced disease makes regional/distant spread plausible. Pathology should report histologic subtype/grade, margins, PNI/LVI and nodal ENE.",
            "Surgery is primary treatment for most resectable major-salivary cancers. Extent follows tumor location and oncologic clearance rather than the old habit of performing the same parotidectomy for every tumor. Preserve a functioning facial nerve when it is not grossly invaded; preoperative paralysis or gross intraoperative nerve invasion may require segmental sacrifice to achieve control, with immediate reconstruction/reanimation planning when feasible. Elective neck treatment is considered for high-grade, advanced-T or other tumors with meaningful occult nodal risk; therapeutic neck dissection is indicated for clinically involved nodes. Adjuvant radiation is favored for high grade, advanced stage, close/positive margin, PNI, nodal disease/ENE and other high-risk features.",
            "Identify the facial nerve using reliable landmarks and dissect it deliberately rather than 'staying away' from it. A nerve that is merely adherent but functioning should not be sacrificed without evidence of gross invasion; a nerve encased by tumor may need oncologic resection. If sacrificed, document proximal/distal ends and reconstruct immediately with cable graft or nerve transfer when possible, plus eye-protection planning. Deep-lobe/parapharyngeal tumors may require transcervical/transparotid exposure; mandibulotomy is reserved for selected access problems rather than routine use.",
            "Boards/chief framework: facial function is both a staging clue and an operative decision point. Preserve a functioning uninvolved nerve; sacrifice grossly invaded nerve for oncologic control and plan reanimation at the same operation when possible. High-grade histology, PNI, advanced T stage and nodal disease determine neck/adjuvant intensity. Adenoid cystic carcinoma's perineural tendency and late distant relapse make long-term surveillance especially important.",
            ["salivary malignancy", "parotid", "facial nerve", "perineural invasion", "adenoid cystic", "neck dissection", "adjuvant radiation", "reanimation"],
            ["NCCN Head & Neck v2.2026", "Pasha 6e"],
        ),
    ],
    "Pediatric Otolaryngology": [
        _entry(
            ["Pediatric Subglottic Stenosis", "Subglottic Stenosis"],
            "Pediatric subglottic stenosis may be congenital or acquired; acquired disease most commonly follows intubation injury, with risk influenced by tube size, duration, motion/trauma, infection and host factors rather than duration alone. Biphasic stridor, recurrent 'croup,' extubation failure or inability to tolerate an age-appropriate ETT should raise suspicion. Congenital SGS is present without prior airway instrumentation and may reflect abnormal cricoid development; acquired scar often follows ulceration/perichondritis at the narrow pediatric cricoid ring.",
            "The pediatric subglottis is a complete cricoid ring, so circumferential scar has less room to expand than in a compliant segment. Grade stenosis by endoscopic sizing using an appropriately sealed ETT/bronchoscope framework such as Myer-Cotton percentage obstruction, but also describe length, maturity, circumferential character, glottic involvement and associated tracheal disease because grade alone does not choose the operation.",
            "Definitive evaluation is microlaryngoscopy/bronchoscopy with direct sizing and characterization of the entire airway; CT cannot substitute for endoscopic sizing. Document vocal-fold mobility, posterior glottis, stenosis length/grade, distance to cords/trachea, tracheomalacia and distal airway. Review prematurity/intubation history, reflux/inflammation only when clinically relevant, swallowing/aspiration, pulmonary disease and tracheostomy dependence. Culture/infection status can matter before major reconstruction in a chronically instrumented airway.",
            "Mild thin/immature stenosis may respond to endoscopic dilation, scar incision and adjunctive steroid strategies; repeated endoscopic treatment is less successful for long, thick, circumferential or cartilaginous stenosis. Open laryngotracheal reconstruction expands the cricoid/subglottis with cartilage grafting and can be single- or double-stage according to airway stability/comorbidity. Cricotracheal resection removes a severe mature stenotic segment and may provide durable control in selected high-grade disease but is more technically demanding and constrained by proximity to the vocal folds and patient factors.",
            "Choose endoscopic treatment for favorable short/soft stenosis where the framework is adequate; choose LTR when expansion can restore lumen while preserving the segment; choose CTR for selected severe mature stenosis where resection offers a better durable airway. Single-stage LTR requires confidence that the reconstructed airway can support extubation without a protective trach; double-stage reconstruction retains/stents the tracheostomy when airway, pulmonary, neurologic or multilevel factors make that unsafe. Preserve recurrent laryngeal nerves and cricoarytenoid function; a technically larger airway with new glottic dysfunction is not a success.",
            "Boards/chief framework: Myer-Cotton grade is necessary but insufficient. Length, scar maturity, cartilage framework, glottic involvement, comorbidity and tracheostomy dependence determine whether endoscopic treatment, LTR or CTR is appropriate. CT can show anatomy but does not replace endoscopic sizing. The staging decision is fundamentally about whether the child can safely depend on the reconstructed airway immediately.",
            ["pediatric SGS", "Myer Cotton", "laryngotracheal reconstruction", "LTR", "cricotracheal resection", "CTR", "single stage", "double stage"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Laryngology / Voice / Swallowing": [
        _entry(
            ["Subglottic / Tracheal Stenosis", "Subglottic / Tracheal Stenosis", "Idiopathic Subglottic Stenosis"],
            "Adult subglottic/tracheal stenosis is an etiologic diagnosis as well as an anatomic one. Major causes include post-intubation/tracheostomy injury, idiopathic subglottic stenosis (classically otherwise healthy middle-aged women), autoimmune/inflammatory disease such as granulomatosis with polyangiitis or relapsing polychondritis, prior surgery/radiation, infection and neoplasm. Progressive exertional dyspnea is frequently mislabeled as asthma until fixed upper-airway obstruction becomes severe.",
            "Describe stenosis by level, length, diameter/percentage narrowing, circumferential character, scar maturity and cartilage integrity. Idiopathic SGS typically centers at the cricoid/proximal trachea; post-intubation injury may involve cuff/tracheostomy sites and can include framework collapse. Flow-volume loops may show fixed obstruction, but endoscopy defines the lesion that an operation must address.",
            "Flexible laryngoscopy screens the glottis/subglottis; operative bronchoscopy provides definitive measurement and assessment of scar/cartilage. CT neck/chest with airway reconstruction is useful for length, external framework and surgical planning. Target autoimmune/infectious laboratory evaluation to history/exam rather than ordering an indiscriminate panel, but unexplained stenosis deserves evaluation for GPA and other systemic disease. Biopsy atypical, ulcerative or mass-like lesions before labeling them idiopathic.",
            "Endoscopic dilation/incision with selected intralesional steroid or other adjuncts can provide meaningful control for short, favorable stenosis and is often used for idiopathic SGS, but recurrence is common and serial procedures may be expected. Open cricotracheal/tracheal resection offers greater durability for selected mature focal disease when morbidity is acceptable. Treat active systemic inflammatory disease in parallel; repeated airway procedures without controlling the underlying process are incomplete treatment. Tracheostomy is an airway strategy when obstruction or comorbidity makes reconstruction unsafe.",
            "In endoscopic treatment, avoid circumferential thermal injury that can worsen fibrosis; radial scar incision and controlled dilation are tailored to the lesion. Consider open resection when recurrence frequency, stenosis length/severity, framework injury or patient preference makes serial endoscopy an inferior long-term strategy. Resection requires tension-free anastomosis and respect for RLNs and cricoid/vocal-fold proximity; excessive resection length or glottic extension changes candidacy. Voice and swallowing outcomes belong in preoperative counseling, not only airway patency.",
            "Boards/chief framework: do not call every adult SGS idiopathic. Determine cause and framework, then choose serial endoscopic control versus durable open reconstruction. Short soft stenosis behaves differently from long mature cartilaginous stenosis. The decision to escalate to open resection is driven by anatomy, recurrence burden, comorbidity and patient goals rather than an arbitrary number of prior dilations.",
            ["adult SGS", "tracheal stenosis", "idiopathic SGS", "GPA", "dilation", "cricotracheal resection", "airway reconstruction"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Facial Plastics / Trauma": [
        _entry(
            ["NOE Fracture Mechanics", "Nasoorbitoethmoid Fracture", "NOE Fracture"],
            "Nasoorbitoethmoid fractures should be suspected with telecanthus, loss of nasal projection, medial orbital/nasal comminution, CSF leak or a disrupted medial canthal contour after high-energy central midface trauma. The defining reconstructive issue is not simply 'broken nasal bones' but whether the medial canthal tendon remains attached to a stable bone fragment. Failure to restore that relationship produces persistent traumatic telecanthus and a rounded medial canthal angle.",
            "The medial canthal tendon attaches to the central NOE fragment; Markowitz-type classification is based on whether that tendon-bearing fragment is large/stable, comminuted but still tendon-attached, or so comminuted that the tendon is detached from usable bone. The lacrimal system, frontal sinus/skull base, medial orbit and nasal support structures lie in the same injury zone, so epiphora, CSF leak and orbital injury are not separate afterthoughts.",
            "Examine intercanthal distance, canthal contour/stability, globe/vision, nasal projection, occlusion and lacrimal symptoms before swelling obscures landmarks. The bowstring/bimanual test assesses mobility of the tendon-bearing fragment. Thin-cut CT defines central-fragment comminution, frontal sinus/skull-base extension and associated panfacial injury. Suspected CSF leak or vision threat changes the acute workup and multidisciplinary plan.",
            "Stable minimally displaced injuries without canthal/nasal deformity may be observed, but displaced NOE fractures require anatomic reduction of the central fragment and restoration of nasal projection/medial canthal position. The more comminuted the tendon-bearing fragment, the more fixation or transnasal canthopexy strategy must compensate for loss of a stable bony anchor. Delayed repair becomes harder as scar contracts and the medial canthus heals in the wrong position.",
            "Reconstruct stable facial reference points first in panfacial trauma, then reduce/fix the NOE complex to restore width, projection and orbital boundaries. When the medial canthal tendon remains attached to a usable fragment, fix that fragment precisely; when the fragment is not reconstructible/tendon attachment is functionally lost, secure the tendon with transnasal canthopexy to a stable posterior/superior vector rather than merely pulling the skin medially. Rebuild dorsal/nasal support when comminution has destroyed projection. Avoid overly anterior canthal fixation, which produces persistent telecanthus despite a technically 'tight' repair.",
            "Boards/chief framework: classify NOE injuries by the medial-canthal-tendon-bearing fragment because that predicts reconstructive difficulty. Telecanthus is an anchoring problem, not a skin problem. In a comminuted injury, fixing plates without restoring the canthal tendon vector can leave the most visible deformity untreated. Delay makes secondary correction substantially harder.",
            ["NOE fracture", "medial canthal tendon", "Markowitz", "telecanthus", "bowstring test", "transnasal canthopexy"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Sleep Surgery": [
        _entry(
            ["Adult PSG Interpretation", "Adult OSA", "Obstructive Sleep Apnea"],
            "Adult polysomnography should be read as physiology, not just an AHI label. Identify obstructive versus central events, oxygen burden, arousal burden, sleep-stage and positional dependence, hypoventilation, limb movements and sleep efficiency. A patient with the same AHI can have very different clinical risk if events are prolonged with severe desaturation, REM-predominant, supine-predominant or accompanied by hypercapnia. Symptoms/comorbidity still matter when interpreting treatment significance.",
            "Obstructive apnea reflects upper-airway collapse with ongoing respiratory effort; central apnea lacks respiratory effort. Hypopneas require airflow reduction plus desaturation/arousal according to scoring criteria. Supine and REM sleep often worsen collapsibility; inadequate REM/supine sampling can underestimate severity. Obesity hypoventilation and other sleep-related hypoventilation syndromes require attention to CO2, not merely counting apneas.",
            "Review total sleep time/efficiency and whether enough REM/supine sleep occurred before trusting a borderline AHI. Record AHI and, when relevant, RDI, oxygen nadir/time below threshold, central apnea index, CO2 data and positional/stage indices. Home sleep apnea testing is appropriate only for selected uncomplicated adults and can underestimate severity because recording time is not identical to EEG-defined sleep time. In suspected central apnea, hypoventilation, parasomnia, neuromuscular disease or significant cardiopulmonary complexity, full PSG is more informative.",
            "PAP remains first-line for many adults with clinically significant OSA, with weight management and treatment of contributing nasal/medical factors; oral appliance therapy is appropriate for selected mild-moderate disease or PAP-intolerant patients. Surgical treatment should follow anatomy/phenotype and patient goals rather than AHI alone. Positional therapy is reasonable when non-supine disease is substantially lower and adherence is realistic. Central-predominant disease requires a different etiologic/treatment pathway and should not be sent automatically into obstructive sleep surgery.",
            "Before offering surgery, translate PSG into a surgical phenotype: severity, oxygen burden, position/REM dependence, central burden, PAP response, BMI and suspected collapse sites. Tonsillectomy, palate surgery, tongue-base procedures, HNS and skeletal advancement solve different anatomic problems. AHI improvement is not the only endpoint—sleepiness, oxygenation, cardiovascular risk, PAP reduction and quality of life matter—yet residual clinically important OSA still requires objective follow-up testing.",
            "Boards/chief framework: AHI is the start of PSG interpretation, not the end. Always ask obstructive versus central, oxygen/CO2 burden, REM/supine dependence and whether the study sampled representative sleep. The same AHI can describe different physiology and therefore different treatment. Surgery is chosen from phenotype/anatomy after the sleep study defines what kind of breathing disorder is actually present.",
            ["PSG", "AHI", "central apnea", "oxygen burden", "REM", "positional OSA", "hypoventilation", "PAP"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "General ENT / Emergencies": [
        _entry(
            ["Deep Neck Space Infection", "Deep Neck Infection", "Pediatric Deep Neck Infection"],
            "Deep-neck infection can evolve from odontogenic, tonsillar/pharyngeal, salivary, traumatic or other sources and may present with fever, neck pain/swelling, trismus, muffled voice, drooling, torticollis or toxic appearance. New stridor, secretion intolerance, rapidly progressive swelling, cranial neuropathy or systemic instability makes this an airway/sepsis emergency. Antibiotic response at an earlier time point does not protect a patient whose physiology is worsening now.",
            "Understand the spaces because displacement predicts source and spread. Parapharyngeal infection can involve prestyloid or carotid-space structures; retropharyngeal space lies anterior to alar fascia; the danger space between alar and prevertebral fascia can extend from skull base toward the diaphragm, creating a route for descending mediastinal infection. Carotid sheath involvement risks IJV thrombosis/Lemierre syndrome and major vascular complications.",
            "Contrast-enhanced CT neck is the workhorse for defining abscess versus phlegmon, involved spaces, gas, vascular thrombosis and source; extend chest imaging when mediastinal spread is suspected. Ultrasound is useful for superficial collections and pediatric nodes but cannot map all deep spaces. Obtain cultures from a drained collection and blood cultures in septic patients. Reassess the airway clinically even after imaging—an old CT cannot veto new stridor or drooling.",
            "Start IV antibiotics covering expected oral aerobes/anaerobes and modify for host/source/culture. Drain a mature/large collection, infection causing airway compromise, vascular/mediastinal complication, or disease failing appropriate medical therapy; selected small pediatric retropharyngeal collections can improve with close inpatient IV therapy. Source control includes the odontogenic, tonsillar or salivary origin when relevant. Lemierre syndrome requires prolonged antimicrobial therapy; anticoagulation is individualized rather than automatic.",
            "Secure a threatened airway in a controlled setting with ENT/anesthesia and surgical-airway backup; distortion/trismus may make routine induction dangerous. Choose transoral drainage for medially accessible peritonsillar/retropharyngeal collections and transcervical approaches for lateral, carotid-space, multiloculated or inferior disease according to anatomy. Explore all communicating infected spaces and place drainage strategically. Descending necrotizing mediastinitis requires immediate thoracic collaboration because neck drainage alone may be insufficient.",
            "Boards/chief framework: airway and source control outrank obtaining a newer scan in a clinically deteriorating patient. Deep-space anatomy explains complications: danger-space disease can descend to mediastinum and carotid-space disease can involve IJV/carotid/cranial nerves. Antibiotics treat cellulitis and microscopic disease; a patient with a threatened airway or uncontrolled drainable source has crossed into procedural management.",
            ["deep neck infection", "parapharyngeal", "retropharyngeal", "danger space", "mediastinitis", "Lemierre", "airway", "source control"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
}


def apply_cross_domain_depth_v161(deep_modules):
    applied, missing = [], []
    for domain, patches in PATCHES_V161.items():
        modules = deep_modules.get(domain, [])
        for patch in patches:
            found = next((m for m in modules if m.get("topic") in patch["candidates"]), None)
            if found is None:
                missing.append((domain, patch["candidates"]))
                continue
            found.update(patch["fields"])
            applied.append((domain, found.get("topic")))
    return {"applied": applied, "missing": missing}
