"""v16.0 — Cross-domain Deep Curriculum enrichment, pass 1.

The Otology v15.8 pass exposed a recurring problem: a topic can be present and
technically six-layered while still omitting the causal framework, decision
thresholds, operative choices, complications, variants, or the actual answer
that a Teach/Boards layer should teach.

This file performs conservative in-place enrichment of two high-consequence
canonical concepts in each of the eight non-Otology domains. It never creates
new topics and never changes concept IDs. Candidate matching is exact against a
small list of known title variants; an unmatched target is reported rather than
crashing production.
"""


def _entry(candidates, recognize, localize, workup, manage, operate, teach, tags, sources=None):
    return {
        "candidates": tuple(candidates),
        "fields": {
            "recognize": recognize,
            "localize": localize,
            "workup": workup,
            "manage": manage,
            "operate": operate,
            "teach": teach,
            "tags": list(tags),
            **({"source_basis": list(sources)} if sources else {}),
        },
    }


PATCHES_V160 = {
    "Rhinology / Allergy / Skull Base": [
        _entry(
            ["Invasive Fungal Rhinosinusitis", "Acute Invasive Fungal Rhinosinusitis"],
            "Acute invasive fungal rhinosinusitis is an angioinvasive emergency, classically in neutropenia, hematologic malignancy, transplantation, profound immunosuppression, or poorly controlled diabetes/ketoacidosis. Early disease may look deceptively mild: severe or focal facial pain, fever, nasal crusting, pallor or anesthesia, facial numbness, orbital symptoms, or cranial neuropathy are more important than waiting for a black eschar, which is a late finding. Mucormycosis and Aspergillus are classic organisms, but the operative principle is driven by invasion rather than species alone.",
            "Disease begins in sinonasal mucosa and invades small vessels, causing thrombosis, ischemia, and tissue necrosis, then spreads across anatomic boundaries into orbit, pterygopalatine/infratemporal fossae, skull base, cavernous sinus, and intracranial compartment. Loss of sensation can reflect ischemic neural involvement and is a major danger sign. Orbital apex findings or multiple cranial neuropathies imply advanced spread even if the nasal cavity does not look dramatically necrotic.",
            "Obtain urgent nasal endoscopy and biopsy of suspicious tissue for frozen/permanent histopathology; tissue invasion, not surface culture alone, establishes invasive disease. Culture helps direct therapy but a negative culture does not exclude invasion. Contrast-enhanced MRI is particularly useful for soft-tissue, orbital, neural, skull-base, and intracranial extent; CT complements it for sinonasal/bony anatomy. Evaluate CBC/neutrophil status, glucose/ketosis and other reversible host factors. Serial endoscopic examinations are part of the workup because demarcation and progression evolve after the first operation.",
            "Management is simultaneous rather than sequential: urgent surgical source control, prompt systemic antifungal therapy chosen for organism/host context, and aggressive reversal of predisposing immunosuppression or metabolic derangement when feasible. Liposomal amphotericin B is a classic initial agent for mucormycosis; azoles such as isavuconazole or posaconazole have important roles depending on organism and treatment phase. New necrosis, neurologic progression, or persistent invasive tissue after the first debridement should trigger urgent reassessment rather than passive observation.",
            "Debride nonviable and visibly involved sinonasal tissue to viable margins while balancing morbidity against achievable disease control; repeat/serial debridement is common because angioinvasive disease may continue to declare itself. Orbital involvement is not automatically synonymous with exenteration: visual function, apex involvement, extent, response to systemic therapy, and whether orbital tissue can be cleared or controlled guide the decision. Intracranial/cavernous involvement requires multidisciplinary skull-base, ophthalmology, infectious-disease, hematology/endocrine, and neurosurgical planning. The operation is iterative: yesterday's debridement does not prove today's margins are clean.",
            "Boards/chief framework: high-risk host + focal sinonasal pain/necrosis, numbness, orbital signs, or cranial neuropathy = invasive fungal disease until proven otherwise. Do not wait for black eschar. Diagnosis requires tissue invasion; treatment requires antifungal therapy + host-factor reversal + repeated surgical assessment/source control. Progression after an initial debridement is a reason to re-operate or re-stage urgently, not evidence that surgery 'failed.'",
            ["AIFR", "mucormycosis", "Aspergillus", "angioinvasion", "serial debridement", "orbital apex", "immunocompromise"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Epistaxis Surgical Control", "Posterior Epistaxis", "Epistaxis"],
            "Most epistaxis is anterior and arises from the Kiesselbach/Little area, but brisk recurrent bleeding into the posterior pharynx, inability to visualize an anterior source, older age/vascular comorbidity, or failure of appropriate anterior control should raise concern for posterior bleeding. In severe bleeding, physiology and airway risk come before finding the exact vessel. Anticoagulation/coagulopathy, hypertension, trauma, tumor, hereditary hemorrhagic telangiectasia, and recent sinonasal surgery change the context but do not replace local control and resuscitation.",
            "Anterior septal bleeding is supplied by anastomoses involving anterior ethmoidal, sphenopalatine, greater palatine, and superior labial branches. Posterior epistaxis is most commonly controlled through the sphenopalatine artery system at/near the sphenopalatine foramen; posterior septal and lateral nasal branches matter surgically. Persistent superior bleeding after adequate SPA control should raise concern for anterior/posterior ethmoidal contribution or another source. Remember that ethmoidal arteries arise from the ophthalmic/internal-carotid circulation, which changes embolization and surgical-risk thinking.",
            "Stabilize first: airway, hemodynamics, IV access, CBC/type and screen/coagulation assessment when bleeding is significant. Suction and topical vasoconstrictor/anesthetic improve visualization; identify and cauterize a focal anterior source when feasible. Endoscopy is more useful than repeated blind manipulation for ongoing posterior bleeding. CTA/angiography is not routine for every nosebleed but becomes useful for refractory bleeding, suspected pseudoaneurysm/vascular lesion, major trauma, or when endovascular treatment is planned.",
            "Use an escalation ladder: compression/topical vasoconstriction → directed cautery when the source is visible → appropriate packing or hemostatic material when needed → endoscopic arterial control for refractory/posterior bleeding. Correct clinically significant coagulopathy when possible without delaying lifesaving control. Admission/monitoring is appropriate for major posterior bleeding, significant blood loss, high-risk comorbidity, or packing that creates airway/physiologic concern. Recurrent unilateral bleeding or an atypical mass requires evaluation for neoplasm rather than repeated symptomatic treatment alone.",
            "Endoscopic sphenopalatine artery ligation/cauterization is the principal operative option for refractory posterior epistaxis; identify the posterior middle-turbinate attachment/sphenopalatine foramen region and control all relevant branches rather than one visually obvious twig. Anterior ethmoid artery ligation is considered when the bleeding pattern/localization implicates ethmoidal supply or SPA control fails with a superior source. Endovascular embolization is an alternative or adjunct in selected refractory cases, especially when surgical access is unfavorable, but carries stroke/vision/soft-tissue ischemia risks because of dangerous ECA–ICA/ophthalmic anastomoses. Choice between surgery and embolization depends on localization, stability, anatomy, prior procedures, and local expertise.",
            "Boards/chief framework: posterior epistaxis is not simply 'pack harder.' Resuscitate, localize, then move from temporary tamponade to definitive arterial control when bleeding is persistent or recurrent. SPA control treats the common posterior source; persistent superior bleeding changes the vascular hypothesis. Ethmoidal vessels belong to the ophthalmic system, so both surgery and embolization require respect for vision and intracranial circulation.",
            ["epistaxis", "sphenopalatine artery", "anterior ethmoid artery", "posterior packing", "embolization", "endoscopic ligation"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],

    "Head & Neck Oncology": [
        _entry(
            ["Unknown Primary with Cervical Metastasis", "Unknown Primary", "Unknown Primary Head and Neck Cancer"],
            "In an adult, a persistent cystic or solid cervical node should be considered metastatic carcinoma until proven otherwise, especially at level II/III. HPV-associated oropharyngeal SCC frequently presents as a cystic neck mass with a small or occult tonsil/base-of-tongue primary; EBV-associated nasopharyngeal carcinoma has a different mucosal home and testing pathway. Do not repeatedly excise or drain a presumed 'branchial cyst' in an adult before oncologic evaluation.",
            "Nodal level and tumor biology guide the search. HPV/p16-positive upper-jugular disease points strongly toward palatine tonsil or lingual tonsil/base of tongue; EBV-positive disease points toward nasopharynx. Supraclavicular adenopathy broadens the search below the clavicles. The eventual treatment field is affected by whether a mucosal primary can be localized, so finding the source is not academic.",
            "Start with complete head-and-neck examination including flexible endoscopy and tissue diagnosis by FNA/core biopsy rather than open excisional biopsy when possible. Pathology should establish SCC and appropriate HPV/p16 and, when indicated, EBV testing. Cross-sectional contrast imaging and FDG-PET/CT help define nodal burden and search for a primary before operative biopsies. If no primary is found, examination under anesthesia with directed biopsies and palatine tonsillectomy—often bilateral depending on context—and lingual tonsil/base-of-tongue mucosectomy can substantially increase primary-site detection in HPV-associated disease.",
            "Management depends on nodal stage, HPV/EBV biology, whether a primary is found, resectability, prior treatment, and expected functional morbidity. Options include neck dissection with risk-adapted adjuvant therapy or definitive radiation/chemoradiation. Identification of a small oropharyngeal primary can reduce unnecessary mucosal radiation volume in selected treatment plans. Avoid an open-node biopsy unless necessary because violation of tissue planes can complicate subsequent neck management.",
            "During operative workup, systematic bilateral palatine tonsil evaluation and lingual tonsil/base-of-tongue assessment are favored over random biopsies of normal mucosa. Transoral robotic/laser lingual tonsillectomy can identify an otherwise occult HPV-associated primary. Neck dissection extent follows nodal burden and oncologic principles rather than the desire to 'find the primary.' Preserve CN XI, internal jugular vein, and SCM when oncologically safe; sacrifice is dictated by gross involvement, not by the label 'unknown primary.'",
            "Boards/chief framework: unknown primary is a structured localization problem. First prove metastatic disease and define HPV/EBV biology, then image, then perform targeted mucosal evaluation/tonsil workup. HPV-positive cystic level-II disease is oropharyngeal until convincingly shown otherwise. The purpose of finding the primary is to improve staging and treatment precision, not merely to name the tumor.",
            ["unknown primary", "HPV", "p16", "EBV", "cystic neck node", "tonsillectomy", "lingual tonsil", "PET CT"],
            ["NCCN Head & Neck v2.2026", "Pasha 6e"],
        ),
        _entry(
            ["HPV-Associated Oropharyngeal SCC", "HPV-Positive Oropharyngeal Squamous Cell Carcinoma"],
            "HPV-associated OPSCC commonly arises in palatine or lingual tonsillar crypt epithelium and often presents with a small/occult primary but bulky or cystic cervical nodes. p16 immunohistochemistry is the standard surrogate used for staging in appropriate oropharyngeal SCC, but p16 positivity outside the oropharynx does not automatically confer HPV-mediated staging. Tobacco exposure and comorbidity still matter prognostically even within HPV-associated disease.",
            "The oropharynx includes palatine tonsils, base of tongue/lingual tonsils, soft palate, and posterior pharyngeal wall. Tonsillar lymphatic density explains early nodal presentation. HPV-mediated OPSCC uses a distinct AJCC staging system because prognosis differs substantially from HPV-negative disease; clinical and pathologic nodal categories are not interchangeable. Retropharyngeal and level II/III nodal pathways should be considered in treatment planning.",
            "Workup includes complete mucosal examination, tissue diagnosis with p16 testing in appropriate OPSCC, contrast-enhanced neck imaging and staging chest/PET imaging as indicated. Assess dentition, nutrition, swallowing, speech, performance status, smoking history, and baseline hearing/renal function when cisplatin may be considered. Staging must use the HPV-mediated OPSCC schema rather than applying the HPV-negative larynx/oral-cavity rules.",
            "Early and selected intermediate disease may be treated with transoral surgery plus neck management or definitive radiation-based therapy; the best choice balances oncologic control against swallowing, speech, xerostomia, aspiration, and treatment burden. Pathology after surgery determines whether observation, radiation, or chemoradiation is needed. Positive margins and extranodal extension are major adverse features that can drive concurrent chemoradiation; other risk features may support postoperative radiation. De-intensification strategies should not be improvised outside evidence-based protocols simply because the tumor is HPV-positive.",
            "For transoral surgery, exposure and ability to obtain a functional oncologic resection matter as much as T stage. Neck treatment must address the expected nodal basins; when performing ipsilateral tonsillar surgery with a neck dissection, coordinate timing/technique with awareness of catastrophic hemorrhage risk and carotid relationships. Pathologic risk stratification after TORS determines whether surgery actually reduced adjuvant intensity; a technically successful resection that still requires full-dose chemoradiation may not have achieved the intended functional advantage.",
            "Boards/chief framework: HPV-associated OPSCC is biologically and prognostically distinct, but it is still cancer requiring disciplined staging and risk-adapted therapy. Know p16's staging role, the tendency toward cystic nodal presentation, and the postoperative features that escalate adjuvant treatment. HPV positivity improves prognosis; it does not give permission to undertreat outside validated pathways.",
            ["HPV OPSCC", "p16", "TORS", "cystic nodes", "adjuvant therapy", "extranodal extension", "positive margin"],
            ["NCCN Head & Neck v2.2026", "Pasha 6e"],
        ),
    ],

    "Thyroid / Parathyroid / Salivary": [
        _entry(
            ["Primary Hyperparathyroidism", "Parathyroid Localization"],
            "Primary hyperparathyroidism is a biochemical diagnosis of inappropriate PTH secretion, usually a single adenoma but sometimes multigland hyperplasia or, rarely, carcinoma. Confirm true hypercalcemic hyperparathyroidism before localization. Important mimics/contexts include familial hypocalciuric hypercalcemia, lithium exposure, vitamin-D deficiency, renal disease, and normocalcemic primary hyperparathyroidism after secondary causes are excluded. Localization studies identify where to operate; they do not establish whether the patient has the disease.",
            "Most superior glands arise from the fourth pouch and are relatively consistent near the posterior upper/mid thyroid, whereas inferior third-pouch glands migrate with the thymus and are more variable, including thyrothymic ligament and mediastinal locations. The recurrent laryngeal nerve and inferior thyroid artery are key relationships. A missing inferior gland should prompt a systematic search along the thyrothymic tract before random dissection; a missing superior gland may be posterior/paraesophageal or retroesophageal.",
            "Repeat albumin-corrected or ionized calcium and intact PTH; evaluate renal function, phosphate, vitamin D, bone density, nephrolithiasis/renal imaging when indicated, and 24-hour urine calcium/creatinine clearance when FHH is a concern. Once surgery is indicated, ultrasound and sestamibi/SPECT, 4D-CT, or other localization are chosen based on local expertise and prior surgery. Discordant or negative imaging does not negate a biochemical diagnosis and does not eliminate the option of bilateral exploration by an experienced surgeon.",
            "Parathyroidectomy is definitive therapy for symptomatic disease and for asymptomatic patients who meet accepted age, calcium, skeletal, renal, or other guideline criteria. A confidently localized sporadic single-gland process can be approached focally; suspected multigland disease, hereditary disease, lithium-associated disease, or nonlocalizing/discordant studies favor a broader exploration strategy. Correct vitamin-D deficiency thoughtfully and anticipate postoperative hypocalcemia, especially with severe bone disease/high turnover.",
            "In a focused operation, identify and remove the abnormal gland while protecting RLN and preserving normal parathyroid tissue; intraoperative PTH can confirm an adequate biochemical fall when used. A pre-excision baseline reflects secretion immediately before devascularization/removal and is useful when induction/manipulation changes the level; interpretation depends on the protocol and assay timing rather than a magic single number. If ioPTH fails to fall appropriately, pause before closing: verify timing/sample integrity, consider a missed second adenoma or multigland disease, and convert to systematic exploration when warranted. For bilateral exploration, identify the expected glands systematically rather than chasing imaging blindly.",
            "Boards/chief framework: diagnosis is biochemical; imaging is for localization. Inferior glands are more migratory because of thymic descent. Focused exploration is a strategy for a convincing single-gland problem, not a substitute for understanding multigland disease. Failure of ioPTH to fall should change the operation, and severe preoperative skeletal disease raises the risk of hungry-bone hypocalcemia after a technically successful cure.",
            ["primary hyperparathyroidism", "sestamibi", "4D CT", "ioPTH", "focused parathyroidectomy", "bilateral exploration", "hungry bone"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Medullary Thyroid Cancer", "Medullary Thyroid Carcinoma"],
            "Medullary thyroid carcinoma arises from parafollicular C cells and secretes calcitonin; it behaves differently from differentiated follicular-cell thyroid cancer and does not respond to radioactive iodine. Disease may be sporadic or hereditary through germline RET alterations/MEN2. Diarrhea/flushing can occur with advanced secretory disease. A diagnosis of MTC should immediately trigger hereditary-risk thinking rather than being treated as 'another papillary thyroid cancer.'",
            "MTC spreads to central and lateral cervical nodes and, when advanced, to mediastinum, lung, liver, and bone. The C cells are distributed throughout the thyroid but are concentrated in the upper poles, and multifocal/bilateral disease is more common in hereditary MEN2. Recurrent laryngeal nerve, trachea/esophagus, and carotid-space involvement determine resectability and operative morbidity in locally advanced disease.",
            "Measure basal calcitonin and CEA, obtain high-quality neck ultrasound, and stage with cross-sectional/distant imaging when marker level, symptoms, or nodal burden warrants it. Every patient with MTC should be offered germline RET testing. Before thyroid surgery in a RET/MEN2 patient, exclude pheochromocytoma biochemically first because an unrecognized catecholamine-secreting tumor can be lethal under anesthesia; assess hyperparathyroidism as part of MEN2A. Family testing and age/variant-specific prophylactic-thyroidectomy counseling follow the identified RET mutation.",
            "Primary resectable MTC is treated surgically with total thyroidectomy; central-compartment nodal management and therapeutic lateral neck dissection are based on clinical nodal disease, tumor burden, calcitonin level, imaging, and guideline risk assessment. RAI has no role. Persistent biochemical disease after surgery is not automatically an indication for blind re-exploration; localize structural disease and balance likelihood of cure against morbidity. Advanced progressive unresectable/metastatic RET-altered disease may be treated with selective RET-targeted systemic therapy in appropriate oncology pathways.",
            "Operate only after pheochromocytoma has been excluded/treated when MEN2 is possible. Preserve parathyroid and RLN function when oncologically safe, but grossly involved structures may require oncologic sacrifice/reconstruction planning. Lateral neck dissection is compartment-oriented for proven/strongly suspected nodal disease rather than node-picking. Postoperative calcitonin/CEA kinetics and imaging guide whether persistent disease is observed, localized for reoperation, or treated systemically.",
            "Boards/chief framework: MTC = calcitonin/CEA + RET/MEN2 + no radioactive iodine. The classic safety trap is operating on the thyroid before excluding pheochromocytoma. A biochemical marker rise is a surveillance signal, not permission for blind neck exploration; structural localization and expected morbidity determine the next intervention.",
            ["medullary thyroid cancer", "calcitonin", "CEA", "RET", "MEN2", "pheochromocytoma", "central neck", "RET inhibitor"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],

    "Pediatric Otolaryngology": [
        _entry(
            ["Pediatric OSA / Adenotonsillar Disease", "Pediatric OSA", "Pediatric Obstructive Sleep Apnea"],
            "Pediatric OSA is repetitive upper-airway obstruction during sleep and is not diagnosed simply by tonsil size or snoring. Adenotonsillar hypertrophy is common, but obesity, craniofacial restriction, neuromuscular disease, Down syndrome, mucopolysaccharidosis, nasal obstruction, laryngomalacia and multilevel collapse change severity and treatment response. Red flags include witnessed apneas, gasping, growth/behavioral problems, enuresis, cardiopulmonary consequences, and discordance between symptoms and routine exam.",
            "Obstruction can occur at adenoid/velopharyngeal, tonsillar/oropharyngeal, tongue-base, supraglottic and skeletal levels. Tonsils that look modest while awake can still contribute meaningfully during sleep, and a child with very large tonsils can have additional multilevel disease. Residual OSA after adenotonsillectomy should prompt phenotype/localization thinking rather than assuming recurrent tonsil tissue.",
            "Polysomnography is the gold standard when diagnostic/severity uncertainty matters and is particularly important in high-risk children or when symptoms/exam disagree. Interpret AHI with oxygen nadir, CO2/hypoventilation, arousal burden and comorbidity rather than using one number in isolation. Preoperative assessment should identify age, obesity, severe PSG findings, craniofacial/neuromuscular syndromes and cardiopulmonary disease that increase postoperative respiratory risk.",
            "Adenotonsillectomy is first-line for many children with adenotonsillar hypertrophy and clinically meaningful OSA. Intracapsular tonsil surgery can reduce pain/bleeding and speed recovery but leaves a small risk of regrowth/revision; extracapsular/total tonsillectomy provides complete tonsillar removal and may be preferred when recurrent infection, substantial tonsillar pathology, or concern about regrowth changes the balance. Persistent OSA requires reassessment for obesity, residual adenoid/tonsil tissue, tongue-base or supraglottic collapse, craniofacial restriction, and PAP/medical or additional surgical options.",
            "The operation is not finished when the tonsils are out: disposition is part of surgical planning. Young age, severe OSA/hypoxemia, major comorbidity, syndromic/neuromuscular disease and significant postoperative respiratory events support monitored admission rather than routine discharge. Intraoperative airway difficulty, opioid sensitivity and postoperative obstruction should be anticipated. For residual disease, DISE or targeted airway evaluation can guide lingual tonsillectomy, supraglottoplasty or other site-specific treatment instead of empiric repeat surgery.",
            "Boards/chief framework: snoring is a symptom, PSG defines physiology, and anatomy/comorbidity explain why treatment succeeds or fails. Know why intracapsular and extracapsular tonsillectomy are different tradeoffs rather than 'better versus worse.' The most important postoperative decision may be who needs monitored admission, especially when severe OSA, young age or syndromic disease makes a routine recovery pathway unsafe.",
            ["pediatric OSA", "adenotonsillectomy", "intracapsular", "extracapsular", "PSG", "postoperative admission", "residual OSA"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Pediatric Airway Foreign Body", "Airway Foreign Body"],
            "A sudden choking episode followed by unilateral wheeze, asymmetric breath sounds, persistent cough, recurrent focal pneumonia or unexplained stridor should trigger concern for airway foreign body even if the child later looks well. A normal chest radiograph does not exclude a radiolucent object. Acute complete obstruction is an airway-rescue problem; stable partial obstruction is a controlled rigid-bronchoscopy problem, not a reason for repeated blind extraction attempts.",
            "Objects lodge according to size, shape and airway geometry; bronchi are common, but laryngeal/tracheal foreign bodies can cause rapidly fatal obstruction. Organic objects such as nuts can swell and generate intense inflammation. Chronic retained objects can cause granulation, bronchiectatic change and recurrent infection, making delayed removal more difficult than the initial event.",
            "History is often the highest-yield test. Inspiratory/expiratory or bilateral decubitus radiographs may show air trapping, atelectasis, mediastinal shift or a radiopaque object, but negative imaging cannot overrule a convincing choking history. CT may help selected stable equivocal cases but should not delay bronchoscopy when suspicion is high. Flexible bronchoscopy can be diagnostic in some settings, but rigid bronchoscopy remains the definitive pediatric removal platform because it secures a working airway and allows instrumentation.",
            "If the child has effective cough/air movement, avoid blind finger sweeps and keep the child calm while mobilizing expertise. Complete obstruction requires age-appropriate choking maneuvers and emergency airway resuscitation. A suspected retained lower-airway foreign body generally warrants operative endoscopy; antibiotics/bronchodilators may treat secondary effects but do not remove the cause. After removal, reassess for a second object, mucosal injury, granulation, pneumothorax or persistent collapse/infection.",
            "Rigid bronchoscopy requires a shared surgeon-anesthesiologist ventilation plan before induction. Maintain oxygenation while preserving access to the airway; technique may use spontaneous or controlled ventilation depending on the case/team, but sudden conversion to complete obstruction, loss of the object, bleeding and inability to ventilate must be anticipated. Inspect the entire tracheobronchial tree after extraction when safe. Proximal sharp objects and friable organic material require deliberate orientation and extraction to avoid turning a partial obstruction into a complete one at the glottis.",
            "Boards/chief framework: convincing choking history beats a normal x-ray. Stable suspected lower-airway foreign body → controlled rigid bronchoscopy; complete obstruction → immediate rescue. The chief-level question is not merely which scope to use, but how the surgeon and anesthesiologist will oxygenate the child while manipulating an object that can migrate and suddenly occlude the airway.",
            ["pediatric airway foreign body", "rigid bronchoscopy", "air trapping", "choking", "ventilation", "radiolucent"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],

    "Laryngology / Voice / Swallowing": [
        _entry(
            ["Bilateral Vocal Fold Immobility", "Bilateral Vocal Fold Paralysis"],
            "Bilateral vocal-fold immobility usually presents as airway compromise/stridor with a surprisingly preserved voice when both folds rest near paramedian position. Do not assume bilateral recurrent-laryngeal-nerve paralysis: posterior glottic stenosis, cricoarytenoid fixation, neurologic disease, central lesions, prior intubation and post-thyroid surgery are important alternatives. The initial priority is whether the airway is safe, not whether the label is 'paralysis.'",
            "True bilateral neurogenic paralysis localizes anywhere from nucleus/vagus to bilateral RLNs; bilateral thyroid-bed injury is a classic peripheral cause. Posterior glottic stenosis instead fixes the arytenoids mechanically, commonly after prolonged intubation, and can mimic paralysis on flexible laryngoscopy. Cricoarytenoid joint fixation/inflammatory arthritis is another mechanical cause. Laryngeal EMG and operative palpation help separate neural from mechanical immobility when the diagnosis remains uncertain.",
            "Perform flexible laryngoscopy and document position, airway aperture, secretion handling and associated neurologic findings. Review recent neck/chest surgery and intubation history. If the cause is unexplained, image the vagal/RLN course appropriately rather than labeling it idiopathic. Laryngeal EMG can provide information about denervation/reinnervation and prognosis; direct laryngoscopy with arytenoid palpation is important when posterior glottic stenosis or joint fixation is suspected.",
            "Acute respiratory compromise requires airway stabilization, which may mean intubation or tracheostomy depending on anatomy and trajectory. When recovery is plausible after recent nerve injury, a reversible airway strategy may be preferable to immediate destructive glottic-widening surgery. Persistent bilateral neurogenic immobility can be managed with tracheostomy, posterior cordotomy/cordectomy, arytenoid procedures or selected reinnervation/pacing approaches, balancing airway against voice and aspiration. Treat a mechanical posterior glottic scar as a scar problem rather than a nerve problem.",
            "Before irreversible glottic widening, prove the mechanism and consider likelihood/timing of neural recovery. Posterior cordotomy enlarges the posterior airway but trades away some voice and may increase aspiration/granulation risk; arytenoidectomy can enlarge the airway further but has similar functional tradeoffs. Tracheostomy preserves the glottic mechanism while buying time but creates its own morbidity. If the arytenoids are fixed from posterior scar, scar release, dilation, grafting/flap or open reconstruction may be more appropriate than a procedure designed for denervated mobile joints.",
            "Boards/chief framework: bilateral immobility is a finding, not an etiology. First secure the airway, then distinguish neural paralysis from posterior glottic/arytenoid fixation before choosing an irreversible operation. Every airway-enlarging procedure trades airway gain against voice and aspiration; the right operation depends on mechanism, recovery potential and the patient's functional priorities.",
            ["bilateral vocal fold immobility", "posterior glottic stenosis", "arytenoid fixation", "cordotomy", "tracheostomy", "laryngeal EMG"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Posterior Glottic Stenosis / Arytenoid Fixation", "Posterior Glottic Stenosis"],
            "Posterior glottic stenosis is a cicatricial fixation process of the posterior commissure/interarytenoid region, most often after prolonged intubation injury. It can mimic bilateral vocal-fold paralysis because both folds appear immobile or poorly abducting. A history of difficult/prolonged intubation, posterior scar, impaired arytenoid excursion and preserved neural activity should move PGS above neurogenic paralysis in the differential.",
            "Pressure injury over the posterior glottis causes ulceration, granulation and scar that can progress from an interarytenoid band to fixation of one or both cricoarytenoid joints. The key anatomic distinction is mechanical tethering/fixation at the posterior commissure and joints versus denervation along the vagus/RLN pathway. Severity/classification reflects how extensively scar involves the posterior commissure and cricoarytenoid joints.",
            "Flexible laryngoscopy identifies posterior scar and reduced abduction but cannot always prove joint fixation. Direct laryngoscopy/bronchoscopy with palpation of each arytenoid is the decisive mechanical assessment; compare passive mobility side-to-side. Laryngeal EMG helps when neurogenic paralysis remains in the differential. Evaluate associated subglottic/tracheal stenosis in patients with prior prolonged intubation because multilevel injury changes reconstruction.",
            "Management depends on scar severity, joint mobility, airway need and voice/aspiration goals. Thin interarytenoid scar may respond to endoscopic lysis with measures to limit re-scarring; denser scar/joint fixation may require dilation, mucosal flap/graft, posterior cordotomy, arytenoid procedures or open posterior cricoid expansion/reconstruction. Tracheostomy is an airway strategy when obstruction is severe or reconstruction is staged. Repeated simple dilation without addressing mature posterior scar mechanics often gives transient benefit only.",
            "In the OR, palpate arytenoids before committing to a neurogenic-airway procedure. Endoscopic scar division should be paired with a plan to maintain epithelialized separation and minimize restenosis when possible. Bilateral cricoarytenoid fixation or thick mature scar may require open reconstruction; isolated unilateral fixation can permit a more limited approach. If concomitant subglottic stenosis exists, sequence or combine reconstruction based on which level limits the airway and whether one procedure will jeopardize the other.",
            "Boards/chief framework: the classic trap is calling PGS 'bilateral RLN paralysis.' History suggests it, but arytenoid palpation proves the mechanical problem. A scar band, fixed joint and denervated nerve are different mechanisms and deserve different operations. The more mature and joint-involving the scar, the less likely repeated dilation alone is to provide durable airway improvement.",
            ["posterior glottic stenosis", "arytenoid fixation", "intubation injury", "arytenoid palpation", "cordotomy", "posterior cricoid"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],

    "Facial Plastics / Trauma": [
        _entry(
            ["ZMC / Orbital Trauma", "Zygomaticomaxillary Complex Fracture", "Orbital Floor Fracture"],
            "ZMC/orbital trauma is assessed first for vision threat, then for globe position/motility, facial projection, occlusion, sensation and trismus. Decreased visual acuity, RAPD, proptosis, tense orbit, severe pain or rapidly progressive ophthalmoplegia is an orbital-compartment emergency, not an elective fracture problem. Infraorbital numbness, malar flattening, palpable step-offs, trismus and diplopia help define the fracture after the eye is safe.",
            "The ZMC functions as a tetrapod connecting zygomaticofrontal, zygomaticomaxillary, zygomaticosphenoid and zygomaticotemporal/arch relationships; accurate reduction at the sphenozygomatic region is particularly important for restoring three-dimensional position. Orbital floor/medial-wall defects alter orbital volume and can cause enophthalmos; muscle entrapment is different from edema-related diplopia. Pediatric trapdoor fractures may entrap muscle with minimal external bruising and trigger nausea/bradycardia through the oculocardiac reflex.",
            "Document visual acuity, pupils/RAPD, color vision when feasible, extraocular movement, diplopia fields, globe position and intraocular pressure when appropriate before swelling/sedation obscures the baseline. CT maxillofacial imaging defines ZMC displacement, orbital-wall defect and muscle/soft-tissue position. Urgent ophthalmology involvement is required for suspected globe injury, optic neuropathy or orbital compartment syndrome. Diplopia alone immediately after trauma is not an automatic indication for floor repair because edema can transiently limit movement.",
            "Observe nondisplaced fractures without functional/aesthetic consequence. Repair ZMC fractures when displacement causes malar deformity, unstable facial width/projection, trismus, significant orbital-volume change or associated functional problems. Orbital repair is considered for persistent functionally significant diplopia with restrictive findings/entrapment, clinically meaningful enophthalmos/hypoglobus or a defect expected to produce volume-related deformity; pediatric trapdoor entrapment requires more urgent release. Treat orbital compartment syndrome immediately with decompression rather than waiting for CT or definitive fracture repair.",
            "For ZMC ORIF, restore the zygoma in three dimensions before committing to orbital reconstruction; fixation points are chosen according to instability/displacement rather than a fixed number for every fracture. Recheck globe position and forced ductions after reduction and after implant placement. Orbital implants must restore the posterior ledge/contour without entrapping soft tissue or impinging the optic apex. Lateral canthotomy/cantholysis is a vision-saving emergency decompression procedure and should not be delayed for imaging when the clinical diagnosis of compartment syndrome is clear.",
            "Boards/chief framework: vision first, fracture second. ZMC repair is about restoring three-dimensional projection; orbital-floor repair is about entrapment and orbital volume, not CT defect size alone. A child with nausea/bradycardia and restricted upgaze after seemingly minor orbital trauma has a trapdoor fracture until proven otherwise. New visual decline changes the timeline from elective reconstruction to immediate decompression.",
            ["ZMC", "orbital floor", "orbital compartment syndrome", "RAPD", "trapdoor fracture", "forced duction", "enophthalmos"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Facial Nerve Reanimation", "Facial Reanimation"],
            "Facial reanimation begins by defining cause, completeness, duration, proximal nerve availability and whether the native facial musculature remains viable. Acute transection, recent denervation, long-standing paralysis and congenital absence are not the same reconstructive problem. Eye protection is urgent regardless of smile strategy. Progressive or unexplained paralysis requires evaluation for tumor or other cause rather than proceeding directly to cosmetic reanimation.",
            "The facial nerve exits the stylomastoid foramen and divides within the parotid; proximal donor availability determines whether direct repair/interposition is possible. Native mimetic muscle becomes progressively less receptive to reinnervation after prolonged denervation, so time since injury is a central decision variable. Masseteric and hypoglossal nerves are common motor donors; cross-face nerve grafting can provide spontaneous smile input but requires axonal growth across distance and often staged planning.",
            "Document House-Brackmann or a more granular facial-function assessment, synkinesis, corneal exposure, Bell phenomenon, lower-lid position and oral competence. Review operative/trauma timing and determine whether the nerve was sacrificed, repaired, anatomically intact or of uncertain continuity. Electrodiagnostics can help selected acute/prognostic questions; imaging is required when neoplasm or unexplained proximal neuropathy is possible. Assess goals explicitly: eye protection, resting symmetry, oral competence, spontaneous versus strong smile, and tolerance for staged surgery.",
            "Immediate clean nerve transection is best treated with tension-free primary neurorrhaphy when possible or interposition graft when a gap prevents it. When the proximal facial nerve is unavailable but native muscles remain viable, nerve transfers such as masseteric-to-facial or hypoglossal-facial strategies can restore movement; cross-face grafting improves potential spontaneity but is slower/weaker and often paired with other strategies. Long-standing denervation with nonviable native muscles requires a new motor unit, commonly free functional muscle transfer. Static slings, brow/lid procedures and eyelid weighting remain valuable adjuncts or definitive treatment for patients who cannot undergo dynamic reconstruction.",
            "Timing drives the operation. Early after known transection, repair the nerve rather than waiting for established paralysis. In intermediate-duration paralysis with viable muscle, connect a motor source before irreversible atrophy; donor choice trades power, spontaneity and morbidity. In chronic paralysis, gracilis or other free functional muscle transfer can be powered by masseteric nerve for strong reliable activation, cross-face input for spontaneity, or dual innervation in selected strategies. Protect the cornea throughout with upper-lid weight, lower-lid tightening, lubrication or tarsorrhaphy as needed rather than postponing eye treatment until smile reconstruction is complete.",
            "Boards/chief framework: facial reanimation is a timing-and-motor-unit problem. Viable native muscle + available proximal nerve favors repair/grafting; viable muscle without proximal input favors nerve transfer; chronically denervated nonviable muscle requires muscle transfer. Masseteric input is powerful and fast, cross-face input is more spontaneous but slower/weaker. Static procedures are not failures—they solve resting symmetry and protection when dynamic reconstruction is impossible or incomplete.",
            ["facial reanimation", "masseteric nerve transfer", "hypoglossal facial", "cross face nerve graft", "gracilis", "eyelid weight", "static sling"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],

    "Sleep Surgery": [
        _entry(
            ["DISE", "Drug-Induced Sleep Endoscopy"],
            "Drug-induced sleep endoscopy is a dynamic localization tool for upper-airway collapse in selected OSA patients, especially when choosing among surgical options or explaining persistent disease. It does not diagnose OSA and does not replace polysomnography. The useful question is not merely 'where is it narrow,' but which structures collapse, in what direction, at what degree, and whether maneuvers such as jaw/tongue advancement change the pattern.",
            "Describe collapse systematically at velum, oropharyngeal lateral walls, tongue base and epiglottis using a consistent framework such as VOTE. Velar collapse may be anteroposterior, lateral or complete concentric; tongue-base collapse and independent epiglottic collapse have different procedural implications. Lateral-wall collapse can explain failure of isolated palate/tongue procedures. Sedation depth matters because excessive anesthesia can create nonphysiologic collapse.",
            "DISE is most useful after OSA severity and non-surgical treatment history are already established. Review PSG, BMI, prior surgery, craniofacial anatomy, tonsils, nasal obstruction and PAP/oral-appliance tolerance first. During DISE document sedation protocol, oxygenation, collapse site/pattern/degree and response to maneuvers. Interpret findings as one component of selection rather than a standalone mandate for surgery.",
            "Use DISE findings to tailor therapy: palatal collapse may support palate-directed surgery; large tonsils support tonsillectomy; tongue-base obstruction may support lingual-tonsil/tongue-base strategies; epiglottic collapse may need epiglottis-specific treatment; multilevel collapse often requires combination therapy. Complete concentric velar collapse is a major unfavorable/exclusionary phenotype for conventional unilateral hypoglossal nerve stimulation pathways. Persistent OSA after prior surgery should be re-localized rather than reflexively repeating the same operation.",
            "The technical goal is to reproduce a sleep-like obstructive pattern safely without oversedation. Maintain spontaneous ventilation, titrate sedative gradually, and avoid interpreting transient induction-stage collapse as the patient's stable phenotype. Jaw thrust or mandibular advancement during DISE can estimate response to airway advancement but is not a perfect predictor. Record video/structured findings so the operative plan can be defended and compared over time.",
            "Boards/chief framework: PSG tells you how much OSA; DISE helps tell you how the airway collapses. Collapse direction matters, not just level. Complete concentric velar collapse should redirect conventional HNS planning. DISE is valuable when it changes procedure selection; it is not a ritual that makes every OSA patient a surgical candidate.",
            ["DISE", "VOTE", "velum", "lateral wall", "tongue base", "epiglottis", "complete concentric collapse", "HNS"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Hypoglossal Nerve Stimulation", "Hypoglossal Nerve Stimulator", "Upper Airway Stimulation"],
            "Hypoglossal nerve stimulation is a selection-dependent treatment for obstructive, not central-predominant, sleep apnea in patients who cannot tolerate or benefit adequately from PAP. Candidacy is not based on AHI alone: BMI, central-event burden, upper-airway anatomy, prior treatment and DISE collapse phenotype matter. Complete concentric collapse at the velum is a key adverse/exclusionary finding for conventional unilateral systems.",
            "Therapy works by recruiting protrusor/stiffening tongue musculature through selected hypoglossal nerve branches while avoiding retrusor-dominant activation. The cuff is placed on appropriate distal hypoglossal branches after branch mapping; inclusion of protrusor branches and exclusion of retrusor branches determines whether stimulation opens or worsens the airway. A respiratory-sensing lead times stimulation to inspiration, and the pulse generator coordinates sensing and stimulation.",
            "Confirm diagnostic PSG and quantify obstructive versus central events, PAP intolerance/failure, BMI and other payer/device-specific candidacy parameters. Examine tonsils, palate, tongue base and craniofacial anatomy; perform DISE to exclude an unfavorable complete-concentric velar phenotype in standard pathways. Discuss expectations: HNS reduces OSA severity in appropriately selected patients but is not guaranteed to normalize AHI and requires activation, titration and ongoing adherence.",
            "Implantation is appropriate only after noninvasive therapy and anatomy/phenotype have been considered. Postoperative activation occurs after healing, followed by gradual amplitude adjustment and formal titration/efficacy assessment. Persistent residual OSA should prompt review of adherence, stimulation settings, tongue motion, lead/cuff function, weight/anatomic changes and residual collapse rather than simply increasing amplitude indefinitely.",
            "Intraoperatively identify the hypoglossal nerve and functional branch pattern, place the stimulation cuff to favor protrusor activation, verify tongue response, position the sensing lead appropriately and test the complete system before closure. Inclusion/exclusion errors can produce mixed or retrusive tongue motion and suboptimal therapy. Protect the hypoglossal nerve and avoid excessive cuff/lead tension. Revision is considered for lead/cuff malfunction, migration, infection or persistent mechanical/device problems—not merely an imperfect AHI without a full programming/anatomic reassessment.",
            "Boards/chief framework: HNS success begins with selection and branch anatomy. DISE complete-concentric palatal collapse, excessive central apnea burden or inappropriate anatomy should stop the implant pathway. In the OR, the critical technical concept is selective protrusor recruitment; after surgery, programming and adherence are part of the therapy rather than afterthoughts.",
            ["hypoglossal nerve stimulation", "HNS", "DISE", "protrusor", "retrusor", "respiratory sensing", "programming"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],

    "General ENT / Emergencies": [
        _entry(
            ["Tracheostomy Emergency", "Tracheostomy Emergencies"],
            "A tracheostomy patient with acute respiratory distress should be approached as an airway emergency with a mechanical differential first: mucus plugging, tube obstruction, displacement/false passage, cuff or ventilator problem, pneumothorax and bleeding. Inability to pass a suction catheter is a powerful clue that the tube is obstructed or not in the tracheal lumen. Subcutaneous emphysema with ineffective ventilation should make you stop forcefully bagging through a potentially false passage.",
            "The age of the tract changes rescue. A fresh/immature tracheostomy can close or false-pass easily, so blind tube replacement can make the situation worse. A mature tract is usually safer to recannulate. A total-laryngectomy stoma is fundamentally different: there is no upper-airway continuity, so oral/nasal ventilation will not oxygenate the patient; oxygenation/intubation must occur through the stoma.",
            "Call airway help while immediately giving oxygen to both potential routes when anatomy is uncertain. Remove speaking valve/inner cannula, assess the tube, attempt suction and deflate the cuff when appropriate. If ventilation remains ineffective, remove an obstructed/displaced tracheostomy tube and oxygenate via the safest patent route based on whether the upper airway is connected. Do not wait for chest radiography before rescuing a failing airway. Once stable, bronchoscopy/endoscopy can confirm tube position and identify obstruction or injury.",
            "Management is algorithmic: oxygenate → remove simple obstructions → determine whether the trach is patent/in the airway → remove a nonfunctional tube when necessary → re-establish ventilation via upper airway or stoma according to anatomy. In a fresh tract, prioritize oral intubation when the upper airway is usable rather than repeated blind stoma attempts; if the airway cannot be accessed from above, controlled stoma recannulation with appropriate expertise is required. Treat the underlying cause after oxygenation is restored.",
            "For early postoperative tracheostomy displacement, do not blindly probe a fresh tract. Use direct visualization, bronchoscopy, stay sutures or controlled surgical exposure as appropriate to re-enter the trachea. Mature tracts can often accept a replacement tube or smaller tube more safely. Significant tracheostomy hemorrhage—especially a sentinel bleed weeks after placement—raises concern for tracheo-innominate fistula: hyperinflate the cuff/temporize digitally if needed while mobilizing immediate definitive vascular/surgical control.",
            "Boards/chief framework: first ask whether a suction catheter passes and whether the tube is actually in the airway. Fresh tract and mature tract are different rescue problems. Tracheostomy and laryngectomy stomas are not interchangeable: a laryngectomy patient has no usable oral route. In a crashing patient, oxygenation outranks obtaining imaging or preserving the current tube.",
            ["tracheostomy emergency", "false passage", "fresh tract", "mature tract", "laryngectomy", "suction catheter", "tracheo-innominate fistula"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
        _entry(
            ["Postoperative Neck Hematoma", "Post-thyroidectomy Neck Hematoma", "Post-Thyroidectomy Hematoma / Airway"],
            "Rapid neck swelling, pressure/tightness, dysphagia, voice change, anxiety, stridor or respiratory distress after thyroid/parathyroid or other neck surgery is a compressive hematoma until proven otherwise. External swelling can underestimate deep pressure, and oxygen saturation may remain normal until late. This is a clinical diagnosis: do not send a deteriorating patient to CT to prove an expanding hematoma.",
            "Bleeding raises pressure within a relatively noncompliant postoperative neck, causing venous/lymphatic obstruction and progressive pharyngeal/laryngeal edema in addition to direct tracheal compression. This explains why the airway can remain difficult even after the clot is released. Common bleeding sources vary by operation but include thyroid pedicles, strap/muscle vessels and venous structures; the immediate emergency is decompression rather than source identification.",
            "At the bedside assess wound tension/expansion, voice, swallowing, respiratory effort and stridor while calling the surgeon/anesthesia/OR team. Obtain IV access and resuscitate, but do not delay decompression for labs or imaging when airway compromise is evolving. Flexible laryngoscopy may help in a stable patient but is not required before opening a tense expanding wound in a deteriorating patient.",
            "A stable small nonexpanding collection can sometimes be observed with close surgical reassessment, but a rapidly expanding hematoma or any airway symptoms require immediate action. If the patient is deteriorating and transfer to the OR is not instantaneous, open the incision at bedside, release skin/subcutaneous/platysmal and deeper closure as needed, evacuate clot, and relieve pressure while airway and definitive operative control are mobilized. Treat hypocalcemia or isolated RLN dysfunction only after excluding the mechanically dangerous hematoma pattern.",
            "After emergency decompression, return to the OR for systematic evacuation, irrigation and hemostasis. Plan airway management assuming supraglottic/glottic edema and distorted anatomy; decompression does not guarantee easy intubation. Awake or advanced airway techniques and surgical airway backup may be necessary depending on physiology. Search the operative bed methodically rather than blindly clamping; secure the actual source and reassess hemostasis under appropriate blood pressure/Valsalva conditions before reclosure.",
            "Boards/chief framework: post-neck-surgery hematoma with airway symptoms is one of the rare situations in which opening the wound immediately at bedside can be lifesaving. CT is a delay, not a diagnostic requirement. The airway can worsen from edema even after decompression, so wound release and airway planning occur in parallel, followed by formal OR hemostasis.",
            ["postoperative neck hematoma", "thyroidectomy", "airway", "bedside decompression", "stridor", "return to OR"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
}


def apply_cross_domain_depth_v160(deep_modules):
    """Apply known-title in-place enrichments without risking a boot failure.

    Returns a small report so audits can verify what matched. An unmatched title
    is intentionally reported rather than used as a reason to take down the app.
    """
    applied = []
    missing = []
    for domain, patches in PATCHES_V160.items():
        modules = deep_modules.get(domain, [])
        for patch in patches:
            found = None
            for module in modules:
                if module.get("topic") in patch["candidates"]:
                    found = module
                    break
            if found is None:
                missing.append((domain, patch["candidates"]))
                continue
            found.update(patch["fields"])
            applied.append((domain, found.get("topic")))
    return {"applied": applied, "missing": missing}
