"""v16.2 — Cross-domain Deep Curriculum enrichment, pass 3.

A third high-yield concept per non-Otology domain. This continues the same
in-place strategy: deepen existing six-layer modules instead of inflating the
canonical topic count.
"""


def _entry(candidates, recognize, localize, workup, manage, operate, teach, tags, sources=None):
    return {
        "candidates": tuple(candidates),
        "fields": {
            "recognize": recognize,
            "localize": localize,
            "workup": workup,
            "manage": manage,
            "operate": operate,
            "teach": teach,
            "tags": list(tags),
            **({"source_basis": list(sources)} if sources else {}),
        },
    }


PATCHES_V162 = {
    "Rhinology / Allergy / Skull Base": [
        _entry(
            ["Chronic Rhinosinusitis", "Chronic Rhinosinusitis (CRS)"],
            "Chronic rhinosinusitis requires at least 12 weeks of compatible symptoms plus objective evidence of sinonasal inflammation on endoscopy or CT; symptoms alone do not establish CRS. Separate CRSwNP from CRSsNP and recognize important phenotypes/endotypes such as type-2/eosinophilic disease, asthma/AERD, odontogenic disease, fungal disease, immunodeficiency and ciliary disorders because recurrence risk and treatment differ. Unilateral disease, bleeding, cranial neuropathy or destructive change should trigger a tumor/alternate-diagnosis pathway rather than routine CRS treatment.",
            "Disease reflects impaired mucociliary function and persistent mucosal inflammation across the ostiomeatal complex and involved sinuses rather than simply 'blocked holes.' The frontal recess, maxillary natural ostium/infundibulum, sphenoethmoidal recess and ethmoid partitions are functional pathways that surgery seeks to restore while preserving mucosa. Polyps often represent diffuse inflammatory biology rather than a single local obstruction, explaining why technically open sinuses can still recur.",
            "Confirm objective disease with nasal endoscopy and/or CT after an appropriate medical-treatment context. CT is principally an anatomic/inflammatory map for diagnosis and surgical planning; incidental mucosal thickening in an asymptomatic patient is not CRS. Evaluate allergy/asthma/AERD, dental source, immune deficiency or ciliary disease when the history suggests them rather than ordering universal panels. In CRSwNP, document polyp burden, smell function, systemic-steroid exposure and prior surgery because these help decide when biologic therapy enters the discussion.",
            "Baseline management uses saline irrigation plus topical intranasal corticosteroid therapy, with short systemic-steroid courses selectively for severe polyp inflammation; antibiotics are reserved for appropriate acute bacterial exacerbation or selected culture-directed situations rather than chronic empiric use for every CRS patient. Endoscopic sinus surgery is considered when meaningful symptoms/objective disease persist despite appropriate medical therapy or when anatomy/complication demands intervention. In severe recurrent type-2 CRSwNP, biologic therapy is an option based on disease burden, comorbid asthma/AERD, prior surgery/systemic-steroid need, biomarkers and patient preference/cost; biologics and surgery are complementary tools rather than mutually exclusive ideologies.",
            "ESS should create durable access/ventilation and topical-therapy delivery while respecting skull base, orbit, lacrimal system and major vessels. Extent should match disease: limited focal disease does not require maximal surgery, whereas diffuse recurrent polyp disease may benefit from broader complete ethmoid/frontal/sphenoid access to support postoperative topical therapy. Preserve mucosa where possible and identify natural ostia to avoid recirculation. Revision surgery begins by understanding why prior treatment failed—scar, retained partitions, missed natural ostium, frontal-recess stenosis, persistent inflammatory biology or an incorrect original diagnosis.",
            "Boards/chief framework: CRS = symptoms for at least 12 weeks + objective inflammation. Then phenotype it. Surgery fixes access/anatomy and improves delivery of medical therapy; it does not cure systemic type-2 inflammation. In recurrent CRSwNP, the real decision is how to combine surgery, topical therapy and biologics based on phenotype, prior treatment burden and patient goals.",
            ["CRS", "CRSwNP", "CRSsNP", "AERD", "type 2 inflammation", "ESS", "biologics", "frontal recess"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Head & Neck Oncology": [
        _entry(
            ["Neck Dissection", "Neck Dissection Principles", "Neck Dissection Levels"],
            "Neck dissection is compartmental oncologic surgery, not removal of visibly abnormal nodes. Selective, modified radical and radical dissections are defined by which lymphatic levels and nonlymphatic structures are removed or preserved. The operation is chosen from primary-site drainage patterns, clinical/radiographic nodal burden, prior treatment and need for therapeutic versus elective neck control. A radiographically small node can still matter if it lies in a high-risk basin; a large node adherent to CN XI/IJV/SCM may change preservation decisions.",
            "Know levels by boundaries and structures, not memorized labels alone: level I around submandibular/submental triangles, II along upper jugular chain with CN XI relationship, III/IV along mid/lower jugular chain, V in posterior triangle and VI/VII in central/upper mediastinal compartments. Level IIb sits posterior/superior to CN XI and its dissection can increase shoulder morbidity. The carotid sheath, vagus, sympathetic chain, phrenic nerve, brachial plexus, thoracic duct on the left and marginal mandibular/hypoglossal nerves are recurrent danger structures.",
            "Preoperative imaging defines nodal levels, ENE suspicion, carotid involvement and distant disease. Determine whether neck treatment is elective or therapeutic and whether radiation/chemoradiation is primary or postoperative. In a previously irradiated neck, assess wound/flap needs, carotid exposure risk and fibrosis. Document baseline shoulder, tongue and lower-cranial-nerve function when relevant. Pathology should preserve level-specific orientation because nodal number, level and ENE drive prognosis/adjuvant therapy.",
            "Use selective neck dissection when oncologic risk is confined to predictable levels and preservation does not compromise control. Modified radical dissection removes the comprehensive lymphatic package while preserving one or more of CN XI, IJV or SCM; radical dissection removes all three when oncologically required. Do not sacrifice a functioning nonlymphatic structure merely because the operation is 'comprehensive,' but do not preserve a structure grossly invaded by tumor at the expense of margin/control. Post-treatment salvage neck surgery is more selective and morbidity-sensitive than routine upfront surgery and should be based on residual structural disease rather than historical N stage alone.",
            "Develop reliable planes around carotid/vagus and protect CN XI early enough to avoid traction injury. When dissecting level IIb, mobilize tissue around CN XI gently and question whether IIb is oncologically required for that primary pattern rather than treating it as automatic. On the left low neck, identify/protect thoracic duct and repair a recognized chyle leak at the operation. Preserve the marginal mandibular nerve at level I, hypoglossal nerve around digastric/carotid region, phrenic/brachial plexus in level V and sympathetic chain posterior to sheath unless oncologic involvement requires sacrifice. Plan flap coverage when major vessel exposure or irradiated skin makes primary closure unsafe.",
            "Boards/chief framework: neck-dissection nomenclature tells you what is removed; oncologic anatomy tells you why. Selective does not mean inadequate and radical does not mean better. CN XI preservation is a functional priority when oncologically safe, IIb dissection has shoulder consequences, and left level IV carries thoracic-duct risk. Every sacrificed structure should have an oncologic reason.",
            ["neck dissection", "levels", "CN XI", "IIb", "thoracic duct", "selective", "modified radical", "radical"],
            ["NCCN Head & Neck v2.2026", "Pasha 6e"],
        ),
    ],
    "Thyroid / Parathyroid / Salivary": [
        _entry(
            ["Differentiated Thyroid Cancer", "Papillary Thyroid Cancer", "Differentiated Thyroid Carcinoma"],
            "Differentiated thyroid cancer (primarily papillary and follicular-derived cancers) is risk-stratified rather than treated with automatic total thyroidectomy. Papillary cancer commonly spreads through lymphatics to central/lateral neck nodes; follicular cancer more often spreads hematogenously. Extrathyroidal extension, aggressive histology, nodal/distant disease, contralateral disease and recurrence risk matter more than the word 'cancer' alone when choosing treatment extent.",
            "The central compartment surrounds the thyroid/trachea between carotid sheaths and includes prelaryngeal, pretracheal and paratracheal nodes; lateral metastatic disease follows jugular-chain levels. The recurrent laryngeal nerve, external branch of superior laryngeal nerve and parathyroid blood supply are the key structures that determine functional morbidity. Tumor invading trachea/esophagus/RLN requires distinction between superficial adherence and true structural invasion because the operation changes substantially.",
            "High-quality ultrasound evaluates the primary and central/lateral nodes; suspicious nodes should be sampled when results will change the operation. Use cytology/molecular information, tumor size/sonographic features and patient risk factors to define the preoperative plan. Cross-sectional imaging is valuable for bulky nodal disease, invasive tumors or substernal/mediastinal extension. Preoperative laryngoscopy is important with voice symptoms, prior neck surgery, invasive/posterior tumor or other RLN-risk contexts because preexisting paralysis changes staging and nerve-management decisions.",
            "Lobectomy is sufficient for many appropriately selected low-risk intrathyroidal differentiated cancers, while total thyroidectomy is favored when bilateral/multifocal burden, larger/high-risk primary disease, gross extrathyroidal extension, clinically significant nodal/distant disease or a need for postoperative radioactive-iodine/thyroglobulin strategy makes it advantageous. Therapeutic central/lateral compartment dissection is performed for clinically involved nodes; prophylactic central dissection is not a reflex for every cN0 low-risk PTC. Postoperative RAI is risk-adapted rather than universal. Surveillance integrates neck ultrasound and thyroglobulin/anti-thyroglobulin antibodies after total-thyroid/appropriate treatment context.",
            "Identify and preserve RLN, EBSLN and viable parathyroids whenever oncologically safe. If an RLN is functioning preoperatively but appears adherent, distinguish peelable contact from gross neural invasion; sacrificing a functioning nerve requires an oncologic reason and reconstruction/voice plan. Gross tracheal invasion may require shave, window or segmental resection according to depth/extent rather than a single technique. Lateral neck disease is treated with compartment-oriented dissection rather than berry-picking. Reoperative disease requires deliberate localization and acceptance that biochemical detectability alone is not enough reason for a high-morbidity exploration without a structural target.",
            "Boards/chief framework: differentiated thyroid cancer management is risk-adapted. Lobectomy versus total thyroidectomy, nodal dissection and RAI are separate decisions with different indications. Therapeutic nodes deserve compartment surgery; cN0 low-risk disease does not automatically deserve prophylactic central dissection. Preserve a functioning RLN unless true oncologic invasion justifies sacrifice, and use structural recurrence—not thyroglobulin anxiety alone—to plan reoperation.",
            ["differentiated thyroid cancer", "papillary thyroid cancer", "lobectomy", "total thyroidectomy", "central neck dissection", "RAI", "thyroglobulin", "RLN"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Pediatric Otolaryngology": [
        _entry(
            ["Laryngomalacia", "Pediatric Laryngomalacia"],
            "Laryngomalacia is dynamic inspiratory supraglottic collapse, usually presenting in early infancy with inspiratory stridor that worsens with feeding, agitation or supine positioning. Most cases are mild and self-limited, but severity is defined by physiology—not loudness of stridor. Apnea/cyanosis, significant retractions, feeding difficulty/aspiration, failure to thrive, hypoxemia, pulmonary hypertension or cor pulmonale identify severe disease requiring escalation. Synchronous airway lesions and neurologic/cardiac comorbidity explain atypical or refractory cases.",
            "Collapse can involve shortened aryepiglottic folds, prolapsing arytenoid mucosa and/or an omega-shaped retroflexed epiglottis; these patterns often coexist. The supraglottic obstruction is dynamic, so awake flexible laryngoscopy is particularly informative. Poor tone/sensorimotor integration and anatomic factors contribute to pathogenesis; reflux may coexist and exacerbate symptoms but should not be treated as the universal primary cause.",
            "Flexible nasolaryngoscopy confirms dynamic collapse and excludes obvious alternative laryngeal disease. Evaluate growth trajectory and feeding/aspiration; use swallow study/FEES when aspiration symptoms or recurrent pulmonary issues warrant it. PSG is useful when sleep-related obstruction severity is unclear, especially in syndromic/neurologic infants. Direct laryngoscopy/bronchoscopy is appropriate before surgery or when symptoms are severe/atypical to assess synchronous lesions such as SGS, tracheomalacia or vocal-fold immobility.",
            "Observe and counsel families for mild disease with adequate growth and no significant hypoxemia/feeding morbidity. Address feeding strategy and comorbid conditions; acid suppression should not be automatic without a clear indication. Supraglottoplasty is indicated for severe laryngomalacia causing clinically important obstruction, cyanotic/apneic events, failure to thrive, significant feeding/aspiration compromise or cardiopulmonary consequence. Persistent OSA after supraglottoplasty requires reassessment for residual/multilevel obstruction rather than assuming the first surgery was technically inadequate.",
            "Supraglottoplasty is tailored to the dominant collapse pattern: divide shortened aryepiglottic folds, reduce redundant arytenoid/supraglottic mucosa judiciously and/or address epiglottic prolapse while preserving protective mucosa and avoiding bilateral deep injury. Over-resection risks supraglottic stenosis and aspiration. Neurologic disease, significant aspiration and syndromic multilevel obstruction predict less straightforward outcomes and may require staged/multilevel treatment or temporary tracheostomy in rare severe cases.",
            "Boards/chief framework: the severity of laryngomalacia is determined by feeding, growth, oxygenation and cardiopulmonary effects—not by how noisy the infant sounds. Mild disease is observed; severe physiologic disease gets supraglottoplasty. Always consider synchronous airway lesions and multilevel obstruction when the presentation is atypical or the child fails an otherwise appropriate operation.",
            ["laryngomalacia", "supraglottoplasty", "failure to thrive", "aspiration", "synchronous airway lesion", "infant stridor"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Laryngology / Voice / Swallowing": [
        _entry(
            ["Dysphagia / Aspiration", "Aspiration after Head and Neck Surgery", "Oropharyngeal Dysphagia"],
            "Dysphagia is a symptom requiring localization: oral preparatory/oral transit, pharyngeal, pharyngoesophageal/UES or esophageal. Aspiration may occur before, during or after the swallow and may be silent; cough is therefore neither necessary nor sufficient. Etiologies include neurologic disease, structural obstruction, weakness/sensory loss, prior radiation/surgery, Zenker/UES dysfunction, vocal-fold immobility and systemic frailty. Weight loss, recurrent pneumonia, dehydration and inability to handle secretions are safety red flags.",
            "Effective swallowing requires tongue propulsion, timely pharyngeal trigger, base-of-tongue/pharyngeal contraction, hyolaryngeal elevation, laryngeal closure and UES opening. Failure at different components produces different residue/aspiration patterns: poor tongue-base/pharyngeal drive causes vallecular/pharyngeal residue; reduced laryngeal closure increases airway invasion; impaired UES opening causes post-swallow residue/regurgitation. Post-radiation fibrosis can impair several mechanisms simultaneously.",
            "Start with history, oral/cranial-nerve examination, voice/airway status and nutritional/pulmonary consequences. FEES directly assesses secretions, laryngeal sensation, penetration/aspiration and residue repeatedly at bedside but has a brief white-out during the swallow and does not visualize the cervical esophagus. Modified barium swallow/VFSS shows bolus flow across oral/pharyngeal phases, timing and UES opening and permits testing compensatory maneuvers; esophagram/endoscopy/manometry answer different distal-esophageal/UES questions. Choose the study from the suspected mechanism rather than ordering every test.",
            "Management separates compensation from rehabilitation. Compensation immediately reduces risk—posture, bolus size/consistency changes, pacing and selected maneuvers—without necessarily restoring physiology. Rehabilitation targets strength, range, coordination or airway protection through therapy matched to the deficit. Treat structural causes when present; improve oral hygiene/nutrition and balance aspiration risk against quality of life rather than assuming feeding-tube placement eliminates aspiration. Pneumonia risk depends on aspirate burden, oral flora, host reserve and secretion management, not aspiration on a study alone.",
            "Procedures should target a demonstrated mechanism: vocal-fold medialization for glottic insufficiency, dilation/myotomy/Botox for selected UES dysfunction, diverticulectomy/endoscopic treatment for symptomatic Zenker, scar/stricture treatment for structural stenosis and aspiration-prevention surgery only for severe refractory cases where airway protection outweighs voice. In irradiated patients, distinguish focal stenosis that can be dilated from global pharyngeal weakness/fibrosis where repeated dilation will not fix the primary physiology.",
            "Boards/chief framework: FEES and MBS are complementary, not competing tests. FEES excels at secretion/laryngeal assessment and repeat bedside evaluation; MBS shows bolus biomechanics and UES passage. Treat the mechanism that causes aspiration or residue. A feeding tube bypasses oral intake but does not prevent aspiration of saliva/reflux, so it is a nutrition strategy—not an aspiration cure.",
            ["dysphagia", "aspiration", "FEES", "MBS", "VFSS", "UES", "compensation", "rehabilitation", "silent aspiration"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Facial Plastics / Trauma": [
        _entry(
            ["Mandibular Biomechanics and Occlusion", "Mandible Fracture", "Mandibular Fractures"],
            "Mandible-fracture management begins with occlusion and function. New malocclusion, trismus, V3 numbness, step-off, mobility and intraoral laceration identify clinically important injury; tooth-bearing fractures communicating with the oral cavity are open fractures. Bilateral condylar fractures classically shorten posterior ramus height and produce an anterior open bite, while unilateral condylar injury can create deviation and asymmetric occlusion. Always look for a second fracture because the mandible behaves as a ring.",
            "Biomechanics vary by location and muscle pull. The superior border is a tension zone and inferior border a compression zone in many body fractures; favorable versus unfavorable fracture orientation describes whether muscle forces reduce or displace fragments. Load-sharing fixation requires adequate bony contact/comminution control; load-bearing reconstruction bridges comminuted/segmental defects when the native bone cannot reliably share force. The inferior alveolar nerve travels within the body/angle and is at risk during injury and fixation.",
            "CT maxillofacial imaging defines fracture pattern, displacement, comminution and dentition, but the preinjury occlusion—using wear facets, patient report, dental records and examination—is the reconstructive target. Document V3 sensation and facial nerve function before treatment. Assess tooth viability, infection, open wounds and associated midface/cervical-spine injuries. Condylar fractures require evaluation of ramus height, displacement/dislocation, bilateral involvement and the patient's ability to mobilize the jaw.",
            "Closed treatment/MMF is appropriate for selected nondisplaced/favorable fractures with reproducible occlusion, some pediatric fractures and many condylar injuries where functional therapy can restore motion. ORIF is favored when reduction/occlusion cannot be maintained closed, displacement is significant, fractures are unfavorable/open, there is comminution/atrophy, multiple injuries make MMF impractical or early function is important. Condylar ORIF is selective—consider severe displacement/dislocation, loss of ramus height with malocclusion, bilateral injuries that cannot be managed functionally, foreign body/open injury or other specific indications—rather than automatic for every radiographic condylar fracture.",
            "Establish/reproduce occlusion before definitive plating whenever possible. Choose fixation according to load-sharing versus load-bearing mechanics and fracture site rather than placing the same plate everywhere. Protect tooth roots and inferior alveolar canal. Angle/body fractures often require tension-band principles plus inferior-border stability when forces demand it; severely comminuted/atrophic defects may need reconstruction plates. After fixation, release MMF and verify passive reproducible occlusion and mandibular range before closure—an x-ray-perfect reduction with a wrong bite is a failed operation.",
            "Boards/chief framework: occlusion is your reduction gauge and biomechanics choose fixation. An anterior open bite after trauma should trigger a search for bilateral condylar fractures. Closed versus open treatment is a functional/stability decision, not a prestige hierarchy. Know load-sharing versus load-bearing and always verify the bite after plating.",
            ["mandible fracture", "occlusion", "condylar fracture", "load sharing", "load bearing", "MMF", "ORIF", "inferior alveolar nerve"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "Sleep Surgery": [
        _entry(
            ["Maxillomandibular Advancement", "MMA", "Maxillomandibular Advancement for OSA"],
            "Maxillomandibular advancement treats OSA by enlarging and tensioning the retropalatal and retrolingual airway through skeletal advancement rather than addressing only one soft-tissue level. It is especially powerful for severe/multilevel obstruction, craniofacial restriction or patients who need a high-efficacy surgical option after PAP intolerance/failure. A normal-looking jaw does not exclude benefit, but skeletal/dental anatomy and willingness to accept facial/occlusal change matter.",
            "Le Fort I maxillary and bilateral sagittal split mandibular osteotomies advance the facial skeleton, moving attached palate/tongue-base/suprahyoid soft tissues anteriorly and increasing airway caliber/stability. Counterclockwise rotation and degree/vector of advancement can alter airway gain and facial profile. The inferior alveolar nerve is a key mandibular risk; tooth roots, descending palatine blood supply and nasal septum/alar base are important maxillary considerations.",
            "Review PSG severity/oxygen burden, PAP history, BMI and prior sleep surgery plus cephalometric/dental occlusion, TMJ status and facial proportions. Orthodontic evaluation is important when dental decompensation or postoperative occlusal goals require it. CT/virtual surgical planning can define osteotomy movement and fixation. Discuss permanent lower-lip/chin numbness risk, malocclusion, relapse, TMJ symptoms, nasal/facial change and the possibility of residual OSA despite major improvement.",
            "MMA is appropriate when expected efficacy justifies invasiveness and anatomy/goals are compatible; it can be primary in selected craniofacial patients or salvage after failed soft-tissue surgery. It is not simply 'last resort' and should be compared with PAP, HNS and other options according to phenotype and patient preference. Weight management and long-term sleep follow-up remain necessary. Objective postoperative sleep testing is required because symptomatic improvement does not prove cure.",
            "Plan the advancement vector/rotation to achieve airway and facial/occlusal goals simultaneously. Maintain condylar seating during mandibular fixation, protect inferior alveolar nerves where possible and verify final occlusion before completing fixation. Maxillary advancement may widen the alar base and affect velopharyngeal/nasal relationships; use appropriate soft-tissue control. Skeletal stability, fixation and postoperative orthodontic/occlusal management are integral to the sleep operation rather than separate cosmetic issues.",
            "Boards/chief framework: MMA is a multilevel skeletal airway operation with high OSA efficacy, not merely orthognathic surgery in a patient who snores. Selection is based on disease severity, phenotype and patient goals; technical success requires condylar seating and correct occlusion as well as airway advancement. Lower-lip/chin sensory change is one of the major counseling points.",
            ["MMA", "maxillomandibular advancement", "OSA", "Le Fort I", "BSSO", "inferior alveolar nerve", "occlusion"],
            ["Pasha 6e", "KJ Lee 12e"],
        ),
    ],
    "General ENT / Emergencies": [
        _entry(
            ["Carotid Blowout Syndrome", "Carotid Blowout"],
            "Carotid blowout syndrome is arterial wall failure in a hostile neck, classically after radiation, major neck surgery, recurrent tumor, infection, fistula or exposed vessel. Think in stages: threatened blowout means the artery is exposed/structurally at risk without active hemorrhage; impending blowout produces a sentinel bleed that stops spontaneously or with temporary pressure; acute blowout is uncontrolled major hemorrhage. A small self-limited bleed from an irradiated infected wound is therefore not reassuring—it may be the warning before exsanguination.",
            "The common carotid, internal carotid and major branches can be involved; prior surgery/radiation strips protective soft tissue and infection/fistula further weakens adventitia/wall. A pharyngocutaneous fistula bathing the carotid is a particularly dangerous setting. Hemorrhage can simultaneously cause exsanguination and airway flooding, so airway and vascular priorities compete in real time.",
            "In a stable threatened/impending patient, obtain urgent CTA/vascular imaging to define pseudoaneurysm, vessel exposure, stenosis and collateral circulation while mobilizing endovascular and surgical teams. Do not delay resuscitation for imaging in active exsanguination. Type/cross blood, correct major coagulopathy, secure large-bore access and anticipate massive transfusion. Flexible endoscopy can define mucosal source in stable cases but should not destabilize a tenuous clot without a control plan.",
            "Sentinel bleeding requires admission and definitive vascular evaluation/intervention, not clinic follow-up. Endovascular covered stent reconstruction can preserve carotid flow when sacrifice is unsafe but requires antiplatelet considerations and carries infection/rebleeding/stent-complication risk in contaminated fields. Embolization/arterial sacrifice can provide durable control when collateral cerebral circulation is adequate but carries stroke risk. Open ligation/reconstruction is sometimes necessary when endovascular therapy is unavailable/failed or the wound requires surgical source control and coverage.",
            "During active hemorrhage, compress/pack only as a temporizing maneuver while protecting the airway and mobilizing definitive vascular control; avoid blind clamps deep in an irradiated wound. If the vessel is exposed in an infected/fistulized neck, definitive management includes coverage with well-vascularized tissue and treatment of the contamination/source when survivable. Balloon-occlusion testing or collateral assessment may inform elective sacrifice in stable patients, but no test should delay control of life-threatening bleeding.",
            "Boards/chief framework: threatened → sentinel/impending → acute is a continuum. Sentinel bleeding is an emergency even after it stops. Endovascular stenting preserves flow but puts prosthetic material into a potentially contaminated field; embolization/sacrifice avoids that issue but risks cerebral ischemia. In a crash, airway protection and hemorrhage control happen simultaneously, and blind wound exploration is dangerous.",
            ["carotid blowout", "sentinel bleed", "irradiated neck", "covered stent", "embolization", "arterial sacrifice", "massive hemorrhage"],
            ["NCCN Head & Neck v2.2026", "Pasha 6e"],
        ),
    ],
}


def apply_cross_domain_depth_v162(deep_modules):
    applied, missing = [], []
    for domain, patches in PATCHES_V162.items():
        modules = deep_modules.get(domain, [])
        for patch in patches:
            found = next((m for m in modules if m.get("topic") in patch["candidates"]), None)
            if found is None:
                missing.append((domain, patch["candidates"]))
                continue
            found.update(patch["fields"])
            applied.append((domain, found.get("topic")))
    return {"applied": applied, "missing": missing}
