"""ENT Mastery v45.9 -- Learning-ladder gapfill: Rhinology / Allergy / Skull Base.

Adds foundation/application/senior_decision Clinical Challenge vignettes for
the 6 Rhinology / Allergy / Skull Base topics flagged by
audit_domain_ladder_inventory_v217.py as having no deliberately-reviewed ladder
row (recently-added topics that never got this pass). Grounded in each topic's
existing Deep Curriculum content -- no new clinical facts, numbers, or grading
systems introduced beyond what that content already states.
"""
from copy import deepcopy

DOMAIN = "Rhinology / Allergy / Skull Base"

NEW_QUESTIONS = [
    # ---------------- Empty Nose Syndrome ----------------
    {
        "id": "v459_rhino_ens_fnd",
        "domain": DOMAIN,
        "topic": "Empty Nose Syndrome",
        "stem": "A 45-year-old woman returns 2 years after bilateral inferior turbinate reduction for nasal obstruction. She now describes a persistent sensation of suffocation and inability to feel airflow, along with nasal dryness and crusting, despite anterior rhinoscopy showing a wide, patent nasal cavity bilaterally. Which diagnosis best explains this presentation?",
        "choices": [
            "Empty nose syndrome",
            "Allergic rhinitis",
            "Chronic rhinosinusitis with nasal polyps",
            "Septal perforation with crusting",
        ],
        "answer": 0,
        "explanation": "Paradoxical obstruction, a suffocation sensation, dryness, and crusting after turbinate surgery despite a visibly open airway is the classic presentation of empty nose syndrome, a multifactorial neurosensory and airflow disorder rather than fixed stenosis.",
        "why_wrong": [
            "Correct.",
            "Allergic rhinitis does not classically follow turbinate resection nor typically present as a paradoxical suffocation sensation from an already wide-open cavity.",
            "Chronic rhinosinusitis with nasal polyps would show polypoid mucosa on exam, not a widely patent, mucosa-depleted cavity.",
            "Septal perforation causes localized whistling and crusting at the perforation edge but does not explain the paradoxical suffocation sensation from turbinate tissue loss.",
        ],
        "board_pearl": "A wide-open nasal cavity on exam does not equal a functional airway -- paradoxical obstruction after turbinate surgery is empty nose syndrome until proven otherwise.",
        "curveball": "What bedside test, despite its limitations, might support the diagnosis and help anticipate response to augmentation?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-empty-nose-syndrome",
        "learning_stage": "foundation",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "The cotton test (placing a small cotton wisp along the lateral nasal wall to functionally simulate augmented tissue) can be tried; symptomatic improvement may support consideration of turbinate/lateral-wall augmentation, though it is not definitive and must be interpreted alongside ENS6Q, endoscopy, and exclusion of inflammatory, structural, neurologic, sleep, and psychiatric contributors.",
    },
    {
        "id": "v459_rhino_ens_app",
        "domain": DOMAIN,
        "topic": "Empty Nose Syndrome",
        "stem": "A 52-year-old man presents 18 months after turbinate reduction surgery with new-onset nasal dryness, crusting, and a sensation of suffocation despite a widely patent nasal airway on endoscopy. He also reports poor sleep, snoring, and a low mood since his surgery. Which next step best reflects appropriate evaluation of possible empty nose syndrome in this patient?",
        "choices": [
            "Diagnose ENS immediately and proceed directly to turbinate augmentation surgery",
            "Dismiss the nasal complaints as purely psychiatric because of his mood symptoms and refer only to psychiatry",
            "Pursue endoscopy, ENS6Q, mucosal assessment, and a carefully interpreted cotton test, while also screening for sleep and mental-health contributors, since no single test is definitive",
            "Reassure the patient that a wide airway on exam excludes any organic problem and discharge him from clinic",
        ],
        "answer": 2,
        "explanation": "ENS workup requires operative history, endoscopy, ENS6Q, mucosal assessment, and a carefully interpreted cotton test, with exclusion of inflammatory, structural, neurologic, sleep, and psychiatric contributors -- no single test is definitive.",
        "why_wrong": [
            "No single test is definitive; proceeding straight to surgery without a structured workup and exclusion of alternative contributors is inappropriate, and evidence for augmentation is variable.",
            "Dismissing nasal symptoms because of coexisting mood symptoms fails to validate the patient and ignores the multifactorial nature of ENS; comorbid psychiatric disease should be treated without dismissing the nasal complaint.",
            "Correct.",
            "A wide cavity on exam does not prove adequate nasal function.",
        ],
        "board_pearl": "ENS is multifactorial -- treat comorbid sleep and mental-health issues in parallel with the nasal complaint, and use a structured, multi-test workup rather than any single definitive test.",
        "curveball": "If cotton testing produces clear symptomatic relief, what caveat should be discussed with the patient before recommending augmentation surgery?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-empty-nose-syndrome",
        "learning_stage": "application",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Even with temporary cotton-test improvement, evidence for turbinate/lateral-wall augmentation is variable and durability is inconsistent, so careful informed consent about uncertain, potentially incomplete or non-durable benefit -- and the possibility of needing revision surgery -- is required before proceeding.",
    },
    {
        "id": "v459_rhino_ens_snr",
        "domain": DOMAIN,
        "topic": "Empty Nose Syndrome",
        "stem": "A 48-year-old woman with a 3-year history of classic empty nose syndrome symptoms after aggressive turbinate resection has completed conservative therapy (humidification, saline, emollients) and management of coexisting sleep and mood disturbance, with only partial relief. Endoscopy confirms absent turbinate tissue, and cotton testing produces reproducible, though temporary, symptomatic improvement. As the surgeon counseling her about turbinate/lateral-wall augmentation, which statement best reflects appropriate senior-level decision-making?",
        "choices": [
            "Proceed to augmentation surgery immediately since cotton-test positivity guarantees a durable cure",
            "Offer augmentation surgery as a reasonable option in this well-selected patient, but counsel that evidence and durability are variable and that revision may be needed, with realistic expectations set in advance",
            "Refuse any surgical option and manage her indefinitely with saline and emollients alone",
            "Proceed directly to revision turbinate resection to remove any remaining tissue",
        ],
        "answer": 1,
        "explanation": "Selected patients with consistent symptoms and temporary cotton-test improvement may consider turbinate or lateral-wall augmentation, but evidence and durability are variable and revision requires careful, realistic consent.",
        "why_wrong": [
            "A positive cotton test does not guarantee a durable cure; overstating certainty is inappropriate.",
            "Correct.",
            "She has already failed conservative therapy and is a selected patient with a consistent history and a supportive test; withholding a reasonable surgical option entirely is not appropriate.",
            "Further resection would worsen the underlying mucosal/tissue loss driving her ENS, which is the opposite of the correct approach.",
        ],
        "board_pearl": "ENS surgery is for selected patients with a consistent story and a supportive (if imperfect) cotton test -- never for patients seeking further tissue removal, and always with realistic, informed expectations.",
        "curveball": "What is the single most important preventive principle to teach a junior resident performing turbinate surgery, to avoid causing ENS in the first place?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-empty-nose-syndrome",
        "learning_stage": "senior_decision",
        "ladder_reviewed": True,
        "focus": "OR_prep",
        "curveball_answer": "Favor mucosa-preserving turbinate surgery techniques rather than aggressive or complete turbinate resection, since prevention is the most reliable strategy given that established ENS treatment options have variable and often non-durable benefit.",
    },
    # ---------------- Silent Sinus Syndrome ----------------
    {
        "id": "v459_rhino_sss_fnd",
        "domain": DOMAIN,
        "topic": "Silent Sinus Syndrome",
        "stem": "A 39-year-old man presents with several months of painless, gradually progressive enophthalmos and hypoglobus on the right side. He denies trauma, sinus pain, or significant nasal symptoms. Which diagnosis should be suspected first?",
        "choices": [
            "Silent sinus syndrome",
            "Orbital cellulitis",
            "Thyroid eye disease",
            "Orbital floor blowout fracture",
        ],
        "answer": 0,
        "explanation": "Painless progressive unilateral enophthalmos or hypoglobus without trauma or prominent sinus symptoms should raise concern for silent sinus syndrome, caused by chronic maxillary outflow obstruction with negative pressure and maxillary atelectasis.",
        "why_wrong": [
            "Correct.",
            "Orbital cellulitis presents acutely with pain, erythema, and signs of infection, not painless progressive enophthalmos.",
            "Thyroid eye disease classically causes proptosis (not enophthalmos) and is usually bilateral with lid retraction.",
            "He denies trauma, which a blowout fracture requires.",
        ],
        "board_pearl": "Painless, progressive, unilateral enophthalmos or hypoglobus without trauma is silent sinus syndrome until imaging proves otherwise.",
        "curveball": "What is the underlying sinus pathophysiology producing the orbital findings?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-silent-sinus-syndrome",
        "learning_stage": "foundation",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Chronic maxillary sinus outflow obstruction leads to progressive negative pressure within the sinus, causing maxillary sinus atelectasis (volume loss) with inferior bowing of the orbital floor, which increases orbital volume and produces enophthalmos/hypoglobus.",
    },
    {
        "id": "v459_rhino_sss_app",
        "domain": DOMAIN,
        "topic": "Silent Sinus Syndrome",
        "stem": "CT of the sinus/orbit in a patient with painless progressive enophthalmos shows an opacified, contracted maxillary sinus, a retracted uncinate process, and an inferiorly bowed orbital floor. Which finding would instead suggest an expansile process such as a mucocele rather than silent sinus syndrome?",
        "choices": [
            "Sinus expansion with outward bony wall remodeling rather than sinus volume loss",
            "Opacification of the maxillary sinus",
            "Depression of the orbital floor",
            "Retraction of the uncinate process",
        ],
        "answer": 0,
        "explanation": "Silent sinus syndrome is characterized by maxillary atelectasis (volume loss) rather than expansion. An expansile process such as a mucocele instead remodels the bony sinus walls outward, which is the key radiographic discriminator from a mucocele, neoplasm, or post-traumatic deformity.",
        "why_wrong": [
            "Correct.",
            "Opacification alone is seen in both processes and does not discriminate between them.",
            "Orbital floor depression is the expected finding in silent sinus syndrome due to volume loss, not a discriminator for a mucocele.",
            "Uncinate retraction is a classic silent sinus syndrome finding, not a mucocele feature.",
        ],
        "board_pearl": "Silent sinus syndrome is a sinus that has shrunk (atelectasis); a mucocele is a sinus that has expanded outward. That direction of bony change is the key radiographic discriminator.",
        "curveball": "If diplopia and orbital deformity are significant, when should orbital floor reconstruction be performed relative to sinus surgery?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-silent-sinus-syndrome",
        "learning_stage": "application",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Orbital floor reconstruction may be performed simultaneously with endoscopic uncinectomy and maxillary antrostomy, or staged afterward; the choice is individualized based on deformity severity, presence of diplopia, and expected orbital remodeling after the sinus is re-aerated -- reconstruction is not automatically mandated in every case.",
    },
    {
        "id": "v459_rhino_sss_snr",
        "domain": DOMAIN,
        "topic": "Silent Sinus Syndrome",
        "stem": "A patient with confirmed silent sinus syndrome undergoes endoscopic uncinectomy and maxillary antrostomy to re-aerate the affected sinus. She has mild hypoglobus and no diplopia. Which statement best reflects the appropriate senior-level approach to orbital floor management in this case?",
        "choices": [
            "Orbital floor reconstruction is mandatory in every case of silent sinus syndrome regardless of severity",
            "Medical therapy alone should have been tried first to reverse the enophthalmos before any surgery",
            "Because her deformity is mild and she lacks diplopia, observation after sinus re-aeration with staged reconstruction only if needed is a reasonable individualized approach",
            "No orbital evaluation is needed since silent sinus syndrome is purely a sinus disease",
        ],
        "answer": 2,
        "explanation": "Orbital-floor reconstruction may be simultaneous or staged depending on deformity, diplopia, and severity, and should not be automatically mandated in every case; individualization is appropriate, especially with mild deformity and no diplopia.",
        "why_wrong": [
            "Reconstruction should be individualized, not automatically mandated in every case.",
            "Medical therapy does not reverse established atelectasis or orbital-volume change, so it would not have addressed her enophthalmos.",
            "Correct.",
            "Coordinated rhinology and ophthalmic evaluation is part of appropriate management, since the orbital consequences (enophthalmos, hypoglobus, diplopia) are central to the disease.",
        ],
        "board_pearl": "Re-aerating the sinus is necessary, but the decision to reconstruct the orbital floor -- simultaneously, staged, or not at all -- must be individualized to deformity severity, diplopia, and expected remodeling.",
        "curveball": "Why might some patients show orbital improvement after sinus surgery alone, without any orbital floor reconstruction?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-silent-sinus-syndrome",
        "learning_stage": "senior_decision",
        "ladder_reviewed": True,
        "focus": "OR_prep",
        "curveball_answer": "Re-aerating and re-pressurizing the previously atelectatic maxillary sinus can allow some remodeling of the orbital floor and soft tissues over time, which is why reconstruction is not automatically performed in every case and may be reserved as a staged procedure only if deformity or diplopia persists.",
    },
    # ---------------- Endoscopic Pituitary / Anterior Skull Base Approach ----------------
    {
        "id": "v459_rhino_pit_fnd",
        "domain": DOMAIN,
        "topic": "Endoscopic Pituitary / Anterior Skull Base Approach",
        "stem": "A patient is found to have a pituitary macroadenoma on MRI obtained for headache workup, with bitemporal visual field loss on formal testing and no endocrine excess. She is being considered for an endoscopic endonasal approach. Which statement correctly describes the roles of the surgical team members in this approach?",
        "choices": [
            "The neurosurgeon alone performs the entire procedure without rhinology involvement",
            "The rhinologist creates and later reconstructs the endonasal surgical corridor while neurosurgery addresses the lesion itself",
            "The rhinologist treats the tumor while neurosurgery manages only the nasal packing postoperatively",
            "Endocrinology performs the surgical resection under microscope guidance",
        ],
        "answer": 1,
        "explanation": "This is a team operation: the rhinologist creates the corridor and performs reconstruction while neurosurgery treats the lesion, and success includes endocrine and visual outcomes, carotid safety, and durable CSF-leak prevention, not merely tumor removal.",
        "why_wrong": [
            "This is explicitly a team operation; excluding rhinology omits the corridor-creation and reconstruction role.",
            "Correct.",
            "This reverses the actual division of labor.",
            "Endocrinology's role is medical and perioperative management, not surgical resection.",
        ],
        "board_pearl": "Endoscopic pituitary/skull-base surgery is a team operation: rhinology builds and closes the corridor, neurosurgery treats the lesion, and success is judged by endocrine, visual, carotid-safety, and CSF-leak outcomes together -- not tumor removal alone.",
        "curveball": "Which anatomic structures bound the endonasal corridor to the sella and must be localized before dural entry?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-endoscopic-pituitary-anterior-skull-base-approach",
        "learning_stage": "foundation",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "The corridor is bounded by the carotid arteries and cavernous sinuses laterally, the optic apparatus superiorly, and the clivus posteriorly; carotid localization is planned before dural entry, and extended approaches can reach the planum, cribriform plate, and clivus for appropriate midline skull-base targets.",
    },
    {
        "id": "v459_rhino_pit_app",
        "domain": DOMAIN,
        "topic": "Endoscopic Pituitary / Anterior Skull Base Approach",
        "stem": "A 30-year-old woman is found to have a small pituitary lesion with markedly elevated prolactin and no visual field deficit or other compressive symptoms. Which management approach is most appropriate before considering the endoscopic endonasal approach?",
        "choices": [
            "Immediate endoscopic endonasal resection regardless of hormone status",
            "A trial of a dopamine agonist, reserving surgery for medical failure or compressive/visual symptoms",
            "Observation alone with no endocrine or visual evaluation",
            "Extended approach with nasoseptal flap harvest as first-line therapy",
        ],
        "answer": 1,
        "explanation": "Disease-specific medical therapy such as dopamine agonists is used for most prolactinomas, with observation reserved for appropriate incidental/noncompressive lesions, and surgery considered when medical therapy fails or compressive/visual findings develop.",
        "why_wrong": [
            "Most prolactinomas are managed medically first; immediate surgery is not the appropriate first step.",
            "Correct.",
            "Appropriate management still requires complete pituitary testing and visual assessment as indicated, not simply observation with no evaluation.",
            "An extended approach with flap harvest is a surgical step reserved for cases requiring surgery, not first-line therapy for a prolactinoma.",
        ],
        "board_pearl": "Not every sellar lesion requires surgery -- most prolactinomas respond to dopamine agonist therapy, and endocrine deficits should be optimized before any operation that ultimately proves necessary.",
        "curveball": "If this patient later develops progressive visual field loss despite dopamine agonist therapy, how does that change the plan?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-endoscopic-pituitary-anterior-skull-base-approach",
        "learning_stage": "application",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Progressive visual field loss despite appropriate medical therapy is a compressive finding that shifts management toward the endoscopic endonasal approach for surgical decompression, with multidisciplinary endocrinology-neurosurgery-rhinology planning, formal visual assessment, and dedicated imaging beforehand.",
    },
    {
        "id": "v459_rhino_pit_snr",
        "domain": DOMAIN,
        "topic": "Endoscopic Pituitary / Anterior Skull Base Approach",
        "stem": "During an extended endoscopic approach for a large skull-base lesion, a high-flow intraoperative CSF leak is encountered after tumor resection. Which reconstructive decision reflects appropriate senior-level planning for this scenario?",
        "choices": [
            "Close with only a thin layer of absorbable packing since the leak will seal on its own",
            "Use a vascularized nasoseptal flap, prepared for or already harvested in anticipation of a high-flow leak, as part of a multilayer closure",
            "Avoid any flap harvest to preserve septal tissue regardless of leak flow",
            "Delay reconstruction to a second-stage operation after the patient recovers",
        ],
        "answer": 1,
        "explanation": "A vascularized nasoseptal flap should be preserved or harvested when a high-flow leak is plausible, and multilayer closure should be planned before dural entry as part of durable CSF-leak prevention.",
        "why_wrong": [
            "A high-flow leak requires a robust, planned closure, not minimal packing alone.",
            "Correct.",
            "Preserving septal tissue at the expense of a durable closure is inappropriate when a high-flow leak is plausible or present.",
            "Leaving a high-flow intraoperative CSF leak unreconstructed and delaying closure to a second operation is not appropriate; closure should occur at the time of the index surgery.",
        ],
        "board_pearl": "When a high-flow CSF leak is plausible, plan for (or already have harvested) a vascularized nasoseptal flap and build a true multilayer closure -- durable leak prevention is a primary operative outcome, not an afterthought.",
        "curveball": "What multidisciplinary and perioperative factors should be optimized before this patient ever reaches the operating room in the first place?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-endoscopic-pituitary-anterior-skull-base-approach",
        "learning_stage": "senior_decision",
        "ladder_reviewed": True,
        "focus": "OR_prep",
        "curveball_answer": "Multidisciplinary endocrinology-neurosurgery-rhinology review, complete pituitary function testing, formal visual assessment when indicated, and optimization of any endocrine deficits should all occur preoperatively, in addition to dedicated MRI and CT for anatomic and operative planning.",
    },
    # ---------------- Orbital Apex Syndrome ----------------
    {
        "id": "v459_rhino_apex_fnd",
        "domain": DOMAIN,
        "topic": "Orbital Apex Syndrome",
        "stem": "A 62-year-old man with poorly controlled diabetes presents with facial pain, ophthalmoplegia involving cranial nerves III, IV, and VI, visual acuity loss, and hypesthesia in the V1 distribution. Which diagnosis best fits this combination of findings?",
        "choices": [
            "Superior orbital fissure syndrome",
            "Cavernous sinus syndrome",
            "Orbital apex syndrome",
            "Isolated CN VI palsy",
        ],
        "answer": 2,
        "explanation": "Ophthalmoplegia (CN III, IV, VI), visual acuity loss or a relative afferent pupillary defect (CN II), and V1 (+/- V2) hypesthesia together define orbital apex syndrome, since the optic canal and superior orbital fissure converge only at that exact anatomic bottleneck.",
        "why_wrong": [
            "Superior orbital fissure syndrome causes motility and sensory deficits but spares vision, since the optic nerve travels through the separate optic canal.",
            "Cavernous sinus syndrome is typically vision-sparing unless disease extends posteriorly, and classically also involves V2.",
            "Correct.",
            "An isolated CN VI palsy would not explain the combined ophthalmoplegia, vision loss, and V1 hypesthesia.",
        ],
        "board_pearl": "Vision loss plus ophthalmoplegia plus V1 numbness localizes to the orbital apex, because the optic canal and superior orbital fissure only converge at that exact anatomic bottleneck.",
        "curveball": "In this diabetic patient, what diagnosis must be assumed and emergently evaluated for until proven otherwise?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-orbital-apex-syndrome",
        "learning_stage": "foundation",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Invasive fungal sinusitis (mucormycosis or aspergillosis) must be assumed in an immunocompromised or diabetic-ketoacidosis patient with facial pain and eye findings until proven otherwise, requiring urgent bedside nasal endoscopy with biopsy of any nonviable, dusky, or black-appearing mucosa for frozen section and fungal stain.",
    },
    {
        "id": "v459_rhino_apex_app",
        "domain": DOMAIN,
        "topic": "Orbital Apex Syndrome",
        "stem": "Three patients present with periorbital findings. Patient 1 has ophthalmoplegia and V1/V2 hypesthesia with normal vision. Patient 2 has ophthalmoplegia and V1 hypesthesia with new vision loss and a relative afferent pupillary defect. Patient 3 has isolated ophthalmoplegia and V1 hypesthesia with normal vision and no V2 involvement. Which patient's presentation most specifically localizes to the orbital apex rather than the cavernous sinus or superior orbital fissure alone?",
        "choices": [
            "Patient 1, because V2 involvement is required for orbital apex syndrome",
            "Patient 2, because the addition of vision loss and a relative afferent pupillary defect indicates optic nerve involvement at the shared apex bottleneck",
            "Patient 3, because isolated motor and sensory findings without V2 always indicate orbital apex syndrome",
            "All three patients are equally consistent with orbital apex syndrome",
        ],
        "answer": 1,
        "explanation": "Vision loss (via the optic canal) is the discriminator that separates orbital apex syndrome from cavernous sinus syndrome (vision-sparing, often with V2 involvement) and superior orbital fissure syndrome (vision-sparing, no optic canal involvement).",
        "why_wrong": [
            "V2 involvement with preserved vision is more typical of cavernous sinus syndrome, not a requirement for orbital apex syndrome.",
            "Correct.",
            "Superior orbital fissure syndrome, not orbital apex syndrome, is the diagnosis when motility and sensory deficits occur with preserved vision.",
            "Vision involvement is the specific discriminator, so the three presentations are not equivalent.",
        ],
        "board_pearl": "Vision loss is the discriminator: preserved vision with V1/V2 findings points to the cavernous sinus, preserved vision with only V1 and motility findings points to the superior orbital fissure, and any added vision loss points to the orbital apex.",
        "curveball": "If disease progresses posteriorly from the cavernous sinus, why can the clinical exam eventually mimic true orbital apex syndrome?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-orbital-apex-syndrome",
        "learning_stage": "application",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Cavernous sinus syndrome is typically vision-sparing, but if disease extends posteriorly it can begin to involve the optic apparatus, converting the exam findings toward those seen in true orbital apex syndrome -- which is why posterior extension, not just initial presentation, must be considered.",
    },
    {
        "id": "v459_rhino_apex_snr",
        "domain": DOMAIN,
        "topic": "Orbital Apex Syndrome",
        "stem": "A senior resident evaluates a patient with new orbital apex syndrome and diabetic ketoacidosis. Imaging is pending and biopsy has not yet been obtained. The consulting team wants to wait for MRI results before proceeding with endoscopy. What is the most appropriate senior-level decision?",
        "choices": [
            "Wait for MRI results before any bedside intervention, since biopsy without confirmatory imaging is premature",
            "Proceed immediately with bedside nasal endoscopy and biopsy of any nonviable-appearing mucosa while correcting the underlying ketoacidosis, without waiting for imaging to dictate the timing of biopsy",
            "Treat with broad-spectrum antibiotics alone and reassess in 24-48 hours",
            "Defer any intervention until ophthalmology completes formal visual field testing",
        ],
        "answer": 1,
        "explanation": "New vision loss with orbital apex syndrome is a surgical emergency; the key trap is treating it as an indication to wait for further imaging rather than obtaining immediate bedside biopsy of nonviable mucosa and correcting the underlying immunocompromised state.",
        "why_wrong": [
            "New vision loss and this clinical picture represent a surgical emergency; waiting for imaging to complete before biopsy risks a delay that can be catastrophic in invasive fungal disease.",
            "Correct.",
            "Antibiotics alone do not address possible invasive fungal disease, and a 24-48 hour reassessment delay is inappropriate for a suspected surgical emergency.",
            "Formal visual assessment is important but should not delay emergent biopsy and correction of the underlying immunocompromised state.",
        ],
        "board_pearl": "New vision loss in orbital apex syndrome is a surgical emergency -- biopsy nonviable mucosa and correct the underlying immunocompromised state emergently rather than waiting on imaging alone.",
        "curveball": "Beyond antifungal therapy and correcting DKA, what surgical principle applies to debridement in fulminant invasive fungal sinusitis?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-orbital-apex-syndrome",
        "learning_stage": "senior_decision",
        "ladder_reviewed": True,
        "focus": "overnight_call",
        "curveball_answer": "Expect that fulminant invasive fungal disease often requires serial surgical debridement of necrotic tissue rather than a single operative intervention, managed jointly with ophthalmology, neurosurgery, and infectious disease, with orbital decompression considered when indicated.",
    },
    # ---------------- Anaphylaxis ----------------
    {
        "id": "v459_rhino_anaph_fnd",
        "domain": DOMAIN,
        "topic": "Anaphylaxis",
        "stem": "Ten minutes after starting the build-up phase of subcutaneous immunotherapy in the office, a patient develops diffuse urticaria, wheeze, and a blood pressure of 78/40 mmHg. What is the immediate first-line treatment?",
        "choices": [
            "Intramuscular epinephrine, 0.01 mg/kg of 1:1000, in the anterolateral thigh",
            "Oral diphenhydramine followed by observation",
            "Intravenous corticosteroids as the initial agent",
            "Positioning the patient upright and administering supplemental oxygen alone",
        ],
        "answer": 0,
        "explanation": "First-line treatment for anaphylaxis is immediate intramuscular epinephrine in the anterolateral thigh at a standard weight-based dose of 0.01 mg/kg of 1:1000 concentration, given without delay.",
        "why_wrong": [
            "Correct.",
            "Antihistamines are adjuncts for cutaneous/itch symptoms and do not treat the airway/hemodynamic emergency; they must never be substituted for or given before epinephrine.",
            "Corticosteroids are an adjunct for theoretical biphasic-reaction prevention, not the first-line treatment for the acute emergency.",
            "Positioning and oxygen are supportive adjuncts, not a substitute for immediate epinephrine, and a hypotensive patient should be positioned supine with legs elevated if tolerated, not upright.",
        ],
        "board_pearl": "Epinephrine is never contraindicated in true anaphylaxis -- the most common preventable error is delaying it while reaching for diphenhydramine or waiting to 'see if it gets worse.'",
        "curveball": "What is the standard weight-based dose and the maximum single doses in children versus adults?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-anaphylaxis",
        "learning_stage": "foundation",
        "ladder_reviewed": True,
        "focus": "overnight_call",
        "curveball_answer": "0.01 mg/kg of 1:1000 (1 mg/mL) epinephrine IM in the anterolateral thigh, to a maximum single dose of 0.3 mg in children and 0.5 mg in adults, repeated roughly every 5-15 minutes as needed if symptoms do not improve.",
    },
    {
        "id": "v459_rhino_anaph_app",
        "domain": DOMAIN,
        "topic": "Anaphylaxis",
        "stem": "A patient becomes pale, diaphoretic, and bradycardic with transient hypotension immediately after a skin-prick allergy test, then improves promptly once positioned supine with legs elevated. There is no urticaria, angioedema, or wheeze. Which diagnosis best fits, and what is the appropriate next step?",
        "choices": [
            "Anaphylaxis; give intramuscular epinephrine immediately",
            "Vasovagal (neurocardiogenic) reaction; continue supportive positioning and monitoring rather than epinephrine",
            "Biphasic anaphylactic reaction; extend observation for 72 hours regardless of exam findings",
            "Anaphylaxis; draw a serum tryptase level before treating",
        ],
        "answer": 1,
        "explanation": "Bradycardia, pallor, diaphoresis, and prompt resolution with recumbency, without urticaria/angioedema/wheeze or persistent hypotension, is the classic vasovagal pattern, distinct from anaphylaxis.",
        "why_wrong": [
            "This presentation is bradycardic with transient, positionally-responsive hypotension and no skin/mucosal or respiratory findings -- the pattern of anaphylaxis is tachycardia with urticaria/angioedema/wheeze and hypotension that does not resolve with recumbency alone.",
            "Correct.",
            "A biphasic reaction refers to recurrence of anaphylaxis symptoms after initial resolution, not this vasovagal presentation, and the diagnosis should not be recharacterized incorrectly.",
            "This is not the anaphylaxis presentation, and even in true anaphylaxis, epinephrine should never be delayed to obtain a tryptase level.",
        ],
        "board_pearl": "Bradycardia + pallor + diaphoresis + rapid resolution with recumbency = vasovagal. Tachycardia + urticaria/angioedema/wheeze + persistent hypotension despite positioning = anaphylaxis, treat with epinephrine.",
        "curveball": "Why is this discrimination especially important in an office that performs skin testing or administers SCIT?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-anaphylaxis",
        "learning_stage": "application",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Because office-based immunotherapy and skin testing are recognized causes of anaphylaxis, any office performing them must have epinephrine, resuscitation equipment, and a rehearsed anaphylaxis protocol immediately available, and must observe patients through the standard post-injection window -- correctly distinguishing a vasovagal reaction from true anaphylaxis prevents both undertreatment of true anaphylaxis and unnecessary epinephrine use for a self-limited vasovagal event.",
    },
    {
        "id": "v459_rhino_anaph_snr",
        "domain": DOMAIN,
        "topic": "Anaphylaxis",
        "stem": "A patient treated for anaphylaxis after a food exposure receives one dose of intramuscular epinephrine with only partial improvement in wheeze and blood pressure. Twelve minutes have passed since the first dose. What is the most appropriate next step, and what discharge plan should follow once she stabilizes?",
        "choices": [
            "Repeat intramuscular epinephrine now, and if she remains refractory after a second dose, pursue escalation of care (IV fluids, oxygen, positioning, consideration of an epinephrine infusion) rather than further empiric epinephrine doses alone; on discharge, prescribe an epinephrine auto-injector and refer for allergy evaluation",
            "Withhold further epinephrine since one dose was already given, and switch to escalating doses of antihistamines and corticosteroids",
            "Discharge her home as soon as her blood pressure normalizes, with no auto-injector prescription since the trigger is now known and avoidable",
            "Observe for only 30 minutes total regardless of severity, since anaphylaxis resolves quickly once treated",
        ],
        "answer": 0,
        "explanation": "Epinephrine is commonly repeated every 5-15 minutes as needed; a patient who does not respond after two doses, or who has refractory hypotension/bronchospasm, needs emergency-level care rather than escalating second-line agents. Every patient treated for anaphylaxis should be prescribed an auto-injector and referred for allergy evaluation before discharge.",
        "why_wrong": [
            "Correct.",
            "Antihistamines and corticosteroids do not treat the airway/hemodynamic emergency and should never be substituted for repeat epinephrine when indicated.",
            "Every patient treated for anaphylaxis should be prescribed and taught to use an epinephrine auto-injector and referred for allergy evaluation before discharge, regardless of whether the trigger is identified.",
            "Observation duration should be individualized and is commonly on the order of several hours, longer for severe reactions or reactions requiring more than one epinephrine dose, given the risk of a biphasic reaction typically within 8-10 hours but reported up to about 72 hours later.",
        ],
        "board_pearl": "A patient who does not respond after two epinephrine doses, or who has refractory hypotension/bronchospasm, needs escalation to emergency-level care rather than escalating doses of second-line agents -- and every treated patient leaves with an auto-injector prescription and an allergy referral.",
        "curveball": "Why might this patient warrant a longer observation period than a patient with a mild, single-organ reaction that resolved after one epinephrine dose?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-anaphylaxis",
        "learning_stage": "senior_decision",
        "ladder_reviewed": True,
        "focus": "overnight_call",
        "curveball_answer": "Reactions requiring more than one epinephrine dose, more severe reactions, and patients with asthma or poor access to care warrant longer observation because biphasic reactions -- recurrence of symptoms without re-exposure, typically within 8-10 hours but reported up to about 72 hours later -- occur in a meaningful minority of such cases.",
    },
    # ---------------- Oral Allergy Syndrome (Pollen-Food Syndrome) ----------------
    {
        "id": "v459_rhino_oas_fnd",
        "domain": DOMAIN,
        "topic": "Oral Allergy Syndrome (Pollen-Food Syndrome)",
        "stem": "A 24-year-old woman with seasonal allergic rhinitis that worsens each spring reports that eating a raw apple causes her lips and mouth to itch and mildly swell within minutes, resolving shortly after, and this has never progressed beyond her mouth. Which diagnosis best fits this history?",
        "choices": [
            "Oral allergy syndrome (pollen-food syndrome)",
            "True peanut-type food allergy",
            "Latex-fruit syndrome",
            "Hereditary angioedema",
        ],
        "answer": 0,
        "explanation": "A reproducible history of rapid-onset, localized lip/mouth/throat itching or mild swelling within minutes of eating a specific raw fruit, resolving within minutes and rarely progressing beyond the oropharynx, in a patient with seasonal allergic rhinitis, is oral allergy syndrome.",
        "why_wrong": [
            "Correct.",
            "A true food allergy (peanut, tree nut, shellfish, egg, or milk) involves heat-stable proteins, carries a higher likelihood of systemic reactions, and is not tied to a seasonal pollen pattern.",
            "Latex-fruit syndrome is a related but distinct cross-reactivity pattern (latex allergy with foods like banana, avocado, kiwi, chestnut) with a higher systemic-reaction rate, and there is no latex exposure history here.",
            "Hereditary angioedema does not follow this reproducible, raw-fruit-triggered, minutes-to-resolve oral pattern tied to seasonal pollen sensitization.",
        ],
        "board_pearl": "A seasonal pollen history plus a reproducible 'raw fruit makes my mouth itch' history is oral allergy syndrome, not a true food allergy.",
        "curveball": "Given her springtime symptom pattern and apple trigger, which pollen family is most likely responsible, and why does cooking the apple usually eliminate her symptoms?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-oral-allergy-syndrome-pollen-food-syndrome",
        "learning_stage": "foundation",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Birch pollen is the classic springtime pairing with apple (via Bet v1/PR-10 homology); the causative proteins are heat-labile, so cooking, processing, or digestion degrades them, which is why reactions are largely limited to raw forms of the fruit.",
    },
    {
        "id": "v459_rhino_oas_app",
        "domain": DOMAIN,
        "topic": "Oral Allergy Syndrome (Pollen-Food Syndrome)",
        "stem": "A patient reports oral itching after eating raw banana. She has a known latex glove allergy from her work as a nurse. On a separate occasion, she also develops throat tightness and hives beyond her mouth after eating avocado. Which statement best characterizes her risk compared to a typical patient with pollen-food (oral allergy) syndrome?",
        "choices": [
            "Her presentation is consistent with typical pollen-food syndrome and carries the same low systemic-reaction risk as birch-apple or ragweed-melon reactions",
            "Her presentation is more consistent with latex-fruit syndrome, which is mechanistically distinct from pollen-food OAS and carries a higher rate of systemic reactions",
            "Cooking her banana and avocado will have no effect on her symptoms since all cross-reactivity syndromes involve heat-stable proteins",
            "Her symptoms exclude oral allergy syndrome entirely because bananas are never implicated in pollen-food cross-reactivity",
        ],
        "answer": 1,
        "explanation": "Latex-fruit syndrome is a related but mechanistically and clinically distinct cross-reactivity pattern (latex allergy with banana, avocado, kiwi, chestnut) that carries a higher rate of systemic reactions than classic pollen-food OAS.",
        "why_wrong": [
            "Her latex allergy history plus systemic symptoms (throat tightness, hives beyond the mouth) with the latex-associated foods (banana, avocado) point away from typical low-risk pollen-food OAS.",
            "Correct.",
            "Pollen-food OAS proteins are heat-labile, and while latex-fruit syndrome proteins differ, the claim that cooking is irrelevant to all cross-reactivity syndromes is not accurate for classic OAS.",
            "Banana is a classic ragweed/profilin-associated OAS food, so it is not excluded from oral allergy syndrome in general -- the issue here is her distinct latex-associated pattern with systemic symptoms.",
        ],
        "board_pearl": "Keep latex-fruit syndrome mentally separate from pollen-food OAS -- different proteins, no pollen association, and a higher systemic-reaction rate; a first reaction to a new cross-reactive food or any systemic symptom is a red flag requiring allergy referral and consideration of an epinephrine auto-injector.",
        "curveball": "What testing modality is preferred over commercial extracts when evaluating suspected OAS, and why?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-oral-allergy-syndrome-pollen-food-syndrome",
        "learning_stage": "application",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "Skin prick testing with fresh fruit ('prick-to-prick' testing) is preferred over commercial extracts because the causative proteins are heat- and processing-labile, and commercial extracts often degrade the relevant epitopes during preparation, reducing test sensitivity.",
    },
    {
        "id": "v459_rhino_oas_snr",
        "domain": DOMAIN,
        "topic": "Oral Allergy Syndrome (Pollen-Food Syndrome)",
        "stem": "A patient with confirmed pollen-food (oral allergy) syndrome to birch-associated foods asks whether she needs to avoid all cooked and canned forms of apple, pear, and carrot, and whether she needs an epinephrine auto-injector. She has never had any symptom beyond mild oral itching and has no latex allergy. What is the most appropriate senior-level counseling?",
        "choices": [
            "She must strictly avoid all cooked, canned, and baked forms of these foods indefinitely, and should carry an epinephrine auto-injector at all times",
            "Cooking, peeling, canning, or baking usually denatures the causative protein and restores tolerance, so blanket restriction of cooked/processed forms is unnecessary; routine auto-injector prescription is not required given her isolated oral symptoms, though treating her underlying seasonal allergic rhinitis may reduce her threshold for oral symptoms in peak season",
            "She should be started on strict avoidance of all raw and cooked forms of any food ever reported in pollen-food cross-reactivity tables, regardless of whether she has ever reacted to them",
            "Because her reactions are due to true, heat-stable food allergens, she requires formal oral food challenge testing before any reassurance can be given",
        ],
        "answer": 1,
        "explanation": "Cooking, peeling, canning, or baking usually denatures the causative heat-labile protein and restores tolerance, so blanket food-allergy-style restriction of cooked/processed forms is unnecessary and overly restrictive; treating underlying seasonal allergic rhinitis can reduce the threshold for oral symptoms during peak pollen season.",
        "why_wrong": [
            "Cooking/processing typically denatures the heat-labile causative protein and restores tolerance, so blanket restriction of cooked forms and routine auto-injector prescription are not indicated for isolated oral symptoms.",
            "Correct.",
            "Management should be guided by her actual reaction history to specific raw trigger foods, not blanket avoidance of every food ever listed in a cross-reactivity table.",
            "The causative proteins in pollen-food OAS are heat-labile, not heat-stable -- that heat-lability is the key mechanistic reason systemic reactions are uncommon.",
        ],
        "board_pearl": "Match the fruit family to the pollen and reassure appropriately -- blanket avoidance of cooked/processed forms and reflexive auto-injector prescription are for red-flag presentations (systemic symptoms, a first reaction to a new cross-reactive food, or a pattern resembling latex-fruit syndrome), not routine isolated oral symptoms.",
        "curveball": "If this same patient later develops throat tightness and hives beyond her mouth after eating raw celery, how should management change?",
        "tier": "Curated learning ladder",
        "mode": "Vignette",
        "concept_id": "v6-rhinology-allergy-skull-base-oral-allergy-syndrome-pollen-food-syndrome",
        "learning_stage": "senior_decision",
        "ladder_reviewed": True,
        "focus": "boards",
        "curveball_answer": "New systemic symptoms (throat tightness, hives beyond the mouth) are a red flag requiring allergy/immunology referral, consideration of an epinephrine auto-injector prescription, and possibly formal testing -- since celery is also part of the mugwort-celery-spice cross-reactivity pattern, and a systemic reaction pattern changes the risk stratification beyond typical isolated OAS.",
    },
]


def apply_deep_curriculum_ladder_rhinology_v459(data_module, app_module=None):
    existing = getattr(data_module, "CLINICAL_CHALLENGES_V119", None)
    if not isinstance(existing, list):
        raise RuntimeError("v45.9: CLINICAL_CHALLENGES_V119 unavailable")
    existing_ids = {q.get("id") for q in existing}
    added = 0
    cases = list(existing)
    for q in NEW_QUESTIONS:
        if q["id"] in existing_ids:
            raise RuntimeError(f"v45.9: duplicate id {q['id']!r}")
        cases.append(q)
        added += 1
    data_module.CLINICAL_CHALLENGES_V119 = cases
    if app_module is not None:
        app_module.CLINICAL_CHALLENGES_V119 = data_module.CLINICAL_CHALLENGES_V119
    return {"questions_added": added}
