"""v20.1 exact operative sequences for the remaining OR Tomorrow registry cases.

Completes the 93-case procedure-level pass and corrects combined procedures that a
single-family matcher can underspecify. Original synthesis from standard operative
ENT references supplied for this curriculum.
"""

EXACT = {
    "arytenoid-adduction": [
        "Expose the ipsilateral thyroid ala through a horizontal neck incision and identify the posterior thyroid border while preserving superior laryngeal and strap-muscle anatomy.",
        "Open the posterior laryngeal framework corridor and identify the muscular process of the arytenoid without entering the pyriform mucosa.",
        "Place the adduction suture through the muscular process in a secure orientation that reproduces lateral cricoarytenoid/interarytenoid vector rather than simply pulling the cartilage anteriorly.",
        "Bring the suture anteriorly through the thyroid cartilage at the planned fixation point while keeping it free of soft-tissue entrapment.",
        "Tension the suture gradually while assessing vocal-fold position, posterior glottic closure, and voice with flexible laryngoscopy/phonation when an awake technique is used.",
        "Combine with medialization thyroplasty when planned, adjusting implant and adduction tension together so posterior closure improves without airway compromise.",
        "Secure the adduction suture only after the arytenoid position is stable and the voice/airway endpoint is acceptable.",
        "Inspect for mucosal violation and bleeding, then close the neck with postoperative airway, voice, and swallowing surveillance.",
    ],
    "conservation-laryngectomy": [
        "Expose the laryngeal framework and neck according to the planned vertical or supracricoid conservation resection, completing indicated neck dissection before opening the pharynx/larynx.",
        "Define tumor extent endoscopically and externally, identifying the anterior commissure, paraglottic/pre-epiglottic spaces, cricoarytenoid unit, thyroid cartilage, and oncologic margins that must be preserved.",
        "Perform framework cuts and enter the larynx through a tumor-safe site, keeping at least one functional cricoarytenoid unit when required by the chosen conservation operation.",
        "Complete mucosal and deep soft-tissue cuts around the tumor with orientation to the arytenoid, pyriform sinus, tongue base, and subglottis; remove the specimen en bloc.",
        "Orient the specimen and obtain/confirm margins from the patient bed as indicated before reconstructing the airway.",
        "Reconstruct the residual larynx according to the operation—reapproximate mucosa/framework or perform cricohyoido(epiglotto)pexy—without excessive tension or rotational distortion.",
        "Create/secure the temporary tracheostomy and feeding access when required, then test the reconstruction for patency, hemostasis, and pharyngeal integrity.",
        "Close drains/neck and establish explicit postoperative airway, aspiration, swallowing-rehabilitation, and decannulation milestones.",
    ],
    "facial-nerve-reanimation": [
        "Map the deficit, chronicity, available proximal facial nerve, distal branches, and donor nerves before incision; expose recipient facial-nerve branches in healthy tissue whenever possible.",
        "Identify the proximal facial stump if usable and freshen it to healthy fascicles; if unavailable, expose the selected donor such as masseteric or hypoglossal nerve with enough length for a tension-free coaptation.",
        "Harvest the interposition nerve graft when required and preserve orientation/length sufficient to bridge without stretch or redundant kinking.",
        "Prepare proximal/donor and distal recipient nerve ends under magnification, minimizing crush and stripping only enough epineurium for accurate alignment.",
        "Perform epineurial/perineurial microsuture coaptation with the fewest sutures needed for stable fascicular contact; use fibrin support selectively without interposing glue between nerve ends.",
        "For nerve transfer, choose distal facial branches that reproduce the intended smile/eye-closure vector and avoid unnecessary denervation of functioning territories.",
        "Lay grafts/coaptations in a vascularized, noncompressed bed and ensure neck/parotid position does not tension the repair.",
        "Obtain hemostasis and close while documenting the exact donor-recipient construct and the expected months-long timeline for reinnervation/therapy.",
    ],
    "free-flap-basics": [
        "Define the defect requirements—lining, cover, bone/support, dead space, and function—and select recipient vessels before harvesting the flap.",
        "Harvest the chosen flap in its anatomic plane while identifying the arterial/venous pedicle and protecting donor nerves, tendons, and critical structures.",
        "Trace the pedicle to obtain adequate caliber and length, then divide it only when the recipient bed and vessels are ready for transfer.",
        "Prepare recipient artery and vein to healthy ends with enough mobility for a tension-free course, removing obstructing adventitia without injuring the vessel wall.",
        "Position the flap and pedicle first, then perform venous and arterial microvascular anastomoses under magnification with no twist, tension, or size-mismatch problem left uncorrected.",
        "Release clamps and assess inflow/outflow by clinical appearance, bleeding, and Doppler; correct vasospasm, kink, compression, or anastomotic defect before final inset.",
        "Complete flap inset while protecting the pedicle from mandibular edge, drain, closure, or neck-position compression and close the donor site appropriately.",
        "Confirm perfusion and establish a documented flap-monitoring and immediate re-exploration pathway for any postoperative signal or clinical change.",
    ],
    "free-flap-takeback": [
        "Treat suspected vascular compromise as time-critical: reopen the recipient site promptly and expose the pedicle/anastomoses before prolonged diagnostic delay.",
        "Release every potential external cause of obstruction first—tight inset, hematoma, neck position, pedicle twist, kink, or drain compression—and reassess flow.",
        "Inspect arterial inflow and venous outflow separately using clinical bleeding/Doppler and direct vessel appearance to localize the failure.",
        "If thrombosis is present, take down the affected anastomosis, remove clot completely, irrigate the lumen, and trim back to healthy intima rather than sewing through damaged vessel.",
        "Perform thrombectomy and revise the arterial or venous anastomosis; select a new recipient vessel or vein graft when the original geometry or vessel quality remains unsafe.",
        "Use pharmacologic thrombolysis/vasodilator maneuvers only within the team's established salvage protocol and after correcting the mechanical/technical cause.",
        "Reperfuse and observe the flap long enough to confirm sustained inflow/outflow, then revise inset so the repaired pedicle lies in a protected, noncompressed course.",
        "Close loosely enough for monitoring and document the revised vessels, ischemia interval, anticoagulation plan, and a very low threshold for repeat exploration.",
    ],
    "frontal-sinus-trauma": [
        "Expose the frontal sinus through the planned coronal/existing-laceration approach and define anterior table, posterior table, supraorbital rims, and nasofrontal outflow anatomy.",
        "Remove and preserve usable anterior-table fragments in an oriented fashion, then inspect the sinus for mucosal injury, posterior-table comminution, CSF leak, and outflow-tract disruption.",
        "If sinus preservation is appropriate, restore a patent outflow pathway and repair/reduce the anterior table without trapping mucosa behind displaced fragments.",
        "For obliteration, remove sinus mucosa meticulously from all walls/recesses and permanently separate the sinus from the nasal outflow tract before filling/obliterating the cavity.",
        "For cranialization, remove the posterior table, strip all sinus mucosa, and allow the frontal lobes/dura to occupy the former sinus after secure dural repair.",
        "Repair CSF/dural defects with a watertight vascularized or grafted barrier and protect the frontal recess from intracranial communication.",
        "Reconstruct the anterior table/supraorbital contour with stable fixation when needed for protection and cosmesis.",
        "Confirm hemostasis and closure of dead space, then document long-term surveillance for mucocele, contour deformity, CSF leak, and intracranial infection.",
    ],
    "hyoid-genioglossus": [
        "Expose the anterior mandible intraorally and map dental roots, mental nerves, genial tubercle, and genioglossus attachment before osteotomy.",
        "Create the genial-tubercle osteotomy below tooth roots while preserving the genioglossus attachment to the mobilized segment and maintaining mandibular continuity.",
        "Advance and rotate the genial segment to tension the genioglossus anteriorly, then secure it rigidly so it cannot recoil posteriorly.",
        "Through the planned cervical incision, expose the hyoid body/greater cornua while protecting hypoglossal and superior-laryngeal neurovascular structures.",
        "Mobilize the hyoid only enough to permit the planned anterior/superior suspension without unnecessary disruption of swallowing musculature.",
        "Place symmetric suspension sutures or fixation from hyoid to thyroid cartilage/mandible according to technique and tension them to enlarge the hypopharyngeal airway.",
        "Reassess mandibular fixation, hyoid position, tongue mobility, hemostasis, and absence of excessive laryngeal displacement.",
        "Close oral and cervical sites and establish postoperative airway observation, oral care, diet, and OSA follow-up.",
    ],
    "jugular-foramen-tumor": [
        "Plan the skull-base corridor from imaging and preoperative lower-cranial-nerve/hearing function, then obtain cervical/mastoid exposure with control of the sigmoid-jugular and carotid compartments required by tumor extent.",
        "Identify the facial nerve, labyrinth, sigmoid sinus, jugular bulb, internal carotid artery, and lower cranial nerves before drilling into the jugular foramen.",
        "Skeletonize the sigmoid sinus/jugular bulb and infralabyrinthine or infratemporal corridor with diamond drilling, preserving hearing structures when the chosen approach is hearing-sparing.",
        "Obtain proximal/distal vascular control when a hypervascular paraganglioma or vessel-encasing tumor makes hemorrhage a major risk.",
        "Debulk the tumor internally and dissect its capsule from lower cranial nerves, carotid artery, brainstem/dura, and facial nerve in small controlled segments.",
        "Control tumor feeders and venous bleeding directly rather than avulsing the lesion from the jugular bulb or carotid adventitia.",
        "Decide deliberately whether adherent tumor should be left to preserve a critical nerve/vessel instead of pursuing unsafe gross-total removal.",
        "Obliterate opened air cells, obtain watertight skull-base closure, reconstruct the soft-tissue defect, and document postoperative CN IX-XII, facial, hearing, aspiration, and vascular surveillance.",
    ],
    "laryngotracheal-cleft-repair": [
        "Confirm cleft type/extent with suspension microlaryngoscopy and bronchoscopy, then obtain the endoscopic or open exposure needed to visualize the entire posterior defect.",
        "Separate esophageal and laryngotracheal mucosal edges carefully along the cleft while protecting arytenoid/cricoid framework and recurrent-laryngeal-nerve regions.",
        "Freshen epithelialized cleft margins only enough to create vascularized surfaces for closure.",
        "Close the esophageal layer independently with watertight mucosal approximation, avoiding narrowing of the esophageal lumen.",
        "Close the laryngotracheal mucosal layer separately so the airway surface is smooth and the posterior glottis/subglottis are not stenosed.",
        "Interpose vascularized tissue between suture lines for larger/open repairs when indicated to reduce recurrent fistula risk.",
        "Inspect the repaired airway endoscopically and confirm an appropriate lumen, hemostasis, and no exposed suture/tissue likely to obstruct.",
        "Secure the planned postoperative airway and feeding strategy, with later swallow/endoscopic assessment before full oral advancement.",
    ],
    "microtia-reconstruction": [
        "Template the normal contralateral ear and mark the planned auricular position/axis before harvesting cartilage or creating the recipient pocket.",
        "Harvest costal cartilage through a chest incision while preserving perichondrium/chest-wall integrity and checking for pleural injury before closure.",
        "Sculpt the framework components to reproduce helix, antihelix, conchal bowl, and base projection, securing pieces without sharp exposed wire/suture points.",
        "Create a thin, well-vascularized postauricular skin pocket at the premarked position without buttonholing the skin envelope.",
        "Insert and orient the cartilage framework so vertical height, projection, and lobule relationship mirror the opposite ear.",
        "Apply controlled suction/bolster so skin conforms to the framework contours without ischemic pressure.",
        "Close the donor and recipient sites and verify chest stability and framework skin perfusion.",
        "Document the staged elevation/lobule/tragal refinement plan and monitor closely for hematoma, skin compromise, infection, or cartilage exposure.",
    ],
    "middle-fossa-skull-base": [
        "Position and perform the temporal craniotomy centered over the middle fossa, then elevate dura from posterior to anterior with minimal fixed temporal-lobe retraction.",
        "Identify the arcuate eminence, greater superficial petrosal nerve, petrous ridge, and middle meningeal/foramen spinosum landmarks before drilling.",
        "Use the chosen landmark strategy to localize the internal auditory canal and skeletonize it with diamond drilling while protecting cochlea, labyrinth, and facial nerve.",
        "Open the IAC dura only after the bony limits are defined and identify facial/cochlear/vestibular nerve relationships under magnification.",
        "Perform the intended tumor, facial-nerve, or superior-canal work with continuous awareness of the geniculate ganglion and labyrinthine facial segment.",
        "Seal any opened petrous air cells and reconstruct drilled defects to prevent postoperative CSF egress to the middle ear/mastoid.",
        "Obtain meticulous dural hemostasis and watertight closure, allowing the temporal lobe to return without focal compression.",
        "Replace the craniotomy and close layers while documenting immediate facial, hearing, vestibular, and neurologic assessment.",
    ],
    "otoplasty": [
        "Mark the desired antihelical fold, conchal position, and helical-mastoid relationship bilaterally before infiltration, comparing symmetry from frontal and posterior views.",
        "Use a posterior auricular incision and elevate skin/perichondrial flaps only as needed to expose the deforming cartilage while preserving vascularity.",
        "Create or weaken the antihelical fold with cartilage-sparing sutures/scoring according to cartilage stiffness, avoiding full-thickness anterior skin injury.",
        "Place Mustardé-type mattress sutures to establish the antihelix with smooth curvature rather than a sharp ridge.",
        "Correct conchal excess/protrusion with concha-mastoid sutures or conservative cartilage reduction while protecting the external auditory canal.",
        "Address lobule projection and superior-pole asymmetry before tying final sutures permanently.",
        "Compare both ears for projection, contour, and absence of telephone/reverse-telephone deformity, then obtain meticulous hemostasis.",
        "Close without exposed permanent sutures and apply a nonischemic protective dressing while monitoring for hematoma and cartilage infection.",
    ],
    "palatoplasty": [
        "Expose the cleft palate with a mouth gag and mark oral/nasal mucosal flaps, relaxing incisions, and greater-palatal neurovascular pedicles before cutting.",
        "Elevate oral mucoperiosteal flaps while preserving the greater palatine pedicles and create enough mobility for a tension-free midline closure.",
        "Separate nasal mucosa from the hard-palate edge and vomer as required, then close the nasal layer continuously/interrupted without leaving a fistula gap.",
        "Dissect the abnormal levator veli palatini insertions from the posterior hard palate and reorient the muscle sling transversely in an intravelar veloplasty.",
        "Reconstruct the uvula/soft palate with aligned nasal, muscle, and oral layers while avoiding excess tension or airway-narrowing bulk.",
        "Close the oral mucosal layer from posterior to anterior and secure hard-palate flaps without strangulating their pedicles.",
        "Inspect for exposed bone, pedicle kinking, bleeding, and symmetric palatal length/mobility; avoid tight packing against the repair.",
        "Remove the gag after checking tongue/teeth and institute postoperative airway, hydration, arm-restraint/feeding, fistula, and speech follow-up plans.",
    ],
    "pharyngocutaneous-fistula": [
        "Define the fistula tract, pharyngeal defect, salivary contamination, carotid exposure risk, nutritional status, and prior radiation before committing to closure.",
        "Open/drain infected or necrotic tissue adequately and debride nonviable wound edges until a healthy vascularized bed is present.",
        "Identify and protect great vessels and reconstructive pedicles; obtain vascularized coverage urgently if carotid exposure is present.",
        "Mobilize pharyngeal mucosa to permit a watertight, tension-free internal closure when direct closure is feasible.",
        "Reinforce the pharyngeal repair with well-vascularized regional or free tissue—commonly pectoralis or free flap—when tissue quality is poor or the defect is large.",
        "Separate salivary tract from neck skin/great vessels and obliterate dead space without compressing flap pedicles.",
        "Place drains away from exposed vessels/anastomoses and confirm hemostasis before external closure.",
        "Maintain enteral nutrition away from the repair and define postoperative wound, leak-testing, antibiotic, and carotid-bleed emergency plans.",
    ],
    "reconstructive-palate": [
        "Confirm the level and pattern of retropalatal collapse and choose the planned expansion/lateral-pharyngeal reconstructive technique before incision.",
        "Expose the soft palate/tonsillar fossae and identify palatopharyngeus, palatoglossus, superior constrictor, uvula, and neurovascular tissue to be preserved.",
        "Perform tonsillectomy first when part of the operation, maintaining a clean capsular plane and controlling bleeding before palatal reconstruction.",
        "Mobilize the selected palatopharyngeus or lateral pharyngeal tissue from restrictive attachments without denervating or devascularizing the flap.",
        "Reposition/suspend the muscle anterolaterally to enlarge the retropalatal airway rather than simply resecting central palate tissue.",
        "Close mucosal flaps over the reconstructed muscle with symmetric tension and avoid excessive shortening that would impair velopharyngeal function/swallowing.",
        "Inspect the resulting airway, uvular/palatal symmetry, and hemostasis with suspension released.",
        "Plan monitored postoperative airway care and specifically track hemorrhage, dysphagia, velopharyngeal insufficiency, and residual OSA.",
    ],
    "retrosigmoid-skull-base": [
        "Position to expose the retrosigmoid region and create a craniotomy/craniectomy with the transverse-sigmoid junction defined and venous sinus protected.",
        "Open dura and release cisternal CSF to relax the cerebellum before using fixed retraction.",
        "Identify the lower cranial nerves, VII-VIII complex, brainstem, petrosal veins, and tumor/neurovascular target under the microscope.",
        "Open the arachnoid planes and internally debulk a mass when needed before attempting circumferential capsule mobilization.",
        "For IAC pathology, drill the posterior canal wall to the needed extent with orientation to labyrinth/endolymphatic structures and protect the facial/cochlear nerves.",
        "Dissect the lesion from brainstem and cranial nerves in small segments, using facial-nerve stimulation and avoiding avulsion of adherent vessels/nerves.",
        "Seal opened mastoid/petrous air cells meticulously and achieve watertight dural closure to reduce CSF leak.",
        "Replace/repair the bony defect and close layers with postoperative facial, hearing, vestibular, lower-cranial-nerve, and neurologic assessment.",
    ],
    "rigid-tracheobronchoscopy": [
        "Coordinate ventilation with anesthesia and obtain direct laryngoscopic exposure before introducing the rigid bronchoscope through the vocal folds.",
        "Advance the bronchoscope under continuous vision through subglottis and trachea, maintaining orientation to the membranous posterior wall.",
        "Inspect the carina and both mainstem bronchi systematically, advancing into lobar bronchi as the indication and scope size permit.",
        "Document stenosis, lesion, secretion burden, dynamic collapse, or foreign body before performing therapeutic manipulation.",
        "For biopsy/debridement, keep forceps and energy devices in the visual field and coordinate FiO2/laser-fire precautions when applicable.",
        "For foreign body removal, secure the object with an appropriate forceps and withdraw it in a controlled fashion rather than pushing it distally.",
        "Reinspect the complete airway after intervention for bleeding, mucosal injury, residual object/lesion, and bilateral ventilation.",
        "Remove the bronchoscope under vision and establish postoperative airway observation based on edema, bleeding, hypoxia, or intervention performed.",
    ],
    "rrp-debridement": [
        "Obtain atraumatic suspension microlaryngoscopy and map papilloma burden across supraglottis, true folds, anterior commissure, subglottis, and trachea before treatment.",
        "Set laser/energy safety parameters with anesthesia, including reduced FiO2 when appropriate, eye protection, wet pledgets, and laser-safe airway equipment for laser cases.",
        "Begin debulking at sites that improve exposure while preserving normal epithelium and the vocal-fold layered structure.",
        "Remove papilloma with microdebrider/laser in small controlled increments, avoiding deep injury to vocal ligament, anterior commissure, and opposing raw surfaces.",
        "Treat anterior commissure disease conservatively enough to reduce web risk rather than pursuing indiscriminate complete epithelial stripping.",
        "Inspect subglottis/trachea for distal disease and treat only lesions safely accessible within the planned procedure.",
        "Control bleeding with minimal thermal injury and remove all loose papilloma fragments from the airway.",
        "Reinspect the airway and document residual intentional disease, adjunct injection if used, voice/airway plan, and interval for repeat surveillance.",
    ],
    "septorhino": [
        "Analyze and mark the external nasal deformity, septum, internal/external valves, dorsal lines, tip support, and airway goals before infiltration and incision.",
        "Expose the septum through open or endonasal approach and elevate mucoperichondrial flaps while preserving a structurally adequate dorsal/caudal L-strut.",
        "Harvest only the septal cartilage needed for reconstruction and correct obstructing bony/cartilaginous deviation without destabilizing the keystone area.",
        "Open and reconstruct the middle vault as needed, preserving or restoring internal nasal-valve angle with spreader graft/flap or equivalent support.",
        "Perform dorsal reduction/augmentation and controlled osteotomies as required, protecting mucosa and maintaining symmetric dorsal aesthetic lines.",
        "Rebuild tip/caudal support with the planned septal extension, columellar strut, lateral-crural, or alar-batten grafts to correct external valve collapse without over-rotation.",
        "Reassess septum, valve patency, tip symmetry, dorsal contour, and bony pyramid before closing mucosa/skin and replacing septum in the midline.",
        "Apply internal splints/external cast selectively and document airway, skin-perfusion, and postoperative edema/bleeding precautions.",
    ],
    "skin-graft-face": [
        "Prepare the recipient defect to a clean, well-vascularized bed and achieve meticulous hemostasis before harvesting the graft.",
        "Template the defect accurately and choose full-thickness versus split-thickness donor skin based on contour, contraction risk, color/texture, and recipient vascularity.",
        "Harvest the graft at uniform thickness; for full-thickness graft, remove excess subcutaneous fat until only dermis remains without perforating it.",
        "Orient and trim the graft to fit the defect exactly without folding, excessive tension, or unnecessary overlap.",
        "Secure the graft perimeter and internal quilting/basting sutures so the undersurface remains in complete contact with the vascular bed.",
        "Evacuate any blood/air trapped beneath the graft and obtain hemostasis without lifting the construct repeatedly.",
        "Apply a bolster or pressure dressing that immobilizes the graft without causing ischemic compression of surrounding facial structures.",
        "Close/dress the donor site and document the timing of bolster removal and monitoring for hematoma, infection, shear, and graft loss.",
    ],
    "supraglottoplasty": [
        "Obtain suspension microlaryngoscopy and bronchoscopy first to confirm severe laryngomalacia and exclude synchronous airway lesions.",
        "Identify shortened aryepiglottic folds, redundant arytenoid mucosa, epiglottic configuration, interarytenoid mucosa, and both true vocal folds before cutting.",
        "Divide the aryepiglottic fold on one side in a controlled lateral location, avoiding deep injury toward the superior laryngeal neurovascular structures.",
        "Trim only clearly redundant supra-arytenoid mucosa while preserving the interarytenoid/posterior commissure mucosa to reduce stenosis risk.",
        "Repeat the planned release on the opposite side while maintaining symmetry and avoiding excessive bilateral raw surfaces.",
        "Reassess epiglottic prolapse and supraglottic opening during spontaneous respiration when feasible; perform epiglottopexy only when specifically indicated.",
        "Control focal bleeding and inspect the true folds/subglottis for thermal or mechanical injury.",
        "End with a clearly documented postoperative airway/feeding observation plan because edema and aspiration risk can worsen transiently after surgery.",
    ],
    "translabyrinthine-skull-base": [
        "Perform a wide cortical mastoidectomy and identify tegmen, sigmoid sinus, posterior canal wall, facial nerve, and all three semicircular canals.",
        "Skeletonize the sigmoid sinus and middle/posterior fossa dura as needed, then exenterate the labyrinth deliberately because hearing preservation is not possible with this corridor.",
        "Identify the vestibule and follow the labyrinthine anatomy toward the internal auditory canal while preserving the facial nerve.",
        "Skeletonize the IAC circumferentially to the fundus with diamond drilling, protecting the facial nerve and avoiding uncontrolled dural entry.",
        "Open the IAC/posterior-fossa dura, identify the facial nerve, and internally debulk the vestibular schwannoma or other target before capsule dissection.",
        "Dissect tumor from the facial nerve and brainstem in small segments with stimulation, accepting deliberate residual tumor if the nerve is inseparable and preservation is the priority.",
        "Obliterate the Eustachian tube/middle-ear pathway and exposed petrous air cells as required, then pack the mastoid defect with abdominal fat or planned reconstruction.",
        "Achieve watertight closure and document immediate facial-nerve function, CSF-leak surveillance, vestibular rehabilitation, and wound monitoring.",
    ],
    "transnasal-esophagoscopy": [
        "Topically anesthetize/decongest the selected nasal cavity and pass the flexible scope along the nasal floor while avoiding turbinate trauma.",
        "Inspect nasopharynx, oropharynx, hypopharynx, and larynx during advancement, then enter the esophageal inlet under direct visualization rather than blind pressure.",
        "Advance through cervical and thoracic esophagus while insufflating only enough for mucosal inspection and documenting lesions/strictures by level.",
        "Traverse the gastroesophageal junction when the indication requires and inspect the proximal stomach before withdrawal.",
        "Obtain biopsies under direct vision with the scope stabilized and avoid sampling immediately adjacent to major extrinsic vascular compression or suspected perforation.",
        "For dilation, pass guidewire/dilator only after the lumen and stricture axis are clearly defined and use incremental sizing rather than force.",
        "Withdraw slowly with a second circumferential inspection for bleeding, mucosal tear, or missed pathology.",
        "Document findings, biopsy sites, dilation size if performed, and postprocedure warning signs for perforation or bleeding.",
    ],
    "transoral-laser-laryngeal-cancer": [
        "Obtain complete suspension-laryngoscopic exposure of the tumor and map its mucosal/deep extent before laser activation, including anterior commissure, ventricle, paraglottic space, and subglottic extension.",
        "Institute laser-fire precautions with anesthesia, including laser-safe tube when appropriate, low FiO2, wet protection, smoke evacuation, and team laser time-out.",
        "Mark a mucosal margin around the lesion and begin resection in an orientation that preserves recognizable anatomic planes and allows specimen reconstruction by pathology.",
        "Divide the tumor en bloc or in planned oncologic blocks, using the cut surface to assess depth toward vocal ligament, paraglottic space, cartilage, and anterior commissure.",
        "Control named/sizable vessels before they retract and avoid char that obscures the true deep margin.",
        "Orient specimens precisely and obtain separate patient-bed margins when indicated, returning to suspicious areas before ending exposure.",
        "Reinspect the larynx for hemostasis, airway caliber, exposed cartilage, and avoid unnecessary opposing mucosal injury that would create web/stenosis.",
        "Set the extubation, airway observation, voice/swallow rehabilitation, and pathology-driven next-treatment plan.",
    ],
    "tympanostomy-tubes": [
        "Inspect the ear canal and tympanic membrane under the microscope, remove obstructing cerumen, and identify the planned anteroinferior or posteroinferior myringotomy site away from ossicles.",
        "Make a small radial myringotomy through the tympanic membrane without plunging the knife into the middle ear.",
        "Suction middle-ear effusion through the incision and characterize it without repeatedly traumatizing the middle-ear mucosa.",
        "Grasp the tube by its flange and insert the medial flange through the myringotomy under microscopic visualization.",
        "Rotate/seat the tube so both flanges are correctly positioned and the lumen is patent rather than buried in canal skin or middle-ear mucosa.",
        "Clear blood or mucus from the tube lumen and instill topical drops when indicated.",
        "Repeat the complete microscopic procedure on the opposite ear when bilateral tubes are planned, reassessing that side independently rather than assuming identical anatomy.",
        "Perform a final bilateral check for tube position, patency, canal trauma, and active bleeding before emergence.",
    ],
    "tonsillectomy-adenoidectomy": [
        "Insert and suspend the mouth gag with teeth/tongue protected, inspect the palate for submucous cleft, and expose both tonsils before starting.",
        "Grasp the first tonsil medially, enter the plane between capsule and superior constrictor at the superior pole, and follow the capsule to the lower pole with traction-countertraction.",
        "Control focal tonsillar-bed bleeding and repeat the full capsular or planned intracapsular dissection on the opposite tonsil.",
        "Retract the soft palate and visualize the adenoid pad, choanae, vomer, and both Eustachian-tube orifices with mirror/endoscope.",
        "Remove obstructing adenoid tissue while protecting the torus tubarius and avoiding excessive inferior resection in a child at risk for velopharyngeal insufficiency.",
        "Inspect the nasopharynx for residual choanal obstruction and obtain targeted adenoid-bed hemostasis rather than broad deep cautery.",
        "Irrigate/suction and briefly release suspension so occult tonsillar or adenoid bleeding declares itself at more physiologic pressure.",
        "Reinspect both tonsillar fossae and nasopharynx, remove all packing/instruments, and confirm no dental/oral injury or active hemorrhage before emergence.",
    ],
    "button-battery": [
        "Treat an esophageal button battery as an immediate removal emergency: secure the airway and proceed to endoscopy without delaying for nonessential testing.",
        "Expose the battery under direct esophagoscopy and assess the surrounding mucosa before grasping so the most stable extraction orientation is chosen.",
        "Remove the battery along the esophageal axis without fragmentation, prolonged manipulation, or pushing it distally.",
        "Reinsert the scope and inspect the injury circumferentially for depth of necrosis, perforation, bleeding, and relationship to the airway/aortic level.",
        "Avoid aggressive debridement of adherent necrosis that could unmask a contained perforation or vascular injury.",
        "Survey for additional foreign material and document the exact level and severity of mucosal injury.",
        "Institute NPO, imaging, antimicrobial, feeding-access, and vascular/airway surveillance according to injury depth and location.",
        "Maintain explicit delayed-hemorrhage/fistula precautions because catastrophic aorto-esophageal or tracheoesophageal complications may occur after removal.",
    ],
    "esophageal-fb": [
        "Secure the airway when aspiration risk, sharp object, proximal impaction, or patient age requires it and choose rigid versus flexible esophagoscopy based on object/location.",
        "Advance under direct visualization to the object without blindly pushing it distally or driving sharp edges into the wall.",
        "Assess object orientation, impaction depth, and surrounding mucosa before selecting grasping forceps, basket, net, or protective hood.",
        "Capture the safest stable edge and withdraw the object with the scope/protection as needed so sharp or broad surfaces do not shear the esophagus.",
        "Re-examine the impaction site for ulceration, laceration, perforation, bleeding, or retained fragments.",
        "Survey the remaining esophagus when safe, especially when ingestion history is uncertain or multiple objects are possible.",
        "If perforation is suspected, stop routine feeding and escalate imaging/surgical management rather than continuing traumatic instrumentation.",
        "Document object, level, mucosal injury, diet/observation plan, and return precautions for chest/neck pain, fever, dyspnea, or bleeding.",
    ],
}


def apply_or_procedure_sequences_v201(registry):
    applied = []
    missing = []
    for slug, seq in EXACT.items():
        op = (registry or {}).get(slug)
        if not op:
            missing.append(slug)
            continue
        op["steps"] = list(seq)
        op["sequence_status_v200"] = "procedure-specific"
        op["sequence_status_v201"] = "exact-procedure-reviewed"
        applied.append(slug)
    return {"applied": applied, "count": len(applied), "missing_registry_slugs": missing}
