"""v42.0: add two procedure-specific attending follow-ups to 38 thin cards.

Only cards whose live ``attending_followup`` is still a valid one-pair list
are changed.  This makes the layer idempotent and preserves later or
independently deepened content.
"""
from copy import deepcopy


def p(q1, a1, q2, a2):
    return [(q1, a1), (q2, a2)]


ADDITIONS = {
 "stapedotomy":p("What should you do if the footplate becomes floating or grossly mobile?","Stop forceful manipulation, keep fragments out of the vestibule, control the oval window with soft tissue, and tailor or stage reconstruction according to exposure and surgeon experience; hearing preservation takes priority over completing the planned piston.","What finding should make you reconsider otosclerosis before fenestrating?","A freely mobile stapes or another mechanical lesion should trigger reassessment. A conductive/mixed loss, absent reflexes, normal drum and a 2-kHz Carhart notch support—but do not prove—otosclerosis."),
 "cochlear-implant":p("How do you protect the facial nerve and chorda during facial-recess exposure?","Identify the fossa incudis/short process superiorly, keep the facial nerve posteromedial and chorda lateral, use irrigation and monitoring, and enlarge only under direct anatomic control rather than drilling blindly toward either nerve.","How do ossification or inner-ear malformation change planning?","Review CT/MRI for lumen, nerve and aberrant facial course; anticipate drill-out, partial/split-array insertion, CSF gusher control and more variable performance, and counsel accordingly."),
 "neck-dissection":p("When should the clinically N0 oral-cavity neck receive elective treatment?","Treat when the estimated occult-node risk is roughly 15-20% or greater. DOI around 3-4 mm is commonly used to inform the decision, but subsite, tumor features, sentinel-node capability and current guideline context matter; 4 mm is not a universal standalone rule.","How do you control an intraoperative left level-IV chyle leak?","Expose the leak, clip or suture-ligate it, consider local muscle/fascial reinforcement, and test the repair with increased intrathoracic pressure before closure rather than relying on a drain alone."),
 "total-laryngectomy":p("Why might the pharyngoesophageal segment be addressed during laryngectomy?","Hypertonicity/spasm can impair tracheoesophageal speech. Selected patients may undergo myotomy, plexus neurectomy or later targeted treatment according to institutional technique; it is not a universal requirement.","When does a pharyngocutaneous fistula need operative rather than conservative care?","Small contained fistulas without sepsis, vessel exposure or major breakdown may close with diversion, wound care and nutrition. Large/high-output, infected, irradiated, vessel-threatening or persistent fistulas favor early vascularized-tissue closure."),
 "submandibular-gland":p("Which nerves require deliberate protection during gland excision?","Protect the marginal mandibular nerve during flap elevation, then identify the lingual and hypoglossal nerves in the deep field; the lingual nerve changes relationship around Wharton duct and gives ganglionic branches to the gland.","How does mylohyoid retraction help?","Anterior retraction exposes the posterior free edge, duct and lingual-nerve relationship so ganglionic branches and duct can be divided under vision without injuring the main lingual trunk."),
 "sialendoscopy":p("Which stones are suitable for purely endoscopic retrieval?","Small mobile distal stones—often around 3-4 mm or less, depending on duct and device—are best suited. Do not force an impacted basket; use lithotripsy or a combined approach to avoid duct avulsion.","How should duct perforation be handled?","Recognize extravasation/false passage early, stop traumatic advancement, reassess endoscopically and clinically, and use observation, stenting, antibiotics or open management according to location, contamination and associated injury."),
 "DLB":p("How do you prevent dental and lip injury during suspension?","Use a fitted guard/padding, optimize head and scope position, and stop if seating requires excessive force rather than levering on incisors or trapping the lip.","How should pediatric subglottic stenosis be sized?","Use graduated tubes and a standardized leak-pressure protocol, record tube manufacturer/outer diameter and grade with validated Myer–Cotton references; age formulas alone and calculations from nominal internal diameter are inadequate."),
 "airway-dilation":p("Why is posterior-wall injury especially concerning?","The posterior cricoid/subglottis lies immediately anterior to the esophagus. Dilate incrementally under direct vision and stop for deep or uncontrolled tearing to avoid perforation and mediastinal injury.","When do radial incisions or steroid accompany dilation?","Use stenosis morphology, length, etiology, prior response and scar maturity: a thin web may respond to dilation, while mature/recurrent fibrotic disease may need controlled incisions and selected steroid. Mitomycin use is selective because evidence is inconsistent."),
 "medialization":p("How do you judge medialization in an awake patient?","Use phonation, flexible visualization when available and airway/voice assessment during sizing. Stridor, airway narrowing or a markedly pressed voice suggests excessive medialization or malposition.","Why choose temporary injection at three months?","Recovery remains possible in many recent paralyses. Temporary augmentation can improve voice/swallow safety while serial exam and, when useful, LEMG clarify prognosis before permanent framework surgery."),
 "zenker":p("How does pouch size affect approach?","Rigid stapling generally needs enough pouch/common wall—often about 2 cm or more—for device seating; flexible septotomy may treat smaller pouches. Anatomy, exposure, comorbidity and local expertise matter more than a universal cutoff.","Why must treatment divide the cricopharyngeal bar?","Zenker is a pulsion pseudodiverticulum driven by outflow resistance at the pharyngoesophageal segment; treating the sac without an adequate myotomy/septotomy leaves the causal high-pressure zone."),
 "tonsillectomy":p("What is the intracapsular versus extracapsular tradeoff?","Intracapsular surgery usually reduces pain and secondary bleeding but carries residual-tissue/regrowth risk; it is commonly used for obstruction, while recurrent infection, abscess history or malignancy concern may favor extracapsular removal.","How should brisk post-tonsillectomy hemorrhage be managed?","Treat as an airway and hemorrhagic emergency: suction-ready positioning, NPO, IV access, resuscitation, labs/type-and-screen and urgent ENT/anesthesia mobilization for controlled operative hemostasis. Avoid repeated traumatic bedside manipulation or sedation in an unstable/uncooperative child."),
 "adenoidectomy":p("Why preserve tissue near the torus and velopharyngeal closure plane?","Over-resection can injure the Eustachian-tube orifice or unmask velopharyngeal insufficiency, especially with palatal abnormality.","What suggests occult submucous cleft before surgery?","Bifid uvula, zona pellucida, posterior hard-palate notch, hypernasality or nasal regurgitation should prompt palatal/velopharyngeal evaluation and consideration of partial adenoidectomy."),
 "thyroglossal":p("Why remove the central hyoid in a Sistrunk procedure?","The tract commonly passes through or closely behind the hyoid; removing the central segment and tract toward the tongue base lowers recurrence versus simple cyst excision while avoiding unnecessarily blind deep dissection.","What must be confirmed preoperatively?","Ultrasound should document orthotopic thyroid tissue; if absent or equivocal, obtain appropriate functional imaging/endocrine evaluation before removing tissue that could be the patient's only functioning thyroid."),
 "branchial":p("What must be excluded before excising a new lateral cystic neck mass in an adult?","Treat it as metastatic disease until proven otherwise—especially HPV-associated oropharyngeal SCC—using imaging, ultrasound-guided sampling and appropriate HPV testing/workup rather than open excision first.","What is the classic course of a second-cleft tract?","It passes between the carotid bifurcation toward the tonsillar fossa and relates closely to CN IX/XII; careful exposure is required because variants occur and incomplete tract removal promotes recurrence."),
 "orbital-floor":p("What pediatric finding requires urgent release?","A trapdoor fracture with motility restriction and oculocardiac symptoms such as nausea, vomiting or bradycardia suggests entrapment and requires urgent specialist repair despite a deceptively small CT defect.","How is implant material selected?","Base the choice on defect size/location, available bony ledges, contamination, patient age and surgeon experience. Rigid patient-specific/titanium constructs give durable posterior support; porous or resorbable materials have different handling and long-term tradeoffs."),
 "mandible-orif":p("What must be confirmed before final fixation?","Restore and document the patient's premorbid occlusion, using MMF/occlusal wear facets and dentition rather than imposing an idealized bite.","How do you protect the inferior alveolar nerve?","Map the canal and tooth roots on imaging, expose when indicated, and choose plate/screw position and length that avoid the canal; document pre- and postoperative sensation."),
 "zmc-orif":p("What drives observation versus ZMC repair?","CT-defined displacement and buttress/orbital involvement plus malar flattening, trismus, diplopia, enophthalmos or sensory dysfunction guide intervention; not every radiographic fracture needs fixation.","What should be checked after buttress reduction?","Reassess orbital floor/rim, forced ductions when indicated, globe position and orbital volume; an anatomic FZ/ZM appearance does not exclude a residual floor defect."),
 "hypoglossal-stimulator":p("Which DISE pattern excludes standard unilateral HNS candidacy?","Complete concentric palatal collapse predicts poor response and is an exclusion in standard labeling; confirm the current device-specific criteria because indications evolve.","Why test selective tongue activation intraoperatively?","The cuff should recruit protrusor branches without dominant retrusor activation. Visual tongue protrusion and stimulation testing confirm functional placement before fixation."),
 "microflap":p("What tissue plane must be preserved?","Protect epithelium and superficial lamina propria and avoid violating the vocal ligament; unnecessary deep dissection creates scar and permanent wave loss.","When should resection be conservative?","If the lesion/plane is indistinct, diffuse or tethered, prioritize preservation, pathology needs and staged/alternative management rather than removing normal vibratory tissue for visual completeness."),
 "rrp-debridement":p("What are the key laser-airway precautions?","Use a laser-safe airway plan, lowest feasible oxidizer concentration, wet protection, communication and immediate fire-response readiness. Avoid opposing raw surfaces at the anterior commissure when staging can reduce web risk.","When is adjuvant therapy considered?","Frequent surgery, distal spread or aggressive disease may justify intralesional/systemic bevacizumab or selected cidofovir in expert care; choice is individualized, with vaccination and surveillance incorporated."),
 "reconstructive-palate":p("What functional complication must palatal surgery avoid?","Excess shortening or sphincter disruption can cause VPI, hypernasality and nasal regurgitation; preserve adequate length and counsel about the airway-speech tradeoff.","How does DISE refine planning?","DISE can identify palatal pattern and multilevel collapse not predicted by awake exam, allowing targeted lateral-wall, tongue-base or epiglottic treatment rather than reflexive isolated palate surgery."),
 "lingual-tonsillectomy":p("Why is postoperative monitoring important?","Tongue-base edema and bleeding can rapidly compromise a previously difficult airway; monitoring level and extubation plan should reflect OSA severity, extent, comorbidity and intraoperative airway course.","When should extubation be delayed?","Extensive resection, marked edema/bleeding, difficult reintubation or poor respiratory reserve may justify planned postoperative intubation or rarely tracheostomy, decided with anesthesia rather than routinely."),
 "hyoid-genioglossus":p("What limits the genioglossus osteotomy?","Tooth roots, mental nerves, inferior alveolar canal and adequate mandibular bone bridges constrain the window; preoperative imaging and controlled cuts prevent devitalization, numbness and fracture.","Why combine hyoid suspension and genioglossus advancement?","They address related but distinct retrolingual/hypopharyngeal vectors; combination is most rational when evaluation shows multilevel collapse rather than as an automatic bundle."),
 "closed-nasal-reduction":p("What injuries must be excluded?","Inspect for septal hematoma, CSF leak, ocular injury and NOE/medial-canthal instability; these require management beyond simple closed reduction.","When is closed reduction timed?","After swelling permits assessment but before consolidation—often within roughly 1-2 weeks in adults and earlier in children—while recognizing fracture pattern and local practice."),
 "noe-orif":p("How is medial canthal tendon stability assessed?","Use careful bimanual/bowstring assessment and CT correlation; swelling alone is unreliable. Tendon-bearing central fragment stability determines whether fixation or transnasal canthopexy is required.","Why use Markowitz classification?","Types I-III describe the tendon-bearing fragment from intact/large to comminuted to tendon avulsion, helping plan simple fixation versus formal tendon reattachment."),
 "frontal-sinus-trauma":p("When can an anterior-table fracture be observed?","Minimal displacement without cosmetic deformity, posterior-table injury, CSF leak or outflow-tract obstruction may be observed with counseling and long-term surveillance for mucocele or contour change.","Why remove mucosa during obliteration/cranialization?","Trapped viable mucosa can continue secreting and form a delayed mucocele/mucopyocele, so meticulous stripping and outflow management are essential."),
 "bilobed-flap":p("What does the Zitelli modification improve?","A smaller total rotation arc—roughly 90 degrees divided between lobes—reduces standing cones and pincushioning compared with older larger-arc designs; design follows local laxity and tension lines.","Why preserve a broad pedicle and choose the second-lobe donor carefully?","The random-pattern subdermal plexus supplies the flap, while the second lobe should recruit mobile skin without pulling the alar rim or distorting the tip."),
 "melolabial-flap":p("What threatens flap survival and alar contour?","An overly narrow/twisted pedicle threatens perfusion, while inset tension can notch or blunt the ala; preserve a broad vascular base and structural lining/support as needed.","When choose an interpolated two-stage flap?","Larger/deeper alar defects needing robust external skin and contour may benefit; divide and inset only after adequate neovascularization, commonly around 3 weeks according to the reconstruction."),
 "cervicofacial-flap":p("Why is ectropion a risk?","Inferior flap tension transmits to the lower lid. Wide mobilization, vector planning and periosteal/fascial suspension offload the lid.","Which plane balances perfusion and nerve safety?","Plane selection varies by region and flap design; remain superficial to facial-nerve branches while preserving an adequate subdermal/SMAS-associated vascular supply, rather than applying one plane indiscriminately across cheek and neck."),
 "skin-graft-face":p("Why use a bolster?","Uniform immobility and contact prevent shear, hematoma and seroma during plasmatic imbibition/revascularization; early failure usually reflects bed, fluid, motion or infection problems.","Why choose full- over split-thickness facial graft?","Full-thickness grafts usually match texture and contract less but require a vascular bed and primarily closable donor site; split-thickness grafts take more readily and cover larger areas but contract and mismatch more."),
 "facial-nerve-reanimation":p("How does denervation duration change reconstruction?","Direct repair/grafting or nerve transfer is favored while native muscle remains reinnervatable, often within roughly 12-18 months; viability varies and may persist longer, so exam/EMG and intraoperative findings guide whether functional muscle transfer is needed.","Masseteric versus hypoglossal transfer—what is the tradeoff?","Masseteric transfer provides strong, rapid smile excursion but requires cortical retraining; partial hypoglossal techniques can improve tone with potential tongue morbidity. Dual inputs may combine excursion and spontaneity."),
 "free-flap-basics":p("How do venous and arterial compromise differ?","Venous congestion is blue, tense and produces brisk dark pinprick blood; arterial insufficiency is pale/cool with poor refill and little bleeding. Either requires immediate troubleshooting and rapid take-back when unresolved.","What adjuncts help monitor buried flaps?","Implantable Doppler and tissue oximetry can add trend data, but probe displacement/adjacent-vessel signals cause errors; clinical assessment and low threshold for exploration remain central."),
 "pharyngocutaneous-fistula":p("Why is a sentinel bleed an emergency?","Salivary contamination in an irradiated/dissected neck can erode carotid vessels. A small warning bleed warrants immediate airway/resuscitation planning and urgent vascular/interventional evaluation.","When is flap closure favored?","Large, persistent, infected, irradiated, strictured or vessel-exposing fistulas need healthy vascularized tissue rather than prolonged wound care alone."),
 "laryngeal-fracture":p("What is the airway principle in suspected major laryngeal trauma?","Preserve spontaneous ventilation, avoid repeated blind attempts and secure the airway with an experienced multidisciplinary plan—often awake tracheostomy when anatomy is disrupted; carefully selected fiberoptic intubation is not universally safe.","How do arytenoid dislocation and RLN injury differ?","Direct palpation assesses mechanical fixation/malposition and LEMG assesses innervation. Reduction may help dislocation; neural injury follows recovery/prognostic and later reanimation/medialization pathways."),
 "pta-drainage":p("What follows an unsuccessful aspiration?","Reassess landmarks and diagnosis. Imaging is indicated for atypical findings, toxic appearance, deep-space concern, failed treatment or uncertain extent—not automatically for ordinary PTA with expected trismus; use the OR when exposure/airway/cooperation is unsafe.","When consider immediate tonsillectomy?","Selected recurrent PTA/recurrent tonsillitis, failed drainage, airway concern or a patient already requiring general anesthesia may favor quinsy tonsillectomy, balanced against bleeding and institutional expertise."),
 "airway-fb":p("Why can a symptom-free interval after choking be misleading?","A retained radiolucent object may cause delayed air trapping, atelectasis or pneumonia despite a normal exam/radiograph; a compelling history and persistent suspicion justify bronchoscopy.","How does retrieval differ for organic versus sharp objects?","Friable organic material requires controlled grasping and fragment clearance; sharp objects must be oriented to shield the point and removed under continuous visualization with bleeding/airway rescue ready."),
 "esophageal-fb":p("How does urgency differ by object?","Esophageal button batteries are emergent and sharp objects urgent; coins/blunt objects should generally be removed within 24 hours, sooner for symptoms, complete obstruction or proximal location. Brief observation applies only to carefully selected cases under a defined protocol.","Where do objects commonly lodge?","Natural narrowings include the upper esophageal sphincter, aortic/bronchial crossing and LES. Localization guides controlled endoscopy and alerts the team to adjacent vascular/airway risk."),
 "button-battery":p("Why must exact location and timing be established?","An esophageal battery causes rapid hydroxide injury and demands immediate removal. A gastric battery is not automatically benign: management depends on symptoms, age, battery size, co-ingestion, magnet, duration and evidence of prior esophageal impaction, using current Poison Center guidance.","What does delayed hematemesis after removal mean?","Assume aortoenteric fistula or other major vascular erosion until proven otherwise; protect airway, activate massive resuscitation and obtain immediate cardiothoracic/vascular/interventional help rather than relying on endoscopic hemostasis."),
}


def apply_or_prep_followup_depth_v420(data_module, app_module=None):
    source = getattr(data_module, "OR_PREP_REGISTRY", None)
    if not isinstance(source, dict):
        raise RuntimeError("v42.0: OR_PREP_REGISTRY unavailable")
    ops = deepcopy(source)
    added, preserved = [], []
    for slug, pairs in ADDITIONS.items():
        card = ops.get(slug)
        if not isinstance(card, dict):
            preserved.append(slug + ":missing")
            continue
        current = card.get("attending_followup")
        valid = isinstance(current, list) and all(
            isinstance(row, (list, tuple)) and len(row) == 2
            and all(isinstance(x, str) and x.strip() for x in row)
            for row in current
        )
        if not valid:
            preserved.append(slug + ":malformed")
        elif len(current) == 1:
            card["attending_followup"] = deepcopy(current) + [list(row) for row in pairs]
            added.append(slug)
        else:
            preserved.append(slug + ":already-deepened")
    data_module.OR_PREP_REGISTRY.clear()
    data_module.OR_PREP_REGISTRY.update(ops)
    if app_module is not None:
        app_module.OR_PREP_REGISTRY = data_module.OR_PREP_REGISTRY
    return {"followup_depth_added": added, "followup_depth_preserved": preserved}
