"""Production entrypoint with the Pasha review subsystem registered last.

Importing runtime_entry first preserves all existing curriculum/practice repairs before
Pasha maps its review bank to the final live question objects.
"""
import runtime_entry
from interpretation_labs_cleanup_v250 import apply_interpretation_labs_cleanup_v250
from pasha_routes import bp as pasha_review_blueprint
from practice_bank_navigation_v150 import install_practice_bank_navigation_v150
from deep_curriculum_otology_v284 import apply_otology_etd_rebuild_v284
from deep_curriculum_production_chain_v314 import apply_deep_curriculum_production_chain_v314
from deep_curriculum_rhinology_v363 import apply_rhinology_allergy_source_trace_v363
from deep_curriculum_snhl_v372 import apply_snhl_bedside_exam_v372
from deep_curriculum_dtc_rai_v373 import apply_dtc_rai_criteria_v373
from deep_curriculum_otology_v374 import apply_vestibular_schwannoma_criteria_v374
from deep_curriculum_rai_tsh_v375 import apply_rai_tsh_dtc_criteria_v375
from deep_curriculum_crssnp_v376 import apply_crssnp_management_v376
from deep_curriculum_peds_crs_v377 import apply_pediatric_crs_surgery_v377
from deep_curriculum_named_grading_v378 import apply_named_grading_criteria_v378
from deep_curriculum_named_grading_criteria_v379 import apply_named_grading_criteria_v379
from deep_curriculum_named_grading_criteria_v380 import apply_mtd_depth_v380
from or_tonsil_hemorrhage_rescue_v281 import apply_or_tonsil_hemorrhage_rescue_v281
from or_thyroid_hematoma_rescue_v282 import apply_or_thyroid_hematoma_rescue_v282
from or_tracheostomy_hemorrhage_rescue_v283 import apply_or_tracheostomy_hemorrhage_rescue_v283
from or_septal_hematoma_rescue_v284 import apply_or_septal_hematoma_rescue_v284
from or_esophageal_perforation_rescue_v285 import apply_or_esophageal_perforation_rescue_v285
from or_laryngectomy_fistula_rescue_v287 import apply_or_laryngectomy_fistula_rescue_v287
from or_airway_fire_rescue_v288 import apply_or_airway_fire_rescue_v288
from or_posterior_epistaxis_rescue_v289 import apply_or_posterior_epistaxis_rescue_v289
from or_tep_prosthesis_rescue_v290 import apply_or_tep_prosthesis_rescue_v290
from or_zenker_perforation_rescue_v291 import apply_or_zenker_perforation_rescue_v291
from or_airway_dilation_injury_rescue_v292 import apply_or_airway_dilation_injury_rescue_v292
from or_prep_indications_fix_v381 import apply_or_prep_indications_fix_v381
from or_prep_indications_fix_v382 import apply_or_prep_indications_fix_v382
from daily_curriculum_quality_v368 import install_daily_curriculum_quality_v368
from daily_curriculum_quality_v370 import install_daily_curriculum_quality_v370
from daily_curriculum_quality_v371 import install_daily_curriculum_quality_v371
from daily_curriculum_rhinology_selective_v382 import install_daily_curriculum_rhinology_selective_v382
from question_quality_repairs_v371 import install_question_quality_repairs_v371
from why_wrong_fix_general_ent_v1 import apply_why_wrong_fix_general_ent_v1
from why_wrong_fix_laryngology_v1 import apply_why_wrong_fix_laryngology_v1
from why_wrong_fix_head_neck_v1 import apply_why_wrong_fix_head_neck_v1
from why_wrong_fix_rhinology_v1 import apply_why_wrong_fix_rhinology_v1
from why_wrong_fix_pediatric_v1 import apply_why_wrong_fix_pediatric_v1
from why_wrong_fix_facial_plastics_v1 import apply_why_wrong_fix_facial_plastics_v1
from why_wrong_fix_otology_v1 import apply_why_wrong_fix_otology_v1
from why_wrong_fix_thyroid_v1 import apply_why_wrong_fix_thyroid_v1
from why_wrong_fix_sleep_v1 import apply_why_wrong_fix_sleep_v1
from why_wrong_fix_vignettes_v137_v1 import apply_why_wrong_fix_vignettes_v137_v1
from why_wrong_fix_vignettes_v138_v1 import apply_why_wrong_fix_vignettes_v138_v1
from why_wrong_fix_vignettes_v139_v1 import apply_why_wrong_fix_vignettes_v139_v1
from deep_curriculum_crswnp_biologics_named_v383 import apply_crswnp_biologics_named_v383
from or_prep_linked_topic_fix_v384 import apply_or_prep_linked_topic_fix_v384
from concept_daily_linking_v384 import install_concept_daily_linking_v384
from or_prep_concept_link_guard_v385 import install_or_prep_concept_link_guard_v385
from deep_curriculum_new_topics_v386 import apply_deep_curriculum_new_topics_v386
from prerequisites_gating_fix_v387 import install_prerequisites_gating_fix_v387
from concept_or_link_fix_v388 import install_concept_or_link_fix_v388
from thyroglossal_duct_cyst_depth_v389 import apply_thyroglossal_duct_cyst_depth_v389
from depth_content_sleep_surgery_v390 import apply_depth_content_sleep_surgery_v390
from depth_content_general_ent_v391 import apply_depth_content_general_ent_v391
from depth_content_facial_plastics_v392 import apply_depth_content_facial_plastics_v392
from depth_content_thyroid_parathyroid_v393 import apply_depth_content_thyroid_parathyroid_v393
from depth_content_otology_v394 import apply_depth_content_otology_v394
from depth_content_rhinology_v395 import apply_depth_content_rhinology_v395
from depth_content_head_neck_oncology_v396 import apply_depth_content_head_neck_oncology_v396
from depth_content_pediatric_ent_v397 import apply_depth_content_pediatric_ent_v397
from depth_content_laryngology_v398 import apply_depth_content_laryngology_v398

OTOLOGY_ETD_REBUILD_V284 = apply_otology_etd_rebuild_v284(runtime_entry.data, runtime_entry.app_mod)
DEEP_CURRICULUM_PRODUCTION_CHAIN_V314 = apply_deep_curriculum_production_chain_v314(runtime_entry.data, runtime_entry.app_mod)
RHINOLOGY_ALLERGY_SOURCE_TRACE_V363 = apply_rhinology_allergy_source_trace_v363(runtime_entry.data, runtime_entry.app_mod)
SNHL_BEDSIDE_EXAM_V372 = apply_snhl_bedside_exam_v372(runtime_entry.data, runtime_entry.app_mod)
DTC_RAI_CRITERIA_V373 = apply_dtc_rai_criteria_v373(runtime_entry.data, runtime_entry.app_mod)
VESTIBULAR_SCHWANNOMA_CRITERIA_V374 = apply_vestibular_schwannoma_criteria_v374(runtime_entry.data, runtime_entry.app_mod)
RAI_TSH_DTC_CRITERIA_V375 = apply_rai_tsh_dtc_criteria_v375(runtime_entry.data, runtime_entry.app_mod)
CRSSNP_MANAGEMENT_V376 = apply_crssnp_management_v376(runtime_entry.data, runtime_entry.app_mod)
PEDIATRIC_CRS_SURGERY_V377 = apply_pediatric_crs_surgery_v377(runtime_entry.data, runtime_entry.app_mod)
NAMED_GRADING_CRITERIA_V378 = apply_named_grading_criteria_v378(runtime_entry.data, runtime_entry.app_mod)
NAMED_GRADING_CRITERIA_V379 = apply_named_grading_criteria_v379(runtime_entry.data, runtime_entry.app_mod)
MTD_DEPTH_V380 = apply_mtd_depth_v380(runtime_entry.data, runtime_entry.app_mod)
OR_TONSIL_HEMORRHAGE_RESCUE_V281 = apply_or_tonsil_hemorrhage_rescue_v281(runtime_entry.data.OR_PREP_REGISTRY)
OR_THYROID_HEMATOMA_RESCUE_V282 = apply_or_thyroid_hematoma_rescue_v282(runtime_entry.data.OR_PREP_REGISTRY)
OR_TRACHEOSTOMY_HEMORRHAGE_RESCUE_V283 = apply_or_tracheostomy_hemorrhage_rescue_v283(runtime_entry.data.OR_PREP_REGISTRY)
OR_SEPTAL_HEMATOMA_RESCUE_V284 = apply_or_septal_hematoma_rescue_v284(runtime_entry.data.OR_PREP_REGISTRY)
OR_ESOPHAGEAL_PERFORATION_RESCUE_V285 = apply_or_esophageal_perforation_rescue_v285(runtime_entry.data.OR_PREP_REGISTRY)
OR_LARYNGECTOMY_FISTULA_RESCUE_V287 = apply_or_laryngectomy_fistula_rescue_v287(runtime_entry.data.OR_PREP_REGISTRY)
OR_AIRWAY_FIRE_RESCUE_V288 = apply_or_airway_fire_rescue_v288(runtime_entry.data.OR_PREP_REGISTRY)
OR_POSTERIOR_EPISTAXIS_RESCUE_V289 = apply_or_posterior_epistaxis_rescue_v289(runtime_entry.data.OR_PREP_REGISTRY)
OR_TEP_PROSTHESIS_RESCUE_V290 = apply_or_tep_prosthesis_rescue_v290(runtime_entry.data.OR_PREP_REGISTRY)
OR_ZENKER_PERFORATION_RESCUE_V291 = apply_or_zenker_perforation_rescue_v291(runtime_entry.data.OR_PREP_REGISTRY)
OR_AIRWAY_DILATION_INJURY_RESCUE_V292 = apply_or_airway_dilation_injury_rescue_v292(runtime_entry.data.OR_PREP_REGISTRY)
OR_PREP_INDICATIONS_FIX_V381 = apply_or_prep_indications_fix_v381(runtime_entry.data.OR_PREP_REGISTRY)
OR_PREP_INDICATIONS_FIX_V382 = apply_or_prep_indications_fix_v382(runtime_entry.data.OR_PREP_REGISTRY)
DAILY_CURRICULUM_QUALITY_V368 = install_daily_curriculum_quality_v368(runtime_entry.data, runtime_entry.app_mod)
DAILY_CURRICULUM_QUALITY_V370 = install_daily_curriculum_quality_v370(runtime_entry.data, runtime_entry.app_mod)

# Reconciled Daily v37.1 runs before the newer global question-quality and domain
# distractor-reasoning layers, so it can improve prompt/answer alignment without
# overwriting their final challenge feedback.
DAILY_CURRICULUM_QUALITY_V371 = install_daily_curriculum_quality_v371(runtime_entry.data, runtime_entry.app_mod)
DAILY_CURRICULUM_RHINOLOGY_SELECTIVE_V382 = install_daily_curriculum_rhinology_selective_v382(runtime_entry.data, runtime_entry.app_mod)
QUESTION_QUALITY_REPAIRS_V371 = install_question_quality_repairs_v371(runtime_entry.data, runtime_entry.app_mod)
WHY_WRONG_FIX_GENERAL_ENT_V1 = apply_why_wrong_fix_general_ent_v1(runtime_entry.data)
WHY_WRONG_FIX_LARYNGOLOGY_V1 = apply_why_wrong_fix_laryngology_v1(runtime_entry.data)
WHY_WRONG_FIX_HEAD_NECK_V1 = apply_why_wrong_fix_head_neck_v1(runtime_entry.data)
WHY_WRONG_FIX_RHINOLOGY_V1 = apply_why_wrong_fix_rhinology_v1(runtime_entry.data)
WHY_WRONG_FIX_PEDIATRIC_V1 = apply_why_wrong_fix_pediatric_v1(runtime_entry.data)
WHY_WRONG_FIX_FACIAL_PLASTICS_V1 = apply_why_wrong_fix_facial_plastics_v1(runtime_entry.data)
WHY_WRONG_FIX_OTOLOGY_V1 = apply_why_wrong_fix_otology_v1(runtime_entry.data)
WHY_WRONG_FIX_THYROID_V1 = apply_why_wrong_fix_thyroid_v1(runtime_entry.data)
WHY_WRONG_FIX_SLEEP_V1 = apply_why_wrong_fix_sleep_v1(runtime_entry.data)
WHY_WRONG_FIX_VIGNETTES_V137_V1 = apply_why_wrong_fix_vignettes_v137_v1(runtime_entry.data)
WHY_WRONG_FIX_VIGNETTES_V138_V1 = apply_why_wrong_fix_vignettes_v138_v1(runtime_entry.data)
WHY_WRONG_FIX_VIGNETTES_V139_V1 = apply_why_wrong_fix_vignettes_v139_v1(runtime_entry.data)
CRSWNP_BIOLOGICS_NAMED_V383 = apply_crswnp_biologics_named_v383(runtime_entry.data, runtime_entry.app_mod)
OR_PREP_LINKED_TOPIC_FIX_V384 = apply_or_prep_linked_topic_fix_v384(runtime_entry.data.OR_PREP_REGISTRY)
DEEP_CURRICULUM_NEW_TOPICS_V386 = apply_deep_curriculum_new_topics_v386(runtime_entry.data, runtime_entry.app_mod)
THYROGLOSSAL_DUCT_CYST_DEPTH_V389 = apply_thyroglossal_duct_cyst_depth_v389(runtime_entry.data)
DEPTH_CONTENT_SLEEP_SURGERY_V390 = apply_depth_content_sleep_surgery_v390(runtime_entry.data)
DEPTH_CONTENT_GENERAL_ENT_V391 = apply_depth_content_general_ent_v391(runtime_entry.data)
DEPTH_CONTENT_FACIAL_PLASTICS_V392 = apply_depth_content_facial_plastics_v392(runtime_entry.data)
DEPTH_CONTENT_THYROID_PARATHYROID_V393 = apply_depth_content_thyroid_parathyroid_v393(runtime_entry.data)
DEPTH_CONTENT_OTOLOGY_V394 = apply_depth_content_otology_v394(runtime_entry.data)
DEPTH_CONTENT_RHINOLOGY_V395 = apply_depth_content_rhinology_v395(runtime_entry.data)
DEPTH_CONTENT_HEAD_NECK_ONCOLOGY_V396 = apply_depth_content_head_neck_oncology_v396(runtime_entry.data)
DEPTH_CONTENT_PEDIATRIC_ENT_V397 = apply_depth_content_pediatric_ent_v397(runtime_entry.data)
DEPTH_CONTENT_LARYNGOLOGY_V398 = apply_depth_content_laryngology_v398(runtime_entry.data)
PREREQUISITES_GATING_FIX_V387 = install_prerequisites_gating_fix_v387(runtime_entry.data, runtime_entry.app_mod)
CONCEPT_DAILY_LINKING_V384 = install_concept_daily_linking_v384(runtime_entry.data, runtime_entry.app_mod)
OR_PREP_CONCEPT_LINK_GUARD_V385 = install_or_prep_concept_link_guard_v385(runtime_entry.app_mod)
runtime_entry.app_mod.OR_PREP_REGISTRY = runtime_entry.data.OR_PREP_REGISTRY
CONCEPT_OR_LINK_FIX_V388 = install_concept_or_link_fix_v388(runtime_entry.app_mod)
INTERPRETATION_LABS_CLEANUP_V250 = apply_interpretation_labs_cleanup_v250(runtime_entry.data, runtime_entry.app_mod)
app=runtime_entry.app
PRACTICE_BANK_NAVIGATION_V150 = install_practice_bank_navigation_v150(app, runtime_entry.app_mod)
if "pasha_review" not in app.blueprints:
    app.register_blueprint(pasha_review_blueprint)
