"""Production entrypoint with the Pasha review subsystem registered last.

Importing runtime_entry first preserves all existing curriculum/practice repairs before
Pasha maps its review bank to the final live question objects.
"""
import runtime_entry
from interpretation_labs_cleanup_v250 import apply_interpretation_labs_cleanup_v250
from pasha_routes import bp as pasha_review_blueprint
from practice_bank_navigation_v150 import install_practice_bank_navigation_v150
from deep_curriculum_otology_v284 import apply_otology_etd_rebuild_v284
from deep_curriculum_production_chain_v314 import apply_deep_curriculum_production_chain_v314
from deep_curriculum_rhinology_v363 import apply_rhinology_allergy_source_trace_v363
from deep_curriculum_snhl_v372 import apply_snhl_bedside_exam_v372
from deep_curriculum_dtc_rai_v373 import apply_dtc_rai_criteria_v373
from deep_curriculum_otology_v374 import apply_vestibular_schwannoma_criteria_v374
from deep_curriculum_rai_tsh_v375 import apply_rai_tsh_dtc_criteria_v375
from deep_curriculum_crssnp_v376 import apply_crssnp_management_v376
from deep_curriculum_peds_crs_v377 import apply_pediatric_crs_surgery_v377
from deep_curriculum_named_grading_v378 import apply_named_grading_criteria_v378
from deep_curriculum_named_grading_criteria_v379 import apply_named_grading_criteria_v379
from deep_curriculum_named_grading_criteria_v380 import apply_mtd_depth_v380
from or_tonsil_hemorrhage_rescue_v281 import apply_or_tonsil_hemorrhage_rescue_v281
from or_thyroid_hematoma_rescue_v282 import apply_or_thyroid_hematoma_rescue_v282
from or_tracheostomy_hemorrhage_rescue_v283 import apply_or_tracheostomy_hemorrhage_rescue_v283
from or_septal_hematoma_rescue_v284 import apply_or_septal_hematoma_rescue_v284
from or_esophageal_perforation_rescue_v285 import apply_or_esophageal_perforation_rescue_v285
from or_laryngectomy_fistula_rescue_v287 import apply_or_laryngectomy_fistula_rescue_v287
from or_airway_fire_rescue_v288 import apply_or_airway_fire_rescue_v288
from or_posterior_epistaxis_rescue_v289 import apply_or_posterior_epistaxis_rescue_v289
from or_tep_prosthesis_rescue_v290 import apply_or_tep_prosthesis_rescue_v290
from or_zenker_perforation_rescue_v291 import apply_or_zenker_perforation_rescue_v291
from or_airway_dilation_injury_rescue_v292 import apply_or_airway_dilation_injury_rescue_v292
from or_prep_indications_fix_v381 import apply_or_prep_indications_fix_v381
from or_prep_indications_fix_v382 import apply_or_prep_indications_fix_v382
from daily_curriculum_quality_v368 import install_daily_curriculum_quality_v368
import daily_curriculum_quality_v368
from daily_blind_case_labels_v402 import apply_daily_blind_case_labels_v402
from daily_curriculum_quality_v370 import install_daily_curriculum_quality_v370
from daily_curriculum_quality_v371 import install_daily_curriculum_quality_v371
from daily_curriculum_rhinology_selective_v382 import install_daily_curriculum_rhinology_selective_v382
from question_quality_repairs_v371 import install_question_quality_repairs_v371
from why_wrong_fix_general_ent_v1 import apply_why_wrong_fix_general_ent_v1
from why_wrong_fix_laryngology_v1 import apply_why_wrong_fix_laryngology_v1
from why_wrong_fix_head_neck_v1 import apply_why_wrong_fix_head_neck_v1
from why_wrong_fix_rhinology_v1 import apply_why_wrong_fix_rhinology_v1
from why_wrong_fix_pediatric_v1 import apply_why_wrong_fix_pediatric_v1
from why_wrong_fix_facial_plastics_v1 import apply_why_wrong_fix_facial_plastics_v1
from why_wrong_fix_otology_v1 import apply_why_wrong_fix_otology_v1
from why_wrong_fix_thyroid_v1 import apply_why_wrong_fix_thyroid_v1
from why_wrong_fix_sleep_v1 import apply_why_wrong_fix_sleep_v1
from why_wrong_fix_vignettes_v137_v1 import apply_why_wrong_fix_vignettes_v137_v1
from why_wrong_fix_vignettes_v138_v1 import apply_why_wrong_fix_vignettes_v138_v1
from why_wrong_fix_vignettes_v139_v1 import apply_why_wrong_fix_vignettes_v139_v1
from deep_curriculum_crswnp_biologics_named_v383 import apply_crswnp_biologics_named_v383
from or_prep_linked_topic_fix_v384 import apply_or_prep_linked_topic_fix_v384
from concept_daily_linking_v384 import install_concept_daily_linking_v384
from or_prep_concept_link_guard_v385 import install_or_prep_concept_link_guard_v385
from deep_curriculum_new_topics_v386 import apply_deep_curriculum_new_topics_v386
from prerequisites_gating_fix_v387 import install_prerequisites_gating_fix_v387
from concept_or_link_fix_v388 import install_concept_or_link_fix_v388
from thyroglossal_duct_cyst_depth_v389 import apply_thyroglossal_duct_cyst_depth_v389
from depth_content_sleep_surgery_v390 import apply_depth_content_sleep_surgery_v390
from depth_content_general_ent_v391 import apply_depth_content_general_ent_v391
from depth_content_facial_plastics_v392 import apply_depth_content_facial_plastics_v392
from depth_content_thyroid_parathyroid_v393 import apply_depth_content_thyroid_parathyroid_v393
from depth_content_otology_v394 import apply_depth_content_otology_v394
from depth_content_rhinology_v395 import apply_depth_content_rhinology_v395
from depth_content_head_neck_oncology_v396 import apply_depth_content_head_neck_oncology_v396
from depth_content_pediatric_ent_v397 import apply_depth_content_pediatric_ent_v397
from depth_content_laryngology_v398 import apply_depth_content_laryngology_v398
from nonfunctional_larynx_duplicate_merge_v399 import apply_nonfunctional_larynx_duplicate_merge_v399
from depth_content_facial_trauma_extra_v400 import apply_depth_content_facial_trauma_extra_v400
from depth_content_high_yield_batch_v401 import apply_depth_content_high_yield_batch_v401
from priority_final_v407 import apply_priority_final_v407
from priority_remainder_v408 import apply_priority_remainder_v408
from priority_pleomorphic_adenoma_v409 import apply_pleomorphic_adenoma_transformation_v409
from priority_first_bite_trauma_v410 import apply_first_bite_trauma_v410
from or_followups_v411 import apply_or_followups_v411
from or_complications_fix_v412 import apply_or_complications_fix_v412
from or_landmarks_exitcheck_fix_v413 import apply_or_landmarks_exitcheck_fix_v413
from deep_source_claim_backfill_v414 import apply_deep_source_claim_backfill_v414
from csf_rhinorrhea_oncall_v416 import apply_csf_rhinorrhea_oncall_v416
from interpretation_labs_depth_fix_v416 import apply_interpretation_labs_depth_fix_v416
from interpretation_labs_audiology_vestibular_rebuild_v417 import apply_interpretation_labs_audiology_vestibular_rebuild_v417
from interpretation_labs_audiology_ecog_vemp_v418 import apply_interpretation_labs_audiology_ecog_vemp_v418
from interpretation_labs_remaining_ten_v419 import apply_interpretation_labs_remaining_ten_v419
from or_prep_followup_depth_v420 import apply_or_prep_followup_depth_v420
from deep_curriculum_new_topic_gaps_v421 import apply_deep_curriculum_new_topic_gaps_v421
from allergy_anaphylaxis_deep_dive_v422 import apply_allergy_anaphylaxis_deep_dive_v422
from sialolithiasis_consolidation_v424 import apply_sialolithiasis_consolidation_v424
from sialendoscopy_lithotripsy_and_skull_base_syndromes_v425 import apply_sialendoscopy_lithotripsy_and_skull_base_syndromes_v425
from allergy_seasonal_oas_v426 import apply_allergy_seasonal_oas_v426
from facial_plastics_chemical_peels_v427 import apply_facial_plastics_chemical_peels_v427
from allergy_domain_consolidation_v428 import apply_allergy_domain_consolidation_v428
from oral_cavity_neck_dissection_depth_v429 import apply_oral_cavity_neck_dissection_depth_v429
from cleft_palate_tensor_veli_palatini_v430 import apply_cleft_palate_tensor_veli_palatini_v430
from clinical_challenge_gapfill_v431 import apply_clinical_challenge_gapfill_v431
from or_prep_attending_followup_gapfill_v432 import apply_or_prep_attending_followup_gapfill_v432
from oral_board_simulator_v433 import apply_oral_board_simulator_v433
from concept_check_why_wrong_gapfill_v434 import apply_concept_check_why_wrong_gapfill_v434
from otosclerosis_duplicate_merge_v435 import apply_otosclerosis_duplicate_merge_v435
from evidence_catalog_gapfill_v436 import apply_evidence_catalog_gapfill_v436
from anatomy_atlas_schematics_v437 import apply_anatomy_atlas_schematics_v437
from concept_check_gapfill_v438 import apply_concept_check_gapfill_v438
from prerequisite_relationship_repair_v439 import apply_prerequisite_relationship_repair_v439
from ajcc9_staging_currency_v440 import apply_ajcc9_staging_currency_v440
from missing_topics_gradingscales_v441 import apply_missing_topics_gradingscales_v441
from bucket6_data_hygiene_v442 import apply_bucket6_data_hygiene_v442
from clinical_challenge_gapfill_v443 import apply_clinical_challenge_gapfill_v443
from accounts_v444 import apply_accounts_v444
from clinical_safety_and_format_gaps_v446 import apply_clinical_safety_and_format_gaps_v446

OTOLOGY_ETD_REBUILD_V284 = apply_otology_etd_rebuild_v284(runtime_entry.data, runtime_entry.app_mod)
DEEP_CURRICULUM_PRODUCTION_CHAIN_V314 = apply_deep_curriculum_production_chain_v314(runtime_entry.data, runtime_entry.app_mod)
RHINOLOGY_ALLERGY_SOURCE_TRACE_V363 = apply_rhinology_allergy_source_trace_v363(runtime_entry.data, runtime_entry.app_mod)
SNHL_BEDSIDE_EXAM_V372 = apply_snhl_bedside_exam_v372(runtime_entry.data, runtime_entry.app_mod)
DTC_RAI_CRITERIA_V373 = apply_dtc_rai_criteria_v373(runtime_entry.data, runtime_entry.app_mod)
VESTIBULAR_SCHWANNOMA_CRITERIA_V374 = apply_vestibular_schwannoma_criteria_v374(runtime_entry.data, runtime_entry.app_mod)
RAI_TSH_DTC_CRITERIA_V375 = apply_rai_tsh_dtc_criteria_v375(runtime_entry.data, runtime_entry.app_mod)
CRSSNP_MANAGEMENT_V376 = apply_crssnp_management_v376(runtime_entry.data, runtime_entry.app_mod)
PEDIATRIC_CRS_SURGERY_V377 = apply_pediatric_crs_surgery_v377(runtime_entry.data, runtime_entry.app_mod)
NAMED_GRADING_CRITERIA_V378 = apply_named_grading_criteria_v378(runtime_entry.data, runtime_entry.app_mod)
NAMED_GRADING_CRITERIA_V379 = apply_named_grading_criteria_v379(runtime_entry.data, runtime_entry.app_mod)
MTD_DEPTH_V380 = apply_mtd_depth_v380(runtime_entry.data, runtime_entry.app_mod)
OR_TONSIL_HEMORRHAGE_RESCUE_V281 = apply_or_tonsil_hemorrhage_rescue_v281(runtime_entry.data.OR_PREP_REGISTRY)
OR_THYROID_HEMATOMA_RESCUE_V282 = apply_or_thyroid_hematoma_rescue_v282(runtime_entry.data.OR_PREP_REGISTRY)
OR_TRACHEOSTOMY_HEMORRHAGE_RESCUE_V283 = apply_or_tracheostomy_hemorrhage_rescue_v283(runtime_entry.data.OR_PREP_REGISTRY)
OR_SEPTAL_HEMATOMA_RESCUE_V284 = apply_or_septal_hematoma_rescue_v284(runtime_entry.data.OR_PREP_REGISTRY)
OR_ESOPHAGEAL_PERFORATION_RESCUE_V285 = apply_or_esophageal_perforation_rescue_v285(runtime_entry.data.OR_PREP_REGISTRY)
OR_LARYNGECTOMY_FISTULA_RESCUE_V287 = apply_or_laryngectomy_fistula_rescue_v287(runtime_entry.data.OR_PREP_REGISTRY)
OR_AIRWAY_FIRE_RESCUE_V288 = apply_or_airway_fire_rescue_v288(runtime_entry.data.OR_PREP_REGISTRY)
OR_POSTERIOR_EPISTAXIS_RESCUE_V289 = apply_or_posterior_epistaxis_rescue_v289(runtime_entry.data.OR_PREP_REGISTRY)
OR_TEP_PROSTHESIS_RESCUE_V290 = apply_or_tep_prosthesis_rescue_v290(runtime_entry.data.OR_PREP_REGISTRY)
OR_ZENKER_PERFORATION_RESCUE_V291 = apply_or_zenker_perforation_rescue_v291(runtime_entry.data.OR_PREP_REGISTRY)
OR_AIRWAY_DILATION_INJURY_RESCUE_V292 = apply_or_airway_dilation_injury_rescue_v292(runtime_entry.data.OR_PREP_REGISTRY)
OR_PREP_INDICATIONS_FIX_V381 = apply_or_prep_indications_fix_v381(runtime_entry.data.OR_PREP_REGISTRY)
OR_PREP_INDICATIONS_FIX_V382 = apply_or_prep_indications_fix_v382(runtime_entry.data.OR_PREP_REGISTRY)
DAILY_CURRICULUM_QUALITY_V368 = install_daily_curriculum_quality_v368(runtime_entry.data, runtime_entry.app_mod)
DAILY_CURRICULUM_QUALITY_V370 = install_daily_curriculum_quality_v370(runtime_entry.data, runtime_entry.app_mod)

# Reconciled Daily v37.1 runs before the newer global question-quality and domain
# distractor-reasoning layers, so it can improve prompt/answer alignment without
# overwriting their final challenge feedback.
DAILY_CURRICULUM_QUALITY_V371 = install_daily_curriculum_quality_v371(runtime_entry.data, runtime_entry.app_mod)
DAILY_CURRICULUM_RHINOLOGY_SELECTIVE_V382 = install_daily_curriculum_rhinology_selective_v382(runtime_entry.data, runtime_entry.app_mod)
QUESTION_QUALITY_REPAIRS_V371 = install_question_quality_repairs_v371(runtime_entry.data, runtime_entry.app_mod)
WHY_WRONG_FIX_GENERAL_ENT_V1 = apply_why_wrong_fix_general_ent_v1(runtime_entry.data)
WHY_WRONG_FIX_LARYNGOLOGY_V1 = apply_why_wrong_fix_laryngology_v1(runtime_entry.data)
WHY_WRONG_FIX_HEAD_NECK_V1 = apply_why_wrong_fix_head_neck_v1(runtime_entry.data)
WHY_WRONG_FIX_RHINOLOGY_V1 = apply_why_wrong_fix_rhinology_v1(runtime_entry.data)
WHY_WRONG_FIX_PEDIATRIC_V1 = apply_why_wrong_fix_pediatric_v1(runtime_entry.data)
WHY_WRONG_FIX_FACIAL_PLASTICS_V1 = apply_why_wrong_fix_facial_plastics_v1(runtime_entry.data)
WHY_WRONG_FIX_OTOLOGY_V1 = apply_why_wrong_fix_otology_v1(runtime_entry.data)
WHY_WRONG_FIX_THYROID_V1 = apply_why_wrong_fix_thyroid_v1(runtime_entry.data)
WHY_WRONG_FIX_SLEEP_V1 = apply_why_wrong_fix_sleep_v1(runtime_entry.data)
WHY_WRONG_FIX_VIGNETTES_V137_V1 = apply_why_wrong_fix_vignettes_v137_v1(runtime_entry.data)
WHY_WRONG_FIX_VIGNETTES_V138_V1 = apply_why_wrong_fix_vignettes_v138_v1(runtime_entry.data)
WHY_WRONG_FIX_VIGNETTES_V139_V1 = apply_why_wrong_fix_vignettes_v139_v1(runtime_entry.data)
CRSWNP_BIOLOGICS_NAMED_V383 = apply_crswnp_biologics_named_v383(runtime_entry.data, runtime_entry.app_mod)
OR_PREP_LINKED_TOPIC_FIX_V384 = apply_or_prep_linked_topic_fix_v384(runtime_entry.data.OR_PREP_REGISTRY)
DEEP_CURRICULUM_NEW_TOPICS_V386 = apply_deep_curriculum_new_topics_v386(runtime_entry.data, runtime_entry.app_mod)
THYROGLOSSAL_DUCT_CYST_DEPTH_V389 = apply_thyroglossal_duct_cyst_depth_v389(runtime_entry.data)
DEPTH_CONTENT_SLEEP_SURGERY_V390 = apply_depth_content_sleep_surgery_v390(runtime_entry.data)
DEPTH_CONTENT_GENERAL_ENT_V391 = apply_depth_content_general_ent_v391(runtime_entry.data)
DEPTH_CONTENT_FACIAL_PLASTICS_V392 = apply_depth_content_facial_plastics_v392(runtime_entry.data)
DEPTH_CONTENT_THYROID_PARATHYROID_V393 = apply_depth_content_thyroid_parathyroid_v393(runtime_entry.data)
DEPTH_CONTENT_OTOLOGY_V394 = apply_depth_content_otology_v394(runtime_entry.data)
DEPTH_CONTENT_RHINOLOGY_V395 = apply_depth_content_rhinology_v395(runtime_entry.data)
DEPTH_CONTENT_HEAD_NECK_ONCOLOGY_V396 = apply_depth_content_head_neck_oncology_v396(runtime_entry.data)
DEPTH_CONTENT_PEDIATRIC_ENT_V397 = apply_depth_content_pediatric_ent_v397(runtime_entry.data)
DEPTH_CONTENT_LARYNGOLOGY_V398 = apply_depth_content_laryngology_v398(runtime_entry.data)
PREREQUISITES_GATING_FIX_V387 = install_prerequisites_gating_fix_v387(runtime_entry.data, runtime_entry.app_mod)
CONCEPT_DAILY_LINKING_V384 = install_concept_daily_linking_v384(runtime_entry.data, runtime_entry.app_mod)
OR_PREP_CONCEPT_LINK_GUARD_V385 = install_or_prep_concept_link_guard_v385(runtime_entry.app_mod)
runtime_entry.app_mod.OR_PREP_REGISTRY = runtime_entry.data.OR_PREP_REGISTRY
CONCEPT_OR_LINK_FIX_V388 = install_concept_or_link_fix_v388(runtime_entry.app_mod)
NONFUNCTIONAL_LARYNX_DUPLICATE_MERGE_V399 = apply_nonfunctional_larynx_duplicate_merge_v399(runtime_entry.data)
DEPTH_CONTENT_FACIAL_TRAUMA_EXTRA_V400 = apply_depth_content_facial_trauma_extra_v400(runtime_entry.data)
DEPTH_CONTENT_HIGH_YIELD_BATCH_V401 = apply_depth_content_high_yield_batch_v401(runtime_entry.data)
PRIORITY_FINAL_V407 = apply_priority_final_v407(runtime_entry.data, runtime_entry.app_mod)
PRIORITY_REMAINDER_V408 = apply_priority_remainder_v408(runtime_entry.data, runtime_entry.app_mod)
PLEOMORPHIC_ADENOMA_TRANSFORMATION_V409 = apply_pleomorphic_adenoma_transformation_v409(runtime_entry.data, runtime_entry.app_mod)
FIRST_BITE_TRAUMA_V410 = apply_first_bite_trauma_v410(runtime_entry.data, runtime_entry.app_mod)
OR_FOLLOWUPS_V411 = apply_or_followups_v411(runtime_entry.data, runtime_entry.app_mod)
OR_COMPLICATIONS_FIX_V412 = apply_or_complications_fix_v412(runtime_entry.data, runtime_entry.app_mod)
OR_LANDMARKS_EXITCHECK_FIX_V413 = apply_or_landmarks_exitcheck_fix_v413(runtime_entry.data, runtime_entry.app_mod)
DEEP_SOURCE_CLAIM_BACKFILL_V414 = apply_deep_source_claim_backfill_v414(runtime_entry.data, runtime_entry.app_mod)
CSF_RHINORRHEA_ONCALL_V416 = apply_csf_rhinorrhea_oncall_v416(runtime_entry.data, runtime_entry.app_mod)
DAILY_BLIND_CASE_LABELS_V402 = apply_daily_blind_case_labels_v402(daily_curriculum_quality_v368, runtime_entry.data)
INTERPRETATION_LABS_CLEANUP_V250 = apply_interpretation_labs_cleanup_v250(runtime_entry.data, runtime_entry.app_mod)
INTERPRETATION_LABS_DEPTH_FIX_V416 = apply_interpretation_labs_depth_fix_v416(runtime_entry.data, runtime_entry.app_mod)
INTERPRETATION_LABS_AUDIOLOGY_VESTIBULAR_REBUILD_V417 = apply_interpretation_labs_audiology_vestibular_rebuild_v417(runtime_entry.data, runtime_entry.app_mod)
INTERPRETATION_LABS_AUDIOLOGY_ECOG_VEMP_V418 = apply_interpretation_labs_audiology_ecog_vemp_v418(runtime_entry.data, runtime_entry.app_mod)
INTERPRETATION_LABS_REMAINING_TEN_V419 = apply_interpretation_labs_remaining_ten_v419(runtime_entry.data, runtime_entry.app_mod)
OR_PREP_FOLLOWUP_DEPTH_V420 = apply_or_prep_followup_depth_v420(runtime_entry.data, runtime_entry.app_mod)
DEEP_CURRICULUM_NEW_TOPIC_GAPS_V421 = apply_deep_curriculum_new_topic_gaps_v421(runtime_entry.data, runtime_entry.app_mod)
ALLERGY_ANAPHYLAXIS_DEEP_DIVE_V422 = apply_allergy_anaphylaxis_deep_dive_v422(runtime_entry.data, runtime_entry.app_mod)
SIALOLITHIASIS_CONSOLIDATION_V424 = apply_sialolithiasis_consolidation_v424(runtime_entry.data, runtime_entry.app_mod)
SIALENDOSCOPY_LITHOTRIPSY_AND_SKULL_BASE_SYNDROMES_V425 = apply_sialendoscopy_lithotripsy_and_skull_base_syndromes_v425(runtime_entry.data, runtime_entry.app_mod)
ALLERGY_SEASONAL_OAS_V426 = apply_allergy_seasonal_oas_v426(runtime_entry.data, runtime_entry.app_mod)
FACIAL_PLASTICS_CHEMICAL_PEELS_V427 = apply_facial_plastics_chemical_peels_v427(runtime_entry.data, runtime_entry.app_mod)
ALLERGY_DOMAIN_CONSOLIDATION_V428 = apply_allergy_domain_consolidation_v428(runtime_entry.data, runtime_entry.app_mod)
ORAL_CAVITY_NECK_DISSECTION_DEPTH_V429 = apply_oral_cavity_neck_dissection_depth_v429(runtime_entry.data, runtime_entry.app_mod)
CLEFT_PALATE_TENSOR_VELI_PALATINI_V430 = apply_cleft_palate_tensor_veli_palatini_v430(runtime_entry.data, runtime_entry.app_mod)
CLINICAL_CHALLENGE_GAPFILL_V431 = apply_clinical_challenge_gapfill_v431(runtime_entry.data, runtime_entry.app_mod)
OR_PREP_ATTENDING_FOLLOWUP_GAPFILL_V432 = apply_or_prep_attending_followup_gapfill_v432(runtime_entry.data, runtime_entry.app_mod)
ORAL_BOARD_SIMULATOR_V433 = apply_oral_board_simulator_v433(runtime_entry.data, runtime_entry.app_mod)
CONCEPT_CHECK_WHY_WRONG_GAPFILL_V434 = apply_concept_check_why_wrong_gapfill_v434(runtime_entry.data, runtime_entry.app_mod)
OTOSCLEROSIS_DUPLICATE_MERGE_V435 = apply_otosclerosis_duplicate_merge_v435(runtime_entry.data, runtime_entry.app_mod)
EVIDENCE_CATALOG_GAPFILL_V436 = apply_evidence_catalog_gapfill_v436(runtime_entry.data, runtime_entry.app_mod)
ANATOMY_ATLAS_SCHEMATICS_V437 = apply_anatomy_atlas_schematics_v437(runtime_entry.data, runtime_entry.app_mod)
CONCEPT_CHECK_GAPFILL_V438 = apply_concept_check_gapfill_v438(runtime_entry.data, runtime_entry.app_mod)
PREREQUISITE_RELATIONSHIP_REPAIR_V439 = apply_prerequisite_relationship_repair_v439(runtime_entry.data, runtime_entry.app_mod)
AJCC9_STAGING_CURRENCY_V440 = apply_ajcc9_staging_currency_v440(runtime_entry.data, runtime_entry.app_mod)
MISSING_TOPICS_GRADINGSCALES_V441 = apply_missing_topics_gradingscales_v441(runtime_entry.data, runtime_entry.app_mod)
BUCKET6_DATA_HYGIENE_V442 = apply_bucket6_data_hygiene_v442(runtime_entry.data, runtime_entry.app_mod)
CLINICAL_CHALLENGE_GAPFILL_V443 = apply_clinical_challenge_gapfill_v443(runtime_entry.data, runtime_entry.app_mod)
ACCOUNTS_V444 = apply_accounts_v444(runtime_entry.app, runtime_entry.data, runtime_entry.app_mod)
CLINICAL_SAFETY_AND_FORMAT_GAPS_V446 = apply_clinical_safety_and_format_gaps_v446(runtime_entry.data, runtime_entry.app_mod)
# Resolve these late-registered topics against the final live curriculum.
# The parent-concept snapshot in data.py is built before the patch chain finishes.
runtime_entry.data.LAB_PARENT_TOPIC_V98.update({
    "audiologic-electrophysiology": "Audiologic Electrophysiology / ABR-OAE-ECoG",
    "allergy-testing": "Allergy Testing & Interpretation",
})
runtime_entry.data.OR_PREP_REGISTRY["parathyroidectomy"]["domain"] = "Thyroid / Parathyroid / Salivary"
app=runtime_entry.app
PRACTICE_BANK_NAVIGATION_V150 = install_practice_bank_navigation_v150(app, runtime_entry.app_mod)
if "pasha_review" not in app.blueprints:
    app.register_blueprint(pasha_review_blueprint)
