"""Production entrypoint with the Pasha review subsystem registered last.

Importing runtime_entry first preserves all existing curriculum/practice repairs before
Pasha maps its review bank to the final live question objects.
"""
import runtime_entry
from interpretation_labs_cleanup_v250 import apply_interpretation_labs_cleanup_v250
from pasha_routes import bp as pasha_review_blueprint
from practice_bank_navigation_v150 import install_practice_bank_navigation_v150
from deep_curriculum_otology_v284 import apply_otology_etd_rebuild_v284
from deep_curriculum_production_chain_v314 import apply_deep_curriculum_production_chain_v314
from deep_curriculum_rhinology_v363 import apply_rhinology_allergy_source_trace_v363
from deep_curriculum_snhl_v372 import apply_snhl_bedside_exam_v372
from deep_curriculum_dtc_rai_v373 import apply_dtc_rai_criteria_v373
from deep_curriculum_otology_v374 import apply_vestibular_schwannoma_criteria_v374
from deep_curriculum_rai_tsh_v375 import apply_rai_tsh_dtc_criteria_v375
from deep_curriculum_crssnp_v376 import apply_crssnp_management_v376
from or_tonsil_hemorrhage_rescue_v281 import apply_or_tonsil_hemorrhage_rescue_v281
from or_thyroid_hematoma_rescue_v282 import apply_or_thyroid_hematoma_rescue_v282
from or_tracheostomy_hemorrhage_rescue_v283 import apply_or_tracheostomy_hemorrhage_rescue_v283
from or_septal_hematoma_rescue_v284 import apply_or_septal_hematoma_rescue_v284
from or_esophageal_perforation_rescue_v285 import apply_or_esophageal_perforation_rescue_v285
from or_laryngectomy_fistula_rescue_v287 import apply_or_laryngectomy_fistula_rescue_v287
from or_airway_fire_rescue_v288 import apply_or_airway_fire_rescue_v288
from or_posterior_epistaxis_rescue_v289 import apply_or_posterior_epistaxis_rescue_v289
from or_tep_prosthesis_rescue_v290 import apply_or_tep_prosthesis_rescue_v290
from or_zenker_perforation_rescue_v291 import apply_or_zenker_perforation_rescue_v291
from or_airway_dilation_injury_rescue_v292 import apply_or_airway_dilation_injury_rescue_v292
from daily_curriculum_quality_v368 import install_daily_curriculum_quality_v368
from daily_curriculum_quality_v370 import install_daily_curriculum_quality_v370
from daily_curriculum_quality_v371 import install_daily_curriculum_quality_v371
from question_quality_repairs_v371 import install_question_quality_repairs_v371
from why_wrong_fix_general_ent_v1 import apply_why_wrong_fix_general_ent_v1
from why_wrong_fix_laryngology_v1 import apply_why_wrong_fix_laryngology_v1
from why_wrong_fix_head_neck_v1 import apply_why_wrong_fix_head_neck_v1
from why_wrong_fix_rhinology_v1 import apply_why_wrong_fix_rhinology_v1
from why_wrong_fix_pediatric_v1 import apply_why_wrong_fix_pediatric_v1
from why_wrong_fix_facial_plastics_v1 import apply_why_wrong_fix_facial_plastics_v1
from why_wrong_fix_otology_v1 import apply_why_wrong_fix_otology_v1
from why_wrong_fix_thyroid_v1 import apply_why_wrong_fix_thyroid_v1
from why_wrong_fix_sleep_v1 import apply_why_wrong_fix_sleep_v1

OTOLOGY_ETD_REBUILD_V284 = apply_otology_etd_rebuild_v284(runtime_entry.data, runtime_entry.app_mod)
DEEP_CURRICULUM_PRODUCTION_CHAIN_V314 = apply_deep_curriculum_production_chain_v314(runtime_entry.data, runtime_entry.app_mod)
RHINOLOGY_ALLERGY_SOURCE_TRACE_V363 = apply_rhinology_allergy_source_trace_v363(runtime_entry.data, runtime_entry.app_mod)
SNHL_BEDSIDE_EXAM_V372 = apply_snhl_bedside_exam_v372(runtime_entry.data, runtime_entry.app_mod)
DTC_RAI_CRITERIA_V373 = apply_dtc_rai_criteria_v373(runtime_entry.data, runtime_entry.app_mod)
VESTIBULAR_SCHWANNOMA_CRITERIA_V374 = apply_vestibular_schwannoma_criteria_v374(runtime_entry.data, runtime_entry.app_mod)
RAI_TSH_DTC_CRITERIA_V375 = apply_rai_tsh_dtc_criteria_v375(runtime_entry.data, runtime_entry.app_mod)
CRSSNP_MANAGEMENT_V376 = apply_crssnp_management_v376(runtime_entry.data, runtime_entry.app_mod)
OR_TONSIL_HEMORRHAGE_RESCUE_V281 = apply_or_tonsil_hemorrhage_rescue_v281(runtime_entry.data.OR_PREP_REGISTRY)
OR_THYROID_HEMATOMA_RESCUE_V282 = apply_or_thyroid_hematoma_rescue_v282(runtime_entry.data.OR_PREP_REGISTRY)
OR_TRACHEOSTOMY_HEMORRHAGE_RESCUE_V283 = apply_or_tracheostomy_hemorrhage_rescue_v283(runtime_entry.data.OR_PREP_REGISTRY)
OR_SEPTAL_HEMATOMA_RESCUE_V284 = apply_or_septal_hematoma_rescue_v284(runtime_entry.data.OR_PREP_REGISTRY)
OR_ESOPHAGEAL_PERFORATION_RESCUE_V285 = apply_or_esophageal_perforation_rescue_v285(runtime_entry.data.OR_PREP_REGISTRY)
OR_LARYNGECTOMY_FISTULA_RESCUE_V287 = apply_or_laryngectomy_fistula_rescue_v287(runtime_entry.data.OR_PREP_REGISTRY)
OR_POSTERIOR_EPISTAXIS_RESCUE_V289 = apply_or_posterior_epistaxis_rescue_v289(runtime_entry.data.OR_PREP_REGISTRY)
OR_TEP_PROSTHESIS_RESCUE_V290 = apply_or_tep_prosthesis_rescue_v290(runtime_entry.data.OR_PREP_REGISTRY)
OR_ZENKER_PERFORATION_RESCUE_V291 = apply_or_zenker_perforation_rescue_v291(runtime_entry.data.OR_PREP_REGISTRY)
OR_AIRWAY_DILATION_INJURY_RESCUE_V292 = apply_or_airway_dilation_injury_rescue_v292(runtime_entry.data.OR_PREP_REGISTRY)
DAILY_CURRICULUM_QUALITY_V368 = install_daily_curriculum_quality_v368(runtime_entry.data, runtime_entry.app_mod)
DAILY_CURRICULUM_QUALITY_V370 = install_daily_curriculum_quality_v370(runtime_entry.data, runtime_entry.app_mod)

# Reconciled Daily v37.1 runs before the newer global question-quality and domain
# distractor-reasoning layers, so it can improve prompt/answer alignment without
# overwriting their final challenge feedback.
DAILY_CURRICULUM_QUALITY_V371 = install_daily_curriculum_quality_v371(runtime_entry.data, runtime_entry.app_mod)
QUESTION_QUALITY_REPAIRS_V371 = install_question_quality_repairs_v371(runtime_entry.data, runtime_entry.app_mod)
WHY_WRONG_FIX_GENERAL_ENT_V1 = apply_why_wrong_fix_general_ent_v1(runtime_entry.data)
WHY_WRONG_FIX_LARYNGOLOGY_V1 = apply_why_wrong_fix_laryngology_v1(runtime_entry.data)
WHY_WRONG_FIX_HEAD_NECK_V1 = apply_why_wrong_fix_head_neck_v1(runtime_entry.data)
WHY_WRONG_FIX_RHINOLOGY_V1 = apply_why_wrong_fix_rhinology_v1(runtime_entry.data)
WHY_WRONG_FIX_PEDIATRIC_V1 = apply_why_wrong_fix_pediatric_v1(runtime_entry.data)
WHY_WRONG_FIX_FACIAL_PLASTICS_V1 = apply_why_wrong_fix_facial_plastics_v1(runtime_entry.data)
WHY_WRONG_FIX_OTOLOGY_V1 = apply_why_wrong_fix_otology_v1(runtime_entry.data)
WHY_WRONG_FIX_THYROID_V1 = apply_why_wrong_fix_thyroid_v1(runtime_entry.data)
WHY_WRONG_FIX_SLEEP_V1 = apply_why_wrong_fix_sleep_v1(runtime_entry.data)
runtime_entry.app_mod.OR_PREP_REGISTRY = runtime_entry.data.OR_PREP_REGISTRY
INTERPRETATION_LABS_CLEANUP_V250 = apply_interpretation_labs_cleanup_v250(runtime_entry.data, runtime_entry.app_mod)
app=runtime_entry.app
PRACTICE_BANK_NAVIGATION_V150 = install_practice_bank_navigation_v150(app, runtime_entry.app_mod)
if "pasha_review" not in app.blueprints:
    app.register_blueprint(pasha_review_blueprint)
