"""v13.9 — canonical coverage closure for Pediatric Otolaryngology and General
ENT / Emergencies. Targets every remaining canonical topic reported missing by
the live v13.7 audit.
"""


def Q(qid, domain, topic, stem, choices, answer, explanation, pearl, curveball):
    return {
        "id": qid, "domain": domain, "topic": topic, "stem": stem,
        "choices": choices, "answer": answer, "explanation": explanation,
        "why_wrong": ["Compare this option with the triage, anatomy, or management principle in the explanation." for _ in choices],
        "board_pearl": pearl, "curveball": curveball,
        "tier": "Curated board/call/OR", "mode": "Vignette",
    }

PED = "Pediatric Otolaryngology"
GEN = "General ENT / Emergencies"

VIGNETTES_V139 = [
    # Pediatric Otolaryngology
    Q("v139_ped_01", PED, "Ankyloglossia / Maxillary Frenulum",
      "A breastfeeding newborn has a visible lingual frenulum but normal latch, maternal comfort and weight gain. What is the best management?",
      ["Observation; appearance alone is not an indication for frenotomy", "Frenotomy for every visible frenulum", "Tracheostomy", "Adenoidectomy"], 0,
      "Ankyloglossia treatment should be driven by functional feeding impairment after skilled lactation assessment, not by anatomy alone.",
      "A frenulum is common anatomy; the diagnosis is functional restriction.",
      "What findings would make frenotomy more reasonable after conservative feeding support?"),

    Q("v139_ped_02", PED, "Choanal Atresia",
      "A neonate becomes cyanotic at rest but improves when crying. A catheter cannot pass through either nasal cavity. What is the immediate priority?",
      ["Establish a secure oral airway and confirm bilateral choanal atresia before definitive repair", "Wait for spontaneous resolution", "Tonsillectomy", "Nasal steroid alone"], 0,
      "Neonates are preferential nasal breathers; bilateral choanal atresia can cause life-threatening obstruction relieved by crying.",
      "In a cyanotic newborn who improves with crying, think nasal obstruction before assuming lung disease.",
      "What syndromic association should be evaluated?"),

    Q("v139_ped_03", PED, "Cleft / Craniofacial Otologic-Airway Care",
      "An infant with cleft palate has persistent bilateral middle-ear effusions and conductive hearing loss. What principle explains the high risk?",
      ["Abnormal tensor veli palatini/Eustachian tube mechanics impair middle-ear ventilation", "The cochlea is always malformed", "Cleft palate prevents ossicular development", "Otitis media is unrelated to clefting"], 0,
      "Cleft palate commonly causes chronic ET dysfunction and OME; longitudinal audiologic and otologic surveillance is essential.",
      "Craniofacial care is longitudinal—airway, hearing, speech and feeding problems evolve at different ages.",
      "How does syndromic micrognathia alter airway planning?"),

    Q("v139_ped_04", PED, "Cleft Lip / Palate — ENT Surgical Fundamentals",
      "During cleft-palate repair, which functional goal is central to speech outcome?",
      ["Reconstruct a mobile muscular sling capable of velopharyngeal closure", "Make the palate as short as possible", "Remove the uvula", "Avoid repairing levator muscle orientation"], 0,
      "Palatoplasty aims to restore separation and functional levator mechanics for speech while minimizing fistula and growth disturbance.",
      "Cleft surgery is not merely closing a hole; muscle reconstruction determines function.",
      "What postoperative finding suggests a palatal fistula affecting speech or feeding?"),

    Q("v139_ped_05", PED, "Congenital Hearing Loss Genetics",
      "An infant has confirmed bilateral congenital sensorineural hearing loss with no obvious syndrome. What is an important next step?",
      ["Offer etiologic evaluation including genetic testing and congenital CMV considerations while beginning early hearing habilitation", "Delay all evaluation until school age", "Assume noise exposure", "Treat with tubes only"], 0,
      "Genetic testing has high yield in congenital SNHL and can inform prognosis, associated conditions and family counseling; habilitation should not wait for the etiologic workup to finish.",
      "Etiologic diagnosis and access to sound should proceed in parallel.",
      "Which genetic diagnosis may change counseling about progression or cochlear-implant outcomes?"),

    Q("v139_ped_06", PED, "Juvenile Recurrent Parotitis",
      "A 7-year-old has recurrent painful unilateral parotid swelling several times per year, normal growth and no abscess. What is the best initial approach?",
      ["Hydration, massage, analgesia and evaluation for recurrent parotitis; sialendoscopy may be considered for frequent refractory episodes", "Parotidectomy after the first episode", "RAI", "Neck dissection"], 0,
      "Juvenile recurrent parotitis is often self-limited by puberty; conservative care is first-line and sialendoscopy can help selected recurrent cases.",
      "Do not over-treat a usually self-limited pediatric salivary disorder with radical gland surgery.",
      "What features should prompt evaluation for immune deficiency or Sjögren-like disease?"),

    Q("v139_ped_07", PED, "Laryngotracheal Reconstruction",
      "A child with mature high-grade subglottic stenosis is tracheostomy-dependent. What is the purpose of cartilage-graft laryngotracheal reconstruction?",
      ["Expand the stenotic laryngotracheal framework to create a stable airway suitable for decannulation", "Paralyze the vocal folds", "Treat otitis media", "Reduce tongue base"], 0,
      "LTR uses anterior and/or posterior cartilage grafts to enlarge the airway; staging and graft choice depend on stenosis grade, glottic function and comorbidities.",
      "Airway reconstruction succeeds when the entire airway and swallowing/neurologic context are optimized—not by stenosis grade alone.",
      "What factors favor single-stage versus double-stage reconstruction?"),

    Q("v139_ped_08", PED, "Lymphatic Malformation",
      "A child has a soft transilluminating multiloculated neck mass that rapidly enlarges during a URI. What treatment framework is appropriate?",
      ["Define macrocystic/microcystic anatomy and airway risk; use observation, sclerotherapy and/or surgery based on symptoms and compartment", "Incise and drain as an abscess", "Mandatory radical neck dissection", "Antibiotics indefinitely"], 0,
      "Lymphatic malformations can acutely swell with infection or hemorrhage; treatment is morphology- and symptom-driven, with sclerotherapy often effective for macrocystic disease.",
      "Airway risk, not cosmetic size alone, determines urgency.",
      "What should be done if floor-of-mouth involvement causes progressive tongue elevation and stridor?"),

    Q("v139_ped_09", PED, "Microtia / Aural Atresia",
      "A child has unilateral microtia and congenital aural atresia. What hearing evaluation is most important early in life?",
      ["Confirm cochlear function and hearing in both ears, then provide amplification/habilitation when indicated", "Wait until auricular reconstruction age", "Assume the opposite ear is normal", "No audiology is needed"], 0,
      "Microtia/atresia can coexist with conductive loss and other anomalies; early hearing assessment prevents language and classroom consequences.",
      "Ear appearance and hearing rehabilitation have different timelines.",
      "How does bilateral atresia change urgency for bone-conduction amplification?"),

    Q("v139_ped_10", PED, "Microtia Reconstruction",
      "Why is autologous costal-cartilage microtia reconstruction often delayed until later childhood?",
      ["Adequate rib cartilage volume is needed to carve a durable framework", "The external ear cannot be reconstructed before adulthood", "Hearing must first become normal", "The facial nerve must mature"], 0,
      "Autologous reconstruction timing balances donor cartilage size, chest anatomy and psychosocial considerations; porous polyethylene has a different timing/risk profile.",
      "Coordinate atresia and auricular reconstruction so one operation does not compromise tissue needed for the other.",
      "Why should atresia surgery timing be coordinated with the reconstructive surgeon?"),

    Q("v139_ped_11", PED, "Nonobstructive Pediatric Sleep Disorders",
      "A child snores occasionally but the main complaint is bedtime resistance, prolonged sleep latency and inconsistent schedules without witnessed obstruction. What is the best next step?",
      ["Evaluate behavioral insomnia/circadian and other nonobstructive sleep disorders before pursuing airway surgery", "Adenotonsillectomy automatically", "HNS", "Tracheostomy"], 0,
      "Not every pediatric sleep complaint is OSA; history should distinguish obstructive breathing, insufficient sleep, insomnia, parasomnias and restless sleep.",
      "Sleep surgery starts with the correct sleep diagnosis.",
      "What symptoms would instead increase suspicion for pediatric OSA?"),

    Q("v139_ped_12", PED, "Pediatric Aspiration",
      "An infant coughs and desaturates with feeds and has recurrent pneumonias. What is the best next evaluation?",
      ["Instrumental swallow assessment such as MBS or FEES tailored to age and question, plus airway evaluation when indicated", "Assume reflux alone", "Tonsillectomy", "No feeding modification"], 0,
      "Pediatric aspiration may result from dysphagia, laryngeal cleft, neurologic disease or airway anomalies; determine timing and mechanism before treatment.",
      "Recurrent pneumonia plus feeding symptoms is an aspiration history until proven otherwise.",
      "What endoscopic finding would suggest a type I laryngeal cleft?"),

    Q("v139_ped_13", PED, "Pediatric Head & Neck Tumors",
      "A child has a rapidly enlarging painless neck mass that is firm and fixed. What is the best principle?",
      ["Treat persistent suspicious pediatric neck masses as potentially neoplastic and obtain targeted imaging/tissue diagnosis rather than repeated empiric antibiotics", "Assume all pediatric masses are reactive", "Perform blind excision without imaging", "Observe for a year"], 0,
      "Although most pediatric masses are benign, firmness, fixation, rapid growth, systemic symptoms or persistence require malignancy evaluation.",
      "Age changes the differential but does not eliminate cancer.",
      "Which tumor categories are especially important by age—lymphoma, rhabdomyosarcoma, thyroid or salivary?"),

    Q("v139_ped_14", PED, "Pediatric Reflux / Eosinophilic Esophagitis",
      "A child has solid-food dysphagia and recurrent food impactions with atopy. What diagnosis should be prioritized over empiric reflux treatment alone?",
      ["Eosinophilic esophagitis requiring GI evaluation and biopsy", "BPPV", "Croup", "Otitis externa"], 0,
      "EoE commonly presents with dysphagia/impaction in atopic children and requires endoscopic biopsy; symptoms should not automatically be attributed to reflux.",
      "Food impaction is an alarm symptom, not a reason for indefinite empiric acid suppression without evaluation.",
      "What dietary or medical therapies may follow diagnosis?"),

    Q("v139_ped_15", PED, "Pediatric Speech Disorders",
      "A preschool child has hypernasal speech but normal hearing. What should ENT evaluation focus on?",
      ["Differentiate articulation/language disorder from resonance dysfunction and assess velopharyngeal structure/function", "Assume hearing loss", "Perform tonsillectomy solely for hypernasality", "Ignore speech-language assessment"], 0,
      "Pediatric speech problems can be linguistic, articulatory, motor or resonance-related; collaboration with speech-language pathology is essential.",
      "ENT should localize the speech problem before operating on anatomy.",
      "How can nasoendoscopy help evaluate velopharyngeal closure?"),

    Q("v139_ped_16", PED, "Pediatric Vestibular Disorders",
      "A child has recurrent episodic vertigo with headache, photophobia and normal hearing between attacks. What diagnosis is important to consider?",
      ["Vestibular migraine of childhood", "Otosclerosis", "Cholesteatoma by default", "Acute mastoiditis"], 0,
      "Children can have migraine-related episodic vestibular syndromes; history, development and age-appropriate vestibular testing guide diagnosis.",
      "Pediatric dizziness is not automatically behavioral; migraine is common and may occur without adult-style headache every time.",
      "What hearing change would instead increase concern for Ménière-like inner-ear disease?"),

    Q("v139_ped_17", PED, "Recurrent Tonsillitis Decision-Making",
      "A child has 3 documented streptococcal tonsillitis episodes in the past year and no modifying factors. What is the best recommendation?",
      ["Watchful waiting because episode frequency does not meet standard recurrent-infection thresholds", "Immediate tonsillectomy is mandatory", "Long-term prophylactic IV antibiotics", "No documentation is needed"], 0,
      "Tonsillectomy for recurrent infection is based on documented episode frequency/severity and modifying factors; below thresholds, watchful waiting is recommended.",
      "Count documented qualifying episodes, not vague lifetime sore throats.",
      "Which modifying factors can justify surgery despite not meeting classic frequency thresholds?"),

    Q("v139_ped_18", PED, "Supraglottoplasty",
      "An infant with laryngomalacia has failure to thrive, apnea and severe retractions despite conservative measures. What treatment is appropriate?",
      ["Supraglottoplasty after confirming the airway diagnosis and assessing synchronous lesions/comorbidities", "Observe regardless of severity", "Adenoidectomy", "Cochlear implantation"], 0,
      "Most laryngomalacia is observed, but severe obstruction, feeding failure or growth compromise are indications for surgery.",
      "Severe laryngomalacia is a breathing/feeding disease, not simply noisy breathing.",
      "What supraglottic structures are typically divided or reduced during supraglottoplasty?"),

    Q("v139_ped_19", PED, "Thyroglossal Duct Cyst",
      "A child has a midline neck mass that elevates with tongue protrusion and swallowing. What is the definitive operation after infection is controlled?",
      ["Sistrunk procedure including the central hyoid segment and tract toward the tongue base", "Simple cyst excision only", "Total thyroidectomy", "Neck dissection"], 0,
      "Removing only the cyst has a high recurrence rate; the Sistrunk removes the central hyoid and tract because of embryologic passage.",
      "Confirm the presence of normal thyroid tissue before excision when imaging raises uncertainty.",
      "How does acute infection change timing of definitive surgery?"),

    Q("v139_ped_20", PED, "Tracheomalacia / Bronchomalacia",
      "An infant has expiratory wheeze and recurrent cyanotic spells; bronchoscopy shows >50% dynamic anterior collapse of the trachea during expiration. What is the management principle?",
      ["Treat severity and underlying compression; many mild cases improve with growth, while severe disease may require positive pressure or surgical stabilization", "Treat with tonsillectomy", "Assume asthma only", "Rigid stent every infant"], 0,
      "Tracheobronchomalacia is dynamic airway collapse; management ranges from observation to ventilatory support, aortopexy/tracheopexy or treatment of external compression.",
      "Dynamic airway disease requires dynamic assessment—static CT may underestimate collapse.",
      "What vascular anatomy can externally compress the trachea and mimic or worsen malacia?"),

    Q("v139_ped_21", PED, "Tympanostomy Tube Indications",
      "A 3-year-old has bilateral OME for 4 months with documented hearing difficulty. What intervention is appropriate?",
      ["Offer bilateral tympanostomy tubes after counseling", "No treatment because effusions never affect hearing", "Mastoidectomy", "Cochlear implantation"], 0,
      "Persistent bilateral OME with hearing difficulty is a standard indication to offer tubes; recurrent AOM without effusion at assessment is different.",
      "Tube decisions depend on duration, hearing, symptoms, developmental risk and whether effusion is actually present.",
      "How does an at-risk child with speech/language delay change threshold for intervention?"),

    Q("v139_ped_22", PED, "Velopharyngeal Insufficiency",
      "A child after cleft-palate repair has persistent hypernasality and nasal air emission. What is the best next step before choosing surgery?",
      ["Speech evaluation plus instrumental assessment of velopharyngeal closure pattern with nasoendoscopy and/or multiview fluoroscopy", "Choose a pharyngeal flap without imaging function", "Adenoidectomy automatically", "Ignore articulation testing"], 0,
      "VPI surgery should be matched to closure pattern, gap size, lateral-wall motion, airway/OSA risk and speech findings.",
      "A pharyngeal flap, sphincter pharyngoplasty and palate revision solve different mechanics.",
      "How does pre-existing OSA influence procedure choice?"),

    # General ENT / Emergencies
    Q("v139_gen_01", GEN, "Airway Foreign Body",
      "A toddler suddenly coughs while eating peanuts and now has unilateral wheeze with asymmetric hyperinflation. What is the best next step when suspicion remains high?",
      ["Urgent operative bronchoscopy with a team prepared for foreign-body removal", "Discharge because chest x-ray can be normal", "Oral antibiotics only", "Tonsillectomy"], 0,
      "A normal radiograph does not exclude an aspirated foreign body; a compelling history plus focal findings warrants bronchoscopy.",
      "Sudden cough/choke followed by focal airway findings is foreign body until proven otherwise.",
      "How does a completely obstructing proximal object change airway strategy?"),

    Q("v139_gen_02", GEN, "Antimicrobial Stewardship in Otolaryngology",
      "A patient has uncomplicated viral URI symptoms for 4 days with clear rhinorrhea and no focal bacterial findings. What is the best antimicrobial decision?",
      ["Do not prescribe antibiotics; provide symptomatic care and return precautions", "Broad-spectrum antibiotics", "IV vancomycin", "Antifungal therapy"], 0,
      "Stewardship means treating bacterial disease when evidence supports it, choosing the narrowest effective agent and appropriate duration.",
      "Antibiotics are not benign reassurance; unnecessary use creates adverse events and resistance.",
      "What sinusitis time course would support bacterial rather than viral disease?"),

    Q("v139_gen_03", GEN, "Chyle Leak",
      "On postoperative day 1 after left neck dissection, the drain becomes milky after enteral feeding and output rises to 700 mL/day. What is the best initial framework?",
      ["Confirm chyle, quantify output, institute dietary/medical management and escalate early for high-output or persistent leaks", "Remove the drain immediately", "Ignore electrolyte losses", "Treat as saliva without testing"], 0,
      "Chyle leak can cause volume, electrolyte, protein and immune losses; low-output leaks may respond to pressure/diet/octreotide while high-output leaks often need earlier procedural control.",
      "A left low-neck dissection plus milky high-output drainage is thoracic-duct injury until proven otherwise.",
      "What operative options exist if conservative management fails?"),

    Q("v139_gen_04", GEN, "Common ENT Consult Triage / Disposition",
      "Which consult should be seen first overnight?",
      ["A postoperative neck patient with rapidly expanding swelling, stridor and respiratory distress", "Stable cerumen impaction", "Chronic tinnitus unchanged for years", "Routine outpatient nasal obstruction"], 0,
      "ENT triage prioritizes airway, active hemorrhage, vision, neurologic compromise, deep-space infection and time-sensitive foreign bodies over stable chronic complaints.",
      "The first question on call is often not 'what is the diagnosis?' but 'what can deteriorate in minutes?'.",
      "How would a stable post-tonsillectomy child with a reported sentinel bleed be prioritized?"),

    Q("v139_gen_05", GEN, "Cranial Nerve Examination / Skull Base Localization",
      "A patient has hoarseness, ipsilateral palate weakness, shoulder weakness and tongue deviation after skull-base surgery. Where does this pattern localize?",
      ["Multiple lower cranial nerves IX-XII near the jugular foramen/hypoglossal region", "Isolated facial nerve", "Cochlea", "Optic chiasm"], 0,
      "A structured cranial-nerve exam can localize lesions before imaging; combinations matter more than memorizing isolated deficits.",
      "Map function to foramina: jugular foramen IX-XI; hypoglossal canal XII.",
      "What sympathetic finding would suggest a more extensive parapharyngeal/skull-base lesion?"),

    Q("v139_gen_06", GEN, "Deep Neck Abscess Drainage",
      "A patient with a large rim-enhancing parapharyngeal abscess has trismus, sepsis and worsening airway symptoms despite IV antibiotics. What is the next step?",
      ["Secure the airway as needed and perform timely surgical drainage with cultures", "Continue antibiotics alone indefinitely", "Blind needle aspiration through the carotid space", "Discharge"], 0,
      "Airway threat, sepsis, large organized collection and failure of medical therapy favor operative drainage; approach is chosen from compartment anatomy.",
      "Deep-neck drainage is an anatomy operation around carotid sheath, cranial nerves and mediastinal pathways.",
      "What imaging finding suggests descending necrotizing mediastinitis?"),

    Q("v139_gen_07", GEN, "ENT Fluids / Electrolytes / Nutrition",
      "A postoperative head-and-neck cancer patient has prolonged poor intake, low phosphate, low potassium and edema shortly after aggressive feeding is restarted. What syndrome is concerning?",
      ["Refeeding syndrome", "Ménière disease", "BPPV", "Bell palsy"], 0,
      "Malnourished patients are at risk for insulin-driven electrolyte shifts after feeding; phosphate, potassium, magnesium and thiamine require proactive monitoring/repletion.",
      "Nutrition is perioperative physiology, not an afterthought in major head-and-neck surgery.",
      "What feeding strategy reduces refeeding risk in a severely malnourished patient?"),

    Q("v139_gen_08", GEN, "ENT Imaging Fundamentals",
      "A patient with suspected deep-neck abscess and possible vascular complication needs imaging. Which study is generally most useful initially?",
      ["Contrast-enhanced CT neck", "Noncontrast skull x-ray", "DEXA scan", "Routine PET without CT"], 0,
      "Contrast CT rapidly maps deep-space infection, abscess, airway displacement and vascular complications; MRI adds soft-tissue/skull-base detail in selected cases.",
      "Order imaging to answer a management question, and understand what contrast adds.",
      "When is MRI preferred for skull-base osteomyelitis or perineural spread?"),

    Q("v139_gen_09", GEN, "ENT Perioperative Anesthesia / Difficult Airway Planning",
      "A patient with a bulky supraglottic tumor has stridor while supine but is stable sitting upright. What is the safest planning principle?",
      ["Create a multidisciplinary awake/controlled-airway strategy that preserves spontaneous ventilation until the airway is secured", "Induce paralysis before the airway plan is agreed", "Send the patient unmonitored to CT first", "Assume direct laryngoscopy will be easy"], 0,
      "When induction may convert partial obstruction into complete obstruction, airway planning must account for position, spontaneous ventilation and surgical-airway backup.",
      "The dangerous airway is often the one that is still barely working before induction.",
      "What anatomy would make awake tracheostomy preferable to awake intubation?"),

    Q("v139_gen_10", GEN, "Esophageal Foreign Body",
      "An adult with steak impaction cannot swallow secretions but is breathing comfortably. What is the best next step?",
      ["Urgent endoscopic removal because complete esophageal obstruction risks aspiration and injury", "Wait several days", "Induce vomiting", "Give solid food to push it down"], 0,
      "Inability to handle secretions indicates complete obstruction and requires urgent endoscopy; sharp objects and batteries are even more time-sensitive.",
      "Airway is first, but a stable airway does not make complete esophageal obstruction elective.",
      "After recurrent food impaction, what underlying disease should be investigated?"),

    Q("v139_gen_11", GEN, "Evidence Interpretation / Outcomes Research",
      "A retrospective study finds a treatment associated with better survival, but treated patients were younger and healthier. What major problem limits causal inference?",
      ["Confounding by indication/selection bias", "Randomization", "Blinding success", "Perfect external validity"], 0,
      "Observational comparisons can be distorted by baseline differences; multivariable adjustment, propensity methods and sensitivity analysis reduce but do not eliminate unmeasured confounding.",
      "A small p value does not repair a biased study design.",
      "What does a confidence interval add beyond the p value?"),

    Q("v139_gen_12", GEN, "Geriatric Otolaryngology / Frailty",
      "An 84-year-old with technically resectable cancer has severe frailty, falls, cognitive impairment and dependence in ADLs. What should guide treatment planning?",
      ["Incorporate frailty, cognition, function, goals and competing mortality—not chronologic age alone", "Operate because age never matters", "Deny treatment based only on age", "Ignore caregiver support"], 0,
      "Frailty predicts surgical toxicity and recovery independently of age; geriatric assessment can identify modifiable vulnerabilities and align treatment with goals.",
      "Age is a number; physiologic reserve and goals are the clinical variables.",
      "Which prehabilitation strategies may reduce perioperative risk?"),

    Q("v139_gen_13", GEN, "Grafts / Implants / Biomaterials in ENT",
      "A reconstructive implant becomes exposed in a previously irradiated field with surrounding infection. What principle is most important?",
      ["Control infection, assess vascularized soft-tissue coverage and remove compromised foreign material when necessary", "Leave infected exposed hardware indefinitely", "Steroids alone", "No role for vascularized tissue"], 0,
      "Biomaterials depend on tissue vascularity and contamination status; irradiated fields have impaired healing and may need robust vascularized coverage.",
      "Implants fail at the interface between material, bacteria and soft-tissue biology.",
      "When is autologous tissue preferable to alloplastic material?"),

    Q("v139_gen_14", GEN, "Hemostasis / Coagulopathy / Antithrombotic Management in ENT",
      "A patient on apixaban presents with life-threatening postoperative neck hemorrhage and airway compression. What is the priority?",
      ["Airway and surgical hemorrhage control immediately, while coordinating appropriate anticoagulant reversal/resuscitation", "Wait for the drug to wear off", "Reverse anticoagulation before addressing the airway", "Discharge"], 0,
      "In life-threatening ENT bleeding, airway and source control occur in parallel with resuscitation and reversal; elective antithrombotic decisions require balancing bleeding and thrombosis risk.",
      "Do not let medication management delay control of a compressing neck hematoma.",
      "How does management differ for minor epistaxis in a high-stroke-risk patient on anticoagulation?"),

    Q("v139_gen_15", GEN, "Immunocompromised Host in Otolaryngology",
      "A neutropenic patient has facial pain, black nasal mucosa and ophthalmoplegia. What is the correct priority?",
      ["Treat as possible acute invasive fungal rhinosinusitis with urgent tissue diagnosis, debridement and systemic antifungal therapy", "Routine outpatient sinusitis care", "Steroids alone", "Wait for neutrophil recovery before evaluation"], 0,
      "Immunocompromise changes both differential and tempo; invasive fungal disease can progress over hours and demands immediate multidisciplinary care.",
      "In the immunocompromised host, subtle mucosal necrosis or cranial neuropathy is a high-risk sign.",
      "What other ENT infections behave atypically in profound immunosuppression?"),

    Q("v139_gen_16", GEN, "Laser / Energy Safety in Otolaryngology",
      "During CO2 laser microlaryngoscopy, which practice most reduces airway-fire risk?",
      ["Use a laser-safe airway strategy, minimize oxidizer concentration when feasible and protect wet pledgets/tissues", "Use 100% oxygen and flammable drapes", "Ignore laser eye protection", "Activate laser before team timeout"], 0,
      "Airway fire requires fuel, oxidizer and ignition; laser cases should deliberately reduce all three and include a shared emergency plan.",
      "Energy safety is an OR system issue, not just a device setting.",
      "What are the immediate steps if the endotracheal tube ignites?"),

    Q("v139_gen_17", GEN, "Oral Manifestations of Systemic Disease",
      "A patient has recurrent painful oral ulcers, genital ulcers and uveitis. What systemic diagnosis should be considered?",
      ["Behçet disease", "BPPV", "Otosclerosis", "Ménière disease"], 0,
      "Oral findings can be the first clue to autoimmune, hematologic, infectious, nutritional or drug-related systemic disease.",
      "Aphthae are common; unusual severity plus extraoral features changes the differential.",
      "What oral findings can suggest hematologic malignancy or severe neutropenia?"),

    Q("v139_gen_18", GEN, "Pain Management in the Head & Neck Patient",
      "A postoperative patient has severe pain despite escalating opioids and is becoming somnolent. What is the best strategy?",
      ["Use multimodal analgesia, reassess for a surgical complication and reduce avoidable opioid toxicity", "Continue escalating opioids without examination", "Ignore renal/hepatic function", "Assume all pain is expected"], 0,
      "Pain can signal hematoma, infection, ischemia or compartment problems; multimodal therapy improves analgesia while limiting opioid adverse effects.",
      "Treat pain and investigate unexpected pain at the same time.",
      "Which nonopioid agents require caution with bleeding, renal disease or liver disease?"),

    Q("v139_gen_19", GEN, "Systemic / Granulomatous Disease Manifestations in ENT",
      "A patient has chronic crusting rhinitis, septal perforation, subglottic stenosis and renal dysfunction. What systemic disease is most likely?",
      ["Granulomatosis with polyangiitis", "Isolated allergic rhinitis", "BPPV", "Otosclerosis"], 0,
      "GPA can affect sinonasal tract, ears, subglottis, lungs and kidneys; ENT manifestations may precede systemic diagnosis.",
      "When multiple ENT compartments are inflamed or destructive, look for a unifying systemic disease.",
      "What laboratory and tissue findings support GPA while recognizing ANCA can be negative?"),

    Q("v139_gen_20", GEN, "Wound Healing / Scar Biology in Head & Neck Surgery",
      "A previously irradiated patient has a chronic neck wound with exposed hardware. Why is healing impaired?",
      ["Radiation causes hypovascular, fibrotic tissue with reduced cellular repair capacity", "Radiation increases tissue vascularity permanently", "Scar biology is unrelated to perfusion", "All wounds heal at the same rate"], 0,
      "Wound healing depends on perfusion, oxygenation, nutrition, infection control and mechanical stability; radiation disrupts several of these pathways.",
      "A chronic wound is often a biology problem before it is a suture problem.",
      "When should vascularized flap coverage be favored over repeated local closure?"),
]
