"""v27.0 — General ENT / Emergencies deliberate ladder pass 2.

Reuses five strong canonical application cases and supplies only the missing
foundation and senior-decision layers. Reused rationale mapping is keyed by
choice text so deterministic answer balancing cannot detach reasoning.
"""
DOMAIN="General ENT / Emergencies"
REUSED={
 "v139_gen_03":("Chyle Leak","application"),
 "v139_gen_04":("Common ENT Consult Triage / Disposition","application"),
 "v139_gen_09":("ENT Perioperative Anesthesia / Difficult Airway Planning","application"),
 "v139_gen_10":("Esophageal Foreign Body","application"),
 "v139_gen_14":("Hemostasis / Coagulopathy / Antithrombotic Management in ENT","application"),
}
REASONS={
 "v139_gen_03":{
  "Confirm chyle, quantify output, institute dietary/medical management and escalate early for high-output or persistent leaks":"Correct. A suspected cervical chyle leak should be confirmed and quantified while nutrition/volume losses are treated; high-output or persistent leakage lowers the threshold for procedural control.",
  "Remove the drain immediately":"Removing a useful drain can conceal ongoing leakage and create an undrained collection; management depends on output and trajectory.",
  "Ignore electrolyte losses":"High-output chyle loss can produce volume, electrolyte, protein, lymphocyte, and nutritional depletion.",
  "Treat as saliva without testing":"Milky drainage after a low left-neck operation and feeding strongly suggests chyle; the diagnosis and output should be characterized rather than assumed to be saliva."},
 "v139_gen_04":{
  "A postoperative neck patient with rapidly expanding swelling, stridor and respiratory distress":"Correct. Airway-threatening postoperative neck swelling can deteriorate within minutes and outranks stable chronic complaints.",
  "Stable cerumen impaction":"Cerumen impaction is generally nonurgent when there is no invasive infection, sudden hearing emergency, or other red flag.",
  "Chronic tinnitus unchanged for years":"Stable chronic tinnitus is important but does not outrank a threatened airway overnight.",
  "Routine outpatient nasal obstruction":"Chronic uncomplicated nasal obstruction is appropriately evaluated electively."},
 "v139_gen_09":{
  "Create a multidisciplinary awake/controlled-airway strategy that preserves spontaneous ventilation until the airway is secured":"Correct. A precarious obstructed airway may collapse after induction; the plan should preserve the physiology that is keeping the airway open until a definitive airway is secured.",
  "Induce paralysis before the airway plan is agreed":"Loss of tone and spontaneous ventilation before a rescue plan is established can convert partial obstruction to complete obstruction.",
  "Send the patient unmonitored to CT first":"Imaging must not take priority over stabilization of a clinically threatened airway.",
  "Assume direct laryngoscopy will be easy":"A bulky supraglottic lesion with positional stridor is specifically a reason not to assume routine laryngoscopy will be safe."},
 "v139_gen_10":{
  "Urgent endoscopic removal because complete esophageal obstruction risks aspiration and injury":"Correct. Inability to handle secretions indicates complete obstruction and warrants urgent endoscopic removal after airway assessment.",
  "Wait several days":"Prolonged complete obstruction increases aspiration, pressure injury, perforation, and other complications.",
  "Induce vomiting":"Induced emesis can worsen aspiration and mucosal injury and is not a safe extraction strategy.",
  "Give solid food to push it down":"Pushing an impacted bolus blindly can worsen impaction or injury and delays definitive management."},
 "v139_gen_14":{
  "Airway and surgical hemorrhage control immediately, while coordinating appropriate anticoagulant reversal/resuscitation":"Correct. A compressive postoperative hemorrhage requires airway and source control in parallel with resuscitation and appropriate reversal; reversal must not delay decompression/control.",
  "Wait for the drug to wear off":"Life-threatening hemorrhage with airway compression is not safely managed by passive observation.",
  "Reverse anticoagulation before addressing the airway":"Reversal matters, but a threatened airway and active surgical source cannot wait for pharmacologic correction to take effect.",
  "Discharge":"Active life-threatening postoperative bleeding requires immediate monitored intervention."},
}
def _q(qid,topic,stage,stem,choices,answer,exp,reasons,pearl,curveball,focus="boards"):
 return {"id":qid,"domain":DOMAIN,"topic":topic,"learning_stage":stage,"stem":stem,"choices":choices,"answer":answer,"explanation":exp,"why_wrong":reasons,"board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder","mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}
VIGNETTES_V270=[
_q("v270_gen_chyle_fnd","Chyle Leak","foundation","After a low left-neck dissection, which postoperative finding most strongly suggests a cervical chyle leak?",["Drain output that becomes milky after enteral fat exposure and rises in volume","Small stable serosanguineous output that steadily falls","Clear saliva appearing only with coughing","A dry drain with normal neck examination"],0,"Thoracic-duct injury classically produces milky triglyceride-rich drainage that often becomes more obvious after enteral fat intake. Output matters because sustained high-volume loss causes important metabolic and nutritional consequences.",["Correct. Feed-associated milky drainage after low left-neck surgery is the classic pattern.","Expected declining serosanguineous output does not suggest ongoing lymphatic leakage.","Salivary leakage follows a different anatomic and clinical pattern and should not be presumed from this finding.","A dry drain without neck swelling does not support an active high-output chyle leak."],"Think diagnosis + daily output + physiologic losses, not just drain color.","Why is a right-sided cervical chyle leak still possible despite the usual left-sided teaching?","boards"),
_q("v270_gen_chyle_snr","Chyle Leak","senior_decision","A patient has persistent 1.2-L/day chylous drainage after neck dissection despite appropriate drainage, nutritional modification and medical therapy, with falling albumin and electrolyte abnormalities. What is the best senior principle?",["Escalate early to definitive leak control such as operative ligation or image-guided lymphatic intervention rather than prolonging failing conservative care","Remove the drain and discharge","Continue the same plan indefinitely regardless of physiology","Begin unrestricted high-fat feeding"],0,"Persistent high-output chyle loss despite an adequate conservative trial exposes the patient to major volume, nutritional and immune losses. Senior management should shorten the path to definitive control, chosen according to local expertise and anatomy.",["Correct. High-output persistent leakage plus physiologic depletion is a failure phenotype that warrants definitive control.","Removing the drain does not stop the leak and may convert controlled external drainage into a neck collection.","Ongoing large-volume loss is harmful; persistence should change the plan rather than merely extend it.","Long-chain dietary fat increases intestinal lymph flow and can worsen a cervical chyle leak."],"The threshold to intervene is a trajectory decision: output, duration and metabolic cost matter together.","How would bilateral neck surgery or prior thoracic procedures alter localization and rescue planning?","senior_decision"),
_q("v270_gen_triage_fnd","Common ENT Consult Triage / Disposition","foundation","Which physiologic threats should dominate overnight ENT consult triage before diagnostic neatness?",["Airway compromise, uncontrolled hemorrhage, threatened vision/neurologic function, rapidly progressive deep infection and time-sensitive foreign bodies","Chronic stable symptoms first because they are easier to finish","Order of pager arrival regardless of severity","Imaging availability alone"],0,"ENT call triage is based on the consequence and speed of deterioration. Airway, bleeding, vision, neurologic compromise, invasive infection and selected foreign bodies can become irreversible before a complete diagnosis is established.",["Correct. Triage prioritizes threats that can deteriorate rapidly or become irreversible.","Ease of disposition does not supersede physiologic risk.","Pager order is not an appropriate severity framework.","Imaging logistics cannot replace clinical prioritization."],"Ask first: what can kill the patient or become irreversible before I finish the next consult?","A patient with a resolved post-tonsillectomy sentinel bleed is currently stable—why is that still higher priority than routine consults?","overnight_call"),
_q("v270_gen_triage_snr","Common ENT Consult Triage / Disposition","senior_decision","Three pages arrive simultaneously: a stable chronic tracheostomy granulation complaint, a child with a reported post-tonsillectomy bleed now hemostatic, and an adult with rapidly progressive floor-of-mouth swelling, drooling and muffled voice. What is the best senior disposition strategy?",["Mobilize immediate airway-capable evaluation for the floor-of-mouth infection while ensuring the post-tonsillectomy bleed remains monitored and is evaluated urgently next; defer the stable chronic issue","See the chronic issue first because it is fastest","Send the floor-of-mouth patient to unmonitored CT before airway assessment","Discharge the post-tonsillectomy bleed because no blood is visible now"],0,"Senior triage handles both immediacy and latent risk. Progressive Ludwig-pattern symptoms threaten the airway now; a sentinel tonsil bleed can recur catastrophically and still deserves urgent monitored assessment; stable chronic granulation can wait.",["Correct. This sequence matches immediate airway risk, then high-risk recurrent hemorrhage, then stable chronic disease.","Speed of completing a consult is not the priority when another patient has evolving airway compromise.","Transport and supine positioning may be dangerous before the airway trajectory is assessed.","A history of significant post-tonsillectomy hemorrhage remains clinically important even when active bleeding has stopped."],"Good call triage is dynamic: reassess the queue whenever physiology changes.","What staffing or location change would you make if the floor-of-mouth patient cannot tolerate supine positioning?","senior_decision"),
_q("v270_gen_airway_fnd","ENT Perioperative Anesthesia / Difficult Airway Planning","foundation","Why can induction of general anesthesia be dangerous in a patient with severe fixed or dynamic upper-airway obstruction who is still breathing spontaneously?",["Loss of pharyngeal/laryngeal tone, respiratory drive and favorable positioning can convert a marginal airway into complete obstruction","Induction always enlarges the airway","Paralysis guarantees easy mask ventilation","Spontaneous ventilation is irrelevant to obstructed-airway planning"],0,"A patient may be maintaining a narrow airway through muscle tone, spontaneous negative-pressure mechanics and position. Sedation, induction or paralysis can remove those compensations before an alternative airway is secured.",["Correct. The pre-induction physiology may be the only thing maintaining patency.","Induction can worsen rather than enlarge a compromised upper airway.","Neuromuscular blockade does not guarantee mask ventilation and may remove protective tone.","Whether spontaneous ventilation can be preserved is central to many difficult-airway plans."],"Do not destroy the mechanism keeping the airway open before the rescue pathway is ready.","Which laryngeal tumor features might make an awake tracheostomy safer than transoral awake intubation?","OR_prep"),
_q("v270_gen_airway_snr","ENT Perioperative Anesthesia / Difficult Airway Planning","senior_decision","A patient with near-obstructing supraglottic cancer has worsening stridor, cannot lie flat and has a very narrow endoscopic glottic view. The team debates awake flexible intubation versus awake tracheostomy. What is the best senior principle?",["Choose the route with the highest probability of securing the airway without traversing or destabilizing the obstructing lesion, with ENT/anesthesia sharing one primary and rescue plan","Attempt repeated deep sedation until the patient tolerates oral instrumentation","Induce and paralyze first so the decision is easier","Base the choice only on which operator is faster"],0,"The route is anatomy- and physiology-dependent. If transoral passage is unlikely, risks bleeding/tumor disruption or could wedge the airway closed, awake surgical airway may be safer; other anatomies favor awake endoscopic intubation. The key is a single coordinated primary/rescue plan before losing spontaneous ventilation.",["Correct. Route selection follows anatomy, physiology and rescue feasibility—not a universal technique.","Repeated sedation can progressively erase airway tone and cooperation without securing the airway.","Induction before the airway is secured may precipitate unrecoverable obstruction.","Operator speed matters less than choosing a route that remains feasible when the airway deteriorates."],"A difficult airway plan is incomplete until the failed-first-plan pathway is explicit and immediately executable.","How do prior radiation and a low bulky neck change the surgical-airway backup?","senior_decision"),
_q("v270_gen_eso_fnd","Esophageal Foreign Body","foundation","Which esophageal foreign-body presentation requires the most urgent endoscopic action even when the patient is breathing comfortably?",["Complete obstruction with inability to swallow secretions, or a button battery/sharp object in the esophagus","A small blunt object already documented in the stomach without symptoms","A resolved globus sensation with normal swallowing","An asymptomatic remote history of food impaction"],0,"Complete obstruction threatens aspiration and pressure injury, while esophageal button batteries and sharp objects can cause rapid tissue injury or perforation. A stable respiratory examination does not make these esophageal emergencies elective.",["Correct. Complete obstruction and caustic/sharp esophageal objects are time-sensitive emergencies.","Many small blunt objects beyond the esophagus can be observed depending on object/patient factors.","Resolved globus without dysphagia is not equivalent to a retained obstructing foreign body.","Remote events warrant etiologic evaluation but not emergent extraction when no object is present."],"Separate airway stability from esophageal urgency: both must be assessed.","Why does an esophageal button battery demand a faster pathway than a coin?","boards"),
_q("v270_gen_eso_snr","Esophageal Foreign Body","senior_decision","After urgent removal of a recurrent steak impaction, the esophageal mucosa shows rings and furrows but no perforation. What is the best senior next step?",["Arrange etiologic evaluation for eosinophilic esophagitis/structural disease, including appropriate biopsies and follow-up rather than treating extraction as the endpoint","Tell the patient the problem is cured permanently","Advise pushing future impactions down with food","Perform empiric neck dissection"],0,"Recurrent food impaction often reflects underlying eosinophilic esophagitis, stricture, ring or motility disease. Extraction solves the emergency; preventing recurrence requires diagnosis and longitudinal treatment of the substrate.",["Correct. Recurrent impaction plus rings/furrows should trigger EoE/structural evaluation and follow-up.","Removing one bolus does not treat the underlying disease driving recurrence.","Blindly pushing food can worsen obstruction or injury.","Neck dissection has no role in this esophageal phenotype."],"For a food bolus, the second diagnosis is often why it happened.","How would suspected perforation after extraction change imaging, antibiotics and oral-intake decisions?","senior_decision"),
_q("v270_gen_hemo_fnd","Hemostasis / Coagulopathy / Antithrombotic Management in ENT","foundation","What is the core principle when deciding whether to interrupt antiplatelet or anticoagulant therapy for an elective ENT procedure?",["Balance procedure-specific bleeding consequences against the patient's indication-specific thromboembolic risk and coordinate a drug/renal-function/timing plan","Stop every antithrombotic for the same number of days","Continue every agent for every operation","Use INR to measure the effect of every direct oral anticoagulant"],0,"Perioperative antithrombotic management is individualized. The danger of even modest bleeding differs across ENT procedures, while thrombosis risk depends on why the drug is prescribed, timing of events/devices and patient factors; DOAC clearance also depends on drug and renal function.",["Correct. Both sides of the risk equation and pharmacology determine the plan.","A universal hold interval ignores drug half-life, renal function, indication and procedural bleeding consequences.","Some operations cannot safely tolerate full antithrombotic effect; continuation is not universal.","Routine INR does not quantify the anticoagulant effect of all DOACs."],"Never ask only 'can I stop it?'—ask what thrombosis you may cause by stopping it and what bleed you may cause by continuing it.","Why is a recent coronary stent a different conversation from remote provoked DVT?","preop"),
_q("v270_gen_hemo_snr","Hemostasis / Coagulopathy / Antithrombotic Management in ENT","senior_decision","A patient on a factor-Xa inhibitor develops brisk postoperative neck bleeding with airway compression. What should happen first at senior level?",["Run airway/decompression and operative source control in parallel with resuscitation, drug-specific reversal when indicated, labs and blood-product strategy","Delay airway treatment until coagulation tests normalize","Give reversal and then observe the expanding neck","Transport to radiology before stabilizing the airway"],0,"Life-threatening ENT hemorrhage is simultaneous physiology and source control. Reversal supports hemostasis but does not mechanically decompress the airway or ligate the bleeding vessel, so it must occur in parallel rather than sequentially delaying intervention.",["Correct. Airway, decompression/source control, resuscitation and reversal are parallel workstreams.","Laboratory normalization is not a prerequisite for treating a clinically collapsing airway.","Reversal alone does not evacuate a compressive hematoma or guarantee surgical hemostasis.","A threatened airway should not be destabilized by nonessential transport before control."],"In catastrophic head-and-neck bleeding, do not turn pharmacology into a reason to delay anatomy.","How would a stable low-volume epistaxis in a patient with very high stroke risk change the threshold to reverse or interrupt anticoagulation?","senior_decision"),
]
def apply_learning_ladders_v270(challenges,item_id_fn):
 by_id={str(q.get("id")):q for q in challenges if q.get("id")}; reused=0
 for qid,(topic,stage) in REUSED.items():
  row=by_id.get(qid)
  if row is None: raise RuntimeError(f"v270 missing reusable case {qid}")
  mapping=REASONS[qid]; choices=list(row.get("choices") or []); unknown=[c for c in choices if c not in mapping]
  if unknown: raise RuntimeError(f"v270 unknown reused choices for {qid}: {unknown}")
  cid=item_id_fn(DOMAIN,topic)
  if not cid: raise RuntimeError(f"v270 orphan reusable topic {topic}")
  row.update({"domain":DOMAIN,"topic":topic,"concept_id":cid,"learning_stage":stage,"why_wrong":[mapping[c] for c in choices],"ladder_reviewed":True,"_coverage_reviewed_v211":True}); reused+=1
 existing=set(by_id); added=0
 for q in VIGNETTES_V270:
  if q["id"] in existing: continue
  row=dict(q); row["concept_id"]=item_id_fn(DOMAIN,row["topic"])
  if not row["concept_id"]: raise RuntimeError(f"v270 orphan new topic {row['topic']}")
  challenges.append(row); existing.add(row["id"]); added+=1
 return {"reused":reused,"added":added}
