"""v27.3 — General ENT / Emergencies deliberate ladder pass 5.

Five exact canonical concepts selected from the live 20/32 inventory. Existing
completed-domain and adjacent General ENT material was reviewed first; this batch
adds missing General-ENT-specific foundation, application, and senior-decision
layers without relabeling strong material from other domains. Choice-aligned
rationales permit deterministic answer balancing.
"""
DOMAIN="General ENT / Emergencies"

def _q(qid,topic,stage,stem,choices,answer,exp,reasons,pearl,curveball,focus="boards"):
 return {"id":qid,"domain":DOMAIN,"topic":topic,"learning_stage":stage,"stem":stem,"choices":choices,"answer":answer,"explanation":exp,"why_wrong":reasons,"board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder","mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}

VIGNETTES_V273=[
_q("v273_gen_cn_fnd","Cranial Nerve Examination / Skull Base Localization","foundation",
   "A patient has new dysphonia, ipsilateral palatal weakness, impaired gag sensation, and shoulder weakness after a skull-base process, while tongue strength is preserved. Which localization best unifies the deficits?",
   ["Jugular foramen involvement affecting cranial nerves IX, X, and XI","Hypoglossal canal involvement affecting cranial nerve XII alone","Internal auditory canal involvement affecting cranial nerves VII and VIII","Optic canal involvement affecting cranial nerve II"],0,
   "The jugular foramen transmits CN IX, X, and XI, so combined pharyngeal sensory/palatal-laryngeal and shoulder deficits localize there. Preserved tongue strength argues against extension to CN XII in the hypoglossal canal.",
   ["Correct. The combined IX-X-XI pattern is a classic jugular-foramen localization.","The hypoglossal canal lesion produces ipsilateral tongue weakness/atrophy rather than this IX-X-XI cluster.","The internal auditory canal localizes facial and vestibulocochlear deficits, not palatal and shoulder weakness.","The optic canal is unrelated to the lower-cranial-nerve findings described."],
   "Do not memorize isolated nerve names only: clusters of deficits are maps of skull-base foramina and spaces.",
   "What additional deficit would suggest extension from the jugular foramen to the hypoglossal canal?","boards"),
_q("v273_gen_cn_app","Cranial Nerve Examination / Skull Base Localization","application",
   "An overnight consult for 'hoarseness' reveals a breathy voice, ipsilateral vocal-fold paralysis, weak palate elevation, coughing with water, and new shoulder droop. What is the best next clinical move?",
   ["Treat this as a multiple lower-cranial-nerve/skull-base localization problem: perform a complete cranial-nerve and swallowing/airway assessment and obtain targeted contrast imaging rather than evaluating the larynx in isolation","Diagnose idiopathic unilateral vocal-fold paralysis and arrange routine voice therapy without further examination","Order a noncontrast sinus CT because sinonasal disease is the usual cause of combined X-XI deficits","Reassure the patient because shoulder weakness is unrelated to the vagus nerve"],0,
   "A vocal-fold paralysis accompanied by palatal, swallowing, or accessory-nerve findings is not an isolated recurrent-laryngeal-nerve problem. The examination should deliberately map CN IX-XII and sympathetic findings, assess aspiration risk, and image the relevant skull base/neck course based on localization.",
   ["Correct. Multiple contiguous cranial-nerve deficits change both the urgency and the anatomic imaging target.","Calling the paralysis idiopathic before recognizing the additional deficits risks missing skull-base malignancy, infection, vascular disease, or other structural pathology.","A sinus CT does not adequately evaluate the lower skull base and vagal/accessory course implicated here.","Shoulder droop indicates CN XI dysfunction and is a critical localization clue rather than an incidental symptom."],
   "A cranial neuropathy becomes a localization case the moment a second neighboring nerve is abnormal.",
   "Which examination findings would push the localization into the carotid space or sympathetic chain rather than the jugular foramen alone?","overnight_call"),
_q("v273_gen_cn_snr","Cranial Nerve Examination / Skull Base Localization","senior_decision",
   "A patient with progressive dysphagia, aspiration, shoulder weakness, and ipsilateral tongue atrophy has several weeks of worsening lower-cranial-nerve deficits. The junior resident wants to order separate tests for each symptom. What is the best senior approach?",
   ["Synthesize the IX-XII pattern as a skull-base/lower-parapharyngeal localization, secure swallowing and airway safety first, and choose imaging that covers the suspected skull base and extracranial nerve course with contrast rather than fragmenting the workup by symptom","Order only a modified barium swallow because aspiration explains all of the neurologic findings","Observe for three months because slowly progressive cranial neuropathies are usually benign","Schedule isolated vocal-fold injection before defining the cause or the patient's broader aspiration risk"],0,
   "Progressive multiple lower-cranial-neuropathy is a structural red flag. Senior reasoning links the deficits anatomically, addresses immediate aspiration/airway consequences, and then images the entire suspected pathway so tumor, perineural disease, infection, inflammatory disease, or vascular pathology is not missed.",
   ["Correct. Localization should collapse multiple symptoms into one anatomic hypothesis while immediate functional threats are managed in parallel.","A swallow study can quantify dysfunction but cannot explain the shoulder and tongue neuropathies or replace etiologic imaging.","Progression across neighboring cranial nerves is a reason to expedite structural evaluation, not to defer it.","Symptom palliation may later be useful, but it should not precede recognition of a potentially serious unifying lesion or aspiration plan."],
   "Chief-level cranial-nerve examination is not a checklist; it is an imaging prescription and a safety assessment.",
   "How would abrupt onset over minutes, rather than progression over weeks, change the vascular urgency and imaging strategy?","senior_decision"),

_q("v273_gen_img_fnd","ENT Imaging Fundamentals","foundation",
   "Which general imaging principle is most useful when choosing between CT and MRI for an ENT problem?",
   ["CT is usually strongest for cortical bone, calcification, gas, and rapid acute assessment, whereas MRI is usually stronger for marrow, soft tissue, intracranial extension, and perineural disease","MRI is always the first test for facial trauma because it depicts fractures better than CT","Noncontrast CT is the preferred study for mapping perineural tumor spread","Ultrasound replaces cross-sectional imaging for all deep-neck and skull-base disease"],0,
   "Imaging should answer the clinical question. Thin-cut CT is excellent for bone, air-containing spaces, calcification, and fast emergency evaluation; contrast-enhanced MRI provides superior soft-tissue, marrow, neural, and intracranial characterization in many settings.",
   ["Correct. Modality selection follows the tissue and complication you need to see, not a universal hierarchy of tests.","CT is generally faster and more sensitive for osseous facial-trauma detail than MRI.","Perineural spread is typically better characterized with appropriately protocolled contrast-enhanced MRI.","Ultrasound is valuable for accessible superficial structures but is limited by bone, air, and deep complex anatomy."],
   "The board question is rarely 'Which scan is best?' It is 'Which scan best answers this anatomic question now?'",
   "Why might you deliberately obtain both CT and MRI for a lateral skull-base lesion?","boards"),
_q("v273_gen_img_app","ENT Imaging Fundamentals","application",
   "A toxic patient has trismus, neck swelling, and concern for a deep-neck abscess with possible vascular complications. Which initial cross-sectional study is most useful in a stable patient?",
   ["Contrast-enhanced CT of the neck, extending coverage as clinically indicated to define deep-space infection, drainable collections, airway effect, gas, and major vascular relationships","Routine noncontrast neck CT because IV contrast obscures abscesses","MRI without contrast as the only acceptable emergency study regardless of availability or airway stability","Plain neck radiographs because they reliably exclude a deep-space collection"],0,
   "Contrast CT is fast, widely available, and maps deep fascial spaces, rim-enhancing collections, gas, airway displacement, and vascular relationships. Coverage should expand when chest/mediastinal extension or another complication is suspected.",
   ["Correct. In a stable patient, contrast CT is a high-yield first study for operative planning and complication mapping in deep-neck infection.","Without contrast, differentiating phlegmon from a drainable collection and assessing vascular complications becomes less reliable.","MRI can add important soft-tissue information but may be slower and less practical in an acutely ill airway patient; it is not mandatory as the first emergency test.","Plain films lack the sensitivity and anatomic detail needed to exclude a deep-space abscess."],
   "A deep-neck CT should answer three questions: where is the source, what must be drained, and what structures are already threatened?",
   "What CT finding would make you extend the workup into the chest for descending mediastinal infection?","overnight_call"),
_q("v273_gen_img_snr","ENT Imaging Fundamentals","senior_decision",
   "After penetrating neck trauma, a hemodynamically stable patient has a rapidly expanding hematoma history, transient oral bleeding, and concern for arterial injury, but no active external hemorrhage at the moment. What imaging decision is most appropriate?",
   ["Obtain urgent CT angiography when the patient is stable enough for imaging, while maintaining a hemorrhage and airway rescue plan; do not substitute a routine venous-phase neck CT for a vascular question","Order a routine noncontrast CT because contrast could hide active bleeding","Delay all vascular imaging until hemoglobin falls","Obtain MRI/MRA first because it is faster and better for acute aerodigestive trauma"],0,
   "When the question is arterial injury, pseudoaneurysm, active extravasation, or vessel trajectory, the protocol must be vascular. CTA rapidly evaluates the cervical vessels and can guide endovascular or operative planning, but unstable patients still require immediate resuscitation/source control rather than obligatory transport to the scanner.",
   ["Correct. Protocol selection must match the vascular question, and physiologic stability determines whether imaging is safe before intervention.","Noncontrast CT cannot adequately characterize arterial lumen injury or active vascular enhancement.","Early hemoglobin may remain deceptively normal during acute hemorrhage; laboratory delay is unsafe when anatomy and history are concerning.","MRI is slower and generally not the first-line acute vascular/penetrating-neck study in an unstable or potentially deteriorating patient."],
   "The wrong CT protocol can be functionally the wrong test even when the correct body part was scanned.",
   "When would hard signs of ongoing vascular injury make direct operative/endovascular control more appropriate than additional imaging?","senior_decision"),

_q("v273_gen_fen_fnd","ENT Fluids / Electrolytes / Nutrition","foundation",
   "A malnourished head-and-neck cancer patient is about to restart nutrition after prolonged minimal intake. Which electrolyte abnormality is the classic early warning for refeeding syndrome?",
   ["Hypophosphatemia from insulin-driven intracellular shifts, often accompanied by potassium and magnesium depletion","Hypernatremia from obligatory sodium loading","Hypercalcemia from rapid bone turnover","Isolated respiratory alkalosis without electrolyte change"],0,
   "Refeeding increases insulin and drives phosphate, potassium, and magnesium into cells. Severe hypophosphatemia can impair diaphragmatic, cardiac, and cellular energy function; high-risk patients also require attention to thiamine and careful advancement of calories.",
   ["Correct. Falling phosphate is the classic biochemical signal and can precede serious cardiopulmonary and neurologic complications.","Sodium balance can change during refeeding, but hypernatremia is not the defining intracellular-shift abnormality.","Hypercalcemia is not the characteristic refeeding electrolyte pattern.","Refeeding syndrome is fundamentally a metabolic/electrolyte process and should not be reduced to an isolated acid-base finding."],
   "The malnourished patient can be harmed by feeding too aggressively; nutrition is a therapy with a dose and a monitoring plan.",
   "Which history, weight-loss, intake, and baseline-electrolyte features make you treat a patient as high risk before feeds begin?","boards"),
_q("v273_gen_fen_app","ENT Fluids / Electrolytes / Nutrition","application",
   "A severely malnourished postoperative patient starts tube feeds and 24 hours later develops weakness, tachycardia, edema, phosphate 1.1 mg/dL, low magnesium, and low potassium. What is the best next step?",
   ["Treat this as refeeding syndrome: slow or temporarily reduce caloric delivery as appropriate, urgently replace phosphate/magnesium/potassium, give thiamine, monitor fluid status and rhythm, then advance nutrition cautiously","Increase feeds immediately to full goal because the electrolyte abnormalities prove underfeeding","Stop all nutrition indefinitely and provide only free water","Give sodium bicarbonate alone because the main problem is metabolic acidosis"],0,
   "This is a classic post-refeeding electrolyte shift with cardiopulmonary risk. Management couples controlled nutritional advancement with aggressive electrolyte/thiamine correction and monitoring; simply pushing to goal feeds can worsen the intracellular shifts.",
   ["Correct. The metabolic injury and the nutrition prescription must be corrected together.","Increasing calories intensifies insulin-driven electrolyte shifts and can worsen instability.","Nutrition should not be abandoned indefinitely; it should be restarted/advanced safely after stabilization with continued monitoring.","Bicarbonate does not correct phosphate, magnesium, potassium, or thiamine depletion and is not the core treatment."],
   "When phosphate crashes after feeds start, do not celebrate caloric delivery—recognize a potentially lethal refeeding complication.",
   "What cardiac, respiratory, or neurologic deterioration would trigger ICU-level monitoring?","overnight_call"),
_q("v273_gen_fen_snr","ENT Fluids / Electrolytes / Nutrition","senior_decision",
   "A free-flap patient is hypotensive overnight after adequate initial resuscitation. The flap is warm with a strong Doppler, urine output is borderline, lungs already have increasing crackles, and repeated large crystalloid boluses have not corrected the blood pressure. What is the best senior management principle?",
   ["Reassess the cause of hypotension and volume responsiveness rather than reflexively giving more crystalloid; correct bleeding/sepsis/cardiac causes, use hemodynamically appropriate vasoactive support when indicated, and avoid edema-producing fluid overload that can harm pulmonary and flap recovery","Continue unlimited crystalloid until urine output exceeds 2 mL/kg/hour regardless of lung findings","Withhold all blood-pressure support because vasopressors are absolutely contraindicated after free-flap surgery","Give hypotonic maintenance fluid as rapid resuscitation because it creates less tissue edema"],0,
   "Postoperative hypotension is not synonymous with fluid depletion. Once intravascular volume is reasonably restored, repeated unselected boluses can worsen pulmonary edema and tissue edema without improving perfusion. The senior decision is to identify the physiology—bleeding, vasodilation, cardiac dysfunction, sepsis, medication effect—and treat it directly while continuing flap surveillance.",
   ["Correct. Goal-directed resuscitation protects both systemic organs and the reconstruction better than chasing pressure or urine output with unlimited fluid.","A fixed urine-output target should not override worsening pulmonary edema or evidence that additional fluid is not improving perfusion.","Modern flap care does not support an absolute prohibition on clinically indicated vasopressors; untreated hypotension also threatens perfusion.","Hypotonic fluid is not appropriate for rapid intravascular resuscitation and can worsen electrolyte/free-water problems."],
   "The chief-level fluid question is 'Is this patient fluid responsive?'—not simply 'Is the blood pressure low?'",
   "How would active hemorrhage or a newly weak flap Doppler change the parallel resuscitation and return-to-OR decisions?","senior_decision"),

_q("v273_gen_pain_fnd","Pain Management in the Head & Neck Patient","foundation",
   "Which principle best describes modern perioperative pain control for most head-and-neck patients?",
   ["Use multimodal analgesia that combines nonopioid and procedure-appropriate adjuncts, reserving opioids for breakthrough pain while accounting for bleeding, renal, hepatic, respiratory, and swallowing risks","Use opioids as the sole first-line agent because nonopioid medications never provide meaningful postoperative analgesia","Avoid acetaminophen in every surgical patient because it increases platelet dysfunction","Give sedating medications without considering obstructive sleep apnea or airway anatomy"],0,
   "Multimodal analgesia reduces reliance on any single drug class. Acetaminophen, NSAIDs when appropriate, local/regional techniques, and selected adjuncts can reduce opioid exposure; the regimen must be individualized to renal/hepatic function, bleeding risk, OSA, airway vulnerability, and procedure-specific concerns.",
   ["Correct. Multimodal therapy improves analgesic flexibility while limiting dose-dependent opioid adverse effects.","Opioid-only strategies increase nausea, constipation, sedation, respiratory depression, and dependence risk and are often unnecessary.","Acetaminophen does not cause the platelet inhibition characteristic of NSAIDs, although dose and hepatic risk still matter.","OSA and compromised upper-airway anatomy increase the danger of sedative and opioid respiratory depression."],
   "Pain control is not a choice between 'opioids' and 'no pain control'; it is a layered risk-adjusted plan.",
   "Which patient factors would make you reduce opioid dosing or increase postoperative respiratory monitoring?","boards"),
_q("v273_gen_pain_app","Pain Management in the Head & Neck Patient","application",
   "Several hours after airway surgery, a patient with severe OSA becomes difficult to arouse after repeated IV opioid doses and has bradypnea with intermittent obstruction. What is the best immediate response?",
   ["Treat opioid-related ventilatory impairment as an airway emergency: stimulate and support ventilation/oxygenation, stop further sedatives/opioids, titrate reversal when indicated, and escalate monitoring while reassessing for a surgical airway complication","Give another opioid dose because agitation after arousal proves undertreated pain","Allow the patient to sleep unmonitored because oxygen saturation is currently normal on supplemental oxygen","Administer a benzodiazepine to reduce upper-airway muscle activity"],0,
   "Bradypnea and depressed consciousness after opioids require immediate ventilatory support and medication reassessment. Supplemental oxygen can mask hypoventilation, particularly in OSA; ENT must also exclude hematoma, edema, bleeding, or another mechanical airway problem rather than anchoring on medication alone.",
   ["Correct. Airway/ventilation comes first, with cautious reversal and simultaneous evaluation for structural postoperative threats.","Additional opioid can deepen respiratory depression and worsen obstruction.","Normal saturation on supplemental oxygen does not ensure adequate ventilation or protect against hypercapnia and sudden obstruction.","Benzodiazepines can further depress ventilation and upper-airway tone and are inappropriate as rescue therapy here."],
   "In an OSA airway patient, sedation score and respiratory pattern can deteriorate before the pulse oximeter tells you the truth.",
   "How would neck swelling, stridor, or bloody drain output change your differential and threshold for bedside wound release or return to the OR?","overnight_call"),
_q("v273_gen_pain_snr","Pain Management in the Head & Neck Patient","senior_decision",
   "A patient on long-term high-dose opioids for advanced head-and-neck cancer undergoes major surgery and has severe postoperative pain despite standard PRN dosing. What is the best senior plan?",
   ["Prevent withdrawal by accounting for the patient's baseline opioid requirement, add multimodal analgesia, use opioid-tolerant breakthrough dosing with close respiratory monitoring, and involve pain/palliative expertise when needed rather than treating the patient as opioid-naive","Stop all baseline opioids abruptly so postoperative pain can be measured accurately","Escalate only benzodiazepines because tolerance to opioids means respiratory depression is impossible","Use the same low PRN opioid dose prescribed for an opioid-naive patient and label persistent pain as drug-seeking"],0,
   "Opioid tolerance changes both baseline requirements and breakthrough dosing. Abrupt cessation can produce withdrawal while undertreatment impairs coughing, mobilization, swallowing rehabilitation, and recovery. Multimodal therapy and specialist input help balance analgesia with respiratory safety, especially in patients with airway compromise.",
   ["Correct. The plan distinguishes baseline physiologic dependence from new surgical pain and treats both without abandoning safety monitoring.","Abrupt cessation risks withdrawal and does not provide humane or physiologically sound perioperative care.","Tolerance does not eliminate respiratory depression, and benzodiazepines add dangerous sedation without treating nociceptive pain.","Opioid-tolerant patients often need different dosing; stigmatizing persistent pain prevents appropriate reassessment and treatment."],
   "Opioid tolerance means the dose-response curve changed; it does not mean the patient stopped deserving analgesia or monitoring.",
   "How would methadone or buprenorphine maintenance change the perioperative medication-reconciliation and consultation plan?","senior_decision"),

_q("v273_gen_abx_fnd","Antimicrobial Stewardship in Otolaryngology","foundation",
   "A patient undergoes uncomplicated clean-contaminated head-and-neck surgery with appropriate perioperative prophylaxis and has no evidence of active infection. Which stewardship principle is best?",
   ["Use procedure-appropriate perioperative prophylaxis and avoid extending antibiotics solely because drains remain in place when there is no separate infectious indication","Continue broad-spectrum IV antibiotics until every drain and staple is removed","Add empiric antifungal therapy to all clean-contaminated cases","Use a fluoroquinolone plus vancomycin indefinitely to prevent any possible surgical-site infection"],0,
   "Surgical prophylaxis is intended to reduce inoculum during the perioperative risk window, not to sterilize drains for days. Unnecessary prolonged therapy increases C. difficile, resistance, adverse drug effects, and line complications without substituting for operative technique or wound surveillance.",
   ["Correct. Prophylaxis duration should be tied to evidence and the procedure, not automatically to drain duration.","Drain presence alone is not a reason for indefinite systemic antibiotics in an otherwise uncomplicated case.","Routine antifungal prophylaxis is not justified for standard clean-contaminated head-and-neck surgery.","Excessively broad prolonged therapy creates toxicity and resistance without a defined target."],
   "A drain is not an infection diagnosis, and antibiotic duration should not be determined by the calendar alone.",
   "Which operative contamination, active-infection, hardware, or host factors would convert prophylaxis into treatment and change duration?","boards"),
_q("v273_gen_abx_app","Antimicrobial Stewardship in Otolaryngology","application",
   "A patient with a drained odontogenic deep-neck abscess improves after broad empiric IV therapy. Cultures grow a susceptible oral streptococcus plus expected oral anaerobes, blood cultures are negative, and there is no mediastinal extension. What is the best antimicrobial decision?",
   ["Narrow therapy to an agent that reliably covers the documented oral flora and clinical syndrome, with route and duration guided by source control and response rather than continuing the broadest empiric regimen","Continue every empiric agent indefinitely because narrowing after culture results is unsafe","Add antipseudomonal therapy despite no microbiologic or host-risk indication","Ignore source control and lengthen antibiotic duration to compensate for an undrained collection"],0,
   "Empiric broad coverage is appropriate when a severe deep-neck infection is undifferentiated. Once source control is achieved and microbiology/clinical response clarify the syndrome, de-escalation reduces toxicity and resistance while maintaining necessary pathogen coverage.",
   ["Correct. Stewardship means matching spectrum, route, and duration to the actual infection after the uncertainty narrows.","Continuing redundant broad agents after cultures and clinical response clarify the infection adds harm without improving source control.","Antipseudomonal coverage should follow a credible host, exposure, or culture indication rather than reflexive escalation.","Antibiotics cannot reliably sterilize an undrained abscess; persistent source control failure requires anatomic reassessment."],
   "Start broad when the patient is sick and the diagnosis is uncertain; narrow when cultures, anatomy, and response make uncertainty smaller.",
   "What clinical deterioration would make you re-image or return for drainage instead of simply broadening antibiotics?","overnight_call"),
_q("v273_gen_abx_snr","Antimicrobial Stewardship in Otolaryngology","senior_decision",
   "An immunocompromised patient with invasive-appearing sinonasal disease worsens despite broad antibacterial therapy. The resident proposes sequentially adding more antibiotics without repeat endoscopy, imaging, or tissue. What is the best senior decision?",
   ["Reassess the diagnosis and source urgently: obtain appropriate tissue for histopathology and bacterial/fungal studies, repeat anatomic assessment for necrosis or undrained disease, and tailor antimicrobial plus surgical therapy to the phenotype rather than stacking empiric drugs blindly","Add three additional broad antibiotics before obtaining any tissue because more spectrum always improves outcomes","Avoid debridement or biopsy because immunocompromised patients should never undergo urgent procedures","Wait for a positive blood culture before considering invasive fungal disease"],0,
   "Clinical failure is information. In a high-risk host, persistent progression despite broad antibacterial therapy raises concern for wrong organism, invasive fungal disease, resistant pathogen, noninfectious mimic, inadequate penetration, or inadequate source control. Histopathology and operative findings may be more decisive than another empiric antibiotic.",
   ["Correct. Senior stewardship is diagnostic stewardship plus source control—not merely choosing a narrower formulary drug.","Unstructured antimicrobial stacking increases toxicity and may still miss fungal disease or a noninfectious diagnosis.","Immunocompromise can increase the urgency of obtaining tissue and debriding necrotic infection rather than prohibiting intervention.","Blood cultures may be negative in localized invasive fungal disease and should not delay tissue diagnosis when the phenotype is concerning."],
   "When treatment fails, ask whether the diagnosis, organism, compartment, or source control is wrong before assuming the spectrum is too narrow.",
   "How should renal function, QT-prolonging drugs, marrow suppression, and drug interactions influence the definitive antimicrobial plan?","senior_decision"),
]

def apply_learning_ladders_v273(challenges,item_id_fn):
 existing={str(q.get("id")) for q in challenges if q.get("id")}; added=0
 for q in VIGNETTES_V273:
  if q["id"] in existing: continue
  row=dict(q); row["concept_id"]=item_id_fn(DOMAIN,row["topic"])
  if not row["concept_id"]: raise RuntimeError(f"v273 orphan topic {row['topic']}")
  challenges.append(row); existing.add(row["id"]); added+=1
 return {"added":added,"ids":[q["id"] for q in VIGNETTES_V273]}
