"""v15.4 — Structured foundation→application→senior-decision ladders.

One complete three-step ladder in each major domain. The goal is not raw volume:
these cases deliberately preserve basic knowledge testing while adding progressively
more contextual and chief-level decision making on the same canonical concept.
"""


def _c(qid,d,t,stage,s,ch,a,e,ww,p,cb,f="boards"):
    return {"id":qid,"domain":d,"topic":t,"learning_stage":stage,"stem":s,
            "choices":ch,"answer":a,"explanation":e,"why_wrong":ww,
            "board_pearl":p,"curveball":cb,"tier":"Curated learning ladder",
            "mode":"Vignette","focus":f}

O="Otology / Neurotology"; R="Rhinology / Allergy / Skull Base"; H="Head & Neck Oncology"
T="Thyroid / Parathyroid / Salivary"; P="Pediatric Otolaryngology"; L="Laryngology / Voice / Swallowing"
F="Facial Plastics / Trauma"; S="Sleep Surgery"; G="General ENT / Emergencies"

VIGNETTES_V154=[
# OTOLOGY — Audiogram Interpretation
_c("v154_oto_fnd",O,"Audiogram Interpretation","foundation",
"Pure-tone testing shows air thresholds near 50 dB HL and bone thresholds near 10 dB HL in the right ear. What type of hearing loss is present?",
["Conductive hearing loss","Sensorineural hearing loss","Mixed hearing loss","Normal hearing"],0,
"A substantial air-bone gap with preserved bone thresholds defines conductive hearing loss. The first audiogram skill is always to compare air and bone thresholds before reaching for a disease label.",
["Correct.","Sensorineural loss requires elevated bone thresholds as well as air thresholds.","Mixed loss requires both elevated bone thresholds and an additional air-bone gap.","Air thresholds around 50 dB HL are not normal."],
"Classify the loss before localizing the cause.","What tympanogram pattern would make middle-ear effusion particularly likely?","boards"),
_c("v154_oto_app",O,"Audiogram Interpretation","application",
"The same patient has a flat type-B tympanogram with normal ear-canal volume and excellent word recognition. Which localization best integrates the data?",
["Middle-ear conductive pathology such as effusion","Large tympanic-membrane perforation","Auditory neuropathy spectrum disorder","Retrocochlear tumor"],0,
"A type-B tracing with normal canal volume supports a nonventilated middle-ear system such as effusion. A large perforation or patent tube usually produces a flat tracing with a large measured canal volume.",
["Correct.","A perforation usually enlarges measured canal volume because the tympanometer also measures the middle-ear/mastoid air space.","Auditory neuropathy is an electrophysiologic disorder and does not explain this classic conductive audiogram plus flat normal-volume tympanogram.","Retrocochlear disease does not create a large air-bone gap with middle-ear immittance abnormalities."],
"Tympanometry localizes the conductive mechanism after the audiogram classifies it.","If the type-B tracing had a very large canal volume, what two explanations should move to the top?","boards"),
_c("v154_oto_snr",O,"Audiogram Interpretation","senior_decision",
"A patient has a 35-dB apparent low-frequency air-bone gap, normal tympanometry, present acoustic reflexes, autophony, and sound-induced vertigo. What should stop you from recommending middle-ear exploration?",
["The pattern suggests a third-window phenomenon rather than ordinary ossicular disease","Any air-bone gap automatically requires stapes surgery","Normal tympanometry proves the audiogram is wrong","Autophony is unrelated to hearing mechanics"],0,
"A pseudoconductive gap with normal middle-ear mechanics plus autophony or Tullio/pressure symptoms should redirect the workup toward a third-window lesion such as superior canal dehiscence. Senior interpretation means recognizing when the audiogram's apparent conductive pattern is not a middle-ear problem.",
["Correct.","Stapes surgery for a third-window disorder can worsen symptoms and does not address the underlying mechanics.","Normal tympanometry is useful evidence that the conductive-appearing pattern may originate outside the middle ear; it does not invalidate the audiogram.","Autophony is a classic symptom of abnormal inner-ear sound/pressure transmission and is highly relevant."],
"A conductive-looking audiogram does not guarantee conductive middle-ear disease.","Which VEMP and CT findings would you want before offering superior-canal surgery?","boards"),

# RHINOLOGY — Epistaxis Surgical Control
_c("v154_rh_fnd",R,"Epistaxis Surgical Control","foundation",
"Most severe posterior nasal bleeding requiring operative control arises from branches of which artery?",
["Sphenopalatine artery","Facial artery at the mandibular border","Superior thyroid artery","Middle meningeal artery"],0,
"The sphenopalatine artery, terminal branch of the internal maxillary artery, is the dominant arterial source targeted during endoscopic surgical control of posterior epistaxis.",
["Correct.","The facial artery is external to the nasal cavity and is not the routine posterior epistaxis target.","The superior thyroid artery supplies the thyroid/laryngeal region, not the posterior nasal cavity.","The middle meningeal artery is intracranial and is not the standard endoscopic target for posterior epistaxis."],
"Know the vessel before you learn the operation.","Where does the sphenopalatine artery enter the nasal cavity?","boards"),
_c("v154_rh_app",R,"Epistaxis Surgical Control","application",
"A patient has recurrent brisk posterior bleeding despite appropriate packing and resuscitation. Which definitive intervention best matches the usual operative target?",
["Endoscopic identification and control of sphenopalatine arterial branches","Repeated anterior cautery only","Routine external carotid ligation as first-line in every patient","Septoplasty without vascular control"],0,
"Persistent posterior epistaxis that fails bedside measures should progress to definitive arterial control. Endoscopic sphenopalatine artery ligation/cautery is a common direct approach because it treats the dominant posterior nasal arterial inflow near its entry point.",
["Correct.","Anterior cautery cannot reliably control a true posterior source.","External carotid ligation is more remote, less targeted, and not the routine first definitive procedure when endoscopic control is feasible.","Septoplasty may improve access in selected anatomy but does not itself control the bleeding vessel."],
"Escalation should become more anatomically targeted, not simply more repetitive.","When might angiographic embolization be preferred to OR ligation?","OR_prep"),
_c("v154_rh_snr",R,"Epistaxis Surgical Control","senior_decision",
"During endoscopic sphenopalatine artery control, the main trunk is clipped but brisk bleeding recurs from a separate posterior-superior branch. What is the best operative interpretation?",
["Missed arterial branching is a recognized cause of failure; expose the foramen region adequately and control all relevant branches","The operation has failed and the nasal cavity should be packed indefinitely","The bleeding must now be venous","Only the anterior ethmoidal artery can branch"],0,
"The sphenopalatine artery often divides into multiple branches. Incomplete exposure or missed branches is a classic reason for persistent bleeding after apparently successful control. Chief-level operative thinking asks why the procedure failed anatomically.",
["Correct.","Packing can temporize but does not correct a missed surgically accessible arterial branch.","Persistent pulsatile posterior bleeding after incomplete branch control remains compatible with arterial bleeding.","Posterior nasal arterial branching is normal anatomy and is not unique to ethmoidal vessels."],
"Failure after SPA control often means incomplete branch control, not inadequate cautery power.","How do septal and lateral-nasal branches influence your dissection around the sphenopalatine foramen?","OR_prep"),

# HEAD & NECK — Total Laryngectomy
_c("v154_hn_fnd",H,"Total Laryngectomy","foundation",
"After a total laryngectomy, where does inspired air enter the lungs?",
["Through the permanent neck stoma only","Through the mouth and nose as before","Through both mouth and stoma equally","Through the esophagus"],0,
"Total laryngectomy permanently separates the trachea from the pharynx. The neck stoma is therefore the patient's only respiratory airway.",
["Correct.","The upper airway no longer communicates with the lungs after total laryngectomy.","There is no dual communication after a completed total laryngectomy.","The esophagus carries swallowed material, not inspired air."],
"A laryngectomy patient is a neck breather, not simply a patient with a tracheostomy.","Why does this distinction matter during emergency oxygenation?","boards"),
_c("v154_hn_app",H,"Total Laryngectomy","application",
"A laryngectomy patient arrives hypoxic with thick crust occluding the stoma. Oxygen placed over the face has no effect. What is the correct immediate airway action?",
["Deliver oxygen/ventilation through the stoma and clear the obstruction","Attempt oral endotracheal intubation","Seal the stoma to redirect airflow through the mouth","Wait for humidification to dissolve the crust"],0,
"All ventilation after total laryngectomy must occur through the stoma. Acute obstruction should be addressed directly at the stoma with oxygenation, suction/crust removal, and escalation as needed.",
["Correct.","Oral intubation cannot reach the trachea because the pharynx and airway are surgically disconnected.","Occluding the stoma blocks the patient's only airway.","Humidification is preventive/supportive but cannot replace immediate relief of a critical obstruction."],
"In a laryngectomy emergency, move every airway intervention to the neck.","How would this emergency differ in a tracheostomy patient with an intact larynx?","overnight_call"),
_c("v154_hn_snr",H,"Total Laryngectomy","senior_decision",
"During salvage total laryngectomy after chemoradiation, the pharyngeal mucosa is fibrotic and closure will be tight. Which decision most directly addresses the increased fistula risk?",
["Create a tension-free watertight closure and strongly consider vascularized tissue reinforcement","Close devascularized mucosa under maximal tension to shorten the operation","Avoid checking the closure because manipulation causes leaks","Place the stoma through the pharyngeal suture line"],0,
"Prior radiation, poor tissue quality, malnutrition, and closure tension increase pharyngocutaneous fistula risk. A senior operative plan anticipates this before closure and may bring in vascularized tissue such as pectoralis or free tissue for reinforcement.",
["Correct.","Tension and poor perfusion increase rather than reduce wound breakdown.","Inspection/leak testing can identify correctable defects before leaving the OR.","Separating the permanent airway from the pharyngeal closure avoids contamination and mechanical compromise."],
"In salvage surgery, reconstruction is part of complication prevention, not an afterthought.","What patient and wound factors would push you toward prophylactic flap reinforcement?","OR_prep"),

# THYROID — Recurrent Laryngeal Nerve Injury During Thyroidectomy
_c("v154_tps_fnd",T,"Recurrent Laryngeal Nerve Injury During Thyroidectomy","foundation",
"Near which location is the recurrent laryngeal nerve particularly vulnerable during thyroidectomy because of its close relationship to the thyroid capsule?",
["Ligament of Berry / laryngeal entry region","Submental triangle","Parotid tail","Posterior nasal cavity"],0,
"The RLN is especially vulnerable near the ligament of Berry and its entry into the larynx, where the nerve lies close to the thyroid and branching/anatomic variation may occur.",
["Correct.","The submental triangle is unrelated to thyroid RLN anatomy.","The parotid tail is a facial-nerve region, not a recurrent-laryngeal-nerve landmark.","Posterior nasal anatomy has no relationship to thyroidectomy RLN risk."],
"Know where the nerve is most vulnerable before discussing monitoring or rescue.","Why is the inferior thyroid artery an imperfect single landmark for the RLN?","boards"),
_c("v154_tps_app",T,"Recurrent Laryngeal Nerve Injury During Thyroidectomy","application",
"After thyroidectomy, a patient develops a new breathy voice and coughs with thin liquids. What is the key first diagnostic test?",
["Flexible laryngoscopy to assess vocal-fold mobility","CT chest before examining the larynx","Empiric reflux medication only","Routine audiogram"],0,
"New dysphonia or aspiration after thyroid surgery should prompt direct assessment of vocal-fold mobility. Flexible laryngoscopy distinguishes RLN dysfunction from unrelated voice complaints and guides airway/aspiration management.",
["Correct.","Chest CT does not establish postoperative vocal-fold mobility and should not precede direct laryngeal assessment for this presentation.","Reflux treatment does not evaluate a new postoperative motor deficit.","Audiometry evaluates hearing, not laryngeal nerve function."],
"Document vocal-fold function when postoperative symptoms suggest nerve injury.","How does management differ for unilateral versus bilateral immobility?","boards"),
_c("v154_tps_snr",T,"Recurrent Laryngeal Nerve Injury During Thyroidectomy","senior_decision",
"During planned total thyroidectomy, the first-side RLN has a true loss of signal despite troubleshooting, although it appears anatomically intact. The opposite lobe can safely be treated later. What should change?",
["Stage the contralateral side rather than risk bilateral vocal-fold paralysis","Proceed because visual continuity proves function","Transect the first nerve to confirm the injury","Complete both sides and plan prophylactic tracheostomy"],0,
"A true first-side loss of signal changes the risk calculation. When oncologically acceptable, staging the contralateral side avoids converting an uncertain unilateral neuropraxia into bilateral vocal-fold immobility and a major airway problem.",
["Correct.","An anatomically intact nerve can still have functional injury or neuropraxia after loss of signal.","Transection creates permanent injury and is not a diagnostic maneuver.","A preventable bilateral nerve injury should not be accepted merely because a tracheostomy could manage the consequence."],
"Monitoring earns its value only when new information changes the operative plan.","What sequence of troubleshooting should precede declaring a true loss of signal?","OR_prep"),

# PEDIATRICS — Croup vs Epiglottitis
_c("v154_ped_fnd",P,"Croup vs Epiglottitis","foundation",
"Which presentation is most typical of viral croup?",
["Barky cough, hoarseness, and inspiratory stridor after a viral prodrome","Drooling, tripod positioning, toxic appearance, and muffled voice","Progressive unilateral neck mass","Isolated otalgia with normal breathing"],0,
"Croup classically produces a barky cough, hoarseness, and inspiratory stridor from subglottic inflammation, usually in a child who is not toxic appearing.",
["Correct.","Drooling, tripod posture, toxic appearance, and muffled voice should raise concern for epiglottitis/supraglottitis rather than routine croup.","A neck mass is not a typical croup presentation.","Isolated ear pain does not describe upper-airway obstruction."],
"Start by separating the clinical syndromes before deciding how aggressively to manipulate the airway.","What treatment is given to essentially all clinically significant croup?","boards"),
_c("v154_ped_app",P,"Croup vs Epiglottitis","application",
"A child has stridor at rest and retractions but remains alert, handles secretions, and has a classic barky cough. What is the best treatment?",
["Dexamethasone plus nebulized epinephrine with observation for recurrence","Immediate bedside tongue-depressor examination for epiglottitis","Antibiotics alone","Discharge without treatment"],0,
"Stridor at rest indicates more significant croup. Corticosteroid therapy reduces airway inflammation, and nebulized epinephrine provides rapid temporary improvement while the child is observed for recurrence after its effect wanes.",
["Correct.","The classic barky-cough phenotype with secretion handling is consistent with croup, and unnecessary distressing airway examination is not the treatment.","Croup is usually viral; antibiotics do not address the primary process.","Stridor at rest requires treatment and observation rather than no intervention."],
"Severity changes croup treatment even when the diagnosis does not change.","How long should you observe after nebulized epinephrine before assuming the rebound-risk window has passed?","overnight_call"),
_c("v154_ped_snr",P,"Croup vs Epiglottitis","senior_decision",
"A febrile child with inspiratory stridor becomes quiet, drools, sits forward, refuses to lie down, and has a muffled voice. The ED asks ENT to perform a bedside oropharyngeal exam. What is the safest response?",
["Avoid agitating the child and coordinate a controlled airway plan with anesthesia/ENT in an appropriate setting","Force a tongue depressor exam immediately","Send the child unmonitored for routine neck radiographs","Treat as ordinary croup and discharge after one nebulizer"],0,
"This is a threatened supraglottic-airway phenotype. Agitation can precipitate complete obstruction, so the priority is maintaining calm and moving to a controlled airway plan with experienced personnel rather than proving the diagnosis at bedside.",
["Correct.","Forceful examination may trigger complete obstruction in a critically narrowed supraglottic airway.","Imaging should not delay airway planning in a clinically unstable or highly concerning patient.","The toxic appearance, drooling, tripod posture, and muffled voice are not routine croup findings."],
"The senior decision is often what not to do: do not destabilize a tenuous pediatric airway just to obtain a prettier exam.","What backup airway equipment and personnel should be immediately available during controlled intubation?","overnight_call"),

# LARYNGOLOGY — Tracheobronchial Endoscopy Principles
_c("v154_lar_fnd",L,"Tracheobronchial Endoscopy Principles","foundation",
"Why is rigid bronchoscopy commonly preferred for removal of a large pediatric airway foreign body?",
["It permits airway control, ventilation, and passage of retrieval instruments through a shared working lumen","It requires no anesthesia","It cannot cause airway trauma","Flexible bronchoscopy cannot visualize the tracheobronchial tree"],0,
"Rigid bronchoscopy provides a controlled airway, allows ventilation during the procedure, and accommodates robust retrieval instruments, making it the standard therapeutic approach for many pediatric airway foreign bodies.",
["Correct.","Rigid bronchoscopy generally requires general anesthesia and close coordination with anesthesia.","Rigid instrumentation can cause trauma, bleeding, edema, or perforation if poorly controlled.","Flexible bronchoscopy can visualize the airway and may be useful diagnostically or in selected situations, but it does not replace rigid bronchoscopy's therapeutic advantages for many foreign bodies."],
"Know why the instrument is chosen before learning how to rescue complications.","What preoperative history makes an aspirated foreign body likely even when the chest x-ray is normal?","boards"),
_c("v154_lar_app",L,"Tracheobronchial Endoscopy Principles","application",
"During rigid bronchoscopy, a smooth foreign body repeatedly slips from the forceps as it is drawn through the glottis. Which principle should guide the next attempt?",
["Optimize visualization and instrument purchase, orient the object for the narrowest safe extraction profile, and coordinate withdrawal with anesthesia","Keep making blind forceps passes until something is caught","Crush every foreign body into fragments","Remove the bronchoscope and abandon airway control"],0,
"Foreign-body extraction should be controlled and visualized. Instrument selection, orientation, and coordinated passage through the glottis reduce distal migration and mucosal trauma while maintaining a ventilating airway.",
["Correct.","Blind passes risk pushing the object distally, causing bleeding, or injuring the airway.","Fragmentation can create multiple distal foreign bodies and is not a universal solution.","Abandoning the ventilating bronchoscope removes the airway-control advantage of the procedure."],
"Successful bronchoscopy is not just finding the object; it is planning the safest route out.","How does a friable organic foreign body change extraction strategy?","OR_prep"),
_c("v154_lar_snr",L,"Tracheobronchial Endoscopy Principles","senior_decision",
"During extraction, the child suddenly desaturates, ventilation through the bronchoscope becomes poor, and chest excursion is asymmetric. What is the immediate priority?",
["Stop extraction attempts and re-establish effective oxygenation/ventilation before resuming the procedure","Continue until the object is removed regardless of saturation","Obtain CT while the child remains hypoxemic","Perform repeated blind distal forceps passes"],0,
"Loss of ventilation ends the elective portion of shared-airway surgery. The team must restore a patent ventilating pathway and rapidly assess obstruction, migrated fragments, bronchospasm, bleeding, or pneumothorax before continuing extraction.",
["Correct.","Prolonged hypoxemia is more dangerous than temporarily abandoning object retrieval.","Imaging cannot precede stabilization in an actively hypoxemic child.","Blind distal passes can worsen obstruction and airway trauma while delaying ventilation."],
"The foreign body is the problem; oxygenation is the priority.","If high airway pressures and unilateral absent breath sounds persist after removal, what complication must you exclude immediately?","OR_prep"),

# FACIAL PLASTICS — Mandibular Biomechanics and Occlusion
_c("v154_fp_fnd",F,"Mandibular Biomechanics and Occlusion","foundation",
"Bilateral subcondylar fractures most classically produce which occlusal change?",
["Anterior open bite","Isolated posterior open bite on one side only","No possible occlusal change","Anterior crossbite from maxillary widening"],0,
"Bilateral loss of posterior ramus height allows the mandible to rotate, producing premature posterior contact and an anterior open bite.",
["Correct.","A unilateral condylar injury can create asymmetric occlusion, but bilateral height loss classically produces a symmetric anterior open bite.","Condylar fractures commonly alter ramus height and therefore occlusion.","The maxilla does not acutely widen because of mandibular condylar fractures."],
"Occlusion is a functional readout of mandibular geometry.","What bite change can a unilateral condylar fracture produce?","boards"),
_c("v154_fp_app",F,"Mandibular Biomechanics and Occlusion","application",
"A displaced mandibular body fracture is being reduced. What should be established before final plate fixation?",
["Reproducible premorbid occlusion and appropriate maxillomandibular relationship","Plate position alone regardless of the bite","Extraction of normal teeth to create space","Permanent maxillomandibular fixation before assessing reduction"],0,
"The teeth provide a functional reduction reference. Restoring premorbid occlusion and then confirming bony reduction prevents the surgeon from rigidly fixing a mandible in the wrong position.",
["Correct.","A well-positioned plate can still stabilize a malreduced mandible with a bad bite.","Healthy teeth are useful landmarks and should not be sacrificed simply to make an incorrect reduction fit.","Temporary fixation can help establish occlusion, but final reduction must still be assessed before committing to permanent fixation."],
"The bite is part of the reduction, not merely a postoperative outcome measure.","How do missing teeth or an edentulous mandible change your reduction references?","OR_prep"),
_c("v154_fp_snr",F,"Mandibular Biomechanics and Occlusion","senior_decision",
"After ORIF, the plates appear well seated but the patient has a new open bite when maxillomandibular fixation is released. What should happen before closure?",
["Re-establish the intended occlusion and reassess fracture reduction, condylar seating, and fixation","Accept the malocclusion because the hardware looks good","Plan delayed orthodontics without checking the reduction","Extract opposing teeth to camouflage the bite"],0,
"A new intraoperative malocclusion is evidence that the functional reduction is wrong until proven otherwise. The surgeon should correct the relationship before leaving the OR rather than converting an immediately fixable error into a secondary deformity.",
["Correct.","Hardware position is not a substitute for correct mandibular geometry and function.","Delayed orthodontics is inappropriate when the cause may be a surgically correctable malreduction now.","Tooth extraction masks the error instead of correcting the skeletal relationship."],
"A stable wrong bite is still a wrong operation.","Which intraoperative findings would make you suspect condylar malposition rather than body-fracture malreduction?","OR_prep"),

# SLEEP — Positional OSA
_c("v154_sleep_fnd",S,"Positional OSA","foundation",
"What feature defines a positional OSA phenotype?",
["Obstructive events are substantially more frequent or severe supine than nonsupine","AHI is identical in every body position","Only central apneas occur supine","Oxygen saturation is always normal"],0,
"Positional OSA describes clinically meaningful worsening of obstructive events in the supine position compared with nonsupine sleep.",
["Correct.","Lack of positional difference argues against a positional phenotype.","Positional OSA concerns obstructive, not purely central, events.","Desaturation may or may not occur and is not the defining criterion."],
"Read position-specific PSG data, not just the overall AHI.","What anatomic mechanism commonly worsens supine obstruction?","boards"),
_c("v154_sleep_app",S,"Positional OSA","application",
"A patient has overall mild OSA, supine AHI 28, and nonsupine AHI 3. CPAP is poorly tolerated. Which treatment is especially reasonable to discuss?",
["Positional therapy with objective follow-up of efficacy and adherence","Multilevel airway surgery solely because the supine AHI is high","Supplemental oxygen as definitive treatment","No treatment because the overall AHI is mild"],0,
"A marked supine-nonsupine contrast identifies a phenotype in which positional therapy may substantially reduce disease burden, particularly when nonsupine AHI is low.",
["Correct.","The high supine AHI should be interpreted in context; the very low nonsupine AHI creates a nonoperative treatment opportunity.","Oxygen does not correct the upper-airway collapse mechanism and is not definitive therapy for uncomplicated positional OSA.","Mild overall disease can still be symptomatic and clinically relevant; treatment should reflect symptoms, comorbidity, and phenotype."],
"Phenotype can change treatment even when the overall AHI does not.","How would obesity or inability to avoid supine sleep affect expected success?","boards"),
_c("v154_sleep_snr",S,"Positional OSA","senior_decision",
"The same patient returns after a positional device. Download data show excellent adherence, but repeat testing shows nonsupine AHI has risen to 22. What should change?",
["Reclassify the problem as no longer predominantly positional and broaden definitive OSA treatment rather than escalating positional therapy alone","Add more positional devices until supine sleep is impossible","Declare treatment successful because the patient adhered","Treat with oxygen only"],0,
"Therapy should follow current physiology, not the original label. If substantial obstruction persists outside the supine position, positional therapy alone no longer addresses the dominant disease burden and the treatment plan should broaden.",
["Correct.","More positional restriction cannot fix severe nonsupine obstruction.","Adherence is not equivalent to physiologic efficacy.","Oxygen does not correct persistent pharyngeal collapse."],
"A phenotype is a measured state, not a permanent identity.","What additional anatomic or DISE information would help choose among PAP alternatives, oral appliance, HNS, or surgery?","boards"),

# GENERAL ENT — ENT Fluids / Electrolytes / Nutrition
_c("v154_gen_fnd",G,"ENT Fluids / Electrolytes / Nutrition","foundation",
"Which electrolyte abnormality is most characteristic and dangerous in refeeding syndrome?",
["Hypophosphatemia","Hypercalcemia","Isolated hypernatremia","Hypermagnesemia"],0,
"Refeeding increases insulin and drives phosphate, potassium, and magnesium intracellularly. Hypophosphatemia is particularly characteristic and can cause respiratory failure, weakness, arrhythmia, and neurologic dysfunction.",
["Correct.","Hypercalcemia is not the classic metabolic hallmark of refeeding.","Sodium abnormalities may occur but isolated hypernatremia is not the defining electrolyte shift.","Magnesium more often falls rather than rises during refeeding."],
"Think phosphate first when a severely malnourished patient deteriorates after feeding starts.","Why is thiamine supplementation also important?","boards"),
_c("v154_gen_app",G,"ENT Fluids / Electrolytes / Nutrition","application",
"A severely malnourished head-and-neck cancer patient is about to start tube feeds. Which prevention strategy is most appropriate?",
["Identify refeeding risk, give thiamine, check/correct phosphate-potassium-magnesium, and advance calories cautiously with close monitoring","Start full calories immediately without baseline labs","Avoid nutrition indefinitely","Give only normal saline regardless of nutritional state"],0,
"High-risk patients should have electrolyte and thiamine assessment before feeding, followed by cautious caloric advancement and close biochemical/clinical monitoring.",
["Correct.","Aggressive feeding can trigger dangerous intracellular electrolyte shifts in a depleted patient.","Avoiding nutrition does not solve malnutrition; the problem is how feeding is restarted.","IV crystalloid alone does not address protein-calorie malnutrition or prevent refeeding physiology."],
"Refeeding syndrome is best managed before it happens.","Which histories or objective markers place a patient in the highest-risk group?","boards"),
_c("v154_gen_snr",G,"ENT Fluids / Electrolytes / Nutrition","senior_decision",
"Twelve hours after feeds begin, phosphate falls sharply and the patient develops weakness, tachycardia, and ventricular ectopy. What is the immediate management priority?",
["Treat this as symptomatic refeeding syndrome: urgently replace deficits, give thiamine, slow or pause caloric advancement as appropriate, and monitor cardiopulmonary status closely","Increase calories because the patient is still malnourished","Ignore the phosphate because refeeding abnormalities are expected","Treat only with an IV fluid bolus"],0,
"Once symptomatic electrolyte shifts occur, the priority is stabilization and correction rather than continued caloric escalation. Severe hypophosphatemia can impair myocardial and respiratory muscle function and requires monitored treatment.",
["Correct.","More calories can intensify the insulin-driven shifts and worsen instability.","Expected does not mean benign; arrhythmia and weakness signal clinically important toxicity.","Volume alone does not correct phosphate, potassium, magnesium, or thiamine deficits."],
"The senior decision is recognizing when nutritional rehabilitation has become an acute metabolic emergency.","What respiratory finding would make ICU-level monitoring especially urgent?","overnight_call"),
]
