VIGNETTES_V128 = [{'id': 'v128_hn_01',
  'domain': 'Head & Neck Oncology',
  'topic': 'HPV-Positive Oropharyngeal Squamous Cell Carcinoma',
  'stem': 'A 58-year-old never-smoker has a p16-positive tonsil SCC measuring 3.2 cm with two ipsilateral level II nodes, neither larger than 6 cm, and no distant disease. Which staging principle is most important?',
  'choices': ['HPV-positive OPSCC uses a distinct AJCC staging system with downstaging relative to p16-negative disease', 'Any nodal disease makes this stage IV', 'p16 status has no staging relevance', 'Tonsil primaries are staged like oral cavity cancers'],
  'answer': 0,
  'explanation': 'AJCC 8 separates p16-positive oropharyngeal carcinoma because prognosis and nodal behavior differ substantially from p16-negative disease.',
  'why_wrong': ['Correct. p16-positive OPSCC has its own T/N stage groupings.', 'Nodal disease does not automatically mean stage IV in HPV-mediated OPSCC.', 'p16 is central to staging classification.', 'Oropharynx and oral cavity have different staging systems.'],
  'board_pearl': 'Always establish subsite and HPV/p16 status before assigning an oropharyngeal stage.',
  'curveball': 'How would the nodal classification differ if this were p16-negative OPSCC?',
  'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_02', 'domain': 'Head & Neck Oncology', 'topic': 'Unknown Primary Squamous Cell Carcinoma',
  'stem': 'A patient presents with metastatic p16-positive SCC in a level II node and no visible mucosal primary on office exam. What is the best next diagnostic strategy?',
  'choices': ['Comprehensive mucosal evaluation with directed imaging and operative evaluation including palatine and lingual tonsil assessment', 'Immediate radical neck dissection only', 'Observe because the primary is usually never found', 'Treat as thyroid cancer until proven otherwise'], 'answer': 0,
  'explanation': 'Unknown-primary workup seeks an occult oropharyngeal source using imaging, endoscopic evaluation, and tonsillar tissue sampling when appropriate.',
  'why_wrong': ['Correct. The goal is to identify the primary and define treatment fields.', 'Neck surgery alone ignores the occult mucosal source.', 'Modern workup often identifies a primary, especially HPV-associated disease.', 'The cytology and nodal level are more consistent with mucosal SCC.'],
  'board_pearl': 'p16-positive cervical nodal SCC strongly focuses the search on the oropharynx.',
  'curveball': 'If palatine tonsillectomy is negative, what role does lingual tonsillectomy/base-of-tongue mucosectomy play?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_03', 'domain': 'Head & Neck Oncology', 'topic': 'Neck Dissection',
  'stem': 'During a selective neck dissection, which maneuver most directly places the spinal accessory nerve at risk in level IIb?',
  'choices': ['Clearing nodal tissue superior and posterior to the spinal accessory nerve', 'Dividing the omohyoid in level IV', 'Identifying the facial artery in level I', 'Ligation of the superior thyroid artery'], 'answer': 0,
  'explanation': 'Level IIb lies posterosuperior to CN XI. Retracting or skeletonizing the nerve to clear this basin can cause postoperative shoulder dysfunction.',
  'why_wrong': ['Correct. Level IIb dissection is the classic CN XI-risk zone.', 'This is not the key CN XI danger maneuver.', 'This is a level I landmark.', 'This is thyroid rather than level II neck anatomy.'],
  'board_pearl': 'Know the oncologic indication for IIb clearance because morbidity is largely CN XI-related.',
  'curveball': 'Which primary sites most strongly influence whether level IIb must be routinely included?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_04', 'domain': 'Head & Neck Oncology', 'topic': 'Laryngeal Cancer',
  'stem': 'Why do supraglottic cancers commonly present with cervical nodal disease earlier than small glottic cancers?',
  'choices': ['The supraglottis has richer lymphatic drainage whereas the true vocal folds have sparse lymphatics', 'The glottis drains directly to level V', 'Glottic tumors never metastasize', 'Supraglottic tumors are always larger at diagnosis'], 'answer': 0,
  'explanation': 'The supraglottis has abundant lymphatics with bilateral drainage potential; early glottic cancers have relatively sparse lymphatics.',
  'why_wrong': ['Correct. This anatomic difference drives nodal risk.', 'Level V is not the primary explanation.', 'Advanced glottic tumors can metastasize.', 'Tumor size alone does not explain the subsite difference.'],
  'board_pearl': 'Laryngeal subsite anatomy predicts nodal behavior and treatment fields.', 'curveball': 'How does subglottic extension change expected nodal basins?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_05', 'domain': 'Head & Neck Oncology', 'topic': 'Organ Preservation in Advanced Laryngeal Cancer',
  'stem': 'A patient with resectable advanced laryngeal SCC asks about nonsurgical organ preservation. Which lesson from RTOG 91-11 is most important?',
  'choices': ['Concurrent chemoradiation improved larynx preservation compared with induction chemotherapy followed by RT or RT alone, at the cost of greater toxicity', 'Chemoradiation eliminated the need for salvage laryngectomy', 'Induction chemotherapy was superior for larynx preservation', 'Radiation alone was equivalent in all endpoints'], 'answer': 0,
  'explanation': 'RTOG 91-11 established concurrent chemoradiation as a major organ-preservation strategy, but functional outcomes, toxicity, and salvage needs remain crucial.',
  'why_wrong': ['Correct. Larynx preservation improved, but treatment selection is nuanced.', 'Salvage surgery remains necessary for persistent/recurrent disease.', 'Induction was not superior for larynx preservation.', 'RT alone was not equivalent for the key preservation endpoint.'],
  'board_pearl': '“Organ preservation” does not guarantee normal laryngeal function.', 'curveball': 'Which patients are poor candidates for nonsurgical preservation despite technical resectability?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_06', 'domain': 'Head & Neck Oncology', 'topic': 'Cutaneous Squamous Cell Carcinoma',
  'stem': 'Which feature most strongly increases concern that a head and neck cutaneous SCC is biologically high risk?',
  'choices': ['Perineural invasion', 'A well-defined 4-mm lesion on the trunk', 'Young age alone', 'Absence of ulceration'], 'answer': 0,
  'explanation': 'Perineural invasion is a major adverse feature associated with recurrence, nodal spread, and need for intensified treatment planning.',
  'why_wrong': ['Correct. PNI materially changes risk.', 'This is not a classic high-risk H&N feature.', 'Age alone is not sufficient.', 'Absence of ulceration is not a high-risk feature.'],
  'board_pearl': 'High-risk cSCC assessment integrates size, depth, site, differentiation, immunosuppression, nerve involvement, and margin status.', 'curveball': 'What imaging finding suggests clinically significant perineural spread rather than microscopic PNI alone?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_07', 'domain': 'Head & Neck Oncology', 'topic': 'Osteoradionecrosis',
  'stem': 'A patient develops exposed mandibular bone months after head and neck radiotherapy, with pain and nonhealing mucosa but no recurrent tumor. What diagnosis is most likely?',
  'choices': ['Osteoradionecrosis', 'Bisphosphonate-related osteonecrosis by definition', 'Acute bacterial osteomyelitis only', 'Normal post-radiation change'], 'answer': 0,
  'explanation': 'Persistent irradiated devitalized bone without tumor recurrence is classic for osteoradionecrosis; infection may be secondary rather than primary.',
  'why_wrong': ['Correct. Timing and radiation history fit ORN.', 'Medication-related necrosis requires the relevant drug exposure.', 'Infection may coexist but does not fully explain the syndrome.', 'Persistent exposed painful bone is not normal.'],
  'board_pearl': 'Always exclude recurrent malignancy before labeling a destructive post-radiation lesion ORN.', 'curveball': 'Which disease features push management toward segmental resection and vascularized reconstruction?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_08', 'domain': 'Head & Neck Oncology', 'topic': 'Salvage Surgery After Radiation',
  'stem': 'A patient undergoes salvage total laryngectomy after prior chemoradiation. Which postoperative complication deserves especially strong anticipatory counseling?',
  'choices': ['Pharyngocutaneous fistula', 'Acute otitis externa', 'BPPV', 'Thyroid storm in every case'], 'answer': 0,
  'explanation': 'Previously irradiated tissues heal poorly, and salvage laryngectomy carries a substantially increased pharyngocutaneous fistula risk.',
  'why_wrong': ['Correct. Prior radiation is a major wound-healing risk.', 'Unrelated to the operation.', 'Unrelated to the operation.', 'Thyroid storm is not an expected routine complication.'],
  'board_pearl': 'Prior radiation changes reconstructive strategy because vascularized tissue can be used prophylactically in high-risk salvage cases.', 'curveball': 'When might a pectoralis or free-tissue onlay be considered to reduce fistula risk?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_09', 'domain': 'Head & Neck Oncology', 'topic': 'Adjuvant Therapy After Head and Neck Cancer Surgery',
  'stem': 'After resection of oral cavity SCC, pathology shows a positive margin and extranodal extension. Which adjuvant approach is most strongly supported?',
  'choices': ['Postoperative concurrent chemoradiation', 'Observation only', 'Radiation only regardless of fitness', 'Immunotherapy alone as standard'], 'answer': 0,
  'explanation': 'Positive margins and extranodal extension are classic high-risk features supporting postoperative concurrent chemoradiation in eligible patients.',
  'why_wrong': ['Correct. These are the highest-risk pathologic triggers.', 'Observation is inadequate.', 'RT alone may be used when chemotherapy is contraindicated but is not the preferred standard in a fit patient with these features.', 'Immunotherapy alone is not the standard adjuvant replacement here.'],
  'board_pearl': 'Separate adverse features that support RT from positive margin and ENE, which support concurrent chemotherapy.', 'curveball': 'What other pathologic findings may justify adjuvant radiation without necessarily requiring chemotherapy?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_hn_10', 'domain': 'Head & Neck Oncology', 'topic': 'Nasopharyngeal Carcinoma',
  'stem': 'A patient has a nasopharyngeal mass with bilateral cervical adenopathy. Which tumor association is classically important in endemic nonkeratinizing nasopharyngeal carcinoma?',
  'choices': ['Epstein-Barr virus', 'HPV exclusively', 'RET mutation', 'BRAF V600E as the defining driver'], 'answer': 0,
  'explanation': 'EBV is strongly associated with nonkeratinizing nasopharyngeal carcinoma and has diagnostic and surveillance relevance in appropriate settings.',
  'why_wrong': ['Correct. EBV is the classic association.', 'HPV can be relevant in selected tumors but is not the defining classic association.', 'RET is associated with medullary thyroid carcinoma.', 'BRAF is not the defining driver of NPC.'],
  'board_pearl': 'Nasopharyngeal carcinoma has distinct biology, nodal patterns, and treatment compared with other mucosal H&N SCC.', 'curveball': 'What is the role of plasma EBV DNA in contemporary disease assessment where validated?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_01', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Vocal Fold Nodules, Polyps, and Cysts',
  'stem': 'A singer has bilateral symmetric mid-membranous lesions at the striking zone with an hourglass glottic gap. What is the most likely diagnosis?',
  'choices': ['Vocal fold nodules', 'Unilateral polyp', 'Vocal fold cyst', 'Posterior granuloma'], 'answer': 0,
  'explanation': 'Bilateral symmetric mid-membranous lesions at the point of maximal collision are classic for nodules.',
  'why_wrong': ['Correct. Symmetry and location are key.', 'Polyps are usually unilateral.', 'Cysts are usually unilateral subepithelial lesions with impaired wave over the lesion.', 'Granulomas arise posteriorly near the vocal process.'],
  'board_pearl': 'For benign phonotraumatic lesions, laterality and exact location are often the fastest discriminator.', 'curveball': 'How would stroboscopic mucosal-wave behavior differ for a cyst versus a polyp?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_02', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Vocal Fold Nodules, Polyps, and Cysts',
  'stem': 'A patient has a unilateral pedunculated hemorrhagic lesion on the free edge of the mid-membranous vocal fold after heavy voice use. Which diagnosis best fits?',
  'choices': ['Vocal fold polyp', 'Bilateral nodules', 'Sulcus vocalis', 'Posterior glottic stenosis'], 'answer': 0,
  'explanation': 'A unilateral exophytic or hemorrhagic mid-membranous lesion after phonotrauma is typical of a polyp.',
  'why_wrong': ['Correct. This is the classic polyp pattern.', 'Nodules are usually bilateral and symmetric.', 'Sulcus is a linear epithelial invagination/scar pattern.', 'PGS is a posterior airway fixation disorder.'],
  'board_pearl': 'Do not collapse nodules, polyps, and cysts into one category; morphology and mucosal-wave behavior matter.', 'curveball': 'What initial management is appropriate before considering phonomicrosurgery?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_03', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Vocal Fold Nodules, Polyps, and Cysts',
  'stem': 'Stroboscopy shows a unilateral subepithelial rounded lesion with markedly reduced mucosal wave directly over the lesion. Which diagnosis is favored?',
  'choices': ['Vocal fold cyst', 'Reinke edema', 'Bilateral nodules', 'Presbyphonia'], 'answer': 0,
  'explanation': 'A cyst is typically a subepithelial mass with focal stiffness and reduced or absent wave over the lesion.',
  'why_wrong': ['Correct. Focal wave loss is highly suggestive.', 'Reinke edema is diffuse and usually bilateral.', 'Nodules are bilateral symmetric lesions.', 'Presbyphonia is characterized by atrophy and bowing.'],
  'board_pearl': 'Focal mucosal-wave loss should make you think of a stiff subepithelial lesion or scar.', 'curveball': 'Why can aggressive excision worsen voice even when the cyst is completely removed?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_04', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Reinke Edema',
  'stem': 'A long-term smoker has a deep low-pitched voice. Laryngoscopy shows bilateral diffuse polypoid swelling of the membranous vocal folds. What is the most likely diagnosis?',
  'choices': ['Reinke edema', 'Vocal fold nodules', 'Spasmodic dysphonia', 'Unilateral paresis'], 'answer': 0,
  'explanation': 'Bilateral diffuse gelatinous expansion of the superficial lamina propria in a smoker is classic Reinke edema.',
  'why_wrong': ['Correct. The appearance and smoking history fit.', 'Nodules are focal striking-zone lesions.', 'Spasmodic dysphonia is a task-specific dystonia without this mass lesion.', 'Paresis causes motion or tone abnormalities rather than diffuse polypoid edema.'],
  'board_pearl': 'Smoking cessation is part of treatment, not merely counseling around treatment.', 'curveball': 'What airway consideration matters when disease is massive and surgery is planned?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_05', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Presbyphonia',
  'stem': 'An older adult has weak breathy voice. Stroboscopy shows bilateral vocal fold bowing with a spindle-shaped glottic gap and otherwise symmetric motion. What is the best diagnosis?',
  'choices': ['Presbyphonia from vocal fold atrophy', 'Unilateral recurrent laryngeal nerve paralysis', 'Adductor spasmodic dysphonia', 'Posterior glottic stenosis'], 'answer': 0,
  'explanation': 'Age-related atrophy causes bilateral bowing and glottic insufficiency, producing weak breathy voice.',
  'why_wrong': ['Correct. Bilateral bowing with preserved motion is typical.', 'Paralysis would cause asymmetric motion and position.', 'Adductor SD produces task-specific strained breaks.', 'PGS causes posterior fixation and airway symptoms.'],
  'board_pearl': 'Differentiate atrophy from paresis by symmetry, motion, tone, and closure pattern.', 'curveball': 'When is injection augmentation reasonable for symptomatic presbyphonia?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_06', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Muscle Tension Dysphonia',
  'stem': 'A teacher has fluctuating dysphonia worsened by voice use. Laryngoscopy shows supraglottic hyperfunction without a structural lesion or neurologic motion abnormality. What is the best initial treatment?',
  'choices': ['Voice therapy', 'Immediate type I thyroplasty', 'Botulinum toxin to the PCA', 'Total voice rest for months'], 'answer': 0,
  'explanation': 'Primary muscle tension dysphonia is treated first with behavioral voice therapy and correction of contributing vocal behaviors.',
  'why_wrong': ['Correct. Therapy targets maladaptive hyperfunction.', 'Thyroplasty treats selected glottic insufficiency.', 'PCA Botox is used for abductor spasmodic dysphonia.', 'Prolonged total voice rest is not standard definitive therapy.'],
  'board_pearl': 'Hyperfunction may be primary or compensatory; look for an underlying lesion or glottic insufficiency before calling it primary MTD.', 'curveball': 'How would your plan change if a subtle unilateral paresis were driving the compensatory squeeze?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_07', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Posterior Glottic Stenosis',
  'stem': 'After prolonged intubation, a patient has stridor and bilateral vocal folds that appear immobile near midline. Which finding best distinguishes posterior glottic stenosis from bilateral RLN paralysis?',
  'choices': ['Restricted cricoarytenoid joint mobility with posterior interarytenoid scar', 'Normal passive arytenoid mobility under anesthesia', 'Absent posterior scar in every case', 'Normal airway symptoms'], 'answer': 0,
  'explanation': 'Posterior glottic stenosis is a mechanical fixation problem, often from interarytenoid scarring and cricoarytenoid joint involvement; passive mobility testing is central.',
  'why_wrong': ['Correct. Mechanical fixation is the key discriminator.', 'Normal passive mobility favors neurogenic paralysis rather than fixation.', 'Posterior scar may be subtle but is common after intubation injury.', 'Both conditions can produce severe airway symptoms.'],
  'board_pearl': 'If bilateral “paralysis” follows intubation, prove whether the joints move before assuming a neurogenic lesion.', 'curveball': 'What role can laryngeal EMG play when the distinction remains uncertain?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_08', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Idiopathic Subglottic Stenosis',
  'stem': 'A healthy middle-aged woman with no intubation history develops progressive exertional dyspnea and fixed upper-airway obstruction. Endoscopy shows a circumferential subglottic scar. Which diagnosis is classic?',
  'choices': ['Idiopathic subglottic stenosis', 'Bilateral vocal fold paralysis', 'Exercise-induced laryngeal obstruction only', 'Tracheomalacia'], 'answer': 0,
  'explanation': 'Idiopathic subglottic stenosis classically affects otherwise healthy adult women and is a diagnosis reached after excluding traumatic, inflammatory, infectious, and other causes.',
  'why_wrong': ['Correct. Demographics and lesion pattern are classic.', 'The lesion is below the glottis and structurally stenotic.', 'EILO is dynamic, not a fixed circumferential scar.', 'Tracheomalacia is dynamic collapse rather than fixed scar.'],
  'board_pearl': '“Idiopathic” is an exclusion diagnosis; ask about intubation, autoimmune disease, reflux context, and systemic symptoms.', 'curveball': 'Which systemic disease must be considered when subglottic stenosis is accompanied by sinonasal and pulmonary findings?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_09', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Vocal Fold Scar / Sulcus Vocalis',
  'stem': 'A patient has persistent rough breathy dysphonia despite a nearly normal-appearing vocal fold edge. Stroboscopy shows a focal segment with poor mucosal wave and tethering. What diagnosis should be considered?',
  'choices': ['Vocal fold scar or sulcus vocalis', 'Normal exam', 'BPPV', 'Acute epiglottitis'], 'answer': 0,
  'explanation': 'Scar and sulcus can be visually subtle on routine laryngoscopy but cause focal stiffness, tethering, and impaired mucosal wave on stroboscopy.',
  'why_wrong': ['Correct. The key is abnormal vibratory function despite subtle surface findings.', 'A focal absent wave is not normal.', 'Unrelated vestibular disease.', 'The clinical picture is not infectious airway disease.'],
  'board_pearl': 'A “normal-looking” fold can still be mechanically abnormal; stroboscopy is essential when voice and appearance do not match.', 'curveball': 'Why are surgical outcomes for vocal fold scar less predictable than for a simple polyp?', 'tier': 'Curated board-style', 'mode': 'Board vignette'},
 {'id': 'v128_lar_10', 'domain': 'Laryngology / Voice / Swallowing', 'topic': 'Paradoxical Vocal Fold Motion / Inducible Laryngeal Obstruction',
  'stem': 'A young athlete has episodic inspiratory stridor during intense exercise, rapid resolution after stopping, normal baseline spirometry, and inspiratory vocal fold adduction during symptoms. What is the best diagnosis?',
  'choices': ['Inducible laryngeal obstruction / paradoxical vocal fold motion', 'Exercise-induced asthma only', 'Bilateral RLN paralysis', 'Subglottic stenosis'], 'answer': 0,
  'explanation': 'Dynamic inappropriate adduction during inspiration, especially when directly observed during symptoms, supports inducible laryngeal obstruction.',
  'why_wrong': ['Correct. The dynamic laryngoscopic finding is diagnostic.', 'Asthma may coexist but does not explain inspiratory vocal fold adduction.', 'Paralysis is persistent rather than episodic.', 'Fixed stenosis does not resolve immediately after exercise.'],
  'board_pearl': 'Inspiratory noise and rapid symptom resolution should prompt consideration of ILO, especially when asthma treatment fails.', 'curveball': 'What behavioral therapy is typically first-line, and when is continuous laryngoscopy during exercise useful?', 'tier': 'Curated board-style', 'mode': 'Board vignette'}]
