"""v27.2 — General ENT / Emergencies deliberate ladder pass 4.

Five exact canonical high-risk consult concepts selected from the live inventory.
Existing adjacent content was reviewed first; these cases add General-ENT-specific
foundation, application, and senior-decision layers without relabeling completed
domain material. Choice-aligned rationales permit deterministic answer balancing.
"""
DOMAIN="General ENT / Emergencies"

def _q(qid,topic,stage,stem,choices,answer,exp,reasons,pearl,curveball,focus="boards"):
 return {"id":qid,"domain":DOMAIN,"topic":topic,"learning_stage":stage,"stem":stem,"choices":choices,"answer":answer,"explanation":exp,"why_wrong":reasons,"board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder","mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}

VIGNETTES_V272=[
_q("v272_gen_angio_fnd","Angioedema","foundation",
   "A patient develops rapidly progressive lip and tongue swelling without urticaria while taking an ACE inhibitor. Which mechanism and treatment principle are most important?",
   ["Suspect bradykinin-mediated angioedema; stop the ACE inhibitor and prioritize airway assessment because epinephrine, antihistamines, and steroids may not reliably reverse the process","Assume histamine-mediated allergy because all angioedema responds promptly to antihistamines","Observe at home because absence of hives excludes airway progression","Give an oral antibiotic because tongue swelling usually represents infection"],0,
   "ACE-inhibitor angioedema is classically bradykinin mediated and often lacks urticaria or pruritus. Standard anaphylaxis medications may be given when the mechanism is uncertain, but they cannot substitute for serial airway assessment and early airway planning when tongue, floor-of-mouth, or laryngeal involvement is progressing.",
   ["Correct. Bradykinin-mediated disease can progress despite conventional allergy medications, so airway trajectory drives management.","Histamine-mediated angioedema more often accompanies urticaria/pruritus and responds to standard anaphylaxis therapy; ACE-inhibitor disease may not.","Absence of hives does not protect the larynx, and progression can be abrupt.","Angioedema is not primarily a bacterial infection and should not be managed as one."],
   "In angioedema, phenotype the mediator—but manage the airway trajectory before the laboratory mechanism is settled.",
   "Which symptoms or flexible-laryngoscopy findings should move you toward controlled early intubation?","overnight_call"),
_q("v272_gen_angio_app","Angioedema","application",
   "A patient with progressive tongue and floor-of-mouth edema develops muffled voice and increasing work of breathing. Flexible laryngoscopy shows supraglottic edema, but oxygen saturation is still normal. What is the best next step?",
   ["Mobilize an experienced difficult-airway team for early controlled airway management while the patient is still oxygenating, with a surgical-airway rescue plan immediately available","Wait for oxygen saturation to fall before escalating","Attempt repeated sedating oral examinations until the airway anatomy is clearer","Send the patient unmonitored to CT before airway planning"],0,
   "Normal saturation is a late and unreliable reassurance in a mechanically narrowing upper airway. Progressive symptoms plus laryngeal involvement favor securing the airway under controlled conditions before edema, agitation, or hypoxemia turns a difficult airway into a crash airway.",
   ["Correct. The safest airway is often the one secured before physiologic collapse, with ENT/anesthesia and front-of-neck rescue prepared.","Desaturation may occur only after critical narrowing and leaves far less margin for a difficult intubation.","Sedation can reduce airway tone and precipitate obstruction in a marginal airway.","Transport away from airway resources is unsafe when the airway is visibly progressing."],
   "Do not use pulse oximetry as the severity monitor for a progressively closing upper airway.",
   "How would known hereditary angioedema alter disease-specific rescue therapy while airway management proceeds?","overnight_call"),
_q("v272_gen_angio_snr","Angioedema","senior_decision",
   "A patient with severe angioedema has worsening supraglottic edema despite medical therapy. Mouth opening is limited, the tongue fills the oral cavity, and anatomy suggests conventional laryngoscopy will be difficult. What is the best senior decision framework?",
   ["Choose the most controlled awake or minimally destabilizing airway strategy feasible with expert personnel, preserve spontaneous ventilation when appropriate, and have immediate surgical airway capability rather than inducing apnea without a rescue plan","Perform routine rapid-sequence induction because paralysis always improves an edematous airway","Delay intervention until stridor becomes continuous","Rely on repeated nebulized therapy as the definitive airway plan"],0,
   "The senior decision is not simply which device to use; it is how to avoid converting a tenuous but spontaneously ventilating patient into a cannot-intubate/cannot-oxygenate emergency. Technique must match anatomy, operator expertise, patient cooperation, and the availability of immediate front-of-neck rescue.",
   ["Correct. Controlled airway strategy and rescue planning are central when edema makes loss of spontaneous ventilation hazardous.","Paralysis can remove the remaining airway tone and eliminate spontaneous ventilation before a definitive airway is secured.","Stridor is a late sign and waiting for it sacrifices safety margin.","Adjunctive medications do not replace a definitive plan when progressive laryngeal edema threatens ventilation."],
   "For the senior resident, the key question is not 'Can I intubate?' but 'What happens if my first airway plan fails after I remove spontaneous ventilation?'",
   "When would an awake tracheostomy be preferable to transoral or transnasal intubation?","senior_decision"),

_q("v272_gen_cbs_fnd","Carotid Blowout Syndrome","foundation",
   "A previously irradiated head-and-neck cancer patient has a small self-limited episode of bright-red bleeding from the pharynx and exposed necrotic tissue near the carotid axis. How should this bleed be interpreted?",
   ["Treat it as a sentinel hemorrhage from threatened carotid blowout until proven otherwise and escalate urgently for airway, vascular, and definitive hemorrhage planning","Reassure the patient because the bleeding stopped spontaneously","Assume minor mucosal trauma because carotid rupture is always immediately fatal","Schedule routine clinic follow-up after prescribing topical saline"],0,
   "Carotid blowout exists on a spectrum from threatened vessel exposure to sentinel bleeding to active rupture. Prior radiation, surgery, infection, fistula, recurrent tumor, and exposed vessel dramatically increase risk; a self-limited herald bleed can precede catastrophic hemorrhage.",
   ["Correct. A sentinel bleed in a high-risk field is an emergency warning, not a benign endpoint.","Temporary hemostasis may reflect clot formation over an unstable arterial defect.","Carotid blowout can present with smaller warning bleeds before free rupture.","Routine outpatient care is inappropriate when a major arterial catastrophe is plausible."],
   "The bleed that stops is sometimes the only warning you get before the bleed that does not.",
   "Which history and wound findings should make you suspect threatened carotid blowout even before hemorrhage occurs?","overnight_call"),
_q("v272_gen_cbs_app","Carotid Blowout Syndrome","application",
   "A patient with recurrent neck cancer suddenly develops brisk pulsatile oropharyngeal bleeding. What is the best immediate management framework?",
   ["Activate massive-hemorrhage and difficult-airway resources, use suction and direct pressure or packing when feasible as a temporizing maneuver, resuscitate with blood products, and obtain urgent endovascular or surgical source control","Send the patient alone for routine outpatient CTA","Blindly clamp deep in the irradiated neck at bedside","Wait for hemoglobin to decline before transfusing or escalating"],0,
   "Active carotid blowout is simultaneously an airway, exsanguination, and source-control emergency. Temporizing compression or packing may buy time, but definitive control usually requires rapid vascular/endovascular coordination; early hemoglobin can underestimate acute blood loss.",
   ["Correct. Airway protection, hemorrhage resuscitation, temporization, and definitive vascular control must occur in parallel.","Diagnostic transport without stabilization or a rescue plan can be fatal during active major-vessel bleeding.","Blind deep clamping in a distorted irradiated field risks nerve, vessel, and airway injury and may worsen hemorrhage.","Hemodynamic trajectory and active blood loss—not a delayed laboratory change—determine urgency."],
   "Carotid blowout is a parallel-processing emergency: airway, blood, pressure, and vascular control all start together.",
   "How does an open pharyngocutaneous fistula alter where and how you can safely tamponade bleeding?","overnight_call"),
_q("v272_gen_cbs_snr","Carotid Blowout Syndrome","senior_decision",
   "Angiography confirms an extracranial carotid pseudoaneurysm causing sentinel hemorrhage in an irradiated neck. What is the key senior-level treatment tradeoff?",
   ["Balance vessel-preserving endovascular reconstruction against arterial sacrifice based on anatomy, infection/contamination, cerebral collateral tolerance, recurrence risk, and the urgency of durable hemorrhage control","Always sacrifice the carotid because covered stents are never appropriate","Always place a covered stent because arterial sacrifice has no role","Choose treatment only by the size of the external wound"],0,
   "Definitive carotid-blowout management is individualized. Covered stents can preserve flow when sacrifice is unsafe but carry thrombosis, infection, and rebleeding concerns in contaminated fields; embolization or vessel sacrifice may be durable when cerebral collateral circulation can tolerate it. Multidisciplinary vascular/neurointerventional planning is essential.",
   ["Correct. The central decision is durable hemorrhage control while managing stroke risk and the hostile wound environment.","Sacrifice may produce devastating cerebral ischemia in patients without adequate collateral circulation.","Stent-grafts are not universally durable, particularly across infected, exposed, or tumor-involved tissue.","Surface wound appearance alone does not define intracranial collateral risk or endovascular anatomy."],
   "The senior tradeoff is hemorrhage versus stroke—and the irradiated infected field changes both sides of that equation.",
   "What postoperative neurologic and rebleeding surveillance is required after endovascular control?","senior_decision"),

_q("v272_gen_eso_perf_fnd","Esophageal Perforation / Cervical Mediastinitis","foundation",
   "After difficult rigid esophagoscopy for an impacted foreign body, a patient develops severe neck pain, crepitus, fever, and tachycardia. What diagnosis and first evaluation should be prioritized?",
   ["Suspect cervical esophageal perforation; keep the patient NPO, begin broad IV antimicrobial therapy/resuscitation, and urgently define the leak and deep-space extent with appropriate contrast imaging while involving surgical teams","Treat this as routine post-procedure odynophagia and discharge","Give an oral diet to see whether swallowing reproduces symptoms","Delay treatment until blood cultures become positive"],0,
   "Pain out of proportion, subcutaneous emphysema, fever, and systemic toxicity after instrumentation are red flags for perforation. Early NPO status, antibiotics, resuscitation, imaging, and source-control planning matter because contamination can track through the neck into the mediastinum.",
   ["Correct. Suspected perforation is a time-sensitive contamination emergency requiring immediate stabilization and anatomic definition.","Crepitus and systemic signs are not expected uncomplicated postoperative symptoms.","Oral intake can worsen contamination through an active leak.","Negative or pending cultures do not justify delaying empiric treatment of a potentially lethal perforation."],
   "After esophageal instrumentation, crepitus plus toxicity is a perforation until proven otherwise.",
   "Which imaging findings suggest a contained cervical leak versus free mediastinal contamination?","overnight_call"),
_q("v272_gen_eso_perf_app","Esophageal Perforation / Cervical Mediastinitis","application",
   "CT after cervical esophageal perforation shows an enlarging paraesophageal collection, mediastinal air, pleural fluid, and persistent sepsis despite antibiotics. What is the best next step?",
   ["Escalate to urgent multidisciplinary source control—drain infected neck/mediastinal/pleural spaces as indicated, control the perforation, maintain broad antimicrobial therapy, and provide enteral or parenteral nutritional strategy that avoids the leak","Continue antibiotics alone because all cervical perforations are managed nonoperatively","Start a regular diet to promote esophageal motility","Remove drains once output decreases briefly without reassessing the septic source"],0,
   "Nonoperative management is reserved for carefully selected stable contained leaks with minimal contamination and close surveillance. Sepsis, enlarging collections, mediastinal extension, or uncontrolled extravasation indicate failure of source control and require procedural escalation.",
   ["Correct. Persistent sepsis plus extending contamination demands drainage and control of the leak rather than medical therapy alone.","Location alone does not make a perforation safe for observation; physiology and containment determine candidacy.","Feeding across an uncontrolled perforation can worsen contamination.","Transient drain changes do not prove that all infected compartments or the leak are controlled."],
   "For perforation, 'cervical' does not mean benign; the danger space does not respect the clavicle.",
   "When is primary repair reasonable, and when might diversion, stenting, or drainage without primary closure be favored?","senior_decision"),
_q("v272_gen_eso_perf_snr","Esophageal Perforation / Cervical Mediastinitis","senior_decision",
   "A delayed esophageal perforation presents with septic shock, necrotic tissue, and descending mediastinal infection. What is the best senior management principle?",
   ["Prioritize repeated anatomic source control and physiologic resuscitation over a one-size-fits-all repair: debride/drain infected compartments, control ongoing contamination, coordinate thoracic/critical-care support, and choose repair or diversion based on tissue viability and defect characteristics","Perform a primary closure regardless of tissue viability","Avoid surgery because delayed presentation makes intervention futile","Treat only the neck because mediastinal infection will resolve once cervical antibiotics are started"],0,
   "Delayed perforation with necrosis and shock is fundamentally a source-control problem. Friable infected tissue may not hold a simple primary closure, and descending mediastinitis often requires drainage beyond the neck. Operative strategy must be individualized to defect size, location, tissue viability, contamination, and patient physiology.",
   ["Correct. Senior management integrates resuscitation with complete drainage/debridement and a repair strategy the tissues can actually support.","Suturing necrotic friable tissue can fail and perpetuate contamination.","Delay worsens prognosis but makes decisive source control more—not less—important when recovery remains possible.","Mediastinal and pleural infection are separate infected compartments that may require direct drainage."],
   "The operation is not 'close the hole'; it is 'stop ongoing contamination and drain every infected compartment.'",
   "What findings would make you plan serial washouts rather than expecting one operation to achieve durable control?","senior_decision"),

_q("v272_gen_lemierre_fnd","Lemierre Syndrome","foundation",
   "A previously healthy young adult develops severe pharyngitis followed several days later by fever, unilateral neck tenderness, and pleuritic chest pain with multiple peripheral pulmonary nodules. What diagnosis should be suspected?",
   ["Lemierre syndrome with septic internal-jugular thrombophlebitis and septic pulmonary emboli","Uncomplicated viral pharyngitis","Isolated community-acquired pneumonia unrelated to the neck","Simple muscular torticollis"],0,
   "The classic pattern is an oropharyngeal infection followed by septic thrombophlebitis of the internal jugular vein and metastatic infection, most often pulmonary. Fusobacterium necrophorum is a classic pathogen, although disease can be polymicrobial.",
   ["Correct. The sequence of pharyngeal infection, lateral neck findings, bacteremia/sepsis, and septic pulmonary lesions is highly characteristic.","Viral pharyngitis does not explain septic shock, jugular thrombosis, or metastatic pulmonary abscesses.","The simultaneous neck source and septic embolic pattern should not be separated into unrelated diagnoses.","Torticollis cannot account for systemic sepsis and pulmonary septic emboli."],
   "Think Lemierre when a sore throat gets better locally but the patient becomes systemically much sicker.",
   "Which imaging study best evaluates both the neck source and internal-jugular thrombosis?","boards"),
_q("v272_gen_lemierre_app","Lemierre Syndrome","application",
   "Contrast CT shows internal-jugular vein thrombosis with adjacent pharyngeal infection in a septic patient whose chest CT demonstrates cavitating septic emboli. What is the core management?",
   ["Start prompt IV antimicrobial therapy with reliable anaerobic coverage, culture blood/source sites, drain any accessible abscess or empyema, and provide sepsis support while individualizing anticoagulation","Treat with anticoagulation alone because the thrombus is the only source","Use a short oral macrolide course and discharge","Ligate the internal jugular vein routinely before giving antibiotics"],0,
   "Lemierre syndrome is an invasive infection first. Prolonged antimicrobial therapy and drainage of purulent collections are central. Anticoagulation remains individualized—often considered for propagation, intracranial extension, persistent septic thrombosis, or other selected scenarios rather than replacing infection control.",
   ["Correct. Infection eradication and source control are mandatory; anticoagulation is an adjunctive case-by-case decision.","Anticoagulation does not sterilize an infected thrombus or drain metastatic abscesses.","Septic thrombophlebitis with embolic disease requires inpatient IV therapy and source-control assessment.","Jugular ligation is now uncommon and reserved for exceptional uncontrolled septic embolization or hemorrhagic/source-control situations."],
   "Do not let the dramatic thrombus distract you from the primary pathology: this is septic thrombophlebitis.",
   "What clinical pattern would make you search for cavernous-sinus or other intracranial extension?","overnight_call"),
_q("v272_gen_lemierre_snr","Lemierre Syndrome","senior_decision",
   "A patient with Lemierre syndrome remains bacteremic and develops new septic pulmonary lesions after several days of appropriate antibiotics. What is the best senior response?",
   ["Reassess source control and disease extent: repeat targeted imaging, look for undrained neck/chest collections or thrombus propagation, confirm microbiology and antibiotic adequacy, and reconsider adjunctive anticoagulation or procedural intervention based on findings","Simply extend the same plan without reassessment because fever commonly lasts weeks","Stop antibiotics because persistent fever proves a drug reaction","Perform routine bilateral neck exploration without localization"],0,
   "Failure to improve should trigger a search for an uncontrolled source, metastatic focus, resistant/unexpected organism, or propagating septic thrombosis. Escalation is driven by anatomy and physiology rather than by a fixed recipe.",
   ["Correct. Persistent bacteremia or new emboli indicate failure of infection control until proven otherwise.","Some fever can persist, but ongoing bacteremia and new metastatic lesions are objective evidence that the current strategy may be inadequate.","Stopping therapy in active septic thrombophlebitis is dangerous without compelling evidence of drug toxicity and an alternative antimicrobial plan.","Unfocused surgery adds morbidity and may miss the actual undrained compartment."],
   "When septic emboli continue, ask what is still infected, still thrombosed, or still undrained.",
   "When would internal-jugular ligation or excision enter the discussion in modern practice?","senior_decision"),

_q("v272_gen_immuno_fnd","Immunocompromised Host in Otolaryngology","foundation",
   "A neutropenic patient receiving chemotherapy develops severe unilateral facial pain, fever, and a pale-insensate nasal turbinate. What principle should guide the ENT evaluation?",
   ["Assume an invasive opportunistic process such as acute invasive fungal rhinosinusitis until urgently excluded; obtain prompt endoscopic assessment and tissue diagnosis while initiating coordinated empiric therapy when suspicion is high","Reassure because neutropenic patients rarely mount dangerous sinonasal infections","Wait for black eschar because tissue necrosis must be visible before invasive fungal disease is possible","Treat as routine viral rhinitis with outpatient follow-up"],0,
   "Immunocompromised patients may have muted inflammatory findings yet rapidly progressive invasive infection. Severe focal pain, sensory change, necrosis or devitalized mucosa, cranial neuropathy, or orbital findings should trigger urgent endoscopic/tissue evaluation and multidisciplinary treatment rather than waiting for classic late eschar.",
   ["Correct. High-risk host plus focal invasive features demands urgent evaluation because delay increases orbital, vascular, and intracranial spread.","Neutropenia increases risk and can blunt visible inflammation rather than protect against infection.","Black eschar is a late and insensitive threshold for action.","Routine outpatient management is unsafe with focal ischemic/neurologic signs in a profoundly immunocompromised host."],
   "In the immunocompromised host, absence of pus or leukocytosis is not absence of invasive infection.",
   "Which bedside cranial-nerve and orbital findings should be documented before the patient leaves the ED for imaging or OR?","overnight_call"),
_q("v272_gen_immuno_app","Immunocompromised Host in Otolaryngology","application",
   "A solid-organ transplant recipient presents with fever, odynophagia, deep neck pain, and subtle swelling. CT suggests a small retropharyngeal phlegmon without a mature abscess, but the patient is becoming septic. What is the best approach?",
   ["Treat the host and physiology as high risk: admit, obtain cultures, start appropriately broad empiric therapy based on immune defect/exposures and local resistance, perform serial airway examinations, and reassess early for evolving drainable infection or atypical pathogen","Discharge because there is no rim-enhancing abscess","Use the same narrow outpatient regimen used for uncomplicated pharyngitis","Delay antimicrobials until a surgical specimen can be obtained"],0,
   "In immunocompromised patients, anatomy can evolve quickly and microbiology is broader. Lack of a mature abscess on the first scan does not neutralize sepsis. Management requires early treatment, airway surveillance, microbiologic sampling when feasible, and a low threshold for repeat imaging or source control if physiology worsens.",
   ["Correct. The combination of impaired host defense and sepsis justifies inpatient treatment and active reassessment even before a drainable collection forms.","A phlegmon can progress and sepsis itself requires hospital-level care.","Immune defects, prior antimicrobials, healthcare exposure, and opportunistic organisms may make narrow routine therapy inadequate.","Cultures are valuable, but clinically significant sepsis should not wait for perfect sampling before empiric therapy begins."],
   "In immunocompromised ENT infections, the first CT is a time point—not a guarantee that an abscess will not declare itself hours later.",
   "How should recent neutropenia, transplant immunosuppression, HIV status, or chronic steroids change your pathogen differential?","overnight_call"),
_q("v272_gen_immuno_snr","Immunocompromised Host in Otolaryngology","senior_decision",
   "An immunocompromised patient with a head-and-neck infection worsens despite broad empiric therapy and initial drainage. What is the best senior-level next move?",
   ["Re-phenotype the failure rather than reflexively adding drugs: reassess airway and source control, repeat imaging/endoscopy when indicated, obtain tissue for bacterial/fungal/mycobacterial pathology and culture, review immune defect and drug exposures, and narrow or redirect therapy from those data","Continue the same regimen indefinitely because treatment failure is expected in immunosuppression","Add every available antimicrobial without obtaining further diagnostic material","Assume the deterioration is solely due to immunosuppression and avoid repeat procedures"],0,
   "Persistent deterioration can reflect incomplete drainage, invasive fungal or mycobacterial disease, resistant bacteria, viral ulcerative disease, malignancy, drug toxicity, or noninfectious inflammatory mimics. Senior care requires renewed localization and tissue diagnosis rather than unstructured antimicrobial accumulation.",
   ["Correct. Failure is a diagnostic and source-control signal; targeted tissue and repeat localization often matter more than indiscriminate antimicrobial escalation.","Expected slower recovery does not explain objective progression, persistent shock, or new invasive findings.","Unstructured polypharmacy increases toxicity and interactions while potentially missing the actual organism or noninfectious diagnosis.","Immunosuppression raises the need for repeat source-control assessment rather than making procedures categorically inappropriate."],
   "When the immunocompromised patient fails therapy, ask whether the diagnosis, organism, compartment, or immune state was wrong—not just whether the antibiotic dose was too low.",
   "When should reduction of immunosuppression be discussed, and which service must be involved before changing it?","senior_decision"),
]

def apply_learning_ladders_v272(challenges,item_id_fn):
 existing={str(q.get("id")) for q in challenges if q.get("id")}; added=0
 for q in VIGNETTES_V272:
  if q["id"] in existing: continue
  row=dict(q); row["concept_id"]=item_id_fn(DOMAIN,row["topic"])
  if not row["concept_id"]: raise RuntimeError(f"v272 orphan topic {row['topic']}")
  challenges.append(row); existing.add(row["id"]); added+=1
 return {"added":added,"topics":sorted({q["topic"] for q in VIGNETTES_V272})}
