"""v24.7 — Pediatric Otolaryngology deliberate ladder pass 7.

Five exact remaining canonical topics selected for resident/chief-level value:
congenital hearing-loss genetics, cleft surgical fundamentals, pediatric head and
neck tumors, microtia reconstruction, and ankyloglossia/maxillary frenulum.
The senior layer prioritizes decisions that change surveillance, airway safety,
operative planning, reconstruction sequencing, or escalation rather than trivia.
"""
DOMAIN="Pediatric Otolaryngology"


def _q(qid,topic,stage,stem,choices,answer,explanation,reasons,pearl,curveball,focus="boards"):
    return {"id":qid,"domain":DOMAIN,"topic":topic,"learning_stage":stage,"stem":stem,
            "choices":choices,"answer":answer,"explanation":explanation,"why_wrong":reasons,
            "board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder",
            "mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}


VIGNETTES_V247=[
_q("v247_ped_genetics_fnd","Congenital Hearing Loss Genetics","foundation",
"A newborn has confirmed bilateral sensorineural hearing loss after diagnostic ABR. Which principle best describes the role of genetic evaluation?",
["Genetic testing is a major part of etiologic evaluation because it can establish nonsyndromic or syndromic causes, refine counseling, and trigger surveillance for associated disease","Genetic testing is useful only when a parent also has hearing loss","A normal physical examination excludes a genetic cause","Genetic testing should be deferred until adulthood because results do not affect pediatric care"],0,
"A substantial proportion of congenital bilateral sensorineural hearing loss has a genetic basis. Modern evaluation uses phenotype-directed or broad hearing-loss testing with genetics support because the result can clarify recurrence risk, prognosis, and non-auditory surveillance.",
["Correct. Genetic diagnosis can change counseling and medical surveillance even when hearing rehabilitation itself is already underway.","De novo and recessive disorders are common enough that a negative family history does not remove the indication for etiologic evaluation.","Many genetic hearing-loss disorders have no obvious syndromic features in infancy.","Childhood results can alter surveillance, counseling, and family testing and therefore need not wait until adulthood."],
"In congenital SNHL, absence of family history does not mean absence of genetics.","Why should etiologic testing proceed in parallel with—not before—hearing amplification and language access?"),
_q("v247_ped_genetics_app","Congenital Hearing Loss Genetics","application",
"A 7-month-old with bilateral severe-to-profound sensorineural hearing loss has limited benefit from appropriately fit hearing aids. A multigene panel is still pending. What is the best next management principle?",
["Continue timely cochlear-implant candidacy and language-access planning while the genetic workup proceeds in parallel","Delay cochlear-implant evaluation until a molecular diagnosis is available","Assume a genetic diagnosis means cochlear implantation will not help","Stop audiologic follow-up until the panel returns because thresholds are unlikely to change"],0,
"Etiologic testing and auditory rehabilitation answer different questions. A pending molecular result should not delay age-sensitive access to sound or visual language, hearing-aid verification, and cochlear-implant evaluation when the child meets clinical criteria.",
["Correct. Rehabilitation is driven by auditory performance and developmental timing, not by completion of every etiologic test.","Waiting for molecular certainty can sacrifice a critical language-development window without improving candidacy assessment.","Many children with genetic causes of cochlear hearing loss benefit substantially from cochlear implantation.","Longitudinal audiology remains essential because hearing levels and device benefit can change."],
"Do not let the search for why a child is deaf delay the work of giving the child language.","Which etiologies or anatomic findings would make you scrutinize cochlear nerve integrity before implantation?","senior_management"),
_q("v247_ped_genetics_snr","Congenital Hearing Loss Genetics","senior_decision",
"A child with congenital sensorineural hearing loss receives a pathogenic result associated with a syndrome that can involve another organ system. What is the best chief-level response?",
["Translate the molecular result into phenotype-specific surveillance and family counseling while continuing hearing rehabilitation based on functional performance","Document the gene result but avoid changing care until symptoms from another organ appear","Use the genotype alone to determine hearing-aid versus cochlear-implant candidacy","Tell the family that every relative with the variant will have the same hearing severity and associated findings"],0,
"The value of a molecular diagnosis is not merely naming the cause. Senior management connects genotype to the child's actual phenotype, recommended surveillance, genetics counseling, and testing of relatives when appropriate, while auditory intervention remains based on hearing and language function.",
["Correct. A clinically actionable genetic result should trigger the relevant multidisciplinary surveillance rather than sit passively in the chart.","Waiting for preventable syndromic complications to become symptomatic defeats one of the main benefits of etiologic diagnosis.","Device candidacy is determined by anatomy, thresholds, aided performance, development, and communication goals—not genotype in isolation.","Variable expressivity and penetrance mean relatives with the same variant may not have identical manifestations."],
"A genetic diagnosis is useful when it changes what you watch for, whom you counsel, or how you plan—not because it supplies a label.","How would a finding suggesting an auditory-neural rather than cochlear disorder change your preimplant evaluation?","senior_management"),

_q("v247_ped_cleft_fnd","Cleft Lip / Palate — ENT Surgical Fundamentals","foundation",
"During cleft-palate repair, restoration of which muscular function is central to creating a competent dynamic soft palate for speech?",
["Reconstruction and transverse reorientation of the levator veli palatini sling","Division of the tensor tympani to improve middle-ear ventilation","Resection of the superior constrictor to widen the nasopharynx","Fixation of the tongue base to the posterior pharyngeal wall"],0,
"A key functional goal of modern palatoplasty is to restore the abnormal levator veli palatini into a more physiologic transverse sling so the palate can elevate and close against the pharynx during speech.",
["Correct. Re-establishing levator sling orientation is central to velopharyngeal function after palatoplasty.","Tensor tympani division is unrelated to palatal closure and does not correct cleft-associated Eustachian-tube dysfunction.","Routine constrictor resection would not reconstruct the deficient palatal mechanism and could create morbidity.","Tongue-base fixation is not a component of standard cleft-palate repair."],
"Palatoplasty is not just closing a mucosal gap; it is reconstructing a functional levator mechanism.","Which neurovascular pedicle must be protected when elevating commonly used hard-palate mucoperiosteal flaps?","OR_prep"),
_q("v247_ped_cleft_app","Cleft Lip / Palate — ENT Surgical Fundamentals","application",
"During a two-flap palatoplasty, a resident elevates a posteriorly based hard-palate mucoperiosteal flap. Which structure is most important to preserve to maintain flap perfusion?",
["The greater palatine neurovascular pedicle emerging near the posterolateral hard palate","The lingual artery within the tongue","The superior thyroid artery","The facial artery at the mandibular border"],0,
"Two-flap palatoplasty relies on posteriorly based mucoperiosteal flaps supplied through the greater palatine vascular pedicle. Pedicle injury can compromise flap perfusion and increase wound breakdown or fistula risk.",
["Correct. The greater palatine pedicle is a critical operative landmark and blood supply for the palatal flap.","The lingual artery supplies the tongue and is not the pedicle of a hard-palate mucoperiosteal flap.","The superior thyroid artery has no role in palatal flap perfusion.","The facial artery is important in facial soft tissue but is not the named pedicle of the standard two-flap palatoplasty."],
"Know the goal and the blood supply: levator reconstruction plus preservation of the greater palatine pedicle.","If closure is under excessive tension, why is forcing the flap into position a setup for fistula rather than a sign of a complete repair?","OR_prep"),
_q("v247_ped_cleft_snr","Cleft Lip / Palate — ENT Surgical Fundamentals","senior_decision",
"Months after cleft-palate repair, a child has hypernasality and a symptomatic palatal fistula. What is the best senior-level next step before choosing a revision operation?",
["Define whether speech dysfunction comes from the fistula, velopharyngeal insufficiency, compensatory articulation, or a combination using cleft-team speech assessment and targeted anatomic evaluation","Close the fistula immediately without evaluating velopharyngeal function because every fistula causes the same speech problem","Perform a pharyngeal flap automatically because hypernasality proves a large velopharyngeal gap","Treat with speech therapy alone because structural defects never require revision"],0,
"Secondary cleft surgery should be problem-specific. A fistula can cause nasal air escape, while true velopharyngeal insufficiency and learned articulation errors may coexist; operative selection requires distinguishing these contributors rather than treating the symptom label alone.",
["Correct. Revision planning starts by localizing the structural and functional causes of the child's speech problem.","Fistula closure alone may not fix resonance if a separate velopharyngeal gap persists.","Hypernasality does not define gap size or closure pattern and therefore does not mandate one pharyngeal procedure.","Speech therapy can address compensatory articulation but cannot close a clinically important structural fistula or velopharyngeal gap."],
"A secondary cleft operation should repair the mechanism you proved—not the symptom you heard.","How would severe baseline obstructive sleep apnea alter the choice of a secondary VPI procedure?","senior_management"),

_q("v247_ped_tumor_fnd","Pediatric Head & Neck Tumors","foundation",
"Which finding in a child with a neck mass should most strongly shift the evaluation away from routine observation for reactive adenopathy and toward an oncologic workup?",
["A persistent, firm, enlarging mass with systemic symptoms or other malignant features","A small tender mobile node during an acute upper-respiratory infection that rapidly regresses","Transient bilateral cervical nodes after vaccination","A node that becomes smaller over several days without treatment"],0,
"Most pediatric neck masses are benign, but persistence, progressive enlargement, firmness/fixation, supraclavicular location, constitutional symptoms, or other concerning features should trigger imaging and tissue-diagnosis planning rather than repeated empiric observation.",
["Correct. Persistence and malignant clinical features change the pretest probability and require a structured workup.","Tender nodes that regress with a clear infection are much more consistent with reactive lymphadenopathy.","Brief bilateral adenopathy after immune stimulation is generally observed unless atypical features persist.","Spontaneous regression is reassuring and does not by itself suggest a tumor."],
"In a pediatric neck mass, time course and behavior are often more important than size on a single day.","Which neck-mass features would make you involve oncology before scheduling an excisional biopsy?"),
_q("v247_ped_tumor_app","Pediatric Head & Neck Tumors","application",
"A teenager has a rapidly enlarging cervical mass, weight loss, night sweats, and imaging concerning for lymphoma. The child is stable and has no airway compromise. What is the best next step?",
["Coordinate a tissue-diagnosis plan that provides adequate material for lymphoma classification before starting empiric steroids or definitive therapy","Begin high-dose corticosteroids immediately and obtain tissue only if the mass remains afterward","Perform an unplanned radical neck dissection to remove all gross disease","Treat with prolonged antibiotics despite the malignant clinical pattern and defer biopsy for several months"],0,
"Lymphoma treatment depends on accurate histologic, immunophenotypic, and often molecular classification. When the child is stable, obtain adequate diagnostic tissue through a multidisciplinary plan before corticosteroids or therapy obscure pathology.",
["Correct. The biopsy should be planned to answer the oncologic question while minimizing morbidity.","Steroids can rapidly alter lymphoma histology and should generally be avoided before diagnostic tissue when the airway and other vital structures are safe.","Radical surgical extirpation is not primary treatment for lymphoma and creates avoidable morbidity.","A strongly malignant phenotype should not be subjected to months of empiric antibiotics instead of definitive diagnosis."],
"Suspected lymphoma is a tissue-diagnosis problem, not a neck-dissection problem.","When might an image-guided core versus an open/excisional biopsy be favored, and what does pathology need from you before the procedure?","senior_management"),
_q("v247_ped_tumor_snr","Pediatric Head & Neck Tumors","senior_decision",
"A child with a large neck mass and anterior mediastinal extension has orthopnea and worsens when supine. Tissue diagnosis is needed. What is the safest senior-level principle?",
["Treat this as a high-risk shared-airway/anesthetic problem: avoid routine deep sedation or supine general anesthesia, maintain spontaneous ventilation when feasible, and pursue the least dangerous diagnostic tissue source with oncology and anesthesia","Schedule routine general anesthesia with paralysis because controlled ventilation eliminates mediastinal-mass risk","Force the child supine for imaging before involving anesthesia","Perform an elective tracheostomy under standard induction because the obstruction is necessarily confined to the cervical trachea"],0,
"Anterior mediastinal masses can cause catastrophic airway or cardiovascular collapse after loss of tone, positive-pressure ventilation, or supine positioning. The chief-level decision is to redesign the diagnostic plan around physiology and use an alternative accessible tissue site or minimally sedating approach whenever possible.",
["Correct. Orthopnea and positional symptoms are major warnings that a routine anesthetic can be dangerous.","Paralysis and positive-pressure ventilation can worsen dynamic airway and vascular compression rather than reliably rescue it.","A child who cannot tolerate supine positioning should not be destabilized merely to complete routine testing.","A cervical tracheostomy may not bypass distal tracheobronchial or vascular compression from a mediastinal mass and itself may require hazardous anesthesia."],
"The most important ENT decision in a mediastinal lymphoma may be how not to anesthetize the child.","If no low-risk tissue source exists and the child is deteriorating, what multidisciplinary rescue options should be planned before entering the OR?","overnight_call"),

_q("v247_ped_microtia_fnd","Microtia Reconstruction","foundation",
"Which statement best describes contemporary reconstruction options for a child with microtia?",
["Reconstruction may use autologous costal cartilage, a porous alloplastic framework with vascularized coverage, or an auricular prosthesis depending on anatomy, age, goals, and local expertise","All children require immediate neonatal rib-cartilage reconstruction","Porous alloplastic frameworks can be placed without vascularized soft-tissue coverage","Auricular reconstruction and hearing rehabilitation should be planned independently because they never affect each other"],0,
"Microtia reconstruction is individualized. Autologous rib cartilage, alloplastic framework reconstruction, and prosthetic rehabilitation each have different timing, tissue, complication, and revision considerations, and must be coordinated with hearing and atresia management.",
["Correct. There is no single mandatory reconstruction for every child with microtia.","Autologous rib cartilage requires sufficient chest-wall cartilage and is not a neonatal operation.","Alloplastic frameworks depend on durable vascularized coverage; exposure is a major complication.","Canal/atresia surgery and auricular framework reconstruction share the same regional tissues and therefore require deliberate sequencing."],
"Microtia planning is a reconstruction-plus-hearing pathway, not an ear-shape operation in isolation.","Why does the planned method of auricular reconstruction affect when or whether atresiaplasty should be performed?"),
_q("v247_ped_microtia_app","Microtia Reconstruction","application",
"A child with unilateral grade III microtia and aural atresia is being considered for both auricular reconstruction and canal surgery. What is the best operative-planning principle?",
["Coordinate the microtia and otology teams before either operation because incision placement, vascularized tissue, scar, and sequencing can affect both reconstruction and atresiaplasty","Perform atresiaplasty first in every child regardless of the planned auricular framework","Perform rib-cartilage reconstruction first in every child regardless of temporal-bone anatomy or hearing goals","Choose the sequence solely by family convenience because the operations do not share tissue or blood supply"],0,
"The optimal sequence depends on reconstructive technique, temporal-bone anatomy, hearing plan, and preservation of skin and vascularized tissue. Uncoordinated surgery can compromise later framework coverage or canal reconstruction.",
["Correct. Sequence is a multidisciplinary reconstructive decision rather than a universal memorized order.","Atresiaplasty first can jeopardize tissue needed for some auricular reconstructions and is not universally appropriate.","Framework first is also not universally correct when anatomy, reconstructive method, or hearing strategy dictates another sequence.","Incisions, scar and vascularized coverage matter directly to both operations, so convenience alone is unsafe planning."],
"Before operating on microtia plus atresia, make the otologist and reconstructive surgeon agree on the map.","Which temporal-bone findings would make an implantable or bone-conduction hearing strategy more attractive than canal reconstruction?","OR_prep"),
_q("v247_ped_microtia_snr","Microtia Reconstruction","senior_decision",
"A child develops focal exposure of a porous alloplastic auricular framework with threatened skin and soft-tissue coverage. What is the best senior-level principle?",
["Treat framework exposure as a reconstructive complication requiring prompt assessment for infection, viability, debridement when needed, and restoration of durable vascularized coverage rather than prolonged observation","Observe indefinitely because exposed alloplastic material reliably re-epithelializes without intervention","Remove the entire framework immediately in every case without assessing infection or salvage options","Cover the exposure with a nonvascularized skin graft alone regardless of the condition of the underlying bed"],0,
"Alloplastic framework success depends on stable vascularized coverage. Exposure can progress to infection or framework loss, so salvage decisions should be early and based on tissue viability, contamination, defect size, and the availability of vascularized local/regional tissue.",
["Correct. Early reconstructive assessment preserves the best chance of framework salvage while controlling infection.","Persistent exposure leaves foreign material vulnerable to colonization and progressive soft-tissue breakdown.","Some limited exposures can be salvaged, so mandatory total removal ignores defect-specific reconstructive options.","A skin graft requires a vascularized recipient bed and does not substitute for deficient vascularized coverage over exposed framework."],
"With an alloplastic ear, coverage is biology: exposed framework is an escalation problem, not a cosmetic nuisance.","Which regional vascularized fascial tissue is commonly valuable for covering an auricular framework, and why must prior surgery preserve it?","senior_management"),

_q("v247_ped_frenulum_fnd","Ankyloglossia / Maxillary Frenulum","foundation",
"Which finding best supports a clinically meaningful diagnosis of ankyloglossia in an infant?",
["Restricted tongue mobility from a lingual frenulum together with a functional feeding problem, rather than frenulum appearance alone","Any visible lingual frenulum, even with normal feeding and tongue movement","An upper-lip frenulum without tongue restriction","Isolated future concern about speech in an asymptomatic newborn"],0,
"Ankyloglossia is a functional diagnosis. The appearance of the frenulum is interpreted alongside tongue mobility and a clinically meaningful problem such as persistent breastfeeding dysfunction after skilled feeding assessment.",
["Correct. Anatomy matters when it demonstrably restricts function.","A visible frenulum is normal anatomy in many infants and does not itself establish disease.","A maxillary frenulum is a separate structure and does not diagnose tongue restriction.","Prophylactic release in an asymptomatic newborn solely to prevent hypothetical later speech difficulty is not a sound indication."],
"Treat function, not photographs of frenula.","What feeding history and examination findings would you document before recommending frenotomy?"),
_q("v247_ped_frenulum_app","Ankyloglossia / Maxillary Frenulum","application",
"A breastfeeding infant has persistent poor latch and maternal nipple pain despite skilled lactation support. Examination shows clearly restricted tongue elevation attributable to a tight lingual frenulum. What is the best next step?",
["Discuss frenotomy as an option after confirming the functional problem, reviewing alternatives and expected benefits, and counseling about bleeding, pain, and the possibility of incomplete improvement","Perform frenotomy because every restrictive-looking frenulum guarantees feeding improvement","Recommend no feeding assessment because tongue appearance alone determines treatment","Release both the lingual and maxillary frenula routinely to prevent all future dental and speech problems"],0,
"When a restrictive lingual frenulum is linked to persistent breastfeeding dysfunction despite appropriate support, frenotomy can be considered through shared decision-making. Benefit is not guaranteed, and the indication should remain functional rather than prophylactic.",
["Correct. The procedure is reasonable when anatomy, function, and failed conservative support align.","Even appropriately selected infants may have multifactorial feeding difficulty, so improvement cannot be guaranteed.","Feeding assessment is essential because latch problems can arise from many causes unrelated to tongue restriction.","Routine paired lingual and maxillary release to prevent hypothetical future problems is not supported as a universal strategy."],
"Frenotomy is a targeted intervention after a targeted functional diagnosis—not a reflex response to a frenulum.","Which findings after a bedside frenotomy would require urgent reassessment rather than routine feeding follow-up?","senior_management"),
_q("v247_ped_frenulum_snr","Ankyloglossia / Maxillary Frenulum","senior_decision",
"A school-age child has a prominent maxillary labial frenulum and a midline diastema, but no feeding problem, gingival trauma, or other functional complaint. The family requests immediate frenectomy to guarantee dental closure. What is the best senior-level response?",
["Coordinate with pediatric dentistry/orthodontics and time any frenectomy to the dental problem and developmental stage rather than promising that isolated early release will close the diastema","Perform immediate frenectomy because every midline diastema is caused by the maxillary frenulum","Perform simultaneous lingual frenotomy despite normal tongue function","Recommend wide excision solely to prevent possible future speech problems"],0,
"A prominent maxillary frenulum is common, and diastema management depends on dentition, orthodontic planning, and whether the frenulum is truly contributing to a persistent problem. Early isolated frenectomy is not a guarantee of spontaneous closure and can create scar that complicates later orthodontic management.",
["Correct. Timing should be coordinated with the actual dental indication and the child's stage of dentition.","Midline spacing has multiple developmental and dental causes; frenulum appearance alone does not establish causality.","Normal tongue mobility provides no indication for a separate lingual procedure.","A maxillary frenulum is not released preemptively to prevent nonspecific future speech problems."],
"The chief-level frenulum decision is often knowing when not to operate yet.","If frenectomy is ultimately indicated, what anatomy and scar consequences should be considered when choosing technique and timing?","senior_management"),
]


def apply_learning_ladders_v247(challenges, concept_id_fn):
    existing={q.get("id") for q in challenges}
    added=[]
    for src in VIGNETTES_V247:
        if src["id"] in existing:
            continue
        q=dict(src)
        q["concept_id"]=concept_id_fn(q["domain"],q["topic"])
        challenges.append(q)
        existing.add(q["id"])
        added.append(q["id"])
    return added
