"""v26.9 — General ENT / Emergencies deliberate ladder pass 1.

Five exact canonical emergency concepts. Four strong historical application/call
cases are preserved and upgraded; missing stages and a full Airway Foreign Body
ladder are added. Rationale reuse is keyed by choice text so answer balancing
cannot detach explanations from answers.
"""
DOMAIN="General ENT / Emergencies"
REUSED={
 "v135_gen_01":("Postoperative Neck Hematoma","application"),
 "v143_gen_04":("Peritonsillar Abscess","application"),
 "v143_gen_02":("Deep Neck Abscess Drainage","application"),
 "v143_gen_01":("Caustic Ingestion","application"),
}
REASONS={
 "v135_gen_01":{
  "Wait for CT confirmation":"Imaging can dangerously delay decompression of an evolving compressive hematoma.",
  "Release the wound/hematoma immediately if airway compromise is evolving while mobilizing the OR and airway team":"Correct. Evolving airway compromise from postoperative neck hematoma is treated immediately; bedside wound release may be lifesaving.",
  "Give oral antibiotics and observe":"Antibiotics do not relieve mechanical airway compression.",
  "Place the patient flat and leave the room":"Delay and supine positioning can worsen a rapidly evolving airway emergency."},
 "v143_gen_04":{
  "Drain the abscess by needle aspiration or incision when appropriate, give antibiotics covering typical oral flora, and address hydration/analgesia":"Correct. A stable classic PTA is generally managed with drainage when appropriate, antibiotics, and supportive care.",
  "Tonsillectomy is mandatory in every first episode":"Immediate tonsillectomy is not mandatory for every uncomplicated first PTA.",
  "No drainage because trismus proves viral pharyngitis":"Trismus and unilateral peritonsillar findings support a deep tonsillar-space process rather than proving viral disease.",
  "CT neck is mandatory before any treatment in a classic uncomplicated case":"Classic uncomplicated PTA is usually a clinical diagnosis; imaging is reserved for uncertainty or concern for deeper spread."},
 "v143_gen_02":{
  "Secure/plan the airway and perform timely surgical drainage with culture plus broad antimicrobial therapy":"Correct. Progressive organized deep-neck abscess with airway effect requires airway planning, source control, cultures, and antibiotics.",
  "Continue oral antibiotics alone indefinitely":"A large progressive collection with airway effect has moved beyond routine oral medical management.",
  "Needle the carotid space blindly at bedside":"Blind drainage near major neurovascular structures is unsafe.",
  "Delay intervention until septic shock":"Waiting for shock forfeits the chance to control the airway and infection before decompensation."},
 "v143_gen_01":{
  "Stabilize airway/hemodynamics, avoid induced emesis or blind neutralization, and coordinate timely endoscopic/CT evaluation based on severity":"Correct. Caustic ingestion is managed by stabilization, avoidance of re-exposure/neutralization injury, and severity-directed aerodigestive evaluation.",
  "Induce vomiting immediately":"Emesis re-exposes the esophagus and pharynx to the caustic agent and can worsen injury/aspiration.",
  "Give acid to neutralize the alkali":"Blind chemical neutralization can generate heat and additional tissue injury.",
  "Discharge if the oral cavity looks normal":"Oral examination does not reliably predict distal esophageal or gastric injury."},
}
def _q(qid,topic,stage,stem,choices,answer,exp,reasons,pearl,curveball,focus="boards"):
 return {"id":qid,"domain":DOMAIN,"topic":topic,"learning_stage":stage,"stem":stem,"choices":choices,"answer":answer,"explanation":exp,"why_wrong":reasons,"board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder","mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}
VIGNETTES_V269=[
_q("v269_gen_hemat_fnd","Postoperative Neck Hematoma","foundation","Which postoperative finding after thyroid/parathyroid or major neck surgery should trigger immediate concern for a compressive neck hematoma?",["Rapid neck pressure/swelling with voice change, dysphagia, anxiety, stridor, or respiratory distress","Stable bruising without pressure symptoms","Mild incisional tenderness alone","Isolated postoperative nausea"],0,"A cervical hematoma can compress the airway through deep pressure before dramatic external swelling appears. Rapid pressure symptoms, voice/swallow change, anxiety and respiratory signs are red flags.",["Correct. Progressive pressure and airway symptoms are the dangerous phenotype.","Stable superficial ecchymosis alone does not establish an expanding compressive hematoma.","Expected incisional tenderness without progression is nonspecific.","Nausea does not localize a cervical compressive process."],"A small-looking neck can still hide lethal deep pressure.","Why can intubation become progressively harder as venous/lymphatic obstruction worsens?","overnight_call"),
_q("v269_gen_hemat_snr","Postoperative Neck Hematoma","senior_decision","A post-thyroidectomy patient has rapidly expanding swelling and worsening stridor; the OR is not immediately available and oxygenation is deteriorating. What is the best senior action?",["Open the cervical incision and release constricting sutures/clot immediately while activating anesthesia/OR help and preparing definitive airway/hemorrhage control","Wait for ultrasound","Attempt repeated sedating fiberoptic examinations without decompression","Observe until hypotension develops"],0,"When a postoperative neck hematoma is causing evolving airway compromise, immediate bedside wound decompression can be lifesaving. Definitive hemostasis follows once pressure is relieved and the airway/OR team is mobilized.",["Correct. Treat the time-critical mechanical obstruction before diagnostic refinement.","Imaging delays treatment of a clinical airway emergency.","Sedation in a progressively compressed airway without pressure relief can precipitate complete obstruction.","Hypotension is a late and unnecessary threshold for action."],"Post-neck-surgery hematoma is one of the few ENT emergencies where opening the wound before the OR may save the airway.","If decompression does not restore ventilation, what parallel airway plan should already be underway?","senior_decision"),
_q("v269_gen_pta_fnd","Peritonsillar Abscess","foundation","Which constellation most strongly suggests peritonsillar abscess rather than uncomplicated tonsillitis?",["Unilateral severe odynophagia with trismus, muffled voice and asymmetric peritonsillar swelling/uvular displacement","Bilateral mild sore throat with cough and rhinorrhea","Isolated hoarseness","Painless midline neck mass"],0,"PTA classically produces unilateral peritonsillar inflammation with trismus, muffled voice and asymmetric palate/uvular findings.",["Correct. The unilateral deep-space pattern and trismus are classic.","Cough/rhinorrhea with symmetric mild pharyngitis is less consistent with PTA.","Hoarseness alone localizes poorly to the peritonsillar space.","A painless midline neck mass is a different diagnostic pathway."],"Trismus is a clue that the process is deeper than routine pharyngitis.","Which exam features should make you worry about parapharyngeal spread or airway compromise?"),
_q("v269_gen_pta_snr","Peritonsillar Abscess","senior_decision","A patient thought to have PTA has severe trismus, toxic appearance, neck stiffness and swelling extending below the angle of the mandible. What is the best senior decision?",["Broaden the diagnosis to deep-neck infection, reassess the airway and obtain contrast imaging if stable rather than treating this as routine office PTA","Perform blind repeated tonsillar needle passes","Discharge after one oral antibiotic dose","Assume CT is never useful in tonsillar infection"],0,"Atypical external neck swelling, toxicity, stiffness, marked trismus or airway symptoms should trigger concern for parapharyngeal/retropharyngeal extension or another deep-space process.",["Correct. The phenotype has escaped the uncomplicated PTA pathway.","Blind repeated aspiration can miss the true compartment and risks adjacent structures.","Toxic deep-space features require monitored escalation, not routine discharge.","Imaging is useful when anatomy, diagnosis or extension is uncertain and the airway is stable enough to obtain it."],"Know when a PTA stops being a PTA problem and becomes a deep-neck/airway problem.","What CT finding would push toward transcervical rather than transoral drainage?","overnight_call"),
_q("v269_gen_deep_fnd","Deep Neck Abscess Drainage","foundation","What three priorities define management of a clinically significant deep-neck abscess?",["Airway safety, anatomic source control, and appropriate antimicrobial therapy","Antibiotics alone regardless of airway or collection","Drain placement without treating the source","Imaging before airway stabilization in every patient"],0,"Deep-neck infection management is built around airway trajectory, source control of the involved compartment/source, and broad antimicrobial therapy refined by cultures.",["Correct. Airway + source control + antibiotics is the core framework.","Organized abscess or airway progression may not resolve with antibiotics alone.","Drainage without controlling an odontogenic/pharyngeal source invites persistence.","An unstable airway takes priority over transport for imaging."],"The CT is a map only after the airway is safe enough to reach the scanner.","Which fascial spaces can descend into the mediastinum?","boards"),
_q("v269_gen_deep_snr","Deep Neck Abscess Drainage","senior_decision","After drainage of a parapharyngeal abscess, fever and inflammatory markers worsen and the patient develops chest pain. What is the best next step?",["Re-image the neck and chest for an undrained compartment or descending mediastinitis and involve thoracic/other teams early","Assume postoperative fever is expected and ignore the chest symptoms","Remove all drains immediately","Switch to oral antibiotics without reassessment"],0,"Persistent toxicity after source control should prompt a search for residual/second-space infection, vascular complication or descending mediastinal spread rather than simple antibiotic escalation alone.",["Correct. Failure after drainage is a localization problem until proven otherwise.","Chest pain with worsening sepsis is not routine postoperative fever.","Premature drain removal may worsen source control.","De-escalation without reassessing an uncontrolled source is unsafe."],"When deep-neck infection does not improve, ask what space or complication you missed.","How does septic IJV thrombophlebitis change the workup?","senior_decision"),
_q("v269_gen_caust_fnd","Caustic Ingestion","foundation","Which statement about caustic ingestion is most accurate?",["The absence of oral burns does not exclude major esophageal or gastric injury","A normal mouth proves the esophagus is safe","Inducing emesis helps remove the caustic","Acid-base neutralization should be attempted at home"],0,"Visible oral injury correlates imperfectly with deeper aerodigestive injury. Management is based on agent, symptoms, airway/perforation risk and severity-directed evaluation.",["Correct. The mouth is an unreliable proxy for distal injury.","Significant distal injury can occur despite a relatively normal oral exam.","Emesis causes repeat mucosal exposure and aspiration risk.","Neutralization can cause exothermic injury and is not recommended."],"Do not let a normal oral cavity falsely downgrade a dangerous ingestion.","Which symptoms make laryngeal injury/airway intervention more urgent?"),
_q("v269_gen_caust_snr","Caustic Ingestion","senior_decision","A caustic-ingestion patient develops severe chest pain, tachycardia, guarding and imaging evidence of transmural necrosis/perforation. What is the best senior principle?",["Treat this as a perforation/necrosis emergency with resuscitation, broad antimicrobials and urgent multidisciplinary surgical source-control planning rather than routine diagnostic endoscopy alone","Proceed with blind neutralization","Discharge if laryngoscopy is normal","Delay until stricture formation"],0,"Perforation or transmural necrosis changes the pathway from injury grading to emergency source control. Endoscopy alone is not definitive treatment of free contamination/necrotic viscera.",["Correct. Organ-threatening transmural injury requires surgical critical-care escalation.","Neutralization worsens injury risk and cannot repair necrosis.","A normal larynx does not negate distal perforation.","Stricture is a later complication; current perforation is immediately dangerous."],"Caustic injury is not one pathway: airway threat, mucosal burn and transmural perforation demand different escalation.","What role does later stricture surveillance/dilation have after survival of severe injury?","senior_decision"),
_q("v269_gen_afb_fnd","Airway Foreign Body","foundation","A toddler suddenly coughs and chokes while eating peanuts, then has persistent unilateral wheeze. Chest radiograph is normal. What is the best interpretation?",["A classic aspiration history can justify bronchoscopy despite normal radiographs","Normal imaging excludes foreign body","Treat as asthma for months before reconsidering","Obtain a barium swallow as the definitive airway test"],0,"Many aspirated foreign bodies are radiolucent and chest radiography can be normal. A convincing witnessed aspiration plus persistent focal respiratory findings should maintain high suspicion.",["Correct. History and focal findings can outweigh a normal x-ray.","Normal radiographs do not exclude radiolucent airway foreign bodies.","Delaying a classic aspiration risks pneumonia, granulation and chronic lung injury.","A barium swallow evaluates the esophagus, not the tracheobronchial airway."],"Do not let a normal x-ray erase a classic choking event.","What inspiratory/expiratory or decubitus findings can support ball-valve obstruction?","boards"),
_q("v269_gen_afb_app","Airway Foreign Body","application","A stable child has high clinical suspicion for a bronchial foreign body after a witnessed choking event. What is the definitive management principle?",["Proceed to controlled rigid bronchoscopy with an anesthesia/surgical plan for ventilation, extraction and distal airway inspection","Perform blind flexible-forceps extraction in clinic","Observe until pneumonia develops","Treat with antibiotics as definitive therapy"],0,"Rigid bronchoscopy is the standard definitive diagnostic/therapeutic approach for a suspected pediatric airway foreign body when clinical suspicion warrants intervention.",["Correct. Controlled rigid bronchoscopy provides airway control, visualization and extraction capability.","Blind instrumentation risks pushing the object distally or causing airway trauma.","Waiting for complications is unnecessary when suspicion is high.","Antibiotics do not remove the obstructing foreign body."],"Foreign-body bronchoscopy is an airway operation before it is an extraction procedure.","Why should both lungs and distal bronchi be inspected after removal?","OR_prep"),
_q("v269_gen_afb_snr","Airway Foreign Body","senior_decision","During rigid bronchoscopy, a large airway foreign body becomes lodged at the glottis during extraction and ventilation abruptly fails. What is the best senior principle?",["Treat it as an immediate shared airway crisis: re-establish ventilation by controlled repositioning/removal, coordinate continuously with anesthesia, and be prepared for emergency surgical airway if obstruction cannot be relieved","Continue pulling blindly regardless of visualization","Stop all airway instrumentation and wait","Push the object distally without a plan"],0,"Foreign-body extraction can convert partial distal obstruction into complete central obstruction. The team must prioritize ventilation, controlled visualization/manipulation and a preplanned rescue pathway.",["Correct. Oxygenation and airway control outrank completion of extraction.","Blind traction can worsen impaction or injure the larynx.","Complete central obstruction cannot safely be observed.","Unplanned distal displacement may create another nonventilated lung/airway emergency."],"The dangerous moment may be extraction through the narrowest part of the airway, not finding the object.","How does a sharp foreign body change extraction orientation and mucosal-injury planning?","senior_decision"),
]
def apply_learning_ladders_v269(challenges,item_id_fn):
 by_id={str(q.get("id")):q for q in challenges if q.get("id")}; reused=0
 for qid,(topic,stage) in REUSED.items():
  row=by_id.get(qid)
  if row is None: raise RuntimeError(f"v269 missing reusable case {qid}")
  mapping=REASONS[qid]; choices=list(row.get("choices") or []); unknown=[c for c in choices if c not in mapping]
  if unknown: raise RuntimeError(f"v269 unknown reused choices for {qid}: {unknown}")
  cid=item_id_fn(DOMAIN,topic)
  if not cid: raise RuntimeError(f"v269 orphan reusable topic {topic}")
  row.update({"domain":DOMAIN,"topic":topic,"concept_id":cid,"learning_stage":stage,"why_wrong":[mapping[c] for c in choices],"ladder_reviewed":True,"_coverage_reviewed_v211":True}); reused+=1
 existing=set(by_id); added=0
 for q in VIGNETTES_V269:
  if q["id"] in existing: continue
  row=dict(q); row["concept_id"]=item_id_fn(DOMAIN,row["topic"])
  if not row["concept_id"]: raise RuntimeError(f"v269 orphan topic {row['topic']}")
  challenges.append(row); existing.add(row["id"]); added+=1
 return {"reused":reused,"added":added,"reviewed_topics":5}
