"""v26.7/v26.8 — Sleep Surgery deliberate ladder pass 4.

Closes five exact canonical nonoperative/pediatric residual-sleep concepts.
Strong v13.7 cases are preserved with explicit stage metadata and individualized
rationales. Reused rationale text is keyed to choice text rather than historical
option position so deterministic answer balancing cannot misalign explanations.
"""
DOMAIN="Sleep Surgery"
REUSED={
 "v137_slp_02":("Circadian Rhythm Sleep-Wake Disorders","foundation"),
 "v137_slp_03":("Down Syndrome Pediatric HNS","application"),
 "v137_slp_06":("Lingual Tonsil / Tongue-Base Obstruction","application"),
 "v137_slp_07":("Narcolepsy / Central Hypersomnolence Recognition","foundation"),
 "v137_slp_12":("Restless Legs / Periodic Limb Movement Disorders","foundation"),
}
REUSED_REASON_BY_CHOICE={
 "v137_slp_02":{
  "Delayed sleep-wake phase disorder managed with schedule/light timing rather than airway surgery":"Correct. Normal restorative sleep at a consistently delayed clock time fits delayed sleep-wake phase physiology.",
  "Severe OSA by history alone":"OSA requires an obstructive sleep-breathing phenotype, not delayed timing alone.",
  "Narcolepsy":"Narcolepsy causes central hypersomnolence/REM phenomena rather than a stable late sleep window.",
  "Central apnea":"Central apnea is a respiratory-event disorder and does not explain reproducible delayed sleep timing."},
 "v137_slp_03":{
  "Confirm candidacy with age/size criteria, PSG severity and DISE pattern while evaluating multilevel obstruction":"Correct. Pediatric HNS is phenotype-selected: residual OSA, anatomy, DISE, comorbidity and current candidacy criteria all matter.",
  "Implant without PSG":"Implantation without confirming current physiology and anatomy risks treating the wrong mechanism.",
  "Assume adenotonsillectomy failure excludes all surgery":"Residual OSA after adenotonsillectomy does not exclude other evidence-based therapies.",
  "Perform adult UPPP routinely":"Adult palatal surgery is not a default answer to the multilevel hypotonia/tongue-base phenotype of Down syndrome."},
 "v137_slp_06":{
  "Lingual tonsillectomy":"Correct. Lingual tonsillectomy directly treats documented lingual-tonsil obstruction when it is a meaningful residual site.",
  "Repeat adenoidectomy despite no adenoid regrowth":"Repeat adenoid surgery does not address a tongue-base target without significant adenoid regrowth.",
  "Septoplasty alone":"Septoplasty does not remove vallecular obstruction from hypertrophic lingual tonsil tissue.",
  "No surgical option":"A demonstrated surgically addressable residual site exists; treatment choice depends on expected benefit and airway/swallow risk."},
 "v137_slp_07":{
  "Refer for sleep-medicine evaluation with PSG followed by MSLT when appropriate":"Correct. Cataplexy plus irresistible sleep episodes should trigger central-hypersomnolence evaluation with appropriately prepared PSG/MSLT when indicated.",
  "Offer palatal surgery":"Palatal surgery treats obstruction, not narcolepsy.",
  "Diagnose OSA without testing":"Daytime sleepiness is nonspecific; cataplexy strongly redirects the differential away from assuming OSA.",
  "Treat with nasal steroids only":"Nasal steroids do not treat cataplexy or central hypersomnolence."},
 "v137_slp_12":{
  "Evaluate for restless legs syndrome, including iron status and medication contributors":"Correct. Evening rest-induced urge to move relieved by movement is classic restless legs syndrome; iron and medication contributors are actionable.",
  "Offer UPPP":"UPPP has no role in a sensorimotor leg disorder without an obstructive target.",
  "Implant HNS":"HNS treats selected OSA, not restless legs syndrome.",
  "Diagnose insomnia only":"Insomnia may coexist, but the specific urge-to-move phenotype should not be relabeled as generic insomnia."},
}
def _q(qid,topic,stage,stem,choices,answer,explanation,reasons,pearl,curveball,focus="boards"):
 return {"id":qid,"domain":DOMAIN,"topic":topic,"learning_stage":stage,"stem":stem,"choices":choices,"answer":answer,"explanation":explanation,"why_wrong":reasons,"board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder","mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}
VIGNETTES_V267=[
_q("v267_sleep_circ_app","Circadian Rhythm Sleep-Wake Disorders","application","A resident cannot fall asleep before 2-3 AM but sleeps normally when allowed a late schedule. There is no convincing OSA phenotype. What is the best next step?",["Document sleep timing with diary/actigraphy and use circadian-timed schedule/light interventions","Schedule DISE","Offer UPPP","Start nocturnal oxygen"],0,"A stable delayed sleep window is a clock-timing disorder. Sleep logs/actigraphy and appropriately timed behavioral/light strategies address the mechanism.",["Correct. Document and treat the circadian mechanism.","DISE is for selected obstructive surgical planning, not circadian diagnosis.","UPPP cannot correct circadian misalignment.","Oxygen does not reset circadian phase."],"When sleep is normal at the preferred clock time, ask whether the clock—not the airway—is the disorder.","How do rotating shifts complicate interpretation?","sleep_interpretation"),
_q("v267_sleep_circ_snr","Circadian Rhythm Sleep-Wake Disorders","senior_decision","A PAP-intolerant patient referred for surgery has only mild OSA but marked delayed phase and chronic sleep restriction; fatigue disappears on vacations with a late schedule. What is the best decision?",["Treat insufficient sleep/circadian misalignment before escalating irreversible airway surgery","Perform multilevel surgery because PAP was not tolerated","Implant HNS for fatigue","Ignore sleep timing because AHI is known"],0,"Surgical candidacy requires a meaningful obstructive target and a symptom plausibly caused by it. Here the fatigue phenotype is better explained by timing and sleep opportunity.",["Correct. Address the dominant nonanatomic symptom generator first.","PAP intolerance alone does not create a surgical indication.","Fatigue alone is not an HNS indication.","AHI does not explain every cause of sleepiness."],"A sleep surgeon must recognize when the airway is not why the patient is tired.","What response to schedule correction would support this interpretation?","senior_decision"),
_q("v267_sleep_ds_fnd","Down Syndrome Pediatric HNS","foundation","Why can OSA persist after adenotonsillectomy in a child with Down syndrome?",["Multilevel obstruction from tongue base, hypotonia, craniofacial anatomy and other sites may remain","Adenotonsillectomy always cures OSA","Residual events are always central","Persistence proves technical failure"],0,"Down syndrome OSA is often multilevel, so removal of adenotonsillar tissue may leave tongue-base, supraglottic or hypotonia-related obstruction.",["Correct. Residual disease often reflects persistent multilevel anatomy.","Adenotonsillectomy does not guarantee cure in this phenotype.","Residual events must be classified by PSG rather than assumed central.","Persistent disease can occur after technically successful surgery."],"Successful adenotonsillectomy can still leave a different obstructive airway behind.","Which residual sites are useful to assess with DISE?"),
_q("v267_sleep_ds_snr","Down Syndrome Pediatric HNS","senior_decision","A child with Down syndrome has persistent symptoms after adenotonsillectomy, but repeat PSG shows predominant hypoventilation and DISE lacks a convincing HNS-responsive pattern. What is the best decision?",["Treat the hypoventilation/current physiology rather than forcing HNS into a mismatched phenotype","Implant HNS because prior surgery failed","Relabel hypoventilation as obstruction","Perform tongue-base reduction without a target"],0,"Pediatric HNS is an obstruction-directed therapy. Dominant hypoventilation or an unfavorable airway phenotype should redirect management to the actual physiology.",["Correct. Therapy should match the current mechanism.","Failure of one operation does not establish candidacy for another.","Hypoventilation is not an obstructive apnea.","Untargeted tongue-base surgery adds risk without a mechanism of benefit."],"Residual pediatric sleep disease is phenotype-driven; HNS is not the automatic next step.","How would new central events or pulmonary disease alter candidacy?","senior_decision"),
_q("v267_sleep_ling_fnd","Lingual Tonsil / Tongue-Base Obstruction","foundation","A child remains obstructed after adenotonsillectomy. Which finding best supports lingual tonsil tissue as a residual target?",["Endoscopic/DISE evidence that hypertrophic lingual tonsil tissue fills the vallecula and contributes to obstruction","Isolated nasal congestion","Central apneas without effort","Restless legs symptoms"],0,"Lingual tonsil hypertrophy is a recognized residual OSA mechanism, but treatment should follow demonstrated obstruction rather than visible tissue alone.",["Correct. The target is tissue shown to contribute to obstruction.","Nasal disease does not localize the problem to lingual tonsil tissue.","Central events reflect respiratory-drive physiology.","RLS does not localize obstruction to the tongue base."],"Prove the lingual tonsil is obstructing—not merely present.","What other tongue-base/supraglottic findings can coexist?"),
_q("v267_sleep_ling_snr","Lingual Tonsil / Tongue-Base Obstruction","senior_decision","A medically complex child has severe residual OSA with DISE-confirmed lingual tonsil obstruction and is scheduled for lingual tonsillectomy. What should drive postoperative planning?",["Anticipate edema, bleeding, dysphagia and airway compromise and choose monitoring/intubation strategy by severity and comorbidity","Treat it like office debridement","Discharge every patient same day","Ignore swallowing risk"],0,"Tongue-base surgery occurs in a confined airway. Severe OSA, syndromic anatomy, pulmonary disease and multilevel surgery should determine postoperative airway and monitoring strategy.",["Correct. The postoperative airway is part of the operation.","Tongue-base surgery has meaningful airway consequences.","Disposition must be risk-based.","Dysphagia is a real postoperative concern."],"For tongue-base surgery, plan the airway after you manipulate the obstruction.","What findings justify planned intubation or ICU observation?","OR_prep"),
_q("v267_sleep_narc_app","Narcolepsy / Central Hypersomnolence Recognition","application","A sleepy patient is being considered for MSLT but sleeps only five hours nightly and has untreated moderate OSA. What is the best approach?",["Correct insufficient sleep and treat competing OSA before relying on MSLT","Diagnose narcolepsy from any short latency","Perform airway surgery to normalize MSLT","Diagnose narcolepsy from sleepiness alone"],0,"MSLT is context dependent; sleep deprivation, untreated OSA, circadian misalignment and medications can confound sleep latency and sleep-onset REM periods.",["Correct. Make the test clinically interpretable before using it diagnostically.","Short latency is nonspecific with sleep debt and untreated OSA.","Surgery is not performed to normalize a diagnostic test.","Sleepiness has a broad differential."],"Before trusting an MSLT, make sure the patient had a fair chance to be normally alert.","Which medications alter REM and MSLT interpretation?","sleep_interpretation"),
_q("v267_sleep_narc_snr","Narcolepsy / Central Hypersomnolence Recognition","senior_decision","An adult has well-controlled obstruction after OSA surgery but disabling sleep attacks and cataplexy persist. What is the best response?",["Stop escalating airway surgery and evaluate central hypersomnolence","Perform another palatal procedure","Assume the postoperative PSG is wrong","Implant HNS despite controlled obstruction"],0,"Persistent sleepiness after effective OSA therapy requires a broader differential; cataplexy strongly suggests central hypersomnolence rather than residual airway obstruction.",["Correct. Re-establish the symptom mechanism before another irreversible intervention.","Palatal surgery does not treat cataplexy.","Multiple sleep disorders can coexist; symptoms do not invalidate a controlled PSG.","HNS treats obstruction and is not indicated when obstruction is controlled."],"Residual sleepiness after successful OSA treatment is a diagnostic problem before it is a surgical failure.","What history distinguishes cataplexy from syncope or weakness?","senior_decision"),
_q("v267_sleep_rls_app","Restless Legs / Periodic Limb Movement Disorders","application","A patient has classic restless legs symptoms and low ferritin without anemia. What is the best management principle?",["Address iron deficiency when appropriate and review aggravating medications/sleep habits","Offer tongue-base surgery","Ignore iron because hemoglobin is normal","Treat with oxygen"],0,"RLS management includes correcting reversible contributors such as low iron stores and reviewing medications that worsen symptoms.",["Correct. Treat reversible contributors before escalating therapy.","Tongue-base surgery does not treat RLS.","Normal hemoglobin does not exclude low iron stores relevant to RLS.","Oxygen does not treat the urge-to-move mechanism."],"Iron stores can matter in RLS even with a normal CBC.","Which medication classes can worsen symptoms?","sleep_management"),
_q("v267_sleep_rls_snr","Restless Legs / Periodic Limb Movement Disorders","senior_decision","A patient with treated OSA has frequent periodic limb movements on PSG but denies urge-to-move or evening sensory symptoms. What is the best interpretation?",["Do not equate a limb-movement index with RLS; determine clinical significance and secondary causes first","Diagnose RLS from PSG alone","Repeat airway surgery","Treat every movement with a dopamine agonist"],0,"RLS is a clinical diagnosis; periodic limb movements are a PSG observation that may be symptomatic, secondary, or incidental.",["Correct. Separate the clinical syndrome from an electrophysiologic observation.","PSG alone does not diagnose RLS.","Poor sleep after controlled OSA is not automatically recurrent obstruction.","Medication treatment requires a clinically meaningful disorder and risk-benefit assessment."],"A limb-movement index is not the diagnosis.","How do untreated OSA, serotonergic drugs, renal disease or iron deficiency alter significance?","senior_decision"),
]
def apply_learning_ladders_v267(challenges,item_id_fn):
 by_id={str(q.get("id")):q for q in challenges if q.get("id")}; reused=0
 for qid,(topic,stage) in REUSED.items():
  row=by_id.get(qid)
  if row is None: raise RuntimeError(f"v267 missing reusable case {qid}")
  choices=list(row.get("choices") or []); mapping=REUSED_REASON_BY_CHOICE[qid]
  unknown=[c for c in choices if c not in mapping]
  if unknown: raise RuntimeError(f"v267 unknown reused choices for {qid}: {unknown}")
  reasons=[mapping[c] for c in choices]
  cid=item_id_fn(DOMAIN,topic)
  if not cid: raise RuntimeError(f"v267 orphan reusable topic {topic}")
  row.update({"domain":DOMAIN,"topic":topic,"concept_id":cid,"learning_stage":stage,"why_wrong":reasons,"ladder_reviewed":True,"_coverage_reviewed_v211":True}); reused+=1
 existing=set(by_id); added=0
 for q in VIGNETTES_V267:
  if q["id"] in existing: continue
  row=dict(q); row["concept_id"]=item_id_fn(DOMAIN,row["topic"])
  if not row["concept_id"]: raise RuntimeError(f"v267 orphan topic {row['topic']}")
  challenges.append(row); existing.add(row["id"]); added+=1
 return {"reused":reused,"added":added,"reviewed_topics":5}
