"""
v14.7 - Second-case depth closure for Facial Plastics / Trauma and
General ENT / Emergencies singleton topics.
"""


def _c(qid,d,t,s,ch,a,e,p,cb,f="boards"):
    return {"id":qid,"domain":d,"topic":t,"stem":s,"choices":ch,"answer":a,
            "explanation":e,"why_wrong":["Correct." if i==a else "This option misses the key discriminator in the scenario." for i in range(len(ch))],
            "board_pearl":p,"curveball":cb,"tier":"Curated second-pass depth","mode":"Vignette","focus":f}

F="Facial Plastics / Trauma"
G="General ENT / Emergencies"

VIGNETTES_V147=[
# Facial plastics / trauma
_c("v147_fp_01",F,"Aesthetic Facial Analysis","A patient requests rhinoplasty because the nose looks 'too large.' What is the best preoperative analysis principle?",["Analyze nasal proportions in the context of facial thirds, profile, chin projection, skin-soft tissue envelope, and patient goals","Measure only nasal length","Promise a celebrity replica","Ignore photography"],0,"Aesthetic planning is relational: a nose can appear prominent because of chin deficiency or facial proportion, and skin thickness constrains what contour changes are visible. Standardized photography and goal alignment are essential.","Treat the face, not an isolated measurement.","How can weak chin projection alter perceived nasal size?","boards"),
_c("v147_fp_02",F,"Aging Face / Injectables / Resurfacing","A patient requests filler for deep nasolabial folds but has significant midface volume loss and skin photodamage. What is the best treatment principle?",["Treat the underlying volume and skin-quality problems rather than simply overfilling the crease","Place unlimited filler directly into the fold","Ignore vascular anatomy","Resurfacing corrects all volume loss"],0,"Facial aging combines skeletal remodeling, fat redistribution, ligamentous change, and skin damage. Good treatment matches modality to mechanism and respects vascular danger zones.","A wrinkle is often the downstream sign of a deeper volume problem.","Which facial filler regions carry major vision-loss risk from vascular injection?","boards"),
_c("v147_fp_03",F,"Alar Retraction / Nasal Vestibular Stenosis","A patient has external nasal valve collapse and alar retraction after prior rhinoplasty. What reconstructive principle is most appropriate?",["Restore structural support and lining/skin relationships with grafting or local reconstruction rather than simply enlarging the nostril","Remove more lower lateral cartilage","Cauterize the vestibule","Observe severe fixed stenosis indefinitely"],0,"Postrhinoplasty alar retraction or vestibular stenosis usually reflects loss of support, scar contracture, or lining deficiency. Treatment reconstructs the deficient layer and resists recurrent contraction.","A stable nasal airway needs framework, lining, and skin in balance.","When would a composite auricular graft be useful?","OR_prep"),
_c("v147_fp_04",F,"Auricular Reconstruction","A traumatic upper-third auricular defect removes skin and cartilage but leaves a healthy postauricular sulcus. What reconstructive principle guides repair?",["Replace both framework and thin pliable skin while preserving ear projection","Close under excessive tension and ignore cartilage loss","Remove the rest of the ear","Use a thick muscle flap over the helix"],0,"Auricular reconstruction depends on restoring cartilage contour and covering it with thin vascularized tissue. Defect size/location determine local flap, cartilage graft, staged pocket, or prosthetic options.","The ear is a framework problem covered by very thin skin.","How does exposed avascular cartilage change graft versus flap choice?","OR_prep"),
_c("v147_fp_05",F,"Bilobed Flap","A 1.2-cm nasal tip defect is too large for primary closure. Why can a bilobed flap work well?",["It recruits adjacent lax dorsal/sidewall skin through two transposition lobes while distributing tension","It requires no geometric planning","It is ideal for every cheek defect","It eliminates pincushion risk"],0,"The bilobed flap is useful for selected small-to-moderate nasal defects because it redirects tension and recruits nearby skin with good color/texture match. Oversizing, poor pivot design, or excessive arc can distort the ala and cause pincushioning.","Bilobed flap success is geometry plus tension control.","What design error commonly causes alar retraction?","OR_prep"),
_c("v147_fp_06",F,"Cervicofacial Flap","A large lateral cheek defect after cancer extirpation exposes parotid fascia but has no bone exposure. What is a major advantage of a cervicofacial advancement flap?",["It recruits large areas of color-matched cheek/neck skin with scars hidden in relaxed tension lines and creases","It requires free tissue transfer in every case","It provides vascularized bone","It is tension-free regardless of defect size"],0,"Cervicofacial flaps can cover large cheek defects with excellent skin match, but distal perfusion, lower-lid tension, facial nerve plane, and prior radiation matter.","For cheek reconstruction, adjacent skin often beats distant skin if perfusion and eyelid position are protected.","How do you reduce ectropion risk in a high cheek defect?","OR_prep"),
_c("v147_fp_07",F,"Facial Synkinesis / Static-Dynamic Rehabilitation","Months after Bell palsy recovery, a patient closes the eye when smiling and has painful neck/platysma contraction. What is the best treatment framework?",["Neuromuscular retraining plus targeted botulinum toxin, with selective surgery for refractory patterns","Repeat steroids indefinitely","Static sling alone cures all synkinesis","No treatment exists"],0,"Synkinesis reflects aberrant reinnervation after facial nerve recovery. Treatment combines retraining and targeted chemodenervation; selective myectomy/neurectomy or other procedures are reserved for persistent functional problems.","Synkinesis is miswired recovery, not persistent complete paralysis.","How would management differ if the patient instead had flaccid complete paralysis with no recovery potential?","boards"),
_c("v147_fp_08",F,"Hair Restoration Fundamentals","A man has stable androgenetic alopecia and adequate occipital donor density. What determines whether transplantation will look natural long term?",["Conservative hairline design, donor planning, graft direction/angle, and anticipation of future loss","Maximize density in the lowest possible juvenile hairline","Ignore future native-hair loss","Harvest beyond the safe donor zone"],0,"Hair restoration is a finite-donor-resource problem. Natural design and long-term planning matter as much as graft survival because native alopecia can continue.","You are spending a limited donor bank over a lifetime.","How do FUT and FUE differ in scar pattern and donor management?","OR_prep"),
_c("v147_fp_09",F,"Local Flap Reconstruction","A small cheek defect lies near the lower eyelid. What is the most important flap-planning principle?",["Place vectors so closure does not pull the lower lid inferiorly and recruit adjacent tissue with matched color/texture","Choose the shortest incision regardless of tension direction","Use a skin graft because local tissue never matches","Ignore relaxed skin tension lines"],0,"Local flaps redistribute tension. Near free margins such as eyelid, ala, or lip, vector control is critical to avoid distortion even if the defect is small.","The dangerous complication is often what the flap pulls on, not whether the flap survives.","What adjunct can protect the lower lid in a larger reconstruction?","OR_prep"),
_c("v147_fp_10",F,"Mandibular Biomechanics and Occlusion","A patient with bilateral subcondylar fractures develops an anterior open bite. What mechanism explains it?",["Loss of posterior ramus height allows clockwise mandibular rotation","The maxilla lengthens acutely","The tongue becomes paralyzed","The teeth erupt overnight"],0,"Bilateral condylar height loss shortens the posterior vertical dimension, causing posterior premature contact and anterior open bite. Occlusion is therefore a functional readout of fracture mechanics.","Read the fracture through the bite.","What occlusal pattern can a unilateral condylar fracture produce?","boards"),
_c("v147_fp_11",F,"Mohs Defect Reconstruction","A nasal ala defect is referred immediately after Mohs surgery. What information should the reconstructive surgeon verify first?",["Margin clearance, exact defect depth/layers, subunit involvement, and whether additional oncologic resection is expected","Only the pre-Mohs photo","Assume margins are positive","Ignore lining and cartilage loss"],0,"Reconstruction should begin only after oncologic clearance is established and the true three-dimensional defect is understood. Nasal defects may require separate lining, support, and cover reconstruction.","Never reconstruct an uncertainty.","How does full-thickness alar loss change the reconstructive ladder?","OR_prep"),
_c("v147_fp_12",F,"Otoplasty","A patient has prominent ears from an underdeveloped antihelical fold with normal conchal depth. Which maneuver best targets the cause?",["Create/reinforce the antihelical fold with cartilage-sparing sutures or scoring as appropriate","Conchal bowl excision only","Remove the lobule","Mastoidectomy"],0,"Prominent-ear correction should match the deformity: absent antihelix, conchal excess, lobular prominence, or combinations. Overcorrection risks unnatural contour and canal distortion.","Diagnose the ear deformity before choosing the otoplasty maneuver.","What complication can arise from overly tight Mustardé sutures?","OR_prep"),
_c("v147_fp_13",F,"Rhinoplasty Tip Mechanics","A patient has a drooping nasal tip and wants increased rotation without excessive loss of projection. Which principle matters most?",["Understand how lateral-crural, medial-crural, septal, and tip-support maneuvers trade rotation against projection","Resect cartilage blindly","Tip rotation and projection are independent","Always shorten the caudal septum maximally"],0,"Tip position is governed by a linked support system. Maneuvers such as cephalic trim, tongue-in-groove, lateral crural steal, and septal work can change both rotation and projection, sometimes in opposite directions.","Every tip maneuver has a vector consequence.","How does thick skin affect the visible result of tip refinement?","OR_prep"),
_c("v147_fp_14",F,"Scar Management","A hypertrophic facial scar is raised and erythematous 4 months after injury but remains within the original wound boundaries. What management is reasonable?",["Silicone/pressure strategies, sun protection, and selected intralesional steroid or laser therapy depending on symptoms and maturation","Immediate wide excision in every case","Radiation as routine first-line therapy","Ignore symptomatic scars permanently"],0,"Hypertrophic scars differ from keloids because they stay within the wound boundaries and may regress. Treatment is staged around maturation, symptoms, tension, and pigment/vascular components.","Scar treatment is timed biology, not a single operation.","What feature would make a keloid diagnosis more likely?","boards"),
_c("v147_fp_15",F,"Skin Graft Selection","A shallow nasal sidewall defect has a healthy vascular bed and no exposed cartilage. What makes a full-thickness skin graft attractive?",["Better color/texture match and less contraction than split-thickness graft in a small facial defect","It survives without a vascular bed","It is ideal over bare cortical bone without periosteum","It never needs bolster fixation"],0,"Full-thickness grafts can provide excellent facial match and contract less, but require a well-vascularized bed, careful donor selection, immobilization, and contour planning.","A graft only survives where plasmatic imbibition and revascularization can occur.","What changes if cartilage is exposed without perichondrium?","OR_prep"),
_c("v147_fp_16",F,"Static Facial Reanimation","A frail patient has permanent facial paralysis and cannot undergo free functional muscle transfer. Which operation best addresses severe lower-lid ectropion?",["Static lower-lid tightening/canthoplasty with adjunctive eyelid loading as needed","Masseteric nerve transfer alone","Tongue-base reduction","Septoplasty"],0,"Static procedures improve resting symmetry and eye protection without restoring active movement. Eyelid protection may include platinum/gold loading, canthoplasty, tarsal strip, or brow procedures depending on the deficit.","For permanent paralysis, protect the cornea before chasing smile symmetry.","What static option can improve oral commissure position?","OR_prep"),
_c("v147_fp_17",F,"Structured Facial Trauma Examination","A panfacial trauma patient is about to be intubated and sedated. Which findings should be documented urgently beforehand if possible?",["Visual acuity/pupils, extraocular movements, facial nerve function, occlusion, CSF leak signs, and cranial nerve deficits","Hair color only","Only nasal airflow","Only blood pressure"],0,"Baseline vision and cranial nerve findings can become impossible to reconstruct after swelling, sedation, or surgery. A structured exam also documents occlusion, facial mobility, sensory deficits, and airway/CSF issues.","The pre-sedation exam is data you may never get back.","If the patient is already intubated and cannot cooperate, how can you still assess for globe-threatening injury?","overnight_call"),

# General ENT / emergencies
_c("v147_gen_01",G,"Antimicrobial Stewardship in Otolaryngology","A postoperative patient has mild erythema without purulence, fever, or systemic signs. What stewardship principle should guide antibiotics?",["Use the narrowest appropriate therapy only when infection is clinically supported, and reassess duration based on response/culture data","Start indefinite broad-spectrum antibiotics for any redness","Always double-cover MRSA and Pseudomonas","Never obtain cultures from a true abscess"],0,"Stewardship means distinguishing inflammation from infection, choosing therapy based on likely pathogens and local resistance, obtaining cultures when they will change care, and shortening or narrowing treatment when possible.","Every antibiotic order should answer: what infection, what pathogen, what duration?","boards"),
_c("v147_gen_02",G,"Cranial Nerve Examination / Skull Base Localization","A patient has hoarseness, dysphagia, ipsilateral shoulder weakness, and tongue deviation after skull-base surgery. What localization is most concerning?",["Lower cranial nerves IX-XII near the jugular foramen/hypoglossal canal region","Optic chiasm only","Isolated trigeminal V1 lesion","Middle ear ossicles only"],0,"Clusters of cranial neuropathies localize anatomically. IX-XI travel through the jugular foramen and XII through the hypoglossal canal nearby, so combined deficits suggest a lower skull-base process.","Multiple cranial nerves are a map, not a list.","What additional finding would suggest Horner syndrome and sympathetic-chain involvement?","boards"),
_c("v147_gen_03",G,"ENT Fluids / Electrolytes / Nutrition","A head-and-neck cancer patient with severe malnutrition begins aggressive tube feeds and develops hypophosphatemia, weakness, and arrhythmia. What is the concern?",["Refeeding syndrome","Simple dehydration only","Acute otitis media","BPPV"],0,"Refeeding after prolonged undernutrition can drive intracellular shifts of phosphate, potassium, and magnesium with dangerous cardiopulmonary consequences. High-risk patients need cautious caloric advancement and electrolyte/thiamine management.","Nutrition rescue can itself become an emergency if refeeding risk is ignored.","Which patients should receive prophylactic thiamine and close electrolyte monitoring?","overnight_call"),
_c("v147_gen_04",G,"ENT Imaging Fundamentals","A patient has suspected deep-neck abscess with trismus, fever, and neck swelling. Which imaging study is generally most useful for defining a drainable collection and vascular relationships?",["Contrast-enhanced CT neck","Noncontrast sinus x-ray","Routine chest ultrasound only","DEXA scan"],0,"Contrast CT rapidly evaluates deep-neck spaces, rim-enhancing collections, gas, airway displacement, mediastinal extension, and carotid/jugular relationships. MRI adds soft-tissue detail in selected cases but is slower and less available emergently.","Choose imaging by the clinical question: collection, vessel, bone, soft tissue, or function.","When would MRI be especially valuable in an ENT infection?","overnight_call"),
_c("v147_gen_05",G,"Evidence Interpretation / Outcomes Research","A retrospective study reports better outcomes after one operation, but the healthier patients were more likely to receive it. What bias threatens the conclusion?",["Confounding by indication/selection bias","Randomization bias","Blinding eliminates the issue","Publication date alone"],0,"Observational surgical studies are vulnerable to confounding because treatment choice reflects patient/tumor characteristics. Matching, regression, propensity methods, and sensitivity analyses can reduce but not erase unmeasured confounding.","Association is not causation just because the p value is small.","What problem does propensity-score matching address, and what can it not fix?","boards"),
_c("v147_gen_06",G,"Geriatric Otolaryngology / Frailty","An 84-year-old is technically resectable for major head-and-neck surgery but has severe frailty, falls, cognitive impairment, and limited reserve. What should guide treatment?",["Frailty, function, goals, expected recovery burden, and oncologic benefit rather than chronologic age alone","Age alone mandates no treatment","Technical resectability alone mandates surgery","Ignore cognition"],0,"Frailty predicts complications, institutionalization, and recovery better than age alone. Geriatric assessment can expose vulnerability and support prehabilitation or less burdensome treatment.","Operability is not only anatomy; it is physiologic reserve plus goals.","What prehabilitation domains can be optimized before surgery?","boards"),
_c("v147_gen_07",G,"Grafts / Implants / Biomaterials in ENT","A reconstructive implant becomes exposed through irradiated skin. What principle best predicts salvage success?",["Evaluate infection, vascularized soft-tissue coverage, implant stability, and whether the surrounding bed can heal; exposed foreign material often needs removal if coverage cannot be restored","Simply bury it under nonvascular scar","Antibiotics always cure exposure","Radiation improves implant integration"],0,"Implants depend on a healthy host bed and durable vascularized coverage. Infection, biofilm, motion, radiation injury, and soft-tissue deficiency can make conservative salvage fail.","An implant is only as durable as the tissue covering it.","How does autologous cartilage differ from synthetic material in infection/exposure behavior?","OR_prep"),
_c("v147_gen_08",G,"Immunocompromised Host in Otolaryngology","A neutropenic patient has severe facial pain, fever, and dusky nasal mucosa. What is the safest approach?",["Treat as possible acute invasive fungal rhinosinusitis with urgent biopsy/debridement and systemic antifungal therapy while reversing immunosuppression when feasible","Wait for black eschar","Routine outpatient allergy treatment","Delay action until cultures finalize"],0,"Immunocompromised patients can have muted inflammatory signs and rapidly invasive infection. Clinical suspicion should lower the threshold for urgent tissue diagnosis and multidisciplinary therapy.","In the immunocompromised host, absence of pus does not equal absence of dangerous infection.","What frozen-section finding establishes tissue invasion?","overnight_call"),
_c("v147_gen_09",G,"Laser / Energy Safety in Otolaryngology","During transoral laser surgery, which step most directly reduces airway-fire risk?",["Use laser-safe airway strategies, minimize oxidizer concentration when feasible, protect the tube/cuff, and coordinate activation with anesthesia","Increase oxygen to 100% during every laser pulse","Ignore wet pledgets","Use standard flammable tube tape"],0,"Airway fire requires fuel, oxidizer, and ignition. Laser safety removes or controls all three through equipment, oxygen strategy, wet protection, communication, and emergency readiness.","Airway fire prevention is a shared-team checklist, not a surgeon-only issue.","What are the immediate steps if an airway fire occurs?","OR_prep"),
_c("v147_gen_10",G,"Oral Manifestations of Systemic Disease","A patient has painful recurrent oral ulcers plus genital ulcers and uveitis. What systemic diagnosis should be considered?",["Behçet disease","Simple aphthae only","Ménière disease","Otosclerosis"],0,"Oral findings can be the presenting sign of autoimmune, hematologic, nutritional, infectious, and medication-related disease. Multisystem clues should prevent reflexive local treatment only.","The mouth can be the biopsy window or warning sign for systemic disease.","What oral findings can suggest hematologic malignancy or neutropenia?","boards"),
_c("v147_gen_11",G,"Pain Management in the Head & Neck Patient","A postoperative patient has severe pain but is opioid-naive and has OSA. What is the best analgesic principle?",["Use multimodal analgesia with acetaminophen/NSAID when appropriate, local/regional strategies, and opioid-sparing dosing with respiratory-risk awareness","High-dose opioid monotherapy","Avoid all nonopioids","Sedate until pain is gone"],0,"Multimodal analgesia reduces opioid exposure and adverse effects. OSA, frailty, renal/hepatic disease, bleeding risk, and procedure type modify medication choice and monitoring.","Good pain control is mechanism-based and risk-adjusted, not simply more opioid.","How does NSAID use change after a procedure with high bleeding concern?","postoperative_call"),
_c("v147_gen_12",G,"Systemic / Granulomatous Disease Manifestations in ENT","A patient has chronic nasal crusting, subglottic stenosis, pulmonary nodules, and renal dysfunction. What unifying diagnosis should be considered?",["Granulomatosis with polyangiitis","Allergic rhinitis only","BPPV","Otosclerosis"],0,"GPA can involve nose/sinuses, ears, subglottis, lungs, and kidneys. ENT manifestations may precede systemic diagnosis, and controlling inflammation is essential before repeated purely structural surgery.","When multiple ENT organs inflame together, think systemic before calling each problem separate.","How should active GPA affect timing of airway reconstruction?","boards"),
_c("v147_gen_13",G,"Wound Healing / Scar Biology in Head & Neck Surgery","A previously irradiated neck incision breaks down after salvage surgery. Why is healing impaired?",["Radiation causes hypovascular, hypocellular, fibrotic tissue with reduced regenerative reserve","Radiation increases angiogenesis indefinitely","The skin becomes immune to infection","Scar tissue has unlimited oxygen supply"],0,"Radiation damages microvasculature and fibroblast function, producing chronic fibrosis and poor tissue reserve. Reconstruction may require vascularized nonirradiated tissue rather than repeated local closure under tension.","When the wound bed cannot heal, bring healing capacity with the reconstruction.","What role can vascularized flap tissue play in salvage laryngectomy closure?","OR_prep"),
]
