"""v14.8 - Targeted closure of formal board/call/OR audit gaps."""

def _c(qid,d,t,s,ch,a,e,p,cb,f):
    return {"id":qid,"domain":d,"topic":t,"stem":s,"choices":ch,"answer":a,
            "explanation":e,"why_wrong":["Correct." if i==a else "This option misses the key clinical discriminator." for i in range(len(ch))],
            "board_pearl":p,"curveball":cb,"tier":"Curated depth-gate","mode":"Vignette","focus":f}

O="Otology / Neurotology"; R="Rhinology / Allergy / Skull Base"; H="Head & Neck Oncology"
L="Laryngology / Voice / Swallowing"; F="Facial Plastics / Trauma"

VIGNETTES_V148=[
_c("v148_oto_01",O,"Sudden Sensorineural Hearing Loss","A patient awakens with abrupt unilateral hearing loss and tinnitus. Otoscopy is normal and bedside testing suggests SNHL. What is the time-sensitive next step?",["Arrange urgent audiometry and begin guideline-concordant corticosteroid treatment when appropriate while evaluating for retrocochlear pathology","Wait several months for spontaneous recovery","Treat only with cerumen drops","Order hearing aids before confirming the loss"],0,"Sudden SNHL is an otologic urgency. Prompt confirmation and corticosteroid therapy within the treatment window can affect recovery; MRI or equivalent evaluation addresses retrocochlear causes.","Do not let a normal ear exam falsely reassure you when the cochlea may be failing.","How does salvage intratympanic steroid therapy fit if recovery is incomplete?","overnight_call"),
_c("v148_oto_02",O,"Chronic Otitis Media / Cholesteatoma","During tympanomastoid surgery for cholesteatoma, matrix is densely adherent over a dehiscent facial nerve. What is the safest operative principle?",["Prioritize facial-nerve preservation, use meticulous dissection with appropriate monitoring, and accept staged disease management if complete removal would create unacceptable nerve injury","Pull the matrix off blindly","Sacrifice the nerve routinely","Ignore residual-risk counseling"],0,"Cholesteatoma surgery balances eradication with preservation of facial nerve, labyrinth, dura, and hearing. High-risk adherent disease may justify staged management rather than uncontrolled injury.","A dry ear is not a success if the facial nerve is sacrificed unnecessarily.","How would labyrinthine fistula change matrix-dissection strategy?","OR_prep"),

_c("v148_rh_01",R,"Invasive Fungal Rhinosinusitis","A neutropenic patient develops facial pain, fever, and a pale insensate middle turbinate. What should happen tonight?",["Urgent endoscopic biopsy with frozen section, systemic antifungal therapy, reversal of immunosuppression when possible, and prompt debridement if invasion is confirmed","Wait for black eschar","Treat as uncomplicated bacterial sinusitis only","Schedule routine follow-up in six weeks"],0,"Acute invasive fungal rhinosinusitis can progress over hours. Early tissue diagnosis and coordinated antifungal/surgical treatment are critical; black eschar is a late finding.","In an immunocompromised patient, tissue ischemia and sensory loss are emergency clues.","What histologic feature confirms angioinvasion?","overnight_call"),
_c("v148_rh_02",R,"Orbital Complications of Sinusitis","A child with acute sinusitis develops painful proptosis, restricted extraocular movements, and reduced visual acuity. What is the immediate priority?",["Urgent contrast imaging, IV antibiotics, ophthalmology/ENT evaluation, and drainage when vision is threatened or an abscess is present","Outpatient nasal steroid only","Wait for spontaneous improvement despite vision loss","Perform allergy testing first"],0,"Postseptal orbital complications can threaten vision and intracranial spread. Visual change, ophthalmoplegia, proptosis, or abscess requires urgent multidisciplinary management.","Vision is the clock in orbital sinusitis complications.","Which findings distinguish preseptal cellulitis from orbital cellulitis?","overnight_call"),
_c("v148_rh_03",R,"Epistaxis Surgical Control","A patient has brisk posterior epistaxis with blood filling the oropharynx despite topical vasoconstrictor and anterior packing. What is the safest next step?",["Stabilize airway/hemodynamics, reverse correctable coagulopathy, and escalate to definitive posterior control such as endoscopic sphenopalatine artery management or embolization depending on the situation","Keep adding anterior packing indefinitely","Discharge while actively bleeding","Biopsy the septum blindly"],0,"Persistent posterior epistaxis is an airway and hemorrhage problem. Resuscitation and definitive vascular control should not be delayed by repeated ineffective bedside maneuvers.","Posterior epistaxis can become an airway emergency before it becomes a hemoglobin problem.","What comorbidities make posterior packing especially risky?","overnight_call"),
_c("v148_rh_04",R,"Epistaxis Surgical Control","During endoscopic control of refractory posterior epistaxis, where is the key arterial target usually found?",["Branches of the sphenopalatine artery entering near the posterior middle meatus/sphenopalatine foramen","The facial artery at the mandibular border only","The superior thyroid artery","The middle meningeal artery through the ear canal"],0,"Endoscopic sphenopalatine artery ligation/cautery requires identifying the posterior lateral nasal wall and controlling all relevant branches near the sphenopalatine foramen.","Failure often comes from missed branches, not from inadequate cautery energy.","When would angiographic embolization be preferred or added?","OR_prep"),

_c("v148_hn_01",H,"Total Laryngectomy","A total-laryngectomy patient arrives dyspneic with thick crust obstructing the stoma. Oxygen is being placed over the mouth without improvement. What is the critical airway principle?",["This patient breathes only through the neck stoma; oxygenate/ventilate through the stoma and clear the obstruction","Intubate orally through the mouth into the lungs","Seal the stoma","Wait for spontaneous improvement"],0,"After total laryngectomy there is complete separation of airway and pharynx. Oral/nasal oxygen cannot reach the lungs; all airway rescue must occur through the stoma.","A laryngectomy stoma is the only airway.","How does this differ from a tracheostomy patient whose upper airway may still communicate with the lungs?","overnight_call"),
_c("v148_hn_02",H,"Total Laryngectomy","During total laryngectomy, what closure principle most reduces pharyngocutaneous fistula risk?",["Create a tension-free, well-vascularized watertight pharyngeal closure and consider vascularized reinforcement in high-risk salvage fields","Leave devascularized mucosa under tension","Avoid checking the closure","Place the stoma through the pharyngeal suture line"],0,"Fistula risk rises with prior radiation, malnutrition, tension, and poor tissue quality. Sound mucosal closure and vascularized reinforcement are central operative principles.","In salvage laryngectomy, bring healthy blood supply to a hostile wound bed.","When would a pectoralis or free-tissue reinforcement flap be particularly valuable?","OR_prep"),
_c("v148_hn_03",H,"Free-Flap Monitoring / Compromise / Salvage","Six hours after oral-cavity free-flap reconstruction, the flap becomes cool, pale, and loses Doppler signal. What should happen?",["Urgent return to the OR for exploration of arterial inflow/pedicle compromise","Observe until morning","Apply topical antibiotics only","Start speech therapy"],0,"Early free-flap vascular compromise is time sensitive. A pale cool flap with absent signal suggests arterial insufficiency and warrants immediate operative assessment rather than prolonged bedside observation.","Flap salvage is measured in hours, not clinic days.","How does venous congestion look different and what technical causes should be sought?","OR_prep"),
_c("v148_hn_04",H,"Complications of Neck Surgery","A patient develops rapidly expanding neck swelling, stridor, and respiratory distress several hours after major neck surgery. What is the priority?",["Treat as a compressive neck hematoma: call for help, release the wound immediately if needed to relieve airway compression, and secure the airway/return to OR","Send for routine outpatient CT first","Wait for the next morning round","Apply an ice pack only"],0,"An expanding postoperative neck hematoma can cause lethal airway compression. Clinical deterioration overrides delays for imaging; decompression and airway control are immediate priorities.","A tight postoperative neck can become an airway faster than it becomes a bruising problem.","How does management differ if the patient is stable with a small nonexpanding collection?","overnight_call"),

_c("v148_lar_01",L,"Tracheobronchial Endoscopy Principles","During rigid bronchoscopy for foreign-body removal, oxygen saturation suddenly falls and ventilation becomes difficult. What is the immediate team response?",["Stop instrumentation, re-establish a patent ventilating airway through the bronchoscope, communicate with anesthesia, and assess for obstruction, bronchospasm, bleeding, or pneumothorax","Continue blindly until the object is removed","Ignore the saturation until the procedure ends","Remove all airway equipment and leave the patient apneic"],0,"Rigid bronchoscopy is a shared-airway procedure. Acute desaturation requires coordinated restoration of ventilation and rapid identification of mechanical or pulmonary causes.","In shared-airway surgery, loss of ventilation ends the elective part of the procedure.","What finding after difficult extraction should make you suspect pneumothorax?","overnight_call"),
_c("v148_lar_02",L,"Acute / Chronic Laryngopharyngitis","An adult with severe odynophagia now has drooling, muffled voice, inspiratory stridor, and rapidly increasing work of breathing. What is the priority?",["Treat this as a threatened supraglottic airway and arrange controlled airway evaluation with ENT/anesthesia rather than routine outpatient laryngitis care","Give voice rest and discharge","Schedule elective voice therapy","Wait for antibiotics to work before assessing the airway"],0,"Once stridor, drooling, or respiratory distress appears, the problem is no longer uncomplicated laryngitis. Airway stabilization and direct evaluation supersede routine symptomatic care.","A voice complaint becomes an airway emergency when breathing and secretion handling deteriorate.","What bedside actions can worsen a critically narrowed supraglottic airway?","overnight_call"),
_c("v148_lar_03",L,"Aspiration-Prevention Surgery","A neurologically impaired patient with known severe aspiration suddenly develops hypoxemia after a large witnessed aspiration event. What is the immediate priority?",["Stabilize oxygenation/ventilation, suction as appropriate, evaluate pulmonary injury, and treat infection only when clinically indicated; definitive aspiration-prevention decisions follow stabilization","Schedule elective aspiration surgery before stabilizing the lungs","Give oral feeding immediately","Ignore the event because aspiration is chronic"],0,"Acute aspiration is first a respiratory emergency. Definitive separation or closure procedures are considered after stabilization when recurrent aspiration remains life threatening despite conservative management.","Chronic aspiration has elective solutions; acute hypoxemia has immediate airway priorities.","What features make long-term aspiration-prevention surgery reasonable after recovery?","overnight_call"),

_c("v148_fp_01",F,"Septal Hematoma","A teenager presents after nasal trauma with bilateral boggy septal swelling and increasing obstruction. What should be done urgently?",["Drain the septal hematoma, prevent reaccumulation, and provide appropriate antibiotic/follow-up care","Wait several weeks for swelling to resolve","Perform cosmetic rhinoplasty immediately","Treat with antihistamines only"],0,"Septal hematoma separates cartilage from its blood supply and can rapidly cause necrosis, abscess, and saddle deformity. It is a same-day drainage problem.","Every nasal trauma exam must look specifically for a septal hematoma.","Why are children particularly vulnerable to long-term deformity after septal cartilage injury?","overnight_call"),
_c("v148_fp_02",F,"Mandibular Biomechanics and Occlusion","During ORIF of a displaced mandibular body fracture, what should be established before final plate fixation?",["Reproducible premorbid dental occlusion with appropriate maxillomandibular relationship, then stable reduction along biomechanical lines","Plate the fracture first and accept any resulting bite","Remove healthy teeth to create space","Ignore condylar position"],0,"Occlusion is the functional reference for mandibular reduction. Fixing a malreduced mandible can create a stable but wrong bite that is difficult to correct later.","In mandible trauma, the teeth are an intraoperative reduction gauge.","How do comminution or an edentulous mandible change fixation strategy?","OR_prep"),
]
