"""v13.7 — canonical coverage closure for Thyroid/Parathyroid/Salivary,
Sleep Surgery, and Facial Plastics/Trauma.

Targets every topic listed as missing for these domains in the live v13.6 audit.
"""


def Q(qid, domain, topic, stem, choices, answer, explanation, pearl, curveball):
    return {
        "id": qid, "domain": domain, "topic": topic, "stem": stem,
        "choices": choices, "answer": answer, "explanation": explanation,
        "why_wrong": ["Compare the option with the management principle in the explanation and the specific clinical context." for _ in choices],
        "board_pearl": pearl, "curveball": curveball,
        "tier": "Curated board/call/OR", "mode": "Vignette",
    }

TPS = "Thyroid / Parathyroid / Salivary"
SLP = "Sleep Surgery"
FPT = "Facial Plastics / Trauma"

VIGNETTES_V137 = [
    # Thyroid / Parathyroid / Salivary
    Q("v137_tps_01", TPS, "Acute Sialadenitis / Sjögren",
      "An elderly dehydrated inpatient develops painful unilateral parotid swelling with purulence from Stensen duct. What is the best initial management?",
      ["Hydration, gland massage/sialogogues, antistaphylococcal antibiotics and drainage if abscess forms", "Immediate total parotidectomy", "Radioactive iodine", "Steroids alone"], 0,
      "Acute bacterial sialadenitis is promoted by salivary stasis; restore flow, treat infection and drain an abscess if present.",
      "Milk the duct on exam: purulence localizes infection and can provide a culture.",
      "The patient instead has chronic bilateral dryness, arthralgias and recurrent swelling. What autoimmune workup becomes relevant?"),

    Q("v137_tps_02", TPS, "Anaplastic Thyroid Cancer",
      "A 74-year-old has a thyroid mass that doubled in size in weeks, hoarseness and tracheal compression. What is the highest-priority management principle?",
      ["Secure a rapid tissue diagnosis and multidisciplinary airway/oncologic plan, including molecular testing for actionable alterations", "Routine lobectomy without staging", "Observe for 6 months", "RAI is reliably curative"], 0,
      "Anaplastic thyroid cancer is rapidly lethal and can threaten the airway; diagnosis, staging, airway strategy and systemic/radiation planning must proceed urgently and in parallel.",
      "Do not create a difficult tracheostomy through tumor reflexively; airway intervention should be individualized with anatomy and goals in mind.",
      "A BRAF V600E mutation is found. How can that change systemic treatment options?"),

    Q("v137_tps_03", TPS, "Central Neck Dissection",
      "A patient with papillary thyroid carcinoma has a biopsy-proven metastatic level VI node. What neck operation is indicated?",
      ["Therapeutic compartment-oriented central neck dissection", "Berry-picking only the palpable node", "No nodal surgery because central nodes never matter", "Routine radical neck dissection"], 0,
      "Clinically involved central nodes are treated with a therapeutic compartment dissection; isolated node plucking increases risk of leaving occult disease and complicates reoperation.",
      "Central dissection is bounded by recurrent laryngeal nerves, carotids, hyoid/upper mediastinum and carries RLN/parathyroid risk.",
      "How does the decision differ for a cN0 low-risk papillary cancer?"),

    Q("v137_tps_04", TPS, "Differentiated Thyroid Cancer",
      "A patient has a 1.4 cm intrathyroidal unilateral papillary carcinoma without nodal disease or aggressive features and prefers surgery. What extent is generally sufficient?",
      ["Thyroid lobectomy is an appropriate definitive operation in a properly selected patient", "Mandatory total thyroidectomy", "Total laryngectomy", "No surgery can be offered"], 0,
      "Contemporary risk-adapted differentiated-thyroid-cancer care accepts lobectomy for selected small unilateral intrathyroidal cancers without clinically apparent nodes or aggressive features.",
      "Extent of surgery should follow oncologic risk and patient goals—not the historical reflex that all thyroid cancer requires total thyroidectomy.",
      "What pathologic findings after lobectomy would make completion thyroidectomy more reasonable?"),

    Q("v137_tps_05", TPS, "Four-Gland Parathyroid Exploration",
      "A patient with primary hyperparathyroidism has negative localization imaging but meets criteria for surgery. What operative strategy is appropriate?",
      ["Bilateral four-gland exploration by an experienced parathyroid surgeon", "Cancel surgery because imaging is negative", "Remove the thyroid gland", "Excise only the first normal gland encountered"], 0,
      "Localization helps choose an approach but does not establish the diagnosis or determine whether surgery is indicated. Nonlocalized disease can be managed with systematic bilateral exploration.",
      "Imaging localizes disease; biochemistry diagnoses hyperparathyroidism.",
      "How does suspected multigland disease change the value of a focused approach?"),

    Q("v137_tps_06", TPS, "Indeterminate Thyroid Cytology / Molecular Testing",
      "A 2 cm thyroid nodule is Bethesda III after repeat FNA. Ultrasound is not highly suspicious. What is the most appropriate framework?",
      ["Integrate ultrasound risk, clinical factors, patient preference and optional molecular testing to choose surveillance versus diagnostic surgery", "Total thyroidectomy is mandatory", "RAI without diagnosis", "Ignore the cytology"], 0,
      "Indeterminate cytology is a risk-estimation problem. Molecular testing can refine malignancy probability but should be interpreted in the context of pretest risk and how the result would change management.",
      "A molecular test is useful only if its result can change what you do.",
      "How would a highly suspicious ultrasound phenotype change the pretest probability?"),

    Q("v137_tps_07", TPS, "MEN2 / RET",
      "A patient with medullary thyroid carcinoma is found to carry a germline RET pathogenic variant. What must be addressed before elective thyroid surgery?",
      ["Screen for pheochromocytoma and treat it first if present", "Give RAI", "Ignore family implications", "Perform parathyroidectomy in every patient regardless of subtype"], 0,
      "MEN2 can include pheochromocytoma and hyperparathyroidism. Undiagnosed pheochromocytoma can cause a catastrophic perioperative crisis, so it must be excluded before thyroid surgery.",
      "Medullary thyroid carcinoma should trigger germline RET consideration and family counseling.",
      "How does RET genotype influence timing of prophylactic thyroidectomy in affected children?"),

    Q("v137_tps_08", TPS, "Parathyroid Carcinoma",
      "A patient has calcium 14.8 mg/dL, PTH many-fold above normal, a firm invasive parathyroid mass and ipsilateral vocal-fold paralysis. What operative principle is most important?",
      ["En bloc oncologic resection without capsular violation when feasible", "Shell out the gland piecemeal", "Needle biopsy through the mass routinely", "Observe because parathyroid cancer is indolent"], 0,
      "Parathyroid carcinoma is suspected with severe hypercalcemia and invasive features; initial en bloc resection offers the best chance of control and avoiding tumor seeding.",
      "Avoid violating the capsule or performing routine FNA when carcinoma is suspected.",
      "What biochemical problem often dominates recurrent/metastatic parathyroid carcinoma care?"),

    Q("v137_tps_09", TPS, "Pleomorphic Adenoma / Warthin Tumor",
      "A mobile superficial parotid mass has FNA consistent with pleomorphic adenoma. Why is simple enucleation generally avoided?",
      ["Microscopic pseudopods and capsule violations increase recurrence risk; remove with an appropriate margin while preserving the facial nerve", "Pleomorphic adenoma is always malignant", "The facial nerve must be sacrificed", "No treatment is ever needed"], 0,
      "Pleomorphic adenoma has microscopic extensions and recurrence risk after capsule violation; surgery should remove the tumor intact with an appropriate parotid technique.",
      "Warthin tumor can often be observed in selected patients; pleomorphic adenoma has a different natural history and recurrence/malignant-transformation concern.",
      "How does a deep-lobe tumor alter the surgical approach and nerve dissection?"),

    Q("v137_tps_10", TPS, "Ranula",
      "A young adult has a painless bluish floor-of-mouth swelling. MRI shows a cystic lesion extending through the mylohyoid into the neck. What management best minimizes recurrence for a plunging ranula?",
      ["Address the ipsilateral sublingual gland, with management of the ranula as needed", "Repeated aspiration alone", "Remove the submandibular gland routinely", "Parotidectomy"], 0,
      "Ranulas arise from the sublingual gland; recurrence is high when only the cyst is drained or excised without treating the source gland.",
      "For a plunging ranula, treat the source—not just the neck component.",
      "Which lingual-nerve and submandibular-duct relationships matter during sublingual-gland excision?"),

    Q("v137_tps_11", TPS, "Reoperative Hyperparathyroidism",
      "A patient remains hypercalcemic after prior parathyroid surgery. Before reexploration, what is most important?",
      ["Reconfirm the biochemical diagnosis and obtain high-quality reoperative localization before entering a scarred neck", "Explore blindly without imaging", "Assume the first operation removed the wrong thyroid lobe", "Operate without reviewing prior pathology"], 0,
      "Reoperative parathyroid surgery carries greater RLN and devascularization risk; confirm persistent/recurrent disease, review prior records and localize before surgery.",
      "In a reoperative neck, information is a safety tool—old operative notes and pathology matter.",
      "What ectopic locations should be specifically reconsidered after a failed exploration?"),

    Q("v137_tps_12", TPS, "Reoperative Thyroid Surgery",
      "A patient needs surgery for recurrent thyroid cancer in a previously dissected central neck. What preoperative assessment is essential?",
      ["Document vocal-fold mobility and map recurrent disease with high-resolution imaging before reoperation", "Skip laryngoscopy because the voice is normal", "Perform blind exploration", "Avoid reviewing the prior operative report"], 0,
      "Reoperative thyroid surgery has increased RLN and parathyroid risk; baseline nerve function, disease mapping and prior operative details are essential.",
      "A normal speaking voice does not prove normal vocal-fold mobility.",
      "If one RLN is already paralyzed, how does that alter the risk discussion for contralateral surgery?"),

    Q("v137_tps_13", TPS, "Secondary / Tertiary Hyperparathyroidism",
      "A dialysis patient has severe refractory hyperparathyroidism with bone pain and markedly elevated PTH despite optimized medical therapy. Which operative concept is appropriate?",
      ["Subtotal parathyroidectomy or total parathyroidectomy with autotransplantation depending on context", "Focused excision of a single presumed adenoma in all cases", "Thyroid lobectomy", "No surgical option exists"], 0,
      "Renal secondary hyperparathyroidism is usually multigland hyperplasia; operative strategies address all glands rather than a single focused adenoma.",
      "Tertiary hyperparathyroidism is autonomous hypersecretion after longstanding secondary disease, often after transplant.",
      "What postoperative electrolyte complication requires aggressive monitoring?"),

    Q("v137_tps_14", TPS, "Sialendoscopy",
      "A patient has recurrent meal-related submandibular swelling from a small mobile hilar duct stone. Which gland-preserving treatment is most appropriate?",
      ["Sialendoscopy with stone retrieval or combined minimally invasive technique depending on size/location", "Immediate neck dissection", "Total parotidectomy", "RAI"], 0,
      "Sialendoscopy permits diagnostic and therapeutic management of obstructive salivary disease while preserving the gland in many patients.",
      "Stone size, mobility and location determine basket retrieval, lithotripsy, transoral combined approach or gland excision.",
      "When is a combined transoral approach more useful than endoscopic retrieval alone?"),

    Q("v137_tps_15", TPS, "Submandibular Gland Excision",
      "During submandibular gland excision, which structures require deliberate protection?",
      ["Marginal mandibular, lingual and hypoglossal nerves", "Optic nerve only", "Facial nerve trunk within the gland", "Recurrent laryngeal nerve only"], 0,
      "Submandibular surgery places the marginal mandibular nerve superiorly and the lingual/hypoglossal nerves deep to the gland at risk; Wharton duct is ligated distally.",
      "Know the nerve-duct-ganglion relationship before dividing the deep lobe attachments.",
      "How does inflammation from chronic stones change the dissection risk?"),

    Q("v137_tps_16", TPS, "Thyroid Eye Disease / Graves Ophthalmopathy",
      "A patient with Graves disease develops progressive proptosis, diplopia and reduced color vision. What finding makes this an ophthalmic emergency?",
      ["Evidence of compressive optic neuropathy", "Mild lid retraction alone", "Stable cosmetic proptosis", "Dry eye that responds to lubrication"], 0,
      "Reduced acuity/color vision, afferent pupillary defect or visual-field compromise can indicate dysthyroid optic neuropathy requiring urgent steroid and/or orbital-decompression management with ophthalmology.",
      "Thyroid eye disease activity and severity—not thyroid hormone level alone—drive orbital treatment.",
      "Why is smoking cessation especially important in thyroid eye disease?"),

    # Sleep Surgery
    Q("v137_slp_01", SLP, "Central Events / Hypoventilation",
      "A PSG shows frequent apneas without respiratory effort and sustained nocturnal hypercapnia. What is the key next step before offering upper-airway surgery?",
      ["Differentiate central apnea and hypoventilation causes and treat the underlying physiology", "Perform UPPP", "Assume tongue-base obstruction", "Ignore CO2 data"], 0,
      "Central events and hypoventilation are not fixed by pharyngeal enlargement; identify medications, heart failure, neurologic disease, obesity hypoventilation or other causes.",
      "Always classify the respiratory event before choosing an anatomic operation.",
      "How would chronic opioid use alter the differential?"),

    Q("v137_slp_02", SLP, "Circadian Rhythm Sleep-Wake Disorders",
      "A teenager cannot fall asleep until 3 AM but sleeps normally from 3 AM to 11 AM when allowed. What is the most likely framework?",
      ["Delayed sleep-wake phase disorder managed with schedule/light timing rather than airway surgery", "Severe OSA by history alone", "Narcolepsy", "Central apnea"], 0,
      "Circadian disorders involve misalignment of sleep timing, not upper-airway obstruction; history and sleep logs/actigraphy are often more informative than airway examination.",
      "Sleep surgery treats obstruction, not every complaint labeled insomnia or sleepiness.",
      "What timing of morning light exposure generally helps advance a delayed sleep phase?"),

    Q("v137_slp_03", SLP, "Down Syndrome Pediatric HNS",
      "A child with Down syndrome has persistent severe OSA after adenotonsillectomy despite PAP intolerance. What is an important next evaluation before hypoglossal-nerve stimulation?",
      ["Confirm candidacy with age/size criteria, PSG severity and DISE pattern while evaluating multilevel obstruction", "Implant without PSG", "Assume adenotonsillectomy failure excludes all surgery", "Perform adult UPPP routinely"], 0,
      "Selected children/adolescents with Down syndrome and persistent OSA may benefit from HNS, but candidacy requires careful phenotype and airway assessment.",
      "Down syndrome OSA is often multilevel; tongue-base obstruction, macroglossia and hypotonia matter after adenotonsillectomy.",
      "Which DISE collapse pattern is unfavorable for conventional HNS candidacy?"),

    Q("v137_slp_04", SLP, "HNS Activation / Programming",
      "One month after uncomplicated hypoglossal-nerve stimulator implantation, the incision is healed. What is the usual next phase of therapy?",
      ["Device activation followed by gradual amplitude advancement and later efficacy titration", "Immediate maximum-amplitude stimulation on postoperative day 1", "Remove the sensing lead", "No follow-up is required"], 0,
      "HNS requires postoperative activation, acclimatization and programming; therapeutic success depends on both implantation and longitudinal optimization.",
      "Think of HNS as a therapy program, not a one-day operation.",
      "What symptoms suggest stimulation amplitude or electrode configuration needs adjustment?"),

    Q("v137_slp_05", SLP, "HNS Troubleshooting / Nonresponse",
      "A patient uses HNS nightly but residual AHI remains high. What is the best next step?",
      ["Confirm adherence, electrode/sensing function, tongue-motion pattern, residual collapse and programming before labeling treatment failure", "Automatically explant the device", "Increase amplitude without evaluation", "Add sedatives"], 0,
      "HNS nonresponse may reflect programming, sensing, unfavorable anatomy, weight change or residual multilevel collapse; troubleshooting should identify the failure mechanism.",
      "More stimulation is not always better—excess amplitude can worsen comfort or produce nonbeneficial tongue motion.",
      "How can repeat DISE or awake endoscopy with stimulation help?"),

    Q("v137_slp_06", SLP, "Lingual Tonsil / Tongue-Base Obstruction",
      "A child has persistent OSA after adenotonsillectomy. DISE shows marked lingual tonsillar hypertrophy obstructing the vallecula. What procedure directly targets the obstruction?",
      ["Lingual tonsillectomy", "Repeat adenoidectomy despite no adenoid regrowth", "Septoplasty alone", "No surgical option"], 0,
      "Lingual tonsil hypertrophy can be an important residual obstructive site, particularly in syndromic or previously operated children.",
      "Use DISE to match the operation to the level and pattern of collapse.",
      "What postoperative complications deserve particular attention after tongue-base surgery?"),

    Q("v137_slp_07", SLP, "Narcolepsy / Central Hypersomnolence Recognition",
      "A young adult has irresistible daytime sleep attacks, cataplexy and sleep paralysis despite adequate sleep time. What is the best next step?",
      ["Refer for sleep-medicine evaluation with PSG followed by MSLT when appropriate", "Offer palatal surgery", "Diagnose OSA without testing", "Treat with nasal steroids only"], 0,
      "Cataplexy plus excessive sleepiness is highly suggestive of narcolepsy; central hypersomnolence requires sleep-medicine testing rather than upper-airway surgery.",
      "Not all daytime sleepiness is OSA—boards test whether you recognize the wrong disease for surgery.",
      "Why must insufficient sleep and untreated OSA be addressed before interpreting an MSLT?"),

    Q("v137_slp_08", SLP, "PAP Troubleshooting",
      "A patient with severe OSA abandons CPAP because of nasal dryness, leak and pressure intolerance. What is the best first approach before declaring PAP failure?",
      ["Optimize mask fit, humidification, nasal obstruction and pressure mode with sleep-team support", "Proceed directly to maxillomandibular advancement", "Stop therapy indefinitely", "Prescribe sedatives to tolerate the mask"], 0,
      "PAP intolerance is often modifiable. Adequate troubleshooting should precede irreversible surgery unless there is a compelling reason otherwise.",
      "A failed device trial is not the same as a failed PAP program.",
      "Which anatomic nasal problems can meaningfully worsen PAP tolerance?"),

    Q("v137_slp_09", SLP, "Palatal Surgery",
      "During counseling for palatal surgery for OSA, which complication should be specifically discussed because it relates to velopharyngeal function and swallowing?",
      ["Velopharyngeal insufficiency or dysphagia", "Retinal detachment", "Facial paralysis in every case", "Sensorineural deafness"], 0,
      "Palatal surgery can improve retropalatal obstruction but may cause pain, dysphagia, foreign-body sensation, stenosis or velopharyngeal dysfunction depending on technique.",
      "Procedure selection should preserve function while changing collapse mechanics.",
      "How does concentric versus anteroposterior palatal collapse influence procedure choice?"),

    Q("v137_slp_10", SLP, "Palatal Surgery Selection for OSA",
      "DISE shows isolated anteroposterior velum collapse without major tongue-base obstruction in a PAP-intolerant patient. What is the best surgical principle?",
      ["Select a palatal procedure matched to the collapse pattern rather than applying the same UPPP to every patient", "Tongue-base resection is mandatory", "No role exists for DISE", "Nasal surgery alone cures all OSA"], 0,
      "Modern sleep surgery is phenotype-based; palatal techniques aim to reposition or stiffen specific patterns of velopharyngeal collapse.",
      "The operation should follow the collapse pattern, not merely the AHI.",
      "How would complete concentric collapse change HNS candidacy?"),

    Q("v137_slp_11", SLP, "Pediatric PSG Interpretation",
      "A 6-year-old has an obstructive AHI of 8 events/hour with oxygen desaturations and adenotonsillar hypertrophy. How should this be interpreted?",
      ["This represents clinically significant pediatric OSA; pediatric thresholds are lower than adult thresholds", "This is normal because adult mild OSA starts at 5", "Only central events matter in children", "PSG cannot guide pediatric treatment"], 0,
      "Children use different PSG norms and lower AHI thresholds; severity must also incorporate gas exchange, symptoms, comorbidities and age.",
      "Never apply adult AHI thresholds mechanically to children.",
      "Which comorbidities increase the need for postoperative monitoring after adenotonsillectomy?"),

    Q("v137_slp_12", SLP, "Restless Legs / Periodic Limb Movement Disorders",
      "A patient referred for 'poor sleep' describes an evening urge to move the legs relieved by walking. Airway exam is normal. What is the best next step?",
      ["Evaluate for restless legs syndrome, including iron status and medication contributors", "Offer UPPP", "Implant HNS", "Diagnose insomnia only"], 0,
      "RLS is a clinical sensorimotor disorder and can mimic sleep disruption from OSA; iron deficiency and medications are modifiable contributors.",
      "Sleep-surgery triage includes recognizing when the problem is not obstructive.",
      "What ferritin/iron issue can contribute even without frank anemia?"),

    Q("v137_slp_13", SLP, "Tongue Base Surgery",
      "A PAP-intolerant adult has severe OSA and DISE shows dominant tongue-base collapse from macroglossia without complete concentric palatal collapse. Which principle is most appropriate?",
      ["Choose a tongue-base intervention matched to anatomy, potentially as part of multilevel treatment", "Palatal surgery alone regardless of collapse", "No procedure can target tongue base", "Tracheostomy is always first-line"], 0,
      "Tongue-base surgery includes reduction, advancement, suspension and other techniques selected by anatomy and collapse pattern; multilevel disease may require combined treatment.",
      "Tongue-base surgery carries edema and bleeding risk—postoperative airway planning is part of the operation.",
      "How would severe retrognathia shift consideration toward skeletal surgery?"),

    # Facial Plastics / Trauma
    Q("v137_fpt_01", FPT, "Aesthetic Facial Analysis",
      "Before elective rhinoplasty, why are standardized frontal, oblique, lateral and basal photographs plus facial-proportion analysis important?",
      ["They establish reproducible anatomy, asymmetry and goals before changing facial balance", "They replace physical examination", "They guarantee a specific cosmetic result", "They are useful only for billing"], 0,
      "Aesthetic surgery starts with objective analysis of proportions, asymmetry, skin/soft tissue and patient goals; surgery should solve identified structural problems.",
      "Document pre-existing asymmetry because surgery rarely creates a perfectly symmetric face.",
      "How does thick versus thin skin alter rhinoplasty planning?"),

    Q("v137_fpt_02", FPT, "Aging Face / Injectables / Resurfacing",
      "A patient seeks treatment for dynamic glabellar rhytids and static photodamage. Which pairing best matches mechanism to treatment?",
      ["Neuromodulator for dynamic muscle-driven lines and resurfacing/skin-directed therapy for photodamage", "Filler alone for all dynamic lines", "Facelift for epidermal pigment only", "No distinction is needed"], 0,
      "Aging-face treatment should match tissue layer and mechanism: neuromodulators reduce muscular activity, fillers restore volume, resurfacing treats skin, and surgery repositions lax tissue.",
      "The safest aesthetic plan is anatomy-specific, not product-specific.",
      "Which vascular complication of filler requires immediate recognition?"),

    Q("v137_fpt_03", FPT, "Alar Retraction / Nasal Vestibular Stenosis",
      "A patient develops external nasal-valve narrowing and alar retraction after overresection during rhinoplasty. What reconstructive principle is most appropriate?",
      ["Restore lining/support with grafting or local tissue as needed rather than further cartilage resection", "Remove more lower lateral cartilage", "Turbinate reduction alone", "Observe despite fixed severe stenosis"], 0,
      "Alar retraction and vestibular stenosis are structural deficits that often require restoration of support and/or lining.",
      "When surgery removed support, the revision operation usually needs to add structure—not remove more.",
      "Which grafts can support the alar rim or lateral crus?"),

    Q("v137_fpt_04", FPT, "Bilobed Flap",
      "A small-to-moderate nasal tip defect after Mohs surgery has adjacent lax dorsal/sidewall skin. What is a key bilobed-flap design principle?",
      ["Recruit adjacent tissue through two transposition lobes while minimizing standing cones and excessive tension", "Make the second lobe larger than the defect routinely", "Ignore relaxed skin tension lines", "Use it for every full-thickness nasal defect regardless of size"], 0,
      "The bilobed flap redistributes tension and recruits nearby nasal skin; careful lobe sizing, pivot point and arc prevent pincushioning and distortion.",
      "On the nose, flap geometry matters because a few millimeters of tension can distort the alar rim.",
      "What complication is encouraged by an overly broad arc of rotation?"),

    Q("v137_fpt_05", FPT, "Cervicofacial Flap",
      "A large lateral cheek defect after cancer resection has exposed soft tissue but no need for free-tissue bulk. Which reconstruction offers good color/texture match using regional laxity?",
      ["Cervicofacial advancement/rotation flap", "Split-thickness graft as the only possible option", "Forehead flap", "No closure"], 0,
      "Cervicofacial flaps recruit broad adjacent cheek/neck skin for large defects with excellent match; design must respect facial-nerve planes and lower-eyelid tension.",
      "For large cheek reconstruction, protect the lower eyelid from vertical traction and ectropion.",
      "How does a defect approaching the lower lid change suspension planning?"),

    Q("v137_fpt_06", FPT, "Dynamic Facial Reanimation",
      "A patient has long-standing complete facial paralysis with irreversibly atrophic native smile musculature. Which option can restore active smile movement?",
      ["Free functional muscle transfer powered by an appropriate donor nerve", "Static sling alone", "Skin graft", "Botulinum toxin to the paralyzed side only"], 0,
      "When native facial muscles are no longer reinnervatable, dynamic reanimation often requires transfer of functioning muscle with motor innervation.",
      "Time since denervation determines whether you reinnervate native muscle or bring new muscle.",
      "Compare masseteric nerve and cross-face nerve graft as donor strategies for smile spontaneity and strength."),

    Q("v137_fpt_07", FPT, "Facial Synkinesis / Static-Dynamic Rehabilitation",
      "A patient recovering from Bell palsy develops involuntary eye closure whenever smiling. What is the best treatment framework?",
      ["Facial neuromuscular retraining with targeted botulinum toxin, reserving surgery for selected refractory patterns", "Strengthen every facial muscle maximally", "Ignore it because synkinesis cannot be treated", "Immediate free flap"], 0,
      "Synkinesis reflects misdirected reinnervation; therapy aims to reduce unwanted co-contraction and retrain selective movement.",
      "Facial paralysis recovery can produce too much linked movement, not simply weakness.",
      "When can selective neurectomy or myectomy be considered?"),

    Q("v137_fpt_08", FPT, "Forehead Flap / Nasal Reconstruction",
      "A large full-thickness nasal defect includes skin and cartilage loss. Why is a paramedian forehead flap often chosen?",
      ["It provides robust vascularized skin with favorable color/texture and can be staged with structural/lining reconstruction", "It replaces missing mucosal lining automatically", "It requires no knowledge of supratrochlear vascularity", "It is a one-size operation for every tiny defect"], 0,
      "Major nasal reconstruction follows three layers: lining, structural support and external cover. The forehead flap is a workhorse for cover but does not eliminate the need to reconstruct the other layers.",
      "Rebuild nose from inside out: lining, framework, then skin cover.",
      "What is the vascular pedicle of the paramedian forehead flap?"),

    Q("v137_fpt_09", FPT, "Hair Restoration Fundamentals",
      "A man with stable androgenetic alopecia wants transplantation. Which donor principle supports follicular-unit transplantation?",
      ["Occipital donor follicles retain relative androgen resistance after relocation", "Transplanted follicles always acquire recipient-site miniaturization", "Hair direction does not matter", "Unlimited donor supply exists"], 0,
      "Hair restoration redistributes a finite donor supply; candidate selection, hairline design, donor density and follicle orientation determine natural results.",
      "A low juvenile hairline can consume donor reserve and age poorly.",
      "How does diffuse unpatterned alopecia change candidacy?"),

    Q("v137_fpt_10", FPT, "Mohs Defect Reconstruction",
      "A nasal defect is referred immediately after Mohs surgery. What is the best first reconstructive step?",
      ["Analyze defect depth, subunit, lining/support loss and surrounding laxity before selecting secondary healing, graft, flap or staged reconstruction", "Choose a forehead flap before examining the defect", "Close every defect primarily under tension", "Reconstruct before confirming clear margins"], 0,
      "Mohs reconstruction follows defect analysis, not a favorite flap. The same surface diameter can represent very different reconstructive problems depending on depth and subunit.",
      "Defect depth often matters more than diameter.",
      "How does exposed cartilage without perichondrium affect graft take?"),

    Q("v137_fpt_11", FPT, "Open Rhinoplasty Fundamentals",
      "What is the principal advantage of an open rhinoplasty approach for complex tip deformity?",
      ["Broad direct exposure for precise diagnosis, graft placement and suture modification of the tip framework", "It eliminates all postoperative edema", "It never leaves a scar", "It avoids disturbing tip support"], 0,
      "Open rhinoplasty provides exposure and precision at the cost of additional dissection/edema and a transcolumellar incision; approach choice should match complexity.",
      "Exposure is a means to execute a structural plan, not a substitute for one.",
      "Which maneuvers preserve or restore tip support after cephalic trim?"),

    Q("v137_fpt_12", FPT, "Otoplasty",
      "A child has prominent ears from an underdeveloped antihelical fold and deep conchal bowl. Which operative principle is appropriate?",
      ["Correct the specific deformities with antihelical creation and/or conchal setback rather than applying one maneuver to all ears", "Excise the entire auricle", "Use only skin excision", "Wait until adulthood in every case"], 0,
      "Prominent-ear surgery is deformity-specific; common contributors include absent antihelix, conchal excess and increased conchomastoid angle.",
      "Avoid overcorrection and a telephone-ear deformity by balancing upper, middle and lower thirds.",
      "What complication can occur from overly tight permanent sutures?"),

    Q("v137_fpt_13", FPT, "Periocular Reconstruction",
      "A full-thickness lower-eyelid defect involves 60% of the lid. Which reconstructive principle is critical?",
      ["Reconstruct both anterior and posterior lamellae and provide horizontal support to protect the globe", "Use a skin graft alone for both lamellae", "Ignore canthal support", "Leave the globe exposed"], 0,
      "Large full-thickness eyelid defects require restoration of both lamellae with vascularized support and attention to canthal/lid tension.",
      "Eyelid reconstruction is functional corneal protection first and cosmetic reconstruction second.",
      "Why should one lamella generally be vascularized when the other is a free graft?"),

    Q("v137_fpt_14", FPT, "Rhinoplasty Graft Selection",
      "A revision rhinoplasty patient has internal nasal-valve narrowing and a weak middle vault. Which graft is classically useful?",
      ["Spreader graft", "Auricular composite graft to the earlobe", "Bone graft to the mandible", "No structural graft can affect the valve"], 0,
      "Spreader grafts restore the dorsal septum-upper lateral cartilage relationship and can widen/support the internal nasal valve.",
      "Choose grafts by the mechanical deficit: spreader for middle vault, batten for lateral wall, rim graft for alar margin, columellar/caudal support for tip-base mechanics.",
      "When might a spreader flap be used instead of a graft?"),

    Q("v137_fpt_15", FPT, "Scar Management",
      "A hypertrophic facial scar remains raised and erythematous several months after injury but stays within the original wound borders. What is an appropriate first-line strategy?",
      ["Sun protection, silicone/pressure strategies and intralesional steroid when indicated before considering revision after maturation", "Immediate wide excision in every case", "Radiation for all facial scars", "No treatment can improve symptoms"], 0,
      "Hypertrophic scars differ from keloids by remaining within the wound; conservative maturation strategies and targeted injections are often used before surgical revision.",
      "Scar revision timing should respect maturation unless function or severe deformity creates a reason to intervene earlier.",
      "How does a true keloid change recurrence counseling and adjuvant treatment considerations?"),
]
