"""
v14.5 - Second-case depth closure for Head & Neck Oncology and
Laryngology / Voice / Swallowing singleton topics.
"""


def _case(qid, domain, topic, stem, choices, answer, explanation, pearl, curveball, focus="boards"):
    return {
        "id": qid, "domain": domain, "topic": topic, "stem": stem,
        "choices": choices, "answer": answer, "explanation": explanation,
        "why_wrong": ["Correct." if i == answer else "This option misses the key clinical discriminator described in the explanation." for i in range(len(choices))],
        "board_pearl": pearl, "curveball": curveball,
        "tier": "Curated second-pass depth", "mode": "Vignette", "focus": focus,
    }


H = "Head & Neck Oncology"
L = "Laryngology / Voice / Swallowing"

VIGNETTES_V145 = [
    # ---------------- Head & Neck Oncology ----------------
    _case("v145_hn_01", H, "Basal Cell Carcinoma of the Head & Neck",
          "A 1.8-cm infiltrative basal cell carcinoma sits on the nasal ala with poorly defined clinical margins. What most appropriately drives treatment planning?",
          ["Observation because BCC never causes local morbidity", "Margin-controlled excision such as Mohs in an anatomically critical high-risk site, followed by reconstruction based on the final defect", "Elective neck dissection", "Chemoradiation as standard first-line therapy"], 1,
          "Most BCC is treated surgically, but high-risk histology, recurrent disease, and cosmetically/ functionally critical facial sites favor margin-controlled excision. Regional nodal surgery is not routine because metastasis is rare.",
          "BCC is usually a local-control problem; the challenge on the face is clearing tumor while preserving reconstructive options.",
          "The defect crosses the alar rim and internal nasal lining. What reconstructive layers must be replaced?", "OR_prep"),

    _case("v145_hn_02", H, "Base of Tongue SCC",
          "A patient with HPV-associated base-of-tongue SCC has a small primary but multiple ipsilateral metastatic cervical nodes. Which principle is most important in treatment selection?",
          ["Primary size alone determines therapy", "Integrate HPV status, T/N stage, swallowing function, resectability, and expected morbidity of transoral surgery versus definitive radiation-based therapy", "Neck disease can be ignored in HPV-positive cancer", "Open mandibulotomy is mandatory"], 1,
          "Oropharyngeal SCC treatment is multidisciplinary. A small accessible primary may be transorally resectable, but nodal burden, adjuvant-treatment probability, functional outcomes, and patient preference determine whether surgery or definitive chemoradiation is the better overall strategy.",
          "Choose the treatment package, not just the easiest way to remove the primary.",
          "Final pathology after TORS shows extranodal extension. How does that alter adjuvant therapy?", "boards"),

    _case("v145_hn_03", H, "Carotid Body Paraganglioma",
          "Imaging shows a hypervascular carotid bifurcation mass splaying the internal and external carotid arteries. The patient is asymptomatic. What is the best next framework?",
          ["Blind office biopsy", "Define Shamblin/anatomic relationships, cranial-nerve risk, growth, age/comorbidity, and hereditary context before choosing surveillance, radiation, or surgery", "Immediate radical neck dissection", "Treat with antibiotics"], 1,
          "Carotid body tumors are paragangliomas. Biopsy is generally avoided because imaging is characteristic and vascularity creates risk. Management ranges from observation to radiation or surgery depending on growth, symptoms, age, genetics, and vessel/nerve involvement.",
          "A hypervascular bifurcation mass is an anatomy-and-morbidity decision, not a biopsy-first neck mass.",
          "What preoperative issue becomes more important in a large Shamblin III tumor encasing the ICA?", "OR_prep"),

    _case("v145_hn_04", H, "Complications of Neck Surgery",
          "After neck dissection, a patient has shoulder droop and difficulty abducting the arm above shoulder level. Which structure is most likely injured?",
          ["Spinal accessory nerve", "Hypoglossal nerve", "Lingual nerve", "Recurrent laryngeal nerve"], 0,
          "CN XI injury denervates the trapezius, producing shoulder droop, pain, scapular dyskinesis, and impaired overhead abduction. Even when anatomically preserved, traction can cause neuropraxia.",
          "A functionally preserved neck dissection requires deliberate protection of CN XI, not just oncologic clearance.",
          "The patient instead has milky high-output drainage from the left lower neck. What complication is likely and what is the first management framework?", "postoperative_call"),

    _case("v145_hn_05", H, "Floor of Mouth SCC",
          "A floor-of-mouth SCC is close to the mandible and Wharton duct with clinically negative neck nodes. Which factor most changes the primary surgical plan?",
          ["Hair color", "Depth/extent of invasion and whether the tumor invades mandible, tongue musculature, or adjacent structures", "Patient handedness", "Presence of tonsilloliths"], 1,
          "Oral cavity cancer surgery is dictated by three-dimensional extent. Mandibular invasion, deep tongue involvement, and nodal risk determine resection, neck treatment, and reconstruction—not surface diameter alone.",
          "For oral cavity SCC, depth and adjacent-structure invasion often matter more than how small the mucosal footprint looks.",
          "How does depth of invasion affect elective neck management in an otherwise N0 oral cavity cancer?", "OR_prep"),

    _case("v145_hn_06", H, "Head & Neck Cancer Surveillance / Second Primaries",
          "A patient is disease-free 3 years after treatment of tobacco-associated laryngeal SCC but continues smoking. What surveillance principle is most important?",
          ["Surveillance ends once two years pass", "Continue symptom-directed examination and appropriate imaging while addressing tobacco/alcohol risk and the ongoing risk of second primary malignancies", "Routine PET/CT every month", "Only monitor the original laryngeal subsite"], 1,
          "Survivorship includes recurrence detection, second-primary risk, treatment toxicities, nutrition, speech/swallowing, dental/thyroid issues after radiation, and tobacco/alcohol cessation. Surveillance intensity changes with time but does not become zero-risk.",
          "The survivor can fail from recurrence, a second primary, or treatment toxicity—follow all three lanes.",
          "What new symptom should trigger expedited chest or esophageal evaluation in this patient?", "boards"),

    _case("v145_hn_07", H, "Head & Neck Radiation Toxicity / Survivorship",
          "A patient treated with neck radiation years ago develops progressive dysphagia, xerostomia, dental decay, and hypothyroidism. What is the best management approach?",
          ["Treat only the thyroid abnormality", "Use multidisciplinary survivorship care addressing swallowing, dental prevention, salivary dysfunction, thyroid screening, nutrition, fibrosis, and aspiration risk", "Assume late toxicity cannot be treated", "Avoid speech-language pathology"], 1,
          "Radiation toxicity is multisystem and often evolves over years. Structured survivorship should screen for endocrine, dental, swallowing, vascular, fibrosis, and nutritional consequences rather than waiting for crises.",
          "Finishing radiation does not finish the treatment burden.",
          "The patient now has recurrent aspiration pneumonia. What tests and functional decisions become urgent?", "boards"),

    _case("v145_hn_08", H, "Hypopharyngeal Cancer",
          "A patient has piriform sinus SCC with a fixed hemilarynx and bulky nodal disease. What principle best frames treatment planning?",
          ["Treat as a simple mucosal excision", "Assess laryngeal function, extent, nodal burden, nutrition, and candidacy for organ-preservation chemoradiation versus ablative surgery", "Neck nodes do not matter", "Voice preservation always outweighs aspiration risk"], 1,
          "Hypopharyngeal cancers often present advanced and carry major swallowing/nutritional morbidity. 'Organ preservation' is only meaningful if the retained larynx is functional and oncologically appropriate.",
          "An anatomically preserved larynx that cannot protect the airway is not true functional preservation.",
          "What findings would make total laryngopharyngectomy more compelling than organ-preservation treatment?", "boards"),

    _case("v145_hn_09", H, "Merkel Cell Carcinoma",
          "An older immunosuppressed patient has a rapidly growing violaceous scalp nodule proven to be Merkel cell carcinoma. Which principle is most appropriate?",
          ["Treat like a low-risk benign cyst", "Recognize the high nodal/distant metastatic risk and use wide local control plus nodal staging and multidisciplinary radiation/systemic planning", "Never evaluate regional nodes", "Observation is standard after biopsy"], 1,
          "Merkel cell carcinoma is an aggressive neuroendocrine skin cancer with meaningful nodal and distant risk. Primary control, sentinel-node/ regional evaluation, and adjuvant radiation or immunotherapy decisions depend on stage and patient factors.",
          "A small skin lesion can represent biologically aggressive disease; stage the basin, not just the scar.",
          "Sentinel node is positive. How does that change regional management?", "boards"),

    _case("v145_hn_10", H, "Neck Lymphoma",
          "A patient has progressive painless cervical adenopathy, B symptoms, and no obvious mucosal primary. FNA is nondiagnostic. What is the best next tissue strategy?",
          ["Open radical neck dissection", "Obtain tissue adequate for architecture and flow cytometry, often core or excisional biopsy depending on context", "Empiric radiation without diagnosis", "Repeated antibiotics indefinitely"], 1,
          "Lymphoma classification requires sufficient tissue architecture and immunophenotyping. A diagnostic biopsy is different from a therapeutic neck dissection; preserve treatment planes and obtain the specimen hematopathology needs.",
          "For lymphoma, the question is not 'how much node can I remove?' but 'what tissue does pathology need to classify the disease?'.",
          "The node is deep behind the carotid sheath. How would you balance biopsy adequacy with operative morbidity?", "boards"),

    _case("v145_hn_11", H, "Nonfunctional Larynx and Intractable Aspiration",
          "A cancer survivor has a structurally preserved larynx after radiation but requires a feeding tube and has repeated aspiration pneumonias despite maximal therapy. What is the next conceptual step?",
          ["Continue calling this successful organ preservation without reassessment", "Evaluate whether aspiration-prevention surgery or functional laryngectomy is appropriate based on pulmonary risk, goals, and rehabilitation potential", "Permanent antibiotics alone", "Ignore swallowing because the tumor is controlled"], 1,
          "Oncologic organ preservation can leave a nonfunctional larynx. Recurrent life-threatening aspiration may justify separation or ablative procedures after careful counseling about voice, swallowing, pulmonary benefit, and alternatives.",
          "Cancer cure and laryngeal function are separate outcomes.",
          "How would preoperative TEP counseling differ for a functional laryngectomy done for aspiration rather than active cancer?", "OR_prep"),

    _case("v145_hn_12", H, "Open Partial / Conservation Laryngectomy",
          "A patient with selected early glottic cancer asks about open partial laryngectomy. Which feature is most important before offering conservation surgery?",
          ["Whether the patient can tolerate temporary dysphagia and has disease anatomically suitable for oncologic resection while preserving a functional cricoarytenoid unit", "Age under 30", "Desire to avoid all rehabilitation", "Presence of allergic rhinitis"], 0,
          "Open conservation laryngeal procedures require carefully selected tumor extent and adequate pulmonary/swallowing reserve because postoperative function depends on preserving at least one functional cricoarytenoid unit and rehabilitation.",
          "Conservation surgery is an oncologic resection plus a physiologic reconstruction—not simply a smaller laryngectomy.",
          "What tumor extension would generally defeat the premise of a supracricoid partial laryngectomy?", "OR_prep"),

    _case("v145_hn_13", H, "Palliative / Goals-of-Care Decision-Making in Head & Neck Cancer",
          "A patient with incurable recurrent HNSCC has severe pain, progressive dysphagia, and poor performance status. What is the best management principle?",
          ["Continue tumor-directed therapy regardless of burden", "Clarify goals and prognosis, aggressively treat symptoms, and align systemic/local interventions with what the patient values", "Avoid discussing prognosis", "Feeding tube placement is always mandatory"], 1,
          "Palliative care is concurrent symptom-focused care, not abandonment. Decisions about systemic therapy, radiation, airway, feeding access, bleeding risk, and hospice should follow prognosis, performance status, expected benefit, and patient goals.",
          "A procedure can be technically possible and still be the wrong treatment if it does not serve the patient's goals.",
          "The patient develops recurrent sentinel oral bleeding. How should anticipatory planning change?", "boards"),

    _case("v145_hn_14", H, "Palliative Decision-Making in Head and Neck Cancer",
          "A terminal head-and-neck cancer patient has worsening upper-airway obstruction but strongly prioritizes avoiding ICU-level care and procedures. What should drive the airway plan?",
          ["The most invasive airway procedure available", "A goals-concordant plan that explains likely trajectories and balances dyspnea relief, procedural burden, and the patient's stated preferences", "Family preference alone", "Automatic tracheostomy"], 1,
          "Airway decisions at end of life must incorporate prognosis, reversibility, expected symptom benefit, communication ability, hospitalization burden, and patient preferences. Tracheostomy is not automatically appropriate because obstruction exists.",
          "In palliation, technical airway success is not the same as goal-concordant care.",
          "What medications and bedside planning can reduce distress if the patient declines an invasive airway?", "boards"),

    _case("v145_hn_15", H, "Radiation Therapy Principles for Head & Neck Surgeons",
          "A surgeon is counseling a patient who will likely need postoperative radiation. Which pathology finding most strongly changes the likelihood that concurrent systemic therapy will be recommended?",
          ["Positive margin or extranodal extension", "Mild dysplasia at a remote site", "A normal chest x-ray", "Seasonal allergies"], 0,
          "Positive surgical margins and extranodal extension are classic high-risk postoperative features that can drive concurrent chemoradiation, whereas other adverse features may support radiation alone depending on the case.",
          "The operation determines not only what is removed but also the adjuvant-treatment burden the patient may need afterward.",
          "How should anticipated radiation influence dental evaluation and reconstruction planning before treatment?", "boards"),

    _case("v145_hn_16", H, "Recurrent / Metastatic HNSCC",
          "A patient has unresectable recurrent HNSCC after prior radiation and good performance status. What should guide systemic therapy selection?",
          ["Use the same drug for every patient", "PD-L1 expression, prior therapy, symptom burden, disease tempo, comorbidities, and need for rapid response", "Age alone", "Tumor subsite alone"], 1,
          "Modern recurrent/metastatic HNSCC therapy uses immune checkpoint inhibitors alone or with chemotherapy depending on biomarkers and clinical urgency. Local palliation and clinical trials remain important.",
          "Systemic therapy choice is a biology-plus-tempo decision: indolent disease and a crashing airway are not treated the same way.",
          "A single painful bone metastasis progresses while all other disease is controlled. What local treatment may be useful?", "boards"),

    _case("v145_hn_17", H, "Sinonasal Malignancies",
          "A patient has a superior nasal cavity malignancy abutting the skull base. Which planning question is most important before choosing an endoscopic resection?",
          ["Whether the tumor can be removed with oncologically appropriate margins while controlling skull-base, orbital, vascular, and intracranial interfaces", "Whether the patient prefers no pathology review", "Whether the middle turbinate is large", "Whether allergy testing is positive"], 0,
          "Endoscopic oncologic resection can be appropriate for selected sinonasal cancers, but route selection depends on histology, margin feasibility, orbit/brain involvement, vascular anatomy, reconstruction needs, and multidisciplinary adjuvant therapy.",
          "'Endoscopic' describes the corridor, not the oncologic adequacy of the operation.",
          "A dural margin is required. What reconstructive principles reduce postoperative CSF leak?", "OR_prep"),

    _case("v145_hn_18", H, "Systemic Therapy Foundations in Head & Neck Cancer",
          "Why might cisplatin be omitted or modified in a patient who otherwise needs concurrent chemoradiation?",
          ["Because systemic therapy never improves control", "Renal dysfunction, hearing loss, neuropathy, frailty, or other comorbidity can make standard high-dose cisplatin unsafe", "Because HPV-positive disease never needs systemic therapy", "Because radiation and chemotherapy cannot be combined"], 1,
          "Cisplatin is effective but nephrotoxic, ototoxic, neurotoxic, and emetogenic. Treatment intensity should reflect oncologic benefit and patient fitness, with alternatives considered when contraindications exist.",
          "A regimen is only standard if the patient can safely receive it.",
          "How does baseline audiometry help an otolaryngologist contribute to systemic-therapy planning?", "boards"),

    _case("v145_hn_19", H, "TEP and Alaryngeal Speech",
          "A total-laryngectomy patient wants the most fluent pulmonary-powered speech option. Which rehabilitation method best fits?",
          ["Tracheoesophageal puncture with voice prosthesis", "Whispering only", "Cochlear implant", "Palatal obturator"], 0,
          "TEP speech redirects pulmonary air through a prosthesis into the pharyngoesophageal segment to generate sound. Success depends on dexterity, pulmonary reserve, tract care, and an appropriate vibratory segment.",
          "TEP restores a pulmonary power source for voice; it does not restore the larynx.",
          "The prosthesis begins leaking through its center. What is the likely mechanism and first response?", "OR_prep"),

    _case("v145_hn_20", H, "Tonsil SCC",
          "A patient with HPV-positive tonsil SCC has a small lateralized primary and limited ipsilateral nodal disease. Which concept is most relevant to selecting TORS plus neck dissection versus definitive radiation?",
          ["Expected total treatment morbidity, including the chance that surgery will still require adjuvant radiation or chemoradiation", "Tumor color", "Whether the patient has had tonsillitis", "The surgeon's preference alone"], 0,
          "For early oropharyngeal cancer, both transoral surgery and radiation-based strategies can control disease. The best choice considers functional outcomes and whether adverse pathology is likely to convert surgery into trimodality therapy.",
          "Avoid a 'minimally invasive' operation that simply adds itself on top of full-dose adjuvant therapy without benefit.",
          "What pathologic findings after TORS most strongly escalate adjuvant therapy?", "boards"),

    _case("v145_hn_21", H, "Tracheal Malignancy",
          "A patient has a short-segment primary tracheal tumor without distant disease. What feature most determines whether segmental tracheal resection is feasible?",
          ["Ability to achieve oncologic margins while performing a tension-safe airway anastomosis", "Hair color", "Presence of allergic rhinitis", "Whether the tumor is visible on chest x-ray"], 0,
          "Tracheal resection is constrained by both oncologic extent and anastomotic tension. Length, location, mediastinal anatomy, prior radiation, and need for release maneuvers determine resectability.",
          "The oncologic margin and the airway anastomosis must both be survivable.",
          "What postoperative maneuver helps protect a high-risk tracheal anastomosis from neck extension?", "OR_prep"),

    _case("v145_hn_22", H, "Transoral Laser Microsurgery for Laryngeal Cancer",
          "A patient with selected early glottic SCC is considering transoral laser microsurgery. What is the central oncologic principle?",
          ["Use the laser to vaporize tumor without preserving orientation", "Resect with a planned margin strategy and pathologic orientation while balancing voice-preserving tissue conservation", "Laser surgery eliminates the need for staging", "Every glottic cancer requires open laryngectomy"], 1,
          "TLM can provide excellent control for selected laryngeal cancers, but requires deliberate exposure, margin assessment, and understanding of depth/spread. Tissue preservation is valuable only when oncologic resection remains adequate.",
          "The laser is a cutting tool; it does not change cancer biology or margin principles.",
          "Exposure is poor and the anterior commissure cannot be visualized adequately. What should you do rather than force the transoral approach?", "OR_prep"),

    _case("v145_hn_23", H, "Tumor Immunology / Immunotherapy in HNSCC",
          "A patient on immune-checkpoint therapy for recurrent HNSCC develops new severe diarrhea, hepatitis, and fatigue while imaging shows tumor response. What is the key management concept?",
          ["Ignore symptoms because the drug is working", "Recognize possible immune-related adverse events and coordinate prompt toxicity grading and immunosuppressive management", "Assume all toxicity is infection", "Continue therapy unchanged in every case"], 1,
          "Checkpoint inhibitors activate antitumor immunity but can also trigger inflammatory toxicity in almost any organ. Recognition and severity-based management may require holding therapy and corticosteroids or other immunosuppression.",
          "Immunotherapy toxicity is the immune system doing the right kind of work in the wrong tissue.",
          "Which airway symptoms during checkpoint therapy would require urgent ENT evaluation?", "boards"),

    # ---------------- Laryngology / Voice / Swallowing ----------------
    _case("v145_lar_01", L, "Acute / Chronic Laryngopharyngitis",
          "A teacher has 10 days of hoarseness after a viral URI, no stridor, no neck mass, and no smoking history. What is the best initial management principle?",
          ["Immediate prolonged antibiotics", "Supportive care and voice hygiene, with laryngeal visualization if symptoms persist or red flags emerge", "Empiric antifungal therapy", "Immediate thyroplasty"], 1,
          "Most uncomplicated acute laryngitis is viral/inflammatory and self-limited. Persistent dysphonia or red flags warrant visualization rather than serial empiric medications.",
          "Hoarseness is a symptom; persistence changes the obligation to look.",
          "Which red flags would make you visualize the larynx sooner?", "boards"),

    _case("v145_lar_02", L, "Arytenoid Adduction / Reinnervation",
          "A patient with chronic unilateral vocal-fold paralysis has a large posterior glottic gap and vertical level mismatch despite adequate bulk. Which procedure specifically addresses this geometry?",
          ["Arytenoid adduction", "Tonsillectomy", "Septoplasty", "Myringotomy"], 0,
          "Arytenoid adduction rotates the arytenoid to improve posterior closure and level, often combined with medialization thyroplasty. Reinnervation may be considered in selected patients for long-term tone/bulk.",
          "Medialization adds bulk; arytenoid adduction changes posterior position and level.",
          "In a young patient with recent stable RLN injury, when might reinnervation be favored?", "OR_prep"),

    _case("v145_lar_03", L, "Aspiration-Prevention Surgery",
          "A neurologically impaired patient has recurrent life-threatening aspiration despite maximal rehabilitation and no useful laryngeal voice. What is the goal of aspiration-prevention surgery?",
          ["Increase pitch", "Separate or close the airway from the alimentary tract enough to prevent pulmonary contamination, accepting voice consequences", "Treat reflux only", "Increase nasal airflow"], 1,
          "Procedures such as laryngotracheal separation, glottic closure, or total laryngectomy sacrifice or alter voice to protect the lungs when conservative strategies fail.",
          "These are pulmonary-protection operations, not voice operations.",
          "How does preserved desire for oral intake influence counseling even if aspiration is eliminated?", "OR_prep"),

    _case("v145_lar_04", L, "Chronic Cough / Laryngeal Hypersensitivity",
          "A patient has chronic cough after negative pulmonary workup, no concerning imaging, and cough triggered by talking, odors, and temperature change with laryngeal paresthesia. What treatment concept is most appropriate?",
          ["Repeated antibiotics", "Consider laryngeal hypersensitivity and use behavioral cough suppression therapy with selected neuromodulators when appropriate", "Total laryngectomy", "No treatment exists"], 1,
          "Some chronic cough reflects sensory hyperresponsiveness after other common causes are addressed. Speech-language therapy and selected neuromodulation can reduce maladaptive cough reflexes.",
          "After dangerous causes are excluded, the cough reflex itself can become the disease target.",
          "What findings would make you return to a pulmonary or oncologic differential instead?", "boards"),

    _case("v145_lar_05", L, "Esophageal Disease for the Otolaryngologist",
          "A patient has progressive solid-food dysphagia and weight loss with a normal oropharyngeal examination. What is the next priority?",
          ["Assume globus and reassure", "Evaluate for structural esophageal disease with appropriate endoscopy/esophagram and GI collaboration", "Voice therapy only", "Intranasal steroids"], 1,
          "Progressive esophageal dysphagia with weight loss is a structural/malignancy red flag. Otolaryngologists should localize oral/pharyngeal versus esophageal symptoms and route the workup appropriately.",
          "Dysphagia localization is a triage skill: where the patient feels food stick is not always where the lesion is.",
          "The barium study shows a Zenker diverticulum. What symptom pattern and operative options become relevant?", "boards"),

    _case("v145_lar_06", L, "Laryngeal Anatomy",
          "During endoscopic laryngeal surgery, which structure forms the inferior boundary of the ventricle and contains the vocal ligament?",
          ["True vocal fold", "False vocal fold", "Aryepiglottic fold", "Epiglottic petiole only"], 0,
          "The true vocal fold contains the vocal ligament and thyroarytenoid muscle, lies inferior to the ventricle, and is central to phonatory vibration and glottic closure.",
          "Know laryngeal anatomy by function: airway protection, vibration, framework, and spaces of tumor spread.",
          "How does the conus elasticus limit or channel subglottic tumor spread?", "OR_prep"),

    _case("v145_lar_07", L, "Modified Barium Swallow",
          "A patient coughs with thin liquids after stroke. What is the main advantage of a modified barium swallow over a routine esophagram?",
          ["It dynamically evaluates oral and pharyngeal swallowing physiology and tests compensatory strategies", "It directly biopsies the esophagus", "It measures vocal pitch", "It replaces all endoscopic swallowing evaluation"], 0,
          "MBS/VFSS visualizes bolus flow through oral/pharyngeal phases, timing, penetration/aspiration, residue, and response to maneuvers or consistency changes.",
          "A swallow study should answer why aspiration occurs and what changes it—not merely whether aspiration occurred.",
          "When might FEES add information that MBS does not provide as well?", "boards"),

    _case("v145_lar_08", L, "Muscle Tension Dysphonia",
          "A professional voice user has dysphonia with excessive supraglottic squeeze, normal fold mobility, and no structural lesion. What is first-line treatment?",
          ["Voice therapy targeting inefficient hyperfunction", "Permanent tracheostomy", "Empiric oncologic resection", "Cochlear implantation"], 0,
          "Muscle tension dysphonia is a functional hyperkinetic voice disorder. Treatment focuses on reducing maladaptive tension and optimizing breath/phonatory coordination, while excluding underlying lesions that can drive compensatory tension.",
          "Before calling it primary muscle tension, make sure the patient is not squeezing to compensate for a hidden glottic problem.",
          "What stroboscopic finding would suggest underlying paresis rather than primary MTD?", "boards"),

    _case("v145_lar_09", L, "Presbyphonia",
          "An older patient has weak breathy voice, vocal-fold bowing, and a spindle-shaped glottic gap without a focal lesion. What management sequence is reasonable?",
          ["Voice therapy first, with injection augmentation or framework surgery for persistent function-limiting glottic insufficiency", "Antibiotics indefinitely", "Total laryngectomy", "No treatment because aging is untreatable"], 0,
          "Presbyphonia reflects age-related tissue and muscle changes. Behavioral optimization is often first-line; augmentation can improve closure when glottic insufficiency remains functionally limiting.",
          "Age explains the mechanism; it does not erase the patient's communication goal.",
          "How would coexisting unilateral paresis change the treatment plan?", "boards"),

    _case("v145_lar_10", L, "Professional Voice",
          "A singer has subtle loss of upper register after thyroid surgery despite normal speaking voice and normal true-vocal-fold mobility. Which deficit should be considered?",
          ["External branch of superior laryngeal nerve dysfunction affecting cricothyroid tension", "Bilateral hypoglossal paralysis", "Conductive hearing loss", "Inferior turbinate hypertrophy"], 0,
          "Professional voice demands make small changes important. EBSLN injury can impair pitch elevation and projection without obvious vocal-fold immobility on routine examination.",
          "A normal speaking voice does not equal normal professional voice performance.",
          "What laryngeal/stroboscopic or EMG findings can support this diagnosis?", "OR_prep"),

    _case("v145_lar_11", L, "Tracheobronchial Endoscopy Principles",
          "During rigid bronchoscopy for an airway foreign body, what is the most important procedural principle?",
          ["Maintain continuous shared-airway communication with anesthesia and preserve control of oxygenation while using the scope as an airway conduit", "Ignore ventilation until the object is removed", "Use blind forceps without visualization", "Always push the foreign body distally"], 0,
          "Rigid bronchoscopy is both an airway and an operative instrument. Safe technique depends on team communication, visualization, ventilation strategy, and avoiding distal displacement or mucosal injury.",
          "In airway endoscopy, the surgeon and anesthesiologist are operating on the same lumen.",
          "The foreign body completely obstructs a mainstem bronchus and fragments during removal. What is the rescue strategy?", "OR_prep"),

    _case("v145_lar_12", L, "Transnasal Esophagoscopy",
          "Which patient is most appropriate for office transnasal esophagoscopy?",
          ["A cooperative patient needing unsedated upper-esophageal evaluation without an anticipated need for major therapeutic intervention", "A patient with unstable airway obstruction", "A child requiring removal of a sharp esophageal foreign body", "A patient who cannot tolerate any nasal instrumentation"], 0,
          "TNE can evaluate selected esophageal complaints in the office without sedation, but does not replace controlled OR endoscopy for unstable airways, sharp foreign bodies, or complex therapeutic needs.",
          "Choose the scope and setting based on what you may need to do, not just what you want to see.",
          "What complications or anatomy should make you stop an office TNE and escalate the setting?", "boards"),

    _case("v145_lar_13", L, "Vocal Fold Nodules",
          "A teacher has bilateral symmetric mid-membranous vocal-fold lesions with hourglass closure and phonotraumatic behavior. What is first-line management?",
          ["Voice therapy and vocal-behavior modification", "Immediate bilateral wide excision", "Chemoradiation", "Tracheostomy"], 0,
          "Classic vocal nodules are usually bilateral phonotraumatic lesions and respond to behavioral voice therapy. Surgery is reserved for selected persistent lesions after diagnosis and technique are addressed.",
          "Treat the collision behavior, not just the bump it created.",
          "The lesions are unilateral, stiff, and irregular on stroboscopy. How does the differential change?", "boards"),

    _case("v145_lar_14", L, "Vocal Fold Sulcus / Scar",
          "A patient has chronic breathy dysphonia and stroboscopy shows a focal sulcus with reduced mucosal wave. Why is treatment difficult?",
          ["Because the lesion alters the layered vibratory cover, so improving closure does not necessarily restore normal mucosal wave", "Because scar always resolves with antibiotics", "Because the RLN is always transected", "Because hearing loss causes the dysphonia"], 0,
          "Vocal-fold scar and sulcus stiffen the lamina propria. Injection or framework surgery may improve glottic closure, but restoration of pliable mucosal vibration is much harder.",
          "A closed glottis and a normal mucosal wave are different therapeutic targets.",
          "How would you counsel a professional singer about expected outcomes before scar-directed surgery?", "OR_prep"),

    _case("v145_lar_15", L, "Vocal Process Granuloma",
          "A patient develops posterior glottic pain and a vocal-process granuloma after prolonged intubation. What is the best initial management principle?",
          ["Address mechanical/phonatory trauma and reflux contributors, use voice therapy when appropriate, and reserve surgery for selected persistent or concerning lesions", "Wide arytenoidectomy in every patient", "No follow-up", "Chemotherapy"], 0,
          "Vocal-process granulomas frequently recur if underlying contact trauma, hyperfunction, cough, reflux, or intubation injury is not addressed. Excision alone can recreate the injury.",
          "If you remove the granuloma but preserve the cause, you preserve the recurrence.",
          "What feature would make biopsy more urgent to exclude malignancy?", "boards"),

    _case("v145_lar_16", L, "Vocal Tremor",
          "A patient has rhythmic voice breaks affecting multiple laryngeal subsites and sometimes the palate/pharynx. What feature favors essential voice tremor over adductor spasmodic dysphonia?",
          ["Regular rhythmic oscillation that can persist across tasks rather than task-specific strained breaks", "A fixed vocal-fold mass", "Complete bilateral immobility", "Only whispering difficulty"], 0,
          "Essential voice tremor is rhythmic and may involve vertical laryngeal or pharyngeal structures; spasmodic dysphonia is task-specific focal dystonia with characteristic breaks. Treatment can include botulinum toxin, systemic tremor therapy, and voice strategies.",
          "Tremor is rhythmic; dystonia is task-specific and patterned.",
          "How does tremor direction and muscle involvement influence botulinum-toxin targeting?", "boards"),
]
