"""v14.3 — balanced second-case depth pass across all nine domains.

Adds a second management-discriminating vignette to 45 canonical singleton
topics. Cases emphasize board reasoning, overnight-call priorities, and
operative anatomy/decision making. All targets are validated against the live
canonical curriculum before merge.
"""

def Q(qid, domain, topic, stem, choices, answer, explanation, pearl, curveball, focus="boards"):
    return {
        "id": qid, "domain": domain, "topic": topic, "stem": stem,
        "choices": choices, "answer": answer, "explanation": explanation,
        "why_wrong": ["Use the mechanism, anatomy, and management priority in the explanation to distinguish this choice." for _ in choices],
        "board_pearl": pearl, "curveball": curveball, "focus": focus,
        "tier": "Curated chief/call/OR", "mode": "Vignette",
    }

VIGNETTES_V143 = [
    Q('v143_oto_01', 'Otology / Neurotology', 'Acute Otitis Externa',
      'A swimmer has severe otalgia, canal edema and debris, an intact tympanic membrane, and no diabetes or cranial neuropathy. The canal is nearly swollen shut. What is the best initial treatment?',
      ['Topical antimicrobial drops plus a wick/aural toilet when needed for delivery', 'Routine oral fluoroquinolone monotherapy', 'CT temporal bone before treatment', 'Urgent mastoidectomy'], 0,
      'Uncomplicated diffuse acute otitis externa is treated topically. When edema prevents drop penetration, careful aural toilet and/or a wick improves delivery; systemic antibiotics are reserved for extension beyond the canal or selected high-risk patients.',
      'Treat the canal locally unless disease has escaped the canal or the host makes uncomplicated disease unlikely.',
      'How would diabetes, disproportionate nocturnal pain, granulation tissue, or a new cranial neuropathy change the diagnosis and workup?', 'overnight_call'),

    Q('v143_oto_02', 'Otology / Neurotology', 'Audiogram Interpretation',
      'An audiogram shows right air thresholds 45 dB, bone thresholds 10 dB, excellent word recognition, and a type B tympanogram with normal canal volume. What is the best interpretation?',
      ['Right conductive hearing loss with a middle-ear process', 'Right sensorineural hearing loss', 'Right auditory neuropathy', 'Normal hearing'], 0,
      'The preserved bone thresholds with a large air-bone gap define conductive hearing loss. A flat type B tympanogram with normal canal volume supports middle-ear effusion or another stiff middle-ear system rather than a perforation.',
      'Always classify hearing loss from air versus bone first; then use tympanometry and speech testing to localize the mechanism.',
      'If the type B tracing had a large ear-canal volume instead, what two common explanations should you consider?', 'boards'),

    Q('v143_oto_03', 'Otology / Neurotology', 'Cochlear Implant Surgery',
      'During cochlear implantation through the facial recess, the round-window niche is identified. Which principle best minimizes intracochlear trauma during electrode insertion?',
      ['Use atraumatic round-window or limited cochleostomy access with slow insertion along the scala tympani trajectory', 'Force the array if resistance is encountered', 'Open the vestibule widely', 'Remove the stapes first'], 0,
      'Modern cochlear implantation emphasizes soft-surgery technique: preserve anatomy, minimize drilling trauma and suction near the cochlea, use a scala-tympani trajectory, and stop/reassess when unexpected resistance occurs.',
      'Resistance during electrode insertion is information, not an invitation to push harder.',
      'If intraoperative testing suggests tip fold-over or extracochlear electrodes, what imaging or electrophysiologic checks can help before closure?', 'OR_prep'),

    Q('v143_oto_04', 'Otology / Neurotology', 'Superior Canal Dehiscence',
      'A patient has autophony, sound- and pressure-induced vertigo, a low-frequency air-bone gap despite normal middle-ear mechanics, and abnormally low cVEMP thresholds. What is the best next diagnostic step before considering repair?',
      ['High-resolution temporal-bone CT reformatted in the superior canal plane and correlation with symptoms/physiology', 'Empiric stapedectomy', 'MRI brain only', 'Treat as otitis media'], 0,
      'Superior canal dehiscence is a third-window syndrome. Diagnosis requires concordant symptoms, physiologic evidence of a third window, and high-resolution CT demonstrating the bony defect; CT alone can overcall thin bone.',
      'Do not operate on a CT finding—operate on a concordant third-window syndrome.',
      'Which disabling symptoms most often justify plugging/resurfacing rather than observation?', 'boards'),

    Q('v143_oto_05', 'Otology / Neurotology', 'Vestibular Migraine',
      'A patient has recurrent 2-hour episodes of vertigo with photophobia and motion sensitivity, a migraine history, normal hearing between attacks, and no progressive unilateral auditory symptoms. What is the best management framework?',
      ['Clinical diagnosis after excluding concerning mimics, with trigger/lifestyle management and migraine-directed preventive or abortive therapy when indicated', 'Urgent labyrinthectomy', 'Treat every episode as bacterial labyrinthitis', 'Stapedectomy'], 0,
      'Vestibular migraine is diagnosed clinically from recurrent vestibular episodes and migraine features after excluding alternative central or otologic causes. Management parallels migraine care and often includes vestibular rehabilitation for persistent motion sensitivity.',
      'The absence of a progressive unilateral cochlear pattern helps separate vestibular migraine from disorders such as Ménière disease.',
      'What new neurologic finding would make you abandon a routine vestibular-migraine pathway and pursue urgent central evaluation?', 'boards'),

    Q('v143_rhi_01', 'Rhinology / Allergy / Skull Base', 'Acute Bacterial Rhinosinusitis',
      'An adult has purulent drainage, obstruction and facial pressure for 11 days without improvement after a viral URI. There are no orbital or neurologic red flags. What is the best interpretation?',
      ['The persistent-without-improvement pattern supports acute bacterial rhinosinusitis and either watchful waiting with follow-up or appropriate antibiotics is reasonable', 'This is automatically chronic rhinosinusitis', 'Urgent FESS is required', 'CT is mandatory before diagnosis'], 0,
      'ABRS is a clinical diagnosis when acute rhinosinusitis persists at least about 10 days without improvement or worsens after initial improvement. Imaging is not routine in uncomplicated disease, and either watchful waiting with reliable follow-up or antibiotics may be appropriate.',
      'Duration and trajectory—not mucus color alone—separate routine viral illness from likely ABRS.',
      'What orbital or intracranial findings would convert this from routine outpatient management to an emergency?', 'overnight_call'),

    Q('v143_rhi_02', 'Rhinology / Allergy / Skull Base', 'AFRS',
      'A young immunocompetent patient has chronic pansinusitis, nasal polyps, very high IgE, eosinophilic mucin with fungal elements but no tissue invasion, and expansile heterogeneous sinus opacification. What is the best management?',
      ['Endoscopic removal of allergic mucin and restoration of drainage plus postoperative anti-inflammatory therapy', 'Treat as invasive fungal rhinosinusitis with emergent orbital exenteration', 'Antibiotics alone', 'No treatment because fungal elements are always colonization'], 0,
      'Allergic fungal rhinosinusitis is noninvasive and driven by type-2 inflammation. Surgery clears thick allergic mucin and opens involved sinuses; corticosteroid-centered postoperative inflammatory control and surveillance reduce recurrence.',
      'Fungus in AFRS is present without tissue invasion—the host, histology, and tempo distinguish it from invasive fungal disease.',
      'What histopathologic finding would instead establish invasive fungal rhinosinusitis and change urgency dramatically?', 'boards'),

    Q('v143_rhi_03', 'Rhinology / Allergy / Skull Base', 'Endoscopic Maxillary Antrostomy',
      'During endoscopic maxillary antrostomy, what technical principle best reduces the risk of creating a persistent mucus-recirculation problem?',
      ['Incorporate the natural maxillary ostium into the antrostomy rather than creating a separate accessory opening', 'Create a posterior accessory opening while leaving the natural ostium isolated', 'Remove the nasolacrimal duct routinely', 'Avoid identifying the uncinate process'], 0,
      'Mucus normally exits through the natural ostium. A surgical opening that does not communicate with it can allow mucus to cycle out one opening and back through another; identifying and incorporating the natural ostium avoids this.',
      'A maxillary antrostomy should join the native drainage pathway, not compete with it.',
      'Where is the nasolacrimal duct relative to the anterior maxillary antrostomy and how does that constrain enlargement?', 'OR_prep'),

    Q('v143_rhi_04', 'Rhinology / Allergy / Skull Base', 'Ethmoidectomy',
      'During complete ethmoidectomy, which pair of structures forms the key superior and lateral danger boundaries?',
      ['Skull base/fovea ethmoidalis superiorly and lamina papyracea laterally', 'Hard palate and mandible', 'Carotid bifurcation and jugular foramen', 'External auditory canal and sigmoid sinus'], 0,
      'Safe ethmoidectomy depends on continuous three-dimensional orientation to the skull base and orbit. The lamina papyracea is the lateral boundary and the fovea/cribriform region the superior boundary, with asymmetry and low skull base increasing risk.',
      'The ethmoid is a box between orbit and skull base; losing either wall is how major complications happen.',
      'If orbital fat suddenly prolapses into the field, what should you stop doing and what immediate checks are appropriate?', 'OR_prep'),

    Q('v143_rhi_05', 'Rhinology / Allergy / Skull Base', 'Odontogenic Sinusitis',
      'A patient has unilateral foul-smelling maxillary drainage and pressure after a maxillary molar extraction. CT shows unilateral maxillary disease with a periapical defect and extension into the anterior ethmoid. What is the best management principle?',
      ['Treat the dental source and the diseased sinonasal drainage pathway in a coordinated fashion when both require intervention', 'Perform sinus surgery while ignoring the dental source', 'Treat indefinitely with intranasal steroid alone', 'Assume allergy because all CRS is bilateral'], 0,
      'Odontogenic sinusitis is commonly unilateral and will recur if the dental source is not controlled. Some patients also need endoscopic sinus surgery for persistent disease, obstruction, extrasinus spread, or to restore drainage.',
      'Unilateral maxillary sinusitis deserves a dental question and a dental look.',
      'How does an oroantral fistula after extraction change the surgical plan?', 'boards'),

    Q('v143_hno_01', 'Head & Neck Oncology', 'Glottic Cancer',
      'A patient has a small T1 glottic squamous cell carcinoma confined to one true vocal fold with normal mobility and no nodes. Which treatment principle is most appropriate?',
      ['Choose a single definitive modality such as transoral laser microsurgery or radiation based on exposure, voice goals, anatomy and patient factors', 'Routine total laryngectomy', 'Mandatory bilateral neck dissection', 'Induction chemotherapy alone'], 0,
      'Early glottic cancer is highly curable with a single local modality. Transoral surgery and radiation can both be appropriate; elective neck treatment is often unnecessary for truly early glottic disease because lymphatic density is low.',
      'For early glottic cancer, maximize cure while avoiding combined-modality morbidity.',
      'What finding would upstage to impaired/fixed vocal-fold mobility and substantially change treatment planning?', 'boards'),

    Q('v143_hno_02', 'Head & Neck Oncology', 'HPV-Associated Oropharyngeal SCC',
      'A 54-year-old never-smoker has a p16-positive tonsillar SCC with a small primary and ipsilateral cystic nodal disease. Which statement is most accurate?',
      ['HPV-associated OPSCC uses a distinct prognostic staging system, but treatment still depends on anatomic extent and multidisciplinary modality selection', 'p16 positivity means no treatment is needed', 'All patients require total laryngectomy', 'Cystic nodes are benign by definition'], 0,
      'HPV-mediated oropharyngeal SCC has distinct AJCC prognostic staging and generally favorable prognosis, but treatment remains risk- and extent-based using surgery and/or radiation with systemic therapy when indicated.',
      'Better prognosis does not mean trivial disease; do not confuse prognostic staging with permission to undertreat outside evidence-based pathways.',
      'If transoral surgery reveals extranodal extension or positive margins, how can that alter adjuvant therapy?', 'boards'),

    Q('v143_hno_03', 'Head & Neck Oncology', 'Neck Management by Primary Site',
      'A patient has a lateral oral tongue SCC with clinically N0 neck but depth/invasion confers substantial occult nodal risk. What is the key neck-management principle?',
      ['Electively treat the appropriate ipsilateral nodal levels when occult risk is sufficiently high rather than waiting for palpable disease', 'Never treat a clinically negative neck', 'Always perform bilateral radical neck dissection', 'Use PET alone as definitive neck treatment'], 0,
      'Clinically N0 does not equal pathologically node-negative. Primary site, T category, depth of invasion, midline proximity and known lymphatic drainage determine whether elective neck dissection or elective radiation is warranted and which levels are treated.',
      'The neck is treated according to occult-risk biology and drainage, not palpability alone.',
      'How does a primary crossing or approaching the midline change concern for contralateral nodal treatment?', 'OR_prep'),

    Q('v143_hno_04', 'Head & Neck Oncology', 'Cutaneous Melanoma of the Head & Neck',
      'A patient has a clinically node-negative invasive scalp melanoma with sufficient Breslow depth to warrant nodal staging. What principle is most appropriate?',
      ['Discuss sentinel lymph-node biopsy when indicated; head-and-neck lymphatic drainage can be complex and may involve parotid or multiple basins', 'Perform elective radical neck dissection for every melanoma', 'Ignore the neck because melanoma never spreads lymphatically', 'Use thyroidectomy for staging'], 0,
      'Sentinel-node biopsy provides pathologic nodal staging for appropriately selected clinically node-negative melanoma. In the head and neck, mapping is especially useful because drainage is variable and may include intraparotid nodes.',
      'Map first; do not assume scalp and facial melanomas drain to one predictable neck basin.',
      'How would a positive intraparotid sentinel node change multidisciplinary regional-management discussion?', 'boards'),

    Q('v143_hno_05', 'Head & Neck Oncology', 'Parapharyngeal Space Tumor',
      'Imaging shows a prestyloid parapharyngeal mass displacing the carotid space posteromedially and containing fat-plane continuity with the deep parotid. What origin is most likely?',
      ['Deep-lobe parotid/salivary origin', 'Vagal schwannoma', 'Carotid body tumor', 'Thyroid nodule'], 0,
      'Prestyloid masses are commonly salivary or fat-containing lesions, whereas poststyloid masses arise from neurovascular structures. Displacement patterns on cross-sectional imaging help predict compartment and nerve/vessel of origin before surgery.',
      'Parapharyngeal-space imaging is a displacement-anatomy problem before it is a pathology problem.',
      'If the internal carotid is encased or the mass extends to the skull base, how does that change operative planning and counseling?', 'OR_prep'),

    Q('v143_tps_01', 'Thyroid / Parathyroid / Salivary', 'Differentiated Thyroid Cancer',
      'A 38-year-old has a 1.4 cm intrathyroidal papillary thyroid carcinoma in one lobe, no suspicious nodes, no gross extrathyroidal extension and no contralateral disease. Which surgical principle is most appropriate?',
      ['Thyroid lobectomy is an appropriate definitive operation for properly selected low-risk unilateral disease', 'Total thyroidectomy plus RAI is mandatory for every papillary cancer', 'Central neck dissection is mandatory despite cN0 status', 'No need to evaluate the neck preoperatively'], 0,
      'Modern risk-adapted thyroid cancer surgery permits lobectomy for selected low-risk unilateral differentiated cancers. Extent should reflect tumor size, invasion, nodes, contralateral disease, need for adjuvant therapy and patient preference.',
      'Do not let the word cancer automatically turn a lobectomy-sized problem into a total-thyroidectomy problem.',
      'What adverse preoperative or intraoperative finding would make total thyroidectomy or therapeutic nodal surgery more compelling?', 'boards'),

    Q('v143_tps_02', 'Thyroid / Parathyroid / Salivary', 'Indeterminate Thyroid Cytology / Molecular Testing',
      'A 2.2 cm thyroid nodule is Bethesda III on repeat FNA, ultrasound is not highly suspicious, and the patient wants to avoid unnecessary surgery. What is the best role for molecular testing?',
      ['Use it as an adjunct to refine malignancy risk and inform surveillance versus diagnostic surgery in the context of pretest risk', 'Use it as a perfect stand-alone cancer diagnosis', 'Ignore ultrasound and clinical context once a molecular result returns', 'Order RAI before diagnosis'], 0,
      'Molecular classifiers can change post-test risk for indeterminate cytology, but performance depends on pretest prevalence and the specific assay. Results should be integrated with ultrasound, patient factors, and preferences rather than treated as absolute truth.',
      'A molecular test changes probability; it does not replace clinical reasoning.',
      'How does a high-risk driver mutation differ from a benign-pattern classifier result in counseling about extent/timing of surgery?', 'boards'),

    Q('v143_tps_03', 'Thyroid / Parathyroid / Salivary', 'MEN2 / RET',
      'A patient with a pathogenic RET variant associated with MEN2 is planning thyroid surgery. Which preoperative step is essential before thyroidectomy?',
      ['Biochemically evaluate for pheochromocytoma and treat it first if present', 'Proceed directly to thyroidectomy without endocrine workup', 'Give RAI before surgery', 'Perform parathyroid autotransplant in every case'], 0,
      'Unrecognized pheochromocytoma can cause a lethal catecholamine crisis during anesthesia. In MEN2, pheochromocytoma must be excluded and addressed before elective thyroidectomy for medullary thyroid carcinoma risk.',
      'In MEN2, the adrenal question can be more immediately dangerous than the thyroid question.',
      'How do RET genotype and age influence timing of prophylactic thyroidectomy in an asymptomatic carrier?', 'overnight_call'),

    Q('v143_tps_04', 'Thyroid / Parathyroid / Salivary', 'Parathyroid Carcinoma',
      'A patient has calcium 15.2 mg/dL, PTH more than 10 times normal, a firm 3.5 cm parathyroid-region mass and hoarseness. What operative principle is most important if carcinoma is strongly suspected?',
      ['Plan an en bloc oncologic resection without rupturing the capsule rather than a simple shell-out', 'Perform fine-needle aspiration through the mass routinely', 'Morcellate the tumor for removal', 'Observe because high PTH excludes malignancy'], 0,
      'Parathyroid carcinoma is suggested by severe hypercalcemia, markedly elevated PTH, large invasive-appearing mass or RLN symptoms. When suspected, initial en bloc resection with involved adjacent tissue offers the best chance of local control; capsule violation can seed tumor.',
      'Parathyroid carcinoma is one of the situations where a clean first operation matters enormously.',
      'How would preoperative vocal-fold paralysis alter suspicion and counseling about RLN sacrifice versus preservation?', 'OR_prep'),

    Q('v143_tps_05', 'Thyroid / Parathyroid / Salivary', 'Sialendoscopy',
      'A patient has recurrent meal-related submandibular swelling. CT shows a 3 mm mobile distal duct stone with no gland mass. What is the best gland-preserving strategy?',
      ['Sialendoscopic retrieval or endoscopically assisted removal', 'Immediate submandibular gland excision in every case', 'Neck dissection', 'Long-term antibiotics without addressing obstruction'], 0,
      'Small accessible duct stones are ideal for gland-preserving endoscopic or endoscopically assisted management. Gland excision is reserved for selected refractory, intraparenchymal, inaccessible, or severely damaged glands.',
      'Sialendoscopy turns many obstructive salivary problems from gland-removal operations into duct-preservation procedures.',
      'What stone size/location may require combined transoral-endoscopic removal or lithotripsy rather than basket extraction alone?', 'OR_prep'),

    Q('v143_ped_01', 'Pediatric Otolaryngology', 'Branchial Cleft Anomalies',
      'A child has recurrent infections from a pit at the anterior border of the lower SCM with a tract coursing between the internal and external carotid arteries toward the tonsillar fossa. Which anomaly is most consistent?',
      ['Second branchial cleft tract', 'First branchial cleft anomaly', 'Thyroglossal duct cyst', 'Dermoid cyst'], 0,
      'A classic second branchial cleft tract travels from the lateral neck, between the carotid bifurcation, and toward the tonsillar fossa. Knowing embryologic course is essential for complete excision and protection of adjacent nerves/vessels.',
      'Branchial anomalies are tested by tract anatomy, not just by where the skin pit appears.',
      'How does a first branchial cleft anomaly change concern for the facial nerve during surgery?', 'OR_prep'),

    Q('v143_ped_02', 'Pediatric Otolaryngology', 'Congenital CMV Hearing Loss',
      'An infant passes the newborn hearing screen but is known to have congenital CMV infection. What is the most important hearing-management principle?',
      ['Arrange longitudinal audiologic surveillance because CMV-related SNHL can be delayed-onset, progressive or fluctuating', 'No further hearing testing is needed after a pass', 'Prophylactic cochlear implantation', 'Treat all hearing loss with tympanostomy tubes'], 0,
      'Congenital CMV can cause hearing loss that appears after the newborn period or progresses over time. Serial age-appropriate audiology is therefore required even after an initial screen is normal.',
      'A passed newborn screen does not close the hearing file in congenital CMV.',
      'How would newly identified unilateral severe SNHL change early-intervention and amplification/implant counseling?', 'boards'),

    Q('v143_ped_03', 'Pediatric Otolaryngology', 'Laryngotracheal Cleft',
      'An infant has coughing and cyanosis with feeds, recurrent pneumonias, and persistent aspiration despite appropriate feeding therapy. Flexible examination is unrevealing. What test best establishes a suspected type I laryngeal cleft?',
      ['Direct laryngoscopy with careful palpation of the interarytenoid region', 'Chest x-ray alone', 'Tympanometry', 'Skin-prick allergy testing'], 0,
      'Small laryngeal clefts can be missed on flexible inspection. Suspension/direct laryngoscopy with palpation of the posterior glottis is the diagnostic standard when suspicion persists.',
      'When aspiration physiology does not fit the flexible exam, palpate the posterior glottis under direct visualization.',
      'What clinical factors support endoscopic cleft repair rather than continued conservative swallowing management?', 'OR_prep'),

    Q('v143_ped_04', 'Pediatric Otolaryngology', 'Pediatric Aspiration',
      'A neurologically impaired child has recurrent pneumonias and cough with thin liquids. Which study most directly answers whether aspiration occurs during the swallow and which consistencies/strategies alter it?',
      ['Instrumental swallow evaluation such as VFSS or FEES selected to the clinical question', 'Routine sinus CT', 'Pure-tone audiogram', 'Sleep study only'], 0,
      'Instrumental swallow assessment defines timing, consistency, residue, penetration/aspiration and response to compensatory strategies. Choice between VFSS and FEES depends on age, anatomy, secretion assessment and the question being asked.',
      'Do not treat aspiration as a single diagnosis—define when, why, and with what material it occurs.',
      'If the child aspirates secretions continuously despite maximal therapy and has life-threatening lung disease, what aspiration-prevention options enter the discussion?', 'boards'),

    Q('v143_ped_05', 'Pediatric Otolaryngology', 'Recurrent Respiratory Papillomatosis',
      'A child with recurrent respiratory papillomatosis has frequent procedures and bulky disease approaching the anterior commissure. Which operative principle is most important?',
      ['Debulk to restore airway/voice while minimizing injury to normal mucosa and avoiding unnecessary opposing raw surfaces', 'Attempt radical deep excision into normal laryngeal tissue to eradicate HPV', 'Create permanent anterior commissure raw surfaces bilaterally', 'Use tracheostomy routinely as first-line therapy'], 0,
      'RRP is usually managed by repeated conservative debulking rather than destructive oncologic margins. Tissue preservation reduces scarring/stenosis, and adjuvant therapy can be considered in aggressive disease.',
      'The goal is disease control with a functional larynx, not histologically negative margins.',
      'What disease pattern or procedure frequency would make adjuvant systemic/intralesional therapy more attractive?', 'OR_prep'),

    Q('v143_lar_01', 'Laryngology / Voice / Swallowing', 'FEES',
      'A patient with neurologic dysphagia needs repeated bedside evaluation of secretion management and fatigue across a meal. Which feature makes FEES especially useful?',
      ['Direct repeated assessment of pharyngeal/laryngeal secretions and airway protection without radiation', 'It visualizes the oral and esophageal phases continuously', 'It eliminates the brief white-out during the swallow', 'It measures lower esophageal sphincter pressure'], 0,
      'FEES is portable, repeatable, radiation-free and particularly strong for secretion assessment, laryngeal sensation, residue and repeated trials. It has a brief white-out during the swallow and does not directly show the oral or esophageal phase.',
      'Choose the swallow test for the question; FEES excels when secretions, airway protection and repeated bedside assessment matter.',
      'When would VFSS add information that FEES cannot provide well?', 'boards'),

    Q('v143_lar_02', 'Laryngology / Voice / Swallowing', 'Microlaryngoscopy',
      'During suspension microlaryngoscopy for a small vocal-fold lesion, which principle best protects long-term voice outcome?',
      ['Use precise superficial dissection that preserves as much normal epithelium and superficial lamina propria as possible', 'Take a deep full-thickness cordectomy for every benign lesion', 'Apply broad thermal injury to ensure hemostasis', 'Ignore exposure-related dental and tongue risks'], 0,
      'Phonomicrosurgery aims to preserve the layered vibratory structure of the vocal fold. Excessive tissue removal, thermal injury, or deep dissection can create scar and permanent stiffness.',
      'The best benign-lesion operation removes the pathology while leaving the vibratory cover behaving like a vocal fold.',
      'What exposure or anesthetic limitations should be discussed before suspension laryngoscopy?', 'OR_prep'),

    Q('v143_lar_03', 'Laryngology / Voice / Swallowing', 'Leukoplakia / Laryngeal Dysplasia',
      'A smoker has persistent unilateral true-vocal-fold leukoplakia with irregular vascularity and reduced mucosal wave. What is the best next step?',
      ['Obtain tissue diagnosis with appropriately planned microlaryngoscopy/biopsy rather than prolonged empiric observation', 'Assume candidiasis and never biopsy', 'Treat with tonsillectomy', 'Reassure because leukoplakia cannot harbor carcinoma'], 0,
      'Leukoplakia is a descriptive surface finding with a spectrum from benign keratosis to invasive carcinoma. Concerning morphology, vascularity, stiffness, persistence or risk factors lower the threshold for biopsy.',
      'Leukoplakia is not a diagnosis; the management question is how likely the white plaque is hiding dysplasia or invasion.',
      'How does severe dysplasia/carcinoma in situ change surveillance and excision strategy compared with benign keratosis?', 'boards'),

    Q('v143_lar_04', 'Laryngology / Voice / Swallowing', 'Posterior Cordotomy / Arytenoidectomy',
      'A patient has chronic bilateral vocal-fold immobility with a critically narrow glottic airway, acceptable swallowing, and a strong desire to decannulate. What trade-off should be emphasized before posterior cordotomy?',
      ['A larger posterior airway can improve breathing/decannulation but may worsen voice and sometimes swallowing', 'The procedure restores normal bilateral vocal-fold motion', 'It has no effect on voice', 'It is designed primarily to improve nasal airflow'], 0,
      'Posterior cordotomy and/or arytenoidectomy enlarge the static glottic airway when motion will not recover. The fundamental trade-off is airway gain versus glottic competence for voice and swallowing.',
      'Every static airway-widening procedure spends some glottic closure to buy airway.',
      'How would active recovery potential or a fixated cricoarytenoid joint change procedure selection?', 'OR_prep'),

    Q('v143_lar_05', 'Laryngology / Voice / Swallowing', 'Radiation-Associated Dysphagia',
      'A head-and-neck cancer survivor years after chemoradiation has progressive solid-food dysphagia, weight loss and aspiration. Which approach is most appropriate?',
      ['Perform instrumental swallow assessment and evaluate for stricture, fibrosis/weakness, cranial neuropathy and recurrent disease rather than assuming a single mechanism', 'Reassure that late radiation dysphagia is always stable', 'Perform vocal-fold injection without evaluation', 'Treat only with antibiotics'], 0,
      'Late radiation dysphagia can reflect fibrosis, reduced hyolaryngeal excursion, neuropathy, xerostomia, stenosis, aspiration and recurrent cancer. Workup should define the mechanism and nutritional/pulmonary consequences before targeted therapy.',
      'Late radiation toxicity is a syndrome of mechanisms, not one diagnosis.',
      'If a focal pharyngoesophageal stenosis is found, how can dilation and swallowing therapy complement each other?', 'boards'),

    Q('v143_fpt_01', 'Facial Plastics / Trauma', 'Facial Soft-Tissue Lacerations / Burns',
      'A deep cheek laceration crosses the expected parotid duct and buccal facial-nerve branches. Before closing the skin, what is the best principle?',
      ['Assess facial movement before anesthesia when possible and specifically evaluate/repair duct and nerve injuries before layered closure', 'Close the skin immediately and ignore deeper structures', 'Ligate every facial nerve branch', 'Excise the parotid gland'], 0,
      'Deep facial lacerations require structured assessment of facial nerve function, parotid duct, lacrimal structures and tissue viability. Primary repair of identifiable important injuries is easiest before swelling/scarring and before skin closure obscures anatomy.',
      'A beautiful skin closure cannot rescue a missed duct or facial nerve injury underneath it.',
      'How does a nerve injury medial versus lateral to the lateral canthus influence whether distal branch repair is necessary?', 'overnight_call'),

    Q('v143_fpt_02', 'Facial Plastics / Trauma', 'Frontal Sinus Fracture',
      'A frontal sinus fracture has a displaced anterior table causing contour deformity, intact posterior table, and a patent frontal outflow tract. What is the main treatment goal?',
      ['Restore anterior-table contour while preserving a functioning sinus when feasible', 'Cranialize every frontal sinus fracture', 'Ignore cosmetic deformity because posterior table is intact', 'Obliterate the sinus regardless of drainage'], 0,
      'Anterior-table-only injuries are primarily a contour problem. Posterior table integrity and frontal outflow tract status drive intracranial/infectious risk and whether sinus-preserving repair is appropriate.',
      'Frontal sinus decisions are built from three variables: anterior table, posterior table, and outflow tract.',
      'How would persistent CSF leak plus a severely comminuted posterior table change the operation?', 'OR_prep'),

    Q('v143_fpt_03', 'Facial Plastics / Trauma', 'Le Fort / Panfacial Trauma',
      'A patient with panfacial fractures has lost normal occlusion and facial width/height. Which operative sequencing principle is most useful?',
      ['Re-establish reliable facial reference points and occlusion, then reconstruct stable buttresses in a planned bottom-up/top-down or outside-in sequence tailored to the injuries', 'Fix whichever fragment is easiest without a global plan', 'Ignore occlusion until all plates are placed', 'Use only nasal bones as the reference for mandibular position'], 0,
      'Panfacial reconstruction requires restoration of facial width, projection, height and occlusion using stable reference segments and buttresses. Sequence depends on which portions of the craniofacial skeleton remain reliable.',
      'Panfacial trauma is a geometry problem—build from stable references rather than chasing fragments.',
      'How does a comminuted mandible with unreliable occlusion change which cranial reference you establish first?', 'OR_prep'),

    Q('v143_fpt_04', 'Facial Plastics / Trauma', 'NOE Fracture Mechanics',
      'A comminuted NOE fracture has the medial canthal tendon attached to a tiny unstable central fragment (Markowitz type II pattern). What is the critical reconstructive objective?',
      ['Rigidly reposition and stabilize the canthal-bearing segment to restore intercanthal distance and nasal projection', 'Reduce only the nasal bones and ignore the canthus', 'Resect both medial canthal tendons', 'Perform isolated orbital floor grafting'], 0,
      'NOE reconstruction succeeds only if the medial canthal tendon or its attached bone is restored to a stable anatomic position. Failure produces telecanthus, loss of nasal projection and difficult secondary deformity.',
      'In NOE trauma, the medial canthal tendon-bearing fragment is the key fragment.',
      'If the tendon is avulsed from bone entirely, what fixation strategy may be required?', 'OR_prep'),

    Q('v143_fpt_05', 'Facial Plastics / Trauma', 'Rhinoplasty Graft Selection',
      'A patient has internal nasal valve narrowing after prior rhinoplasty with a narrow middle vault. Which graft is classically used to widen/support the internal valve and dorsal aesthetic lines?',
      ['Spreader graft', 'Columellar strut only', 'Auricular composite graft to the lobule', 'Temporalis fascia alone'], 0,
      'Spreader grafts placed between the dorsal septum and upper lateral cartilages can widen the internal nasal valve angle and reconstruct the middle vault. Other grafts address different structural problems.',
      'Choose a rhinoplasty graft by the mechanical deficit it is supposed to correct.',
      'When might an autospreader flap or lateral-wall suspension be preferable or additive?', 'OR_prep'),

    Q('v143_slp_01', 'Sleep Surgery', 'Central Events / Hypoventilation',
      'A polysomnogram shows frequent apneas with absent respiratory effort and sustained nocturnal hypercapnia rather than obstructive flow limitation. What is the key next step?',
      ['Evaluate central apnea/hypoventilation causes and tailor ventilatory therapy rather than sending directly for upper-airway surgery', 'Perform UPPP because all apneas are obstructive', 'Tonsillectomy regardless of age/anatomy', 'Ignore CO2 data'], 0,
      'Absent respiratory effort and hypercapnia point away from a purely collapsible upper-airway problem. Cardiac, neurologic, medication, altitude, neuromuscular and hypoventilation causes may require distinct PAP/ventilatory strategies.',
      'Before offering sleep surgery, prove the events are actually obstructive.',
      'What medications or comorbidities are common reversible contributors to central events or hypoventilation?', 'boards'),

    Q('v143_slp_02', 'Sleep Surgery', 'HNS Troubleshooting / Nonresponse',
      'A patient has persistent moderate OSA 8 months after hypoglossal nerve stimulator implantation despite good nightly adherence. What is the best next step?',
      ['Reassess device settings, electrode/tongue motion, sleep-study response and residual collapse pattern before labeling therapy a failure', 'Explant immediately without evaluation', 'Increase amplitude indefinitely despite discomfort', 'Assume weight and anatomy cannot change'], 0,
      'HNS nonresponse can reflect programming, inadequate tongue recruitment, residual palatal/lateral-wall collapse, weight change, positional factors or inappropriate original phenotype. Structured re-evaluation can identify a correctable cause.',
      'HNS is a titratable system; nonresponse deserves phenotyping before explantation.',
      'How can awake endoscopy or repeat DISE help when programming changes do not restore control?', 'OR_prep'),

    Q('v143_slp_03', 'Sleep Surgery', 'Lingual Tonsil / Tongue-Base Obstruction',
      'A child has persistent OSA after adenotonsillectomy. DISE shows dominant lingual tonsil hypertrophy with tongue-base collapse. What is the best management principle?',
      ['Target the demonstrated site, such as lingual tonsillectomy with or without additional tongue-base therapy when appropriate', 'Repeat palatine tonsillectomy', 'Perform nasal fracture reduction', 'Ignore DISE and choose surgery randomly'], 0,
      'Residual pediatric OSA is often multilevel. When DISE demonstrates substantial lingual-tonsil/tongue-base obstruction, site-directed treatment is more rational than repeating already-completed palatal surgery.',
      'Residual OSA should trigger re-localization, not repetition.',
      'What syndromic or obesity-related factors predict persistent multilevel disease even after tongue-base treatment?', 'OR_prep'),

    Q('v143_slp_04', 'Sleep Surgery', 'Pediatric PSG Interpretation',
      'A 6-year-old PSG shows obstructive apneas/hypopneas, oxygen desaturations and elevated obstructive AHI, but very few central events. Which principle differs from adult interpretation?',
      ['Children use pediatric event definitions and much lower AHI thresholds for abnormality/severity than adults', 'An AHI under 15 is always normal in children', 'Central events automatically mean epilepsy', 'Oxygen data are irrelevant'], 0,
      'Pediatric PSG uses age-specific scoring and lower thresholds because even relatively small obstructive event burdens can be clinically significant. Gas exchange, arousals and comorbidities also matter.',
      'Do not apply adult AHI cutoffs to a child.',
      'How would significant nocturnal hypoventilation change perioperative risk even if the AHI were only moderate?', 'boards'),

    Q('v143_slp_05', 'Sleep Surgery', 'Palatal Surgery Selection for OSA',
      'An adult with PAP intolerance has favorable anatomy and DISE showing primary anteroposterior palatal collapse without major tongue-base or complete concentric collapse. What is the best surgical principle?',
      ['Select a palatal procedure matched to the collapse pattern and counsel that isolated palatal surgery works best in appropriately phenotyped patients', 'Perform the same UPPP on every OSA patient', 'Ignore BMI and collapse pattern', 'Use HNS specifically to treat complete concentric palatal collapse'], 0,
      'Sleep surgery is phenotype-driven. Palatal procedures are most effective when the palate is a meaningful primary obstruction site and patient anatomy/risk profile are favorable; multilevel disease may require a multilevel plan.',
      'The operation should match the collapse you actually observed.',
      'Which DISE pattern is a classic contraindication to standard unilateral hypoglossal nerve stimulation candidacy?', 'OR_prep'),

    Q('v143_gen_01', 'General ENT / Emergencies', 'Caustic Ingestion',
      'A patient intentionally ingests a strong alkali and presents with drooling, odynophagia and chest pain. What is the best initial principle?',
      ['Stabilize airway/hemodynamics, avoid induced emesis or blind neutralization, and coordinate timely endoscopic/CT evaluation based on severity', 'Induce vomiting immediately', 'Give acid to neutralize the alkali', 'Discharge if the oral cavity looks normal'], 0,
      'Caustic injury severity cannot be inferred from the mouth alone. Airway and perforation risk come first; emesis and neutralization can worsen injury, and symptomatic/significant ingestions need coordinated GI/ENT/surgical evaluation.',
      'A normal mouth does not exclude a dangerous esophageal or gastric burn.',
      'What findings suggest perforation or transmural necrosis and push management toward emergency surgery rather than routine endoscopy?', 'overnight_call'),

    Q('v143_gen_02', 'General ENT / Emergencies', 'Deep Neck Abscess Drainage',
      'CT shows a 4 cm rim-enhancing parapharyngeal abscess with trismus, fever and early airway deviation despite IV antibiotics. What is the best management?',
      ['Secure/plan the airway and perform timely surgical drainage with culture plus broad antimicrobial therapy', 'Continue oral antibiotics alone indefinitely', 'Needle the carotid space blindly at bedside', 'Delay intervention until septic shock'], 0,
      'A large organized deep-neck collection with clinical progression, airway effect or failure of medical therapy usually requires drainage. Airway strategy is part of the operation because induction can worsen obstruction.',
      'Deep-neck infection management is airway + source control + antibiotics, in that order when the airway is threatened.',
      'How does suspected descending mediastinitis change imaging extent and surgical-team involvement?', 'overnight_call'),

    Q('v143_gen_03', 'General ENT / Emergencies', 'Lemierre Syndrome',
      'A 20-year-old has worsening fever and unilateral neck pain one week after pharyngitis. CT shows internal jugular vein thrombosis and chest CT shows multiple peripheral cavitary nodules. What is the best treatment?',
      ['Prolonged antibiotics with strong anaerobic coverage, source control when needed, and individualized anticoagulation decisions', 'Topical nasal steroid alone', 'Immediate carotid endarterectomy', 'No treatment because IJV thrombosis is expected after pharyngitis'], 0,
      'Lemierre syndrome is septic internal-jugular thrombophlebitis, classically from Fusobacterium necrophorum, with septic emboli often to the lungs. Treatment centers on prolonged appropriate antibiotics and drainage of any source; anticoagulation is selective.',
      'Young patient + recent sore throat + neck pain + septic lung lesions is Lemierre until proven otherwise.',
      'What progression pattern would make anticoagulation more compelling despite limited randomized evidence?', 'overnight_call'),

    Q('v143_gen_04', 'General ENT / Emergencies', 'Peritonsillar Abscess',
      'An adult has unilateral severe sore throat, muffled voice, trismus, uvular deviation and a fluctuant superior tonsillar pillar. He can protect his airway and tolerate secretions. What is the best management?',
      ['Drain the abscess by needle aspiration or incision when appropriate, give antibiotics covering typical oral flora, and address hydration/analgesia', 'Tonsillectomy is mandatory in every first episode', 'No drainage because trismus proves viral pharyngitis', 'CT neck is mandatory before any treatment in a classic uncomplicated case'], 0,
      'Classic peritonsillar abscess is usually a clinical diagnosis. Drainage plus antibiotics and supportive care is standard in a stable patient; imaging is reserved for atypical anatomy, concern for deeper spread, or diagnostic uncertainty.',
      'Do not let a classic drainable PTA wait for a scan unless the story suggests something deeper or different.',
      'What history would make interval or acute tonsillectomy more reasonable?', 'overnight_call'),

    Q('v143_gen_05', 'General ENT / Emergencies', 'Common ENT Consult Triage / Disposition',
      'Which overnight ENT consult requires the most immediate bedside evaluation?',
      ['A post-thyroidectomy patient with rapidly expanding neck swelling, stridor and anxiety', 'Stable chronic unilateral tinnitus for two years', 'Incidental asymptomatic septal deviation', 'Routine cerumen impaction'], 0,
      'Rapidly expanding postoperative neck hematoma can progress to complete airway obstruction within minutes and outranks stable chronic complaints. Triage in ENT should prioritize airway, hemorrhage, vision, intracranial spread and rapidly progressive infection.',
      'ENT triage is physiology first: airway and uncontrolled bleeding beat diagnostic elegance.',
      'If the patient deteriorates before transport to the OR, what immediate wound-decompression maneuver may be lifesaving?', 'overnight_call'),
]
