"""v13.6 — canonical coverage closure for Otology and Rhinology/Allergy/Skull Base.

Every entry targets a topic reported missing by the live v13.5 audit. Cases are
management-discriminating and emphasize boards, overnight-call triage, or OR
planning rather than simple label recognition.
"""


def Q(qid, domain, topic, stem, choices, answer, explanation, pearl, curveball):
    return {
        "id": qid, "domain": domain, "topic": topic, "stem": stem,
        "choices": choices, "answer": answer, "explanation": explanation,
        "why_wrong": ["Review the explanation and compare the management principle with the clinical context." for _ in choices],
        "board_pearl": pearl, "curveball": curveball,
        "tier": "Curated board/call/OR", "mode": "Vignette",
    }


OTO = "Otology / Neurotology"
RHI = "Rhinology / Allergy / Skull Base"

VIGNETTES_V136 = [
    Q("v136_oto_01", OTO, "Acute Otitis Externa",
      "A diabetic patient has severe otalgia, canal edema and purulent debris but no cranial neuropathy or granulation extending beyond the canal. What is the best initial treatment?",
      ["Topical antimicrobial drops after careful canal toilet, with a wick if needed", "Immediate mastoidectomy", "Oral steroids alone", "Observation without ear precautions"], 0,
      "Uncomplicated acute otitis externa is primarily a topical-treatment disease; systemic therapy is reserved for extension beyond the canal or selected high-risk situations.",
      "Severe pain out of proportion, granulation tissue, cranial neuropathy, or skull-base findings should trigger concern for necrotizing otitis externa.",
      "The same patient develops progressive facial weakness and deep nocturnal pain. What workup and treatment now become urgent?"),

    Q("v136_oto_02", OTO, "Age-Related Hearing Loss / Presbycusis",
      "A 72-year-old reports progressive symmetric difficulty understanding speech in noise. Otoscopy is normal and audiometry shows bilateral sloping sensorineural loss with reduced speech-in-noise performance. What is the best next management step?",
      ["Counsel on communication strategies and offer appropriately fitted amplification", "Order temporal-bone CT routinely", "Treat with systemic steroids", "Reassure that intervention does not improve function"], 0,
      "Age-related hearing loss should be identified and treated because amplification, assistive devices and communication strategies can improve function and quality of life; unexplained asymmetry or poor word recognition changes the workup.",
      "Current AAO-HNS guidance emphasizes screening adults age 50 and older and escalation to cochlear-implant evaluation when appropriately fitted amplification remains inadequate.",
      "Despite optimized hearing aids, word recognition remains very poor. What referral should be considered?"),

    Q("v136_oto_03", OTO, "Audiologic Electrophysiology / ABR-OAE-ECoG",
      "A newborn fails automated hearing screening. Diagnostic testing shows absent OAEs but a normal cochlear microphonic with severely abnormal ABR waveforms. Which diagnosis best fits?",
      ["Auditory neuropathy spectrum disorder", "Otosclerosis", "Superior canal dehiscence", "BPPV"], 0,
      "Preserved outer-hair-cell activity or cochlear microphonic with abnormal neural synchrony on ABR suggests auditory neuropathy spectrum disorder.",
      "Know what each test samples: OAE reflects outer-hair-cell function; ABR samples synchronous auditory neural conduction; electrocochleography can evaluate cochlear/nerve potentials.",
      "How would prematurity or NICU history affect counseling and follow-up?"),

    Q("v136_oto_04", OTO, "Auditory Neuroanatomy / Cochlear Physiology",
      "A patient has a unilateral lesion of the auditory cortex. Which hearing deficit is most expected?",
      ["Difficulty with complex sound localization and processing rather than complete unilateral deafness", "Complete ipsilateral deafness", "Pure conductive hearing loss", "Isolated loss of vestibulo-ocular reflexes"], 0,
      "Central auditory pathways become bilateral above the cochlear nuclei, so a unilateral cortical lesion usually impairs higher-order processing/localization more than it causes total deafness in one ear.",
      "Boards often test the bilateral central auditory projection as the reason unilateral central lesions do not mimic cochlear destruction.",
      "Where along the pathway would a lesion produce an ipsilateral peripheral sensorineural loss?"),

    Q("v136_oto_05", OTO, "Cochlear Implant Failure / Revision",
      "A cochlear-implant user who previously performed well develops abrupt loss of sound perception after head trauma. Integrity testing shows abnormal electrode impedances. What is the next best step?",
      ["Prompt device evaluation with imaging/integrity testing and consideration of revision if hardware failure is confirmed", "Increase hearing-aid gain only", "Treat empirically for labyrinthitis without device testing", "No intervention because implants cannot be revised"], 0,
      "Sudden performance loss requires systematic assessment of external equipment, programming, electrode integrity, imaging and medical causes; confirmed internal hardware failure may require revision/reimplantation.",
      "Revision CI is not simply 'replace the device'—identify migration, infection, soft failure, hard failure, ossification and anatomy before operating.",
      "Imaging shows electrode migration from the cochlea. What operative issues should be discussed?"),

    Q("v136_oto_06", OTO, "Cochlear Implant Surgery",
      "During cochlear implantation, which operative goal most directly reduces insertion trauma and preserves residual cochlear structure?",
      ["Atraumatic scala-tympani electrode insertion through the round window or an appropriate cochleostomy", "Routine drilling into the vestibule", "Intentional ossicular disarticulation", "Packing the middle ear tightly around the electrode"], 0,
      "Modern CI technique prioritizes atraumatic scala-tympani placement, minimizing drill and insertion trauma while securing the receiver and electrode.",
      "Pre-op planning should review cochlear patency, facial-nerve course, mastoid anatomy, vaccination status, hearing goals and device-specific MRI considerations.",
      "What anatomy makes a malformed inner ear a higher-risk implantation?"),

    Q("v136_oto_07", OTO, "Congenital Inner-Ear Malformations",
      "A child with profound congenital SNHL has CT showing an incomplete partition malformation and a widened cochlear aperture. What operative concern is especially important during cochlear implantation?",
      ["CSF/perilymph gusher and atypical facial-nerve anatomy", "Mandatory stapedectomy", "External canal stenosis only", "No additional surgical risk"], 0,
      "Congenital inner-ear malformations may alter cochlear, IAC and facial-nerve anatomy and increase the risk of a CSF/perilymph gusher during cochlear entry.",
      "Always interpret congenital hearing loss as both an audiologic and an anatomic problem before implantation.",
      "How would cochlear nerve deficiency on MRI change candidacy counseling?"),

    Q("v136_oto_08", OTO, "Cortical Neuroplasticity in Hearing Loss",
      "Why is prolonged auditory deprivation an important consideration when counseling a child with congenital profound hearing loss about delayed implantation?",
      ["Auditory cortical pathways reorganize with deprivation, which can limit later speech and language benefit", "The ossicles always fuse after infancy", "The cochlea becomes infected without stimulation", "Hearing aids permanently damage auditory cortex"], 0,
      "Auditory development is time-sensitive; prolonged deprivation can produce maladaptive cortical reorganization and poorer later language outcomes.",
      "The biologic reason early access to sound matters is neurodevelopment, not merely convenience.",
      "How does this principle differ in an adult who lost hearing after normal language development?"),

    Q("v136_oto_09", OTO, "Eustachian Tube Dysfunction",
      "An adult has months of aural pressure and tympanic-membrane retraction with a type-C tympanogram. Nasopharyngoscopy is normal. Which finding best supports obstructive Eustachian tube dysfunction rather than patulous ETD?",
      ["Negative middle-ear pressure and retraction", "Autophony of breathing relieved when supine", "A tympanic membrane moving with respiration", "Symptoms only during vigorous exercise"], 0,
      "Obstructive ETD produces inadequate ventilation with negative pressure/retraction; patulous ETD classically causes autophony and respiratory TM movement.",
      "Do not offer balloon dilation solely for nonspecific ear fullness—document a compatible obstructive phenotype and exclude mimics.",
      "What additional evaluation is important for new unilateral adult middle-ear effusion?"),

    Q("v136_oto_10", OTO, "Hearing Aids and Bone-Conduction Devices",
      "A patient has maximal conductive hearing loss from congenital canal atresia with excellent cochlear reserve. Which rehabilitation strategy bypasses the external and middle ear?",
      ["Bone-conduction hearing device", "Systemic steroids", "Vestibular implant", "Tympanostomy tube through the atretic canal"], 0,
      "Bone-conduction devices transmit sound through skull vibration to a functioning cochlea and are useful when conventional air-conduction amplification is not feasible.",
      "Match the device to the site of deficit: air-conduction aids need a usable canal; bone conduction bypasses canal/middle ear; CI bypasses damaged hair-cell transduction.",
      "What factors determine implantable versus nonsurgical bone-conduction options?"),

    Q("v136_oto_11", OTO, "Hyperacusis / Decreased Sound Tolerance",
      "A patient reports ordinary environmental sounds as painfully loud after a normal audiogram and normal ear exam. What is the best management framework?",
      ["Confirm the phenotype, screen for migraine/anxiety or other contributors, counsel against excessive sound avoidance, and use graded sound-based therapy when appropriate", "Recommend continuous maximum-strength earplug use", "Perform stapedectomy", "Treat all cases as malingering"], 0,
      "Hyperacusis is a decreased sound-tolerance disorder that may coexist with tinnitus, migraine and anxiety. Excessive sound avoidance can reinforce central gain and disability.",
      "Differentiate hyperacusis, misophonia and recruitment; they are not interchangeable labels.",
      "What historical features would make superior canal dehiscence a competing diagnosis?"),

    Q("v136_oto_12", OTO, "Lateral Skull-Base Tumor Framework",
      "A patient has progressive unilateral hearing loss, lower cranial neuropathies and an enhancing jugular-foramen mass. What is the most useful first management framework?",
      ["Define compartment of origin, cranial-nerve function, vascularity, growth rate and patient goals before choosing observation, radiation or surgery", "Biopsy every lateral skull-base mass transcanally", "Assume all lesions are vestibular schwannomas", "Proceed directly to radical surgery without angiographic or cranial-nerve assessment"], 0,
      "Lateral skull-base tumors demand localization first; jugular foramen, petrous apex, CPA and temporal bone lesions have different differentials, vascular risks and morbidity profiles.",
      "The correct operation follows anatomy and biology; it should not precede them.",
      "If the lesion is highly vascular with salt-and-pepper MRI appearance, what tumor class rises on the differential?"),

    Q("v136_oto_13", OTO, "Neurotologic Intraoperative Cranial-Nerve Monitoring",
      "During CPA tumor surgery, facial-nerve EMG activity suddenly becomes sustained after traction. What is the best immediate response?",
      ["Stop the provoking maneuver, irrigate/reassess and allow the signal to recover before proceeding", "Increase traction to finish faster", "Ignore monitoring because anatomy alone matters", "Cut the nerve to eliminate false signals"], 0,
      "Monitoring is an adjunct that can warn of mechanical, thermal or ischemic nerve stress; a new concerning signal should change the operative maneuver.",
      "Monitoring does not replace direct anatomy, but its value is lost if warnings do not alter behavior.",
      "How do free-run EMG and stimulated thresholds provide different information?"),

    Q("v136_oto_14", OTO, "Otologic Manifestations of Systemic Disease",
      "A patient with granulomatosis with polyangiitis develops persistent serous otitis media, progressive mixed hearing loss and facial weakness despite tubes. What principle should guide management?",
      ["Consider systemic inflammatory disease activity rather than repeatedly treating the ear as isolated infection", "Repeat tympanostomy indefinitely without systemic evaluation", "Assume otosclerosis", "Avoid rheumatologic collaboration"], 0,
      "Systemic autoimmune and granulomatous disease can involve the middle ear, inner ear and facial nerve; local procedures may relieve sequelae but systemic control is often essential.",
      "Persistent or atypical ear disease can be the presenting sign of systemic disease.",
      "What red flags distinguish autoimmune inner-ear disease from routine age-related loss?"),

    Q("v136_oto_15", OTO, "Otosclerosis / Stapes Fixation",
      "A young adult has progressive conductive hearing loss, a normal tympanic membrane, absent stapedial reflexes and a Carhart notch. Which treatment is most appropriate when hearing loss is bothersome?",
      ["Discuss hearing amplification versus stapedotomy/stapedectomy based on goals and candidacy", "Tympanostomy tube placement", "Long-term antibiotics", "Labyrinthectomy"], 0,
      "Otosclerosis causing stapes fixation can be managed with amplification or stapes surgery in appropriately selected patients.",
      "Before stapes surgery, confirm the conductive mechanism and counsel about SNHL, vertigo, taste disturbance, prosthesis issues and the rare dead ear.",
      "How would an only-hearing ear alter operative counseling?"),

    Q("v136_oto_16", OTO, "Ototoxic / Noise-Induced Hearing Loss",
      "A patient receiving cisplatin develops new bilateral high-frequency tinnitus and hearing loss. What is the best next step?",
      ["Document audiometric change, coordinate ototoxicity monitoring and discuss dose/therapy implications with oncology", "Wait until profound deafness develops", "Treat with tympanostomy tubes", "Assume conductive loss"], 0,
      "Ototoxicity monitoring aims to identify threshold shifts early enough to inform oncologic risk-benefit decisions and rehabilitation planning.",
      "Noise and many ototoxins first affect high-frequency cochlear function; prevention and monitoring are more effective than trying to reverse established hair-cell loss.",
      "Which additional exposure can potentiate aminoglycoside ototoxicity risk?"),

    Q("v136_oto_17", OTO, "Persistent Postural-Perceptual Dizziness (PPPD)",
      "A patient has nonspinning dizziness and visual-motion sensitivity most days for 5 months after a resolved vestibular neuritis. Examination and vestibular testing are now largely compensated. What treatment is most appropriate?",
      ["Vestibular rehabilitation with education and treatment of anxiety/migraine contributors; SSRI/SNRI may help selected patients", "Repeated canalith repositioning despite no positional nystagmus", "Labyrinthectomy", "Strict bed rest"], 0,
      "PPPD is a chronic functional vestibular disorder often triggered by a vestibular event and maintained by maladaptive postural/visual dependence and threat processing.",
      "Normal or compensated vestibular testing does not make PPPD imaginary; the diagnosis depends on the characteristic persistent symptom pattern.",
      "How would episodic spontaneous vertigo with photophobia change the differential?"),

    Q("v136_oto_18", OTO, "Petrous Apex Lesions",
      "Imaging shows an expansile petrous-apex lesion that is intrinsically T1 bright and demonstrates restricted diffusion. The patient has diplopia from sixth-nerve involvement. Which diagnosis is most likely?",
      ["Cholesterol granuloma or cholesteatoma must be distinguished by MRI signal characteristics before selecting drainage versus removal", "Simple otitis externa", "BPPV", "Isolated tympanosclerosis"], 0,
      "Petrous-apex lesions are managed by imaging phenotype and relationship to carotid artery, cochlea, labyrinth, dura and cranial nerves; cholesterol granuloma and epidermoid/cholesteatoma require different strategies.",
      "For petrous-apex disease, route selection is an anatomy problem: transnasal, infracochlear, infralabyrinthine or other approaches depend on safe corridors.",
      "What imaging feature favors cholesterol granuloma over cholesteatoma?"),

    Q("v136_oto_19", OTO, "Temporal Bone Anatomy",
      "During mastoidectomy, which landmark is the most reliable guide to the vertical facial nerve as drilling approaches the facial recess?",
      ["The facial nerve course just medial to the short process of the incus, with the chorda tympani forming the lateral boundary of the facial recess", "The carotid canal", "The cochlear aqueduct", "The tegmen alone"], 0,
      "Safe temporal-bone surgery requires a three-dimensional relationship among the lateral semicircular canal, incus, facial nerve, chorda, sigmoid sinus, tegmen and labyrinth.",
      "Never learn mastoid anatomy as isolated structures; learn the surgical corridors and their danger boundaries.",
      "What are the three boundaries of the facial recess?"),

    Q("v136_oto_20", OTO, "Tympanic Membrane Perforation",
      "A patient has a dry traumatic central tympanic-membrane perforation and mild conductive loss 1 week after injury. What is the best initial management?",
      ["Dry-ear precautions and observation because many traumatic perforations heal spontaneously", "Immediate mastoidectomy", "Routine ototoxic drops", "Permanent water exposure to prevent crusting"], 0,
      "Most uncomplicated traumatic TM perforations heal with observation and dry-ear precautions; persistent perforation, infection, ossicular injury or major hearing loss changes management.",
      "Avoid aminoglycoside-containing drops when the middle ear is exposed unless there is a specific indication and risk-benefit rationale.",
      "At 4 months the perforation remains dry but unchanged. What repair options should be discussed?"),

    Q("v136_oto_21", OTO, "Vestibular Rehabilitation",
      "After unilateral vestibular neuritis, a patient avoids head movement because it provokes brief disequilibrium. Weeks later recovery has plateaued. What intervention best promotes central compensation?",
      ["Graded gaze-stabilization, balance and habituation exercises with early mobilization", "Prolonged vestibular-suppressant use", "Strict bed rest", "Repeated Epley maneuvers without BPPV"], 0,
      "Vestibular rehabilitation drives adaptation, substitution and habituation; prolonged suppressants can impede compensation after the acute phase.",
      "Use vestibular suppressants for severe acute symptoms briefly, not as chronic therapy for a compensated unilateral deficit.",
      "What finding would suggest that new BPPV has developed during recovery?"),

    Q("v136_oto_22", OTO, "Vestibular Test Battery",
      "A patient with chronic imbalance has normal calorics but an abnormal video head-impulse test only at high-frequency head rotations. What principle explains the discrepancy?",
      ["Different vestibular tests sample different frequency ranges and end organs, so discordance can be physiologic and diagnostically useful", "One of the tests must be invalid", "Calorics test only otolith function", "vHIT measures hearing rather than vestibular function"], 0,
      "Calorics, rotary chair, vHIT, VEMP and posturography interrogate different portions/frequencies of the vestibular system; interpretation is syndromic, not pass/fail.",
      "A vestibular battery localizes physiology; it does not replace the history.",
      "Which VEMP pathway predominantly samples saccular/inferior vestibular nerve function?"),

    # Rhinology / Allergy / Skull Base
    Q("v136_rhi_01", RHI, "AFRS",
      "A young immunocompetent adult with asthma has nasal polyps, heterogeneous hyperdense sinus contents, bony expansion and allergic mucin containing fungal hyphae without tissue invasion. What is the best framework?",
      ["Allergic fungal rhinosinusitis treated with surgery to clear disease plus anti-inflammatory postoperative therapy", "Acute invasive fungal rhinosinusitis requiring amphotericin for tissue invasion", "Simple viral URI", "Sinonasal lymphoma"], 0,
      "AFRS is a noninvasive eosinophilic inflammatory disease with allergic mucin, polyposis and characteristic expansile radiographic disease; surgery and long-term inflammatory control are central.",
      "Fungal elements in sinus material do not equal invasive fungal disease; tissue invasion and host context are decisive.",
      "What postoperative strategy reduces recurrence risk?"),

    Q("v136_rhi_02", RHI, "Acute Bacterial Rhinosinusitis",
      "An adult has purulent drainage, nasal obstruction and facial pressure for 12 days without improvement after a viral URI. Which diagnosis and initial strategy are appropriate?",
      ["ABRS; offer watchful waiting with reliable follow-up or appropriate first-line antibiotics depending on severity and shared decision-making", "Viral rhinosinusitis because fever is absent", "CRS requiring immediate ESS", "Invasive fungal sinusitis"], 0,
      "The 2025 AAO-HNS adult sinusitis update supports ABRS when symptoms persist at least 10 days without improvement or worsen after initial improvement; uncomplicated cases do not require routine imaging.",
      "Duration and double-worsening are more useful than mucus color alone for distinguishing ABRS from viral disease.",
      "What complication would make contrast imaging urgent?"),

    Q("v136_rhi_03", RHI, "Benign Sinonasal Tumor Framework",
      "A patient has a slowly growing unilateral nasal mass. Imaging shows smooth remodeling rather than aggressive destruction. What is the best next step?",
      ["Define site of origin, vascularity and skull-base/orbital relationships before biopsy or excision", "Blind office biopsy of every unilateral mass", "Assume inflammatory polyposis", "Treat indefinitely with antibiotics"], 0,
      "Benign sinonasal tumors still demand anatomic localization and vascular assessment because lesions such as angiofibroma can bleed catastrophically if biopsied indiscriminately.",
      "Unilateral disease is a diagnostic red flag; image before biopsy when vascularity or skull-base attachment is possible.",
      "Which demographic and imaging pattern would make juvenile nasopharyngeal angiofibroma likely?"),

    Q("v136_rhi_04", RHI, "CF / Primary Ciliary Dyskinesia Sinonasal Disease",
      "A young patient has lifelong pansinusitis, recurrent lower respiratory infections and bronchiectasis. Which evaluation is most appropriate?",
      ["Assess for cystic fibrosis or primary ciliary dyskinesia and coordinate multisystem care", "Treat as isolated seasonal allergic rhinitis", "Perform cosmetic septorhinoplasty first", "No pulmonary evaluation is needed"], 0,
      "Early-onset refractory CRS with chronic lower-airway disease should trigger evaluation for mucociliary disorders such as CF or PCD.",
      "Rhinologic disease can be the upper-airway expression of a systemic mucociliary disorder; surgery does not replace disease-specific pulmonary care.",
      "What laterality finding can accompany PCD/Kartagener syndrome?"),

    Q("v136_rhi_05", RHI, "CRS Phenotyping",
      "Two patients meet objective criteria for CRS; one has eosinophilic polyposis and asthma, while the other has purulence and no polyps. Why is phenotyping important?",
      ["It predicts different medical, biologic and surgical considerations and recurrence patterns", "All CRS receives identical therapy", "Phenotype matters only for coding", "Polyps exclude CRS"], 0,
      "CRS is heterogeneous. Polyp status, type-2 inflammation, asthma/AERD, odontogenic disease, fungal disease, immunodeficiency and other drivers change treatment and prognosis.",
      "Modern CRS care is diagnosis plus endotype/phenotype plus patient goals—not a single antibiotic ladder.",
      "Which phenotype should prompt discussion of biologic therapy?"),

    Q("v136_rhi_06", RHI, "CRSsNP",
      "An adult has >12 weeks of nasal obstruction and drainage with objective CT/endoscopic inflammation but no polyps. Symptoms persist despite appropriate saline and intranasal corticosteroid therapy. What is the next management principle?",
      ["Reassess diagnosis/comorbid drivers and discuss ESS when symptoms and objective disease remain significant despite individualized medical therapy", "Diagnose ABRS solely because symptoms are chronic", "Give indefinite antibiotics to every patient", "Biologic therapy is mandatory"], 0,
      "CRSsNP requires chronic symptoms plus objective inflammation. Surgery is considered when burden persists despite individualized medical management and after evaluating alternative drivers.",
      "The 2025 surgical CRS guideline emphasizes candidacy based on symptoms, disease characteristics and prior therapy—not an arbitrary one-size-fits-all medication duration.",
      "What CT finding should make odontogenic disease a competing driver?"),

    Q("v136_rhi_07", RHI, "CRSwNP",
      "A patient with asthma has bilateral polyps, anosmia and recurrent symptoms despite topical steroid irrigations. What treatment discussion is most appropriate?",
      ["Discuss ESS and/or biologic therapy based on disease burden, prior surgery, type-2 comorbidity and patient preference", "Antibiotics alone are definitive", "Polyps should never be biopsied or removed", "No further treatment is available"], 0,
      "CRSwNP often reflects type-2 inflammation; surgery restores ventilation/access for topical therapy while biologics may be appropriate in selected severe recurrent disease.",
      "For polyposis, surgery and biologics are complementary options selected by phenotype, prior treatment, cost, comorbidity and goals.",
      "What history should specifically raise concern for AERD?"),

    Q("v136_rhi_08", RHI, "Endoscopic CSF Leak Repair / Nasoseptal Flap",
      "A patient with a high-flow postoperative skull-base CSF leak is scheduled for endoscopic repair. Which reconstructive principle is most important?",
      ["Use a multilayer closure with well-vascularized tissue such as a pedicled nasoseptal flap when indicated", "Pack the nose without identifying the defect", "Avoid vascularized reconstruction for high-flow leaks", "Create a larger defect to equalize pressure"], 0,
      "High-flow skull-base leaks benefit from precise defect identification, multilayer reconstruction and vascularized coverage; the nasoseptal flap is a workhorse for large/high-risk defects.",
      "Preserve the posterior septal vascular pedicle when a nasoseptal flap may be needed later in the case.",
      "Which artery supplies the classic nasoseptal flap pedicle?"),

    Q("v136_rhi_09", RHI, "Endoscopic Maxillary Antrostomy",
      "During endoscopic maxillary antrostomy, why should the natural ostium be incorporated into the surgical opening?",
      ["To avoid recirculation between separate natural and accessory/surgical openings", "To protect the optic nerve", "To prevent septal perforation", "Because the maxillary sinus drains through the sphenoid ostium"], 0,
      "A proper antrostomy identifies and incorporates the natural maxillary ostium; a separate posterior opening can create mucus recirculation and persistent symptoms.",
      "The uncinate and natural ostium are orientation landmarks—do not confuse an accessory ostium for the natural drainage pathway.",
      "What orbital structure is at risk with overly aggressive superior dissection?"),

    Q("v136_rhi_10", RHI, "Ethmoidectomy",
      "During anterior ethmoidectomy, which structure forms a critical superior boundary whose violation risks intracranial injury?",
      ["Skull base/fovea ethmoidalis", "Inferior turbinate", "Hard palate", "Anterior nasal spine"], 0,
      "Ethmoid surgery requires constant orientation to lamina papyracea laterally and skull base superiorly, with asymmetric skull-base height and Keros depth affecting risk.",
      "Safe ethmoidectomy is an anatomy exercise: know orbit, skull base, anterior ethmoid artery and basal lamella before removing partitions.",
      "Why does a low-lying asymmetric skull base increase operative risk?"),

    Q("v136_rhi_11", RHI, "Facial Pain / Headache vs Rhinogenic Disease",
      "A patient has facial pressure and headaches but normal endoscopy and normal sinus CT between episodes. What is the best next step?",
      ["Reconsider migraine or another nonrhinogenic headache disorder rather than diagnosing CRS from pain alone", "Perform ESS for pain despite no objective inflammation", "Give indefinite antibiotics", "Diagnose fungal sinusitis"], 0,
      "Facial pain without objective sinonasal inflammation is commonly nonrhinogenic; migraine is frequently misdiagnosed as sinus headache.",
      "CRS requires objective evidence. Pain location alone is not a reliable sinus map.",
      "Which accompanying symptoms would support migraine over sinusitis?"),

    Q("v136_rhi_12", RHI, "Frontal Recess / Frontal Sinus",
      "Why is preoperative CT review especially important before frontal recess surgery?",
      ["Frontal drainage is determined by patient-specific cells and their relationship to the skull base, orbit and anterior ethmoid artery", "The frontal recess anatomy is identical in every patient", "CT is only useful after complications", "The frontal sinus drains through the nasolacrimal duct"], 0,
      "Frontal drainage anatomy is highly variable; agger nasi and frontal cells shape the pathway and determine safe dissection around orbit and skull base.",
      "Plan frontal surgery from CT in three planes rather than trying to discover complex anatomy blindly in the OR.",
      "What is the consequence of circumferential mucosal stripping in the frontal outflow tract?"),

    Q("v136_rhi_13", RHI, "Frontal Sinusotomy / Draf Procedures",
      "A patient with recalcitrant frontal sinus disease after prior surgery has severe bilateral frontal recess scarring. Which concept distinguishes increasingly extensive Draf procedures?",
      ["Progressive enlargement of the frontal drainage pathway up to a common bilateral opening in Draf III", "Increasing removal of the inferior turbinate", "Progressive narrowing of the frontal ostium", "Different antibiotic regimens"], 0,
      "Draf procedures describe escalating frontal sinusotomy extent; Draf III creates a common median drainage pathway by removing the superior septum and frontal sinus floor between orbits.",
      "Extensive frontal surgery is justified by disease and anatomy, not by the label of revision surgery alone.",
      "What postoperative problem makes meticulous topical care and debridement important after Draf III?"),

    Q("v136_rhi_14", RHI, "Fungal Ball",
      "An immunocompetent adult has unilateral maxillary opacification with internal hyperdensities. Surgery finds dense clay-like fungal debris without mucosal invasion. What is the appropriate treatment?",
      ["Endoscopic removal and restoration of drainage; systemic antifungals are usually unnecessary without invasion", "Long-term amphotericin for all cases", "Observe despite persistent obstruction", "Treat as AFRS with no surgery"], 0,
      "A fungal ball is noninvasive fungal colonization, commonly maxillary or sphenoid; complete removal and ventilation are usually curative.",
      "Differentiate fungal ball, AFRS and invasive fungal disease by host, inflammation and tissue invasion—not merely the word 'fungus.'",
      "What symptom would make a sphenoid fungal ball particularly concerning?"),

    Q("v136_rhi_15", RHI, "Immunodeficiency-Associated Chronic Rhinosinusitis",
      "A patient has refractory CRS plus recurrent pneumonias and unusually frequent bacterial infections. What is the best next step?",
      ["Evaluate for humoral or other immunodeficiency and coordinate treatment of the underlying immune defect", "Assume all failures are due to inadequate sinus surgery", "Avoid vaccination history", "Treat only with topical decongestants"], 0,
      "Frequent or atypical infections with refractory CRS should prompt immune evaluation; treating the host defect may be as important as local sinus therapy.",
      "When CRS behaves unusually, reconsider host factors before escalating surgery repeatedly.",
      "Which basic laboratory studies can screen humoral immunity?"),

    Q("v136_rhi_16", RHI, "Inferior Turbinate Hypertrophy",
      "A patient has chronic nasal obstruction from enlarged inferior turbinates despite allergy control and topical therapy. What surgical principle is preferred?",
      ["Reduce submucosal volume while preserving functional mucosa when possible", "Remove the entire turbinate routinely", "Fracture the nasal bones", "Perform frontal sinusotomy"], 0,
      "Turbinate surgery aims to improve airflow while preserving mucosal humidification and sensation; overly aggressive resection risks dryness, crusting and empty-nose symptoms.",
      "Think tissue preservation rather than 'bigger resection equals better airflow.'",
      "How does dynamic nasal valve collapse change the interpretation of persistent obstruction after turbinate reduction?"),

    Q("v136_rhi_17", RHI, "Nasal Anatomy for Endoscopy",
      "During diagnostic nasal endoscopy, which landmark best helps identify the sphenoethmoidal recess?",
      ["Superior turbinate, with the sphenoid ostium typically medial to it", "Inferior turbinate head", "Nasolacrimal valve", "Anterior nasal spine"], 0,
      "Endoscopic orientation depends on turbinates, septum, uncinate, middle meatus, superior turbinate, choana and skull-base relationships.",
      "Know where you are before you instrument: endoscopic anatomy is the first safety system in rhinology.",
      "Which major artery is at risk posteriorly near the sphenopalatine foramen?"),

    Q("v136_rhi_18", RHI, "Objective Assessment of Nasal Function",
      "A patient reports severe unilateral obstruction but has only mild septal deviation on exam. What is the best principle for objective assessment?",
      ["Use endoscopy and, when useful, validated symptom scores or airflow/resistance testing as adjuncts while recognizing that symptoms and objective measurements may not correlate perfectly", "CT airflow alone determines whether surgery is indicated", "Ignore patient-reported obstruction", "A normal Cottle maneuver excludes obstruction"], 0,
      "Nasal obstruction is multidimensional; endoscopy, structural exam, NOSE score, acoustic rhinometry/rhinomanometry and response to decongestion can clarify contributors but no single metric replaces clinical judgment.",
      "Objective tests are adjuncts, not an automatic surgical threshold.",
      "How would decongestant response help distinguish mucosal from fixed structural obstruction?"),

    Q("v136_rhi_19", RHI, "Odontogenic Sinusitis",
      "A patient has unilateral foul-smelling maxillary drainage and CT shows maxillary opacification adjacent to a periapical dental lesion. What is the best management?",
      ["Treat the dental source and address persistent sinus disease/drainage as needed, often collaboratively", "ESS alone while leaving the dental infection untreated", "Diagnose allergic rhinitis", "Observe indefinitely"], 0,
      "Odontogenic sinusitis often presents unilaterally and requires source control of dental pathology; sinus surgery may be needed for persistent disease but cannot substitute for dental treatment.",
      "Unilateral maxillary disease should trigger a dental review, even when the patient denies tooth pain.",
      "How does an oroantral fistula change management?"),

    Q("v136_rhi_20", RHI, "Olfactory Dysfunction",
      "A patient develops anosmia after a viral illness with normal endoscopy and no obstructing lesion. Which therapy has the best risk-benefit profile for persistent postviral olfactory loss?",
      ["Structured olfactory training", "Routine prolonged systemic antibiotics", "Inferior turbinectomy", "No counseling because recovery never occurs"], 0,
      "Olfactory training is a low-risk evidence-supported intervention for persistent postviral smell loss; workup is driven by history, endoscopy and red flags for central or obstructive disease.",
      "Smell loss can be conductive, sensorineural or central; first localize the mechanism.",
      "What unilateral neurologic or nasal findings would prompt imaging?"),

    Q("v136_rhi_21", RHI, "Pediatric Chronic Rhinosinusitis",
      "A child has chronic nasal drainage and cough despite appropriate medical therapy. Adenoid hypertrophy is prominent and there is no CF or immune disorder. What surgical step is commonly considered before full ESS in younger children?",
      ["Adenoidectomy, with or without adjunctive sinus procedures depending on disease", "Total turbinectomy", "Draf III", "No surgery can ever be appropriate"], 0,
      "Adenoid disease can serve as a bacterial reservoir and contribute to pediatric CRS; adenoidectomy is often an early surgical intervention before extensive ESS in otherwise typical cases.",
      "Pediatric CRS is not simply adult CRS in a smaller nose—age, adenoids and systemic disorders matter.",
      "What history would make CF or PCD evaluation important before escalating surgery?"),

    Q("v136_rhi_22", RHI, "Recurrent Acute Rhinosinusitis",
      "A patient has four discrete, well-documented episodes of acute bacterial rhinosinusitis each year with complete resolution between episodes. What distinguishes this from CRS?",
      ["Symptom-free intervals between separate acute episodes", "Any positive CT finding", "Presence of facial pressure", "Use of antibiotics"], 0,
      "Recurrent acute rhinosinusitis consists of repeated discrete episodes with return to baseline, unlike CRS with persistent symptoms and objective inflammation.",
      "Do not label persistent symptoms as recurrent acute disease; the temporal pattern determines the phenotype.",
      "When should CT be timed to maximize diagnostic value in recurrent acute disease?"),

    Q("v136_rhi_23", RHI, "Revision FESS",
      "A patient has persistent CRS after prior ESS. Before scheduling revision surgery, what is the most important next step?",
      ["Determine why the first treatment failed using endoscopy, CT, operative records, adherence and disease phenotype", "Repeat the exact operation without reviewing anatomy", "Assume scar tissue is always the sole cause", "Stop all topical therapy"], 0,
      "Revision ESS should be hypothesis-driven: residual partitions, lateralized middle turbinate, stenosis, recirculation, persistent inflammatory endotype, odontogenic source and adherence all require different solutions.",
      "A revision operation should correct a defined failure mechanism, not simply repeat surgery because symptoms persist.",
      "What CT/endoscopic finding suggests maxillary recirculation?"),

    Q("v136_rhi_24", RHI, "Septal Deviation",
      "An adult has fixed unilateral nasal obstruction from a marked caudal septal deviation that persists after decongestion. Which treatment most directly addresses the structural cause?",
      ["Septoplasty with technique tailored to the caudal deformity while preserving support", "Antibiotics alone", "Frontal sinusotomy", "Long-term oral decongestants"], 0,
      "Septoplasty is indicated for symptomatic structural obstruction when medical therapy cannot correct the mechanical deviation; caudal work must preserve or reconstruct L-strut support.",
      "The septum is both an airway partition and a structural beam; overresection risks saddle deformity and tip support loss.",
      "How does an internal nasal-valve problem change the operative plan?"),

    Q("v136_rhi_25", RHI, "Sinonasal Malignancy",
      "A patient has unilateral obstruction, recurrent epistaxis and facial numbness. Imaging shows an enhancing sinonasal mass with bone destruction. What is the best next framework?",
      ["Obtain imaging that defines skull-base/orbital extent, establish tissue diagnosis safely, stage the neck/distant disease as appropriate and plan multidisciplinary treatment", "Treat empirically as CRS for months", "Blindly debulk without pathology", "Assume all sinonasal tumors have the same treatment"], 0,
      "Sinonasal malignancies are histologically diverse and treatment depends on pathology, local extent, resectability and potential need for surgery, radiation and systemic therapy.",
      "Cranial neuropathy, unilateral bleeding and destructive imaging are tumor red flags—not routine sinusitis.",
      "How does orbital apex or cavernous-sinus involvement affect resectability and treatment planning?"),

    Q("v136_rhi_26", RHI, "Sphenoidotomy",
      "During sphenoidotomy, which structures make superior and lateral overexpansion potentially catastrophic?",
      ["Optic nerve and internal carotid artery", "Inferior turbinate and lacrimal sac", "Anterior nasal spine and hard palate", "Parotid duct and facial nerve"], 0,
      "The optic nerve and carotid artery may protrude or dehisce into the sphenoid sinus; preoperative CT review of pneumatization and partitions is mandatory.",
      "A sphenoid septum can insert on the carotid canal—do not torque it blindly.",
      "What visual symptom after sphenoid surgery requires immediate evaluation?"),

    Q("v136_rhi_27", RHI, "Systemic Disease of the Nose / Sinuses",
      "A patient has chronic crusting, epistaxis, septal perforation and progressive saddle-nose deformity. What is the best next step before reconstructive surgery?",
      ["Evaluate for systemic inflammatory, infectious, drug-related or neoplastic causes and control active disease first", "Immediate cosmetic reconstruction without etiologic workup", "Treat as simple allergic rhinitis", "Perform turbinectomy"], 0,
      "Destructive nasal disease can reflect GPA, relapsing polychondritis, cocaine injury, infection or malignancy; reconstruction during active disease risks failure.",
      "A septal perforation is a finding, not a diagnosis—identify the destructive process before rebuilding the nose.",
      "Which laboratory and systemic findings would support GPA?"),
]
