"""
v14.6 - Second-case depth closure for Pediatric Otolaryngology,
Thyroid/Parathyroid/Salivary, and Sleep Surgery singleton topics.
"""


def _c(qid,d,t,s,ch,a,e,p,cb,f="boards"):
    return {"id":qid,"domain":d,"topic":t,"stem":s,"choices":ch,"answer":a,
            "explanation":e,"why_wrong":["Correct." if i==a else "This option does not address the key discriminator in the scenario." for i in range(len(ch))],
            "board_pearl":p,"curveball":cb,"tier":"Curated second-pass depth","mode":"Vignette","focus":f}

P="Pediatric Otolaryngology"
T="Thyroid / Parathyroid / Salivary"
S="Sleep Surgery"

VIGNETTES_V146=[
# Pediatrics
_c("v146_ped_01",P,"Ankyloglossia / Maxillary Frenulum","A breastfeeding newborn has a visible lingual frenulum but feeds well, gains weight, and the mother has no nipple pain. What is the best next step?",["Frenotomy solely because a frenulum is visible","Observe; intervene only when functional feeding problems persist despite skilled lactation support","General anesthesia for frenectomy","Stop breastfeeding"],1,"Ankyloglossia is a functional diagnosis, not an anatomic label. Frenotomy is most useful when restricted tongue mobility is clearly linked to persistent breastfeeding dysfunction despite appropriate support.","Treat function, not the photograph.","What findings would make frenotomy more reasonable?","boards"),
_c("v146_ped_02",P,"Cleft / Craniofacial Otologic-Airway Care","A child with cleft palate has recurrent effusions and conductive hearing loss. Why is this population high risk for chronic middle-ear disease?",["Tensor veli palatini dysfunction impairs Eustachian tube opening","The cochlea is always malformed","They universally have cholesteatoma at birth","The facial nerve does not develop"],0,"Cleft palate alters palatal muscle mechanics, especially tensor veli palatini function, causing persistent ET dysfunction and effusion. Hearing surveillance and tympanostomy management are therefore central to longitudinal care.","In cleft care, hearing is a developmental issue, not just an ear-fluid issue.","How does this affect tube strategy over childhood?","boards"),
_c("v146_ped_03",P,"Cleft Lip / Palate — ENT Surgical Fundamentals","During palatoplasty, what functional goal matters beyond simply closing the mucosal defect?",["Reconstruct the levator sling to support velopharyngeal function","Remove the soft palate","Create a permanent palatal fistula","Shorten the palate"],0,"Successful palate repair restores a functional muscular sling and palatal length as well as tissue continuity. Muscle orientation influences speech and velopharyngeal competence.","Palatoplasty is a functional muscle reconstruction, not just hole closure.","How does a postoperative fistula affect speech and feeding?","OR_prep"),
_c("v146_ped_04",P,"Congenital Hearing Loss Genetics","A newborn has bilateral sensorineural hearing loss with no obvious syndromic features. What is the best evaluation principle?",["Genetic evaluation can identify etiology, prognosis, syndromic risks, and recurrence implications","Genetics never changes management","CT alone identifies all causes","Wait until adolescence"],0,"Modern congenital hearing-loss workup integrates audiology, genetics, and selective imaging. Genetic diagnosis can predict progression, associated organ risks, and family recurrence while avoiding unnecessary testing.","Etiology can change surveillance even when it does not change today's audiogram.","What associated evaluations become important if a syndromic diagnosis emerges?","boards"),
_c("v146_ped_05",P,"Croup vs Epiglottitis","A toxic child sits tripod, drools, has muffled voice, and refuses to lie down. What is the safest next step?",["Agitate the child for a detailed throat exam","Keep the child calm and coordinate a controlled airway with ENT/anesthesia while starting appropriate antibiotics","Send home with humidified air","Obtain a throat culture before airway planning"],1,"This presentation is classic for epiglottitis/supraglottitis. Airway deterioration can be sudden, so avoid distressing exams and move to controlled airway management with a prepared difficult-airway team.","Drooling + tripod + toxic appearance is an airway plan, not a bedside-exam challenge.","How does classic viral croup differ in exam and first-line therapy?","overnight_call"),
_c("v146_ped_06",P,"Juvenile Recurrent Parotitis","A 7-year-old has repeated self-limited episodes of unilateral parotid swelling without stones or abscess. What is a reasonable management strategy?",["Supportive care during episodes with hydration, massage, and selective antibiotics; consider sialendoscopy for troublesome recurrences","Total parotidectomy after the first episode","Radiation therapy","Ignore recurrent swelling indefinitely"],0,"Juvenile recurrent parotitis is usually managed conservatively because many children improve with age. Sialendoscopy can be diagnostic/therapeutic in persistent burdensome disease.","The natural history matters: many children outgrow the problem.","What findings would make you suspect an immune deficiency or autoimmune disease instead?","boards"),
_c("v146_ped_07",P,"Lymphatic Malformation","An infant has a soft transilluminating lateral neck mass that rapidly enlarges during a URI but does not compromise the airway. MRI shows a macrocystic lesion. What therapy is often first-line?",["Image-guided sclerotherapy","Immediate radical neck dissection in every case","Antibiotics alone","Radioactive iodine"],0,"Macrocystic lymphatic malformations often respond well to sclerotherapy. Surgery remains important for selected lesions, residual disease, airway compromise, or anatomy poorly suited to percutaneous treatment.","Choose treatment by cyst architecture and functional threat, not by the word 'mass.'","What changes if the lesion suddenly threatens the airway?","overnight_call"),
_c("v146_ped_08",P,"Microtia / Aural Atresia","A child with unilateral microtia and aural atresia has normal hearing in the opposite ear. What should happen before considering canal reconstruction?",["Assess inner-ear function and temporal-bone anatomy, then discuss bone-conduction versus atresiaplasty options","Operate without imaging or hearing testing","Assume the cochlea is normal","Delay all hearing counseling until adulthood"],0,"Management integrates audiology, speech-development needs, CT anatomy when surgical candidacy is being considered, and family goals. Bone-conduction options can bypass the atretic canal.","Atresia surgery is a hearing-rehabilitation decision constrained by temporal-bone anatomy.","Which CT features make atresiaplasty less favorable?","OR_prep"),
_c("v146_ped_09",P,"Microtia Reconstruction","A family asks when to pursue autologous rib-cartilage microtia reconstruction. What most influences timing?",["Adequate costal cartilage size and chest development balanced against psychosocial goals","It must occur in infancy","Age never matters","It should always wait until after 25"],0,"Autologous reconstruction is commonly delayed until enough rib cartilage is available for a durable framework. Porous polyethylene options have different timing and soft-tissue tradeoffs.","Framework material and donor-site maturity drive timing.","How do porous polyethylene and autologous cartilage differ in exposure and donor-site risks?","OR_prep"),
_c("v146_ped_10",P,"Nonobstructive Pediatric Sleep Disorders","A child has daytime sleepiness, normal PSG for OSA, and an irregular sleep schedule with late-night device use. What is the next best step?",["Evaluate sleep duration, circadian habits, insomnia, movement disorders, and central hypersomnolence rather than assuming occult OSA","Adenotonsillectomy automatically","CPAP without diagnosis","Ignore the symptoms"],0,"Not all pediatric sleepiness is obstructive. Sleep hygiene, circadian delay, restless legs, narcolepsy, medications, and insufficient sleep are common alternatives.","A normal AHI does not mean the sleep complaint is imaginary; it means broaden the sleep differential.","What history would make narcolepsy more likely?","boards"),
_c("v146_ped_11",P,"Pediatric Head & Neck Tumors","A child has a rapidly enlarging firm neck mass with constitutional symptoms and no infectious response. What is the best next principle?",["Prompt imaging and tissue diagnosis through a pediatric oncology-aware pathway","Repeated antibiotics for months","Assume branchial cleft cyst","Immediate radical neck dissection without diagnosis"],0,"Pediatric neck masses are often benign, but rapid growth, fixation, B symptoms, neurologic findings, or persistent unexplained adenopathy require malignancy-focused evaluation while minimizing unnecessary open procedures.","In children, common is benign—but red flags still change the lane completely.","How does suspected lymphoma alter the type of tissue sample you want?","boards"),
_c("v146_ped_12",P,"Pediatric Hearing Loss Workup","A 3-year-old has speech delay and inconsistent response to sound. Otoscopy is normal. What is the most important next step?",["Age-appropriate formal audiologic evaluation rather than relying on office response to voice","Wait for school screening","CT before hearing testing","Speech therapy without assessing hearing"],0,"Behavioral audiometry, tympanometry, OAEs, and electrophysiology are chosen by developmental age and cooperation. Hearing status should be established early because auditory deprivation affects speech/language development.","Before labeling speech delay, prove what auditory signal the child is actually receiving.","What if reliable behavioral thresholds cannot be obtained?","boards"),
_c("v146_ped_13",P,"Pediatric Reflux / Eosinophilic Esophagitis","A child has solid-food dysphagia, food impactions, eczema, and feeding avoidance. What diagnosis should be considered beyond reflux?",["Eosinophilic esophagitis","Croup","BPPV","Otitis externa"],0,"EoE often presents with dysphagia, impaction, feeding difficulty, and atopy. Diagnosis requires GI-directed endoscopy with biopsies; empiric acid suppression alone should not delay evaluation when the phenotype fits.","Food impaction plus atopy is an esophageal-biopsy problem until proven otherwise.","How can EoE masquerade as pediatric feeding disorder?","boards"),
_c("v146_ped_14",P,"Pediatric Speech Disorders","A child has normal hearing but persistent hypernasal speech and nasal air escape after cleft-palate repair. What is the best next step?",["Perceptual speech evaluation plus nasoendoscopic or imaging assessment for velopharyngeal insufficiency","Hearing aid fitting","Tonsillectomy solely for speech","Antibiotics"],0,"Speech disorders must be localized: articulation/phonology, resonance, motor speech, and structural velopharyngeal function require different treatments. VPI needs dynamic assessment before surgery.","Do not operate on 'speech delay' until you know which speech mechanism is failing.","Which errors are unlikely to improve with VPI surgery alone?","boards"),
_c("v146_ped_15",P,"Pediatric Vestibular Disorders","A child has recurrent vertigo with headaches, photophobia, motion sensitivity, and normal hearing. What diagnosis belongs high in the differential?",["Vestibular migraine","Otosclerosis","Acute mastoiditis","Isolated conductive hearing loss"],0,"Vestibular migraine is common in pediatric episodic vertigo and can occur without simultaneous headache. History should also consider BPPV, congenital syndromes, infection, medication, and central causes.","In children, migraine biology can present through balance before the history sounds like an adult migraine story.","What neurologic red flags would mandate imaging?","boards"),
_c("v146_ped_16",P,"Pediatric Vocal Fold Immobility","A neonate has biphasic stridor and weak cry. Flexible laryngoscopy shows bilateral vocal-fold immobility. What is the immediate priority?",["Airway stability and evaluation for central/iatrogenic/anatomic causes","Voice therapy only","Observation regardless of work of breathing","Adenoidectomy"],0,"Bilateral immobility can critically narrow the glottic airway. Initial management is driven by respiratory status while the cause is investigated; airway intervention may be required.","With bilateral immobility, the airway problem often outweighs the voice problem.","How does unilateral immobility present differently in an infant?","overnight_call"),
_c("v146_ped_17",P,"Recurrent Tonsillitis Decision-Making","A child has multiple sore throats but documentation is inconsistent and many episodes lack fever, adenopathy, exudate, or positive testing. What is the best next step?",["Use episode quality/documentation and guideline thresholds rather than counting every sore throat as tonsillitis","Tonsillectomy after any two sore throats","Never consider surgery","Antibiotics continuously"],0,"Tonsillectomy decisions for recurrent infection depend on well-characterized episodes and burden, with modifying factors considered when strict counts are not met.","Episode count without episode quality is a weak indication.","Which modifying factors can still support surgery despite imperfect count criteria?","boards"),
_c("v146_ped_18",P,"Thyroglossal Duct Cyst","A child has a midline neck mass that elevates with tongue protrusion. Ultrasound shows a normal thyroid gland. What is definitive treatment after infection has resolved?",["Sistrunk procedure removing the cyst, central hyoid, and tract toward the tongue base","Simple aspiration only","Total thyroidectomy","Radiation"],0,"TGDC follows the embryologic thyroid descent tract. Sistrunk excision reduces recurrence by removing the central hyoid and tract rather than only the cyst.","Embryology explains the operation.","How would acute infection change timing and immediate management?","OR_prep"),
_c("v146_ped_19",P,"Tracheomalacia / Bronchomalacia","An infant has expiratory stridor/wheeze and dynamic airway collapse on bronchoscopy that worsens with agitation. What determines whether surgery is needed?",["Severity of physiologic consequences such as cyanotic spells, recurrent infections, ventilator dependence, or failure to thrive","Noise volume alone","Age alone","Any collapse on bronchoscopy"],0,"Many children improve as cartilage matures, but severe symptomatic tracheobronchomalacia may require airway support, aortopexy/tracheopexy, or treatment of external compression.","Operate on consequences, not on a dramatic bronchoscopy image alone.","How does anterior vascular compression change the operative strategy?","OR_prep"),
_c("v146_ped_20",P,"Velopharyngeal Insufficiency","A child after cleft repair has persistent hypernasality. Endoscopy shows a small central gap with good lateral-wall motion. Why does closure pattern matter?",["It guides procedure selection such as pharyngeal flap versus sphincter-type reconstruction","It has no relevance","It determines hearing aid candidacy","It proves adenoid hypertrophy"],0,"VPI surgery should match the dynamic closure pattern and gap. A procedure that ignores motion can over- or under-correct and may create obstructive sleep apnea.","VPI surgery is dynamic geometry, not generic throat narrowing.","How does preexisting OSA change the risk discussion?","OR_prep"),

# Thyroid/parathyroid/salivary
_c("v146_tps_01",T,"Acute Sialadenitis / Sjögren","An older dehydrated inpatient develops painful swollen parotid gland with purulence from Stensen duct. What is initial management?",["Hydration, sialogogues/massage, oral hygiene, and antibiotics targeting typical bacterial pathogens; drain if abscess forms","Parotidectomy immediately","Radioactive iodine","Steroids alone"],0,"Acute suppurative sialadenitis is commonly related to salivary stasis and ascending bacterial infection. Support flow and treat infection while evaluating for abscess or obstruction.","Stasis + bacteria is the acute sialadenitis model.","What chronic pattern would instead suggest Sjögren syndrome?","overnight_call"),
_c("v146_tps_02",T,"Differentiated Thyroid Cancer: Active Surveillance","A reliable patient under surveillance for a 7-mm low-risk papillary carcinoma now develops a new suspicious lateral neck node. What should happen?",["Reassess with targeted ultrasound/FNA and convert to treatment if nodal metastasis is confirmed","Continue surveillance unchanged because the primary is small","RAI without diagnosis","Ignore the node"],0,"Active surveillance has explicit exit criteria. New nodal disease changes the risk state and generally prompts definitive treatment planning.","Surveillance is active because you act when biology changes.","How does proximity to the RLN or trachea alter surveillance candidacy even without growth?","boards"),
_c("v146_tps_03",T,"Familial Hyperparathyroidism and Parathyromatosis","A young patient with MEN1 has hypercalcemia and multigland enlargement. Why is a focused single-gland operation usually inappropriate?",["Hereditary disease commonly involves multiple glands and needs a syndrome-specific multigland strategy","MEN1 affects only one gland","Localization excludes multigland disease","PTH is unrelated"],0,"MEN syndromes change the prior probability from a solitary adenoma to multigland hyperplasia. Operative planning must account for recurrence, supernumerary glands, thymic tissue, and lifelong surveillance.","Genetics changes the operation before you ever make the incision.","What is parathyromatosis and why is capsular violation important?","OR_prep"),
_c("v146_tps_04",T,"Four-Gland Parathyroid Exploration","Localization is nonconcordant in biochemically proven primary hyperparathyroidism. What is the key operative strategy?",["Systematic bilateral exploration using embryology, RLN relationships, and gland viability rather than chasing one scan","Cancel surgery permanently","Remove the thyroid blindly","Only explore the side with the largest ultrasound gland"],0,"Bilateral exploration remains effective when imaging is nonlocalizing or multigland disease is suspected. The surgeon uses expected locations, migration pathways, and intraoperative physiology to test the hypothesis.","Negative localization is not negative disease.","What do you do if only three glands are found?","OR_prep"),
_c("v146_tps_05",T,"Pleomorphic Adenoma / Warthin Tumor","A mobile superficial parotid mass has FNA consistent with pleomorphic adenoma. Why is simple enucleation discouraged?",["Microscopic pseudopods/satellite nodules make capsular violation and inadequate margin prone to recurrence","Because it is always metastatic","Because the facial nerve must be sacrificed","Because biopsy cures it"],0,"Pleomorphic adenoma has a pseudocapsule with microscopic extensions; formal extracapsular or superficial-parotid technique selected by location reduces recurrence while preserving the facial nerve.","Benign does not mean biologically indifferent to surgical technique.","How does Warthin tumor differ in multiplicity and observation options?","OR_prep"),
_c("v146_tps_06",T,"Radioactive Iodine and TSH Suppression in DTC","A disease-free older patient with prior low-risk DTC has atrial fibrillation and osteoporosis. What should happen to long-term TSH suppression?",["Relax unnecessary aggressive suppression based on current response and competing risks","Maximal suppression forever","Stop thyroid hormone entirely","Give RAI annually"],0,"TSH targets should evolve with response-to-therapy and recurrence risk. In an excellent responder with cardiac/bone risk, chronic intense suppression may cause more harm than benefit.","TSH suppression is a dynamic dose decision, not a tattoo from the initial diagnosis.","How would persistent structural disease change the balance?","boards"),
_c("v146_tps_07",T,"Radioiodine-Refractory Differentiated Thyroid Cancer","A patient has one rapidly growing bone metastasis threatening the spinal cord while the rest of RAI-refractory disease is stable. What is the best principle?",["Use local therapy to the threatening oligoprogressive site while preserving an otherwise effective systemic strategy when appropriate","Repeat RAI despite nonavidity","Wait for paralysis","Total thyroidectomy again"],0,"RAI-refractory disease management depends on tempo and threat. Focal surgery or radiation can control an oligoprogressive critical lesion without automatically changing systemic treatment.","Treat the lesion that is changing the patient's risk, not just the label 'metastatic.'","What findings would trigger systemic kinase-inhibitor therapy?","boards"),
_c("v146_tps_08",T,"Ranula","A child has a bluish fluctuant floor-of-mouth cyst arising from the sublingual space and extending into the neck through the mylohyoid. What is definitive management for a recurrent plunging ranula?",["Address the ipsilateral sublingual gland source, often with excision, rather than repeatedly draining the neck cyst alone","Serial aspiration only forever","Parotidectomy","Thyroidectomy"],0,"Ranulas arise from sublingual gland mucus extravasation. Plunging lesions track around/through mylohyoid; treating only the cervical collection leaves the source and recurrence risk.","The neck component is the reservoir; the sublingual gland is the source.","What nerves and ducts are at risk during transoral sublingual gland excision?","OR_prep"),
_c("v146_tps_09",T,"Reoperative Thyroid Surgery","A patient needs reoperation for recurrent central-neck thyroid cancer. What is the most important preoperative step beyond imaging?",["Document baseline vocal-fold mobility and review the prior operative anatomy","Assume both RLNs are normal","Skip consent about hypoparathyroidism","Avoid reviewing prior pathology"],0,"Reoperative fields have scarred planes and higher RLN/parathyroid risk. Baseline laryngoscopy, prior operative notes, imaging, and clear oncologic targets are essential.","In reoperative endocrine surgery, yesterday's anatomy is part of today's imaging.","How does a preexisting unilateral paralysis change the threshold for contralateral dissection?","OR_prep"),
_c("v146_tps_10",T,"Salivary Adenoid Cystic Carcinoma and Perineural Spread","A patient with minor salivary adenoid cystic carcinoma develops numbness along V2. What is the most important next imaging principle?",["MRI along the entire involved nerve pathway to the skull base","Ultrasound of the thyroid only","No imaging because the primary is small","Bone scan alone"],0,"Adenoid cystic carcinoma has strong perineural tropism. Cranial neuropathy should prompt MRI mapping from the primary toward foraminal and intracranial endpoints, which changes surgery and radiation fields.","For adenoid cystic carcinoma, symptoms can map the tumor's route of travel.","What does extension to foramen rotundum do to surgical planning?","boards"),
_c("v146_tps_11",T,"Secondary / Tertiary Hyperparathyroidism","A dialysis patient has very high PTH and diffuse four-gland hyperplasia despite optimized medical therapy, severe bone pain, and calciphylaxis risk. What surgical concept is appropriate?",["Subtotal parathyroidectomy or total parathyroidectomy with autotransplantation depending on strategy","Focused removal of one localized gland only","Thyroid lobectomy alone","No surgery is ever used"],0,"Renal hyperparathyroidism is typically multigland disease. Refractory severe secondary/tertiary disease requires a planned multigland operation with attention to recurrence and postoperative hungry bone.","Renal HPT is a four-gland physiology problem.","Why is postoperative calcium management especially challenging?","OR_prep"),
_c("v146_tps_12",T,"Submandibular Gland Excision","During submandibular gland excision, which nerve is particularly vulnerable as it loops around Wharton duct in the floor of mouth?",["Lingual nerve","Facial nerve main trunk","Optic nerve","Phrenic nerve"],0,"The lingual nerve passes near and loops around the submandibular duct. The marginal mandibular nerve and hypoglossal nerve are other key structures in the surgical field.","Know the gland by its duct and the three nerves around the operation.","How do you protect the marginal mandibular nerve during the cervical approach?","OR_prep"),
_c("v146_tps_13",T,"Thyroid Eye Disease / Graves Ophthalmopathy","A patient with Graves disease develops proptosis, pain, reduced color vision, and an afferent pupillary defect. What is the priority?",["Urgent evaluation for compressive optic neuropathy with ophthalmology/endocrine coordination","Routine observation only","Thyroidectomy immediately without eye evaluation","Antibiotics alone"],0,"Visual loss, color desaturation, RAPD, or severe exposure can represent sight-threatening thyroid eye disease. Active inflammatory disease and compressive optic neuropathy require urgent specialist treatment.","In thyroid eye disease, vision loss is the emergency—not the cosmetic proptosis.","How does active inflammatory disease affect timing of orbital decompression versus rehabilitative surgery?","overnight_call"),

# Sleep
_c("v146_slp_01",S,"Circadian Rhythm Sleep-Wake Disorders","A teenager cannot fall asleep until 2–3 AM but sleeps normally and feels refreshed when allowed to wake late. What diagnosis best fits?",["Delayed sleep-wake phase disorder","Severe OSA proven","Narcolepsy","Restless legs only"],0,"A stable delayed circadian phase differs from insomnia because sleep quality is normal when aligned with the internal clock. Treatment uses timed light, schedule shifts, and sometimes melatonin rather than airway surgery.","Sleep timing disorders are clock problems, not airway problems.","How should morning light and evening melatonin be timed conceptually?","boards"),
_c("v146_slp_02",S,"Down Syndrome Pediatric HNS","A child with Down syndrome has persistent severe OSA after adenotonsillectomy. What is the next best framework?",["Reassess multilevel obstruction with PSG and often DISE; consider CPAP, lingual tonsil/tongue-base surgery, or HNS in selected patients","Repeat adenotonsillectomy automatically","Ignore residual OSA","Uvulopalatoplasty alone in every child"],0,"Down syndrome commonly has multilevel obstruction from midface, tongue base, lingual tonsils, hypotonia, and obesity. Residual OSA needs phenotype-directed treatment rather than a one-size-fits-all operation.","Persistent pediatric OSA after T&A is an anatomy reassessment problem.","What selection criteria matter for pediatric hypoglossal nerve stimulation?","boards"),
_c("v146_slp_03",S,"Narcolepsy / Central Hypersomnolence Recognition","A young adult has irresistible sleep attacks, sleep paralysis, hypnagogic hallucinations, and emotion-triggered loss of muscle tone. What diagnosis is most likely?",["Narcolepsy with cataplexy","OSA only","Delayed sleep phase only","BPPV"],0,"Cataplexy is highly specific for narcolepsy type 1 in the right context. Evaluation typically includes adequate sleep documentation, overnight PSG, and MSLT.","Cataplexy turns generic sleepiness into a central hypersomnolence workup.","Why must insufficient sleep and untreated OSA be excluded before interpreting MSLT?","boards"),
_c("v146_slp_04",S,"Palatal Surgery","A CPAP-intolerant adult has retropalatal collapse on DISE with minimal tongue-base collapse. What principle supports palatal surgery?",["Procedure selection should match the observed collapse pattern and tissue anatomy","Every OSA patient needs the same palate operation","DISE findings never matter","Palatal surgery treats central sleep apnea"],0,"Palatal procedures alter retropalatal mechanics. Outcomes depend on phenotype and technique; they are less rational when obstruction is predominantly elsewhere.","Match the operation to the collapse site.","What DISE pattern would make isolated palatal surgery less likely to succeed?","OR_prep"),
_c("v146_slp_05",S,"Restless Legs / Periodic Limb Movement Disorders","A patient has an urge to move the legs at night, worse at rest and relieved by movement. What reversible contributor should be checked?",["Iron deficiency/ferritin status","Middle-ear pressure","Thyroid nodule size","Nasal septal angle"],0,"RLS is a sensorimotor disorder with characteristic circadian/rest features. Iron deficiency can contribute and should be corrected when present before escalating pharmacotherapy.","Not every sleep complaint is airway anatomy.","How are periodic limb movements on PSG different from the clinical diagnosis of RLS?","boards"),
_c("v146_slp_06",S,"Tongue Base Surgery","A CPAP-intolerant adult has dominant tongue-base collapse on DISE with a large lingual tonsil. What operative principle is most appropriate?",["Select a tongue-base/lingual-tonsil procedure that targets the observed obstruction while considering swallowing and bleeding risk","Perform isolated septoplasty as definitive OSA therapy","Ignore DISE anatomy","Remove the epiglottis in every case"],0,"Tongue-base surgery should match the mechanism—lingual tonsil hypertrophy, muscular tongue collapse, or epiglottic interaction—and be integrated into a multilevel plan when needed.","Tongue-base surgery is not one operation; it is a family of procedures matched to the collapse mechanism.","How does complete concentric palatal collapse affect HNS candidacy?","OR_prep"),
]
