"""v26.8 — final canonical Sleep Surgery ladder: Oral Appliance Therapy."""
DOMAIN="Sleep Surgery"; TOPIC="Oral Appliance Therapy"
def _q(qid,stage,stem,choices,answer,explanation,reasons,pearl,curveball,focus="boards"):
 return {"id":qid,"domain":DOMAIN,"topic":TOPIC,"learning_stage":stage,"stem":stem,"choices":choices,"answer":answer,"explanation":explanation,"why_wrong":reasons,"board_pearl":pearl,"curveball":curveball,"tier":"Curated learning ladder","mode":"Vignette","focus":focus,"ladder_reviewed":True,"_coverage_reviewed_v211":True}
VIGNETTES_V268=[
_q("v268_sleep_oa_fnd","foundation","What is the usual mechanism of a mandibular-advancement oral appliance used for obstructive sleep apnea?",["Advance/stabilize the mandible and tongue-related upper airway to reduce pharyngeal collapsibility","Deliver continuous positive airway pressure through the teeth","Stimulate the hypoglossal nerve electrically","Treat central apnea by increasing respiratory drive"],0,"A custom titratable mandibular-advancement device treats selected OSA by mechanically advancing/stabilizing the mandible, which can enlarge and stiffen the retrolingual/velopharyngeal airway.",["Correct. Oral appliance therapy is a mechanical upper-airway stabilization strategy.","A mandibular advancement device does not generate PAP pressure.","Electrical hypoglossal stimulation is a different therapy.","Oral appliances do not correct absent central respiratory drive."],"Oral appliance therapy is an anatomic splinting strategy without a mask or implanted stimulator.","Which dental/TMJ features should be assessed before prescribing a mandibular-advancement device?"),
_q("v268_sleep_oa_app","application","A patient with mild-to-moderate OSA is unable to tolerate PAP and prefers a nonoperative option. Dentition is adequate and there is no prohibitive TMJ disease. What is the best treatment pathway?",["Discuss a custom titratable mandibular-advancement appliance fitted by a qualified dental sleep provider and verify efficacy with follow-up sleep testing","Use an over-the-counter sports mouthguard without objective follow-up","Proceed directly to multilevel airway surgery","Treat with nocturnal oxygen alone"],0,"Oral appliance therapy is a reasonable evidence-based alternative for selected adults with OSA who prefer it or cannot tolerate PAP. A custom titratable device, dental oversight, symptom/side-effect follow-up and objective efficacy assessment are important because subjective improvement does not prove control of OSA.",["Correct. Selection, professional fitting/titration and objective reassessment are all part of therapy.","A generic mouthguard is not equivalent to a custom titratable sleep appliance and should not substitute for efficacy testing.","Irreversible surgery is not automatically the next step when an appropriate nonoperative therapy remains available.","Supplemental oxygen may improve saturation but does not reliably relieve pharyngeal obstruction."],"For every OSA therapy, ask both: can the patient use it, and did it actually control the disease?","How would severe baseline hypoxemia or very severe OSA change counseling about relying on an oral appliance alone?","sleep_management"),
_q("v268_sleep_oa_snr","senior_decision","A patient reports dramatic improvement in snoring with a mandibular-advancement device, but follow-up testing shows persistent severe OSA and new morning jaw pain despite further titration. What is the best senior decision?",["Do not equate snoring improvement with adequate OSA treatment; address dental/TMJ toxicity and move to another effective therapy or combined strategy based on residual phenotype","Continue advancing indefinitely despite jaw pain because the snoring improved","Declare the OSA cured from symptoms alone","Add sedatives to improve appliance tolerance without reassessing obstruction"],0,"Oral appliance success requires both tolerability and objective control of the sleep-disordered breathing. Persistent severe residual OSA plus treatment toxicity means the current strategy is inadequate; alternatives may include PAP retrial/troubleshooting, positional or weight-directed therapy, HNS/surgery when appropriately selected, or combination approaches.",["Correct. Objective residual disease and treatment morbidity should trigger strategy reassessment.","Unlimited advancement can worsen occlusal/TMJ morbidity without producing adequate airway benefit.","Snoring is an imperfect surrogate for OSA severity.","Sedation can worsen airway physiology and does not solve documented treatment failure."],"A quieter airway is not necessarily a controlled airway.","Which residual collapse pattern or craniofacial anatomy might favor a different non-PAP surgical strategy such as MMA?","senior_decision"),
]
def apply_learning_ladders_v268(challenges,item_id_fn):
 cid=item_id_fn(DOMAIN,TOPIC)
 if not cid: raise RuntimeError("v268 orphan canonical Oral Appliance Therapy")
 existing={str(q.get("id")) for q in challenges if q.get("id")}; added=0
 for q in VIGNETTES_V268:
  if q["id"] in existing: continue
  row=dict(q); row["concept_id"]=cid; challenges.append(row); existing.add(row["id"]); added+=1
 return {"added":added,"reviewed_topics":1}
