"""v13.8 — canonical coverage closure for Head & Neck Oncology and
Laryngology / Voice / Swallowing. Each case targets an exact missing canonical
topic from the live v13.7 coverage report.
"""


def Q(qid, domain, topic, stem, choices, answer, explanation, pearl, curveball):
    return {
        "id": qid, "domain": domain, "topic": topic, "stem": stem,
        "choices": choices, "answer": answer, "explanation": explanation,
        "why_wrong": ["Compare this option with the decision rule and anatomy described in the explanation." for _ in choices],
        "board_pearl": pearl, "curveball": curveball,
        "tier": "Curated board/call/OR", "mode": "Vignette",
    }

HN = "Head & Neck Oncology"
LAR = "Laryngology / Voice / Swallowing"

VIGNETTES_V138 = [
    # Head & Neck Oncology
    Q("v138_hn_01", HN, "Basal Cell Carcinoma of the Head & Neck",
      "A 7 mm primary nodular BCC on the nasal ala has ill-defined borders in a tissue-critical cosmetic subunit. Which treatment best maximizes margin control and tissue preservation?",
      ["Mohs micrographic surgery", "Observation", "Empiric antibiotics", "Neck dissection"], 0,
      "High-risk facial BCC benefits from complete margin assessment while sparing uninvolved tissue; Mohs is especially useful on the central face and recurrent/ill-defined lesions.",
      "Risk is driven by site, size, borders, recurrence, histology and host factors—not by diameter alone.",
      "How would perineural symptoms change staging and imaging?"),

    Q("v138_hn_02", HN, "Base of Tongue SCC",
      "A nonsmoker has an HPV-associated base-of-tongue SCC with ipsilateral nodal metastasis. What factor must be established because it changes staging and prognosis?",
      ["p16/HPV-associated status", "Serum calcium", "Thyroid uptake scan", "Audiogram only"], 0,
      "HPV-associated oropharyngeal SCC has a distinct staging system and prognosis; treatment is selected by stage, function and multidisciplinary considerations.",
      "Base of tongue is oropharynx, not oral tongue; subsite changes staging and treatment.",
      "What features might make transoral surgery versus definitive chemoradiation reasonable options?"),

    Q("v138_hn_03", HN, "Carotid Body Paraganglioma",
      "A slow-growing painless upper-neck mass splays the internal and external carotid arteries on imaging and is avidly enhancing. What is the most appropriate next step?",
      ["Define cranial-nerve function, vascular anatomy, tumor size and patient factors before choosing observation, radiation or surgery", "Open biopsy in clinic", "Assume metastatic SCC", "Incise and drain"], 0,
      "Carotid body paragangliomas are hypervascular; diagnosis is usually imaging-based and open biopsy can cause major bleeding.",
      "Shamblin relationship to the carotids predicts surgical difficulty and morbidity.",
      "What inherited syndrome or multifocality history should prompt genetic evaluation?"),

    Q("v138_hn_04", HN, "Complications of Neck Surgery",
      "After neck dissection, a patient cannot elevate the shoulder above horizontal and has scapular winging. Which injury is most likely?",
      ["Spinal accessory nerve dysfunction", "Hypoglossal injury", "Lingual nerve injury", "Recurrent laryngeal injury"], 0,
      "CN XI dysfunction causes trapezius weakness, shoulder droop and impaired abduction; early recognition and physical therapy reduce chronic disability.",
      "Post-neck-dissection deficits should be localized anatomically rather than labeled generic postoperative weakness.",
      "Which deficit suggests marginal mandibular nerve injury instead?"),

    Q("v138_hn_05", HN, "Cutaneous Melanoma of the Head & Neck",
      "A thin invasive melanoma of the scalp is excised. Which pathologic measurement most directly drives T category and sentinel-node discussion?",
      ["Breslow depth, with ulceration also important", "Clark level alone", "Tumor color", "Serum TSH"], 0,
      "Melanoma staging relies heavily on Breslow thickness and ulceration; sentinel-node candidacy depends on depth/risk features and patient context.",
      "Head-and-neck lymphatic drainage is complex, so preoperative mapping is especially valuable.",
      "How does a positive sentinel node change regional management discussion?"),

    Q("v138_hn_06", HN, "Floor of Mouth SCC",
      "A floor-of-mouth SCC approaches the mandible but CT shows no cortical invasion. What principle should guide mandibular resection?",
      ["Preserve the mandible when oncologically safe; marginal versus segmental resection depends on true bone invasion and achievable margins", "Segmental mandibulectomy for every floor-of-mouth cancer", "No neck management is ever needed", "Treat as laryngeal cancer"], 0,
      "Mandibular sacrifice should match actual invasion and margin requirements; unnecessary segmental resection adds major functional morbidity.",
      "Oral-cavity surgery is a three-dimensional margin and function problem, not a fixed operation by subsite.",
      "How does clinically positive nodal disease change neck management?"),

    Q("v138_hn_07", HN, "Free-Flap Monitoring / Compromise / Salvage",
      "Six hours after free-flap reconstruction, the flap becomes tense and blue with brisk dark pinprick bleeding. What is the best action?",
      ["Treat as venous congestion and urgently evaluate for pedicle compromise, with prompt takeback when indicated", "Wait until morning", "Apply ice", "Assume arterial thrombosis because the flap is blue"], 0,
      "Venous compromise causes congestion, dark bleeding and swelling; salvage success falls with delay, making rapid recognition and reexploration critical.",
      "A failing flap is an emergency measured in hours.",
      "How does an arterial-compromised flap look different?"),

    Q("v138_hn_08", HN, "Glottic Cancer",
      "A small T1 glottic SCC is confined to one true vocal fold with normal mobility. Which treatments can both be oncologically appropriate?",
      ["Transoral laser microsurgery or definitive radiation", "Total laryngectomy only", "Chemotherapy alone", "Observation"], 0,
      "Early glottic cancer is commonly treated with single-modality transoral surgery or radiation, selected by anatomy, voice goals, exposure and patient preference.",
      "Early glottic cancer has low occult nodal risk because true vocal folds have sparse lymphatics.",
      "How does impaired vocal-fold mobility change T category and treatment considerations?"),

    Q("v138_hn_09", HN, "Head & Neck Cancer Surveillance / Second Primaries",
      "A patient is disease-free 2 years after treatment for tobacco-associated oral cavity SCC. What surveillance principle remains important?",
      ["Continue focused recurrence surveillance while addressing tobacco/alcohol use, functional late effects and risk of second primary malignancy", "Stop all follow-up after the first negative scan", "Use PET/CT monthly indefinitely", "Ignore new pulmonary symptoms"], 0,
      "Survivorship includes recurrence detection, second-primary risk, nutrition, dental, swallowing, speech, endocrine and psychosocial effects.",
      "Surveillance is not just imaging; symptoms and treatment toxicities matter.",
      "What new symptom should prompt evaluation for a second primary lung malignancy?"),

    Q("v138_hn_10", HN, "Head & Neck Radiation Toxicity / Survivorship",
      "Years after neck radiation, a patient has progressive dysphagia, xerostomia, neck fibrosis and elevated TSH. What is the best framework?",
      ["Recognize these as late treatment effects requiring multidisciplinary survivorship management", "Assume recurrent cancer explains every symptom", "No intervention is possible", "Perform total laryngectomy automatically"], 0,
      "Radiation can cause salivary dysfunction, fibrosis, dysphagia, dental disease, hypothyroidism, carotid disease and osteoradionecrosis; survivorship requires proactive screening and rehabilitation.",
      "Cancer cure does not end ENT care; late toxicities can emerge years later.",
      "Which dental precaution matters before invasive procedures in a heavily irradiated mandible?"),

    Q("v138_hn_11", HN, "Hypopharyngeal Cancer",
      "A patient has pyriform-sinus SCC with significant nodal disease and impaired swallowing. What feature is characteristic of hypopharyngeal cancer?",
      ["It often presents late with substantial nodal burden and requires explicit functional as well as oncologic planning", "It almost never metastasizes to the neck", "It is usually cured by local excision alone", "HPV status determines all staging"], 0,
      "Hypopharyngeal cancers often present at advanced stage and treatment must balance organ preservation with whether the organ will remain functional.",
      "An anatomically preserved larynx is not necessarily a functional larynx.",
      "What findings would favor primary laryngopharyngectomy over organ-preservation therapy?"),

    Q("v138_hn_12", HN, "Merkel Cell Carcinoma",
      "An older immunosuppressed patient has a rapidly enlarging painless violaceous cheek nodule diagnosed as Merkel cell carcinoma. What principle is appropriate?",
      ["Treat as an aggressive neuroendocrine skin cancer with wide/local control plus regional nodal staging and multidisciplinary adjuvant consideration", "Treat like a benign cyst", "No nodal evaluation is needed", "Antibiotics alone"], 0,
      "Merkel cell carcinoma has high regional and distant metastatic risk; sentinel-node staging and radiation/systemic considerations are common.",
      "A small skin lesion can carry disproportionate oncologic risk in Merkel cell carcinoma.",
      "How does clinically node-positive disease alter management?"),

    Q("v138_hn_13", HN, "Neck Lymphoma",
      "A patient has rapidly enlarging bilateral cervical nodes, B symptoms and no mucosal primary. What tissue strategy is preferred?",
      ["Obtain adequate tissue architecture for lymphoma classification, often core or excisional biopsy with flow studies", "FNA cytology alone always provides complete subclassification", "Neck dissection is definitive therapy", "Empiric radiation before diagnosis"], 0,
      "Lymphoma requires lineage and architecture; avoid an oncologic neck dissection for a disease primarily treated systemically.",
      "When lymphoma is plausible, plan the biopsy around what pathology needs—not merely the easiest needle target.",
      "How does airway compromise from bulky disease change urgency?"),

    Q("v138_hn_14", HN, "Neck Management by Primary Site",
      "Why can a clinically N0 oral tongue SCC still require elective neck treatment?",
      ["Occult nodal risk is substantial enough in selected tumors that elective neck dissection or radiation improves regional control", "Oral tongue never drains to cervical nodes", "Neck treatment depends only on patient age", "Sentinel nodes do not exist in oral cancer"], 0,
      "Elective neck management is based on subsite-specific lymphatic risk, depth of invasion and tumor factors; different primaries drain to different levels.",
      "The neck operation follows the primary site and expected drainage pattern.",
      "How does depth of invasion influence elective neck treatment in oral tongue SCC?"),

    Q("v138_hn_15", HN, "Nonfunctional Larynx / Chronic Aspiration After Cancer Therapy",
      "A disease-free patient years after chemoradiation has recurrent aspiration pneumonias, feeding-tube dependence and a fibrotic but anatomically intact larynx. What should guide discussion?",
      ["Functional salvage options including aspiration-prevention surgery or total laryngectomy when rehabilitation has failed", "Cancer surveillance alone because the larynx is anatomically present", "Repeated antibiotics indefinitely", "No surgical option exists without recurrent cancer"], 0,
      "A chronically aspirating nonfunctional larynx can be life-threatening even without cancer recurrence; definitive separation of airway and alimentary tract may restore oral intake and reduce pneumonias.",
      "Organ preservation is only a success when the preserved organ remains safe and functional.",
      "What quality-of-life tradeoffs accompany functional laryngectomy?"),

    Q("v138_hn_16", HN, "Open Partial / Conservation Laryngectomy",
      "Which patient characteristic is essential before considering open partial laryngectomy?",
      ["Tumor extent compatible with preservation plus adequate pulmonary reserve and ability to rehabilitate swallowing", "Bilateral cricoarytenoid fixation", "Extensive subglottic invasion", "Inability to protect the airway"], 0,
      "Conservation laryngeal surgery requires both oncologic suitability and enough remaining function for airway protection, voice and swallowing.",
      "The contraindication is often functional as much as anatomic.",
      "Why does arytenoid function matter after supracricoid procedures?"),

    Q("v138_hn_17", HN, "Palliative / Goals-of-Care Decision-Making in Head & Neck Cancer",
      "A frail patient with incurable recurrent HNSCC has bleeding, pain and dysphagia. What is the best management framework?",
      ["Clarify goals and prognosis while offering symptom-directed local/systemic therapy and palliative care concurrently", "Offer maximal surgery regardless of goals", "Avoid discussing prognosis", "Stop all symptom treatment"], 0,
      "Palliative care can coexist with tumor-directed therapy; decisions should align treatment burden with goals, expected benefit, function and symptom relief.",
      "A technically possible operation is not automatically a patient-centered operation.",
      "How would a sentinel bleed from tumor near the carotid change urgent planning?"),

    Q("v138_hn_18", HN, "Parapharyngeal Space Tumor",
      "A prestyloid parapharyngeal mass displaces the carotid space posteriorly and has fat-plane continuity with the deep parotid lobe. What tumor class is favored?",
      ["Deep-lobe salivary tumor such as pleomorphic adenoma", "Carotid body paraganglioma", "Vagal schwannoma", "Glottic SCC"], 0,
      "Parapharyngeal tumors are localized by prestyloid versus poststyloid compartment and vessel displacement; this narrows the differential and guides surgical approach.",
      "In the PPS, vessel displacement is a diagnostic anatomy lesson.",
      "How would a poststyloid mass displacing the internal carotid anteriorly change the differential?"),

    Q("v138_hn_19", HN, "Radiation Therapy Principles for Head & Neck Surgeons",
      "Why does concurrent cisplatin increase the effectiveness of definitive radiation for selected locally advanced HNSCC?",
      ["It acts as a radiosensitizer and improves locoregional control at the cost of added toxicity", "It prevents all mucositis", "It replaces the need for staging", "It protects hearing"], 0,
      "Head-and-neck surgeons should understand definitive versus adjuvant radiation, radiosensitization, dose-limiting organs and acute/late toxicities to counsel patients intelligently.",
      "Surgery and radiation decisions are coupled; adverse pathology can change postoperative treatment intensity.",
      "Which pathologic findings classically support postoperative chemoradiation rather than radiation alone?"),

    Q("v138_hn_20", HN, "Reconstruction Selection After Head & Neck Ablation",
      "After segmental mandibulectomy with a large oral soft-tissue defect, which reconstructive option best restores bone continuity and provides soft tissue?",
      ["Osteocutaneous free flap such as fibula when patient and defect are appropriate", "Skin graft alone", "Local mucosal advancement only", "No reconstruction"], 0,
      "Reconstruction is selected by missing components—lining, skin, bulk, bone, tendon—and by functional goals and patient factors.",
      "Choose the flap from the defect backward, not from surgeon habit forward.",
      "When might a scapular system be preferable to fibula?"),

    Q("v138_hn_21", HN, "Recurrent / Metastatic HNSCC",
      "A patient develops unresectable recurrent HNSCC after prior chemoradiation. What should guide systemic treatment selection?",
      ["Performance status, PD-L1/biomarkers, symptoms, prior therapy, disease tempo and goals", "Primary-site surgery regardless of resectability", "RAI", "Observation in all patients"], 0,
      "Recurrent/metastatic HNSCC management is individualized among immunotherapy, chemotherapy combinations, local palliation and supportive care.",
      "Systemic therapy is chosen from biology plus patient fitness plus treatment goals.",
      "How can oligometastatic or oligoprogressive disease alter the role of local therapy?"),

    Q("v138_hn_22", HN, "Systemic Therapy Foundations in Head & Neck Cancer",
      "Which statement best distinguishes neoadjuvant, concurrent and adjuvant systemic therapy?",
      ["Timing relative to local therapy differs, and concurrent therapy may function as radiosensitization", "They are interchangeable labels", "Systemic therapy never affects radiation", "Adjuvant therapy precedes surgery by definition"], 0,
      "ENT surgeons should understand why systemic agents are given, when they are given and how toxicity affects surgical recovery and salvage options.",
      "Know treatment intent and timing even when medical oncology prescribes the drug.",
      "Why do renal function and hearing status matter before cisplatin?"),

    Q("v138_hn_23", HN, "TEP and Alaryngeal Speech",
      "After total laryngectomy, a patient wants the most fluent pulmonary-powered alaryngeal voice option. What rehabilitation is commonly considered?",
      ["Tracheoesophageal puncture with voice prosthesis", "Whispering only", "Cochlear implantation", "Nasal valve surgery"], 0,
      "TEP redirects pulmonary air through a prosthesis into the pharyngoesophageal segment to generate voice; electrolarynx and esophageal speech are alternatives.",
      "Laryngectomy counseling should include speech rehabilitation before the operation, not after loss of voice occurs.",
      "What causes leakage through versus around a TEP prosthesis?"),

    Q("v138_hn_24", HN, "Tonsil SCC",
      "A patient has an HPV-associated tonsillar SCC and a small mobile ipsilateral level II node. Which principle is correct?",
      ["Oropharyngeal staging and treatment should incorporate HPV status and can include transoral surgery with neck management or definitive radiation-based therapy", "Treat as oral cavity cancer", "No neck treatment is needed", "HPV status has no prognostic relevance"], 0,
      "Tonsil SCC is oropharyngeal disease with HPV-specific staging; both surgical and nonsurgical definitive strategies may be appropriate in selected patients.",
      "Do not confuse tonsillar pillar/oropharynx with retromolar trigone/oral cavity.",
      "Which pathology after transoral surgery would intensify adjuvant therapy?"),

    Q("v138_hn_25", HN, "Total Laryngectomy",
      "During total laryngectomy, what fundamental anatomic change must the patient understand preoperatively?",
      ["The airway is permanently separated from the mouth/nose and breathing occurs through a neck stoma", "Normal nasal breathing continues", "Aspiration remains possible from food entering the trachea", "Natural laryngeal voice is preserved"], 0,
      "Total laryngectomy permanently separates respiratory and digestive tracts, eliminating laryngeal voice and aspiration through the native larynx but requiring lifelong stoma care.",
      "A laryngectomee cannot be orally or nasally intubated—emergency oxygenation goes through the stoma.",
      "What postoperative signs suggest pharyngocutaneous fistula?"),

    Q("v138_hn_26", HN, "Tracheal Malignancy",
      "A patient has an adenoid cystic carcinoma of the upper trachea without distant metastasis. Which principle is most important for surgical planning?",
      ["Define longitudinal extent and resectability because safe tracheal resection is limited by achievable tension-free anastomosis", "Perform unlimited-length tracheal resection", "Ignore recurrent laryngeal nerves", "Treat as thyroid cancer"], 0,
      "Primary tracheal tumors are uncommon; resection depends on length, location, invasion and ability to reconstruct without excessive anastomotic tension.",
      "Tracheal surgery is as much an anastomotic-tension problem as an oncologic-margin problem.",
      "What postoperative maneuver reduces tension on a cervical tracheal anastomosis?"),

    Q("v138_hn_27", HN, "Transoral Laser Microsurgery for Laryngeal Cancer",
      "A patient with a well-exposed early glottic cancer is considering transoral laser microsurgery. What is a major advantage?",
      ["Single-modality organ-preserving treatment with pathologic margin assessment and short treatment course", "No possibility of voice change", "No need for surgical exposure", "It is appropriate for every T4 tumor"], 0,
      "TLM can provide excellent control for selected early laryngeal tumors while preserving future treatment options, but exposure, depth and functional consequences matter.",
      "Good transoral exposure is a prerequisite, not an afterthought.",
      "How does anterior commissure involvement complicate margin assessment and recurrence risk?"),

    Q("v138_hn_28", HN, "Tumor Immunology / Immunotherapy in HNSCC",
      "A patient with recurrent/metastatic HNSCC is being considered for checkpoint inhibition. What biologic concept underlies this therapy?",
      ["Blocking inhibitory immune checkpoints can restore antitumor T-cell activity", "It directly ablates tumor with ionizing radiation", "It works only by suppressing all T cells", "It is a form of RAI"], 0,
      "Checkpoint inhibitors target pathways such as PD-1/PD-L1 that tumors exploit to evade immune surveillance; response and toxicity differ from cytotoxic chemotherapy.",
      "Immune-related adverse events can affect nearly any organ and require early recognition.",
      "What clinical toxicity would make you suspect immune-mediated pneumonitis?"),

    # Laryngology / Voice / Swallowing
    Q("v138_lar_01", LAR, "Acute / Chronic Laryngopharyngitis",
      "A professional voice user has 5 days of hoarseness after URI without airway symptoms or red flags. What is the best initial approach?",
      ["Voice conservation, hydration and observation; avoid routine antibiotics or steroids without a specific indication", "Immediate microlaryngoscopic biopsy", "Empiric antifungals", "Total voice rest for months"], 0,
      "Most acute laryngitis is viral/self-limited; persistent dysphonia or red flags require laryngeal visualization.",
      "Do not treat a symptom with antibiotics when the syndrome is viral and the larynx has not shown a bacterial target.",
      "What duration or red-flag history should prompt earlier laryngoscopy?"),

    Q("v138_lar_02", LAR, "Arytenoid Adduction / Reinnervation",
      "A patient has chronic unilateral vocal-fold paralysis with a large posterior glottic gap and vertical height mismatch. Which adjunct can improve closure when medialization alone is insufficient?",
      ["Arytenoid adduction", "Posterior cordotomy", "Bilateral botulinum toxin", "Adenoidectomy"], 0,
      "Arytenoid adduction rotates the vocal process medially and can correct posterior gap/height mismatch; reinnervation restores tone over time in selected patients.",
      "Choose the procedure for the geometry of glottic insufficiency, not simply the diagnosis of paralysis.",
      "When is ansa-to-RLN reinnervation especially attractive?"),

    Q("v138_lar_03", LAR, "Aspiration-Prevention Surgery",
      "A neurologically devastated patient has life-threatening aspiration despite maximal rehabilitation and no realistic chance of functional laryngeal recovery. What is the goal of aspiration-prevention surgery?",
      ["Separate or close the airway from the alimentary tract to prevent pulmonary contamination, accepting voice tradeoffs", "Improve nasal airflow", "Restore cochlear hearing", "Treat reflux only"], 0,
      "Procedures such as laryngotracheal separation or functional laryngectomy prioritize pulmonary protection when aspiration is otherwise intractable.",
      "The endpoint is survival and pulmonary safety, not preservation of every laryngeal function.",
      "What counseling is required regarding communication after airway-separating surgery?"),

    Q("v138_lar_04", LAR, "Chronic Cough / Laryngeal Hypersensitivity",
      "A patient has chronic cough after negative pulmonary workup, no ACE inhibitor, controlled reflux/asthma, and cough triggered by talking and odors with laryngeal paresthesia. What treatment is reasonable?",
      ["Behavioral cough-suppression therapy with treatment of contributing laryngeal hypersensitivity; neuromodulation may help selected patients", "Antibiotics indefinitely", "Tracheostomy", "Ignore triggers"], 0,
      "Chronic cough can persist as a hypersensitivity/neurogenic syndrome after common causes are addressed; speech-language therapy and selected neuromodulators can reduce symptoms.",
      "Chronic cough is a diagnosis of mechanism after dangerous/common causes are excluded—not a synonym for reflux.",
      "What history would make an ACE inhibitor or eosinophilic airway disease more likely?"),

    Q("v138_lar_05", LAR, "Esophageal Disease for the Otolaryngologist",
      "A patient reports progressive solid-food dysphagia and weight loss. What is the most appropriate next step?",
      ["Urgent structural evaluation of the esophagus with endoscopy/imaging as appropriate rather than empiric reflux treatment alone", "Reassure without workup", "Voice therapy only", "Treat as BPPV"], 0,
      "Progressive dysphagia and weight loss are alarm features for structural or malignant esophageal disease.",
      "ENT dysphagia evaluation must distinguish oropharyngeal transfer problems from esophageal obstruction.",
      "How does dysphagia to solids and liquids from onset shift the differential toward motility disease?"),

    Q("v138_lar_06", LAR, "FEES",
      "What is a major advantage of FEES over a modified barium swallow?",
      ["Bedside repeatable assessment of secretion management, laryngeal sensation and real foods without radiation", "Direct visualization during the exact moment of the swallow without white-out", "Complete esophageal evaluation", "Measurement of vocal-fold vibration"], 0,
      "FEES excels at secretion, airway protection and repeated bedside assessment, but the pharyngeal swallow is briefly obscured by white-out.",
      "Choose FEES versus MBS based on the clinical question; neither is universally superior.",
      "Which finding on FEES suggests impaired sensation and higher aspiration risk?"),

    Q("v138_lar_07", LAR, "Injection Laryngoplasty",
      "A patient has acute unilateral vocal-fold paralysis after surgery with severe breathy dysphonia and aspiration but uncertain nerve recovery. What intervention can temporarily improve closure?",
      ["Injection laryngoplasty with a temporary material", "Permanent bilateral cordotomy", "Total laryngectomy", "No treatment until 12 months"], 0,
      "Early temporary injection can improve voice, cough and swallowing while awaiting neural recovery and does not preclude later definitive procedures.",
      "Do not force a patient to aspirate for months simply because nerve recovery is uncertain.",
      "How does injection target placement differ for atrophy versus paralysis?"),

    Q("v138_lar_08", LAR, "Laryngeal Anatomy",
      "Which membrane forms the inferior fibroelastic framework and has a free superior edge that becomes the vocal ligament?",
      ["Conus elasticus", "Quadrangular membrane", "Thyrohyoid membrane", "Cricotracheal ligament"], 0,
      "The conus elasticus extends superiorly to form the vocal ligament; the quadrangular membrane contributes to the vestibular fold and aryepiglottic fold.",
      "Boards repeatedly test the larynx as connected spaces and membranes because tumor and edema spread along them.",
      "What spaces lie lateral to the ventricle and influence transglottic tumor spread?"),

    Q("v138_lar_09", LAR, "Leukoplakia / Laryngeal Dysplasia",
      "A smoker has persistent unilateral vocal-fold leukoplakia with irregular vascularity and impaired mucosal wave. What is the best next step?",
      ["Microlaryngoscopic evaluation with biopsy/excision tailored to oncologic suspicion and voice preservation", "Assume benign keratosis forever", "Antibiotics only", "No follow-up"], 0,
      "Leukoplakia is a visual descriptor spanning benign keratosis to invasive cancer; suspicious morphology and functional changes require tissue diagnosis.",
      "Treat the lesion, but preserve as much layered vocal-fold microstructure as oncologically safe.",
      "How does high-grade dysplasia change surveillance and treatment intensity?"),

    Q("v138_lar_10", LAR, "Medialization Thyroplasty",
      "A patient has stable unilateral vocal-fold paralysis 18 months after nerve injury with a persistent glottic gap. Which durable framework procedure is appropriate?",
      ["Type I medialization thyroplasty, with arytenoid adduction if posterior gap/height mismatch warrants", "Posterior cordotomy", "Tracheostomy only", "Bilateral vocal-fold stripping"], 0,
      "Medialization thyroplasty provides adjustable permanent glottic closure for stable unilateral insufficiency while preserving the mucosa.",
      "Framework surgery changes position; reinnervation changes tone; injection changes bulk.",
      "Why is intraoperative voice assessment useful in awake thyroplasty?"),

    Q("v138_lar_11", LAR, "Microlaryngoscopy",
      "During suspension microlaryngoscopy, what safety concern must be addressed before laser use?",
      ["Laser-safe airway strategy, low inspired oxygen when feasible, eye protection and team fire precautions", "Increase oxygen to 100% routinely", "Use flammable pledgets", "Ignore dental protection"], 0,
      "Microlaryngoscopy requires careful exposure, dental protection and coordinated airway/laser fire safety.",
      "A laryngeal laser case is a shared airway case; surgeon and anesthesia plan together.",
      "What immediate steps are taken if an airway fire occurs?"),

    Q("v138_lar_12", LAR, "Modified Barium Swallow",
      "A patient coughs with thin liquids after stroke. What does a modified barium swallow add?",
      ["Dynamic fluoroscopic assessment of oral and pharyngeal bolus flow, aspiration timing and compensatory strategies", "Direct mucosal biopsy", "Long-term esophageal pH measurement", "Vocal-fold mucosal wave analysis"], 0,
      "MBS visualizes bolus transit and timing across consistencies and can test maneuvers in real time; it complements rather than duplicates FEES.",
      "Ask whether aspiration occurs before, during or after the swallow—the mechanism determines rehabilitation.",
      "What pattern suggests impaired upper-esophageal-sphincter opening?"),

    Q("v138_lar_13", LAR, "Posterior Cordotomy / Arytenoidectomy",
      "A patient with stable bilateral vocal-fold immobility has a tracheostomy and wants decannulation, accepting a weaker voice. What procedure can enlarge the posterior glottic airway?",
      ["Posterior cordotomy with or without partial arytenoidectomy", "Medialization thyroplasty", "Bilateral injection augmentation", "TEP"], 0,
      "Posterior glottic-widening procedures trade voice quality and sometimes swallowing protection for airway; counseling must make that trade explicit.",
      "For bilateral immobility, airway and voice goals point in opposite directions.",
      "How would potentially recoverable recent bilateral paresis change timing?"),

    Q("v138_lar_14", LAR, "Professional Voice",
      "A singer with subtle loss of upper range has a normal speaking voice and nearly normal routine laryngoscopy. What is the best next assessment?",
      ["Videostroboscopy with voice-specialist evaluation", "Reassurance based only on conversational voice", "CT neck as the first test", "Antibiotics"], 0,
      "Professional voice complaints can reflect subtle vibratory lesions or technique problems that are invisible on routine exam; stroboscopy and task-specific assessment are high yield.",
      "For professional voice users, small physiologic changes can have large occupational consequences.",
      "How does management differ if a small hemorrhagic polyp is found just before a performance?"),

    Q("v138_lar_15", LAR, "Radiation-Associated Dysphagia",
      "A head-and-neck cancer survivor develops progressive late dysphagia years after radiation with reduced tongue-base retraction and pharyngeal fibrosis. What is the best framework?",
      ["Instrumental swallow assessment and targeted rehabilitation while evaluating stricture, aspiration and cranial neuropathy", "Assume symptoms are untreatable", "Antibiotics", "Nasal surgery"], 0,
      "Late radiation dysphagia is often multifactorial from fibrosis, weakness, neuropathy and stenosis; management requires mechanism-specific therapy.",
      "Late radiation injury can progress long after cancer treatment ends.",
      "When does intractable aspiration justify discussion of aspiration-prevention surgery?"),

    Q("v138_lar_16", LAR, "Stroboscopy Interpretation",
      "A vocal-fold cyst produces a focal region with absent mucosal wave while the opposite fold remains pliable. What does this suggest?",
      ["A subepithelial lesion tethering the cover and disrupting normal vibration", "Normal vibration", "Bilateral vocal-fold paralysis", "Pure hearing loss"], 0,
      "Stroboscopy evaluates periodicity, symmetry, amplitude, closure and mucosal wave; focal wave loss suggests stiffness from lesion, scar or malignancy.",
      "Stroboscopy is a biomechanics test, not simply a prettier laryngoscopy.",
      "What limitation makes stroboscopy less reliable with severely irregular aperiodic phonation?"),

    Q("v138_lar_17", LAR, "Tracheobronchial Endoscopy Principles",
      "A child has suspected airway foreign body with unilateral hyperinflation. What endoscopic tool is typically preferred for definitive removal?",
      ["Rigid bronchoscopy with appropriate ventilation and optical forceps", "Flexible nasopharyngoscopy only", "Esophagoscopy", "No endoscopy"], 0,
      "Rigid bronchoscopy provides airway control, ventilation and working channels for pediatric foreign-body extraction; flexible bronchoscopy may be diagnostic or useful in selected contexts.",
      "Bronchoscopy is both an airway and foreign-body operation—equipment and anesthesia planning are inseparable.",
      "What should be done if the object fragments and migrates distally?"),

    Q("v138_lar_18", LAR, "Transnasal Esophagoscopy",
      "Which patient is a good candidate for office transnasal esophagoscopy?",
      ["A stable cooperative patient needing unsedated evaluation of pharyngoesophageal mucosa or selected dysphagia/reflux questions", "A patient with complete airway obstruction", "A child with button battery lodged in the esophagus", "Any unstable GI bleed"], 0,
      "TNE can evaluate the esophagus without general anesthesia or IV sedation in selected patients but is not a substitute for emergent rigid endoscopy when airway or sharp/caustic foreign-body risk exists.",
      "Office convenience never overrides acuity or the need for airway control.",
      "What findings on TNE would require formal GI endoscopy and biopsy planning?"),

    Q("v138_lar_19", LAR, "Vocal Fold Nodules",
      "A teacher has bilateral symmetric mid-membranous vocal-fold lesions with an hourglass closure pattern. What is first-line treatment?",
      ["Voice therapy and vocal-behavior modification", "Immediate bilateral cordectomy", "Radiation", "Tracheostomy"], 0,
      "Classic nodules are phonotraumatic and usually respond to behavioral voice therapy; surgery is reserved for selected refractory/atypical lesions.",
      "Bilateral symmetric lesions at the striking zone should make you ask how the voice is being used.",
      "Which finding would make you reconsider the diagnosis and pursue biopsy?"),

    Q("v138_lar_20", LAR, "Vocal Tremor",
      "An older patient has rhythmic oscillation of the palate, pharynx and larynx during sustained phonation. Which diagnosis is favored over spasmodic dysphonia?",
      ["Essential/voice tremor", "Adductor spasmodic dysphonia", "Unilateral paralysis", "Vocal-fold cyst"], 0,
      "Vocal tremor is rhythmic and can involve multiple subsites, whereas spasmodic dysphonia produces task-specific irregular spasms.",
      "Listen for rhythm and look beyond the true vocal folds when distinguishing tremor from dystonia.",
      "What treatments can be considered when tremor is functionally limiting?"),
]
